### ISSUE TITLE
Add option to consider no tests ran a failure

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1000]

**Comment by natebosch** [comment]
Does it need to be an option? I'd be fine starting with this always being the case, and if we make it an option I think the default should be to fail on no tests

**Comment by matanlurey** [comment]
+1 Always. I think the number of libraries where _all_ tests will be skipped are pretty small...

**Comment by jakemac53** [comment]
One thing I was thinking about is if/when we run only affected tests then having it on by default would not necessarily be what you want. We could handle that scenario specifically though, and are a ways off from it anyways.

**Comment by jakemac53** [comment]
This is really a test package feature, closing
