### ISSUE TITLE
Add "analyze" command

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1001]
... to replace manual usage of `dartanalyzer`, and to re-use incremental builds/summaries.

**Comment by natebosch** [comment]
definitely curious what kind of performance we could see with this.

**Comment by matanlurey** [comment]
I imagine its not *too* important, since most packages are smaller, but interesting :)

**Comment by jakemac53** [comment]
Thinking about this it might actually be more complicated than you would think. We might not even typically compute summaries for many things for instance (if they aren't imported by an entrypoint), so we would have to run a build which might end up being pretty expensive.

**Comment by natebosch** [comment]
We could potentially model the analyzer as a builder that goes from `.dart` to `.dart.analysis_errors`. Depending on whether and how we look at deeper integration with tests some of the work there could benefit this.

It's not something we'll look at soon, but it will be good to have this in mind as we look at future possibilities

**Comment by MichaelRFairhurst** [comment]
@devoncarew mentioned that there may already be some tools that do this (I want to say one was called dart fix?) by running the analysis_server, and it may be better to encourage using that than to create a new API which may differ in unexpected ways and/or require maintenance etc

**Comment by devoncarew** [comment]
There are a few CLI tools that use the analysis server for analysis - `dart2_fix`, `tuneup`, and `flutter analyze`.

There is a bunch of post-processing that the dartanalyzer and the analysis server do to the reported issues - things like changing the severity off errors: https://www.dartlang.org/guides/language/analysis-options#changing-the-severity-of-analysis-rules. I would be leery of having a user facing tool reporting errors that either didn't have the same logic as other analysis tools, or duplicated the logic, and could potentially get out of date.

A wrapper around the analysis server is pretty easy to write and guarantees that you'll see the same analysis as what people see in other tools.

**Comment by alorenzen** [comment]
We're basically looking for a web equivalent of `flutter analyze`, which takes into account the results of a build.

If that ends up being a simple wrapper around analysis server, that's fine by me.

In that case, is there anything to do on the `build_runner` side, or is this just a request for `webdev` now?

**Comment by alorenzen** [comment]
It looks like the `flutter analyze` command actually calculates a list of directories[1] to send to the analysis server. That's probably something that we'd want `build_runner` to handle, and not `webdev`?

[1] https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze_once.dart#L91

**Comment by natebosch** [comment]
> A wrapper around the analysis server is pretty easy to write and guarantees that you'll see the same analysis as what people see in other tools.

Our most likely design would be a wrapper around `dartanalyzer` which sets up a directory with the merged result of a build and invokes the cli there.

**Comment by devoncarew** [comment]
Flutter passes in directories mostly to be targeted about what it analyzes in the flutter repo itself (there are 29 dart packages in there). For a user's app, it just uses the main project directory.

Building on the analysis server gets you performance benefits for the 2nd and later runs, which is one of the reasons we moved away from a combo package:analyzer / dartanalyzer solution to an analysis server based one.

**Comment by jakemac53** [comment]
Closing this as not planned
