### ISSUE TITLE
Proposal: new post-build step which allows for file expansion and deletion 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1010]
cc @matanlurey @natebosch for comments/feedback

At a high level, the idea is to add a new phase which runs after the main build. The design of this phase is motivated by a few key use cases:

- Expanding out archives into all the files contained in them, (see https://github.com/dart-lang/build/issues/814)
- Cleaning up output files before deployment (see https://github.com/dart-lang/build/issues/189)

The api would be very restrictive, essentially it will allow you to take a single asset as an input, and allow you to do one or both of the following:

- delete it
- expand it into multiple files

This would explicitly have the following restrictions:

- You cannot output a file which already exists (either it was in the original graph or was expanded from another file).
- You cannot read any file other than the primary input asset (as an optimization and to discourage abuses of this phase).
- Since this is a post-build step, any extra outputs cannot be read by the actual build in any way.

Exactly what the api would look like is a bit up in the air, but it would likely only be exposed by `build_runner` and not `build` at least in the short term. Fundamentally everything described above is compatible with bazel though.

If we think this is a good idea, I can work up a more specific design proposal for the api.

**Comment by matanlurey** [comment]
👍

**Comment by jakemac53** [comment]
One api for this could be a new builder class, something like this:

```
/// Note the lack of `buildExtensions`, the main difference between normal builders is
//  these ones do not define their outputs ahead of time.
class PostProcessBuilder {
  FutureOr<Null> build(PostProcessBuildStep buildStep) {

  }
}

class PostProcessBuildStep implements AssetWriter {
  AssetId get input;

  Future<String> readInputAsString();
  Future<List<int>> readInputAsBytes();

  void deleteInput();

  // Plus the normal AssetWriter methods (writeAsString, writeAsBytes, etc).
}
```

Not the prettiest thing in the world.. but it would do the trick.

We could also just have it implement `AssetReader` but throw if you try to read anything except `input`... which might be more flexible later but also would likely lead to confusion.

**Comment by jakemac53** [comment]
I did just realize that this would be quite challenging to get working with a fully lazy serve mode, which we probably do want at some point. Since we don't know what outputs will be produced by these builders, we don't know how to build these files if they are requested.

**Comment by jakemac53** [comment]
Another option we were considering, is to tackle the issue of enabling users to add in their own serve handlers. If we actually allowed your dependencies to do this automatically (similar to how they apply builders), then `build_web_compilers` could provide a handler which knows how to serve deferred loaded dart2js files out of archives.

This is also generally useful - angular_router could provide a handler for doing custom routing for instance.

The difficult part is what to do for deployment, we still need some sort of step for expanding the archives in the merged output directory, and that would have to match up with whatever the serve handler is doing.

**Comment by jakemac53** [comment]
Ok, so one idea solve this with the original proposed design, we could add a `Map<String, Iterable<Glob>> get buildExtensions` field to the `PostProcessBuilder` class.

This works exactly like regular `buildExtensions`, except you would be allowed to output anything matching the glob. In a future lazy serve mode we could iterate all of these builders and if their output globs match the requested file we would run that builder. We could either assert that only one builder has matching globs, or we could continue the process until one of the matching builders actually outputs the desired asset.

**Comment by jakemac53** [comment]
Alright, so we had some more conversations related to this and are going to go with the original proposal here. We will not require you to declare output globs, which means **we are adding a feature which can never be supported in lazy serve mode**.

Instead, the thought is that the combination of a couple different features would replace laze serve mode:
-  The ability to build only specific apps, instead of your entire project (https://github.com/dart-lang/build/issues/539)
-  The ability to only start builds on refresh or other explicit triggers (widget in browser, etc, https://github.com/dart-lang/build/issues/1063)

**Comment by jakemac53** [comment]
@natebosch ok so as a part of this we also need to update the build_config because we have a new type of builder, and it only takes `input_extensions` and not `build_extensions`. I propose the following changes to the `BuilderDefinition` config:

- Add an `is_post_process` boolean field
- Add an `input_extensions` field, which is a list of extensions.
  - It is only allowed if `is_post_process` is `true`.
- Make it an error to provide `is_post_process` and `build_extensions`.

Another alternative would be creating a whole new section, `post_process_builders` or something, but it would duplicate almost all the fields...

**Comment by natebosch** [comment]
We also need to think about the other fields that _don't_ apply to this new type:

- Do we need (want?) to support multiple "builder_factories" for this?
- What does "auto_apply" mean here? Do these get applied per target like normal builders do?
- "required_inputs" definitely doesn't apply
- "is_optional" doesn't apply
- can a target configure this at all? Would it ever use "generate_for" such that the "defaults" section of the BuilderConfig matters?

In general I'm nervous about overloading because the more we find reasons that the two types of config diverge the more complex things get...

**Comment by jakemac53** [comment]
Hmm ya good points, it probably does make sense to just create a whole separate section/class to represent these. The other fields we want to add won't apply  either (run_before, requires_builder)

**Comment by matanlurey** [comment]
To clarify @jakemac53 @natebosch - is the first part of this done, i.e. the archive/extraction steps? I believe we just need deletion of assets that don't need to be in the final build, right?

**Comment by natebosch** [comment]
Yes we need to support deletion.

I also realized that we might want to move the interfaces to `package:build` since angular likely wants to ship a `PostProcessBuilder` to clean up `.ng_placeholder` files, but we don't want to add a non-dev dependency on `build_runner`...

**Comment by matanlurey** [comment]
Sgtm 👍
