### ISSUE TITLE
Clarify which option will cancel the build when output directory already exists

### ISSUE THREAD

**Issue by nshahan** [dart-lang/build#1011]
It's not clear if option 1 will halt the build if I don't want anything to happen in the output directory.

```
Found existing output directory `/foo` but no manifest file. Please choose one of the following options:
1 - Skip creating the output directory
2 - Delete the existing directory entirely
3 - Leave the directory in place and write over any existing files
```

**Comment by jakemac53** [comment]
Open to suggestions here - we want to keep it brief otherwise this just becomes a wall of text.

**Comment by jakemac53** [comment]
Fwiw though, none of these options cancel the build. The first option does cancel creating an output directory though.

**Comment by nshahan** [comment]
If the directory already exists and you chose to "skip creating the output directory" does the contents of the directory that already exists change?

**Comment by natebosch** [comment]
no, it shouldn't touch the directory if you choose option 1. Happy to review a PR adding language to make that clear 😉

**Comment by jakemac53** [comment]
What about these changes:
```
1 - Leave the existing directory alone, but continue building
2 - Overwrite the existing directory entirely
3 - Leave the directory in place and write over any conflicting files
```

**Comment by nshahan** [comment]
I found that when I picked option 1 it looked like the build failed with a severe error. Is it the case that technically the build already completed and it was just copying to output directory that failed?

**Comment by jakemac53** [comment]
> I found that when I picked option 1 it looked like the build failed with a severe error. Is it the case that technically the build already completed and it was just copying to output directory that failed?

Oh yes, we do still treat it as a "failed" build, because the output directory was not created in that case. We could change that, I am not sure what the right thing is to do actually.
