### ISSUE TITLE
Build failures cause cascading errors that are confusing

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1018]
For example, this error reported by a user on Gitter:

> @matanlurey Ok still trying to make sure I have everything setup correctly.
>
> I'm even getting errors in some the async libs:

```
[error] Invalid override. The type of 'TypeSafeStream.lastWhere' ('((T) → bool, {defaultValue: () → Object}) → Future<dynamic>') isn't a subtype of 'Stream<T>.lastWhere' ('((T) → bool, {defaultValue: () → dynamic, orElse: () → T}) → Future<T>'). (package:async/src/typed/stream.dart, line 59, col 3)
[error] Invalid override. The type of 'TypeSafeStream.singleWhere' ('((T) → bool) → Future<T>') isn't a subtype of 'Stream<T>.singleWhere' ('((T) → bool, {orElse: () → T}) → Future<T>'). (package:async/src/typed/stream.dart, line 62, col 3)

Please fix all errors before compiling (warnings are okay).
[WARNING] Instance of 'WebEntrypointBuilder' on one_veenee|web/main.dart: Unable to read async|lib/src/typed/stream.ddc.js, check your console for compilation errors.
[SEVERE] Instance of 'DevCompilerBuilder' on async|lib/src/typed_stream_transformer.module: ```
```

In this case they did nothing wrong, the analyzer step failed because a package is out of date.

It would be nice to make these analysis errors (i.e. compilation errors) stand out better, but I've filed [TODO] about that. In the mean time ... maybe we should flip `--fail-on-severe` to `true` by default, because clearly its not possible to move forward in these cases.

**Comment by matanlurey** [comment]
Another example? https://github.com/dart-lang/build/issues/1020

**Comment by natebosch** [comment]
Yeah I think one thing we need to do is mark an output as failed and do something smarter when a future step tries to read it. The behavior today of it just looking missing is weird.

**Comment by natebosch** [comment]
We're now throwing when a build step attempts to read a file that failed, though they can still check `canRead` and it will get treated as if the file doesn't exist.

Taking a look at how to handle serving successful assets when the overall build failed and hitting some trouble - we currently rely on serving `.ddc.errors` files to communicate build failures for DDC, but if we refuse to serve assets produced by failing build steps we'll hide these. We might need a new scheme for communicating failures to the browser.

**Comment by jakemac53** [comment]
The `.ddc.errors` files are not a general solution anyways so that would probably be best if we can come up with something general.

**Comment by natebosch** [comment]
The next piece of this we had discussed is tracking when a build step _attempts_ to read an asset (with `canRead` or with `readAs*` in a `try/catch`) which is a failure and mark it as failed as well. The reasoning was, I think, that if you potentially depend on broken state you must be broken as well.

I'm not quite sure I still agree with that line of thinking, maybe it should be OK for a builder to skip a failing read and give a potentially degraded but still usable output. We can leave it up to the builders to decide whether the failed read is truly breaking.

Any thoughts @jakemac53 ?

**Comment by jakemac53** [comment]
The ddc case is a good callout - we definitely want to be able to show _something_ in the browser still. We wouldn't want the entrypoint builder to fail and not serve its outputs just because a single module didn't exist.

**Comment by natebosch** [comment]
Now that we treat reads of failed potential outputs specially, and have re-reporting of errors from previous builds. I think we can consider this finished. We'll continue to keep an eye out for user confusion over failure modes.
