### ISSUE TITLE
Display "compile errors" more prominently

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1019]
See https://github.com/dart-lang/build/issues/1018 for an example.

If code is mistyped and doesn't pass analysis (or CFE in the future), it should be more clear.

I'd like to see:

```
[SEVERE] An error occurred compiling. Check your IDE and/or command-line dartanalyzer:
  package:async/src/typed/stream.dart
    line 59, col 3: Invalid override.
    <Description>
```

(Open to other formatting suggestions)

I'm not sure what package this should go under. Runner? Modules? Web?

**Comment by natebosch** [comment]
I think our error messages for compiler errors are OK at this point. We can still improve the "cascade" case and errors for previous builds but that is covered by other issues.
