### ISSUE TITLE
Add a "name" getter for Builder?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1023]
See errors like https://github.com/dart-lang/angular/issues/897:

> [WARNING] Instance of 'LibraryBuilder' on ...

There is nothing here that says it is _Angular_ that is warning, versus say, DDC.

I could override `toString()`, but that also means `LibraryBuilder`/`PartBuilder` in `package:source_gen` would need to delegate `toString()` to the wrapper generator; maybe that is OK too?

**Comment by natebosch** [comment]
Yeah I think I'd prefer using `toString()` for this. Let's have source_gen implement `toString()` and avoid a breaking change in package:build

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/source_gen#311
