### ISSUE TITLE
Consuming multiple libraries that have builders applying to dependents 

### ISSUE THREAD

**Issue by davidmarne** [dart-lang/build#1030]
Right now if two libraries have builders that apply changes to the dependents package, and both builders output to the same file you get a message similar to:

```
DuplicateAssetNodeError: GeneratedAssetNode: built_redux|lib/builder.g.dart generated from input built_redux|lib/builder.dart.
This probably means you have multiple actions that are trying to output the same file
``` 

I've run into a case where I want to consume two libraries, that both have builders that output to source and use source_gen's PartBuilder. However, unless one library compromises and uses a custom build_extenstion, I will hit this issue because both want to output to *.g.dart. 

It seems practical to let both libraries output to the same file for the specific use case of source_gen's PartBuilder. Thoughts on what it would take to make that possible? If its not practical to allow this should it be considered best practice to use custom build extensions that use the library name to guarantee the output files are unique (eg *.built_value.dart rather than *.g.dart)?

**Comment by natebosch** [comment]
Yeah this is a use case we'd really like to support. Unfortunately the solution today is write a custom PartBuilder to put together multiple generators, or to to use unique extensions as you suggested.

Follow #975 where we'll be looking for better solutions.

**Comment by davidmarne** [comment]
@natebosch is there any way to prevent `pub run build_runner build` from running built_value's build if I were to write a custom PartBuilder to put together both generators?

**Comment by natebosch** [comment]
You'd need to write a `build.yaml` and set `enabled: false` for that builder.

**Comment by natebosch** [comment]
https://github.com/dart-lang/build/blob/master/build_config/README.md#configuring-builders-applied-to-your-package
