### ISSUE TITLE
build_runner watch -o build does not detect file changes on windows

### ISSUE THREAD

**Issue by tprouza** [dart-lang/build#1031]
`pub run build_runner watch` works fine
but `pub run build_runner watch -o build` is not responding to file changes
I see this happening only on windows.

**Comment by jakemac53** [comment]
That is bizarre, but I can actually repro it.

**Comment by jakemac53** [comment]
Ok, it looks like as a workaround you can output to a directory not within your project, for instance `pub run build_runner watch -o ..\build`.

My guess here is that the file watcher is getting overwhelmed by all the new files in the `build` directory, and somehow as a result is not giving us the file change notifications in the actual package.

**Comment by jakemac53** [comment]
It looks like the `PollingDirectoryWatcher` works on windows, so I will hardcode an exception to use that for now, and file a bug on the watcher package for the `WindowsDirectoryWatcher`.

**Comment by jakemac53** [comment]
Published the fix in 0.7.11+1
