### ISSUE TITLE
If no source directories match then serve mode never starts a server.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1044]
This is pretty confusing, and includes if you are generating files under `web` or some folder that would match. At a minimum we should give a warning that no directories matched.

**Comment by nshahan** [comment]
I think this issue should probably stay open. The message is helpful, but it would be nice if serve checked for source or generated directories.

**Comment by jakemac53** [comment]
Re-opened, but assigned low priority since this is a pretty narrow use case

**Comment by natebosch** [comment]
I think if you manually specify the directory it works, is that good enough for your use case?

`pub run build_runner serve web`

**Comment by jakemac53** [comment]
That is the workaround but it shouldn't be required technically. The issue is if you have a project where the entire web directory is generated.

**Comment by natebosch** [comment]
Does this come up often enough that it's worth making smooth?

**Comment by nshahan** [comment]
Probably not very common, just very confusing when it doesn't work. For my use case the new message and the ability to specify the directory manually works fine. 

Hypothetically it could be more confusing if you have multiple web entry points, some that exist as source code and some that are completely generated.

**Comment by natebosch** [comment]
I think this is working now.
