### ISSUE TITLE
Check for `foo.dart` when `foo.module` doesn't exist

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1046]
We lost a chunk of time trying to investigate why a `.module` file wasn't getting created when the issue was that we had an import to a non-existent dart file. The real dart file was in a different directory.

We should check for the dart file and adjust the error message since this points to a problem with the code, not a problem with the build order etc.

cc @nshahan

**Comment by matanlurey** [comment]
Not sure the best way to solve it, but I investigated a bit:

https://github.com/dart-lang/build/blob/20f533b243d6f8b0c0b0f219ee531a9b504082da/build_modules/lib/src/modules.dart#L125-L127

... is confusing. You might want to consider making it a `.fine`.

https://github.com/dart-lang/build/blob/20f533b243d6f8b0c0b0f219ee531a9b504082da/build_web_compilers/lib/src/dev_compiler_builder.dart#L45-L51

... prints a blank error.

**Comment by jakemac53** [comment]
I am going to just make `computeTransitiveDependencies` throw if it fails to find a module. I don't think it ever makes sense to continue in that case.
