### ISSUE TITLE
Provide a post-build hook

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1062]
- Only available to the "root" package
- Only ran with --output
- Something like

```dart
FutureOr<void> postBuild(String outputPath)
```

Would let folks who want to deploy apps do rewriting for cache busting, etc.

See https://github.com/dart-lang/angular/issues/939#issuecomment-369017026

CC @jakemac53

**Comment by matanlurey** [comment]
Other rationales:

* Ability to write commit or build #s as part of the output/metadata.

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/build/issues/1308
