### ISSUE TITLE
Add `runs_before` *and* `applies_builders` to builder config

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1065]
Indicates that a different builder should be run on this target (package) after this builder, including it's outputs. Can be used to effect builder ordering when that builder would have run anyways, and can cause builders to run that would not have run otherwise.

Necessary for a "CombineOutputs" builder that can be opted in for source_gen like scenarios. #975 

cc @nshahan

**Comment by jakemac53** [comment]
`requires_builder` imo because it can cause a builder to run that was not applied at all previously.

**Comment by natebosch** [comment]
synced offline, these probably end up needing to be separate options.

Going with `runs_before` and `applies_builders` for now.
