### ISSUE TITLE
Reading generated files in a VM test

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1079]
I have a crazy workaround to be able to read generated files in a VM test that works both externally (PBR) and internally (Bazel). However, the external (PBR) version only works with the following "technique":

```bash
$ pub run build_runner build -o build
$ pub run test -p vm
```

... where the test _knows_ to find the generated files in `build/`. I'd prefer to remove this logic so I can just use `pub run build_runner test`. Any ideas?

Source:

https://github.com/dart-lang/angular/blob/74750a031c5b0a292f2ab471a44f6a3ff99e5f79/_goldens/test/check_goldens_test.dart#L14-L40

**Comment by natebosch** [comment]
is there a reason that `pbr test -- -p vm` doesn't work for you today?

**Comment by matanlurey** [comment]
I need to read generated files in the VM test, and it wasn't working w/o this.

**Comment by matanlurey** [comment]
Figured this out, thanks!
