### ISSUE TITLE
Help users know to use Dart2JS for deployment

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1089]
See https://github.com/dart-lang/angular/issues/1016.

I'd love to brainstorm a bit how we can best do this.

/cc @vsmenon

**Comment by jakemac53** [comment]
I think we probably want to add a `deploy` command, which takes a single app, and possibly has different defaults. This would be similar to `pub build` versus `pub serve`, and we could add a flag to the `BuilderOptions` which tells it the current mode?

**Comment by matanlurey** [comment]
Sounds like it.

Other ideas I have include adding a `console.warning(...)` to all DDC apps, i.e. "You are currently running in Dartdevc, a developer compiler. Many optimizations, such as tree-shaking, are not enabled. See goo.gl/XXX on how to deploy this application."

**Comment by matanlurey** [comment]
(This aligns nicely with talks with @vsmenon re: DDC devtools - "we see you are running DDC but not the dev extension. See ..."

**Comment by natebosch** [comment]
With `--release` I think this is more apparent.
