### ISSUE TITLE
Change default for --fail-on-severe

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1097]
Maybe even remove the flag?

**Comment by matanlurey** [comment]
Would be part of the way to https://github.com/dart-lang/build/issues/913.

Though FWIW, I find this really confusing, including internally. In AngularDart I've started throwing `BuildError` when you hit a "severe" state; it avoids getting into weird error cases (i.e. step 1 fails, so step 2 hits an NPE):

https://github.com/dart-lang/angular/blob/1d79577139085d927d6ee1b4a8cb9e41256d1336/angular_compiler/lib/src/cli/logging.dart#L112-L129

**Comment by jakemac53** [comment]
I don't know that we actually want to do this until we have a way of doing partial builds. Or at least we shouldn't kill the build early as a result - I would be fine with treating the overall build as failed as long as we will still serve apps.

The use case I am primarily worried about is refactoring - I should be able to hack around during refactoring and serve any apps that still work. I shouldn't have to update my tests to match until after I am done with the refactor - or maybe I update them first if I am into TDD, either way would put you in a bad place if we bailed early on the builds.

**Comment by matanlurey** [comment]
@jakemac53:

> I don't know that we actually want to do this until we have a way of doing partial builds. Or at least we shouldn't kill the build early as a result - I would be fine with treating the overall build as failed as long as we will still serve apps.

I guess I'm confused. Isn't a `severe` usually something that will prevent a successful serve/build anyway? If it's not, maybe we should encourage downgrading to a warning?

> The use case I am primarily worried about is refactoring - I should be able to hack around during refactoring and serve any apps that still work.

Ack, but again, I see this as `severe` == `your_app_will_not_work`. For example:

```dart
void main() {
  String x = 5;
}
```

... won't compile. There is no value in continuing*, right?

_*I realize there might be value on continuing other unrelated builds._

**Comment by jakemac53** [comment]
@matanlurey the problem is we don't have a way right now of not building your entire package - so if any of your tests don't compile it would break the entire build and you wouldn't be able to serve your app etc.

Once we do have that, I am fully in favor of flipping this default.

**Comment by natebosch** [comment]
> I would be fine with treating the overall build as failed as long as we will still serve apps.

Yeah I think what we should do is let builds continue, and serve any assets that were written even if that asset is marked failed, but track that things are failed. We can separately consider a flag which does/doesn't serve or copy to `--output` the assets which are marked failed.

**Comment by matanlurey** [comment]
Another option might be keeping this as a flag, and flip to to `false` by default when using the `serve` command (versus the `build` or `test` command). Thoughts?

**Comment by kevmoo** [comment]
Just hit this with https://github.com/dart-lang/webdev – build should have a non-zero exit if build fails!

**Comment by natebosch** [comment]
Taking a look at this now - I think it makes more sense to _not_ serve these assets.
