### ISSUE TITLE
Use pkg:http_multi_server for serve – listen on v4 and v6

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1103]
https://github.com/dart-lang/build/blob/20f533b243d6f8b0c0b0f219ee531a9b504082da/build_runner/lib/src/entrypoint/options.dart#L355

Support both IPv4 & v6 endpoints – helpful for systems that have one but not the other

**Comment by natebosch** [comment]
Our default server binds to `'localhost'` which should work for ipv6. If you specify `--hostname` you're on your own for making sure you pick a host which works with ipv6, ipv4, or both.

Try it:

`curl -g -6 "http://[::1]:8080/"`

**Comment by kevmoo** [comment]
We need to be as flexible out-of-the-gate as `pub serve` - https://github.com/dart-lang/pub/blob/73ff0d3d9f80f60d41e3135ac44597d011abb4f3/lib/src/io.dart#L882

This is a blocking issue for IntelliJ support.

**Comment by kevmoo** [comment]
...we should support local clients trying to connect on v4 and/or v6 – whichever is available.

**Comment by kevmoo** [comment]
@alexander-doroshko – could you comment?

**Comment by alexander-doroshko** [comment]
Debugging in IntelliJ works great for me without any tricks with build_runner 0.7.13. Thanks a lot for the quick fix!
