### ISSUE TITLE
Add "clean" command

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1104]
... especially now that more tools will use `.dart_tool`, deleting that entire directory is sort of a smell. Ideally it would also mention that this shouldn't be needed, and we'd love a bug, i.e.:

```bash
$ pub run build_runner clean
$
$ > Deleting cache. This shouldn't be necessary for most applications, unless you
$ > have made intentional edits to generated files (i.e. for testing). Consider
$ > filing a bug at ...
```

**Comment by matanlurey** [comment]
Thoughts @jakemac53 @natebosch?

**Comment by kevmoo** [comment]
SGTM

**Comment by natebosch** [comment]
We think today it'll delete `.dart_tool/build`? I think that makes sense for now.

**Comment by jakemac53** [comment]
SGTM
