### ISSUE TITLE
Pick a different character than `|` for separators

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1127]
At least for builder keys... On linux it causes us to need extra quoting and seems to also trigger some weirdness with `Process.run` on windows (which behaves differently than linux).

This would be very breaking - `build.yaml` files would need to change. We could maybe do it in a backwards compatible way and translate the `|` into the new character though?

**Comment by jakemac53** [comment]
Ya I think we need to just support two versions, at least for a bit. Maybe warn if we see the `|`?

**Comment by matanlurey** [comment]
Do we have any idea what other common delimiters are used in apps/clis?

**Comment by natebosch** [comment]
`/`, or `.` seem fairly sane and shouldn't require any weird escaping.

`:` is a common separator but we're using that for targets and I like having different ones.

`#`, `&` would both probably be fine in the shell, but in the yaml they would cause problems since we allow referring to same-package builders with an omitted package name.

**Comment by matanlurey** [comment]
Hmm, how about `@`?

**Comment by natebosch** [comment]
`.` won't work because internally package names can have `.`

`@` and `!` also have special meaning in yaml. `~` seems to work but looks... weird

`/` and `:` seem to be the only real safe choices. Jake and I discussed and since there should never be any ambiguity about whether you're referring to a target or a builder it should be safe to use the same separator. I think we'll run with that.

**Comment by matanlurey** [comment]
Sounds good, `:` is fine with me.

(one of the reasons I dislike YAML are all the special meanings, but oh well)

**Comment by DanTup** [comment]
I don't actually know what this refers to; what are we separating?

**Comment by natebosch** [comment]
In the new build system when you configure a 'Builder' you refer to it by it's key, which is the package it's defined in, followed by it's name. So the builder which outputs the final JS file is (currently) `build_web_compilers|entrypoint`. You can refer to this key either in your `build.yaml`

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
```

Or on the command line with `--define="build_web_compilers|entrypoint=compiler=dart2js"` (we know the syntax is a bit nasty - we hope that `webdev` will help hide some of this).

The command line usage behaves strangely on Windows, I can't find a way to invoke this that works with our call to `Process.run` from our tests: https://github.com/dart-lang/build/pull/1122/commits/e0079c329cf9771b5546703a4494a57d317733ae

**Comment by DanTup** [comment]
Hmm, I'm not sure I have a great opinion. I think a forward slash might look a bit nicer (and it feels familiar to refer to things like `package/something` - and git uses `remote/branch`).

Windows uses `;` as a path separator but I think that's dangerous because some shells might see it as a end-of-command character?

I think whatever you pick you'll want to escape in some form if it's to go to the command line, in case someone puts quotes around it (or something just totally bogus/dangerous).

**Comment by DanTup** [comment]
> (trailingArgs: ['--define', 'bad|key=foo=bar'])

I'm not sure what that's supposed to come through as, but escaping for the command line on Windows is a massive PITA. Even in PoSh it's confusing - check out the length of [this article](http://edgylogic.com/blog/powershell-and-external-commands-done-right/) - if even has info on `echoargs.exe` as a trouble-shooting utility :(

**Comment by natebosch** [comment]
Do you know if windows does anything strange with `:`?

**Comment by DanTup** [comment]
Not sure (suspect not). On my way out, but if you give me a snippet of how you're launching the process I could run it on CMD/PowerShell with all the characters and post back how they come through to the other process (might not be today though as may not be back till late).

**Comment by natebosch** [comment]
Thanks for that link. From scanning through it looks like `:` is safe and we like how it matches what we're doing with targets. Thanks for the advice!

**Comment by chalin** [comment]
Are you looking for a replacement syntax for `|` as used in keys like this?

```yaml
    builders:
      build_web_compilers|entrypoint:
        ...
```

As you know,`:` (followed by a space) is used to separate a YAML key from its value. Some simple YAML parsers might not like having a colon in an unquoted key name, so we might be forced to write quoted keys in YAML files (or maybe we don't care about simplified YAML parsers):

```yaml
    builders:
      'build_web_compilers:entrypoint':
        ...
```
Using `/` would avoid such potential issues. Also, visually `/` might read more naturally than have two (or more colons) in a row.
 
```yaml
    builders:
      build_web_compilers/entrypoint:
        ...
```

cc @kevmoo

**Comment by kevmoo** [comment]
@natebosch @jakemac53 – ship sailed here?

**Comment by natebosch** [comment]
> ship sailed here?

I don't necessarily think so - pretty sure we can keep backwards compatibility to avoid disruption, but give something that looks nicer going forward.
