### ISSUE TITLE
Use Trace.terse (pkg/stack_trace) for crashes

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1135]
... we used to do this when `Chain.capture` was used, but now it is lost.

For example:
https://github.com/dart-lang/build/issues/1134

... has a bunch of junk in it unrelated to user code :)

**Comment by natebosch** [comment]
I think the linked example would not have been caught by the `Chain.capture` either since that wasn't at the top level. I think this case isn't going through the logger? We might need to add a top-level exception handler to catch cases like this

**Comment by matanlurey** [comment]
Ah OK. Where would that be setup, typically?

**Comment by natebosch** [comment]
We either need to do something in the generated `build.dart`, or in `run`

https://github.com/dart-lang/build/blob/b5b349574552c645059a61be9d360674f47e95be/build_runner/lib/src/entrypoint/run.dart#L13
