### ISSUE TITLE
Why declareOutputs?

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/build#114]
In my project, I need to generate classes from a XML file. 

My InputSet is the single xml file. The output assets are determined after passing the xml file (I am trying to generate a file for each class). Due to the `declareOutputs` function, I have to parse the xml file by using file system directly inside the declareOutputs function and cache the generated code (I don't want to parse it again in the build function). This does not feel right to me. So I ended up jamming all classes into a single file.

Why do we need the declareOutputs function? IMO, Let the user decide which file to write in the build function will be much flexible. (Like the transformer which only require inputs).

**Comment by jakemac53** [comment]
This is for two reasons:

- Compatibility with other build systems in the future such as [bazel](http://www.bazel.io/), where you must declare outputs ahead of time based only on the file name.
- Future ability to lazily build on demand only the required files for some task.
