### ISSUE TITLE
DDC source maps still aren't applied for the SDK

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1151]
```
Type 'JSArray<String>' is not a subtype of type 'Iterable<int>'
  package:$sdk/dev_compiler/amd/dart_sdk.js 4909:29   throw
  package:$sdk/dev_compiler/amd/dart_sdk.js 4837:17   castError
  package:$sdk/dev_compiler/amd/dart_sdk.js 4808:17   as
  package:$sdk/dev_compiler/amd/dart_sdk.js 4021:19   check_C
  package:$sdk/dev_compiler/amd/dart_sdk.js 4710:16   _checkAndCall
  package:$sdk/dev_compiler/amd/dart_sdk.js 4765:17   callMethod
  package:$sdk/dev_compiler/amd/dart_sdk.js 4768:17   dsend
  list_change_test.dart 98:7                          test.test.dart.fn
  package:test                                        <fn>
  package:$sdk/dev_compiler/amd/dart_sdk.js 25138:33  onValue
```

To reproduce:

* https://github.com/dart-lang/observable/pull/63
* Revert the fix I made to `list_change_test.dart` :)

**Comment by matanlurey** [comment]
Apparently this might be SDK version specific. Let me verify.

**Comment by natebosch** [comment]
I think https://github.com/dart-lang/sdk/commit/34f8c356a324aa1f4f76c7d11f4b3a1ab42e3d10#diff-f259f1095503568ea0750a55a83301c0 was the commit we expected to fix this.

So if you were won dev.35 or it's likely still a problem. If you were on dev.33 an upgrade should hopefully fix it.

**Comment by matanlurey** [comment]
Running on dev.35 now (was on dev.32):

```
00:05 +132 -1: [Chrome] test/list_change_test.dart: List deltas can be applied Delete Empty [E]
  Type 'JSArray<String>' is not a subtype of type 'Iterable<int>'
  package:$sdk/dev_compiler/amd/dart_sdk.js 4910:29   throw
  package:$sdk/dev_compiler/amd/dart_sdk.js 4838:17   castError
  package:$sdk/dev_compiler/amd/dart_sdk.js 4809:17   as
  package:$sdk/dev_compiler/amd/dart_sdk.js 4022:19   check_C
  package:$sdk/dev_compiler/amd/dart_sdk.js 4711:16   _checkAndCall
  package:$sdk/dev_compiler/amd/dart_sdk.js 4766:17   callMethod
  package:$sdk/dev_compiler/amd/dart_sdk.js 4769:17   dsend
  list_change_test.dart 98:7                          test.test.dart.fn
```

:(

**Comment by matanlurey** [comment]
`Dart VM version: 2.0.0-dev.35.0 (Fri Mar 9 13:09:14 2018 +0100) on "macos_x64"`

**Comment by natebosch** [comment]
cc @vsmenon

**Comment by vsmenon** [comment]
We shouldn't be keeping source maps for the SDK any more.  But it looks like it's being mapped weirdly ... "package:..."?

**Comment by natebosch** [comment]
This is the same thing we were seeing in https://github.com/dart-lang/sdk/issues/32389

We intend for all of `dart_sdk.js` to get source mapped to `dart:sdk_internal` but that isn't happening.

The problem might be that we check for `!sourceUrl.startsWith('package:')` in additional to `sourceUrl.contains('dart_sdk.js')`, but `build_runner` treats the SDK like the special package `$sdk` in that it serves resources from `/packages/$sdk`. I don't know if `build_runner` specifically is giving the `package:` URI or if that is assumed from the path.
