### ISSUE TITLE
re: #1151 - Remind me to upgrade my SDK?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1152]
Maybe "your version of the SDK is X, but the latest stable BR requires Y. Consider upgrading?"

**Comment by jakemac53** [comment]
I am not sure if BR itself is really the right place for this, because old versions inherently can't know about sdk constraints of future releases. Should we move this to webdev?

**Comment by natebosch** [comment]
I think webdev should own this.

cc @kevmoo

**Comment by kevmoo** [comment]
Do we think this is useful before Dart v2 is gold? In which cases should it run?
