### ISSUE TITLE
During serve, pasting a file into web/ requires re-running

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1163]
I had the following:

```
web/
  index.html
```

```html
<img src="missing-file.png" />
```

I copy pasted `missing-file.png` into `web/missing-file.png`, and refreshed.

Still nothing (404).

I hit `ctrl-c` and re-ran `pub run build_runner serve`, and it worked.

**Comment by natebosch** [comment]
did a build with 0 outputs run after you added the file?

**Comment by matanlurey** [comment]
No.

**Comment by natebosch** [comment]
I can't repro, if I write any file to `web/` then it triggers a build with 0 outputs and I can load it.

Do you have a `targets` section in your build.yaml with explicit `sources`? I would expect if this was being excluded it wouldn't work even after a restart, but maybe theres a bug around that

**Comment by matanlurey** [comment]
No. FWIW I copy-pasted it through IntelliJ. Maybe it does something different?

I'll re-open if I see this again.
