### ISSUE TITLE
Updating SDK does not invalidate dart2js output

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1169]
SDK 2.0.0-dev.37.0, build_runner 0.8.0 and friends

Upgraded SDK to -dev.37. Ran `pbr build` w/ a build_web_compiler

expected: new build output, etc
actual: "nothing changed, no action ran"

**Comment by natebosch** [comment]
We should invalidate the entire build graph of the sdk changes...

**Comment by kevmoo** [comment]
Agreed!

**Comment by natebosch** [comment]
My language was vague - we _do_ invalidate the entire build if the SDK changes. Just upgraded my SDK and ran a build and got: `[WARNING] Throwing away cached asset graph due to Dart SDK update.`

Can you repro this?

**Comment by kevmoo** [comment]
I'll look...

**Comment by kevmoo** [comment]
Weird...can't repo.
