### ISSUE TITLE
Support a faster 'pbr test <file.dart>'

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1175]
i.e.

`pub run build_runner test -- test/regression/814_query_html_element_test.dart`

**Comment by natebosch** [comment]
do you mean building only that output? Definitely on our radar but we don't have a concrete plan yet.

**Comment by matanlurey** [comment]
Yes only building (or re-building). No worries, just filing for tracking :)

**Comment by jakemac53** [comment]
We do sort of support this via `--build-filters` but the test command doesn't smartly build only that test for you which would be nice.
