### ISSUE TITLE
build_runner watch crashes after a file is saved using webstorm

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/build#1177]
I use following command to build new dart when they are changed
```bash
pub run build_runner watch --output build --config release
```
No crashes while using vs-code and sublime text but when I edit and save a file , I am able to see error messages without any crashes.

When using Webstorm, after I press `Ctrl + S`  `build_runner` crashes unexpectedly after showing following error message : 

```bash
[INFO] Running build completed, took 2.2s
[INFO] Caching finalized dependency graph completed, took 61ms
[INFO] Reading manifest at build/.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 47ms
[SEVERE] Missing asset untitled2|web/dart/popup.dart___jb_tmp___, it may have been deleted during the build. Please try rebuilding and if you continue to see the error then file a bug at https://github.com/dart-lang/build/issues/new.


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


AssetNotFoundException: untitled2|web/dart/popup.dart___jb_tmp___
package:build_runner/src/asset/file_based.dart 133:18  _fileForOrThrow.<fn>

```

Operating system:
Arch Linux 64-bit

build_runner version : 
version: "0.8.0"

dart --version output :
Dart VM version: 2.0.0-dev.38.0 (Thu Mar 15 16:53:42 2018 +0100) on "linux_x64"

pubscpec.yaml
```yaml
name: untitled2
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: coder <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dependencies:
  chrome: any
  js: any

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter:
  build_runner:
  build_web_compilers:

transformers:
- chrome
- $dart2js:
    csp: true
    commandLineOptions: [--use-old-frontend]
- dart_to_js_script_rewriter:
    csp: true

web:
  compiler:
    debug: dartdevc

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
```

build.release.yaml
```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
```

**Comment by dineshbhosale** [comment]
Same error occurs in Idea community editor after installing dart plugin.

**Comment by matanlurey** [comment]
You may want to disable or slow-down the rate of IntelliJ's auto-save feature:
https://stackoverflow.com/a/28950477/2118226

Unfortunately it will be quite difficult to account for every possible temporary file. I'll let @natebosch decide what we should be doing here, even if its just messaging.

**Comment by natebosch** [comment]
We might need to increase our debounce time. Temporary save files are a tough problem for file watchers...

In any case I think we should have a smoother failure than this, ideally it would try to run another build rather than die altogether. Will take a look next week.

**Comment by jakemac53** [comment]
I don't think we want to increase the debounce time for all users, but we could make it configurable via `build.yaml` so users who do experience issues can permanently increase it for their project?

**Comment by jakemac53** [comment]
Closing as I don't think we have any plans to change this, current suggestion for users experiencing it is to disable the safe-write feature in intellij.
