### ISSUE TITLE
Removing legacy parser "useAstPkg" has introduced a mysterious error

### ISSUE THREAD

**Issue by exo-pla-net** [dart-lang/build#1182]
Running "pub run build_runner serve" produces:

`'package:angular/builder.dart': error: line 29 pos 42: invalid arguments passed to constructor 'CompilerFlags' for class 'CompilerFlags': no optional formal parameter named 'useAstPkg'`

It seems to have been induced by this change to angular:
https://github.com/dart-lang/angular/commit/5331aa6c9a209fc62e4cea4321246a1b09c84291#diff-55a6b6b41d96fc35f35cff0494fafd21

I'm using:
* [ 2.0.0-dev.39.0 ] Dart SDK Version
* angular: 5.0.0-alpha+7
* angular_components: 0.9.0-alpha+7
* build_runner 0.8.0

**Comment by matanlurey** [comment]
Have you tried upgrading to the latest release, `5.0.0-alpha+8`?

Use `pub upgrade`.

Closed as this is a (potential) Angular issue, not Build.

Please re-open here if the issue persists after upgrading:
https://github.com/dart-lang/angular/issues/new
