### ISSUE TITLE
Add a course-grained modules for non-path dependencies.

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1186]
When files are not likely to change often we can group them into bigger DDC modules which means fewer (but bigger) summaries used for later actions.
Our intuition is that 100 large summaries will perform better than 1000 small ones.

**Comment by jakemac53** [comment]
Note that this is also far fewer total actions and nodes in the graph, as well as fewer dependencies for the nodes that exist.

**Comment by natebosch** [comment]
High level summary for our current and proposed module grouping algorithms:

Currently `build_runner` is a fine-grained as possible. Any Dart library which _can_ be it's own module _will_ be its own module. We only group multiple Dart libraries when the is a library cycle. We directly use the `libraryCycle` from analyzer: https://github.com/dart-lang/build/blob/1b8cb5d04c82c0517c36961a3d5a3d748c7710f0/build_modules/lib/src/modules.dart#L93

In `pub` things are grouped into bigger modules. @jakemac53 wrote it so would know better than me, but I think at a high level its:
- Every library under `lib/` get's its won module, or a grouped module if it's in a cycle like above
- Libraries under `lib/src` get grouped into as large of groups as possible such that each of the modules from `lib/` can satisfy it's imports without pulling in extra compiled code.

This is all implemented in `module_computer.dart`: https://github.com/dart-lang/pub/blob/711f515553a6b87e522715944391cced4dc96d13/lib/src/dartdevc/module_computer.dart

**Comment by jakemac53** [comment]
> Every library under lib/ get's its won module, or a grouped module if it's in a cycle like above

It also rolls into its module anything under `lib/src` that it imports that isn't imported by any other public file under `lib`.

**Comment by jakemac53** [comment]
Also libraries under `lib/src` that aren't imported by any public library I believe get their own module.
