### ISSUE TITLE
Discuss: Allow user defined Modules for DDC

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1187]
We hope #1186 helps for non-path (and non-root) packages, but it will not work for the local packages.  What would help here is being able to define module boundaries manually (targets in `build.yaml`?) and some advice on how to structure packages to take advantage of it. This would be a closer model to what we have internally which is user-defined and coarse-grained modules everywhere.

This issue is to discuss possible designs and impacts - we do not have immediate plans to implement this.

There would be a lot of challenges with this - currently the build targets and their relationships are not something we expose to Builders at all.

**Comment by eredo** [comment]
So this would help for projects which use shared path libraries? We are using build_runner for our new internal software applications and are running in some performance issues, so I was wondering if there's already a solution for properly sharing build results of local packages.

To give a little more insight of our project, I'll try to write down the current tree and the dependencies:

```
- dart_shared
-- network
-- shell
-- components
- dart_apps
-- backoffice
-- customer
-- account_manager
-- contractor_manager
-- shop
-- contract_manager
```

All projects within `dart_apps` are web applications with an entrypoint, `backoffice` and `customer` are what we call "main applications" which are available to our customer (internal / external), where as `account_manager`, `contractor_manager`, ... are so called "child applications". Child applications are independent from each other and can run as a standalone application, but on production only available when opening one of our "main applications". To make it easier to develop these applications we have a tool, which detects all dart projects and runs `build_runner serve` within each of them. 
Now to my original question: When changes occur in one of the `dart_shared` packages, each application ("main" and "child") which implements the package will build it and store the DDC results in it's own `.dart_tool/build/generated/...` folder. This is a big overhead and instead it would be great to build it once and each application forwards to that build result. Is there already a solution? Or if not would it currently be possible to do something like this using `bazel`?

**Comment by jakemac53** [comment]
The only way to share the compilation currently would be to stick all the applications in a single package - or possibly create a sort of "meta_package" that depends on all the individual app packages and has only an entrypoint for each.

It is a non-goal at this time to try and share compilation of dependencies because it would be quite difficult to get right, and it would only work for narrow use cases (exact same versions of dependencies, build configuration). Also they would have to coordinate to prevent stepping on each others toes if there were multiple build servers going on at the same time, etc.

**Comment by jakemac53** [comment]
Note that if you did go the "meta_package" route, you could create separate top level directories for each application, and you could then build them individually (but with a shared cache) by passing the directory name as an argument to your build/watch/serve command, `pub run build_runner serve backoffice` for instance.

**Comment by matanlurey** [comment]
Maybe @eredo should file a different bug (and we should clarify the intent of this one), since it is not about sharing module outputs across different packages.

**Comment by jakemac53** [comment]
Actually, I am going to just close this bug as there is no intention to implement it.
