### ISSUE TITLE
Remove `--assume-tty`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1188]
Seems to be noise now, right?

**Comment by kevmoo** [comment]
@jakemac53 – good to do before we call v1?

**Comment by jakemac53** [comment]
It looks like we use the imperative api in tests, but we don't use the command line arg. It might make future integration tests harder to write though...

I definitely agree we should either close this issue as unplanned or drop it for 1.x, so adding it to the 1.0.0 milestone

**Comment by jakemac53** [comment]
cc @natebosch worth doing?

**Comment by natebosch** [comment]
Yes, we can always add it back in if someone complains, but we want to trim to the smallest possible API for 1.0.0 cause otherwise we're stuck supporting it for the long haul

**Comment by jakemac53** [comment]
Went ahead and added this tohttps://github.com/dart-lang/build/pull/1849
