### ISSUE TITLE
Watcher rebuilds but does not pick up source changes for all generators

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/build#119]
On

https://github.com/google/built_json.dart/tree/master/example

(add a "watch" script under "tool", that similarly runs all three generators)

I see odd behaviour: changing input files seems to correctly trigger builds, and updated output, but only  a subset of the expected changes happen. It looks like the issue is over-caching of input sources -- when I debug, I see old sources as input to some of the generators.

For example change compound_value.dart to rename a field in both CompoundValue and CompoundValueBuilder. The field should be renamed in the generated output, compound_value.g.dart, from BuiltValueGenerator. But no change is made.

Oddly, the input change _is_ detected by BuiltJsonGenerator: again in compound_value.dart, comment out the 'serializer' field. The generated output serializers.g.dart is correctly updated to remove the reference to it. Uncomment, and it's correctly updated again.

I tried to dig into the caching to figure out what's going on here, but got a bit lost. Any pointers appreciated :) ... otherwise, could you take a look, please?

**Comment by jakemac53** [comment]
confirmed that I can repro the issue, taking a look

**Comment by davidmorgan** [comment]
Any update please?

**Comment by jakemac53** [comment]
I spent some time investigating this but wasn't able to track down the issue. It's definitely still on my radar but I need to set aside a good chunk of time to investigate.

**Comment by natebosch** [comment]
I narrowed this down to a problem where changing the contents of a Source and bumping the modificationStamp are not causing the AnalysisContext to give us a different LibraryElement.

I still need to investigate whether this is something we're doing weird, or whether it's a bug in the AnalysisContext.

**Comment by natebosch** [comment]
The code that is intended to let the AnalysisContext know of updates is around here: https://github.com/dart-lang/code_transformers/blob/1076161ff1e9dd02ce133e3560df1fef7ad2e346/lib/src/resolver_impl.dart#L578

This does work correctly for the first Resolver that sees a change, but when using sharedSources other Resolver instances read from the sources map, don't see that anything has changed, and don't update their AnalysisContext.

The short term could be to not use shared sources when using watch.
https://github.com/dart-lang/build/blob/4868681a1dd7018b28cc6a358d953a77b7922eec/lib/src/analyzer/resolver.dart#L44

I'm not sure all of the implications so I'll hold off on submitting a change that turns off sharedSources for everyone.

Longer term we should look at either using a single AnalysisContext when using sharedSources, or at making sure ever Resolver updates its own AnalysisContext when there is a change.
