### ISSUE TITLE
Indicate what actions are pending when they get 'stuck'

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1193]
We log the number of actions completed, but once things stop moving it's not clear what actions we're waiting on.

Since this will likely be multi-line we should output output it when actions have been running longer than some threshold - maybe 60 seconds for a single action?

Dart2JS will regularly take that long for bigger projects.

**Comment by jakemac53** [comment]
bumping this to P1, we really need it imo

**Comment by jakemac53** [comment]
I have an alternate proposal for how it could work though - we should just have a global timer where if _no_ actions complete after some much shorter threshold (5s?) then we start logging warnings with a slow (not exponential) backoff.

This would be just as useful imo as tracking the actions individually, but should be simpler and more efficient.
