### ISSUE TITLE
Warn or fail if any command is run with 0 builders possible

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1200]
If I add a dependency on `build_runner` today and nothing else that exposes builders and run a build it will "successfully" do a build with 0 outputs. We should either warn or fail in this case.

cc @kevmoo

**Comment by kevmoo** [comment]
What about `serve` and/or build/watch with -o ?

**Comment by natebosch** [comment]
Yeah `serve` and `-o` are the two cases where there is _some_ possibility of a real use case.

I'm somewhat inclined to say we don't support those and see if we get any bugs about it since it's just easier to not have special cases in our check.

The other thing that makes this slightly lower value than I had originally thought is we can expect the vast majority of packages to have a dep on package:test and it won't be too long before that ships a builder...

**Comment by kevmoo** [comment]
ack. Easier to get less restrictive later...
