### ISSUE TITLE
Exit non-zero (75?) when terminating due to config change

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1201]
75 seems meant for this https://github.com/dart-lang/io/blob/080b68a704133d6462215ac89da5fccb8655b335/lib/src/exit_code.dart#L61

This will make hooking restart in webdev (https://github.com/dart-lang/webdev/issues/18) much easier, too!

**Comment by natebosch** [comment]
Is this a blocker to dropping pub build?

**Comment by kevmoo** [comment]
Sorry. Strictly not. Makes it easier to implement the restart thing in webdev...
