### ISSUE TITLE
Use a custom SDK for testing/development

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1205]
See https://github.com/dart-lang/angular/issues/1146#issuecomment-376679806.

Is this supported with an environment variable or otherwise? If not, worth it?

**Comment by natebosch** [comment]
We'll use whatever SDK the VM is running with. So if you run `path/to/some_sdk/bin/dart .dart_tool/build/entrypoint/build.dart build` you'd be getting builds with that version of the SDK used by the Resolver.

I don't know much about `pub run` to understand how it picks which Dart vm to use, so if we need to do something there to get the inner `pub run test` invocation looking right we can definitely investigate.

**Comment by matanlurey** [comment]
Is it reasonable to support something like:

```bash
$ DART_SDK=/path/to/sdk pub run ...
```

?

**Comment by natebosch** [comment]
We could investigate. It would be easy to make a mistake - we have number of places we find the SDK path and we'd need to be confident we've tracked them all down to honor the environment variable.

**Comment by kevmoo** [comment]
Thoughts @nex3 ?

**Comment by natebosch** [comment]
I thought of a somewhat cheaper way to support this - we could add a flag which is the path to the Dart VM to use (instead of an Isolate) to run the build script.

It would still be a chunk of complexity that I'd hope not to include for a rare use case, but if we hit blockers with other workarounds we can revisit. It also would not cause the inner `pub run test` execution to use the overridden SDK, but builds would run and resolve with it.

Reopen if we need to add this.

**Comment by nex3** [comment]
The way this generally works in my experience is that whatever entrypoint you invoke controls the SDK that's used everywhere. So, for example, if you invoke `/path/to/sdk/bin/pub run build`, it and everythin git invokes should use the SDK in `/path/to/sdk`. If it's *not* doing this, it probably should.

I use this all the time to test across different SDK versions. I have symlinks for each SDK version I have installed, so to test on 1.24.2 I just invoke `pub-1.24.2 run ...`.

**Comment by natebosch** [comment]
I suppose we could hardcode the logic for getting from an SDK directory back to `pub` rather than running the `pub` which is on your `$PATH` as well. We do that already for `ddc`.

**Comment by nex3** [comment]
I strongly recommend doing so. Finding the root directory of the SDK is [pretty straightforward](https://github.com/dart-lang/pub/blob/master/lib/src/sdk.dart#L13-L26), and from there you just use `p.join(sdkRoot, "bin", "pub")`.

**Comment by jakemac53** [comment]
we do this everywhere now afaik and have for a while
