### ISSUE TITLE
Catch exceptions and treat them as build step failures rather than killing the entire build

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1207]
Today we treat "log.severe" very differently from throwing an exception, even with `--fail-on-severe`.

With a severe log we record a failing action and let the build continue. With a thrown exception the build dies and we fail to write the asset graph.

I think we shouldn't rely on builder authors to only `log.severe` to indicate a failed build - we should allow them to throw and treat them the same.

**Comment by kevmoo** [comment]
> I think we shouldn't rely on builder authors to only log.severe to indicate a failed build - we should allow them to throw and treat them the same.

Yes!
