### ISSUE TITLE
Drop the `exception` field from `BuildResult`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1209]
After https://github.com/dart-lang/build/pull/1208 this field is going to be a lot less meaningful - there are potentially multiple exceptions in disparate actions that cause a failing overall build.

We either need to expand this allow for multiple exceptions, or drop it and find another way to communicate why a build fails to the serve handler. Currently we only use this to render a page showing why a build failed - we could also do that through the AssetGraph or some other mechanism.

This would be technically breaking.

**Comment by jakemac53** [comment]
Ya when builds could only fail due to an internal exception this made sense, it no longer does.
