### ISSUE TITLE
Asset graph handler compiled JS can get stale

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1211]
The file `graph_viz_main.dart.js` needs to be recompiled any time we change the format for AssetGraph serialization.

We should probably have a test that this file is up to date, and we should document how to rebuild it.

**Comment by natebosch** [comment]
It's not clear to me what the process should be - the process I found involved some manual renames. If there is a better way it might also involve wanting to ignore the .js.deps file so we should update .gitignore if that's the case.

See #1210

**Comment by jakemac53** [comment]
Hmm ya, we could in theory add a build.yaml and build this file as a part of users builds but that would slow down initial builds :(.

Probably just some sort of test would be best.

**Comment by natebosch** [comment]
We never actually documented how to rebuild this...

**Comment by jakemac53** [comment]
and I just updated the version too so we definitely need to rebuild it :grimacing:

**Comment by natebosch** [comment]
The compiled code no longer depends on the asset graph serialization which is why this was originally closed.
