### ISSUE TITLE
Incremental Builds are taking an excessive amount of time

### ISSUE THREAD

**Issue by rwrozelle** [dart-lang/build#1215]
Hi,

I have an Angular Application that takes 6 minutes for its initial build.  Trivial changes are taking over a minute to rebuild.  Are there any tools I can use to figure out what is going on?  Something to help me untangle the dependencies and determine the why behind the long rebuilds?

Dart SDK - Dev 2 43
build_runner: 0.8.1
Linux Lubuntu 17.10 running in Virtual Box with 10Gb Ram and 2 CPUs.

Initial build:
```
[INFO] Generating build script completed, took 1.1s
[INFO] Setting up file watchers completed, took 65ms
[INFO] Waiting for all file watchers to be ready completed, took 696ms
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] Cleaning up outputs from previous builds. completed, took 1.1s
[INFO] Reading cached asset graph completed, took 9.1s
[INFO] Building new asset graph completed, took 4.4s
[INFO] Checking for unexpected pre-existing outputs. completed, took 7ms
[INFO] Running build completed, took 6m 28s
[INFO] Caching finalized dependency graph completed, took 1.9s
[INFO] Succeeded after 6m 31s with 6318 outputs
Serving `web` on port 8080
Serving `test` on port 8081
```
After trivial change, added a print statement in a file:
```
[INFO] Starting Build
[INFO] Updating asset graph completed, took 13ms
[INFO] Running build completed, took 55.6s
[INFO] Caching finalized dependency graph completed, took 3.0s
[INFO] Succeeded after 58.7s with 48 outputs
```

**Comment by matanlurey** [comment]
Hi @rwrozelle. This certainly isn't desired behavior.

A couple things you could do for us, to help:
1. Run `pub run build_runner serve --track-performance`
2. Navigate to `localhost:8080/$perf`
3. Please save the HTML and upload/send it to us.

Some [documentation here](https://github.com/dart-lang/build/blob/07b9652454222babad585bf684170097b41f12bd/build_runner/CHANGELOG.md#0710).

Another option, if possible, is sharing your project (publicly or privately) so I can try it.

/cc @natebosch

**Comment by rwrozelle** [comment]
@matanlurey 

Thank you, exactly what I was looking for.  I'm going to use this tool for a bit and see if I can optimize the build process.  The basic problem appears to be using the library packages in my "src" code and pulling to many dependencies into a "src" file.  My approach stems from having 4 layers to my code, each with a library package that I then used for import to the layers above.  It saved me development when modifying layers (they were treated as a unit in above layers), but is costing me in the build process with the new builder tech introduced in 2.0.  If I can't get build time down, I guess another approach would be to build the layers as completely separate projects and depend on them through the pubspec.

**Comment by matanlurey** [comment]
@rwrozelle Is this _just_ an Angular builder, or custom builders?

**Comment by rwrozelle** [comment]
Just Angular builder.  I've outsmarted myself and have a cross-dependency and its not the layering in library packages that is the problem.  That's what appears to be taking so long to build.  But the $perf page helps tremendously.  It would be nice if there was a page that displayed the asset graph in a human readable way.
