### ISSUE TITLE
[Feature request] `build_runner serve` should display a URL instead of just the port

### ISSUE THREAD

**Issue by cedx** [dart-lang/build#1217]
Using `build_runner` v0.8.0 with SDK v2.0.0-dev.43 on Ubuntu 17.10.
This is NOT an issue: just a little feature that I want.

When using `pub serve`, the terminal displays : `Serving appname web on http://localhost:8080`

When using `pub run build_runner serve`, the terminal displays: `Serving 'web' on port 8080`

Having the full URL displayed is convenient: it let me "CTRL+click" on the URL and have my browser opened with that URL (I'm using Gnome Terminal). Having only the port displayed forces me to manually open my browser and to enter the full URL before testing my application.

**Comment by matanlurey** [comment]
Sounds reasonable! If you're feeling up to a (small) PR, it sounds easy!
