### ISSUE TITLE
Angular app build not terminating; getting "Rescheduling failed request" messages

### ISSUE THREAD

**Issue by chalin** [dart-lang/build#1218]
On Travis (linux, Dart 2-dev.43), when attempting to build the updated **stagehand web-angular template** (from this PR https://github.com/dart-lang/stagehand/pull/471), the app build doesn't terminate.

Here is an excerpt from the [Travis log](https://travis-ci.org/dart-lang/stagehand/jobs/359935966):

```nocode
pub run build_runner test --fail-on-severe --delete-conflicting-outputs -- -p chrome --reporter=expanded
[INFO] Generating build script...
[INFO] Generating build script completed, took 395ms

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.2s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Running build...
[INFO] 1.6s elapsed, 50/106 actions completed.
... (elided a few lines here)
[INFO] 59.8s elapsed, 2414/4071 actions completed.
[INFO] 1m 0s elapsed, 2464/4071 actions completed.
[INFO] 1m 2s elapsed, 2485/4080 actions completed.
Rescheduling failed request...
[INFO] 1m 3s elapsed, 2517/4080 actions completed.
... (elided a few lines here)
[INFO] 1m 24s elapsed, 2582/4146 actions completed.
[INFO] 1m 26s elapsed, 2582/4146 actions completed.
Rescheduling failed request...
[INFO] 1m 29s elapsed, 2626/4146 actions completed.
[INFO] 1m 30s elapsed, 2680/4153 actions completed.
[INFO] 1m 32s elapsed, 2710/4159 actions completed.
[INFO] 1m 33s elapsed, 2710/4159 actions completed.
Rescheduling failed request...
[INFO] 1m 34s elapsed, 2745/4159 actions completed.
[INFO] 1m 35s elapsed, 2797/4162 actions completed.
[INFO] 1m 36s elapsed, 2805/4162 actions completed.
[INFO] 1m 37s elapsed, 21/4[INFO] 13m 49s elapsed, 4411/4774 actions completed.

Done: Job Cancelled

[INFO] 15m 13s elapsed, 4796/4812 actions completed.
... (and this continues, frozen at 4796 actions completed)
```

cc @kwalrath @matanlurey @kevmoo

**Comment by matanlurey** [comment]
I'm confused why you are using `test` and `--delete-conflicting-outputs`. Is that important?

**Comment by natebosch** [comment]
According to the travis log this was with `build_runner 0.8.1`

It's possible that https://github.com/dart-lang/build/pull/1208 broke something here.

How reliably does this repro?

**Comment by chalin** [comment]
Oops, that's a copy-paste error (that used to be `build_runner build` command, rather than `test`). I'm assuming that that shouldn't be the cause of this problem, right?

**Comment by chalin** [comment]
> How reliably does this repro?

I can't reproduce it locally (on MacOS), but on Travis, it has happened every time I restart the job.

**Comment by natebosch** [comment]
Could you try a dependency_override to force version `0.8.0` and see if it still happens?

**Comment by chalin** [comment]
Will try that now.

**Comment by chalin** [comment]
> Could you try a dependency_override to force version 0.8.0 and see if it still happens?

Travis job is https://travis-ci.org/dart-lang/stagehand/jobs/359958482 in case you want to track progress.

**Comment by chalin** [comment]
That allowed the build to complete, but

- There are still those "Rescheduling failed request" message
- The build took 7 min (it takes less than 1 min locally)

> Succeeded after 7m 26s with 5816 outputs

**Comment by natebosch** [comment]
I suspect the rescheduling is caused by running low on memory or something and the DDC process getting killed.

**Comment by chalin** [comment]
Ah, ok. I'll switch to `sudo: require` then.

**Comment by chalin** [comment]
Actually, with `sudo: require` all these problems have gone away. And I confirm that with the latest `build_runner`, tests are passing now.
