### ISSUE TITLE
Warn when we detect <8GB of RAM?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1222]
re: https://github.com/dart-lang/build/issues/1218#issuecomment-377331025.

We might want to:
* Automatically run in low resource mode
* Warn the user, and recommend low resource mode
* At least warn the user, perhaps pointing to docs showing common errors in low-memory CIs

**Comment by matanlurey** [comment]
I wish. Only searching I found was https://github.com/mezoni/system_info/blob/469aaebb338f0f8c461b157542cab793ac3967a3/lib/src/system_info.dart#L503-L520.

... but maybe there are other ways to do this (or we can ask the Flutter/VM team to help).

**Comment by DanTup** [comment]
Are you talking about total memory, or available? (just because I have 8GB doesn't mean that 6GB of it isn't used by my electron apps ;-))

**Comment by jakemac53** [comment]
Going to close this as its difficult to detect and we have resolved a lot of our memory issues so that CI environments shouldn't generally require --low-resources-mode any more.
