### ISSUE TITLE
Improvement: Implement cancel build with serve

### ISSUE THREAD

**Issue by serates** [dart-lang/build#1226]
I have noticed that every time i change a file or group of files while running build_runner serve That instead of cancelling the current build it queues a new build per file change. Due to my builds being slow 1m+ in incremental build mode, this makes a simple change between a html template and dart file take significant amount of time to incrementally build. 

If you could look into having the change detector be parallelized so that it can potentially cancel an in-progress build on an additional change. This will save a huge amount of time.

* Dart SDK: 2.0.0.dev - 43
* Packages: build_runner 0.8.1, AngularDart 5 alpha 9
* Builders: built_value, graphql (custom): Generates serialization to graphql queries for built value objects, state( custom )builds a reduxer reducer list for built_value objects.
* Platform: MacOSX
* Chrome, Firefox

**Comment by jakemac53** [comment]
This is an option - but I think it would be more beneficial to just reduce build times enough that its no longer necessary.

Can you do a build with `--track-performance` and navigate to `/$perf` in the browser and send us a zip file of that page? Ideally a representative slow incremental build is what we want to look at.

**Comment by serates** [comment]
I'll see if i can get a new one, I have recently extracted my builders out to a separate package, but it hasn't really done much. This performance group was taken with alpha 7 of angulardart and was the real bad. https://drive.google.com/file/d/1HWY7ZDOJrhG7q9Mu1GvyuGlAFDbKIDnR/view?usp=sharing

**Comment by jakemac53** [comment]
Given the `optional` builders and lazy pull model that creates this is not likely to help - we can't cancel builders mid-build safely and we start the vast majority of builders up front.
