### ISSUE TITLE
Improvement: Prevent full package rebuild on isolated builder changes

### ISSUE THREAD

**Issue by serates** [dart-lang/build#1227]
From a discussion on gitter and investigation it became apparent that build_runner is rather naive with builders that are in the package you are developing. It assumes by default that all builders can change all packages in a project including all dependencies. As such when a developer changes a builder in his project it causes a full rebuild of all included dart code (which is very very very slow).

I would like build to either utilize the generate_for list of a builder config to determine whether a builder actually needs to rebuild certain dependencies. For example if i define a builder in a library A that has generate_for: lib/*_state.dart and is only going to apply to dependents of library A, if library A changes we shouldn't be rebuilding packages that don't depend on A.

Another option is to add a build.yaml config to manually tell build that this builder only impacts files within the package it is declared in, etc. Doing this could significantly improve build time. I know i received alot of push back on this in gitter but this really would have a huge impact on build time. I could go potentially from 1m - 6m build times to a consistent <1m build time. cause i don't have to rebuild angular everytime i fix a bug in my state tree.

This is being triggered in my project because i define two custom builders that run only on the code in my package itself (does nothing on any dependency code). 

GraphQL Builder: Generates specific serializers that transform built_value objects into GraphQL Queries
State Builder: Helps implement an OOP version of a Redux model by auto generating reducer mappings and tree traversal for state.

But because these builders are defined in my project where they have impact, they cause a full rebuild of all dependencies whenever i change graphql or state.

**Comment by serates** [comment]
Dart SDK: 2.0.0-dev.43
Build: 0.8.1
Packages: AngularDart 5 alpha+9
Builders: built_value + the ones mentioned above

**Comment by jakemac53** [comment]
Yes this is a known issue but is non-trivial to get right. Today we invalidate the entire build if any dart file in the build script itself changes. We could theoretically check only the transitively reachable imports from each builder factory import, and only invalidate the outputs of those builders when those change.

**Comment by natebosch** [comment]
> We could theoretically check only the transitively reachable imports from each builder factory import, and only invalidate the outputs of those builders when those change.

Yeah I played around with this idea a bit and the complexity gets pretty high pretty quick. We _might_ be able to generate some code that creates a artificial script with only the `import` for a given factory and runs it in an Isolate and then reports back the transitively reachable imports.

**Comment by serates** [comment]
@natebosch Could you point me to where in the code it invalidates dependencies on this sort of thing, I just want to run a few experiments on my side (kind of a just in case there is something else i can fix in my code)

**Comment by natebosch** [comment]
We monitor for changes with [`BuildScriptUpdates`](https://github.com/dart-lang/build/blob/a2ee9fa2ddbe538c9802f777e6b458fab9b2b8f7/build_runner/lib/src/changes/build_script_updates.dart). It looks for the URIs loaded in the current VM, filters it down to the ones it cares about, then the watcher which is collecting changed files on disk and feeding them to run new builds checks whether any of the changes files [impact the build script](https://github.com/dart-lang/build/blob/a2ee9fa2ddbe538c9802f777e6b458fab9b2b8f7/build_runner/lib/src/generate/watch_impl.dart#L191)
