### ISSUE TITLE
Consider moving some logic from `createMergedDir` into a implementation of AssetReader

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1239]
https://github.com/dart-lang/build/pull/1238 will introduce `FinalizeAssetReader` which includes some logic for hiding deleted files from the "view" of a full build. The merged output directory and the server share very similar constraints around what assets they should expose. #1033 is open to re-implement logic for "hiding" certain assets in the server.

We should consider whether we can solve both of these use cases with a single implementation.

**Comment by jakemac53** [comment]
We now have a `FinalizedAssetsView` and `OptionalOutputsTracker` which generalize these things a bit. Would you consider this implemented @natebosch ?

**Comment by natebosch** [comment]
yeah I think this is probably as good as we can hope for, for now.
