### ISSUE TITLE
Add --symlink flag which changes the -o directory to be all symlinks

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1242]
This would speed up running tests or development scenarios where people need a merged output dir.

**Comment by jakemac53** [comment]
To clarify, if we use symlinks not only will the first creation of the merged dir be faster but we also should be able to leave in place any existing links. We only have to delete any links to deleted files and add new ones for new files.

**Comment by matanlurey** [comment]
Huge +1 (for compatible systems, at least).

I'd love to see this be the default for POSIX (with an opt-out as `--no-symlinks`)

**Comment by jakemac53** [comment]
I think we will need to start this as opt-in only, since the main supported use case of the output directory is for deployment.

For the test command we will automagically use the symlink option though, which is the other code path that is affected by this (and the main motivation for fixing it too).
