### ISSUE TITLE
Creating a merged output dir on windows is slow

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1247]
It seems to be almost a full 10x slower, even with an SSD.

**Comment by jakemac53** [comment]
It looks like general builds are a fair bit slower on windows as well - this could be related to scratch spaces possibly and general file I/O?

**Comment by lexaknyazev** [comment]
Here's a small repro with the same 10x ratio (windows vs linux). Tested on Dart SDK 2.0.0-dev.62.0.
```dart
import 'dart:io';
import 'dart:typed_data';

void main() {
  final bytes = new Uint8List.fromList(const [0x00, 0x01, 0x02, 0x03]);
  final sw = new Stopwatch()..start();
  for (var i = 0; i < 1500; ++i) {
    new File('tmp/tmp/tmp/$i')
      ..createSync(recursive: true)
      ..writeAsBytesSync(bytes);
  }
  sw.stop();
  print(sw.elapsedMilliseconds);
}
```

**Comment by jakemac53** [comment]
Thanks for looking into that @lexaknyazev, that is definitely interesting and helps confirm my suspicions... not sure if this is an SDK issue or what?

**Comment by lexaknyazev** [comment]
I've just tried to mimic IO activity of `_createMergedOutputDir/_writeAsset/_writeAsBytes` from [create_merged_dir.dart](https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/create_merged_dir.dart).

Given that this snippet has nothing to do with `package:build`, I'd say that it's either a bad IO access pattern on windows or an SDK issue.

**Comment by jakemac53** [comment]
We can try switching to async file writes as well - that might resolve these issues sufficiently.

**Comment by jakemac53** [comment]
Looks like switching to async file writes mitigates this significantly - it reduces the overhead to about ~3x. I will be sending out a cl for that shortly.

**Comment by lexaknyazev** [comment]
I've found two more ways to improve this.
- Disable Windows Defender for the `build` directory (probably it's worth to add this to the docs).
- Run `build_runner` without IntelliJ running (my guess is that `fsnotifier64.exe` affects IO).

**Comment by jakemac53** [comment]
accidentally closed this with the message in #1569

**Comment by jakemac53** [comment]
Confirmed that disabling Windows Defender cuts this time in ~half again - I don't use intellij but I did see an additional ~20% improvement by outputting to a directory that wasn't open in vscode.

I think once we document those two best practices we can close this issue.

**Comment by jakemac53** [comment]
Maybe "best practices" wasn't the best wording there lol but in any case landing the docs now haha
