### ISSUE TITLE
Add docs about migrating from barback/transformers

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1249]
Need something to link to for https://github.com/dart-lang/site-www/blob/master/src/tools/pub/obsolete.md

**Comment by kevmoo** [comment]
@matanlurey was this page meant to just be a high-level discussion? Or should we have another page that talks about migration?

**Comment by natebosch** [comment]
I think if we want to focus on specifics of moving from the `Transformer` interface to the `Builder` interface it should be a different page. `transforming_code.md` is a higher level discussion about the types of code people might want to output and the limitations of the build system and will be interesting well after we're done migrating from barback.

**Comment by kevmoo** [comment]
> I think if we want to focus on specifics of moving from the Transformer interface to the Builder interface it should be a different page.

ack. Renaming...

**Comment by kevmoo** [comment]
We do have https://github.com/dart-lang/build/tree/master/build#differences-between-the-build-package-and-pub--barback

Should this be its own doc?

**Comment by kevmoo** [comment]
This is a start: https://github.com/dart-lang/build/blob/master/docs/from_barback_transformer.md

**Comment by natebosch** [comment]
I think our documentation seems to be sufficient. We have not had many questions about the transition other than how to work around the restrictions of not having overwriting.
