### ISSUE TITLE
Stop requiring `target` and `build_extensions` from builders config

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1258]
Until we actually have a need for these, just confuses docs

**Comment by natebosch** [comment]
These were forward-looking fields that would, in theory, make it possible to start using bazel without adding additional config. In practice we're not validating them and realistically aren't going to get around to adding validation. We can leave the parsing in and allow them so it's not a breaking change, but we should stop requiring them and remove references to them from our documentation.

**Comment by natebosch** [comment]
Is it worth the breaking change? The alternative is to parse them and ignore them, and allow them to be null/missing.

**Comment by jakemac53** [comment]
I do actually think its worth removing them - when we have another breaking change to roll it up with.

**Comment by kevmoo** [comment]
Hrm...fair...

**Comment by kevmoo** [comment]
Could we get a `0.2.6` out w/ this ASAP? Then the new build_runner release could depend on it.

...and we can start migrating folks!

**Comment by natebosch** [comment]
can roll this out independent of build_runner release, folks who want to use this (should) already have a dependency on build_config and can bump their dep to be sure that the fields are optional.
`build_runner` was already ignoring them.
