### ISSUE TITLE
DDC builders memory usage can be reduced

### ISSUE THREAD

**Issue by yury-yufimov** [dart-lang/build#1272]
I have a project with DDC builders setted up as in readme:
[README](https://github.com/dart-lang/build/blob/master/build_web_compilers/README.md#manual-usage)

It seems, that without lowResourceMode project can't be built on my machine at all.
With lowResourceMode it's possible, but take too much time, so I've investigated, what happens without lowResourceMode. My best guess is following:

Every builder (module, summaries, compiler) is marked as optional.
When entry point builder starts working, all dependent assets added to queue for building.
When any builder starts its build, it continues until first `await`. 
Then next builder (from queue) starts working, also till first `await`.
Process continues until builders for every asset is added to queue, but none of them can be completed, until every builder finishes all work before last `await` in its code.
So, none of the local variables (e.g. `transitiveDeps` from linked summary builder), can be cleaned up by GC.
It seems, that my machine can't finish normal build, because it tries to compile every asset in parallel, without posiibility to clean local variables, needed by any builder.

What fix I can suggest:
There can be some pool of resources for builders: do not start compiling new asset, until compilation of any previous N assets is finished.
Or may be there are some flags of dartVM, which can manage behaviour of async-await, but I couldn't find any.

Used versions:
Dart VM version: 2.0.0-dev.46.0 on "macos_x64"
build_runner: 0.8.1
build_modules: 0.2.0+2
build_web_compilers: 0.3.5

**Comment by natebosch** [comment]
Good digging!

I think this worst case should only happen on the first build with no cached asset graph (or after a pub upgrade). Incremental builds more eagerly build expected inputs and, I think, more serially.

I don't know if we can limit to a pool of builds without risking deadlock, but we should take a look at whether we can use less memory before triggering the other builds,. Or make it possible to free it.

Using larger modules for ddc could also help here.

**Comment by natebosch** [comment]
I think there are a couple ways that we can improve this.

- #1186 should mean fewer over all actions, and each action should be cheaper in terms of memory use.
- We could potentially limit how many non-optional tasks we start at a time. Today for very "wide" packages (especially those with a lot of tests) there could be a lot of primary inputs to the non-optional DDC step and we use `Future.wait` to start them all. If we limit this then it could reduce the "first level" of the memory used, though the transitive crawling will still exist.
