### ISSUE TITLE
build_web_compilers is not able to correctly set value of `baseUrl` variable.

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/build#1279]
For example, when root URL of an Angular Dart 5 application is `https://example.com/toolkit_for_facebook/`

and `index.html` includes following tag
`<base href="/toolkit_for_facebook/">`

Then script generated by `build_web_compilers` should be able to properly set values for `baseUrl` variable but it does not and gives errors as shown in following image.

![baseurlerr](https://user-images.githubusercontent.com/8603858/38583336-4aede7e2-3d30-11e8-8b59-e12dd98bf808.png)

build_web_comppiler version:
version: 0.3.4+2

OS:
Arch linux X64

Dart version:
Dart VM version: 2.0.0-dev.38.0 (Thu Mar 15 16:53:42 2018 +0100) on "linux_x64"

**Comment by natebosch** [comment]
Yeah I think we will need to add some config for this.
Tracking at https://github.com/dart-lang/build/issues/1087
