### ISSUE TITLE
Warn when attempting to create a merged output from a top-level directory that doesn't exist

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1297]
`pub run build_runner build --output not_here:build` should print a warning and a non-zero exit code.

We _should_ support the case where `not_here` doesn't exist until the build happens though.

**Comment by kevmoo** [comment]
@nshahan does this trick in angular_component_examples where web doesn't exist – but it's synthesized in the build.

So don't break that – or maybe through if `web` is never created?

**Comment by kevmoo** [comment]
> So don't break that – or maybe through if web is never created?

I read the top comment. Glad it's our our radar, @natebosch
