### ISSUE TITLE
Uncaught exceptions cause a serve log message but do not print the StackTrace

### ISSUE THREAD

**Issue by nshahan** [dart-lang/build#1299]
The StackTrace is not being logged:
https://github.com/dart-lang/build/blob/master/build/lib/src/builder/logging.dart#L27

But adding the StackTrace to the log.severe still does not print it during the build even when running in `--verbose`.

To get it to print I had to use the StackTrace as the log message.

**Comment by jakemac53** [comment]
We should be logging the stack trace here https://github.com/dart-lang/build/blob/master/build_runner/lib/src/logging/std_io_logging.dart#L40 - I wonder if all the frames could be getting folded by the code there.

**Comment by natebosch** [comment]
Yeah I can see this when I include the stack trace argument to the `log.severe`...
