### ISSUE TITLE
Improve error reporting / stacktrace in Chrome with devcompiler

### ISSUE THREAD

**Issue by Meai1** [dart-lang/build#1328]
Dart VM version: 2.0.0-dev.49.0 (Wed Apr 18 20:41:36 2018 +0200) on "linux_x64"
build_runner-0.8.3
Chrome

Is it possible to make the following error a lot simpler to parse mentally? As you can see, I have to look quite hard to find the error message and location I care about: 
![devc error](https://user-images.githubusercontent.com/1112157/39092038-6819bd6a-4603-11e8-8368-d82bf3062a89.png)
In my opinion the `CharFuncs:23` should be clickable on the right as the first link, without having to expand the whole list. All or most of the darksdk.js functions are probably something I dont need to know about at all... And the message "Value not in range" should be at the top next to the red "uncaught"

**Comment by natebosch** [comment]
This is something we're hoping to fix soon. Track at https://github.com/dart-lang/build/issues/1151
