### ISSUE TITLE
Support command line args autocomplete via the completion package 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1338]
Lots of moving parts here to get things working via `pub run ...` but we could start by just adding the basic support for directly invoked scripts, and according to kevin we can get it to work via aliases as well.

**Comment by jakemac53** [comment]
@natebosch @grouma considering adding this to Q2 objectives, wdyt? It could provide a lot of value.

**Comment by grouma** [comment]
Feel free to add it to the Q2 objectives but I think there are a lot of higher priority items.

**Comment by jakemac53** [comment]
I will leave it off Q2 objectives for now - will need to wait until we get some support from pub I think
