### ISSUE TITLE
Discussion: create a separate target for non-lib sources in the root package

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1342]
The reasoning here is that it would allow us to eliminate most cyclic dependencies. In practice, the majority of package cycles I have see are as a result of the "dev_dependencies", not regular "dependencies".

Today, for the root package, we create a single default target with the `$default` alias. This target contains sources in all whitelisted directories and all dependencies listed in the pubspec.

Instead, we could create two targets (or possibly more):

- `lib`: all the sources under lib, only the regular `dependencies`, not `dev_dependencies`.
- `app`: all sources excluding `lib` (or possibly one per top level dir), and all `dependencies` plus `dev_dependencies`.

This would eliminate most package cycles we know about, which can trigger bad build-time behavior (falling back on fined grained modules for one). This also makes builds more predictable, because there are better ordering guarantees if you don't have cycles (all your dependencies outputs will be available).

This also opens the door to a different type of package filter, such as `toEntrypointTargets` (or something like that), which would never apply to the `lib` targets. This could speed up glob checking in the root package. Today compilers that never run on lib have to exclude that directory with a `generate_for` default glob, which requires a potentially large amount of work startup for builds (I believe @natebosch fixed this so the cost isn't incurred on incremental builds though?).

**Comment by jakemac53** [comment]
The biggest issue I see here is making things easily configurable, today the `$default` alias is a nice shorthand.

One option for this would be to make `$default` be special, and actually builder options to both default targets, but then it is hard to understand what it would mean to supply `srcs` to the `$default` target.

**Comment by natebosch** [comment]
My concerns revolve around how this will impact configuration.

If I want to set options to some builder which is applied across my package, both lib and non-lib, I'd now need to specify those options twice, once for each target.

**Comment by natebosch** [comment]
This isn't an issue configuring builders on packages they don't author - it's configuring builders on their own package.

Imagine I need angular to run on `lib/` for my components and `web/` for my `main.dart`. Imagine also that there is some configuration that I need to apply to angular just for my package.

Today it's:

```yaml
targets:
  $default:
    builders:
      angular:
        options:
          some: 'config'
```

If we force lib and non-lib to be different targets we risk this becoming:

```yaml
targets:
  $default:
    builders:
      angular:
        options:
          some: 'config'
targets:
  $entrypoints:
    builders:
      angular:
        options:
          some: 'config'
```

So that's why we're considering whether we can have some way to configure builders across targets, and whether `$default` should mean configuring a builder for the whole package... but then things like `sources` _must_ be ignored for `$default` so we're in a tricky spot...

**Comment by jakemac53** [comment]
Going to close this as not planned, it would be nice but I think the ship has sailed
