### ISSUE TITLE
Don't create a package directory if there are no files under the package

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1348]
If we have a PostProcessBuilder that remove dart source files a package in the output could become empty. We should probably just not write it at all.

**Comment by jakemac53** [comment]
Will we actually create it? I thought we lazily created the directories.

**Comment by natebosch** [comment]
when I was trying https://github.com/dart-lang/build/pull/1350 I noticed empty directories

**Comment by natebosch** [comment]
I think you're right. Maybe what we need to look at is cleaning up directories if we remove everything from them...

**Comment by jakemac53** [comment]
Ya, possibly a pass at the very end of creating the merged output dir that just deletes empty dirs? We could delete pre-existing dirs though (if outputting to a "merged" directory).
