### ISSUE TITLE
Throw a helpful error if `log` is not available

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1377]
https://github.com/dart-lang/build/blob/a466ff0d237bebeed27ad578cd97601ff0bbadfc/build/lib/src/builder/logging.dart#L10

Now the user ends up with some 

```
NoSuchMethodError: The method 'severe' was called on null.
Receiver: null
```

Better to check in the `log` getter and throw a `Not supported...` something something...

**Comment by natebosch** [comment]
Or maybe set up a global logger?
