### ISSUE TITLE
Build runner fails to generate JSON serialization files for json_serializable package

### ISSUE THREAD

**Issue by Dkrinker** [dart-lang/build#1422]
Issue happens when I run the command: "flutter packages pub run build_runner build" to generate the JSON serialization files for json_serializable package

Fails to build generated json serialization files

* Dart Version: Dart 2.0.0-dev.48.0.flutter-fe606f890b
* Build Runner version: 0.8.8
* Using MacOSX 10.13.5
* Using IntelliJ IDEA 2017.3.5

The following error is reported:
__________________________________

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

NoSuchMethodError: The getter 'inputs' was called on null.
Receiver: null
Tried calling: inputs
dart:core                                                       Object.noSuchMethod
package:build_runner/src/asset_graph/serialization.dart 58:23   _AssetGraphDeserializer.deserialize
package:build_runner/src/asset_graph/graph.dart 42:52           new AssetGraph.deserialize
package:build_runner/src/generate/build_definition.dart 194:31  _Loader._tryReadCachedAssetGraph.<fn>
package:build_runner/src/logging/logging.dart 25:30             logTimedAsync
package:build_runner/src/generate/build_definition.dart 192:12  _Loader._tryReadCachedAssetGraph
package:build_runner/src/generate/build_definition.dart 81:28   _Loader.prepareWorkspace
package:build_runner/src/generate/build_definition.dart 65:12   BuildDefinition.prepareWorkspace
package:build_runner/src/generate/build_impl.dart 112:29        _singleBuild
package:build_runner/src/generate/build_impl.dart 101:20        build
package:build_runner/src/generate/build.dart 70:5               build
package:build_runner/src/entrypoint/options.dart 359:24         _BuildCommand.run
package:args/command_runner.dart 194:27                         CommandRunner.runCommand
package:args/command_runner.dart 109:29                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 109:11                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31              run
.dart_tool/build/entrypoint/build.dart 11:22                    main

Missing some or all of the above might make the issue take longer or be impossible to act on.

Below is a sample dart class to be serialized:
________________________________________________

import 'package:json_annotation/json_annotation.dart';
import 'rest-error.dart';

part 'server-info.g.dart';

@JsonSerializable()

class ServerInfo extends Object with _$ServerInfoSerializerMixin {
  final RestError error;
  final String macAddress;
  final String hostName;
  final int restPort;
  final String restVersion;
  final String productVersion;
  final String ipAddress;

  ServerInfo(this.error,
      this.hostName,
      this.ipAddress,
      this.macAddress,
      this.productVersion,
      this.restPort,
      this.restVersion);

  factory ServerInfo.fromJson(Map<String, dynamic> json) =>
      _$ServerInfoFromJson(json);
}

Thank you

**Comment by jakemac53** [comment]
Interesting, its actually failing to deserialize the asset graph from a previous run it looks like.

Did you try deleting your `.dart_tool/build` directory and re-running?

Definitely a bug here it looks like but that might get you unblocked.

**Comment by jakemac53** [comment]
Oh also note that `@jsonserializable()` I believe should be `@JsonSerializable()`, but this is a bug either way.

**Comment by Dkrinker** [comment]
deleting the contents in .dart_tool/build seemed to clear the issue.  Thanks.  Noted on the @JsonSerializable() attribute although it did work.

**Comment by Dkrinker** [comment]
nvm.  The original source is @JsonSerializable() not sure why it got lowercased above.

**Comment by baoxiehao** [comment]
Deleting the .dart_tools/build is NOT working for me, SO strange. I've struggled for days...

[INFO] Generating build script...
[INFO] Generating build script completed, took 363ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 10.8s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 635ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] 1.0s elapsed, 2/18 actions completed.
[INFO] 2.2s elapsed, 4/18 actions completed.
[INFO] 3.2s elapsed, 4/19 actions completed.
[INFO] 10.4s elapsed, 18/19 actions completed.
[INFO] 11.5s elapsed, 42/42 actions completed.
[WARNING] json_serializable on lib/hisun/asset.dart:
Missing "part 'asset.g.dart';".
[WARNING] json_serializable on lib/hisun/login.dart:
Missing "part 'login.g.dart';".
[WARNING] json_serializable on lib/hisun/currency.dart:
Missing "part 'currency.g.dart';".
[WARNING] json_serializable on lib/hisun/summary.dart:
Missing "part 'summary.g.dart';".
[INFO] Running build completed, took 11.9s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 100ms

[INFO] Succeeded after 12.0s with 0 outputs (124 actions)
