### ISSUE TITLE
The include/exclude keys may exist with null values - causing NPE

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1424]
See https://github.com/dart-lang/build/blob/b634c1f5cfd36af3f722c577c8e5f9fddeae01a3/build_config/lib/src/parse.dart#L409-L414

Maybe treat null value as empty?

**Comment by natebosch** [comment]
What does the yaml look like to hit this case?

**Comment by kevmoo** [comment]
```yaml
include:
```

**Comment by jakemac53** [comment]
With the change to JsonSerializable we don't crash any more, but we also don't report an error which we probably should?

**Comment by jakemac53** [comment]
Closing this, I don't think we need to retain the explicit error in the case
