### ISSUE TITLE
build_runner bug: The getter 'target' was called on null

### ISSUE THREAD

**Issue by chalin** [dart-lang/build#1426]
I'm attempting to upgrade the Angular example apps to use [pageloader 3.0.0-dev (master@HEAD)](https://github.com/google/pageloader).

I've updated the toh-1 example app, but when I try to build, I get the message:

- **You have hit a bug in build_runner**

Here is part of the log:

```
> pub run build_runner build
[INFO] Generating build script completed, took 273ms


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


NoSuchMethodError: The getter 'target' was called on null.
Receiver: null
Tried calling: target
dart:core                                                          Object.noSuchMethod
package:build_runner/src/package_graph/apply_builders.dart 250:22  createBuildPhases.<fn>
package:graphs/src/strongly_connected_components.dart 44:24        stronglyConnectedComponents.strongConnect
package:graphs/src/strongly_connected_components.dart 66:55        stronglyConnectedComponents
package:build_runner/src/package_graph/apply_builders.dart 248:18  createBuildPhases
package:build_runner/src/generate/build_impl.dart 93:29            build
package:build_runner/src/generate/build.dart 70:5                  build
package:build_runner/src/entrypoint/options.dart 359:24            _BuildCommand.run
package:args/command_runner.dart 194:27                            CommandRunner.runCommand
package:args/command_runner.dart 109:29                            CommandRunner.run.<fn>
dart:async                                                         new Future.sync
package:args/command_runner.dart 109:11                            CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31                 run
.dart_tool/build/entrypoint/build.dart 81:22                       main
```

**Steps to reproduce:**

- Get a copy of the site-webdev branch associated with PR
  https://github.com/dart-lang/site-webdev/pull/1585
- `cd examples/ng/doc/toh-1`
- `pub get`
- `pub run build_runner build`

**Environment:**

- Dart VM version: 2.0.0-dev.53.0 (Thu May 3 12:35:47 2018 +0200) on "macos_x64"
- For package versions, see the PR's `pubspec.lock` file, but essentially:
  - `build_runner` 0.8.8
  - `pageloader` @HEAD of master.

cc @kevmoo @kwalrath

**Comment by natebosch** [comment]
So the issue is https://github.com/google/pageloader/blob/3aa5db304e55068a966e1057d37fc2f704bfa5a8/build.yaml does not have a target matching the package name which is supposed to be required.

We used to have a check that the default target with the same name as the package exists, but it was erroneously removed in https://github.com/dart-lang/build/pull/1261

**Comment by kevmoo** [comment]
@natebosch – should we have an issue/PR for pageloader here?

**Comment by natebosch** [comment]
We could track it with an issue in that repo if you want, I was going to open a PR with a link to this issue.

**Comment by kevmoo** [comment]
SGTM!

**Comment by chalin** [comment]
Just to be clear, who will be tackling the fix on the pageloader side? /cc @mk13

**Comment by natebosch** [comment]
>Just to be clear, who will be tackling the fix on the pageloader side?

https://github.com/google/pageloader/pull/128

**Comment by natebosch** [comment]
When I switch to a pageloader dependency on that commit I hit a new error:

```
DuplicateAssetNodeError: GeneratedAssetNode: angular_tour_of_heroes|lib/hero.g.dart generated from input angular_tour_of_heroes|lib/hero.dart.
This probably means you have multiple actions that are trying to output the same file.
```

Can probably hack around this with a careful `generate_for` for now. In the longer term we want to fix this with a combining builder in source gen.

https://github.com/dart-lang/source_gen/issues/319

**Comment by chalin** [comment]
My understanding of builder config files and how to use them is _very_ rudimentary. For example, I don't even know if the toh-1 project requires its own build.yaml file or not (I would suspect not).

Note that the single toh-1 file that pageloader is supposed to process is under `test/**` (there are none under `lib/**`), so maybe the new `$default` that you added via https://github.com/google/pageloader/pull/128 isn't what is needed?

I've tried various incantations using `generate_for`, but I can't get the build to go through. If you could get it to work, and let me know how you did it, that would be grand.

**Comment by mk13** [comment]
For pageloader, should we provide a temporary build.yaml template file that users can copy and paste into their application until the long term solutions is implemented?

**Comment by chalin** [comment]
SGTM: if you provide me with such a temporary build.yaml, I'll give it a try.

**Comment by mk13** [comment]
Can you try copying the build.yaml file here: https://github.com/mk13/pageloader/blob/master/build.yaml

without the `builders` section?

**Comment by natebosch** [comment]
@mk13 If you expect most projects will keep their page object definition under `test/` you can add a default `generate_for` for them.

```yaml
builders:
  pageloader:
    import: "package:pageloader/builder.dart"
    builder_factories: ["pageloaderBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for: ["test/**"]
```

**Comment by mk13** [comment]
Sure, I'll also add "testing/**" as well in the template since some users may distinguish them.

Patrice can you verify if Nate's example fixes your issue? If so, I'll add this into the documentation with instructions on how to configure it.

**Comment by chalin** [comment]
I had tried that already config earlier today, and it **doesn't** make [the error that Nate reported earlier](https://github.com/dart-lang/build/issues/1426#issuecomment-388510037) go away:

```nocode
> pub run build_runner build --config po
[INFO] Generating build script completed, took 277ms
[INFO] Building new asset graph...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


DuplicateAssetNodeError: GeneratedAssetNode: angular_tour_of_heroes|test/app_test.g.dart generated from input angular_tour_of_heroes|test/app_test.dart.
This probably means you have multiple actions that are trying to output the same file.
package:build_runner/src/asset_graph/graph.dart 468:11          AssetGraph._addGeneratedOutputs
...
```

**Comment by mk13** [comment]
Try changing your pubspec.yaml to:

```
dependencies:
  pageloader:
    git: git@github.com:mk13/pageloader.git
```

I've added a change in my repo further restricting Pageloader to only files labeled as `*_po.dart` within 
`test/` or `testing/`. Also ensure that this file doesn't contain any Angular code-gen entry points.

I think this should work. If it does, what we can do is require users to label their files as `*_po.dart` with instructions to not use other code-gen packages in these files. Later on, when the long term fix is added, we can relax on this restriction.

**Comment by chalin** [comment]
> Also ensure that this file doesn't contain any Angular code-gen entry points.

Yeah, that is the problem with the toh-1 example. It is a simple all-in-one-file example (and so that file is also an Angular entry point). I'm trying the new build script on toh-2 now (since the PO file is separate). I'll let you know how it works.

**Comment by chalin** [comment]
Is there a way to run the pageloader builder only?

**Comment by chalin** [comment]
Nm, I got it to work for the toh-2 example app using the a local build.yaml file (and PO files separate from ng entry point files)! \o/

I'll share what I have tonight if I can, otherwise, it'll be tomorrow morning.

**Comment by chalin** [comment]
> If it does, what we can do is require users to label their files as `*_po.dart` with instructions to not use other code-gen packages in these files. Later on, when the long term fix is added, we can relax on this restriction.

SGTM

**Comment by natebosch** [comment]
> Is there a way to run the pageloader builder only?

Not exactly. You could explicitly disable the other builder but that means it's always disabled, not just disabled for one build.

**Comment by chalin** [comment]
FYI, I've pushed the updated toh-2 component tests that are currently passing with pageloader 3; see https://github.com/dart-lang/site-webdev/pull/1585. I'll finish converting the other tests tomorrow.

**Comment by chalin** [comment]
We have an acceptable workaround for this. Closing.
