### ISSUE TITLE
Enable full app kernel generation

### ISSUE THREAD

**Issue by grouma** [dart-lang/build#1428]
Currently we support modular kernel generation. We will need to modify this workflow to enable merged kernels so that an application can be run on the VM in Dart 2 directly from kernel.

**Comment by grouma** [comment]
Note that this kernel generation will need to take into account what the target platform is. It is likely that we can infer the platform when creating the `.module` files since we are parsing the Dart source.

**Comment by natebosch** [comment]
Is the Vm unable to run from multiple kernel files?

**Comment by grouma** [comment]
Unfortunately our tests indicate no.

**Comment by mraleph** [comment]
You can concatenate multiple files into a single file and emit a multicomponent Kernel file. That should be supported by the VM. 

/cc @jensjoha

**Comment by grouma** [comment]
Do you need a special delimiter? When @jakemac53 and I ran some tests we weren't able to get the application to run when we did a simple byte concatenation.

**Comment by jakemac53** [comment]
I think there is some other issue at play there, I can follow up once I look at it with Siggi.

I couldn't get it working even with a single full kernel file generated from the current worker code, I think it needs to be updated in some way.

**Comment by jakemac53** [comment]
Note that I have full app kernel generation working now for really basic examples after working a bit with @sigmundch .

However, if I try to run a test I am getting errors. My guess is this is related to how we are doing the concatenation.

@mraleph is there a specific api we need to use to combine multiple kernel files (today its just literally mashing the files together). Or maybe we have to do it in a specific order?

**Comment by jakemac53** [comment]
Fwiw, the error I am getting is the following:

```
NoSuchMethodError: The getter 'suite' was called on null.
Receiver: null
Tried calling: suite
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      Engine._runLiveTest (package:test/src/runner/engine.dart:351:23)
<asynchronous suspension>
#2      Engine._runGroup (package:test/src/runner/engine.dart:320:19)
<asynchronous suspension>
#3      Engine.run.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/runner/engine.dart:274:17)
<asynchronous suspension>
#4      new Future.sync (dart:async/future.dart:222:31)
#5      Pool.withResource.<anonymous closure> (package:pool/pool.dart:126:18)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:662:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:477:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

Which is really weird because I wouldn't expect any isolate magic to be happening when I invoke a file directly.

My intuition is that when I am modularly compiling dill files there are some with a `main` (in the test lib directory) and we actually end up invoking that directly because of that. We probably need to omit the `main` method from the full modular files, and create one extra one for bootstrapping entrypoints which only has the `main` method.

Does that sound right @sigmundch ?

**Comment by jakemac53** [comment]
Ok, so I have actually nailed this down to a more minimal repro, it doesn't have anything to do with `main` in other modules.

There is something wonky going on with the `QueueList` class from `package:collection`, only in modular mode though:

```dart
import 'package:collection/collection.dart';

main() {
  var queue = new QueueList.from(['foo', 'bar']);
  queue.add('baz');
  print(queue.first); // prints null ??
  print(queue.length); // prints 3 yay!
  print(queue); // throws
}
```

**Comment by jakemac53** [comment]
Output is as follows:
```
null
1
Unhandled exception:
NoSuchMethodError: The method 'moveNext' was called on null.
Receiver: null
Tried calling: moveNext()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      StringBuffer.writeAll (dart:core/runtime/libstring_buffer_patch.dart:94:19)
#2      IterableBase.iterableToFullString (dart:collection/iterable.dart:283:14)
#3      QueueList.toString (package:collection/src/queue_list.dart:111:37)
#4      _StringBase._interpolateSingle (dart:core/runtime/libstring_patch.dart:799:17)
#5      print (dart:core/print.dart:9:26)
#6      main (org-dartlang-app:///test/foo_test.dart:8:3)
#7      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
kernel-service: Calling main resulted in an error: isolate terminated by vm
```

**Comment by mraleph** [comment]
I wonder if this is related to how we do mixin transformation. 

I think in general @jensjoha is the right person to talk to about this sort of things.

**Comment by natebosch** [comment]
@jensjoha - can you please take a look?

**Comment by mraleph** [comment]
@jensjoha is away - I will try to find somebody else to look at this.

**Comment by jakemac53** [comment]
If you want to repro this on your own (beware this is all just prototype code), you will need to build the sdk with my branch https://github.com/jakemac53/sdk/tree/full-kernel.

Then check out my branch of the build repo https://github.com/jakemac53/build/tree/full-kernel.

Then, from the `_test` directory of the build repro, you can run `dart tool/build_kernel.dart build bin -o build`, which will create the `build` directory I provided here. You can run the generated kernel file with `dart --preview-dart-2 build/bin/hello.app.dill`.

**Comment by jakemac53** [comment]
https://dart-review.googlesource.com/c/sdk/+/58920 is the sdk change to enable this

**Comment by jakemac53** [comment]
This is published now as build_vm_compilers
