### ISSUE TITLE
Multi-platform support - with config specific imports

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1430]
Meta bug for tracking work towards supporting multiple compilation pipelines for kernel (one per platform).

- [x] Create custom module files for each platform (`.<platform>.module` etc)
  - [x] Needs to understand the platform constants that are supported by the CFE, and only crawl the correct config specific import for each platform.
    - We don't want to use actual resolution to do this, which might complicate things.
  - [x] Throw on non-whitelisted constants in config specific imports.
- [x] Create custom kernel files per platform, which consume module files for that platform only 
- [x] Update the Builders for the various backends to only consume kernel files for their platform
  - [x] DevCompiler
  - [x] Dart2Js, once we add kernel support
  - [x] VM, once we add kernel support

Outstanding questions:

- How should platform specific modules work in `fine` mode? (This uses a Resolver which is currently based on a specific platform, I am not actually sure which one).
- Should you have to specify a platform when getting a resolver?
- In general, how should Dart codegen be supported? (modules aren't computed until after Dart codegen runs).

**Comment by jakemac53** [comment]
cc @leafpetersen

**Comment by natebosch** [comment]
> We don't want to use actual resolution to do this, which might complicate things.

We should consider whether changing the criteria that imports are selected on to explicit platforms would make this easier. https://github.com/dart-lang/sdk/issues/32960#issuecomment-387924292

**Comment by jakemac53** [comment]
> Should you have to specify a platform when getting a resolver?
> In general, how should Dart codegen be supported? (modules aren't computed until after Dart codegen runs).

I worked up a separate proposal for these https://github.com/dart-lang/build/issues/1436

**Comment by jakemac53** [comment]
We should also figure out if we want to make this opt in per platform (via a dependency), or have all platforms available always.

It seems like we may need to have support baked in all the way through to support the separate Dart Codegen proposal anyways... we could even be smart about only adding in kernel builders for the platforms that are required by other builders to limit the asset graph bloat?

**Comment by jakemac53** [comment]
cc @vsmenon

**Comment by jakemac53** [comment]
This is done now - working on publishing it all (likely won't finish until tomorrow)

**Comment by jakemac53** [comment]
Note that there are still some issues in analyzer, https://github.com/dart-lang/sdk/issues/34179 and https://github.com/dart-lang/sdk/issues/34177
