### ISSUE TITLE
it is unclear where webdev emits its output files

### ISSUE THREAD

**Issue by robertmuth** [dart-lang/build#1450]
For Dart VM version: 2.0.0-dev.55.0 on linux

When I run 

webdev build --release

I see:
====
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 585ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] 4.4s elapsed, 6/10 actions completed.
[INFO] build_web_compilers|entrypoint on web/whorld.dart:Running dart2js with --minify --packages=.package-aab36fb7f7cc0560c962b151b18884a5 -oweb/whorld.dart.js web/whorld.dart

[INFO] 6.0s elapsed, 17/18 actions completed.
[INFO] 7.1s elapsed, 17/18 actions completed.
[INFO] build_web_compilers|entrypoint on web/whorld.dart:Dart2Js finished with:

Compiled 8,971,799 characters Dart to 144,422 characters JavaScript in 2.71 seconds
Dart file (web/whorld.dart) compiled to JavaScript: web/whorld.dart.js

[INFO] Running build completed, took 8.2s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 121ms

[INFO] Succeeded after 8.4s with 14 outputs (1313 actions)
======

But where does the output really go?

It looks some artifacts go under .dart_tool  which is super obscure
an there seems to be no single directory that combines .html and .dart.js
for easy webserving.

**Comment by matanlurey** [comment]
Please take a look at the getting started guide:
https://github.com/dart-lang/build/blob/master/docs/getting_started.md#creating-an-output-directory

😄

**Comment by robertmuth** [comment]
It would be less confusing if  --output were mandatory for build and maybe even for  serve.
Or, if webdev would emit a message to stdout indicating were files are being written to.

Keep in mind that people are switching from pub build and pub serve and since the commands
have the same name people can reasonably expect similar behavior.

Furthermore, the main landing page for the migration:
https://webdev-dartlang-org-dev.firebaseapp.com/dart-2
does not mention --output at all

**Comment by jakemac53** [comment]
> It would be less confusing if --output were mandatory for build and maybe even for serve.

I think for `webdev` you could make the case that `build` should default to `--output=build`, it already defaults to `--release`. If it doesn't do that already, I think its a reasonable request.

The build package itself will likely never do this though because its a general build system and is not opinionated in the same way as webdev or pub were. You can generate files directly to source as well in which case --output is completely unnecessary.

> Keep in mind that people are switching from pub build and pub serve and since the commands
> have the same name people can reasonably expect similar behavior.

Yes, `webdev` aims to be a drop in replacement and I think there is general agreement that it should produce functionally the same output.

**Comment by natebosch** [comment]
Tracking issue for webdev: https://github.com/dart-lang/webdev/issues/27
