### ISSUE TITLE
Consider adding a `reason` field to `AssetNotFoundException`, or similar

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1460]
It would be useful for error reporting from other builders if they could know why they couldn't read a certain file to provide better error messages. Some common reasons would include:

- File doesn't exist in the graph at all
- The package doesn't exist in the graph (missing dependency)
- The package isn't a dependency of the current primary input (missing direct dependency, usually would only surface in bazel but we could add the restriction in build_runner). 
- It is a generated file that failed to be built
- It is a generated file that is generated in a later phase (either a package cycle or a missing dependency probably)
- It is a generated file that the builder decided not to output
- It is a synthetic asset, or `isReadable` is false generally.

**Comment by matanlurey** [comment]
A potentially lighter-weight solution might be just a different `toString()`.

I.e. `_BuildRunnerAssetNotFoundException` and `_BazelAssetNotFoundException`.

**Comment by jakemac53** [comment]
> A potentially lighter-weight solution might be just a different toString().
> 
> I.e. _BuildRunnerAssetNotFoundException and _BazelAssetNotFoundException.

That could work, or we could just make `reason` be a String (and use it in the default `toString()`)?
