### ISSUE TITLE
Add MRU for the caching asset reader

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1461]
We can end up using a lot of memory to cache files we've read and not all of them will be reread.

**Comment by jakemac53** [comment]
Note that this can potentially cause inconsistent builds as well - by using the unbounded cache we ensure the view of a file throughout a build is consistent.

I don't think that is a blocker, as we should run another build afterwords anyways, but it might cause weird errors mid build or something.

**Comment by jakemac53** [comment]
> Or we could have an unbounded cache for source files (not generated files) in the root package and path dependencies.

Actually, this sounds fairly reasonable to me, the main downside I see is the complications it adds to the implementation but we can come up with something reasonable I think.

**Comment by jakemac53** [comment]
Note that the resolver also caches sources today, but we could change that if we use `waitFor`, which might not actually take a lot of extra work?

**Comment by natebosch** [comment]
> the resolver also caches sources today

We could share a cache pretty easily, but we'd need to make it unbounded for Dart files if we did that. Would definitely be curious to try the `waitFor` approach.

**Comment by jakemac53** [comment]
Actually, the cache might already be "shared" in that we are sharing the same instances of the strings?

**Comment by natebosch** [comment]
Some other considerations:

- Consider never caching assets that are written with `writeAsBytes` since they are less likely to be read again during the build.
- Consider more eagerly finding the `Digest` as assets are written since we know that every asset we write will have it's digest computed.
- Consider adding a maximum asset size that we cache, if a large asset is written drop it from the cache.
- Consider caching only on read rather than on write.
