### ISSUE TITLE
NoSuchMethodError: The getter 'inputs' was called on null.

### ISSUE THREAD

**Issue by slipxnot** [dart-lang/build#1463]
When i run this command in (build_runner: "^0.8.9") i m getting the below error:
`flutter packages pub run build_runner build --delete-conflicting-outputs`

NoSuchMethodError: The getter 'inputs' was called on null.
Receiver: null
Tried calling: inputs
dart:core                                                       Object.noSuchMethod
package:build_runner/src/asset_graph/serialization.dart 58:23   _AssetGraphDeserializer.deserialize
package:build_runner/src/asset_graph/graph.dart 42:52           new AssetGraph.deserialize
package:build_runner/src/generate/build_definition.dart 187:31  _Loader._tryReadCachedAssetGraph.<fn>
package:build_runner/src/logging/logging.dart 25:30             logTimedAsync
package:build_runner/src/generate/build_definition.dart 185:12  _Loader._tryReadCachedAssetGraph
package:build_runner/src/generate/build_definition.dart 75:28   _Loader.prepareWorkspace
package:build_runner/src/generate/build_definition.dart 60:54   BuildDefinition.prepareWorkspace
package:build_runner/src/generate/build_impl.dart 115:29        _singleBuild
package:build_runner/src/generate/build_impl.dart 104:20        build
package:build_runner/src/generate/build.dart 71:5               build
package:build_runner/src/entrypoint/build.dart 28:24            BuildCommand.run
package:args/command_runner.dart 194:27                         CommandRunner.runCommand
package:args/command_runner.dart 109:29                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 109:11                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31              run
.dart_tool\build\entrypoint\build.dart 11:22                    main

pub finished with exit code 1

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.4.4, on Microsoft Windows [Version 10.0.17134.48], locale en-IL)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] VS Code, 64-bit edition (version 1.22.2)
[√] Connected devices (1 available)

**Comment by jakemac53** [comment]
You can reach us on gitter as well if you would prefer to share it privately https://gitter.im/dart-lang/build

**Comment by slipxnot** [comment]
By passed it using an older version 0.8.3 and it worked, I tried to reproduce it in the other computer at work and i get another error:
```
NoSuchMethodError: No static getter 'terminal' declared in class 'StdioType'.
Receiver: StdioType
Tried calling: terminal
```
Sending the asset_graph.json in gitter channel
Thanks @jakemac53

**Comment by jakemac53** [comment]
@natebosch did we forget to bump the asset graph version at some point maybe?

**Comment by jakemac53** [comment]
> NoSuchMethodError: No static getter 'terminal' declared in class 'StdioType'.
> Receiver: StdioType
> Tried calling: terminal

Note that this is a separate bug related to the flutter sdk, see https://github.com/dart-lang/build/issues/1448

**Comment by natebosch** [comment]
> did we forget to bump the asset graph version at some point maybe?

It's entirely possible. Were you able to figure out what the difference was?

**Comment by jakemac53** [comment]
hadn't gotten a chance to look yet but I did get the asset graph file so I can check it (might not happen till next week)

**Comment by ctartamella** [comment]
I believe I'm hitting this same issue.  Running clean as suggested gives 
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


AssetGraphVersionException: saw version 15 but the current version is 21.
package:build_runner/src/asset_graph/serialization.dart 25:7  _AssetGraphDeserializer.deserialize
package:build_runner/src/asset_graph/graph.dart 42:52         new AssetGraph.deserialize
package:build_runner/src/entrypoint/clean.dart 48:17          CleanCommand.run.<fn>
package:build_runner/src/logging/logging.dart 25:30           logTimedAsync
package:build_runner/src/entrypoint/clean.dart 41:11          CleanCommand.run
package:args/command_runner.dart 194:27                       CommandRunner.runCommand
package:args/command_runner.dart 109:29                       CommandRunner.run.<fn>
dart:async                                                    new Future.sync
package:args/command_runner.dart 109:11                       CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31            run
.dart_tool\build\entrypoint\build.dart 11:22                  main

pub finished with exit code 1
```
which makes me think this could be related.  My asset graph is also here:
```
Dart SDK 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c
Flutter SDK 0.3.2
flutter_refit 0.0.1
|-- analyzer 0.31.1
|   |-- args...
|   |-- charcode 1.1.1
|   |-- cli_util...
|   |-- collection...
|   |-- convert...
|   |-- crypto...
|   |-- front_end 0.1.0-alpha.9
|   |   |-- charcode...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- kernel...
|   |   |-- meta...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- source_span...
|   |   '-- yaml...
|   |-- glob...
|   |-- html 0.13.3
|   |   |-- csslib 0.14.4
|   |   |   |-- args...
|   |   |   |-- logging...
|   |   |   |-- path...
|   |   |   '-- source_span...
|   |   |-- source_span...
|   |   '-- utf 0.9.0+4
|   |-- isolate 1.1.0
|   |-- kernel 0.3.0-alpha.9
|   |   |-- args...
|   |   |-- logging...
|   |   |-- package_config...
|   |   '-- path...
|   |-- meta...
|   |-- package_config 1.0.3
|   |   |-- charcode...
|   |   '-- path...
|   |-- path...
|   |-- plugin 0.2.0+2
|   |-- source_span...
|   |-- watcher...
|   '-- yaml...
|-- build_config 0.2.6+2
|   |-- build...
|   |-- meta...
|   |-- path...
|   '-- yaml...
|-- build_runner 0.8.9
|   |-- args 1.4.3
|   |-- async 1.13.3
|   |   '-- collection...
|   |-- build 0.12.6
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- logging...
|   |   |-- meta...
|   |   '-- path...
|   |-- build_config...
|   |-- build_resolvers 0.2.0+2
|   |   |-- analyzer...
|   |   |-- build...
|   |   |-- cli_util...
|   |   '-- path...
|   |-- cli_util 0.1.3
|   |   '-- path...
|   |-- code_builder...
|   |-- collection 1.14.9
|   |-- convert 2.0.1
|   |   |-- charcode...
|   |   '-- typed_data...
|   |-- crypto 2.0.3
|   |   |-- collection...
|   |   |-- convert...
|   |   '-- typed_data...
|   |-- dart_style 1.0.9+1
|   |   |-- analyzer...
|   |   |-- args...
|   |   |-- path...
|   |   '-- source_span...
|   |-- glob 1.1.5
|   |   |-- async...
|   |   |-- collection...
|   |   |-- path...
|   |   '-- string_scanner...
|   |-- graphs 0.1.2
|   |-- http_multi_server 2.0.4
|   |   '-- async...
|   |-- io 0.3.2+1
|   |   |-- charcode...
|   |   |-- meta...
|   |   |-- path...
|   |   '-- string_scanner...
|   |-- logging 0.11.3+1
|   |-- meta 1.1.5
|   |-- mime 0.9.6+1
|   |-- path 1.5.1
|   |-- pool 1.3.5
|   |   |-- async...
|   |   '-- stack_trace...
|   |-- shelf 0.6.8
|   |   |-- async...
|   |   |-- collection...
|   |   |-- http_parser 3.1.2
|   |   |   |-- charcode...
|   |   |   |-- collection...
|   |   |   |-- source_span...
|   |   |   |-- string_scanner...
|   |   |   '-- typed_data...
|   |   |-- path...
|   |   |-- stack_trace...
|   |   '-- stream_channel...
|   |-- stack_trace 1.9.2
|   |   '-- path...
|   |-- stream_transform 0.0.11
|   |-- watcher 0.9.7+7
|   |   |-- async...
|   |   '-- path...
|   '-- yaml 2.1.13
|       |-- charcode...
|       |-- collection...
|       |-- source_span...
|       '-- string_scanner...
|-- code_builder 3.0.3
|   |-- built_collection 3.1.1
|   |   |-- collection...
|   |   '-- quiver 0.29.0+1
|   |       |-- matcher...
|   |       '-- meta...
|   |-- built_value 5.4.4
|   |   |-- built_collection...
|   |   |-- collection...
|   |   |-- fixnum 0.10.7
|   |   '-- quiver...
|   |-- matcher 0.12.2+1
|   |   '-- stack_trace...
|   '-- meta...
|-- jaguar_serializer 1.0.0-dev7
|-- jaguar_serializer_cli 1.0.0-dev8
|   |-- analyzer...
|   |-- build...
|   |-- jaguar_serializer...
|   |-- logging...
|   '-- source_gen...
|-- source_gen 0.8.1+1
|   |-- analyzer...
|   |-- build...
|   |-- dart_style...
|   |-- meta...
|   |-- path...
|   '-- source_span...
'-- test 0.12.38+1
    |-- analyzer...
    |-- args...
    |-- async...
    |-- boolean_selector 1.0.3
    |   |-- collection...
    |   |-- source_span...
    |   '-- string_scanner...
    |-- collection...
    |-- glob...
    |-- http_multi_server...
    |-- io...
    |-- js 0.6.1
    |-- matcher...
    |-- meta...
    |-- multi_server_socket 1.0.1
    |   '-- async...
    |-- node_preamble 1.4.1
    |-- package_resolver 1.0.2
    |   |-- collection...
    |   |-- http 0.11.3+16
    |   |   |-- async...
    |   |   |-- collection...
    |   |   |-- http_parser...
    |   |   '-- path...
    |   |-- package_config...
    |   '-- path...
    |-- path...
    |-- pool...
    |-- pub_semver 1.4.1
    |   '-- collection...
    |-- shelf...
    |-- shelf_packages_handler 1.0.3
    |   |-- async...
    |   |-- package_resolver...
    |   |-- path...
    |   |-- shelf...
    |   '-- shelf_static...
    |-- shelf_static 0.2.7
    |   |-- convert...
    |   |-- http_parser...
    |   |-- mime...
    |   |-- path...
    |   '-- shelf...
    |-- shelf_web_socket 0.2.2
    |   |-- shelf...
    |   |-- stream_channel...
    |   '-- web_socket_channel...
    |-- source_map_stack_trace 1.1.4
    |   |-- package_resolver...
    |   |-- path...
    |   |-- source_maps...
    |   '-- stack_trace...
    |-- source_maps 0.10.5
    |   '-- source_span...
    |-- source_span 1.4.0
    |   |-- charcode...
    |   '-- path...
    |-- stack_trace...
    |-- stream_channel 1.6.6
    |   |-- async...
    |   '-- stack_trace...
    |-- string_scanner 1.0.2
    |   |-- charcode...
    |   '-- source_span...
    |-- term_glyph 1.0.0
    |-- typed_data 1.1.5
    |-- web_socket_channel 1.0.7
    |   |-- async...
    |   |-- crypto...
    |   '-- stream_channel...
    '-- yaml...
```

**Comment by jakemac53** [comment]
closing this as I can't actually repro the issue
