### ISSUE TITLE
Snapshot the generated build.dart script

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1496]
With Dart 2 things are going to get very slow to start if we're parsing from source on every run. We should start snapshotting the Dart script.

- [ ] Figure out what criteria to use to invalidate it (we unconditionally invalidate today)
- [ ] Add support for passing down the "apparent" script name to use for the asset graph path. Today we compute it based on the file path of the entrypoint, but that will very depending on whether we're running from source (if we're producing an app-jit snapshot) or from the snapshot.

**Comment by jakemac53** [comment]
We could solve this instead with a longer lived daemon process? It would use existing logic to kill itself if any files it imports are changed, but for most users that shouldn't ever happen (outside of pub get/upgrade).

**Comment by jakemac53** [comment]
Closing in favor of https://github.com/dart-lang/build/issues/1656

**Comment by jakemac53** [comment]
So I did a bit of testing here, and the snapshot does can actually check itself for changes appropriately (based on the original sources it came from).

Given that, we could add a simple hidden flag like `--exit-if-changed`, or make it somehow recognize it is a snapshot and automatically exit with a special exit code in this scenario. Then, we would re-snapshot from the wrapper script and regenerate the snapshot.

**Comment by jakemac53** [comment]
This could also be tied in with https://github.com/dart-lang/build/issues/1745

**Comment by jakemac53** [comment]
Also related https://github.com/dart-lang/build/issues/1201
