### ISSUE TITLE
UnexpectedOutputException if I transform from .tmpl.html to .html

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/build#1508]
* [x] Dart SDK Version (`dart --version`)
Dart VM version: 2.0.0-dev.59.0 (Tue May 29 22:11:36 2018 +0200) on "macos_x64"

* [x] What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0

* [x] What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
I'm using my own builder. 
It replaces %version% in index.tmpl.html and copies it to index.html
Thats at least what I want to do but builder crashes with

```
[SEVERE] git_version|htmlBuilder on web/index.tmpl.html:

UnexpectedOutputException: mini_web_sample|web/index.tmpl.html
Expected only: {mini_web_sample|web/index.html}
```

* [X] Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOSX
----
I know - a workaround would be to rename index.tmpl.html to index.tmpl and then
```
var copy = inputId.changeExtension(".html");
```
this works but it would be much nicer if I could change the extension from .tmpl.html to .html

**Comment by jakemac53** [comment]
> this works but it would be much nicer if I could change the extension from .tmpl.html to .html

This does work - and is in fact what you told the build system you were going to do (and it expected you to do). This exception:

```
UnexpectedOutputException: mini_web_sample|web/index.tmpl.html
Expected only: {mini_web_sample|web/index.html}
```

Is saying you tried to output `mini_web_sample|web/index.tmpl.html` but declared `mini_web_sample|web/index.html` as an output (via outputExtensions).

My guess is you are creating the output ID like this: `buildStep.inputId.changeExtension('.html')`, but that will only replace the final extension (`.html`) which won't actually do what you want.  You could instead do `buildStep.inputId.changeExtension('').changeExtension('.html')`, or something like `new AssetId(buildStep.inputId.path, buildStep.inputId.path.replaceFirst('.tmpl.html', '.html'))`

**Comment by MikeMitterer** [comment]
Thanks - you were right!! It looks like a hack to me but however - if it works, it works...
