### ISSUE TITLE
folder with hyphen --> ddc runtime error

### ISSUE THREAD

**Issue by nilsdoehring** [dart-lang/build#1523]
Area: webdev, dartdevc

Running a script from a folder with a hyphen in its name results in a ddc runtime error.

Example project layout
![image](https://user-images.githubusercontent.com/1327275/41024842-9be5cc8e-6970-11e8-881e-e4081801a56a.png)

Chrome console output:
```
Uncaught ReferenceError: folder__main is not defined
    at main.dart.bootstrap.js:153
    at Object.execCb (require.js:1696)
...
```

Steps to reproduce:
* Create a `Bare-bones Web App` in IDEA via `New Project -> Dart`
* Create a folder with a hyphen under `web/` (or anywhere else)
* Move files from `web/` to `web/hyphen-folder`
* Debug `web/hyphen-folder/index.html`

The error comes from the hyphen being sanitized incorrectly/differently in generated js,
* in _main.dart.bootstrap.js_: `app.hyphen-folder__main.main();`
* in _main.ddc.js_: `hyphen$45folder__main`

IDEA EAP 2018.2
SDK 2.0.0-dev.60.0
  build_runner: ^0.8.9
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0+3
OSX, Chrome

**Comment by jakemac53** [comment]
Should get a version published next week most likely
