### ISSUE TITLE
Debugging Web Apps: Stacktrace/Mapping seems broken

### ISSUE THREAD

**Issue by nilsdoehring** [dart-lang/build#1525]
When debugging a web app that is producing cast errors at runtime, a user would expect that:
* Debugger gets triggered, displaying the error message and Dart stack/code
* Console prints meaningful info, or at least the same contents as Chrome dev tools console

What happens instead?
* Debugger doesn't get triggered
* Console prints only a subset of Chrome dev tools console (Screenshot 1)
* User has to look at Chrome's console output and make best guesses where the error lies in Dart code (Screenshot 2)

What steps will reproduce the problem?
1. Checkout [this branch](https://github.com/nilsdoehring/StageXL_DragonBones/tree/dart-2) (it is missing a typecast when parsing json)
2. Activate Dart, pub get
3. Debug example/swords_man/index.html

Screenshot 1
![image](https://user-images.githubusercontent.com/1327275/41028948-c9bf9ef0-697a-11e8-8c0b-4c68ae7b8924.png)

Screenshot 2 (Chrome console)
![image](https://user-images.githubusercontent.com/1327275/41028964-d117a936-697a-11e8-97e3-473c842b03d9.png)

IDEA EAP 2018.2
Dart SDK 2.0.0-dev.60.0
build_runner: ^0.8.9
build_test: ^0.10.2
build_web_compilers: ^0.4.0+3
OSX, Chrome

Also reported in Jetbrains YouTrack as [WEB-33172](https://youtrack.jetbrains.com/issue/WEB-33172)

**Comment by eredo** [comment]
Not sure if that's applicable to this log output, but there was a comment in a similar angular issue about turning on custom formatters for in Chrome Dev Tools: https://github.com/dart-lang/angular/issues/1367#issuecomment-394555525

**Comment by jakemac53** [comment]
@nilsdoehring can you confirm if enabling the custom formatter fixes this issue for you?

**Comment by afpatmin** [comment]
Enabling it does not fix it for me unfortunately

**Comment by afpatmin** [comment]
Update; removing `<base href="/">` in index.html made it reference dart files directly again on my end

**Comment by nilsdoehring** [comment]
Enabling custom formatters indeed makes Chrome console reference the dart files (see pic below). No changes on the IDEA side, though (i.e. console output exactly the same as in OP).

![image](https://user-images.githubusercontent.com/1327275/41466062-d56b7670-70a0-11e8-80df-df8a5472f5d8.png)

**Comment by matanlurey** [comment]
@natebosch Do you want to track IDE issues here or elsewhere?

**Comment by jwren** [comment]
In YouTrack, when @nilsdoehring opened the issue he included a link to https://youtrack.jetbrains.com/issue/WEB-33172

**Comment by natebosch** [comment]
Sounds good, we'll track there. We can reopen this issue if we need any changes on the build side.

**Comment by jwren** [comment]
SGTM.  Are we sure then that the source maps are all correct from the DDC side?

**Comment by natebosch** [comment]
> Are we sure then that the source maps are all correct from the DDC side?

I think we're confident with them. We have some tests for source maps and things seem to be working in the browser once the config is set up.
