### ISSUE TITLE
FileBasedAssetReader.findAssets() stream is prematurely terminated following a Glob.list() exception

### ISSUE THREAD

**Issue by chalin** [dart-lang/build#1534]
When testing a new builder from [site-webdev PR #1624](https://github.com/dart-lang/site-webdev/pull/1624), I faced the following issue. The [build.doc.yaml](https://github.com/dart-lang/site-webdev/blob/bf62af2fe2e05e67577821ac46a815c1af84269e/build.doc.yaml) contains the following `targets.$default.sources.include` glob:

- `examples/html/{lib,test,web}/**`

The problem is that there is no `web` folder under `examples/html`. While `Glob.list()` reports the exception:

    FileSystemException: Directory listing failed, path = '.../site-webdev/examples/html/web/' (OS Error: No such file or directory, errno = 2)

The exception gets silently gobbled up, and the element generation for the asset stream stops.

---

The point at which the `FileSystemException` seems to get caught and dropped is in the `FileBasedAssetReader.findAssets()` function:

https://github.com/dart-lang/build/blob/526457f2da5c97b37e65b736bd807212fcc7d2e6/build_runner_core/lib/src/asset/file_based.dart#L41

In particular this `try-catch` block:

https://github.com/dart-lang/build/blob/526457f2da5c97b37e65b736bd807212fcc7d2e6/build_runner_core/lib/src/asset/file_based.dart#L51-L62

Because of the async nature of the directory tree generation, I was seeing some files from under `examples/html` but not always the same collection of files.

It would probably be better to handle async errors (and report them as warnings) using, say, [stream.handleError()](https://api.dartlang.org/dev/2.0.0-dev.60.0/dart-async/Stream/handleError.html), and to iterate with the `await for` over the error free stream. In this way, errors won't prevent any of the input targets from being listed.

cc @kevmoo, @kwalrath

**Comment by jakemac53** [comment]
Ah! Thank makes sense - we should not just be swallowing that exception. Thanks for investigating!
