### ISSUE TITLE
We should not surface InternalAssetNode assets from findAssets

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1573]
Can we add a `node.isValidInput` check here? Will that break anything else?

https://github.com/dart-lang/build/blob/242b5f75400d2a7f842d355b48759383692dfa3d/build_runner_core/lib/src/asset/reader.dart#L80

**Comment by jakemac53** [comment]
We could also check that it is not an InternalAssetNode?

**Comment by natebosch** [comment]
AFAIK `InternalAssetNode` is the reason we have both `isReadable` and `isValidInput`.

**Comment by jakemac53** [comment]
I think `isValidInput` should be fine - but we might want to update the docs. Currently it is referring explicitly to primary inputs and not secondary inputs.

**Comment by natebosch** [comment]
Which docs do you mean?
