### ISSUE TITLE
Make it possible to run against '$lib$' even if it isn't included in the target sources

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1575]
It's confusing to have to add `lib/$lib$` as a source when it's not ever a file you see.

Also, is it confusing that if you enable a builder on multiple targets you'd get a conflicting output? Can we message that well? Or detect it and handle it cleanly?

**Comment by jakemac53** [comment]
What if we made these placeholders be an implicit include for the `default` target? We could still respect `excludes` for them, and explicit includes in other targets.

Idk though, feels a bit magic.

**Comment by jakemac53** [comment]
Going to close this, running with a warning if placeholders are not included in some target https://github.com/dart-lang/build/pull/2664
