### ISSUE TITLE
Filter out the builders which "applies_builders" some builder which is "build_to: source" on non root packages

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1578]
Today we filter out builders that won't work because they want to build to source and auto apply to some package other than the root. Once source_gen adds the combining builder the actual builder doing work would be build_to: cache and so would get needlessly run.

cc @kevmoo - we'll want this before launching the combining builder stuff because it will impact performance.

Blocking https://github.com/dart-lang/source_gen/issues/319

**Comment by kevmoo** [comment]
Yes, please!

**Comment by jakemac53** [comment]
This could also be resolved by allowing boolean-selector type logic to auto-apply - in this case we would want `root_package && dependents`. That way it would only apply to the root package, and only if that also had an explicit dependency.

**Comment by kevmoo** [comment]
OMG – 2 users! https://pub.dartlang.org/packages?q=dependency%3Aboolean_selector
