### ISSUE TITLE
[Dart2js] Invalid baseUrl when main.dart.js is not at the root

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/build#1588]
When building a dart application using dart2js, then serving the scripts on a path other than `localhost/main.dart.js` ; the location of some packages is inferred incorrectly.

Which means that when hosting our `main.dart.js` at `localhost/dartlib/main.dart.js`
then it will call try to imports packages on `localhost/packages/...` instead of `localhost/dartlib/packages/...`

This can be problematic if we want to import our dart scripts inside an existing JS app.

The cause is some variables such as `baseUrl` of `main.dart.js` defaulting to `/`.
____

Dart VM version: 2.0.0-dev.55.0 (Mon May 14 09:23:07 2018 +0200) on "macos_x64"

build_runner 0.8.10
build_web_compilers 0.4.0+4

Chrome

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/issues/1087, https://github.com/dart-lang/build/pull/1332, https://github.com/dart-lang/build/issues/1279 for some related context, this should only be an issue with `dartdevc` and not `dart2js`.

Would some sort of configuration option for setting `baseUrl` also fix your issue?

**Comment by rrousselGit** [comment]
Oh sorry, didn't see the  issue about `baseUrl` configuration. That's a duplicate then
