### ISSUE TITLE
AssetNotFoundException: dt|lib/src/todo_list/todo_list_component.dart___jb_tmp___

### ISSUE THREAD

**Issue by adamlofts** [dart-lang/build#1597]
I am trying to run `build_runner watch` whilst editing the todo app in intellij. 

Steps to reproduce this crash:

1. Code in the intellij window for a minute
2. Click away from intellij, this prompts intellij to save the file to disk
3. The build starts, but then crashes complaining about temporary files used by intellij when saving to disk

```
pub run build_runner watch web -o ../web/static/dart
[INFO] Generating build script completed, took 270ms
[INFO] Setting up file watchers completed, took 25ms
[INFO] Waiting for all file watchers to be ready completed, took 499ms
[INFO] Reading cached asset graph completed, took 1.4s
[INFO] Checking for updates since last build completed, took 1.7s
[INFO] Running build completed, took 14.8s
[INFO] Caching finalized dependency graph completed, took 261ms
[INFO] Reading manifest at ../web/static/dart/.build.manifest completed, took 2ms
[INFO] Deleting previous outputs in `../web/static/dart` completed, took 205ms
[INFO] Creating merged output dir `../web/static/dart` completed, took 1.8s
[INFO] Writing asset manifest completed, took 13ms
[INFO] Succeeded after 17.1s with 33 outputs (54 actions)
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 11ms
[INFO] Running build completed, took 5.0s
[INFO] Caching finalized dependency graph completed, took 376ms
[INFO] Reading manifest at ../web/static/dart/.build.manifest completed, took 3ms
[INFO] Deleting previous outputs in `../web/static/dart` completed, took 242ms
[INFO] Creating merged output dir `../web/static/dart`...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


AssetNotFoundException: dt|lib/src/todo_list/todo_list_component.dart___jb_tmp___
package:build_runner/src/asset/file_based.dart 133:18  _fileForOrThrow.<fn>

```

* [ ] Dart SDK Version (`dart --version`)

Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "linux_x64"

* [ ] What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

  build_runner: 0.8.9

  * _If you are not sure, try checking your `pubspec.lock` file._

* [ ] What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.

n/a

* [ ] Whether you are using Windows, MacOSX, or Linux (if applicable)

Linux

* [ ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Chrome

* [ ] Any other packages or constraints we should know about

n/a

**Comment by jakemac53** [comment]
This is an issue with the interaction between the `safe write` feature in intellij and build_runner. You can work around it by disabling this feature in intellij.

For most people this is solved with the debouncing logic in our file watcher, but if the file exists for longer than that delay or the file watcher doesn't see the delete fast enough (are you on windows?), then you can get this error.

I am curious, did it do a rebuild after this failure which succeeded? Or did the process exit, or just sit there waiting for more edits?

**Comment by jakemac53** [comment]
We do also have a way of configuring this delay with custom build scripts, but no command line argument for the auto build script right now. It would be easy enough to add though if we decide that is the right course of action. It doesn't really fully resolve the issue but it should at least mitigate it.

**Comment by adamlofts** [comment]
The main problem is that the process exits so I have to restart it and wait for it to get going. I'm on Linux with an SSD but its still easy to reproduce for me. 

I would prefer a solution which I can check-in to the project rather than an intellij setting but am happy to disable safe write if needed.

I will try and configure a custom build script. Would it also help if I exclude these files in the script somehow?

**Comment by matanlurey** [comment]
I could see a way to ignore certain patterns being generally useful.

@jakemac53 Are we getting to a point where something like a `.build_runner_rc` is needed?

**Comment by jakemac53** [comment]
> The main problem is that the process exits so I have to restart it and wait for it to get going. I'm on Linux with an SSD but its still easy to reproduce for me.

Ok - I think the first actionable thing to do here is add more explicit handling around this case. We should log an error but not exit - and then do a rebuild (the rebuild should happen automatically anyways if it didn't exit).

> I would prefer a solution which I can check-in to the project rather than an intellij setting but am happy to disable safe write if needed.

As @matanlurey just suggested maybe we should look at a way of having machine specific configuration for some of these options. We don't have many users who report running into this (although you aren't the only one), so I don't think it should generally be checked into the repo but we could consider project level configuration as well.

> I will try and configure a custom build script. Would it also help if I exclude these files in the script somehow?

You could actually exclude these files with just a regular `build.yaml`, something like this:

```yaml
targets:
  $default:
    sources:
      exclude:
        - **/*___jb_tmp___
``` 

If you want to create a custom build script you could start by simply copying the `.dart_tool/build/entrypoint/build.dart` file that is autogenerated - you may need to explicitly call `watch` instead of `run` though if `run` doesn't provide this option.

**Comment by adamlofts** [comment]
I wonder if I am doing something stupid because this happens on pretty much every edit I make to a file. My project layout has 2 folders:

- /web This is a google app engine standard app.
- /dart This is a dart project (I started with the TODO app)

I am trying to run the build watcher to automatically update files in /web/static as I edit my dart app. I am using the standard  `dev_appserver.py` to serve all files in /web (including generated dart files).

> We don't have many users who report running into this (although you aren't the only one), so I don't think it should generally be checked into the repo but we could consider project level configuration as well.

To be clear I was saying I would check-in the solution into MY project, not yours :smile: 

I tried a `build.yaml` solution as you suggested but it doesn't seem to help. I get the same error. Its hard for me to know for sure but I think its being picked up because I tested excluding everything and I got an empty build.

Tomorrow I will try a custom build.

This is the log with `-v` added incase it is useful. This is the log after editing a component html and clicking out of intellij (no other changes).

```
[INFO] Generating build script completed, took 276ms
[INFO] Setting up file watchers completed, took 14ms
[INFO] Waiting for all file watchers to be ready completed, took 99ms
[INFO] Reading cached asset graph completed, took 739ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 317ms
[INFO] Caching finalized dependency graph completed, took 260ms
[INFO] Reading manifest at ../web/static/dart/.build.manifest completed, took 1ms
[INFO] Deleting previous outputs in `../web/static/dart` completed, took 44ms
[INFO] Creating merged output dir `../web/static/dart` completed, took 1.8s
[INFO] Writing asset manifest completed, took 15ms
[INFO] Succeeded after 2.4s with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 9ms
[FINEST] Got remove event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.dart in /home/adam/dev/mbox/mbox[FINEST] Got modify event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.dart in /home/adam/dev/mbox/mbox[FINEST] Got remove event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.module in /home/adam/dev/mbox/mb[FINEST] Got add event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.module in /home/adam/dev/mbox/mbox/[FINEST] Got modify event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.module in /home/adam/dev/mbox/mb[FINEST] Got remove event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.linked.sum in /home/adam/dev/mbo[FINEST] Got add event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.linked.sum in /home/adam/dev/mbox/m[FINEST] Got modify event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.linked.sum in /home/adam/dev/mbo[FINEST] Got remove event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.ddc.js.map in /home/adam/dev/mbo[FINEST] Got remove event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.ddc.js in /home/adam/dev/mbox/mb[FINEST] Got add event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.ddc.js in /home/adam/dev/mbox/mbox/[FINEST] Got modify event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.ddc.js in /home/adam/dev/mbox/mb[FINEST] Got add event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.ddc.js.map in /home/adam/dev/mbox/m[FINEST] Got modify event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.ddc.js.map in /home/adam/dev/mbo[FINEST] Got remove event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.unlinked.sum in /home/adam/dev/m[FINEST] Got add event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.unlinked.sum in /home/adam/dev/mbox[FINEST] Got modify event for "asset:dt/.dart_tool/build/generated/dt/lib/src/todo_list/model_component.template.unlinked.sum in /home/adam/dev/m[INFO] Running build completed, took 11.9s
[INFO] Caching finalized dependency graph completed, took 242ms
[INFO] Reading manifest at ../web/static/dart/.build.manifest completed, took 2ms
[INFO] Deleting previous outputs in `../web/static/dart` completed, took 201ms
[INFO] Creating merged output dir `../web/static/dart`...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


AssetNotFoundException: dt|lib/src/todo_list/model_component.html___jb_tmp___
package:build_runner/src/asset/file_based.dart 133:18  _fileForOrThrow.<fn>

```

**Comment by jakemac53** [comment]
Weird - I don't see any logs about it even seeing that file being added/removed. Something _interesting) seems to be going on haha...

**Comment by adamlofts** [comment]
I had a stab at debugging this.

There are two change events coming from the graphWatcher:

```
build.dart:main():stdout> OHNO AssetChange {asset: dt|lib/src/todo_list/model_component.html___jb_tmp___, type: add}
Paused at watch_impl.dart:264:33
$ n
Continuing...
Paused at watch_impl.dart:264:13
$ n
Continuing...
build.dart:main():stdout> OHNO AssetChange {asset: dt|lib/src/todo_list/model_component.html___jb_tmp___, type: remove}
```

However the REMOVE event is being filtered in `_shouldProcess` because the asset does not exist in the graph. This means the event is not debounced. This code seems to have changed from build_runner 0.8.9 so perhaps the issue is fixed already.

https://github.com/dart-lang/build/blob/a110d5d14a4ea5eab17a658affa6f27f20651615/build_runner/lib/src/generate/watch_impl.dart#L355

**Comment by adamlofts** [comment]
OK I've got a solution working for me. :champagne: 

As far as I can tell the rootPackage does not respect the `excludes:` globs. This is why the `build.yaml` suggestion did not work.

If I set my `build.yaml` to:

```
targets:
  $default:
    sources:
      include:
        - 'benchmark/**'
        - 'bin/**'
        - 'example/**'
        - 'lib/**.dart'
        - 'lib/**.html'
        - 'lib/**.css'
        - 'test/**'
        - 'tool/**'
        - 'web/**'
        - 'pubspec.yaml'
        - 'pubspec.lock'
```
then I no longer get the crash!

**Comment by jakemac53** [comment]
> As far as I can tell the rootPackage does not respect the excludes: globs. This is why the build.yaml suggestion did not work.

This should work, if it doesn't its a bug. I think more likely its because it should be `exclude` not `excludes` though :). We should also be throwing an error on unrecognized options - this one is somewhat special though so we might have missed the custom error handling required since it has custom deserialization logic.

**Comment by adamlofts** [comment]
I copy pasted your example so fairly sure I had `exclude` correct. The reason I thought exclude wasn't working was when I was reading the code for the graph and watcher it seemed like events were filtered based on only the whitelist and not the filter.

**Comment by jakemac53** [comment]
> I copy pasted your example so fairly sure I had exclude correct. The reason I thought exclude wasn't working was when I was reading the code for the graph and watcher it seemed like events were filtered based on only the whitelist and not the filter.

Oh yes, that was the case for a while but we fixed it I think?

**Comment by jakemac53** [comment]
I think I am going to add a note to the FAQ about how to resolve this (using excludes), and then close this issue, wdyt @natebosch @adamlofts does that seem reasonable?
