### ISSUE TITLE
Shorten names by not repeating types

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#161]
We've got names which include details already expressed through the type signature. Some of these were likely attempting for consistency against APIs in other libraries (ie read/write as string in File from dart:io)

In this package there is no ambiguity and the extra verbosity isn't useful. This is a breaking change but I think it's worth doing before we hit 1.0

- `Asset.stringContents` -> `Asset.content`
- `AssetReader.readAsString` -> `AssetReader.read`
- `AssetWriter.writeAsString` -> `AssetWriter.write`

**Comment by jakemac53** [comment]
Are we really sure that we don't ever want to support reading/writing bytes instead of strings? Previously there were unimplemented read/write methods I think, matching the ones in the File apis. I think that consistency with the file apis here actually has a lot of value.

**Comment by natebosch** [comment]
We'd have a ton of work to do if we want to support writing bytes. The reason we dropped the methods was that most implementations of these interfaces didn't support the bytes alternative, and adding support would be challenging - we'd have to change all of our caching for instance.

I'm not sure I agree that consistency with `File` is worthwhile. That api was built around bytes primarily and String secondarily. In our case String is and should be the primary use case and if we add support for bytes it should be the one with a longer name.

**Comment by jakemac53** [comment]
closing as we did add support for reading/writing as bytes
