### ISSUE TITLE
AssetGraph placed in folder, based on ABSOLUTE path to build file

### ISSUE THREAD

**Issue by yury-yufimov** [dart-lang/build#1619]
We are using dart2.0.0-dev.63.0 and build_runner 0.9.0 for building our project.

We have strong intention to distribute initial state of BuildCache (.dart_tool content) to all developers, for reducing initial build time.

After build is finished, asset graph is placed in 
/Users/MY_USER_NAME/projects/MY_PROJECT_FOLDER/.dart_tool/build/...MD5_FOR_BUILD_SCRIPT.../asset_graph.json

It turns out, that MD5_FOR_BUILD_SCRIPT depends on absolute path to build script, like:
/Users/MY_USER_NAME/projects/MY_PROJECT_FOLDER/tools/grind.dart

That makes it quite difficult to distribute suitable cache for all developers.

Proposal: calculate MD5_FOR_BUILD_SCRIPT only from relative path within project folder and, may be, project name from pubspec.yaml

**Comment by DisDis** [comment]
@kevmoo @natebosch @jakemac53

**Comment by jakemac53** [comment]
Seems reasonable :+1:
