### ISSUE TITLE
Automatically release Resolver instances

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#162]
The `Resolver` lifecycle is a particularly pointy bit of our API. It's not allowed to`.resolve` for the same AssetId multiple times, and failing to release a resolver can cause very hard to track bugs.

We should consider whether the `BuildStepImpl` can manage Resolver lifecycles so that `Builders` have fewer chances to make mistakes.

**Comment by jakemac53** [comment]
It looks like we could just add this to `ManagedBuildStep.complete()`?

**Comment by natebosch** [comment]
Yeah I think we could automatically release in `complete()` and return cached Resolver instances if a Builder calls Resolve multiple times.

We need to re-evaluated whether taking an `AssetId` is still necessary or whether we always use a single Resolver instance per build step.
