### ISSUE TITLE
Trying to build and run all of Angular's tests in Dart2JS is slow

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1620]
(Er, slow-er than I'd expect - I realize we do no parallelization yet)

https://github.com/dart-lang/angular/blob/master/_tests/pubspec.yaml

```yaml
  analyzer: ^0.32.0
  build_runner: ^0.9.0
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
```

```bash
pub run build_runner test -r -- -p chrome
```

... does some work, and then hangs for me.

Interestingly, I think it hangs somewhere very low level, because I keep seeing `15.1s` multiple times:

```
[WARNING] No actions completed for 15.1s, waiting on:
  - build_web_compilers|entrypoint on test/di/injector_test.dart
  - build_web_compilers|entrypoint on test/di/reflective_static_test.dart
  - build_web_compilers|entrypoint on test/core/linker/component_selector_test.dart
  - build_web_compilers|entrypoint on test/core/testability/testability_test.dart
  - build_web_compilers|entrypoint on test/core/exports_test.dart
  .. and 223 more

[WARNING] No actions completed for 15.1s, waiting on:
  - build_web_compilers|entrypoint on test/di/injector_test.dart
  - build_web_compilers|entrypoint on test/di/reflective_static_test.dart
  - build_web_compilers|entrypoint on test/core/linker/component_selector_test.dart
  - build_web_compilers|entrypoint on test/core/testability/testability_test.dart
  - build_web_compilers|entrypoint on test/core/exports_test.dart
  .. and 223 more
```

... after waiting for a few more minutes, it looks like some are actually being built, though.

**Comment by jakemac53** [comment]
I think https://github.com/dart-lang/build/issues/1462 might help resolve this initial slowness issue, fwiw we do have the ability to parallelize dart2js builds with multiple workers

**Comment by matanlurey** [comment]
I ended up cancelling after 30 minutes.

It might have eventually finished before the death of the universe, but my battery would not last.

**Comment by jakemac53** [comment]
Also curious, did this ever succeed?

**Comment by matanlurey** [comment]
That particular action did, I did not wait to see if all of them would, though.

**Comment by jakemac53** [comment]
> I ended up cancelling after 30 minutes.
> 
> It might have eventually finished before the death of the universe, but my battery would not last.

By that time was it actually making progress?

**Comment by matanlurey** [comment]
It made some progress, but it went back into the `15.1s` loop for a long time at some point.

It seems to go
* Run all generators (pretty fast)
* Hanging 15.1s for a duration of time
* Emit some JS outputs
* Hanging 15.s
* Emit some JS
* ...

**Comment by jakemac53** [comment]
So I think 15s is the timeout for this warning log about no actions completing, so it would make sense if there is only one dart2js worker, and it takes between 15s and 30s to compile each test, that you would continually see the `15.1s` warning.

It is weird though if you see the same time being logged but no difference in the number of pending actions.

**Comment by matanlurey** [comment]
Definitely. I'm guessing we agree though that `_tests` _should_ be runnable with Dart2JS, right?

**Comment by jakemac53** [comment]
I am curious here @matanlurey - what is your expectation for doing this? Is the primary issue in your view the fact that it waits for the entire build to finish before running any tests?

**Comment by matanlurey** [comment]
I mean my immediate expectation was that it at least gets somewhere in 30 minutes. I was expecting that by 30 minutes in either at least a single test was started, _or_ I had a clearer idea of the progress - I couldn't tell if it was going to take another 5 minutes or another 5 hours.

**Comment by jakemac53** [comment]
Running it locally on my beefy box just to see how it works for me - it looks like each test for me takes about 10 seconds to compile. It also looks like I was wrong and we don't have built in support for running multiple concurrent dart2js compiles - we could fix that though without much work.

In any case, with roughly 200 tests (guestimate based on remaining actions), that means > 30  minutes with a single dart2js process.

If we got near optimal parallelism with say 4 dart2js workers, we could potentially get that under 10 minutes on my machine, which would probably be >30 minutes still on travis or other CI environments, and somewhere in between those for typical developer machines.

I think that would be pretty reasonable given the constraints and tools available?

If/when dart2js accepts kernel files directly as input we will happily build that modularly and provide it to dart2js, which might reduce this time by up to 50%, but it is unlikely it will be more than that.

WDYT @matanlurey ?

**Comment by jakemac53** [comment]
also fwiw - it looks like my build got stuck eventually with errors just like you reported:

```
[WARNING] No actions completed for 15.1s, waiting on:
  - build_web_compilers|entrypoint on test/regression/755_reflective_meta_fail_test.dart
  - build_web_compilers|entrypoint on test/security/style_sanitizer_test.dart
  - build_web_compilers|entrypoint on test/security/html_sanitizer_test.dart
  - build_web_compilers|entrypoint on test/security/url_sanitizer_test.dart
  - build_web_compilers|entrypoint on test/common/pipes/date_pipe_test.dart
  .. and 233 more
```

I think that dart2js might be dying and we aren't handling that well.

**Comment by matanlurey** [comment]
> Running it locally on my beefy box just to see how it works for me - it looks like each test for me takes about 10 seconds to compile. It also looks like I was wrong and we don't have built in support for running multiple concurrent dart2js compiles - we could fix that though without much work.

I was trying on my Macbook, which is also having some SMC issues, so possible that's related.

> In any case, with roughly 200 tests (guestimate based on remaining actions), that means > 30  minutes with a single dart2js process.

Yeah, that seems reasonable, I guess I just wasn't willing to wait _40_ minutes to see a single test get executed. Thanks.

> If we got near optimal parallelism with say 4 dart2js workers, we could potentially get that under 10 minutes on my machine, which would probably be >30 minutes still on travis or other CI environments, and somewhere in between those for typical developer machines.

Yeah we're probably not quite ready for travis (maybe only travis cRON).

I think that would be pretty reasonable given the constraints and tools available?

> If/when dart2js accepts kernel files directly as input we will happily build that modularly and provide it to dart2js, which might reduce this time by up to 50%, but it is unlikely it will be more than that.

I guess running tests concurrently might help too, like you mentioned above.

> WDYT @matanlurey ?

SGTM. Thanks for digging in. (And for reproing the build stuck issue)

**Comment by jakemac53** [comment]
So - I was able to resolve the hangs at least, but, it took a bit longer than 10 mins.... :

```
[INFO] Build:Succeeded after 1h 41m with 2261 outputs (5345 actions)
```

I am not sure if dart2js has a memory leak in worker mode or what but trying to run 4 dart2js works seemed like a bad idea as it completely ground my computer to a halt.

In terms of the tests, I did get a lot of failures, the majority appear to be of the form:

```
    Actual: <Closure 'D9'>
     Which: threw bD:<Invalid argument(s): No provider found for Fi>
```

I eventually killed it at this point as it seemed stuck:

```
-77:10 +625 ~7 -41: test/di/injector_test.dart: Injector .generate should support Module 
```

Full output here https://gist.github.com/jakemac53/d919f6d42f44644623590d1d1e960fc7.

**Comment by jakemac53** [comment]
Ok, tried again and watched the memory profile this time, it definitely climbs consistently for each compile.

I have filed https://github.com/dart-lang/sdk/issues/33708 to look into this on the sdk side, I think on the build_runner side of things I will just make it restart the worker every X builds or something.

**Comment by matanlurey** [comment]
Wow! Thanks for investigating @jakemac53

**Comment by jakemac53** [comment]
So, with one hack in the build.yaml for `_test`, 4 workers, and the hack to restart dart2js every 10 builds:

```
[INFO] Build:Succeeded after 5m 24s with 1350 outputs (4156 actions)
```

:tada:

**Comment by matanlurey** [comment]
Fantastic job, thanks!

**Comment by matanlurey** [comment]
I know at least some of the tests won't pass without minification disabled and assertions enabled btw.

**Comment by jakemac53** [comment]
> I know at least some of the tests won't pass without minification disabled and assertions enabled btw.

Ok, I will let you figure out the test part, once I land things so you can actually run them :).
