### ISSUE TITLE
DDC module builder fails with error 'Asset ... is not a dart library' if Meta Module Clean Builder catch exception

### ISSUE THREAD

**Issue by nickclmb** [dart-lang/build#1623]
Hi all,

When ModuleBuilder with coarse strategy can't find the .meta_module.clean file it switches to finer build strategy.
In this case ModuleBuilder goes to code line
```
var depLibrary = await buildStep.resolver.libraryFor(dep);
```
and then to `libraryFor` function in `AnalyzerResolver`:
```
  @override
  Future<LibraryElement> libraryFor(AssetId assetId) async {
    var source = sources[assetId];
    if (source == null || !_isLibrary(source)) {
      throw new NonLibraryAssetException(assetId);
    }
    return _context.computeLibraryElement(source);
  }
```

`sources` may not have that assetId, because MetaModule doesn't use resolver to parse dart files, it uses parseCompilationUnit or parseDirectives analyzer functions instead, so if you don't use other builders (angular or something) `source` value will be null.

Reproduce: lib depends on some package that is not in 'dependencies' in pubspec
MetaModuleCleanBuilder will then catch AssetNotFoundException in 
```
} on AssetNotFoundException {
      // Could not find the raw meta module file for one of this module's
      // dependency so we will forgo outputing a file to signal to the
      // module builder that it should use the fine strategy.
      return;
    }
```
and produce no output.

I'm using 
coarse strategy
build_runner 0.9.0
build_modules 0.2.3

**Comment by matanlurey** [comment]
Is this bug to _allow_ this behavior (i.e. depend on a package that isn't in `dependencies`) or to make the error message more clear? /cc @natebosch @jakemac53

**Comment by nickclmb** [comment]
Ok, i think this issue can be closed, I think there is no issue in buildrunner, it was my bad.
