### ISSUE TITLE
Determining outputs ahead of time from the contents of the input

### ISSUE THREAD

**Issue by tejainece** [dart-lang/build#163]
It would be nice if build let us declare outputs based on the content of the input asset.

My usecase: I am trying to write a swagger yaml generator for jaguar. In jaguar, the routes are grouped into class and route handlers are methods on the class. So, i can parse the routes from the source using analyzer and can generate accurate yaml file for all routes/paths.

The problem is, there could be several different apis in same project. Lets say my project has two apis: uber and facebook. I would like to create `uber_api.yaml` and `facebook_api.yaml`. I cannot know what apis are inside the library being built until i get to the `build` method. Would be helpful if somehow `declareOutputs ` got an instance of `LibraryElement` somehow.

**Comment by natebosch** [comment]
One technique we use with bazel sometimes is to output a .tar file which allows us to fill it with multiple files that are unknown ahead of time. 

Why do these files need to be separate rather than a single 
.yaml with multiple sections? 
What will be reading these files? Do you expect them to be edited by hand after they are generated?

**Comment by jakemac53** [comment]
As Nate implied, this is for `bazel` (and other build system) support. This requires that we can declare all outputs ahead of time given only the filenames (the build graph is generated before running any actions or reading any files).

I would personally recommend just combining the two files into one as Nate suggested.

Closing for now as we don't have a way of supporting this.

**Comment by tejainece** [comment]
> Why do these files need to be separate rather than a single^

They are separate APIs. So need to be in their own swagger files

> .yaml with multiple sections?

Have to stick to open API specifications

> What will be reading these files? Do you expect them to be edited by hand after they are generated?

Nothing in the project will be reading the file. It is for documentation purposes or later using it to generate clients for various languages and platforms.

**Comment by jakemac53** [comment]
> They are separate APIs. So need to be in their own swagger files

In that case a tar/zip/jar/etc file is really the only option unfortunately.

**Comment by jakemac53** [comment]
Actually, one other potential solution is to provide some configuration to the builder that tells it what the outputs for given inputs up front. This would need to live in dart code (not a separate file, as that can't be read in either without using dart:io directly which will break `build_runner`s incremental builds), probably passed in via your constructor.

**Comment by tejainece** [comment]
Ok. I think tar-ing and then untar-ing should work fine.

Thanks.
