### ISSUE TITLE
Explain script tag in `index.html` 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/build#1633]
The build_runner readme should explain how the "Dart" script tag in `index.html` should look like in a Dart web project.

**Comment by jakemac53** [comment]
We do have a tiny mention of this [here](https://github.com/dart-lang/build/blob/master/docs/getting_started.md#replacing-dart_to_js_script_rewriter) but it should probably be highlighted better I agree.

**Comment by zoechi** [comment]
Ok found it.
I guess I just skipped the whole section because of the title `dart_to_js_script_rewriter`
