### ISSUE TITLE
Document using build_runner on travis/other CI solutions

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/build#1635]
Has there been any discussion around adding a Travis `dart_task` for testing with build_runner?

https://docs.travis-ci.com/user/languages/dart/#Running-Tests

I looked through all the issues that mentioned Travis here and build_runner in the Travis issue tracker but didn't find anything.

- Is it already supported somehow?
- Is it feasible?

It seems like [build stages](https://docs.travis-ci.com/user/build-stages/) are ideal for projects using build_runner, but from what limited information I could find, it also [seems like dart_task isn't supported or working yet with build stages](https://github.com/travis-ci/travis-ci/issues/9678#issuecomment-393231556). Would the use of build stages make this request irrelevant?

**Comment by jakemac53** [comment]
Good question - especially with plans for improving speed of vm tests with build_runner many more projects will get the benefit of integrating with it for CI environments, so we should make that as easy as possible.

In general, I am not a huge fan of the whole `dart_task` paradigm - it isn't very flexible and I don't think it supports build stages. I would prefer to improve our docs to highlight more "manual" (but also flexible) approach.

**Comment by leonsenft** [comment]
That sounds good to me!

**Comment by matanlurey** [comment]
+1 for sort of EOLing `dart_task`. 

I'd prefer some sort of CLI-like solution (that keeps you on rails) for simpler projects versus `dart_task`, and medium and larger projects should have guidelines and docs explaining best practices.
