### ISSUE TITLE
Consider moving all packages into a package[s] folder

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1638]
i.e. the top-level directory would look more like:

```
> benchmarks
> docs
> examples
  > ...
> packages
  > bazel_codegen
  > build
  > ...
  > scratch_space
> tests
> tools
```

I realize most of the work would be making sure links still point to the correct place. I do wonder if it will make the package a bit more grokkable to newcomers (I showed the repo to someone and they got a bit overwhelemed).

**Comment by jakemac53** [comment]
I don't think mono_repo would handle this well, nor do I think its worth changing it to?

I do agree with the number of packages in this repo now it could be confusing though.

**Comment by natebosch** [comment]
> I don't think mono_repo would handle this well

I'm fine considering that a blocker, but if it doesn't handle it we should fix that.

> nor do I think its worth changing it to

I'm not sure either. I'd like to see some consistency between our mono repo setups. AFAIK Angular is currently the only repo using the proposed layout.

**Comment by jakemac53** [comment]
I am going to close this as not planned, I don't see us having the time to do it any time in the foreseeable future.
