### ISSUE TITLE
webdev serve converts special characters 

### ISSUE THREAD

**Issue by AlexanderJohr** [dart-lang/build#1654]
When I use webdev serve to serve a javascript file, it converts some caracters for example this third party regex (I don't know what it does):

[A-Za-zªµºÀ-ÖØ-öø-ʸʻ-ˁː-ˑˠ-ˤˮͰ-ͳͶ-ͽΆΈ-ϵϷ-҂Ҋ-։ः-हऻऽ-ीॉ-ौॎ-ॐक़-ॡ।-ॿং-হঽ-ীে-ৌৎ-ৡ০-ৱ৴-৺ਃ-ਹਾ-ੀਖ਼-੯ੲ-ੴઃ-હઽ-ીૉ-ૌૐ-ૡ૦-૯ଂ-ହଽ-ାୀେ-ୌୗ-ୡ୦-୷ஃ-ிு-ௌௐ-௲ఁ-ఽు-ౄౘ-ౡ౦-౯౿-ಹಽ-ೋೕ-ೡ೦-ീെ-ൌൎ-ൡ൦-ෆා-ෑෘ-ะา-ำเ-ๆ๏-ະາ-ຳຽ-ໆ໐-༗༚-༴༶༸༾-ཬཿ྅ྈ-ྌ྾-࿅࿇-ာေးျ-ြဿ-ၗၚ-ၝၡ-ၰၵ-ႁႃ-ႄႇ-ႌႎ-ႜ႞-ፚ፠-ᎏᎠ-Ᏼᐁ-ᙿᚁ-ᚚᚠ-ᜑᜠ-ᜱ᜵-ᝑᝠ-ᝰក-ាើ-ៅះ-ៈ។-៚ៜ០-៩᠐-ᢨᢪ-ᤜᤣ-ᤦᤩ-ᤱᤳ-ᤸ᥆-᧚ᨀ-ᨖᨙ-ᩕᩗᩡᩣ-ᩤᩭ-ᩲ᪀-᪭ᬄ-ᬳᬵᬻᬽ-ᭁᭃ-᭪᭴-᭼ᮂ-ᮡᮦ-ᮧ᮪-ᯥᯧᯪ-ᯬᯮ᯲-ᰫᰴ-ᰵ᰻-᱿᳓᳡ᳩ-ᳬᳮ-ᶿḀ-ᾼιῂ-ῌῐ-Ίῠ-Ῥῲ-ῼ‎ⁱⁿₐ-ₜℂℇℊ-ℓℕℙ-ℝℤΩℨK-ℭℯ-ℹℼ-ℿⅅ-ⅉⅎ-⅏Ⅰ-ↈ⌶-⍺⎕⒜-ⓩ⚬⠀-⣿Ⰰ-ⳤⳫ-ⳮⴀ-⵰ⶀ-ⷞ々-〇〡-〩〱-〵〸-〼ぁ-ゖゝ-ゟァ-ヺー-ㆺㇰ-㈜㈠-㉏㉠-㉻㉿-㊰㋀-㋋㋐-㍶㍻-㏝㏠-㏾㐀-䶵一-ꒌꓐ-ꘌꘐ-ꙮꚀ-ꛯ꛲-꛷Ꜣ-ꞇ꞉-ꠁꠃ-ꠅꠇ-ꠊꠌ-ꠤꠧ꠰-꠷ꡀ-ꡳꢀ-ꣃ꣎-꣙ꣲ-ꤥ꤮-ꥆꥒ-ꥼꦃ-ꦲꦴ-ꦵꦺ-ꦻꦽ-ꨨꨯ-ꨰꨳ-ꨴꩀ-ꩂꩄ-ꩋꩍ-ꪯꪱꪵ-ꪶꪹ-ꪽꫀꫂ-ꯤꯦ-ꯧꯩ-꯬꯰-ﬗＡ-Ｚａ-ｚｦ-ￜ]"),u=new RegExp("[־׀׃׆א-״߀-ߪߴ-ߵߺ-ࠕࠚࠤࠨ࠰-ࡘ࡞‏יִײַ-ﬨשׁ-ﭏ]"),h=new RegExp("[؈؋؍؛-ي٭-ٯٱ-ەۥ-ۦۮ-ۯۺ-܍ܐܒ-ܯݍ-ޥޱﭐ-ﴽﵐ-﷼ﹰ-ﻼ]"),d=new RegExp('[\t-\r-"&-*;-@[-`{-~¡¦-©«-¬®-¯´¶-¸»-¿×÷ʹ-ʺ˂-ˏ˒-˟˥-˭˯-˿ʹ-͵;-΅·϶֊؆-؇؎-؏۞۩߶-߹௳-௸௺౸-౾༺-༽᎐-᎙᐀ ᚛-᚜៰-᠊᠎᥀-᥅᧞-᧿᾽᾿-῁῍-῏῝-῟῭-`´- ‐-\u2029‵-⁃⁅- ⁼-⁾₌-₎℀-℁℃-℆℈-℉℔№-℘℞-℣℥℧℩℺-℻⅀-⅄⅊-⅍⅐-⅟↉-∑∔-⌵⍻-⎔⎖-⒇⓪-⚫⚭-⟿⤀-⭙⳥-⳪⳹-⳿⸀-〄〈-〠〰〶-〷〽-〿゛-゜゠・㇀-㇣㈝-㈞㉐-㉟㉼-㉾㊱-㊿㋌-㋏㍷-㍺㏞-㏟㏿䷀-䷿꒐-꓆꘍-꘏꙳꙾-ꙿ꜀-꜡ꞈ꠨-꠫꡴-꡷﴾-﴿﷽︐-︙︰-﹏﹑﹔﹖-﹞﹠-﹡﹤-﹨﹫！-＂＆-＊；-＠［-｀｛-･￢-￤￨-�]

It gets converted to:

[A-Za-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-Ê¸Ê»-ËË-Ë‘Ë -Ë¤Ë®Í°-Í³Í¶-Í½Î†Îˆ-ÏµÏ·-Ò‚ÒŠ-Ö‰à¤ƒ-à¤¹à¤»à¤½-à¥€à¥‰-à¥Œà¥Ž-à¥à¥˜-à¥¡à¥¤-à¥¿à¦‚-à¦¹à¦½-à§€à§‡-à§Œà§Ž-à§¡à§¦-à§±à§´-à§ºà¨ƒ-à¨¹à¨¾-à©€à©™-à©¯à©²-à©´àªƒ-àª¹àª½-à«€à«‰-à«Œà«-à«¡à«¦-à«¯à¬‚-à¬¹à¬½-à¬¾à­€à­‡-à­Œà­—-à­¡à­¦-à­·à®ƒ-à®¿à¯-à¯Œà¯-à¯²à°-à°½à±-à±„à±˜-à±¡à±¦-à±¯à±¿-à²¹à²½-à³‹à³•-à³¡à³¦-àµ€àµ†-àµŒàµŽ-àµ¡àµ¦-à·†à·-à·‘à·˜-à¸°à¸²-à¸³à¹€-à¹†à¹-àº°àº²-àº³àº½-à»†à»-à¼—à¼š-à¼´à¼¶à¼¸à¼¾-à½¬à½¿à¾…à¾ˆ-à¾Œà¾¾-à¿…à¿‡-á€¬á€±á€¸á€»-á€¼á€¿-á—áš-áá¡-á°áµ-á‚á‚ƒ-á‚„á‚‡-á‚Œá‚Ž-á‚œá‚ž-ášá -áŽáŽ -á´á-á™¿áš-áššáš -áœ‘áœ -áœ±áœµ-á‘á -á°áž€-áž¶áž¾-áŸ…áŸ‡-áŸˆáŸ”-áŸšáŸœáŸ -áŸ©á -á¢¨á¢ª-á¤œá¤£-á¤¦á¤©-á¤±á¤³-á¤¸á¥†-á§šá¨€-á¨–á¨™-á©•á©—á©¡á©£-á©¤á©­-á©²áª€-áª­á¬„-á¬³á¬µá¬»á¬½-á­á­ƒ-á­ªá­´-á­¼á®‚-á®¡á®¦-á®§á®ª-á¯¥á¯§á¯ª-á¯¬á¯®á¯²-á°«á°´-á°µá°»-á±¿á³“á³¡á³©-á³¬á³®-á¶¿á¸€-á¾¼á¾¾á¿‚-á¿Œá¿-á¿›á¿ -á¿¬á¿²-á¿¼â€Žâ±â¿â‚-â‚œâ„‚â„‡â„Š-â„“â„•â„™-â„â„¤â„¦â„¨â„ª-â„­â„¯-â„¹â„¼-â„¿â……-â…‰â…Ž-â…â… -â†ˆâŒ¶-âºâŽ•â’œ-â“©âš¬â €-â£¿â°€-â³¤â³«-â³®â´€-âµ°â¶€-â·žã€…-ã€‡ã€¡-ã€©ã€±-ã€µã€¸-ã€¼ã-ã‚–ã‚-ã‚Ÿã‚¡-ãƒºãƒ¼-ã†ºã‡°-ãˆœãˆ -ã‰ã‰ -ã‰»ã‰¿-ãŠ°ã‹€-ã‹‹ã‹-ã¶ã»-ãã -ã¾ã€-ä¶µä¸€-ê’Œê“-ê˜Œê˜-ê™®êš€-ê›¯ê›²-ê›·êœ¢-êž‡êž‰-ê ê ƒ-ê …ê ‡-ê Šê Œ-ê ¤ê §ê °-ê ·ê¡€-ê¡³ê¢€-ê£ƒê£Ž-ê£™ê£²-ê¤¥ê¤®-ê¥†ê¥’-ê¥¼ê¦ƒ-ê¦²ê¦´-ê¦µê¦º-ê¦»ê¦½-ê¨¨ê¨¯-ê¨°ê¨³-ê¨´ê©€-ê©‚ê©„-ê©‹ê©-êª¯êª±êªµ-êª¶êª¹-êª½ê«€ê«‚-ê¯¤ê¯¦-ê¯§ê¯©-ê¯¬ê¯°-ï¬—ï¼¡-ï¼ºï½-ï½šï½¦-ï¿œ]

Dart SDK Version: 2.0.0-dev.68.0
OS: Windows 10

**Comment by jakemac53** [comment]
Ah, it looks like we need to explicitly set the encoding to utf-8 in our shelf response, otherwise you don't get the `charset=utf-8` in the content-type header and this happens.

**Comment by jakemac53** [comment]
Ok, looked into this a bit more. It doesn't look like other servers typically try and deal with this either, and instead you should set the default encoding using a meta tag in your html like this `<meta charset="UTF-8">`. The servers can't know the correct encoding to pass for all assets, or even what assets represent strings at all.

**Comment by AlexanderJohr** [comment]
I tried that now. It is a unit test so I did it this way : `document.head.append(new MetaElement()..attributes['charset']="UTF-8");` and this bekomes `<meta charset="UTF-8">` After that I load the legacy JavaScript files. But still the same problem. Left the file directly from disk displayed in chrome and right the file served by webdev serve:

![screenshot 000211](https://user-images.githubusercontent.com/7449711/42827926-d0a89ffe-89e7-11e8-8ff3-1fbca4041bc8.png)

**Comment by jakemac53** [comment]
Hmm I don't know if meta tags can be injected lazily like that, you can create custom html for unit tests though, just create a `*.html` file with the same name as the test just with the html extension, see [the docs](https://github.com/dart-lang/test#running-tests-with-custom-html).

**Comment by AlexanderJohr** [comment]
Year, that did it! Thanks!

It is confusing though. I have to call the html page same as the dart test file - e.g. number_formater_test.dart and number_formater_test.html. But I should not use the same URL for running the test. It does nothing. Instead, I have to access it via number_formater_test.debug.html.

**Comment by natebosch** [comment]
https://github.com/dart-lang/test/issues/907
