### ISSUE TITLE
Warn a developer if an error message in their package is served from cache

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/build#1673]
This issue is a reaction to my confusion here: https://groups.google.com/a/dartlang.org/d/msg/misc/5KdzgsyGiAc/fCiNj9zfAgAJ

To avoid this confusion for other developers in the future, it could be better communicated when a builder is actually executed, and when the build output is retrieved from cache.

Right now, the output looks like this (with `--verbose`):
```
[SEVERE] regular_scanner|scanner_builder on example/main.dart:
Error running TableDrivenScannerGenerator
<stack trace>
```

I think it would be good to add something like: `[WARNING] regular_scanner|scanner_builder on example/main.dart is cached, showing previously generated output`

**Comment by natebosch** [comment]
I think I'll go with:

```
[SEVERE] regular_scanner|scanner_builder on example/main.dart: (cached)
Error running TableDrivenScannerGenerator
<stack trace>
```

Note the end of the `SEVERE` line. Then I'll add an `FAQ` that should be discoverable by searching for "cached"
