### ISSUE TITLE
Need a way to test against real dependencies

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#168]
build_test makes it easy to test with *all* fake sources, but there is no way to test with a fake primary input but real dependencies. Currently we need clunky end-to-end tests.

**Comment by natebosch** [comment]
Ideally this should work with the same test with and without bazel.

**Comment by matanlurey** [comment]
Current API:

```dart
Future testBuilder(
  Builder builder,
  Map<String, dynamic> sourceAssets, {
  Set<String> generateFor,
  bool isInput(String assetId),
  String rootPackage,
  RecordingAssetWriter writer,
  Map<String, dynamic> outputs,
  void onLog(LogRecord log)
})
```

Potential future API (just a scratchboard):

```dart
Future testBuilderOn(
  Builder builder,
  String inputName,
  dynamic inputContents, {
  Iterable<String> dependencies,
  ...
})
```

Idea for use:

```dart
testBuilderOn(myBuilder, 'input.dart', '''
  import 'package:angular2/angular2.dart';

  class Foo {}
''', dependencies: [
  'package:angular2/**/*.dart',  
]);
```

(I realize this isn't sound, just want to start a conversation)

--- 

There is also the possibility of just exposing a `TestBuildStep`, i.e:

```dart
main() {
  TestBuildStep buildStep;

  setUp(() {
    buildStep = new TestBuildStep(...)
  });

  test('CopyBuilder should copy all primary inputs', () async {
    buildStep.addPrimaryInput('package:a/a.dart', '// Hello World');
    var buildResult = await testBuilderWith(const CopyBuilder(), buildStep);
    expect(buildResult, wroteFile('package:a/a.dart.copy', '// Hello World'));
  });
}
```

This actually might be more immediately useful for AngularDart, but will require more work - i.e. a `TestBuildStep` API.

**Comment by natebosch** [comment]
We have some ideas around this but any solution we can come up with is either:

- very complex/hacky
- requires a different setup on bazel vs pub

**Comment by matanlurey** [comment]
Even something like a `TestBuildStep` @natebosch?

**Comment by jakemac53** [comment]
What if we required you to have a physical dart import to anything you wanted to load, and we used the dart vm itself to resolve the imports? I don't know 100% that we have all the features needed available to us, but it might be worth trying...

**Comment by matanlurey** [comment]
FWIW, I'm able to get bazel-only testing by doing the following. Just thought I'd share so we can think about how to make a build-system independent API:

```dart
main() {
  final bazelRunFiles = Platform.environment['RUNFILES'];
  const workspaceDir = const String.fromEnvironment('workspaceDir');

  var realPackage = 
    new File('$bazelRunFiles/$workspaceDir/real_package/lib/real_package.dart')
        .readAsStringSync();

  var inputFiles = {
    'real_package|lib/real_package.dart': realPackage,
  };
}
```

We'd need an universal way of doing this, though :-/

**Comment by matanlurey** [comment]
Edit: Similar to the `bazel_codegen` / `build_runner` split, what about:

```dart
// build_test|lib/src/resolve_inputs.dart
import 'dart:io';

Map<String, String> resolveInputs(Iterable<String> glob) {
  if (Platform['RUNFILES'] != null) {
    return _resolveInputsForBazel(...);
  }
  return _resolveInputsForPub(...);
}
```

**Comment by matanlurey** [comment]
I'm going to take a shot at this, though I might need a pass or two to make sure this works seamlessly in transformers/build_runner/bazel.

**Comment by matanlurey** [comment]
I think I have everything necessary to implement what I want at this point. I'm going to assume a combination of `PackageAssetReader` and `MultiAssetReader` gives me the ability to mimic real builds with fake inputs (but real dependencies). Will re-open if I end up finding out otherwise - it's possible we could use some sugar (i.e. `testBuilderOn`, but I'll bring that up when I have a good use case and defaults).
