### ISSUE TITLE
Too little information in stacktrace, debugger keeps stepping into dartsdk source

### ISSUE THREAD

**Issue by Meai1** [dart-lang/build#1690]
1.

Reproduce: 
```
dependencies:
    decimal: "^0.3.0"
```

```
import 'package:decimal/decimal.dart';

main() {
  Decimal.fromInt(5) / Decimal.fromInt(0);
}
```
*Dart VM version: 2.0.0-dev.69.4 (Fri Jul 27 11:42:55 2018 +0200) on "linux_x64
*Chrome 67

>   build  version: "0.12.7+2"
>   build_config: version: "0.3.1+2"
>   build_modules: version: "0.3.1+1"
>   build_resolvers: version: "0.2.1+1"
>   build_runner: version: "0.9.2"
>   build_runner_core: version: "0.2.2+2"
>   build_web_compilers: version: "0.4.1"

2.

I made a video, please keep in mind that I'm pressing F10 here the whole time. My expectation would be to step over the single user code line that I have here and then just printing the stacktrace. The stacktrace should let me jump to that single usercode line and optionally navigate further into dart2js source code if I want to but that shouldn't be necessary right. This is the only line and yet I'm in a never ending step battle.

http://webm.land/media/84bs.webm

**Comment by natebosch** [comment]
I filed https://github.com/dart-lang/sdk/issues/34029 with what I understand the request to be. It looks like you're using DDC.
