### ISSUE TITLE
ToString support desperately needed for debugging

### ISSUE THREAD

**Issue by Meai1** [dart-lang/build#1691]
I made a video showing the problem, the toString() method perfectly shows what I actually need to know. **No matter how deep I go into this object, I'm not getting useful information.** It's completely opaque to me, it catapults me back into printf debugging if we dont get toString() support. I dont know if this is even possible because this is all just source mapped but I hope it is.. it just has to be. The entire debugging story is broken unless this can be done somehow.

http://webm.land/media/esaf.webm

I use the same dependencies/build setup as in the issue I made here: https://github.com/dart-lang/build/issues/1690

**Comment by jakemac53** [comment]
cc @vsmenon @alan-knight

**Comment by jakemac53** [comment]
This should probably move to the SDK repo, as its a general tooling issue not directly related to package:build

**Comment by vsmenon** [comment]
Have you enabled custom formatting?

**Comment by Meai1** [comment]
I dont know what you mean vsmenon, I'm not aware of a feature like that except for formatting the code in the IDE but surely you don't mean that.

**Comment by vsmenon** [comment]
https://webdev.dartlang.org/guides/debugging#enabling-custom-formatters

**Comment by matanlurey** [comment]
Yes, this is handled by custom formatting:
https://webdev.dartlang.org/guides/debugging#enabling-custom-formatters

It is also now documented on our website:
https://webdev.dartlang.org/guides/debugging#enabling-custom-formatters
