### ISSUE TITLE
Add a "package" granularity to build_modules

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1693]
If a package does not have a mix of platform specific libraries for different platforms, and doesn't use config specific imports, it should be safe to compile it as a single module which could also be even more performant than coarse when there are multiple entrypoints.

The concern here would be configuration. I can imagine it being easy to opt in to this within a package, but if we need a way to push this configuration to your dependencies we don't have a great pattern right now. It is possible with `<package_name>.build.yaml` files, but that isn't super safe to do.

**Comment by jakemac53** [comment]
There is also a build time and loading time concern here - you should only have to load/compile the things reachable from the public thing you are importing.

**Comment by natebosch** [comment]
> you should only have to load/compile the things reachable from the public thing you are importing.

Yeah this would only be useful when you assume that the majority of the code is used.

Since our original impetus for module discovery was handling code for different platforms in the same package, it's possible that a package granularity will work even better when we have platform specific modules. The web module could throw away any library which import dart:mirrors for instance...

**Comment by jakemac53** [comment]
If we haven't done this by now, we probably don't need to :)
