### ISSUE TITLE
Does not resolve URIs in entrypoints inside a subdirectory of web/

### ISSUE THREAD

**Issue by munificent** [dart-lang/build#1694]
With the latest bleeding edge SDK, build_runner serve and build_runner build are generating errors like:

```
[SEVERE] build_web_compilers|ddc on web/debug/generation.module:
Error compiling dartdevc module:hauberk|web/debug/generation.ddc.js

[error] Target of URI doesn't exist: 'histogram.dart'. (/web/debug/generation.dart, line 6, col 8)
```

This problem does *not* occur on the latest dev SDK (2.0.0-dev.64.1).

If temporarily remove the `web/debug` directory, the build completes without error:

```
~/dev/hauberk (master *) → pub run build_runner serve
[INFO] Generating build script completed, took 322ms
[INFO] Setting up file watchers completed, took 23ms
[INFO] Waiting for all file watchers to be ready completed, took 202ms
[INFO] Building new asset graph completed, took 820ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 16.3s
[INFO] Caching finalized dependency graph completed, took 202ms
[INFO] Succeeded after 16.5s with 344 outputs (2112 actions)
Serving `web` on http://localhost:8080
```

And it serves up my app. But then I see another problem: changes to my code are not reflected by `build_runner serve`. If I change some code, I see that a build occurs:

```
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 11ms
[INFO] Running build completed, took 2.4s
[INFO] Caching finalized dependency graph completed, took 217ms
[INFO] Succeeded after 2.6s with 6 outputs (6 actions)
```

But it still serves up the app from before my change.

To repro:

```sh
$ git clone https://github.com/munificent/hauberk.git
$ cd hauberk
$ pub get
$ pub run build_runner serve
```

**Comment by jakemac53** [comment]
Looks like our cron job (which runs on edge) is failing with similar errors, https://travis-ci.org/dart-lang/build/jobs/410045783

**Comment by jakemac53** [comment]
Filed https://github.com/dart-lang/sdk/issues/34035 to investigate from the sdk side of things as it appears to be an sdk bug on the surface - although it is possible we need to change how we use 
library/module root.

**Comment by munificent** [comment]
I checked with my game on the latest bleeding edge, and it's working perfectly. Thanks for the quick fix!

**Comment by jakemac53** [comment]
Travis is passing now, https://travis-ci.org/dart-lang/build/builds/410518790
