### ISSUE TITLE
FileSystemException: Failed to watch path, path = 'XXXX' (OS Error: No space left on device, errno = 28)

### ISSUE THREAD

**Issue by bl4ckm4jick** [dart-lang/build#1711]
Dart SDK Version :2.0.0-dev.69.1 (Fri Jul 20 18:30:52 2018 +0200) on "linux_x64"
build_runner 0.9.2

I ran into this issue on Fedora 28 Workstation. When running webdev (through webstorm, but also command line) it throws a failed to watch path error due to errno 28. This was using a vanilla installation of dart-sdk (and webstorm). And creating the default Dart projects

```
xxx/pub global run webdev serve web:33915
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 25ms

[INFO] Waiting for all file watchers to be ready...


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


FileSystemException: Failed to watch path, path = 'xxx/untitled2' (OS Error: No space left on device, errno = 28)
dart:isolate  _RawReceivePortImpl._handleMessage

Dart Dev Server terminated
```
I could not find any issues reporting this in dart, but I was able to resolve the issue by increasing the maximum number of watchers in inotify from 8192 which was the default.
```
echo 1048576 > /proc/sys/fs/inotify/max_user_watches
```
or more permanently with editing /etc/sysctl.conf and adding.
```
fs.inotify.max_user_watches=1048576
```
At least a more informative error would be helpful, as "No Space left on device" is misleading.

**Comment by natebosch** [comment]
Yeah, we do want a better error message for this. Tracking at https://github.com/dart-lang/build/issues/867

**Comment by MalcolmMielle** [comment]
Can't thank you enough for this. Same machine, same problem ! Solution solved it

**Comment by GaspardMerten** [comment]
Thank you for the solution :100:  :+1:

**Comment by basnetjiten** [comment]
echo 1048576 > /proc/sys/fs/inotify/max_user_watches Thank you for figuring this out and solving the problem :)

**Comment by insinfo** [comment]
Thank you for the solution  👍

**Comment by tony123S** [comment]
```
xxx@xxx:~/AndroidStudioProjects/xxx$ echo 1048576 > /proc/sys/fs/inotify/max_user_watches
bash: /proc/sys/fs/inotify/max_user_watches: Permission denied
```

How to fix?

**Comment by bl4ckm4jick** [comment]
@tony123S you will need to enter the command as root
