### ISSUE TITLE
How to listen to changes in other folders or file except lib

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/build#1713]
```
dart --version
Dart VM version: 2.0.0-dev.63.0.flutter-4c9689c1d2 (Mon Jun 18 15:50:02 2018 +0000) on "macos_x64"
```
I'm a flutter developer, I want to generate dart code to help me manage the assets.
Flutter's asset is declared in the `pubspec.yaml`.

I'm want to watch the `pubspec.yaml` 's change or the images folder's change to auto generate dart code, but the build_runner seem only support lib folder's change.

So, my builder is only use the FileSystemEntity.watch to watch file change ,and the `flutter packages pub run build_runner build` is block. I must use cmd+c the exit the build_runner and I run the build again is nothing because the main.dart isn't changed.

question:
 Can this build listen to folders except lib. What can I do？

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/pull/1716, where I proposed a new FAQ section on this topic.

**Comment by CaiJingLong** [comment]
Get it.
But I can't be sure that the user's pictures and other resource files must be in the images directory, which can be configured through pubspec.yaml.

So ,other solution?
@jakemac53

**Comment by jakemac53** [comment]
If you are releasing a builder to users via pub or some other mechanism, those users will have to set up their build.yaml appropriately given the instructions in the FAQ.

The recommendation I would give a builder author is to try and detect the situation and give a nice warning pointing at the FAQ. There is a `canRead` method on `buildStep`, which will allow you to check if you can read a file. If you can't you could `log.warning` some message.

**Comment by CaiJingLong** [comment]
@jakemac53  thx ,I will read the document and tell the user how to customize the configuration of build.yaml.
