### ISSUE TITLE
FileSystemException: Cannot create link to target

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/build#1740]
From https://travis-ci.org/pulyaevskiy/node-interop/jobs/414168807 :
```
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

FileSystemException: Cannot create link to target '/home/travis/.pub-cache/hosted/pub.dartlang.org/node_interop-1.0.0-dev.9.0/test/all_test.dart', path = 'build/test/all_test.dart' (OS Error: File exists, errno = 17)
dart:isolate  _RawReceivePortImpl._handleMessage
```

* [x] Dart 2.0.0 (`dart --version`)
* [x] `build_runner: ^0.10.0`, `build_test`
* [x] `build_node_compilers: ^0.1.12`
* [x] Linux / Travis
* [x] Whether you are using Chrome, Safari, Firefox, Edge - no
* [x] Any other packages or constraints we should know about - for some reason only happens during Travis build for me https://travis-ci.org/pulyaevskiy/node-interop/jobs/414168807

**Comment by natebosch** [comment]
hmm, why are we trying to create a link to a file in a hosted package outside of it's `lib/`?

`test/all_test.dart` does exist in both `node_interop` and `node_io`. This looks like it's happening when testing `node_io`. I'm curious to know how `asset:node_iterop/test/all_test.dart` would get in the AssetGraph at all...

**Comment by natebosch** [comment]
It is an explicit source in a target - https://github.com/pulyaevskiy/node-interop/blob/bdb1b4d9c69a3f586cbafe8f8a45132b7fcc7aac/node_interop/build.yaml#L6

I bet we aren't correctly filtering non-lib stuff when we construct the asset graph.

**Comment by pulyaevskiy** [comment]
I'm not sure I'm following the above, but this only happens when I run tests on Travis. Locally on macOS everything works fine.

It doesn't seem like an OS issue to me though. I'll try to delete these files and see how build reacts to this.

**Comment by pulyaevskiy** [comment]
Oh, ok, I think I'm starting to understand the issue.

I tried removing `test/**` from build.yaml in node_interop but it doesn't work and running `pub run build_runner test` fails with "no such file".

@natebosch anything you could recommend for me to do on my end to fix this? Or is this something that needs to be fixed on the `build_runner` side?

**Comment by natebosch** [comment]
> I tried removing `test/**` from build.yaml in node_interop but it doesn't work and running `pub run build_runner test` fails with "no such file".

Where you in the `node_interop` or `node_io` package when you tried that command? I'm most curious about what happens if you remove that pattern from the glob in `node_interop` and then run a test in `node_io` with a path override to that package.

I can't think of any other potential workarounds, and even with that workaround this is something that needs to be fixed in `build_runner`.

**Comment by pulyaevskiy** [comment]
Ok, so basically I got lucky that all of the files in my packages have distinct names, except for `all_test.dart` so they don't overwrite each other.

I suspect that if I remove it from node_interop it should resolve the issue. Though I'll try to remove both of them as they were also a workaround for dart2js failing to compile many entrypoints on Travis. But it seems to be not an issue anymore.

**Comment by natebosch** [comment]
Fix is published - please try a `pub upgrade` and it shouldn't happen anymore.

**Comment by pulyaevskiy** [comment]
Awesome, thanks @natebosch !

**Comment by 3990995** [comment]
delete pubspec.lock  and flutter pub upgrade and flutter pub get  fix
