### ISSUE TITLE
Auto-generated `*.debug.html` now broken

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1749]
`Refused to execute script from 'http://localhost:8080/regression/1539_nested_template_test.dart.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

(Likely because the test names were changed)

**Comment by matanlurey** [comment]
I don't believe there were any errors, I think we accidentally changed the auto-gen'd names?

**Comment by jakemac53** [comment]
For our e2e examples it works still :/

**Comment by matanlurey** [comment]
Thanks! I'll re-open if I see this again.
