### ISSUE TITLE
Hot restart should restore the page to its initial state by default, or require a custom hook

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1762]
Today the default handler simply invokes `main()`, but that won't get rid of the existing application on the page. Thus, if you append some tags to the body in your `main()`, then it will keep appending new copies of the app.

Internally we deep clone the original `document.body` before initially calling `main`, and then restore it to that state before we re-invoke `main`. This definitely isn't a universal solution, but is somewhat reasonable and tends to work for a lot of apps.

We could either implement that as the default, or we could possibly just require some top level hook to be implemented before we will even attempt to hot restart.

**Comment by samogot** [comment]
With #1765 it would be possible to implement client hook this way
```
var _id = 'hello';

void main() {
  var helloDiv = Element.div()
    ..id = _id
    ..text = 'Hello Dart';
  document.body.append(helloDiv);
}

Object hot$onDestroy() {
  document.body.querySelectorAll('#$_id').forEach((e) => e.remove());
}
```

It will work even if `_id` is changed between versions.

**Comment by jakemac53** [comment]
I think that as long as this is well documented it should be sufficient - one nice thing about these magic top level hooks is dart2js should optimize them away as well :).
