### ISSUE TITLE
Error output references [filename].ddc.js

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/build#1780]
When debugging a web app with `<base href="/">` set, error stacktraces only references .ddc.js files.

I've created a minimal repro here:
[https://github.com/afpatmin/sourcemap_issue_repro](https://github.com/afpatmin/sourcemap_issue_repro)

Here's the error output with `<base href="/">` set:
[https://www.dropbox.com/s/b00hdmyaavlnr10/with-base.png?dl=0](https://www.dropbox.com/s/b00hdmyaavlnr10/with-base.png?dl=0)

And here it is without:
[https://www.dropbox.com/s/bcx6rpn9kv7wiv5/without-base.png?dl=0](https://www.dropbox.com/s/bcx6rpn9kv7wiv5/without-base.png?dl=0)

"Enable JavaScript source maps" and "Enable custom formatters" are both checked in Chrome console settings.

Dart VM version: 2.0.0 (Unknown timestamp) on "linux_x64"
build_runner: 0.10.1+1
build_web_compilers: 0.4.2+2
Builders: default
Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by jakemac53** [comment]
Do you get general source maps or does that not work either?

**Comment by afpatmin** [comment]
Yes source maps works properly right up to the point when I add the `base` tag

**Comment by jakemac53** [comment]
Right, but do the source maps show up in dev tools at all with the `base` tag, or is it only for stack traces that it appears to be an issue?

**Comment by afpatmin** [comment]
Aha, yes it seems only stack traces doesn't work. I can still browse the .dart files directly under the sources tab, set breakpoints etc. I created a minimal project to demonstrate the issue if you like to test it yourself

**Comment by drbcode** [comment]
This PR will fix this issue:
https://github.com/dart-lang/build/pull/1781
