### ISSUE TITLE
Can not skip dart:mirrors

### ISSUE THREAD

**Issue by valotas** [dart-lang/build#1790]
Environment:

* Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "linux_x64"
* build_runner: 0.10.1+1, build_test: 0.10.3+1
* build_web_compilers: ^0.4.0
* linux
* code: https://github.com/valotas/mustache4dart/tree/dart2browser

I get the following:

```
[SEVERE] build_web_compilers|ddc on lib/src/reflect.module (cached):
Error compiling dartdevc module:mustache4dart|lib/src/reflect.ddc.js

[error] Cannot import "dart:mirrors" in web applications (https://goo.gl/R1anEs). (package:mustache4dart/src/reflect_with_mirrors.dart, line 1, col 8)

Please fix all errors before compiling (warnings are okay).
}
```

which is true but [`reflect_with_mirrors.dart` is conditionally imported](https://github.com/valotas/mustache4dart/blob/dart2browser/lib/src/reflect.dart#L2) only when `dart.library.mirrors` is available.

Is this behavior intended?

**Comment by matanlurey** [comment]
I don't believe that conditional variable is actually supported.

**Comment by matanlurey** [comment]
I do not believe you can

**Comment by matanlurey** [comment]
We should probably fail early on unsupported conditional literals? 

@jakemac53 @natebosch

**Comment by natebosch** [comment]
We're moving forward with conditional import support. Not sure of a timing yet

**Comment by valotas** [comment]
Is there any workaround for the moment? The only thing that I can think of
is completely different entry point for the browser.

**Comment by jakemac53** [comment]
Yes the only thing that works today is a totally different entrypoint, using dependency injection or something provide the correct implementation for the platform.

I am working on support for this feature currently but its a little ways out still from landing.

**Comment by jakemac53** [comment]
Ok, @valotas if you update to the latest build_modules/build_web_compilers/build_vm_compilers (likely just requires a pub upgrade), then this should now be supported.

Please file any issues if you have trouble!

**Comment by jakemac53** [comment]
Do note though that at least for now you will have to add `// ignore: uri_does_not_exist` comments on your config specific imports, at least until https://github.com/dart-lang/sdk/issues/34177 is resolved.

**Comment by jakemac53** [comment]
Actually @natebosch made a good point that you are also using config specific exports, there is also an SDK issue for those (they don't work at all unfortunately, due to an analyzer issue). You can follow along at https://github.com/dart-lang/sdk/issues/34179, as soon as it is fixed in the sdk there shouldn't be anything required on the build package side of things.

**Comment by valotas** [comment]
It looks like it works! Thanks for the quick response!
