### ISSUE TITLE
Should FileBasedAssetReader handle long paths on Windows?

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/build#1816]
An Angular user found that they couldn't build an application with long paths on Windows, due to the [260 character maximum path](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation) limit: https://github.com/dart-lang/angular/issues/1605.

There's an issue filed against the SDK for `File` from `dart:io` to support long paths, but as @whesse pointed out, there are undesirable consequences of using long paths by default (they don't support relative paths).

Since it's unlikely `dart:io` will handle this automatically, should the `package:build` ecosystem automatically apply the long path prefix (`\\?\`) on Windows? Since the build ecosystem can (likely already does) use absolute paths, the limitations of using long paths shouldn't be an issue.

**Comment by natebosch** [comment]
I commented on the linked angular issue, but I share the same concerns expressed here: https://github.com/dart-lang/sdk/issues/27825#issuecomment-260955635

If we try to be too magic with this there is a good chance we'll break some other expectation.

@jakemac53 - what are your thoughts?

**Comment by jakemac53** [comment]
The reasoning in that issue seems pretty sound, if we can't support symlinks or forward slashes that would cause us a lot of issues.

**Comment by jakemac53** [comment]
One argument for this though is unlike the SDK, our users don't have the ability to solve the problem in their own code since they don't hit the file system directly... they have to hack their registry to disable this check.

**Comment by jakemac53** [comment]
I think we pretty much decided not to do anything here. The recommendation is to edit your registry settings to allow longer paths.

If we get enough reports of issues like this we can re-evaluate.
