### ISSUE TITLE
Moving files around tends to case the build server to need to be restarted

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/build#1823]
When files are named incorrectly, or refactored, fixing them does not fix the build.

Steps to reproduce:

- create a component
- use the wrong templateUrl or styleUrl
- observe error says that the `.template.dart` file is missing (not helpful IMHO)
- fix it
- observe the build still fails
- run `pub run build_runner clean`
- run `webdev serve` again
- observe the build succeeds

platform:

* Dart SDK version: 2.0.0
* AngularDart version 5.0.0
* macOS

**Comment by johnpryan** [comment]
There are other cases where I need to completely restart (e.g. run `pub run build_runner clean` and then a fresh build with `webdev serve`) for example, when changing a `template` attribute to a `templateUrl` attribute. Or when changing the name of SCSS files.

**Comment by johnpryan** [comment]
Using the `sass_builder` package, if the SCSS file is broken and then fixed, the build package gets into a state where the SCSS error is not provided (because it's fixed) but it still can't find the generated file:

```
Please check the following imports:

`import 'package:my_package/my_component.css.shim.dart' as import0;` from my_package|lib/my_component.template.dart at 17:1

```

**Comment by jakemac53** [comment]
Going to take a shot at a repro for these

**Comment by jakemac53** [comment]
I tried reproducing the first two scenarios and can't replicate the error (build succeeds when I fix the issue) :/.

Are you using symlinks for your source files by chance? Or anything else like that? Can you try killing the server and restarting it (without a clean) and see if that fixes things for you?

**Comment by johnpryan** [comment]
Yeah I'll try that today the next time I hit the issue. We've been hitting it quite a bit. We are not using symlinks AFIAK, we are just using a normal angulardart 5.0.0 project (with sass_builder.)

In general I find that doing some refactoring on angulardart components tends to reproduce the issue.

Would running with verbose logging help provide more detail?

**Comment by jakemac53** [comment]
It might help ya, that will show us the file change events that are seen (or not)

**Comment by johnpryan** [comment]
Ok sounds good I'll run in verbose mode today and see if i run into the issue again. Unfortunately I wasn't able to reproduce the issue using the AngularDart Stagehand template

**Comment by johnpryan** [comment]
Could this be an issue with `webdev` or `sass_builder`?

**Comment by jakemac53** [comment]
almost certainly not `webdev`, but possibly `sass_builder` somehow

**Comment by johnpryan** [comment]
Just found some steps:

1. Create an AngularDart 5.0.0 app (using stagehand)
2. run pub run `build_runner serve`
3. create a new Dart file that references files that don't exist yet:

```
import 'package:angular/angular.dart';

@Component(
  selector: 'fancy-app',
  templateUrl: 'fancy_app_component.html',
  styleUrls: const [
    'fancy_app_component.css',
  ],
  directives: const [
    coreDirectives,
  ],
)
class FancyApp {
  FancyApp();
}
```
3. create the missing files `fancy_app_component.css` and `fancy_app_component.html`
4. observe the build still fails
5. start and stop the build server
6. observe the build still fails
7. stop and run `pub run build_runner clean`
8. start the build serve and observe it succeeds

here's the output i saw with the verbose flag:

[build_runner_output.txt](https://github.com/dart-lang/build/files/2394027/build_runner_output.txt)

**Comment by jakemac53** [comment]
Awesome, I can repro using those steps thanks!
