### ISSUE TITLE
Error while testing code generation in Dart: Builder failed to write asset

### ISSUE THREAD

**Issue by jorgecoca** [dart-lang/build#1828]
Dart version: 2.0
Builder Runner version: 0.10.2
Builder used: SharedPartBuilder
Building on Mac
----
Question posted here: https://stackoverflow.com/questions/52339888/error-while-testing-code-generation-in-dart-builder-failed-to-write-asset
---
I have create a Dart (Dart v2) code generator to detect annotations of type Cooper.

The generator looks like this:

```dart
class CooperGenerator extends GeneratorForAnnotation<Cooper> {
  @override
  Future<String> generateForAnnotatedElement(
      Element element, ConstantReader annotation, BuildStep buildStep) async {
    final name = annotation?.peek("implementationClassName")?.stringValue ?? "CooperApi";
    return "class $name {}";
  }
}
```

I am writing unit tests to verify that my Generator works as expected. Looks like this:

```dart
import 'package:build/build.dart';
import 'package:test/test.dart';
import 'package:build_test/build_test.dart';
import 'package:source_gen/source_gen.dart';
import 'package:cooper_generator/cooper_generator.dart';

void main() {
  group('CooperGenerator', () {
    test('generates implementation for classes annotated with @Cooper',
        () async {
      final builder = PartBuilder([CooperGenerator()], '.g.dart');
      await testBuilder(builder, _inputs, outputs: _output);
    });
  });
}

final _output = {
  "jorge|lib/coop.g.dart": '''
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'coop.dart';

// **************************************************************************
// CooperGenerator
// **************************************************************************

class CooperImplementation {}
          '''
};

final _inputs = <String, String>{
  'cooper|lib/cooper.dart': _cooperSource,
  'jorge|lib/coop.dart': _classToGenerate,
};

const String _classToGenerate = r'''
    import 'package:cooper/cooper.dart';
    @Cooper("CooperImplementation")
    abstract class CooperContract {}
''';

const String _cooperSource = r'''
class Cooper {
  final String implementationClassName;

  const Cooper(this.implementationClassName);
}
''';
```

The code works perfectly fine, and it generates the code I am expecting. However, when running the unit tests, I am getting the following error, and I can't understand why:

```
ERROR: Expected: contains AssetId:<jorge|lib/coop.g.dart>
Actual: ?:[]
Builder failed to write asset jorge|lib/coop.g.dart

package:test                                    expect
package:build_test/src/test_builder.dart 49:7   checkOutputs.<fn>
dart:collection                                 __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach
package:build_test/src/test_builder.dart 41:13  checkOutputs
package:build_test/src/test_builder.dart 140:3  testBuilder
===== asynchronous gap ===========================
dart:async                                      _AsyncAwaitCompleter.completeError
package:build_test/src/test_builder.dart        testBuilder
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
package:build_test/src/test_builder.dart        testBuilder
test/generator_test.dart 12:13                  main.<fn>.<fn>
```

Any ideas? Thanks!

**Comment by jakemac53** [comment]
I think you need to pass `rootPackage: 'jorge'` to the `testBuilder` call.The api there is a bit weird (it should probably be a required arg). By default it expects a root package name of "a" which is what we use internally in all our tests (we extracted this utility from our internal build_runner testing utilities originally, where we follow that convention).

**Comment by jorgecoca** [comment]
Even when I add `rootPackage: 'jorge'`, it keeps failing with the same error. Any other ideas?

**Comment by jakemac53** [comment]
I tried to repro and it works fine for me with your example :/

**Comment by jakemac53** [comment]
going to close as this is getting stale, but feel free reopen if you are still having issues

**Comment by elnurvl** [comment]
I am encountering this problem also. Tried a lot of ways. No success. Even the above snippet does not work on my environment despite noting it is working.

`environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.34.0
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.1.0
  build_test: ^0.10.3
  collection: ^1.14.10
  path: ^1.6.2`

**Comment by elnurvl** [comment]
@jorgecoca , did you solve the issue? If yes, can you please explain the cause of the error and the solution for it?
