### ISSUE TITLE
[build]: Efficient way of copying (other than read/write)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#183]
I'd like to be able to do:

```dart
Future build(BuildStep buildStep) async {
  await buildStep.copy(inputAsset, outputAsset);
}
```

I've "implemented" it today by using `readBytes` and `writeBytes` as a stopgap.

**Comment by natebosch** [comment]
[nit] should not `await` this :)

If we had extension methods this seems like a good use case. As is I think we're better off not expanding the interface for a situation that isn't likely to come up very often.

One thing we'll look at when `FutureOr<T>` is more widespread is whether the `write` methods should take that type which would make it possible to not wait for the read.

**Comment by natebosch** [comment]
This can now be written as

```
buildStep.writeAsBytes(outputAsset, buildStep.readAsBytes(inputAsset));
```

With a copy method we'd save ~ `buildStep.readAsBytes()` which is not enough to add a utility for a situation that should come up pretty rarely.
