### ISSUE TITLE
bug when test `pub run build_runner build --config debug` commands

### ISSUE THREAD

**Issue by herowuking** [dart-lang/build#1841]
OS: Microsoft Windows [Version 10.0.16299.15]
IDE: Visual Studio Code V1.27.2
Dart: Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"

I just want to test how to build a web app demo with dart, here is my operation steps:
1. Open VS Code， Select a foleder , open Terminal , input `stagehand web-angular` ,return;
2. `pub get` , return;
3. `pub run build_runner build --config debug`, return:
----------------------------------------------------------------
[INFO] Generating build script completed, took 631ms

**You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues**

FileSystemException: Cannot open file, path = 'build.debug.yaml' (OS Error: The system could not find the specified file. , errno = 2)
dart:io                                                                   _File.readAsStringSync
package:build_runner/src/package_graph/build_config_overrides.dart 29:23  findBuildConfigOverrides
package:build_runner/src/generate/build.dart 95:15                        build
package:build_runner/src/entrypoint/build.dart 28:24                      BuildCommand.run
package:args/command_runner.dart 194:27                                   CommandRunner.runCommand
package:args/command_runner.dart 109:29                                   CommandRunner.run.<fn>
dart:async                                                                new Future.sync
package:args/command_runner.dart 109:11                                   CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31                        run
.dart_tool\build\entrypoint\build.dart 132:22                             main

**Comment by herowuking** [comment]
sorry，I think I made a mistake.
 the file `build.name.yaml ` should be created manually...

**Comment by herowuking** [comment]
> 
> 
> sorry，I think I made a mistake.
> the file `build.name.yaml` should be created manually...

the message `You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues` misled me

**Comment by jakemac53** [comment]
Ya we should handle this exception and give a better error message here.

Fwiw though - in general you shouldn't need a "build.debug.yaml" any more. We now support `debug_options` and `release_options` keys for all builders so you can configure them all in the normal `build.yaml`.

**Comment by jakemac53** [comment]
I also filed https://github.com/dart-lang/site-webdev/issues/1825 to remove the misleading section and update this page generally, its quite out of date.
