### ISSUE TITLE
Expand analyzer constraints to include 0.33.x versions

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/build#1869]
Dartdoc and other clients of the analyzer that require specific support for the new mixin declarations need to be able to use the 0.33 version, and currently can't if they use build, because of the constraints for analyzer on build.

- [x] build
- [x] build_resolvers
- [x] build_modules
- [x] build_web_compilers

Blocking

- [x] dart-lang/dartdoc#1752
- [x] dart-lang/dartdoc#1765.
- [x] https://github.com/dart-lang/json_serializable/issues/339

**Comment by jakemac53** [comment]
It looks like analyzer is still on 0.33.0-alpha.0, can we wait until a real version is published or does this have to happen beforehand?

**Comment by bwilkerson** [comment]
If we push a non-alpha version then we would probably need to update a large number of packages. We can do that if you feel strongly enough about not using alpha versions, but I always try to avoid it for as long as possible because of the work it makes for everyone else.

**Comment by jakemac53** [comment]
There is no difference though if we are being asked to upgrade to the alpha release? Why would only package:build be required to update?

**Comment by jakemac53** [comment]
(in general if this is for the new mixin declaration support I would expect all users are going to want that anyways, so its worth a major release)

**Comment by kevmoo** [comment]
0.33.0 was published on Thursday. We're already seeing issues w/ Flutter on json_serializable.

**Comment by jcollins-g** [comment]
Dartdoc is no longer hard blocked on this.

**Comment by jakemac53** [comment]
This is done
