### ISSUE TITLE
bazel_codegen's AssetReader does not follow exception contract for readAsBytes and readAsString

### ISSUE THREAD

**Issue by alanrussian** [dart-lang/build#1880]
Instead of returning `CodegenError`s, it should return `PackageNotFoundException`s and `AssetNotFoundException`s.

https://github.com/dart-lang/build/blob/master/build/lib/src/asset/reader.dart#L19-L20

**Comment by alanrussian** [comment]
Link to the bazel asset reader: https://github.com/dart-lang/build/blob/master/bazel_codegen/lib/src/assets/asset_reader.dart

**Comment by alanrussian** [comment]
I'm working on a pull request

**Comment by natebosch** [comment]
Thanks for the report!

Do you need the fix published on `pub` or will it be enough to bring the fix into google?

**Comment by alanrussian** [comment]
I personally only need it fixed in Google. I have a pull request ready if you want me to publish it here. Let me know how you want me to proceed.

**Comment by natebosch** [comment]
> I have a pull request ready

Ah sorry, I saw too late that you were also working on a PR. Is yours different from mine? https://github.com/dart-lang/build/pull/1881

**Comment by alanrussian** [comment]
No problem. I should have stated that earlier. :)

Mine's pretty much the same + tests.

**Comment by natebosch** [comment]
If you've already got tests then we should run with that one :)

If you open it I will review and pull it in to google.
