### ISSUE TITLE
Migrate to AnalysisDriver

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1886]
- [x] `_bazel_codegen`
- [ ] `build_resolvers`

Migrated from https://github.com/dart-lang/bazel/issues/183

**Comment by natebosch** [comment]
This will be breaking for Builders in a similar way that the bazel_codgen migration to summaries was breaking - certain APIs will no longer work when starting from a `LibraryElement`.

During the migration to summaries we had to move away from `computeNode()` (and, unknown at the time, away from `.unit`) on any library that was coming from a summary. These APIs were giving an escape hatch into the AST model which doesn't work backed by a summary.

During the migration to `AnalysisDriver`, or eventually `AnalysisSessions` we'll also have to move away from these APIs for the libraries that we have the source for. It's still possible to to get to an AST model but _not_ through the `LibraryElement`. Today the option is to start by accessing the AST model for a URI and then crawling that model. Eventually there may be new ways to jump to the AST model for a given Element that don't involve calling APIs on that element.

**Comment by yury-yufimov** [comment]
@natebosch , am I right, that this is strategic / long-term plans, and these changes won't be available in DartSDK 2.1 / 2.2 ?

**Comment by natebosch** [comment]
Moving forward with this is not tied to a particular SDK version.

We are blocked on moving forward until we can make sure we update known usages of the Resolver API so that they work with the `LibraryElement` instance that will be produced by the driver model.

**Comment by jakemac53** [comment]
Note we also need to update to return empty sources for uris that we don't have a source for, see discussion at https://github.com/dart-lang/build/pull/1910
