### ISSUE TITLE
Make `AssetId.parse` harder to misuse

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1899]
The `AssetId.parse` constructor only handles the format created by `AssetId.toString()` and was mostly meant as a cheaper serialization format when writing to json. It was never really meant to be used outside of build system implementations that deal with serializing large numbers of IDs.

Unfortunately it's leaked a bit into some build users. For instance Angular has a dependency on the fact that the `Resolver` returns elements where the `element.source.fullName` is a serialized `AssetId`. We happen to implement it that way in our resolvers:

https://github.com/dart-lang/build/blob/0e79b63c6387adbb7e7f4c4f88d572b1242d24df/bazel_codegen/lib/src/summaries/build_asset_uri_resolver.dart#L52-L53

https://github.com/dart-lang/build/blob/0e79b63c6387adbb7e7f4c4f88d572b1242d24df/build_resolvers/lib/src/resolver.dart#L266-L267

And Angular depends on it here:

https://github.com/dart-lang/angular/blob/cbd6150a145457cb8580e61105506ce03ee6895c/angular_compiler/lib/src/outliner/collect_type_parameters.dart#L61

I propose we either:

- Deprecate `AssetId.parse` and transition users to `AssetId.resolve`, make `AssetId.resolve` handle `package|path` serialization format for backwards compatibility, and transition serialization to use `package:` or `asset:` URIs using `AssetId.uri` and `AssetId.resolve` to serialize/deserialize. This would come with some efficiency losses but I don't think they'll have a huge impact. Our asset graph serialization already uses something different and even more space efficient where it doesn't repeat package names. In the next breaking change release for `build` we'd change `toString()` to use `.uri.toString()` since that format is more useful to humans.
- Make `AssetId.parse` handle `asset:` and `package:` URI by forwarding to `AssetId.resolve` when it doesn't have a `|` character. We wouldn't need to deprecate it and could live with both APIs being nearly interchangeable except where there is a `from` argument for relative imports. We could leave existing serialization usage as is. We had originally proposed expanding the allowed format for `AssetId.parse` in https://github.com/dart-lang/build/issues/287 and decided instead to implement as a separate `resolve` API, but don't have a recorded discussion on why we made that choice.

cc @jakemac53 @matanlurey

**Comment by natebosch** [comment]
For completeness I should note that I'm pretty sure it was me who recommended this approach in the angular builder. 😳

**Comment by jakemac53** [comment]
The `Source` class does have a [uri getter](https://github.com/dart-lang/build/blob/0e79b63c6387adbb7e7f4c4f88d572b1242d24df/build_resolvers/lib/src/resolver.dart#L243), should we just migrate angular to use that and completely remove the `parse` method?

**Comment by natebosch** [comment]
It turns out we don't always have control over `source.uri`. We originally can pass a URI `creatSource`, but the analysis driver code paths sometimes do a `Source` -> `fullname` -> `Source` round trip which causes it to lose the URI we had specified. In those cases the URI is a `file:` URI which has some implementation details of how we do a mapping from `AssetId` to an absolute path. We don't more code to rely on those details.

I think what we might need to do is add an api like `Resolver.findAssetId(Element)` and migrate use cases to that.

**Comment by jakemac53** [comment]
cc @natebosch should we just close this at this point? I doubt we will get around to it :D

**Comment by natebosch** [comment]
We did add `assetIdForElement` in #1947 

I think most use cases have migrated over to it. I would be curious to take another look at usage here and figure out if we are exposing the right APIs on `AssetId`.

**Comment by natebosch** [comment]
If we do end up making a breaking change for this we should also consider taking a `Uri` instead of a `String` in `AssetId.resolve`. It is easy to shift the `Uri.parse` to the call site, but in the use case of starting with a `Uri` it's wasteful to go through `.toString()` and then `Uri.parse` again.

**Comment by natebosch** [comment]
I did a quick audit. It looks like `AssetId.parse` would be relatively easy to drop, the majority of usage is in our packages, especially in test code. I think dropping it and allowing some small bits of duplication in the few places we use it makes sense - they should own the details of deserialization from that format, and there is no reason most consumers of the build API should care about it.

We should consider changing the `.toString()` representation, but it's harder to predict if that would cause subtle issues for someone.

It does look like there are usages of `AssetId.resolve` that should be migrated to `resolver.assetIdForElement` since it is safer. I think `AssetId.resolve` does still have valid use cases though so we should keep it.

**Comment by jakemac53** [comment]
I think the question is how much value we would get out of doing this. It hasn't caused any concrete problems that I am aware of so it doesn't seem to really justify a breaking change or a lot of effort to fix it.

**Comment by natebosch** [comment]
If we make end up making a breaking change version bump we should drop the `.parse` constructor and change the argument to `.resolve` to a `Uri`. Both of these are very statically safe. Dropping `.parse` will not cause any churn except for us cause the usage has already been migrated.  Changing the argument type will cause some churn, but it's also higher value. We are doing a lot of `Uri` to `String` to `Uri` (sometimes even more cycles than that) that we should stop.

**Comment by jakemac53** [comment]
Going to take a shot at dropping this with the null safety breaking release

**Comment by jakemac53** [comment]
Ok so I realized we use this internally across several packages (build_test, build_modules, build_runner, build_runner_core). The format itself is also leaked through the `build_test` package in the input/output maps (the format of the keys) as well as in the build_resolvers package.

My 2 cents at this point is that it isn't worth trying to clean this up.

**Comment by natebosch** [comment]
It does look like the pain that would come from dropping `parse` outweigh the costs and risks. 😢 

Oh well, I can learn to ignore that.

I think we should still look at changing the argument to `Resolve` to be `Uri`. I will see how that looks.

**Comment by jakemac53** [comment]
Ok, I am going to go ahead and close this as not planned.

**Comment by jakemac53** [comment]
@natebosch did you still want to evaluate changing the `Resolve` argument?
