### ISSUE TITLE
Add some convenience constructors/DSLs in build_runner

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#190]
I'd like to see:

- [ ] `new PhaseGroup([...])` instead of needing `..addPhase`:

```dart
new PhaseGroup([
  new Phase(),
  new Phase(),
  new Phase(),
]);
```

- [ ] `new Phase.singleAction` instead of `new Phase()..addAction`:

```dart
new Phase.singleAction(builder, inputSet)
```

**Comment by matanlurey** [comment]
@natebosch Any opposition to this? Happy to help out.

**Comment by jakemac53** [comment]
I am fine with adding these

**Comment by natebosch** [comment]
Looks like a good idea

**Comment by matanlurey** [comment]
@jakemac53 @natebosch Still OK with this with new plans?

**Comment by natebosch** [comment]
There is a good chance we'll be changing the surface area of the PhaseGroup stuff a bit... This is still a good idea but we should put them on hold for a bit to avoid doing any work that might get thrown away... Let's keep this issue open and revisit

**Comment by matanlurey** [comment]
Phases no longer exist thanks to @natebosch so closing.
