### ISSUE TITLE
Issue with webdev serve --hostname

### ISSUE THREAD

**Issue by jscholler** [dart-lang/build#1903]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

-> Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"

$  **pub global activate webdev**

Resolving dependencies... (2.3s)
+ args 1.5.1
+ charcode 1.1.2
+ collection 1.14.11
+ io 0.3.3
+ meta 1.1.6
+ path 1.6.2
+ pub_semver 1.4.2
+ source_span 1.4.1
+ stack_trace 1.9.3
+ string_scanner 1.0.4
+ webdev 1.0.0
+ yaml 2.1.15
Downloading webdev 1.0.0...
Precompiling executables... (1.3s)
Precompiled webdev:webdev.
Installed executable webdev.
Activated webdev 1.0.0.

$ **webdev serve --hostname localhost:9000**
Creating build script, took 8523ms

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

NoSuchMethodError: The getter 'address' was called on null.
Receiver: null
Tried calling: address
dart:core                                             Object.noSuchMethod
package:build_runner/src/entrypoint/serve.dart 75:49  ServeCommand._runServe
package:build_runner/src/entrypoint/serve.dart 60:12  ServeCommand.run
package:args/command_runner.dart 196:27               CommandRunner.runCommand
package:args/command_runner.dart 111:29               CommandRunner.run.<fn>
dart:async                                            new Future.sync
package:args/command_runner.dart 111:11               CommandRunner.run
package:build_runner/src/entrypoint/run.dart 23:31    run
.dart_tool/build/entrypoint/build.dart 88:22          main
```

**Comment by jscholler** [comment]
After re-reading the help, I got it right:
$ **webdev serve web:9000**
Creating build script, took 8681ms
[INFO] Setting up file watchers completed, took 21ms
[INFO] Waiting for all file watchers to be ready completed, took 202ms
[INFO] Building new asset graph completed, took 1.1s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 13.2s
[INFO] Caching finalized dependency graph completed, took 166ms
[INFO] Succeeded after 13.4s with 260 outputs (2085 actions)
Serving `web` on http://localhost:9000

**Comment by jakemac53** [comment]
We could add special error handling for this case, that is probably a pretty common mistake.

**Comment by jakemac53** [comment]
I am going to close this as not planned, given the amount of time that has passed and lack of anything done yet :).
