### ISSUE TITLE
Possible race condition causes build_runner to hang

### ISSUE THREAD

**Issue by nshahan** [dart-lang/build#1904]
Dart SDK: 2.1.0
build: 1.0.1
build_runner: 1.1.2

I'm building a new version of the angular_components example gallery. The build process hung at the following point shown below.

It does not respond to CTRL-C to kill the process. It does not log anything when I press CTRL-C either.

```
$ pub run build_runner serve web
[INFO] Generating build script completed, took 436ms
[INFO] Setting up file watchers completed, took 47ms
[INFO] Waiting for all file watchers to be ready completed, took 247ms
[INFO] Reading cached asset graph completed, took 1.4s
[INFO] Checking for updates since last build completed, took 2.6s
[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds. completed, took 1.5s
[INFO] Terminating. No further builds will be scheduled
```

**Comment by natebosch** [comment]
Can you reliably repro this?

**Comment by nshahan** [comment]
Nope, I wish. I was chatting with @jakemac53 about it a little today. He asked that I file an issue to at least have something that others could +1 on if they experienced the same thing and you could get some signal of the severity. 

He also felt that knowing that the interceptor for CTRL-C wasn't working as well as the lack of logging gave a little hint as to where it was hung.

**Comment by natebosch** [comment]
There have been  number of changes to how we start processes/isolates and how we handle signals since this was filed. Hopefully this is resolved - if there is still an intermittent failure we haven't seen it in a long time and don't have anything to go off of to investigate so I'll close.
