### ISSUE TITLE
Remove/deprecated enableSyncAsync & ignoreCastFailures in webEntrypointBuilder

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1905]
https://github.com/dart-lang/build/blob/998b6ca7c1e449b8b7f31c8d45166c2416088627/build_web_compilers/lib/src/web_entrypoint_builder.dart#L32-L33

Not needed – at all any more, right?

**Comment by jakemac53** [comment]
Not sure if you can still disable sync-async or not, @jmesserly ?

I think we still ignore dome cast failures internally, so we probably should still have the option externally too.
