### ISSUE TITLE
A snapshot with no builders "poisons" the invalidation

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1906]
Repro:

- Have a dependency on `build_runner` and no other dependencies with builders
- Run a build. See "Nothing can be built, yet a build was requested."
- Add a dependency on a package with a builder and `pub get`.
- Run a build. Still see "Nothing can be built, yet a build was requested."

Something is interacting poorly with the snapshot invalidation - we're not failing with a cause that would make us regenerate the build script and resnapshot.

There are related bad behaviors when removing dependencies on packages with builders. The snapshot is not invalidated and it tries to run with the old builders. Then we get error messages like

```
[WARNING] build_modules|lib/builders.dart was not found in the asset graph, incremental builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
```

**Comment by natebosch** [comment]
Maybe what we want is to store a hash of the package graph and eagerly invalidate the snapshot if the package graph changes.

**Comment by jakemac53** [comment]
ah ya this explains that gitter issue that was being reported - I think we don't even create an asset graph so it never checks if it got invalidated.

**Comment by jakemac53** [comment]
it looks like if we just remove the CannotBuildException here and let it continue instead then things work as expected - it does a no-op build and serializes the graph, and recognizes that the build script changed if you re-run with new dependencies that add builders.
