### ISSUE TITLE
AssetId.parse but for relative imports

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#192]
For example, someone has the directive:

```dart
import 'some/relative/path.dart';
```

I'd like to create an `AssetId` representing that file in my builder so I can read it.

**Comment by jakemac53** [comment]
Ya this would be nice, what about a `AssetId relative(AssetId to)` instance method on `AssetId`?

**Comment by matanlurey** [comment]
Here is my hack today:

```dart
  AssetId assetId;
    try {
      assetId = new AssetId.parse(directiveUri);
    } on FormatException catch (_) {
      assetId = new AssetId(
        p.normalize(source.package),
        p.join(source.path, directiveUri),
      );
    }
```

(Yes it could be better and not use try/catch, but just playing around)

**Comment by matanlurey** [comment]
+1 to @jakemac53's suggestion.

**Comment by jakemac53** [comment]
We could also add a more general `AssetId.resolve(String uri, {AssetId from})` constructor, which would support absolute `package:` uris as well as relative ones if `from` is provided.

**Comment by natebosch** [comment]
At one point I had a change that added the concept of a 'canonical' Uri. With that solution this use case would have looked like:

```dart
var canonicalUri = normalize(directiveUri, from: buildStep.inputId.asUri);
var assetId = new AssetId.fromUri(canonicalUri);
```

**Comment by matanlurey** [comment]
On a related note, I forgot to add `lib/` when doing this manually.

Hopefully `new AssetId.from` or whatever we come up with handles this for me. Easy to get wrong.
