### ISSUE TITLE
Null value error when trying to build and serve simple project

### ISSUE THREAD

**Issue by advonesix** [dart-lang/build#1921]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* [ ] Dart SDK Version (`dart --version`)
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"

* [ ] What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
$ cat pubspec.lock | grep build_runner -n3
120-      url: "https://pub.dartlang.org"
121-    source: hosted
122-    version: "0.2.2+7"
123:  build_runner:
124-    dependency: "direct dev"
125-    description:
126:      name: build_runner
127-      url: "https://pub.dartlang.org"
128-    source: hosted
129-    version: "1.1.2"
130:  build_runner_core:
131-    dependency: transitive
132-    description:
133:      name: build_runner_core
134-      url: "https://pub.dartlang.org"
135-    source: hosted
136-    version: "1.1.1"

* [ ] What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
none.
* [ ] Whether you are using Windows, MacOSX, or Linux (if applicable)
win10 x64
* [ ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
n/a
* [ ] Any other packages or constraints we should know about
$ cat pubspec.yaml
name: hics
description: A web app that uses AngularDart Components
 version: 1.0.0
 homepage: https://www.example.com
 author: Me<email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+20

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1

Missing some or all of the above might make the issue take longer or be impossible to act on.

I keep trying to build/serve and get this message which tells me to post here.

DESKTOP-LNRIKU5 MINGW64 /c/programming/projects/web/hics
$ webdev serve
Creating build script, took 8440ms
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 13ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 126ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 527ms

[INFO] Reading cached asset graph completed, took 1.2s

[INFO] Checking for updates since last build...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

NoSuchMethodError: The getter 'lastKnownDigest' was called on null.
Receiver: null
Tried calling: lastKnownDigest
dart:core                                                            Object.noSuchMethod
package:build_runner_core/src/generate/build_definition.dart 377:42  _Loader._computeBuilderOptionsUpdates.updateBuilderOptionsNode
package:build_runner_core/src/generate/build_definition.dart 387:33  _Loader._computeBuilderOptionsUpdates
package:build_runner_core/src/generate/build_definition.dart 290:20  _Loader._updateAssetGraph
package:build_runner_core/src/generate/build_definition.dart 89:17   _Loader.prepareWorkspace.<fn>
package:build_runner_core/src/logging/logging.dart 25:30             logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 86:27   _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_definition.dart 64:50   BuildDefinition.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 105:49        BuildImpl.create
package:build_runner/src/generate/watch_impl.dart 323:34             WatchImpl._run.<fn>
package:build_runner/src/generate/watch_impl.dart 345:6              WatchImpl._run
package:build_runner/src/generate/watch_impl.dart 203:20             new WatchImpl
package:build_runner/src/generate/watch_impl.dart 123:5              _runWatch
package:build_runner/src/generate/watch_impl.dart 86:15              watch
dart:async                                                           _completeOnAsyncReturn
package:build_runner_core/src/generate/options.dart                  BuildOptions.create
dart:async                                                           _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart        TargetGraph.forPackageGraph
dart:async                                                           _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart        _packageBuildConfig
dart:async                                                           _completeOnAsyncReturn
package:build_config/src/build_config.dart                           BuildConfig.fromBuildConfigDir

**Comment by natebosch** [comment]
Looks like we forgot to publish the version of `build_runner_core` that fixed this. That's published now as `1.1.2`,  this should be resolved by a `pub upgrade`.

**Comment by advonesix** [comment]
Thank you. This fixed it.
