### ISSUE TITLE
Build to source and webdev serve

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/build#1940]
* Dart VM version:  2.1.1-dev.0.0 (Wed Dec 19 10:26:42 2018 +0100) on "windows_x64"
* `build_runner 1.1.0+`

After `build_runner` switched to running from snapshots, one specific workflow got broken.

1. Let's say a package needs to build some files to source (i.e., `build_to: source` in `build.yaml`).
2. To perform an initial build, one could invoke something like: 
 `pub run build_runner build --delete-conflicting-outputs --output web:build\web --release`. This command successfully runs and creates needed files:
```
  [INFO] Generating build script...
  [INFO] Generating build script completed, took 278ms

  [INFO] Initializing inputs
  [INFO] Building new asset graph...
  [INFO] Building new asset graph completed, took 1.2s

  [INFO] Checking for unexpected pre-existing outputs....
  [INFO] Deleting 1 declared outputs which already existed on disk.
  [INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

  [INFO] Running build...
```
3. Before `build_runner 1.1.0`, it was possible to use `pub global run webdev serve web:55555` and it worked fine because it was using cached asset graph created on the step 2:
```
Creating build script, took 5098ms
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 10ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 215ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 343ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 391ms

[INFO] Running build...
```
4. After `build_runner 1.1.0`, running `webdev serve` ignores cached asset graph and fails because built source files already exist:
```
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 9ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 217ms

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.4s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Found 1 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
[SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. 
[INFO] Terminating. No further builds will be scheduled
```

**Comment by kevmoo** [comment]
@natebosch – would you take a look?

**Comment by manuscle** [comment]
Hi,
I think I get a similar problem as @lexaknyazev on Webstorm
The workflow is like this: I run tests with pub run build_runner test --fail-on-severe -- -p chrome
Everything working fine, then I run index.html with webstorm, so webstorm run /usr/lib/dart/bin/pub global run webdev serve web:53322
Then I get the same error as above
To avoid this error, I have to run pub global run webdev build --output=web:build, choose to delete conflict, then I can run index.html from webstorm

**Comment by kevmoo** [comment]
What builders are ya'll using that generate things to source?

**Comment by natebosch** [comment]
Does anyone have a concrete repro case where we are ignoring an existing asset graph when we shouldn't?

I think since this was originally filed we've improved the cleanup use case when we invalidate an existing asset graph, and now the known cases where things don't work well are where you are in a fresh checkout and don't have an asset graph at all - those use cases are solved by brining over the `.dart_tool/build` directory with you, but that UX isn't great.

**Comment by lexaknyazev** [comment]
@natebosch 
Here's a complete example.

**Preparation:**
Clone https://github.com/lexaknyazev/build_bug.git and run `pub get`.

**Working workflow**
We have to delete conflicting outputs once when running `webdev build`.
```
> pub global run webdev build
Creating build script, took 5072ms
[INFO] Building new asset graph completed, took 787ms
[INFO] Found 1 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
Delete these files?
1 - Delete
2 - Cancel build
3 - List conflicts
1
[INFO] Checking for unexpected pre-existing outputs. completed, took 2.8s
[INFO] build_web_compilers:entrypoint on web/main.dart:Running dart2js with --minify --packages=.package-43d1052aecb44189a102cac2ff4d54e5 -oweb/main.dart.js web/main.dart
[INFO] build_web_compilers:entrypoint on web/main.dart:Dart2Js finished with:

Compiled 7,381,723 characters Dart to 5,428 characters JavaScript in 0.41 seconds
Dart file (web\main.dart) compiled to JavaScript: web/main.dart.js

[INFO] Running build completed, took 1.3s
[INFO] Caching finalized dependency graph completed, took 114ms
[INFO] Creating merged output dir `build` completed, took 94ms
[INFO] Writing asset manifest completed, took 1ms
[INFO] Succeeded after 1.5s with 11 outputs (1436 actions)
```
Notice, that `webdev serve` doesn't ask about conflicting outputs afterwards.
```
> pub global run webdev serve
Creating build script, took 5040ms
[INFO] Setting up file watchers completed, took 10ms
[INFO] Waiting for all file watchers to be ready completed, took 21ms
[INFO] Reading cached asset graph completed, took 225ms
[INFO] Checking for updates since last build completed, took 379ms
[INFO] Running build completed, took 1.3s
[INFO] Caching finalized dependency graph completed, took 131ms
[INFO] Succeeded after 1.4s with 12 outputs (1433 actions)
Serving `web` on http://localhost:8080
```

**Non-working workflow**
Remove `build` and `.dart_tool/build` first.

Unlike `webdev build`, the following command creates a build script snapshot.
```
> pub run build_runner build --delete-conflicting-outputs --release --output web:build
[INFO] Generating build script completed, took 276ms
[INFO] Creating build script snapshot... completed, took 9.2s
[INFO] Building new asset graph completed, took 930ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 3ms
[INFO] build_web_compilers:entrypoint on web/main.dart:Running dart2js with --minify --packages=.package-43d1052aecb44189a102cac2ff4d54e5 -oweb/main.dart.js web/main.dart
[INFO] build_web_compilers:entrypoint on web/main.dart:Dart2Js finished with:

Compiled 7,381,723 characters Dart to 5,428 characters JavaScript in 0.41 seconds
Dart file (web\main.dart) compiled to JavaScript: web/main.dart.js

[INFO] Running build completed, took 1.3s
[INFO] Caching finalized dependency graph completed, took 113ms
[INFO] Creating merged output dir `build` completed, took 84ms
[INFO] Writing asset manifest completed, took 1ms
[INFO] Succeeded after 1.5s with 11 outputs (1436 actions)
```
Now, `webdev serve` ignores existing build script snapshot and asks about conflicting outputs:
```
> pub global run webdev serve
Creating build script, took 5075ms
[INFO] Setting up file watchers completed, took 9ms
[INFO] Waiting for all file watchers to be ready completed, took 22ms
[INFO] Building new asset graph completed, took 941ms
[INFO] Found 1 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
Delete these files?
1 - Delete
2 - Cancel build
3 - List conflicts
```

**Comment by natebosch** [comment]
Ah, I wonder if its because running from the snapshot vs the source makes it look like it should be using a different asset graph.

@jakemac53 - we either need to normalize the build tool hash between snapshot or not, or we need to migrate `webdev` to always use the snapshot as well.

**Comment by jakemac53** [comment]
Ooohhh ya that makes sense. With the latest webdev this won't be an issue any more, but we probably should update build_runner to somehow recognize its own snapshots at least.

**Comment by Ikxyz** [comment]
@lexaknyazev  When I run the index.html all I get is a blank page with this error in the console
![image](https://user-images.githubusercontent.com/40415727/58689634-734ca980-837f-11e9-98c3-94989e21acb6.png)

**Comment by jakemac53** [comment]
@Ikxyz  It looks like you are trying to load the resources using a file: uri instead of using the webdev server.

**Comment by Ikxyz** [comment]
@jakemac53  How do i go about getting the static index.html and js for deployment
Thanks

**Comment by jakemac53** [comment]
You can use the --output option, which accepts a directory to output to. So for instance `--output build` would deploy to the `build` directory.

Note that this would still be a debug build if you are not also passing `--release`.

In webdev the `build` command would also automatically enable release mode and I believe it will default to the `build` output directory as well.

**Comment by Ikxyz** [comment]
@jakemac53  Thanks
