### ISSUE TITLE
NoSuchMethodError: The getter 'address' was called on null.

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/build#1941]
I am trying to get Angular running on Chrome OS however I am difficulty connecting to the linux container from Chrome OS so I attempted to use the --hostname arg however I get the following error:

```
pub run build_runner serve web:6969 --hostname penguin.linux.test
[INFO] Generating build script completed, took 519ms


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


NoSuchMethodError: The getter 'address' was called on null.
Receiver: null
Tried calling: address
dart:core                                             Object.noSuchMethod
package:build_runner/src/entrypoint/serve.dart 68:49  ServeCommand.run
package:args/command_runner.dart 196:27               CommandRunner.runCommand
package:args/command_runner.dart 111:29               CommandRunner.run.<fn>
dart:async                                            new Future.sync
package:args/command_runner.dart 111:11               CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31    run
.dart_tool/build/entrypoint/build.dart 129:22         main
```

**Comment by jimmyff** [comment]
Hey @natebosch I've tried with different ports but everytime I get the same error. If I don't specify a hostname it builds and serves but I can't connect to it from http://penguin.linux.test (as i don't think it's listening on 0.0.0.0).

My temporary working solution is to do a build_runner watch (and output to  build/). Then use python SimpleHTTPServer to serve that directory as that listens on 0.0.0.0.

**Comment by natebosch** [comment]
> If I don't specify a hostname it builds and serves but I can't connect to it from http://penguin.linux.test (as i don't think it's listening on 0.0.0.0).

You  could try passing `any` for the hostname. We treat that name specially and will listen on `0.0.0.0`.

**Comment by jodinathan** [comment]
I've stumbled upon this error when I switched machines and my problem was that the hostname that I use, "local.guara.ci", was not registered within my /etc/hosts.
It took me a while to figure it out that it wasn't a build_runner version problem so I guess the error message could be improved.
