### ISSUE TITLE
Add file polling flag for `build_runner serve`

### ISSUE THREAD

**Issue by lebenasa** [dart-lang/build#1943]
(Not sure if this should be in `webdev` or in `build_runner`.)

`webdev serve` doesn't rebuild at all on file change when running inside VM (in my case via vagrant). I reckon it's because the trigger depends on filesystem signal? If that's the case would be nice if it has file polling flag like `webpack`'s `--watch-poll`.

**Comment by kevmoo** [comment]
@jakemac53 @natebosch ?

**Comment by lebenasa** [comment]
Hi, happy new year by the way.

Tried it on regular hashicorp/precise64 guest in MacOS host, the `vagrant-fsnotify` solution is indeed working well. In my opinion it's a better solution than doing long polling, but on the other hand would  trip beginners working in VM (doing this for colleagues working in Windows machines...). It's just a small feature parity gap to `webpack`.

I think file polling would fall under nice to have feature?

**Comment by jakemac53** [comment]
We do have a `--use-polling-watcher` flag now - which should hopefully resolve this issue.
