### ISSUE TITLE
We should give a nice error if using the flutter sdk with build_web_compilers

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1946]
Today if you are using the flutter sdk and try to run a web app with build_web_compilers it will fail with some very noisy and not very helpful errors (because ddc/dart2js don't ship with it).

We should try to recognize this situation and give a nice error.

**Comment by natebosch** [comment]
Maybe we should revisit the environment checks idea?

https://github.com/dart-lang/build/issues/961

**Comment by jakemac53** [comment]
Yep that would probably be the cleanest way of resolving it

**Comment by jakemac53** [comment]
ddc/dart2js do ship with the flutter sdk now, I think this should actually work
