### ISSUE TITLE
build_runner 1.1.2 crashes with message "You have hit a bug in build_runner"

### ISSUE THREAD

**Issue by denis-beurive** [dart-lang/build#1948]
I have hit the error message below:

    [INFO] Running build completed, took 825ms
    [INFO] Caching finalized dependency graph completed, took 220ms
    [INFO] Succeeded after 1.1s with 4 outputs (7 actions)

    You have hit a bug in build_runner
    Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

    AssetNotFoundException: myapp|web/main.ddc.js.errors
    package:build_runner/src/server/server.dart 220:20  BuildUpdatesWebSocketHandler.emitUpdateMessage
    package:build_runner/src/server/server.dart 72:25   new ServeHandler._.<fn>

Thus, I report the bug as required. I use `build_runner V1.1.2` (the last version, as far as I know).

However, I can't reproduce it. I was editing my code on a desktop window while "buil_runner" was running on another window. I did not see the exact moment when the error was reported. Thus I cannot tell what's produced it.

I'll try to "come back in the code"... however I cannot promise I'll find out.

You will find the information you ask below:

* [ ] Dart SDK Version: `Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"`
* [ ] What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`):

    packages:
      analyzer:
        dependency: transitive
        description:
          name: analyzer
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.34.1"
      angular:
        dependency: "direct main"
        description:
          name: angular
          url: "https://pub.dartlang.org"
        source: hosted
        version: "5.2.0"
      angular_ast:
        dependency: transitive
        description:
          name: angular_ast
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.5.8"
      angular_compiler:
        dependency: transitive
        description:
          name: angular_compiler
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.4.2"
      angular_test:
        dependency: "direct dev"
        description:
          name: angular_test
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.2.0"
      archive:
        dependency: transitive
        description:
          name: archive
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.5"
      args:
        dependency: transitive
        description:
          name: args
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.5.1"
      async:
        dependency: transitive
        description:
          name: async
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.8"
      bazel_worker:
        dependency: transitive
        description:
          name: bazel_worker
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.1.15"
      boolean_selector:
        dependency: transitive
        description:
          name: boolean_selector
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.4"
      build:
        dependency: transitive
        description:
          name: build
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.2"
      build_config:
        dependency: transitive
        description:
          name: build_config
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.3.1+4"
      build_modules:
        dependency: transitive
        description:
          name: build_modules
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.3"
      build_resolvers:
        dependency: transitive
        description:
          name: build_resolvers
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.2.2+7"
      build_runner:
        dependency: "direct dev"
        description:
          name: build_runner
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.1.2"
      build_runner_core:
        dependency: transitive
        description:
          name: build_runner_core
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.1.2"
      build_test:
        dependency: "direct dev"
        description:
          name: build_test
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.10.4"
      build_web_compilers:
        dependency: "direct dev"
        description:
          name: build_web_compilers
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.4.4+3"
      built_collection:
        dependency: transitive
        description:
          name: built_collection
          url: "https://pub.dartlang.org"
        source: hosted
        version: "4.1.0"
      built_value:
        dependency: transitive
        description:
          name: built_value
          url: "https://pub.dartlang.org"
        source: hosted
        version: "6.2.0"
      charcode:
        dependency: transitive
        description:
          name: charcode
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.1.2"
      code_builder:
        dependency: transitive
        description:
          name: code_builder
          url: "https://pub.dartlang.org"
        source: hosted
        version: "3.1.3"
      collection:
        dependency: transitive
        description:
          name: collection
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.14.11"
      convert:
        dependency: transitive
        description:
          name: convert
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.1.1"
      crypto:
        dependency: transitive
        description:
          name: crypto
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.6"
      csslib:
        dependency: transitive
        description:
          name: csslib
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.14.6"
      dart_style:
        dependency: transitive
        description:
          name: dart_style
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.2.2"
      fixnum:
        dependency: transitive
        description:
          name: fixnum
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.10.9"
      front_end:
        dependency: transitive
        description:
          name: front_end
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.1.8"
      glob:
        dependency: transitive
        description:
          name: glob
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.1.7"
      graphs:
        dependency: transitive
        description:
          name: graphs
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.1.3+1"
      html:
        dependency: transitive
        description:
          name: html
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.13.3+3"
      http:
        dependency: transitive
        description:
          name: http
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.12.0"
      http_multi_server:
        dependency: transitive
        description:
          name: http_multi_server
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.5"
      http_parser:
        dependency: transitive
        description:
          name: http_parser
          url: "https://pub.dartlang.org"
        source: hosted
        version: "3.1.3"
      intl:
        dependency: transitive
        description:
          name: intl
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.15.7"
      io:
        dependency: transitive
        description:
          name: io
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.3.3"
      js:
        dependency: transitive
        description:
          name: js
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.6.1+1"
      json_annotation:
        dependency: transitive
        description:
          name: json_annotation
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.0"
      json_rpc_2:
        dependency: transitive
        description:
          name: json_rpc_2
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.9"
      kernel:
        dependency: transitive
        description:
          name: kernel
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.3.8"
      logging:
        dependency: transitive
        description:
          name: logging
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.11.3+2"
      matcher:
        dependency: transitive
        description:
          name: matcher
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.12.3+1"
      meta:
        dependency: transitive
        description:
          name: meta
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.1.6"
      mime:
        dependency: transitive
        description:
          name: mime
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.9.6+2"
      multi_server_socket:
        dependency: transitive
        description:
          name: multi_server_socket
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.2"
      node_preamble:
        dependency: transitive
        description:
          name: node_preamble
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.4.4"
      package_config:
        dependency: transitive
        description:
          name: package_config
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.5"
      package_resolver:
        dependency: transitive
        description:
          name: package_resolver
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.6"
      pageloader:
        dependency: "direct dev"
        description:
          name: pageloader
          url: "https://pub.dartlang.org"
        source: hosted
        version: "3.0.3"
      path:
        dependency: transitive
        description:
          name: path
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.6.2"
      pedantic:
        dependency: transitive
        description:
          name: pedantic
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.4.0"
      plugin:
        dependency: transitive
        description:
          name: plugin
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.2.0+3"
      pool:
        dependency: transitive
        description:
          name: pool
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.3.6"
      protobuf:
        dependency: transitive
        description:
          name: protobuf
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.10.5"
      pub_semver:
        dependency: transitive
        description:
          name: pub_semver
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.4.2"
      pubspec_parse:
        dependency: transitive
        description:
          name: pubspec_parse
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.1.3"
      quiver:
        dependency: transitive
        description:
          name: quiver
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.1"
      scratch_space:
        dependency: transitive
        description:
          name: scratch_space
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.0.3+2"
      shelf:
        dependency: transitive
        description:
          name: shelf
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.7.4"
      shelf_packages_handler:
        dependency: transitive
        description:
          name: shelf_packages_handler
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.4"
      shelf_static:
        dependency: transitive
        description:
          name: shelf_static
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.2.8"
      shelf_web_socket:
        dependency: transitive
        description:
          name: shelf_web_socket
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.2.2+4"
      source_gen:
        dependency: transitive
        description:
          name: source_gen
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.9.3"
      source_map_stack_trace:
        dependency: transitive
        description:
          name: source_map_stack_trace
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.1.5"
      source_maps:
        dependency: transitive
        description:
          name: source_maps
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.10.8"
      source_span:
        dependency: transitive
        description:
          name: source_span
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.4.1"
      stack_trace:
        dependency: transitive
        description:
          name: stack_trace
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.9.3"
      stream_channel:
        dependency: transitive
        description:
          name: stream_channel
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.6.8"
      stream_transform:
        dependency: transitive
        description:
          name: stream_transform
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.0.14+1"
      string_scanner:
        dependency: transitive
        description:
          name: string_scanner
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.4"
      sync_http:
        dependency: transitive
        description:
          name: sync_http
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.1.3"
      term_glyph:
        dependency: transitive
        description:
          name: term_glyph
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.1"
      test:
        dependency: "direct dev"
        description:
          name: test
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.5.1+1"
      test_api:
        dependency: transitive
        description:
          name: test_api
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.2.1"
      test_core:
        dependency: transitive
        description:
          name: test_core
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.2.0+1"
      timing:
        dependency: transitive
        description:
          name: timing
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.1.1+1"
      typed_data:
        dependency: transitive
        description:
          name: typed_data
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.1.6"
      utf:
        dependency: transitive
        description:
          name: utf
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.9.0+5"
      vm_service_client:
        dependency: transitive
        description:
          name: vm_service_client
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.2.6"
      watcher:
        dependency: transitive
        description:
          name: watcher
          url: "https://pub.dartlang.org"
        source: hosted
        version: "0.9.7+10"
      web_socket_channel:
        dependency: transitive
        description:
          name: web_socket_channel
          url: "https://pub.dartlang.org"
        source: hosted
        version: "1.0.9"
      webdriver:
        dependency: transitive
        description:
          name: webdriver
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.0.0"
      yaml:
        dependency: transitive
        description:
          name: yaml
          url: "https://pub.dartlang.org"
        source: hosted
        version: "2.1.15"
    sdks:
      dart: ">=2.1.0-dev.5.0 <3.0.0"

* [ ] Whether you are using Windows, MacOSX, or Linux; Linux
* [ ] Whether you are using Chrome, Safari, Firefox, Edge: Chrome

**Comment by jakemac53** [comment]
I think this was probably a race condition where the next build started (and succeeded) before this request finished.

This shouldn't cause any real world issues but we can leave it open - we could wrap this in a try/catch or something to detect this scenario and silence it.

**Comment by jakemac53** [comment]
I am going to close this as we haven't seen further reports
