### ISSUE TITLE
Is the docs out of day "build/docs/transforming_code.md"?

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/build#1958]
Dart version: 2.1.0

We follow [this guide](https://github.com/dart-lang/build/blob/master/docs/transforming_code.md) to upgrade our old dart 1 transformers code, but it gets an error `The generative constructor 'Calculator() → Calculator' expected, but factory found.`

```
part of 'calculator.dart';

abstract class _$Calculator extends Calculator { //  <- error: The generative constructor 'Calculator() → Calculator' expected, but factory found.
  int _memoize1;

  @override
  int doExpensiveCalculation() => _memoize1 ??= super.doExpensiveCalculation();
}
```

Any idea?

**Comment by jakemac53** [comment]
I don't think the docs were ever correct actually, there needs to be actual private constructors on both of the classes afaik for it to work.

**Comment by jumperchen** [comment]
Okay, thanks for the quick fix. :)
