### ISSUE TITLE
Why build does not accept input at root folder ?

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/build#197]
I have a package that need a config file (ex: config.yaml) directly on my root folder.

```
-> ./config.yaml
-> ./lib/..
-> ./bin/..
...
```

I am generating code from that file, but `build` does not accept that input, why ?

I know it is a choice by looking at the code
https://github.com/dart-lang/build/blob/0b4f98e568399af8df3d4d7d32100b87d26e517a/build_runner/lib/src/generate/build_impl.dart#L501

**Comment by jakemac53** [comment]
I can't think of a reason not to allow this, what error did you get?

**Comment by jakemac53** [comment]
Oh nvm I see in the code you linked it just treats them as invalid inputs, I would be fine personally with removing that restriction.

**Comment by lejard-h** [comment]
I would be fine too :)
No error, my file is just not treated.
I can do a pull request, the change is pretty simple
