### ISSUE TITLE
Documentation missing for 0.7.0

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/build#199]
pub.dartlang.org docs link is to: https://www.dartdocs.org/documentation/build/0.7.0/ which is 404ing.

**Comment by natebosch** [comment]
@kevmoo do you know if we can poke dartdocs to generate for the newer package version?

**Comment by kevmoo** [comment]
https://www.dartdocs.org/documentation/build/0.7.0/log.txt

I need to send a request to get this rebuilt.

**Comment by kevmoo** [comment]
Done - https://github.com/dart-lang/dartdoc/issues/1342

**Comment by kevmoo** [comment]
Er, https://github.com/astashov/dartdocs.org/issues/40
