### ISSUE TITLE
Missing "part 'todo.g.dart';" error

### ISSUE THREAD

**Issue by twistedinferno** [dart-lang/build#1990]
Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"
build_runner-1.1.3
Flutter (Channel master, v1.1.10-pre.155, on Linux, locale en_US.UTF-8)

Hi, I'm trying to get the example in the tutorial and project below
https://medium.com/flutter-community/part-2-code-generation-in-dart-annotations-source-gen-and-build-runner-bbceee28697b
https://github.com/jorgecoca/todo_reporter.dart

I get the following error
Missing "part 'second_todo.g.dart';".
when I run flutter packages pub run build_runner build

I've tried updating my packages, different versions of the packages too.

To recreate the problem you might have to make a change to the todo.dart file in the example folder.

Any ideas?

**Comment by kevmoo** [comment]
@jakemac53 @natebosch ?

**Comment by natebosch** [comment]
This file: https://github.com/jorgecoca/todo_reporter.dart/blob/2817607ae96fb38408849c603dda9c1e234bdd3a/example/lib/second_todo.dart

Needs to have, following the imports, the line `part 'second_todo.g.dart';`. Without it the [`part of` statement here](https://github.com/jorgecoca/todo_reporter.dart/blob/2817607ae96fb38408849c603dda9c1e234bdd3a/example/lib/second_todo.g.dart#L3) doesn't work.

**Comment by twistedinferno** [comment]
Ah, that's great.  Many thanks Nate and Kevmo

**Comment by jmewes** [comment]
I came across this issue because i used `part './payload.g.dart';` instead of `part 'payload.g.dart';`. Removing `./` solved my problem.

**Comment by natebosch** [comment]
FYI we recently improved the messaging for this. On the latest source_gen the steps to resolve this should hopefully be more clear.

```
second_todo.g.dart must be included as a part directive in the input library with:
    part 'second_todo.g.dart';
```
