### ISSUE TITLE
Should dev_dependencies be included in build output?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/build#1993]
I'm not sure if this is expected, but seems strange to me. Pubspec lists packages like `test` and `pedantic` under `dev_dependencies` but when running `webdev build --no-build-web-compilers -r` the output `build/packages` folder seems to contain resources for those packages (it also includes folders for build_web_compilers folder, node_preamble, build_runner that seem unnecessary).

I don't know that they'd cause any issues, but if they're unnecessarily being compiled to JS then maybe there are perf gains by skipping them.

**Comment by kevmoo** [comment]
@jakemac53 @natebosch – there are reasons here, but I'm not the best one to articulate them

**Comment by natebosch** [comment]
> if they're unnecessarily being compiled to JS then maybe there are perf gains by skipping them.

Nothing will be compiled to JS unless you import it, so no major perf problem there. What you are seeing is files that are published in those packages that we were unable to cleanup.

> I'm not sure if this is expected

Somewhat expected yes. We can't know for sure some of those things aren't use by, for example, test code that does get compiled and run. The biggest negative impact is thing trying to only build the `web` directory and using `--output`, but then seeing unnecessary stuff get copied over. Doing automatic output cleanup on release builds is something that is really tricky - we're doing OK I think given the constraints but it's an area we might want to revisit if we have bandwidth.

**Comment by jakemac53** [comment]
Right, we can't distinguish between dev dependencies and regular dependencies here. For instance the `test` package is imported by test code usually, and does ultimately need to get compiled to JS.

As Nate said we won't compile to JS anything which isn't imported though, due to the lazy nature of how we do builds.

**Comment by DanTup** [comment]
> What you are seeing is files that are published in those packages that we were unable to cleanup.

Aha, that explains that :-)

Thanks for the info!
