### ISSUE TITLE
Failed to precompile build_runner:build_runner:

### ISSUE THREAD

**Issue by MonsterKris** [dart-lang/build#1995]
Failed to precompile build_runner:build_runner:
Crash when compiling package:build_config/src/builder_definition.dart,
at character offset null:
Bad state: No element
#0      List.first (dart:core/runtime/libgrowable_array.dart:215:5)
#1      BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:547:28)
#2      DietListener.listenerFinishFields (package:front_end/src/fasta/source/diet_listener.dart:804:14)
#3      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:847:5)
#4      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:654:5)
#5      DietListener.endFields (package:front_end/src/fasta/source/diet_listener.dart:284:5)
#6      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2251:16)
#7      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2910:15)
#8      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2700:15)
#9      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1710:13)
#10     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1670:14)
#11     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:565:14)
#12     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:457:14)
#13     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#14     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:253:14)
<asynchronous suspension>
#15     Loader.buildBodies (package:front_end/src/fasta/loader.dart:181:15)
<asynchronous suspension>
#16     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#18     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
<asynchronous suspension>
#19     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:145:38)
<asynchronous suspension>
#20     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#21     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>
#22     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:40:18)
<asynchronous suspension>
#23     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:132:20)
<asynchronous suspension>
#24     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#32     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:130:10)
#33     generateKernel (package:front_end/src/kernel_generator_impl.dart:39:32)
<asynchronous suspension>
#34     kernelForComponent (package:front_end/src/api_prototype/kernel_generator.dart:83:17)
<asynchronous suspension>
#35     SingleShotCompilerWrapper.compileInternal (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/vm/bin/kernel_service.dart:179:11)
<asynchronous suspension>
#36     Compiler.compile.<anonymous closure> (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/vm/bin/kernel_service.dart:121:31)
<asynchronous suspension>
#37     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#38     _rootRun (dart:async/zone.dart:1120:38)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#45     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#46     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#47     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#48     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by jakemac53** [comment]
Hmm, is this reproducible or did it just happen once? It seems like a possible kernel bug.

**Comment by jakemac53** [comment]
closing this for now, assuming it is stale. please respond with more info if it is still a problem

**Comment by softmarshmallow** [comment]
having this issue. pub upgrade does not work for me

**Comment by natebosch** [comment]
@softmarshmallow can you attach the output from `pub deps`?

What is the specific command you are running to see this stack trace?
