### ISSUE TITLE
Roll out the migration to AnalysisDriver to external users

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1998]
# Background

We need to get all builder packages migrated to use AnalysisDriver externally. There are breaking behavior changes in the `LibraryElement` instances that are returned. Packages don't generally have a dependency on `build_resolvers` where the implementation is changing.

#1983 has the code changes, but needs a bit of work on versioning to get it submitted.

# Options

## Breaking change in `package:build`

We could bump the version of `build` to `2.0.0` as an indication that _all_ resolvers (only 1 implementation externally) will now vend elements produced by the analysis driver. The migrated `build_resolvers` will only work with `2.0.0` so pub will never give a new resolver to a builder expecting to use the old code patterns.

## Breaking change in `package:analyzer`

All packages impacted by this should have a dependency on both `build` and `analyzer`. We publish a new version of `analyzer` which may or may not drop the task model, but critically will be used as a marker to indicate that when used through the build system will have the new behavior. `build_resolvers` will use a minimum constraint at that version, so only packages which increase their upper bound will get the new resolver implementation.

The nice thing about this approach is that to the builder authors this is a closer match to what is breaking - they see `LibraryElement` instances behaving differently. The fact that they behave differently because they were fetched differently from some class deep in the build system is an implementation detail.

**Comment by stereotype441** [comment]
(Capturing some IM discussion I had with @natebosch)

We (the analyzer team) are in the middle of preparing a breaking change release of the analyzer now (version 0.35.0).  That will be the first version of the analyzer that drops support for the task model (and explicitly prohibits its use by throwing an exception).  So if you want, you could switch over to driver in the same release as you switch over to 0.35.0.

**Comment by jakemac53** [comment]
I like the approach of doing this using the analyzer breaking version. It should mean less churn for builder authors, they would already have to bump their analyzer version anyways. Builders that don't use the analyzer won't be affected.

**Comment by stereotype441** [comment]
Analyzer 0.35.0 is now published to pub

**Comment by jakemac53** [comment]
This is done! Long live AnalysisDriver!
