### ISSUE TITLE
You have hit a bug in build_runner Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues   FormatException: Unexpected end of input (at character 1)  ^  dart:convert                                                                                                                           JsonCodec.decode

### ISSUE THREAD

**Issue by corbaz** [dart-lang/build#2026]
TC:\laragon\www\weda>webdev serve
Creating build script, took 22055ms
[INFO] Setting up file watchers completed, took 53ms
[INFO] Waiting for all file watchers to be ready completed, took 59ms
[INFO] Reading cached asset graph...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

FormatException: Unexpected end of input (at character 1)

^

dart:convert                                                                                                                           JsonCodec.decode
C:\Users\lacas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\build_runner_core-2.0.2\lib\src\asset_graph\serialization.dart 20:33  new _AssetGraphDeserializer
package:build_runner_core/src/asset_graph/graph.dart 42:7                                                                              new AssetGraph.deserialize
package:build_runner_core/src/generate/build_definition.dart 215:38                                                                    _Loader._tryReadCachedAssetGraph.<fn>
package:build_runner_core/src/logging/logging.dart 25:30                                                                               logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 213:12                                                                    _Loader._tryReadCachedAssetGraph
package:build_runner_core/src/generate/build_definition.dart 79:28                                                                     _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_definition.dart 64:50                                                                     BuildDefinition.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 112:49                                                                          BuildImpl.create
package:build_runner/src/generate/watch_impl.dart 310:34                                                                               WatchImpl._run.<fn>
package:build_runner/src/generate/watch_impl.dart 332:6                                                                                WatchImpl._run
package:build_runner/src/generate/watch_impl.dart 182:20                                                                               new WatchImpl
package:build_runner/src/generate/watch_impl.dart 124:5                                                                                _runWatch
package:build_runner/src/generate/watch_impl.dart 85:15                                                                                watch
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_runner_core/src/generate/options.dart                                                                                    BuildOptions.create
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart                                                                          TargetGraph.forPackageGraph
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart                                                                          _packageBuildConfig
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_config/src/build_config.dart                                                                                             BuildConfig.fromBuildConfigDir

C:\laragon\www\weda>webdev serve
Creating build script, took 20768ms
[INFO] Setting up file watchers completed, took 52ms
[INFO] Waiting for all file watchers to be ready completed, took 67ms
[INFO] Reading cached asset graph...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

FormatException: Unexpected end of input (at character 1)

^

dart:convert                                                                                                                           JsonCodec.decode
C:\Users\lacas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\build_runner_core-2.0.2\lib\src\asset_graph\serialization.dart 20:33  new _AssetGraphDeserializer
package:build_runner_core/src/asset_graph/graph.dart 42:7                                                                              new AssetGraph.deserialize
package:build_runner_core/src/generate/build_definition.dart 215:38                                                                    _Loader._tryReadCachedAssetGraph.<fn>
package:build_runner_core/src/logging/logging.dart 25:30                                                                               logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 213:12                                                                    _Loader._tryReadCachedAssetGraph
package:build_runner_core/src/generate/build_definition.dart 79:28                                                                     _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_definition.dart 64:50                                                                     BuildDefinition.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 112:49                                                                          BuildImpl.create
package:build_runner/src/generate/watch_impl.dart 310:34                                                                               WatchImpl._run.<fn>
package:build_runner/src/generate/watch_impl.dart 332:6                                                                                WatchImpl._run
package:build_runner/src/generate/watch_impl.dart 182:20                                                                               new WatchImpl
package:build_runner/src/generate/watch_impl.dart 124:5                                                                                _runWatch
package:build_runner/src/generate/watch_impl.dart 85:15                                                                                watch
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_runner_core/src/generate/options.dart                                                                                    BuildOptions.create
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart                                                                          TargetGraph.forPackageGraph
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart                                                                          _packageBuildConfig
dart:async                                                                                                                             _completeOnAsyncReturn
package:build_config/src/build_config.dart                                                                                             BuildConfig.fromBuildConfigDir

**Comment by jakemac53** [comment]
It sounds like you probably killed a build in the middle of serializing the asset graph to disk, so it didn't finish and has a malformed asset graph now.

I would try a `pub run build_runner clean` and if that doesn't work a `rm -rf .dart_tool/`.
