### ISSUE TITLE
BuildStep.findAssets does not pickup new assets

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#2036]
For example:

```dart
  @override
  build(buildStep) async {
    final textFiles = buildStep.findAssets(Glob('lib/src/text/**.txt'));
    // ...
  }
```

If I _change_ a file (i.e. `lib/src/text/a.txt`), the builder will execute again.
If I _add_ a file, (i.e. add `lib/src/text/b.txt`), it will not.

Is that intended? Using `pub run build_runner clean` is a (bad) workaround for now.

**Comment by jakemac53** [comment]
This is definitely intended to work

**Comment by jakemac53** [comment]
There is a test that is at least trying to validate this behavior https://github.com/dart-lang/build/blob/master/build_runner_core/test/asset_graph/graph_test.dart#L346, it might be flawed somehow though.

**Comment by matanlurey** [comment]
Thanks. I'll see if I can create a minimal reproduction.

**Comment by natebosch** [comment]
I haven't heard continued reports of this and we've fixed some other bugs around invalidation so I'm guessing this is no longer a problem.
