### ISSUE TITLE
Native extension support

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2047]
For now we just ignore any dart-ext imports (well, after https://github.com/dart-lang/build/pull/2046).

At least for kernel compilation on the vm though we will probably have to do something explicit to make these work.

If this is a blocker for you please comment on this issue, it is low priority until we have customers for it.

**Comment by natebosch** [comment]
We might run in to problems with https://github.com/dart-lang/sdk/issues/35292

**Comment by jakemac53** [comment]
> We might run in to problems with [dart-lang/sdk#35292](https://github.com/dart-lang/sdk/issues/35292)

Right, I don't even know how this is _intended_ to work with modular compilation, so there would be a lot of investigation involved and probably some work in the sdk to support it.
