### ISSUE TITLE
NoSuchMethodError: The method '>=' was called on null

### ISSUE THREAD

**Issue by ian128** [dart-lang/build#2059]
I'm following Get Started section 
[https://webdev.dartlang.org/guides/get-started](url) 
to testing out (webdev serve) my Dart on Web installation. Well it says, 

`You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

NoSuchMethodError: The method '>=' was called on null.

Receiver: null

Tried calling: >=(Instance of 'Version')
dart:core                                             Object.noSuchMethod

package:build_runner/src/entrypoint/test.dart 143:26   _packageTestSupportsSymlinks

package:build_runner/src/entrypoint/test.dart 26:15    new TestCommand

package:build_runner/src/entrypoint/runner.dart 30:16  new BuildCommandRunner

package:build_runner/src/entrypoint/run.dart 21:16     run

.dart_tool/build/entrypoint/build.dart 90:22           main`

Dart 2.1.0, on MacOs_x64 (10.13.6)

**Comment by natebosch** [comment]
I'm not sure how you'd execute something from the `test` command by running `webdev serve`...

**Comment by natebosch** [comment]
Ah, because we execute that code when it's constructed.

@kevmoo - do you know why we'd get a null `pubspec.version`  after parsing?

https://github.com/dart-lang/build/blob/59265c66ffda3820f752cdd8d5fafebb87a9cc1c/build_runner/lib/src/entrypoint/test.dart#L143

**Comment by kevmoo** [comment]
There is no `version` defined in the pubspec? Version is only required if you're publishing.

**Comment by natebosch** [comment]
@ian128 - do you have a package named `test` in your dependencies which is _not_ the one coming from pub?

**Comment by ian128** [comment]
@natebosch nope
![image](https://user-images.githubusercontent.com/39366247/53376282-61c6c080-3990-11e9-888e-25b29f72ff47.png)

**Comment by natebosch** [comment]
Ah, this is because you've named _your_ package `test` 😄 

Should be easy to fix.

**Comment by ian128** [comment]
@natebosch Thanks! 
![image](https://user-images.githubusercontent.com/39366247/53378592-b9692a00-3998-11e9-93f3-a4b33acccee1.png)
