### ISSUE TITLE
I want an internal package builder to not run in downstream package builds

### ISSUE THREAD

**Issue by corwinsheahan-wf** [dart-lang/build#2062]
Hi there!

We've got a package (call it package `upstream_package`) which has a builder internal to that package which generates some helper files to run tests on sauce labs. This builder is not intended for use by downstream dependents, nor are the build outputs required for downstream dependents to consume `upstream_package`. 

We'd like to not run this builder at all when dependents of `upstream_package` run builds in their packages. The builder's config has `auto_apply` set to `none`, and the default target in `upstream_package` enables the builder. While this prevents the builder from running on any downstream deps, the builder will still run on `upstream_package` when a build is run in the downstream package. 

It looks like this might be possible by specifying a separate build target, based on [this paragraph](https://github.com/dart-lang/build/tree/master/build_config#dividing-a-package-into-build-targets), but I'm only inferring and guessing here. However, it seems that the intention for targets is to split files into subsets, rather than split out builders. Is there any way to specify a builder to never run in `upstream_package` if the origination of the build is from a consuming package?

**Comment by jakemac53** [comment]
We don't have direct support for this today, but note that if the builder inputs are only from the `test` directory then it won't actually run on any files anyways, although it will still exist as a phase in the build. 

There is one other feature we do support, which is the `--config=<name>` argument. That will change which build.yaml file is loaded, to instead load `build.<name>.yaml` from your package.

So, you could create a `build.saucelabs.yaml` file, and always run your CI builds with `--config=saucelabs`.

**Comment by corwinsheahan-wf** [comment]
@jakemac53 The separate config file will likely work great for our purposes! Thank you!

**Comment by natebosch** [comment]
Another solution would be to create a new package `upstream_package_builder` with the builder implementation and `build.yaml` file. Use `apply_to: dependents`. Make this package a `dev_dependency` of `upstream_package`.

The builder will only be involved in builds is when the root package is `upstream_package` and the `pub get` pulls it in, otherwise it will not show up at all.

**Comment by jakemac53** [comment]
Closing this for now as I think we have some existing solutions that are good enough for this purpose.
