### ISSUE TITLE
`build_web_compilers` should warn when it sees an import to `dart:io`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2076]
I had thought we already did this...

If I have a transitive import from `web/main.dart` to `dart:io` I should get a warning. Today things will only fail at runtime.

**Comment by jakemac53** [comment]
This is obsolete now, we will refuse to compile the entrypoints at all

**Comment by natebosch** [comment]
Does it work if the import is in main.dart directly?

**Comment by jakemac53** [comment]
Yes it looks like it
