### ISSUE TITLE
AssetId.resolve should support more than package: URLs

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#208]

**Comment by matanlurey** [comment]
I don't remember what the basis for this issue was. Do we still want to keep it?

@jakemac53 @natebosch

**Comment by jakemac53** [comment]
We want to support relative uris, specifically for assets that don't live under `lib` that is the only option. See this throw https://github.com/dart-lang/build/blob/2a2b70f2ff6b3dfde51e7ede6f7c2e3117bc8d1a/build/lib/src/asset/id.dart#L64.

**Comment by natebosch** [comment]
I think we already handle relative paths if you pass a `from` asset.

**Comment by matanlurey** [comment]
I think you are right @natebosch - I think this was opened specifically for that feature.

**Comment by jakemac53** [comment]
Ah yep I missed the actual support there, closing.
