### ISSUE TITLE
DDC bootstrap cannot run on IE11 browser

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/build#2083]
Dart version: 2.1.0

IE11 got undefined with this code `new Error().stack` from https://github.com/dart-lang/build/blob/756ffe1a20ad323286b31d2c485c6a9496ac3f75/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L214

**Comment by jakemac53** [comment]
DDC does not support IE11, and support will be deprecated in dart2js as well before long.

cc @kevmoo I don't know if you have any announcement links for this?

**Comment by jumperchen** [comment]
okay, I found the link here - https://webdev.dartlang.org/faq#q-what-browsers-do-you-support-as-javascript-compilation-targets
