### ISSUE TITLE
build_resolvers pkg has deprecation error on travis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#2087]
https://travis-ci.org/dart-lang/build/jobs/507016382

```
TASK: dartanalyzer
dartanalyzer --fatal-infos --fatal-warnings .
Analyzing build_resolvers...
  hint • 'processRequiredPlugins' is deprecated and shouldn't be used at lib/src/analysis_driver.dart:29:27 • deprecated_member_use
1 hint found.
```

**Comment by natebosch** [comment]
cc @scheglov @stereotype441 - should we drop the call altogether or is there a replacement? What minimum version of the analyzer package should we be on to stop calling this?

**Comment by scheglov** [comment]
Drop the call, old plugins don't work anyway.
