### ISSUE TITLE
If running a "build script snapshot" with a "failed to instantiate builder" error, try rebuilding

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#2098]
Situation

- Make a mistake in `lib/builder.dart`
- run build
- Build fails with `Failed to instantiate builder for json_serializable with configuration` error (fine)
- Fix mistake in `lib/builder.dart`
- Rerun build
- Build fails with `Failed to instantiate builder for json_serializable with configuration` error – because it's running the snapshot!

Work-around: run clean first

**Comment by jakemac53** [comment]
There are a whole class of edge cases like this actually that mostly only come up for builder authors but we should fix in a general way.

One potential solution - if there is an existing snapshot but no serialized asset graph then delete the snapshot and recreate it. We can't check if it was up to date anyways in this case, and all the edge cases I know of are related to the first build failing for one reason or another, resulting in no asset graph being serialized.

**Comment by natebosch** [comment]
If we invalidate the snapshot do we also delete the asset graph? I think you can still hit a problem if you build successfully so you have an asset graph file, then change something that would cause a failure that doesn't invalidate the snapshot and get stuck in this loop...

**Comment by kevmoo** [comment]
`lib/builder.dart` – sorry. Fixed.
