### ISSUE TITLE
Doesn't generate .g.dart files

### ISSUE THREAD

**Issue by H03in** [dart-lang/build#2099]
using fluuter json_serializer to generate json from my models, build runner build the .g.dart file for first time but it does not work any more and build is succeed without any warning or error.

i tried to executing clean command and rebuild it did not care.

* Dart SDK Version (1.5.1)
* What package(s) from this repo you are using, and the version (i.e. `build_runner1.2.8`)
* using flutter json_serializer
* MacOSX
* Flutter

**Comment by natebosch** [comment]
Can you provide a repro case?

> Dart SDK Version (1.5.1)

We haven't made any changes that would be visible on an SDK that old in a very long time...

**Comment by H03in** [comment]
@natebosch thanks for your response, the problem was from my  json_serialization code.
