### ISSUE TITLE
Add support for building only certain "entrypoints"

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2102]
- Deprecate `is_optional: True` in `build.yaml`.
- Add an enum `BuilderType` with values `optional`, `required`, `entrypoint`.
- Add `builder_type: optional` in `build.yaml`.
- Add support for treating `entrypoint` builders as if they are `optional`, but marking a subset of their outputs as `required` using arguments.

When performing a build with no rest args treat all entrypoint outputs as required. When performing a build with today's supported rest args (top level directories) treat all entrypoint outputs in those directories as required. When performing a build with newly supported specific file rest args treat only the entrypoint outputs that are "rooted" at those files as required.

I'm not sure how much work it will take to be able to individually target outputs to flip them from optional to required...

**Comment by kevmoo** [comment]
I'd love to have this.

**Comment by natebosch** [comment]
@kevmoo - can you explain the use case so we can prioritize?

**Comment by kevmoo** [comment]
`json_serializable` development.

https://github.com/dart-lang/json_serializable/blob/master/json_serializable/build.yaml

Sometimes I just want iterate on `_doc_builder` without having _internal, json_serial, and build_web_compilers running

Or maybe I just want to hack no tests, in which case I don't want `_doc_builder` or `build_web_compilers` running.

I end up just adding `enabled: false` all over `build.yaml` while I'm coding, which is annoying.

**Comment by natebosch** [comment]
> Sometimes I just want iterate on `_doc_builder` without having _internal, json_serial, and build_web_compilers running

This issue would not cover that case if I understand correctly. This issue is not about picking which builders run, it's about picking which source files that are "entrypoint" sources should have their non-required outputs created.

Plausibly `_doc_builder` could be an `entrypoint` builder (though I have some doubts), as could `build_web_compilers|entrypoint`, which would mean we could pick which inputs get outputs for those, but if a given source has outputs from both they'd both run. `json_serializable` wouldn't make sense as an entrypoint builder - it should stay `required` which means it would always run.

**Comment by kevmoo** [comment]
If I could say "only do the build things required to give me `doc/doc.md`" great

Same for, say, "test/**" – assuming that'd exclude DDC builds

**Comment by natebosch** [comment]
> If I could say "only do the build things required to give me doc/doc.md" great

You'll need to file a separate feature request for that.

**Comment by kevmoo** [comment]
WRT this request, though, it'd ALSO be nice to be able to build only `web/index.dart` and not all of the tests – is that captured here?

**Comment by natebosch** [comment]
> WRT this request, though, it'd ALSO be nice to be able to build only web/index.dart and not all of the tests – is that captured here?

That is already possible. `pub run build_runner web` or `pub run build_runner serve web` cover that use case. You can already choose which "top level directory" to build.

The use case that is _not_ covered today, and the one that is covered by this request, is building `web/app1.dart` without building `web/app2.dart`.

**Comment by kevmoo** [comment]
For json_serializable, `pbr watch --delete-conflicting-outputs --verbose doc` doesn't seem to do anything. 😕

**Comment by jakemac53** [comment]
The --build-filter argument is meant to resolve this (not be most user friendly api but it does have the functionality to do what you want here).
