### ISSUE TITLE
Update PackageGraph to allow Flutter as a dependency

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#211]

**Comment by natebosch** [comment]
Can you clarify this?

**Comment by matanlurey** [comment]
We choke right now when we see the `sdk: ...` property.

I am working with Eric to get an example of `.packages` for a Flutter app so we can support `build_runner`.

**Comment by matanlurey** [comment]
We need to publish a new build_runner to fix this.

@jakemac53 @natebosch @kevmoo

**Comment by natebosch** [comment]
published
