### ISSUE TITLE
browser tests with `build_runner test` and `--pub-serve` flag are not working

### ISSUE THREAD

**Issue by valakis** [dart-lang/build#2130]
Running browser test with external `build_runner serve` breaks them completely: the external `build_runner serve` generates resources _over_ the ones generated by `build_runner test` and these resources will not be reachable from inside the test itself.

- Dart: 2.1.0
- build_runner: 1.2.3
- build_test: 0.10.6
- build_web_compilers: 1.2.0
- OS: Linux
- Browser: Chrome

**Comment by jakemac53** [comment]
The `--pub-serve` flag is not supported by build_runner - you should use the `build_runner test` command. Does `build_runner test` work for you?

If not we will need some more information here to understand the issues you are seeing.

**Comment by jakemac53** [comment]
Going to close this as not actionable after 7 days of inactivity just as a heads up, please respond in the next two days if there is still something to be done here.

**Comment by valakis** [comment]
I'm trying to generate the test assests (`build_runner serve`)  once both for the vm and browser test then run the test by a different `build_runner test` command.

**Comment by jakemac53** [comment]
I think what you are saying is a known issue - we don't provide a way of reading generated to cache files inside of tests.

You should be able to work around it by reading from `.dart_tool/build/generated/<package-name>/<package-path>` until we have a better proposal here.
