### ISSUE TITLE
Add Future<LibraryElement> BuildStep#library

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#214]
... as a convenience API for doing:

```dart
Future build(BuildStep buildStep) async {
  var resolver = await buildStep.resolver;
  var library = await resolver.getLibrary(buildStep.inputId);
}
```

Instead:

```dart
Future build(BuildStep buildStep) async {
  var library = await buildStep.library;
}
```

It could also be something like `resolveLibrary()`.

It should likely throw if you attempt to resolve a library on a non-Dart source file.

**Comment by matanlurey** [comment]
@natebosch @jakemac53 Reasonable?

**Comment by natebosch** [comment]
Seems fine, probably `inputLibrary`. I don't want to add too many convenience methods to keep the surface area small and keep one way to do things... But this is common enough to warrant a shortcut

**Comment by natebosch** [comment]
Seems fine, probably `inputLibrary`. I don't want to add too many convenience methods to keep the surface area small and keep one way to do things... But this is common enough to warrant a shortcut
