### ISSUE TITLE
How to have inputs from one target depend on the outputs of another?

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/build#2146]
```
Dart SDK: 2.2.0
build: 1.1.3
build_config: 0.3.1+4
build_resolvers: 1.0.4
build_runner: 1.3.1
build_runner_core: 3.0.2
```

What is the recommended way to get the resolver to see types that were generated in a previous target?

What I have always done is:
* Say I have two targets, `_a` and `_b`. `_b` depends on `_a`.
* `_a` creates `a.g.dart`, from `a.dart`.
* `_b` generates `b.g.dart` from `b.dart`, but depends on the existence class `B` from `b.g.dart`.

This used to work perfectly if I just defined `_a` and `_b` as two separate targets in my `build.yaml`, and had `_b` depend on `_a`. However, now, all references to `B` appear as `dynamic` instead.

My `build.yaml` looks like:

```yaml
targets:
  _a:
    sources:
      - a.dart
  _b:
    dependencies:
       - ":_a"
    sources:
      - b.dart
```

My only guess is that the resolver will only see Dart files listed in `sources` for a given target. However, if I include `a.dart` in both targets, I'll get an error, because `a.g.dart` can only be generated once.

So is there a different recommended path for having the inputs to one target depend on the outputs of a previous target?

Thanks in advance.

**Comment by natebosch** [comment]
Hmm, I would have expected this to work using `dependencies` like that.

One thing that could make it not work is if there is an import cycle across the difference targets. So if any file in `_a` imports (transitively) any file in `_b`, that could break this...

**Comment by thosakwe** [comment]
I'm running the graph inspector, and get an output (truncated) like this:

```
> graph

  package:angel_serialize_generator/$lib$
  test/$test$
  web/$web$
  test/models/author.dart
  ... (more here)
  test/models/book.dart
```

In this case, `author.dart` is the file that depends on `book.dart`.

Does the order they appear in the graph inspector relate to the order in which they are built (or is this the reverse order)?

**Comment by jakemac53** [comment]
The command line graph inspector is pretty hard to use - I would try the visual one at `http://localhost:8080/$graph` when using the `serve` command.

You can search for files using the top left search box and it will tell you the phase number in which it is generated - that should help in determining the ordering.

**Comment by thosakwe** [comment]
Everything looks to be correct. In fact, all the files that are supposed to be generated, are. I patched my builder a bit to print out the `book.g.dart` source, if `author.dart` could read it, and it worked.

However, one thing was interesting to me:
* I also patched my builder to print out the names of classes it could find
* Calls to `BuildStep.canRead` succeeded for both `book.dart` and `book.g.dart` when generating `author.angel_serialize.g.part`.
* However,  when using a `LibraryReader`, the only class listed from `book.dart` was `_Book`. `Book` is auto-generated, and contained in `book.g.dart`, which is a `part of` the former. So, for some reason or another, the resolver didn't see the class in the generated file, even though the build step could read it.

I guess I just need to figure out why...

**Comment by natebosch** [comment]
Ah, another thing to confirm - is `book.dart` _imported_ from the second library that you are generating code for?

One thing that could cause this - we only recrawl imports starting at `buildStep.inputId`, so only it's transitive imports can be resolved.
The is a non-hermetic "leak" of information from the analyzer for any libraries that were previously resolved.

So what would happen is that `book.dart` was crawled while generating `book.g.dart` so it can be resolved, but `book.g.dart` has never been crawled. Then when we go to crawl fro the next build step, if it doesn't import `book.dart` we won't re-crawl it's part files, so `book.g.dart` won't be resolved.

Is that what's happening here?

**Comment by thosakwe** [comment]
Actually... I think that might be it. Is there any possible workaround?

**Comment by jakemac53** [comment]
There is no workaround at this time I don't think. It is pretty difficult to do in a way that doesn't come at a very high cost, so I think we are pretty wary of it (we would have to do a full transitive crawl of all imports each time you try to use the resolver, instead of just once when you ask for the resolver itself).

**Comment by jakemac53** [comment]
Closing as not intended for now :(

**Comment by thosakwe** [comment]
That's fine, I've opted to just keep related classes in the same files for now.

**Comment by thosakwe** [comment]
Can I submit a PR to potentially change this? Many people have complained about this to me.

**Comment by jakemac53** [comment]
Actually on a re-read of the last comment from @natebosch it sounds like there is a bug in the implementation, which we would be open to a fix for.

If we want to allow resolving files that are not imported by the primary input then we should have some more discussions about how we can allow that in a way that doesn't regress performance generally. I think there are probably some options.

**Comment by natebosch** [comment]
I do think we could do something to allow resolving other code through `resolver.libraryFor(assetId)`.

What we'd want to do is check if `assetId` was one of the files crawled, and if not restart the crawl process from there.

It will probably be tricky to maintain the state for what has been crawled already.

**Comment by natebosch** [comment]
> on a re-read of the last comment from @natebosch it sounds like there is a bug in the implementation, which we would be open to a fix for.

I don't think there is a bug, so much as that there is non-hermetic behavior which is being exposed. I think we've already decided that being hermetic will be too expensive to do.

If we do expand the capability of `resolver.libraryFor(assetId)` that should make it more difficult to hit the non-hermetic bits by properly tracking inputs on the newly crawled libraries.
