### ISSUE TITLE
Should consider log.severe as a build failure

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#215]
The bazel and barback runners for a Builder consider a log at level severe to indicate a build failure and won't try to continue the build. For consistency we should do this in `build_runner` as well.

**Comment by matanlurey** [comment]
+1

**Comment by matanlurey** [comment]
Thought about this today - it should probably be a configurable flag. For example in https://github.com/dart-lang/source_gen/pull/209 I added a warning that I'd _like_ to make a severe, but I'd worry that would hurt dev-cycle for some users if severe broke the build in build_runner.

WDUT?

**Comment by jakemac53** [comment]
We could change it so that we only fail builds if a builder throws an exception? Otherwise logging as severe would be allowed. Whatever we do though I think its important to be consistent across environments.

**Comment by matanlurey** [comment]
I thought about this more and agree with you 👍

**Comment by natebosch** [comment]
I'd be happy with adding a `--no-fail-on-severe`. I think it makes sense for failing to be the default.

**Comment by jakemac53** [comment]
Should we close this now or is there future work planned?

**Comment by jakemac53** [comment]
Or move it to M1?

**Comment by natebosch** [comment]
I'm good with closing this. We can probably improve the UX but I think the biggest win we'll get is with a synchronous logging API and we're not likely to do that in M0
