### ISSUE TITLE
Document the cost of resolving buildStep.inputLibrary

### ISSUE THREAD

**Issue by ekweible** [dart-lang/build#2150]
We recently discovered that by using the `PartBuilder` util from the `source_gen` package, `await buildStep.inputLibrary` was being called for each library asset which results in the analysis context for that file being fully resolved. Consequently, all transitively imported files become dependencies/inputs in the asset graph which can have a significant impact to the build time especially in larger projects.

Currently, this cost is not made apparent by the documentation in this repo nor by the source documentation on relevant APIs like `BuildStep.inputLibrary`. I'd like to request that this cost be explicitly communicated (maybe in ["FAQ for Builder authors"](https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md)?) - currently it seems a bit too easy to incur this cost when it may not be necessary. A related point that might also be worth clarifying is the difference between just parsing the AST for a file and fully resolving it to get the elements.

**Comment by jakemac53** [comment]
4+ years later, we probably should still do this, although it isn't actually true any more that all transitive imports always become dependencies (the most recent version does fix this, at least sometimes).
