### ISSUE TITLE
Make it easier to deal with conflicting to-source outputs

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#2168]
Use https://pub.dartlang.org/packages/preload

Always getting conflicts with `web/index.html`.

See https://github.com/dart-lang/sample-pop_pop_win for an example

**Comment by kevmoo** [comment]
Maybe related to https://github.com/dart-lang/build/issues/1940

**Comment by kevmoo** [comment]
build_runner_core v3.0.2

**Comment by kevmoo** [comment]
@jakemac53 @natebosch this is on a build where the asset graph is new.

Is there an existing bug for pre-defining these?

**Comment by natebosch** [comment]
> Is there an existing bug for pre-defining these?

Not that I know of. It's this one now.


Proposal for `build.yaml`:

```yaml
generated_files:
- **/*.g.dart
- web/index.html
```

Pros:
- Can avoid `--delete-conflicting-outputs` while maintaining safety.
- Can use `generated-files: ['**']` to opt in to no-safety without having to pass the arg.

Cons:
- It will feel unnecessary to most users. "You know what files are generated - why do I have to tell you?"

We should brainstorm other names for the key. `safe_to_clobber` maybe?

**Comment by natebosch** [comment]
Idea first proposed by @jakemac53 in https://github.com/dart-lang/webdev/issues/259#issuecomment-481771981
