### ISSUE TITLE
Daemon logs need more work

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2171]
I noticed some issues when debugging https://github.com/dart-lang/build/pull/2170 that should be resolved:

- All newlines appear to be stripped from the output
- Logs that aren't supposed to be overwritten are

I think these are both related - it used to be you could add an extra newline after a log and then it wouldn't be deleted.

**Comment by grouma** [comment]
Hmmm. I recall having a discussion with either your or @natebosch that we should keep the logging as simple as possible in Daemon mode and let any client handle the complexity of formatting the logs. We moved towards this design by pushing the color and clearing logic into Webdev. Are you sure this is an issue? Let's discuss more in person to iron out the details.

**Comment by grouma** [comment]
I tried to reproduce this issue in multiple different terminals but I wasn't able to do so. Closing for now.

**Comment by jakemac53** [comment]
I noticed that @alan-knight and I think @kenzieschmoll were seeing the logs like I see them so I think this is a real issue and not specific to me so re-opening

**Comment by jakemac53** [comment]
This is resolved with build_daemon 1.x which gives more structured logs
