### ISSUE TITLE
Support passing `--target` to the kernel worker

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2174]
Today the kernel worker will make an assumption about the target depending on whether summaries are used. We want to make this explicit so that the two settings are not tied together.

It would be handy if this matched the platform name as we already use in the module builder - but there is an incompatibility. The on the build side we call it `ddc`, while on the kernel worker side we call it `devcompiler`

Some options:
- Make `ddc` an allowed alias for `devcompiler` in the kernel worker. Not breaking.
- Add `kernelTarget` to the `DartPlatform`. Breaking in `build_modules`.
- Add `kernelTarget` to the constructor for `KernelBuilder`. Breaking in `build_modules`.
- Hack together a translation between the two in `KernelBuilder`.
- Rename `ddc` to `devcompiler` in `build_web_compilers`. Breaking in `build_web_compilers` (I think).

**Comment by natebosch** [comment]
We might also be able to change the target name in the worker from `'devcompiler'` to `'ddc'` since nothing is passing it today.

**Comment by jakemac53** [comment]
> Make ddc an allowed alias for devcompiler in the kernel worker. Not breaking.

+1

**Comment by jakemac53** [comment]
@natebosch do you know the status here? Can we take action on it now?

**Comment by natebosch** [comment]
yes, we should be able to start passing `--target` as long as we are constrained to `2.3.0`
