### ISSUE TITLE
build_daemon should support doing a single build

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2196]
Right now you can register a build target, but that does rebuilds on each change which we don't want for things like the `build` and `test` commands (we just want a single build).

Also, there is a bit of a question around the functionality when there is already an ongoing build. Should we just get that build result? What if changes have been made between when that build started and we schedule a build?

I think we probably would want to wait for the current build to complete, and then do a new build just to be safe?

**Comment by jakemac53** [comment]
cc @grouma

**Comment by grouma** [comment]
I think a lot of this logic is already implemented. You can manually trigger a build:
https://github.com/dart-lang/build/blob/master/build_daemon/lib/client.dart#L100

The build daemon ensures only one build at a time here:
https://github.com/dart-lang/build/blob/master/build_daemon/lib/src/server.dart#L98

Clients will only be notified of build results if applicable, e.g. they care about a given target:
https://github.com/dart-lang/build/blob/master/build_daemon/lib/src/server.dart#L99

I don't know if we really need to add anything to the daemon protocol. The way I see it is the client will register a target. Manually trigger a build. Wait for the result then disconnect. Thoughts?

**Comment by jakemac53** [comment]
`startBuild` doesn't take a build target though, should we just add that?

**Comment by jakemac53** [comment]
Oh, I guess you were saying you still should register for a build. The problem with that is you could end up causing multiple builds - which could have side effects (output directory manipulation). So canceling your connection isn't really sufficient.

**Comment by grouma** [comment]
Hmmm. There's no real guarantee this won't happen even if we update the protocol. Two clients can be interested in the same build target. One can be long living, while the other could just want a single build.

**Comment by jakemac53** [comment]
It makes it a lot easier to screw up I think though not having a single build api?

**Comment by grouma** [comment]
Yeah I'm not opposed to having a simpler API. This will also reduce code duplication between `webdev` and `build_runner` when we eventually update `build_runner`'s build method to also use the daemon.

**Comment by grouma** [comment]
With manual builds and `startBuild` this should be satisfied. See https://github.com/dart-lang/build/pull/2336
