### ISSUE TITLE
Document the build daemon classes

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2197]
There are almost no doc comments on any of the build daemon related classes right now, which makes them difficult to understand and use. We need to go through and thoroughly document everything.

Specifically all the data classes are really bare and the BuildDaemonClient class also.

As an example, `client.buildResults` is a `Stream<BuildResults>`, and `BuildResults.results` is a `List<BuildResult>`. Why are there multiple build results for each item in the stream?

**Comment by grouma** [comment]
Great idea. I can start tackling this today.
