### ISSUE TITLE
Add support for mocking the global `log` without going through testBuilder

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#220]
The benefit of `log` was the ability to easily split out responsibility for a build without having to pass around a `BuildStep` or `Logger` instance. When unit testing these things we should be able to do it without going through a `BuildStep` or full `Builder`

Add a utility to set up the global `log` for a test.

**Comment by natebosch** [comment]
This is an alternative to making `scopeLog` public from package:build.

It might be as simple as re-exporting that function from build_test.

I feel better about peaking into `src/` from build_test than making it public overall

**Comment by jakemac53** [comment]
sgtm
