### ISSUE TITLE
Flaky build_daemon test on travis

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2212]
Unfortunately travis doesn't keep logs after you restart...

I _think_ it's this expectation that fails:
https://github.com/dart-lang/build/blob/db8b12b84d3696100c6f8025b4d902a33c2e736c/build_daemon/test/daemon_test.dart#L122

Maybe a race condition?

**Comment by grouma** [comment]
Hmm that's a confusing one. I don't see how there would be a race condition with this one. The expectation above completes only after the workspace has been written. Next time the flake happens can you copy the logs?

**Comment by natebosch** [comment]
Example failure output:

```

00:48 +18 -1: test/daemon_test.dart: Daemon cleans up after itself [E]                                                                                                                                 
  Expected: false
    Actual: <true>
  
  package:test_api             expect
  test/daemon_test.dart 136:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                   _AsyncAwaitCompleter.completeError
  test/daemon_test.dart        main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                   _asyncThenWrapperHelper
  test/daemon_test.dart        main.<fn>.<fn>
```

https://github.com/dart-lang/build/blob/f273276d319920c2f18e68575f99134b079f0374/build_daemon/test/daemon_test.dart#L136
