### ISSUE TITLE
Replace declareOutputs with inputExtension/outputExtensions

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#222]
Today in a `Builder` there is a lot of flexibility in deciding what outputs to generate based on an input name. This flexibility is almost completely unused and makes future work more difficult. It's also a detriment to cross-compatibility since we can't support executing Dart code to determine outputs in bazel.

# Proposal

Replace `declareOutputs` with `inputExtension` and `outputExtensions`. Every files ending with `inputExtension` would be a primary input and produce a new files with the extension replaced with every value in `outputExtensions`. The extensions would need to exactly map to the configuration in `build.yaml` when bazel is used.

# Limitations/Drawbacks

One known use case that we'd be making harder is sass - today it is easy to declare no outputs for inputs that start with a leading underscore. We are not aware of other use cases that this would break.

The workaround means slightly more work on the consuming side. Rather than the `Builder` author being able to run only on files that don't start with underscore, the consumer would use a `generate_for` glob that matches only files getting an output.

# Benefits

- Parity between implementations. Arbitrary Dart code to determine outputs is not something we can support in bazel.
- Simpler mental model. The outputs can always be easily predicted.
- Will allow us to extend the configuration expressivity. Today we cannot express that a Builder will output only with the file doesn't already exist - and we cannot check for existence of other files during `declareOutputs`.  If `build_runner` can predict outputs by extension without running code in the Builder we can allow configuration to express that an output is allowed to be superseded by an existing file of the same name.

**Comment by natebosch** [comment]
@matanlurey @filiph @jakemac53 - please give feedback on this proposal. If there is some way this catastrophically breaks a use case it'd be good to find it up front.

**Comment by matanlurey** [comment]
Is it possible to support a glob() format instead of inputs/outputs? Would that help SASS?

**Comment by natebosch** [comment]
A glob() could be hard to support in bazel but we should definitely look closer.

One thing that should be possible in bazel, and could be done if we get to config driven `build_runner` is to have a `default_srcs` and `default_generate_for` globs based on a builder. So SASS could configure `default_srcs = glob(lib/**/*.scss), default_generate_for =  glob(lib/**/*scss, exclude = **/_*.scss)`

**Comment by jakemac53** [comment]
LGTM, I am a big fan of this proposal as it covers all the use cases I know of and simplifies builders a bit.

> If build_runner can predict outputs by extension without running code in the Builder we can allow configuration to express that an output is allowed to be superseded by an existing file of the same name.

I don't think this should be the default behavior, but should be explicitly opt-in. Lets figure out the api for this as well as a part of this proposal. I could imagine either an additional boolean field to enable this behavior, or possibly an additional field that is the list of "soft" output extensions?

**Comment by natebosch** [comment]
The priority for this just became much higher.

I think we should hold off on making a decision around "soft" outputs and start working towards replacing `declareOutputs` asap.

**Comment by filiph** [comment]
SGTM. Simple and predictable. 

Do I understand it correctly that this could potentially unlock an 'aggregate' transformer in the build world?

**Comment by natebosch** [comment]
This is mostly orthogonal to an aggregate builder concept.

**Comment by natebosch** [comment]
We should consider whether we want to allow multiple input extensions. The typical case is 1, but we can imagine scenarios where we want to combine multiple `Builder`s into a single step so they can run concurrently during a build.

The `Phase` concept in `build_runner` allows multiple build actions to cover this case. Today in bazel we only allow a single `Builder` per 'phase' equivalent.

**Comment by jakemac53** [comment]
If the only use case we can come up with is for combining multiple builders then imo we should keep this restricted to a single one and cover the use case with some other concept (similar to `Phase`)?

We could introduce a `MultiBuilder` even if necessary in `build_bazel`?

**Comment by natebosch** [comment]
The nice think about modeling this in `Builder` is that we can use the _same_ concept everywhere.

Pros:
- We'd get to simplify `Phase` in build_runner
- We'd have 1 concept rather than 3
- As we find new places to use Builders they can all be consistent and consistently powerful

Cons:
- A little more overhead when learning how to write a Builder
- Potentially noisier code

Although `const {'.dart': const ['.template.dart']}; ` really is not very noisy.

**Comment by natebosch** [comment]
After some offline discussion we're going forward with a `get` returning `Map<String, List<String>>`. Most builders will likely implement this with a const.

My initial thought is to call this `buildExtensions` - I'm open to other suggestions.

I think we need to allow one of they keys to be empty indicating that it accepts any input. We should also allow empty output lists.
https://github.com/dart-lang/angular2/blob/9eb1ef80eb09ac72c0e24e0ea3a6dcd46d036544/test/meta/types_test.dart#L350

**Comment by jakemac53** [comment]
Is it worth allowing empty output lists for that one test? It seems like it could be re-written to just output a dummy file.

**Comment by natebosch** [comment]
We currently allow empty lists returned from `declareOutpts` AFAIK. If we want to make that stricter I think we should consider it a separate change.

**Comment by natebosch** [comment]
New wrinkle - this doesn't work nicely with `build_runner` where we put outputs in package:a based on inputs from package:b...

Do we know if anyone is using this?

**Comment by jakemac53** [comment]
Hmm, actually I think this might matter. However once we can output files in other packages maybe it won't be necessary any more?

**Comment by natebosch** [comment]
Yeah this shouldn't be as much of a problem when build_runner can run for more than the primary package. In the short term we might need to break that support but I don't know if it will actually impact anyone today.

**Comment by jakemac53** [comment]
I don't know if it breaks compatibility with actual existing things, but it does make that feature a blocker for things like angular where technically today you could make angular work without it.

**Comment by natebosch** [comment]
All the changes are in across this repo.
