### ISSUE TITLE
Add glob or directory listing API in AssetReader

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#223]
This first came up in https://github.com/dart-lang/build/issues/213

A glob api would be the most flexible option since directory listing can easily be done with a glob.

Proposed API:

`List<AssetId> findAssets(String glob)`

I have it take in a String or glob from `package:glob`: I'm not sure it's worth the extra set of dependencies in `build` even if all implementations choose to use package:glob anyway.

**Comment by jakemac53** [comment]
Should we also allow a package name?

**Comment by natebosch** [comment]
Allowing a package name should be feasible, and we can default to the root package...

`List<AssetId> findAssets(String glob, {String package})`

**Comment by matanlurey** [comment]
+1 that API, only nit is maybe `Iterable<AssetId>` in the case someone is going to try and find the first file that matches something?

**Comment by jakemac53** [comment]
It is worth noting that we can't support globbing other packages in pub, so we might want to hold off on actually adding that support until it is needed?

If we do decide to add it, then I think we should also consider adding sync apis (which also won't work in pub).

**Comment by natebosch** [comment]
I retract my earlier statement... `build` already transitively depends on `glob` so for the sake of stricter API (and potentially better performance) I'm going to use

```
Iterable<AssetId> findAssets(Glob glob);
```

**Comment by natebosch** [comment]
Some offline discussion:

This API is going to mean that all implementations of `AssetReader` will need to have an understanding of a 'default' or 'root' package. This shouldn't be too much of a problem in general but will cause a few bits of weirdness:

- In tests the `InMemoryAssetReader` will either always need a default package, or will need to `throw` if there is no default package. Should be doable.
- It'll be harder to pass in a `RunnerAssetReader` for building with build_runner. We'll likely have to change this to a factory `RunnerAssetReader forPackageGraph(PackageGraph graph)`

**Comment by natebosch** [comment]
With https://github.com/dart-lang/build/pull/253 this is now rolled out everywhere
