### ISSUE TITLE
Support running .dill files in `run` command

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/build#2239]
This will be a very simple PR to implement. Because we have `build_vm_compilers`, and can generate `.dill` files already, allowing `run` to support `.dill` would let users skip the initial Dart-to-kernel compilation step when running scripts, especially if the scripts haven't changed since the last run.

The line to change is here:
https://github.com/dart-lang/build/blob/master/build_runner/lib/src/entrypoint/run_script.dart#L86

This code:

```dart
if (p.extension(scriptName) != '.dart')
```

Will simply become:

```dart
if (!const ['.dart', '.dill'].contains(p.extension(scriptName)))
```

Am I good to send in a PR for this?

**Comment by thosakwe** [comment]
Work is done in this branch: https://github.com/thosakwe/build/tree/run-dill

**Comment by jakemac53** [comment]
We definitely want to support running from dill, if `build_vm_compilers` is present.

I think we should do it automatically though, we can discover if the `.app.dill` file is present for the dart file and run that instead.

**Comment by thosakwe** [comment]
Awesome!

**Comment by jakemac53** [comment]
We have deprecated build_vm_compilers due to lack of usage
