### ISSUE TITLE
Don't roll unsupported modules up into supported modules

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2242]
Today the default module strategy can end up making an entire module be "unsupported" even though it is really just some small transitively unsupported sub-library that is unsupported.

On the surface this seems ok - importing the entrypoint of the module is still not going to work if any transitive dep is unsupported. However, this can lead to a scenario where a `src` import (even from the same package!) can give you an error about an unsupported library that you aren't even importing transitively.

For example, this package structure will cause us to not compile `web/main.dart` because `lib/src/b.dart` is not supported on web, even though we never import that file:

```
lib /
  a.dart // imports `src/b.dart` and `src/c.dart`
  src/
    b.dart // imports `dart:io`
    c.dart // doesn't import `dart:io`
web/
  main.dart // imports `lib/src/c.dart`
```

I think the simplest solution here is to just never roll unsupported modules up into larger modules (unless they are in a cycle). So in the example above we could create a module with `lib/a.dart` and `lib/src/c.dart` but we would leave `lib/src/b.dart` in its own module.

**Comment by jakemac53** [comment]
cc @natebosch @grouma

**Comment by natebosch** [comment]
It's always been the case that a `src` import could cause you to bring in extra code, including unsupported code...

**Comment by jakemac53** [comment]
> It's always been the case that a `src` import could cause you to bring in extra code, including unsupported code...

Right, but now we will refuse to even attempt to compile those libraries so it surfaces in a worse way :).

**Comment by jakemac53** [comment]
Actually, I just realized this is worse that I originally realized. We really need to check not just if the module itself is incompatible but also if any of its transitively imported modules are incompatible.

**Comment by natebosch** [comment]
> also if any of its transitively imported modules are incompatible.

That definitely makes this more tricky - at the time we're doing this level of merging we don't necessarily have transitive modules available...
