### ISSUE TITLE
Use new BuildConfig.parse({configYamlPath}) when build_config 0.4.1 is released

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#2257]
https://github.com/dart-lang/build/blob/93b9f3bdbbe7e94f13cce15a8e5909b72fe422b6/build_runner/lib/src/package_graph/build_config_overrides.dart#L37

Will give more helpful errors when parsing fails.

**Comment by kevmoo** [comment]
CC @natebosch RE https://github.com/dart-lang/build/pull/2247

**Comment by natebosch** [comment]
Was fixed in https://github.com/dart-lang/build/pull/2386
