### ISSUE TITLE
When the build_daemon fails to start we should log the exception to the client

### ISSUE THREAD

**Issue by grouma** [dart-lang/build#2259]
I think we want to fiddle with the logic here:
https://github.com/dart-lang/build/blob/master/build_daemon/lib/client.dart#L56

**Comment by grouma** [comment]
Found out we actually log the error message. However, the message is immediately cleared due to our logging logic. This will mostly be fixed by `build_daemon` version `1.0.0` as the client will now log `SEVERE` messages which should not be cleared:
https://github.com/dart-lang/build/blob/master/build_daemon/lib/client.dart#L36

**Comment by jakemac53** [comment]
@grouma is this done now?

**Comment by grouma** [comment]
Yup. This is done.
