### ISSUE TITLE
Javascript bridge is broken with build_test

### ISSUE THREAD

**Issue by valakis** [dart-lang/build#2260]
The latests version (1.4.0) of `build_runner test` command will not import the js bridged dart files. Here is  a miminal reproduction: [repo](https://github.com/valakis/test_repo)
`pub run test -p chrome` runs as expected but
`pub run build_runner test -- -p chrome` terminates with error. `serve` and `build` commands run fine, but `test` fails with the below error message.
Here is the error:
```
00:01 +0 -1: test/bridge_test.dart: Javascript bridge [E]                                                                                                                                              
  NoSuchMethodError: tried to call a non-function, such as null: 'bridge_interop$.bridge'
  bridge_test.dart 10:12  <fn>
  
00:01 +0 -1: Some tests failed.
```

**Comment by jakemac53** [comment]
It looks like this is happening with DDC but not dart2js.

I don't know exactly what is expected but the `bridge_interop.ddc.js` file is essentially an empty module:

```
define(['dart_sdk'], function(dart_sdk) {
  'use strict';
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const bridge_interop = Object.create(dart.library);
  dart.trackLibraries("test/bridge_interop", {
    "bridge_interop.dart": bridge_interop
  }, '{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"bridge_interop.ddc.js"}');
  // Exports:
  return {
    bridge_interop: bridge_interop
  };
});

//# sourceMappingURL=bridge_interop.ddc.js.map
```

Note that even its source map has no sources, so something weird is up for sure.

**Comment by jakemac53** [comment]
Ok, we tracked this down to a kernel/ddc issue. It looks like all cross module js interop calls are broken right now. 

As a workaround you can add a helper method to the same library which isn't external, and have that just forward to the external JS method, so something like this:

```dart

@JS('bridge')
external String _bridge();

String bridge() => _bridge();
```

**Comment by jakemac53** [comment]
Going to close this in favor of https://github.com/dart-lang/sdk/issues/36912

**Comment by jakemac53** [comment]
Note that another workaround would be to limit to `build_web_compilers: ^1.0.0`, which would keep you on the analyzer based DDC until this gets resolved. The widget inspector for flutter_web won't work as well though.
