### ISSUE TITLE
Empty file import causes webdev build to break

### ISSUE THREAD

**Issue by Meai** [dart-lang/build#2261]
Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "linux_x64"

bla.dart = totally empty file, or full of only comments

```
import 'bla.dart';
main() {
}
```

> webdev serve

Causes:
`Uncaught TypeError: Cannot read property '$0' of undefined`

**Comment by Meai** [comment]
okay actually there seem to be even deeper issues with Dart 2.3 
I switched back to 2.2 because I dont have time to investigate this, my code works again immediately.

**Comment by jakemac53** [comment]
You can also try falling back to `build_web_compilers: ^1.0.0`, version 2.x switches to using the common frontend which is the most likely culprit. Then you can still use all the new ui-as-code features.

**Comment by jakemac53** [comment]
Actually, I can't repro this issue, can you create a git repo I can clone that reproduces it?

**Comment by Meai** [comment]
Ok it works now after `pub cache repair`, I dont see why I should have to remember doing that though. Clearly something is still subtly wrong.
