### ISSUE TITLE
Hot reload socket issues

### ISSUE THREAD

**Issue by sinegovsky-ivan** [dart-lang/build#2272]
- Dart SDK 2.2.0
- angular: 5.2.0
- build_runner: 1.2.3
- build_web_compilers: 1.2.0
- MacOSX 10.4
- Chrome 74

**Issue 1:** 
We are using https for local development, but hot-reload socket use ws:// prefix and chrome doesn't allow to use ws:// with https:

> Uncaught Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

This issue is fixed in https://github.com/dart-lang/build/pull/2271

**Issue 2:** 
We are using nginx as the proxy to our backend. Nginx has been redirecting all root requests (for example: foo.bar/) to our backend.
Since the socket connection is also using the root address, it is redirected to our backend instead of webdev hot-reload server.
Is any way to change socket endpoint? 
_For example localhost:8181/hot-reload-socket instead of localhost:8181._

**Comment by jakemac53** [comment]
I think we should move this to the webdev repo where the hot restart/reload logic has all moved, I think it probably has the same problem though.

cc @kevmoo can you move it?

**Comment by kevmoo** [comment]
Issue moved to [dart-lang/webdev #389](https://github.com/dart-lang/webdev/issues/389) via [**ZenHub**](https://www.zenhub.com/)
