### ISSUE TITLE
Feature Request: fall back to index.html for missing files to allow reloading pushState based routes

### ISSUE THREAD

**Issue by fbcouch** [dart-lang/build#2273]
For example, I'm serving the web/ folder on localhost, and my webapp uses pushState to navigate to /create-account; if I hit refresh, I end up with a not found message. I think there should be an option to allow any missing files to fall back to index so that in that case, web/index.html would be served.

I'm sure there's a cleaner way of doing this, but what I did for my own use was to modify AssetHandler.handle to add that fallback:
```dart
Future<shelf.Response> handle(shelf.Request request, String rootDir) =>
    ((request.url.path.endsWith('/') || request.url.path.isEmpty)
            ? _handle(request.headers, pathToAssetId(_rootPackage, rootDir, request.url.pathSegments.followedBy(const ['index.html']).toList()),
                fallbackToDirectoryList: true)
            : _handle(request.headers, pathToAssetId(_rootPackage, rootDir, request.url.pathSegments)))
        .then((initialResponse) {
      if (initialResponse.statusCode == 404) {
        return _handle(request.headers, pathToAssetId(_rootPackage, rootDir, const ['index.html']),
            fallbackToDirectoryList: true);
      }
      return initialResponse;
    });
```

**Comment by jakemac53** [comment]
The problem with this is it would likely end up hiding a lot of legitimate 404s, we don't want to serve the `index.html` for missing images, css files, fonts, etc which really should be 404s.

We have had similar asks from the angular team for instance in the past as well, but the best solution available at this time is to use a proxy server in front of our server, which rewrites known routes to `index.html` before forwarding them on.

**Comment by natebosch** [comment]
Existing issue considering alternatives: https://github.com/dart-lang/build/issues/886
