### ISSUE TITLE
Unable to start build daemon

### ISSUE THREAD

**Issue by cooler-king** [dart-lang/build#2274]
Having problems with the build daemon starting due to failure to create a server socket.  The problem reliably goes away if I reboot my computer.  But once it starts happening I can't get it to stop until I reboot.  I haven't found any other workaround yet, including deleting .dart_tool.

Dart 2.3.0
Windows x64

![image](https://user-images.githubusercontent.com/11008367/57932881-dd4a5680-7889-11e9-9033-e39059af3272.png)

**Comment by natebosch** [comment]
cc @grouma

**Comment by jakemac53** [comment]
Should this be deduped with some other issues? I think the others exist in the webdev repo?

**Comment by grouma** [comment]
Closing in favor of  https://github.com/dart-lang/webdev/issues/375
