### ISSUE TITLE
Can i know the total number of mapped files?

### ISSUE THREAD

**Issue by KingWu** [dart-lang/build#2275]
I would like to capture the total number of mapped files. And read the file's name. Finally, generate a dart file when the last build(BuildStep buildStep) called.

**Comment by jakemac53** [comment]
> I would like to capture the total number of mapped files.

To clarify, by "mapped files" do you mean generated files? Or potentially generated files too (that were either not output explicitly or not required for the current build)?

> Finally, generate a dart file when the last build(BuildStep buildStep) called.

There isn't a mechanism for that (how would multiple of these compose together?).

There are `PostProcessBuilder`s but they are very limited and you can't produce dart files with them (or if you do, they would be produced after the compilers run so there isn't much point). They are really only intended for expanding archives.

**Comment by jakemac53** [comment]
Going to close this as I don't think either of these are feasible at this time, given my current understanding of the request.

If you want to make a builder that has access to certain types of files, you can use [required_inputs](https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md#builderdefinition) but you shouldn't generally output the same file extension as you require, especially not `.dart`. That leads to an in-determinant ordering with other builders that also require `.dart` files (the compilers specifically).

**Comment by natebosch** [comment]
You might be interested in reading through https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md in case that matches your use case.
