### ISSUE TITLE
Primary input library has essentially no data 

### ISSUE THREAD

**Issue by eernstg** [dart-lang/build#2310]
Working on an update to a package such that it uses 'build' with analyzer 0.36.3, I obtain a `LibraryElementImpl` representing the primary input library which is essentially empty (almost all fields are null), and this subsequently causes various other problems.

However, the core problem can be reproduced with a very small example: https://github.com/eernstg/build_example_unresolved. When that repo is cloned to a directory, `cd` there and do this:

```
> pub get
> rm -rf .dart_tool
> dart bin/main.dart
```

The resulting output contains lines like the following (I deleted some `[WARNING]` lines to avoid the visual noise):

```
[INFO] Build:Running build...
inputId: unresolved|example/example.dart
Resolved input library: 
  Unit: /unresolved/example/example.dart
Library: 
  Unit: /unresolved/example/example.dart
Library: dart.core
  Unit: dart:core
```

The point is that the primary input to the builder (`example.dart`) can be obtained using `await buildStep.inputLibrary` (see [UnresolvedBuilder.build](https://github.com/eernstg/build_example_unresolved/blob/ac03b8edda1d88637fa7b795e295954b7db06b3e/lib/unresolved.dart#L12)), and a set of libraries reachable from there can be obtained using `await resolver.libraryFor(inputId)`, but even though every _other_ library than the primary input has all the expected properties, there seems to be no way to obtain a properly resolved representation of the input library.

Is this a bug? Maybe it's for the analyzer? With earlier analyzer versions the issue did not arise.

**Comment by natebosch** [comment]
I don't understand what the specific issue demonstrated by the repro is. Is it that `library.displayName` is blank for the input library?

**Comment by eernstg** [comment]
@natebosch, thanks for taking a look!

The issue that I see directly in the original context (package reflectable) is that the following returns null, as a result of updating to use analyzer 0.36.4 rather than a <0.35 version:

```dart
ConstantEvaluator(library.source, library.context.typeProvider).evaluate(expression);
```

Constant evaluation returning null is an issue that we've seen several times, and it has generally been caused by a library that has not been resolved. So when I see a `LibraryElementImpl` associated with this problem that has almost every field set to `null`, it seems likely that it is not resolved.

The small extract of the situation in https://github.com/eernstg/build_example_unresolved confirms that the input library has a similarly "empty" state. The fact that `library.topLevelElements.toList()` is non-empty seems consistent with the assumption that the library has been parsed, but not resolved.

But it sounds like you think the library could very well be resolved in spite of the many nulls. Btw, do you have a way to verify that? (there is nothing like an `isResolved` getter, it is just documented that a number  of values returned from `Element` methods may be null or an empty list, or 'the information isn't available', because the library isn't resolved).

**Comment by natebosch** [comment]
From a different thread it sounds like the issue may be related to the different "levels" of resolution that the analyzer has? `buildStep.inputLibrary` should be a resolved element model. To get an AST (either parsed or resolved) you'd need to go through `library.session.getResolved*` or `library.session.getParsed*`.

**Comment by natebosch** [comment]
> Btw, do you have a way to verify that? (there is nothing like an `isResolved` getter, it is just documented that a number of values returned from `Element` methods may be null or an empty list, or 'the information isn't available', because the library isn't resolved).

My understanding was that the element model is always "resolved" and it's the AST that can be either "parsed" or "resolved". I don't know much about which fields do or do not work in that model.

We use [`AnalysisDriver.getLibraryByUri`](https://github.com/dart-lang/build/blob/593931a940dfa6236c50d034e51bc00ff97f5ac0/build_resolvers/lib/src/resolver.dart#L94) to get to the element model. @stereotype441 may be able to better explain the behavior of the returned library.

**Comment by eernstg** [comment]
Thanks again @natebosch and @stereotype441 for your input, it's been very helpful! I think `build` and the analyzer are working as intended (so I'll close this now). Then I'll need to refactor the code I'm working on such that it's generally asynchronous, and then I can use `getResolved*`.
