### ISSUE TITLE
Expose daemonPort as getter/method on Daemon client.

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/build#2313]
...This is required for the flutter_tool to pass through to webdev eventually. Since I believe the client should know the port already we could expose it as a getter/setter.

**Comment by jonahwilliams** [comment]
Err, not as a setter - that would make no sense :)

**Comment by jakemac53** [comment]
Ah so the asset server port (which I think is the specific thing you need here) is not a general build daemon concept (its build_runner specific). That complicates this a little bit.

**Comment by grouma** [comment]
Do we need the asset port:
https://github.com/dart-lang/build/blob/master/build_runner/lib/src/entrypoint/daemon.dart#L91

Or the build daemon port:
https://github.com/dart-lang/build/blob/master/build_daemon/lib/client.dart#L22

**Comment by grouma** [comment]
If we need to expose the asset port we will need to do that through `package:build_runner` as this is not a `build_daemon` concept.

If we need to expose the `daemon` port then we can easily modify the client API for `package:build_daemon`. 

@jonahwilliams can you confirm what is required?

**Comment by jonahwilliams** [comment]
Sorry for the delay!

What is needed is the `daemonPort` that web dev requires here: https://github.com/dart-lang/webdev/pull/440/files#diff-b84db82f5fe57b165c3d044fa5916e5bL24

This can be grabbed via the utility method in https://github.com/flutter/flutter/pull/34252/files#diff-01a7653ade6cc1a5182fdebf929ad64bR496

(I could also keep using the above utility method)

**Comment by jakemac53** [comment]
That is a poorly named parameter, its really the asset server port :).
