### ISSUE TITLE
Add a flag to disable auto building

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/build#2314]
Instead of watching files and eagerly building, we should expose a flag that a) disables file watching and debouncing and b) only starts a build when specifically requested via the daemon. This is to integrate with the flutter_tools resident runner.

**Comment by grouma** [comment]
There is a concern that tools provide an incomplete list of sources. The alternative approach is to allow the build_daemon to continue watching for changed files but instead support a mode of manually triggering the builds.

**Comment by jonahwilliams** [comment]
Yes, i think that approach would be perfectly acceptable as well

**Comment by jakemac53** [comment]
On windows for now at least the watcher comes at a very large cost because of the polling watcher. At least on windows we should probably do a regular file scan, and I would prefer to only deal with one code path so that makes me lean towards the file scan on demand approach.

**Comment by jonahwilliams** [comment]
That's a good point, i would also be concerned that with a polling watcher we might "miss" events unless there was a sufficient debounce period, but that would probably slow the whole thing down again
