### ISSUE TITLE
When DDC compilation skips an entrypoint, provide the import path from entrypoint to each incompat lib

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2316]
* Dart SDK Version: 2.3.2
* Relevant packages:

```
- build_resolvers 1.0.5
- build_runner 1.5.2
- build_test 0.10.8
- build_web_compilers 2.1.1
- built_value_generator 6.6.0
- build_config 0.4.0
- build_daemon 1.0.0
- build_modules 2.3.0
- build_runner_core 3.0.6
```

-----

With build_web_compilers 2.x when we get warnings about compilation being skipped because transitive libraries have unsupported sdk deps, there is not currently a way to see the import path from the entry point to those problematic transitive libraries. We've got quite a few instances of this happening, but unfortunately it is usually non-obvious to figure out how, for example, `test_core|lib/src/runner/load_exception.dart` actually got imported.

It would be nice if for each incompatible lib, the import path was provided in the build output (maybe only in `--verbose` mode) so that the problematic imports can be more easily tracked down and fixed.

**Comment by jakemac53** [comment]
Another way to approach this problem could be a general utility that takes a dart file and a uri for some dependency, and will give you the import path(s) to that dependency.

There have been other use cases for wanting to do such a thing and we could simply link to the tool in the message?

**Comment by jakemac53** [comment]
I am also not really sure what the best way to visualize this is going to be - these import paths could be very long.

**Comment by jakemac53** [comment]
Note that while not official I have published a small package called `import_path` which you can use to get the shortest import path from one dart library to another:

```
pub global activate import_path
pub global run import_path <entrypoint> <import>
```
