### ISSUE TITLE
Wrongly included file ruins build

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/build#2322]
Related to: https://github.com/grpc/grpc-dart/issues/195
The example https://github.com/sigurdm/angular_grpc_web demonstrates the issue.

I get this message on doing `pub run build_runner serve web:8083`:
```
[WARNING] build_web_compilers:entrypoint on web/main.dart:
Skipping compiling angular_grpc_web|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

googleapis_auth|lib/src/oauth2_flows/auth_code.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
```
When I delete the import of googleapis_auth-0.2.7|rsa_sign.dart at: https://github.com/sigurdm/grpc-dart/blob/demonstrate_issue/lib/src/auth/auth.dart#L20 the problem disappears. But it the transitive closure of rsa_sign.dart's import graph does not contain googleapis_auth|lib/src/oauth2_flows/auth_code.dart (unless I'm missing something very obvious).

I don't know how this import sneaks in - any ideas?

**Comment by jakemac53** [comment]
It is quite possible that you are running into https://github.com/dart-lang/build/issues/2242.

Fixing this has turned out to be more difficult than originally anticipated and we never actually got any reports of it happening, but we could prioritize a fix.

**Comment by sigurdm** [comment]
I made a 'hack' by copying the offending code from googleapis_auth to grpc-dart, making this less pressing.

That code should not be imported from googleapis_auth/src anyways.
We could consider putting it in its own package, but I would really not like having to maintain a package claiming to implement cryptographic primitives. (Well now I technically am, but in a more covert manner).

**Comment by jakemac53** [comment]
Ok, so it sounds like it was likely that you were hitting that issue then? If so we can probably close this as a dupe of that one.

**Comment by sigurdm** [comment]
From my perspective it does indeed looks like the symptoms of #2242 - I don't know the internals well enough to confirm it is the same.
