### ISSUE TITLE
http://localhost:63342/quickstart/web/main.dart.js 404 (Not Found)

### ISSUE THREAD

**Issue by hpoit** [dart-lang/build#2324]
Hi @jakemac53! I have a similar issue I've been trying to solve for the past two days:
![image](https://user-images.githubusercontent.com/3711100/59927639-57cf3e80-9413-11e9-840e-d9234013c603.png)
I've installed Dart's SDK (not from Flutter), and also have added some paths to `.bash_profile`:
![image](https://user-images.githubusercontent.com/3711100/59927757-8d742780-9413-11e9-82de-597440e64e34.png)
Need help please!

_Originally posted by @hpoit in https://github.com/dart-lang/build/issues/1088#issuecomment-504436139_

**Comment by hpoit** [comment]
When I run flutter pub global activate webdev, I get:
![image](https://user-images.githubusercontent.com/3711100/59953445-828eb680-9456-11e9-8d1d-9c5ada16b1a9.png)
Thanks @jakemac53. Which other information can I provide you? Can you help me with defining the exact path on `.bash_profile`?

**Comment by hpoit** [comment]
To reproduce this error, I have followed the steps up to https://angulardart.dev/tutorial/toh-pt1#libapp_componentdart-import-and-class, installed Flutter AngularDart first, realized it wasn't enough, then installed the Dart SDK, then tried running index.html again, but no go.

**Comment by hpoit** [comment]
I am using AngularDart for a business project. I need to learn it fast and start building the web project I outlined to the customer. After that, I plan on using Flutter for the iOS and Android part of the project.

**Comment by hpoit** [comment]
This is off-topic: I also wanted to ask you on how and which tools you recommend to use to separate the backend of AngularDart into microservices. The AngularDart part of the project will be the customer's back-office side of the software, or an ERP if you will.

**Comment by hpoit** [comment]
What's the path for Flutter's web directory so I can export it?

**Comment by hpoit** [comment]
Jake, I skipped this step, going through it now: https://dart.dev/tools/webdev Sorry.

**Comment by hpoit** [comment]
I was using Flutter's weddev

**Comment by jakemac53** [comment]
was your issue resolved @hpoit ?
