### ISSUE TITLE
And an FAQ entry about -D environment limitations and workaround

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2325]
See https://github.com/dart-lang/build/issues/1053#issuecomment-385449775

We should have an FAQ entry about this. We could also consider publishing a reusable version of the constant builder concept.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/pull/2507 Changes this, as it adds the general ability to add ddc arguments as long as they are consistent throughout the entire build.

**Comment by jakemac53** [comment]
We do support environment args for ddc at least now - on request we can add others.
