### ISSUE TITLE
Test command can leave the child `pub run test` process running in background

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2327]
* Dart SDK Version: 2.3.2 and 2.5.0-dev.0.0
* Build package versions:
  * build_runner: 1.6.0
  * build_runner_core: 3.0.6
  * build_test: 0.10.8
* MacOSX

---

The `pub run test` command consumes the first `sigint` instance in order to give the test runner a chance to finish in-progress work (new test suites are prevented from starting, in-progress suites are allowed to finish). However, the `pub run build_runner test` command will exit on the first instance of `sigint`. The result is that interrupting a `build_runner test` process can leave the `pub run test` process running in the background.

A repro can be found here: https://github.com/evanweible-wf/build_runner_test_hanging_test_process

---

Locally, I was able to update the `TestCommand` at `build_runner/lib/src/entrypoint/test.dart` like so:

```diff
   Future<int> _runTests(String precompiledPath) async {
     stdout.writeln('Running tests...\n');
     var extraTestArgs = argResults.rest;
     var testProcess = await Process.start(
         pubBinary,
         [
           'run',
           'test',
           '--precompiled',
           precompiledPath,
         ]..addAll(extraTestArgs),
         mode: ProcessStartMode.inheritStdio);
-    return testProcess.exitCode;
+    StreamSubscription sigintSub;
+    sigintSub = ProcessSignal.sigint.watch().listen((signal) async {
+      testProcess.kill(signal);
+      await testProcess.exitCode;
+      await sigintSub?.cancel();
+      sigintSub = null;
+    });
+    final testExitCode = await testProcess.exitCode;
+    unawaited(sigintSub?.cancel());
+    return testExitCode;
   }
 }
```

and this resolved the issue. The sigint received by the build_runner process gets explicitly forwarded to the test process, and the handler doesn't return until the test process exits, which in turn keeps the build_runner process open until that happens. As a result, you can interrupt the build_runner process with `ctrl+c` and if the test process consumes that event, the build_runner process will transitively do the same.

**Comment by evanweible-wf** [comment]
The solution above might be a naive one. I know build_runner has some of its own interrupt/disconnector logic, but it isn't currently tied to child processes in any explicit manner (at least that I can see). I also noticed that the test package listens for exit signals like so:

https://github.com/dart-lang/test/blob/1ccf56082adf35d5436e09793f547dbaa2e48218/pkgs/test_core/lib/src/executable.dart#L59-L68

Not sure if listening only for sigint would suffice in this scenario 🤷‍♂

**Comment by evanweible-wf** [comment]
Been playing around with it some more, and I'm actually not sure if the signal needs to be explicitly forwarded to the child process, I _think_ because it is started in the `inheritStdio` mode.. but waiting for it to exit does seem necessary.

**Comment by evanweible-wf** [comment]
This seems to do the trick:
```dart
Stream<ProcessSignal> get exitProcessSignals => Platform.isWindows
      ? ProcessSignal.sigint.watch()
      : StreamGroup.merge(
          [ProcessSignal.sigterm.watch(), ProcessSignal.sigint.watch()]);

void ensureProcessExit(Process process) {
  StreamSubscription sub;
  sub = exitProcessSignals.listen((signal) async {
    await process.exitCode;
    await sub?.cancel();
    sub = null;
  });
  process.exitCode.then((_) {
    sub?.cancel();
    sub = null;
  });
}
```

e.g.:

```dart
final process = await Process.start('pub', ['run', 'test'], mode: ProcessStartMode.inheritStdio);
ensureProcessExit(process);
return process.exitCode;
```

I haven't tested it with processes started in detached mode, but if necessary the signal can be forwarded via `process.kill()`.

**Comment by jakemac53** [comment]
@evanweible-wf did you want to send a PR for that change? It generally lgtm, although I think you might not need to cancel the subscription explicitly in the listener (the following `process.exitCode.then(...)` should handle it).

**Comment by evanweible-wf** [comment]
@jakemac53 yup sounds good, I'll make a PR 👍
