### ISSUE TITLE
testBuilder should provide a way to specify language versions

### ISSUE THREAD

**Issue by srawlins** [dart-lang/build#2343]
See the accepted [Dart Language Versioning](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md) specification.

In summary, the "Dart language version" of a package can be specified in the `pubspec.yaml` of a pub package, and forwarded to the `.packages` file of a local pub checkout (e.g. by `pub get`). Additionally, an individual library can override the Dart language version that its package specifies, via a comment at the top, e.g. `// @dart = 2.0`. Only overrides to _earlier_ versions are allowed.

So, `testBuilder` (and similar methods?) should allow the test author to specify what Dart language version the source assets are using. Presumably one language version per package declared in the source assets. Builder authors will want to test, e.g., that they can build correct code when one asset uses Dart language version 2.5, and that asset imports another asset, which uses Dart language version 2.0.

#2229 is related: at a time when an unreleased Dart language version requires an experiment flag (such as now, with the NNBD experiment flag), then `testBuilder` will also need to "pass  on" that flag.

**Comment by natebosch** [comment]
Can this be put in to the source asset content?

**Comment by srawlins** [comment]
Alas. The only Dart language versioning that can be specified in a library content is _overriding_ the Dart language version specified in a package, to an earlier version.

**Comment by natebosch** [comment]
Ah, in that case we need to start by figuring out whether we need to communicate package version information to the analyze in the non-test case.

@stereotype441 - can you weight in? Will we need to do something around language versioning with the `AnalysisDriver`?

**Comment by jakemac53** [comment]
This seems like a larger problem. Imo it isn't reasonable to expect codegen authors to generate different code based on the supported language version of the library they are generating into. Ideally we wouldn't even surface that information to them.

One option would be for code generators to simply put in the `// @dart = x.x` comment based on _their_ minimum sdk constraint, but that has several issues as well (especially if you can't upgrade the version). It also makes combining builders harder but that should be resolvable.

**Comment by jakemac53** [comment]
cc @lrhn for your thoughts since I think you own the feature

Given NNBD it seems like code generators may not be able to avoid knowing about these language version constraints...

**Comment by jakemac53** [comment]
It is also worth noting that we don't expose the `pubspec.yaml` file from non-root packages at all to builders right now. We will probably need to add an api to get the sdk constraint for the package, as well as the language version comment for a given file. We will either have to whitelist the pubspec.yaml asset for the dependency tracking or make yet another special node type or something?

**Comment by srawlins** [comment]
The mockito code gen API needs this functionality, to declare the Language version of inline assets for, for example, `testBuilder`.

This doesn't sound like something an external contributor (me) could easily add. ☹️

**Comment by jakemac53** [comment]
I think there might be a larger but related issue here around the resolver that we expose. As far as I can tell we are not pointing it at a `.packages` file at all (much less the new, `.dart_tool/package_config.json` file). 

So I don't know where the analyzer is getting the language version information, or how we are supposed to be supplying it.

**Comment by jakemac53** [comment]
cc @scheglov are language versions ready to use in the analyzer, and how are they configured?

**Comment by srawlins** [comment]
LibraryElement now has [isNonNullableByDefault](https://pub.dev/documentation/analyzer/latest/dart_element_element/LibraryElement/isNonNullableByDefault.html), but that is for individual library overrides, I think.

**Comment by jakemac53** [comment]
The analyzer must at some point be reading the `package_config.json` files though... or maybe it just reads the pubspec.yaml directly? I suppose from an analyzer perspective the latter might actually be the correct choice.

We need to know how to communicate the language version for each package before we can implement anything here in any case.

You could experiment by adding `pubspec.yaml` files for each package with sdk version constraints and see what happens.

**Comment by scheglov** [comment]
I have not read the `package_config.json` [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md) yet. I don't believe we have anything implemented to support it in analyzer yet.

**Comment by srawlins** [comment]
> You could experiment by adding pubspec.yaml files for each package with sdk version constraints and see what happens.

Analyzer knows no version number which would support NNBD, so this doesn't work yet. You can also enable the experiment via `analysis_options.yaml`:

```yaml
analyzer:
  enable-experiment:
    - non-nullable
```

But this did not work in `testBuilder`. I tried adding assets like:

```dart
{
    'foo|lib/foo.dart': r'''
class Foo {
  dynamic a() => 7;
  int _b(int x) => 8;
  static int c(int y) => 9;
}
''',
    'foo|analysis_options.yaml': r'''
analyzer:
  enable-experiment:
    - non-nullable
''',
}
```

And never was able to affect the nullability via [TypeSystem](https://pub.dev/documentation/analyzer/latest/dart_element_type_system/TypeSystem-class.html), nor the LibraryElement's `isNonNullableByDefault` property.

**Comment by natebosch** [comment]
I would not expect this to be possible today - we don't feed any `analysis_options` files to the analyzer. Solving this will require a supported way for us to convey this information.

**Comment by srawlins** [comment]
Looks like @jakemac53 has plumbed everything necessary the `withEnabledExperiments` function from `package:build/experiments.dart`. Can this be closed?

**Comment by jakemac53** [comment]
I think you would need to pass your own resolver to `resolveSource` but then that would work. We could always create a new resolver on each call instead of using [this default one](https://github.com/dart-lang/build/blob/master/build_test/lib/src/resolve_source.dart#L18), and then that would always work I think.

**Comment by jakemac53** [comment]
Actually we should probably do that anyways and forward the `packageConfig` parameter from `resolveSources` to it as well, which is how you would actually supply the language versions to opt into any features you enable.
