### ISSUE TITLE
BuildRunnerDaemonBuilder should respect --skip-build-script-checks 

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/build#2356]
In https://github.com/dart-lang/build/pull/2317/files#diff-d93edda0ea4440c7871bf77eb8bd3017R72 a check was added for a build script check. This will cause a daemon spawned by the flutter_tool to never successfully start, since we don't require the project to have a build_runner/daemon dependency.

instead we'd need something like
```
    if (!_buildOptions.skipBuildScriptCheck && _builder.buildScriptUpdates
        .hasBeenUpdated(changes.map<AssetId>((change) => change.id).toSet())) {
      _buildScriptUpdateCompleter.complete();
      return;
    }
```

**Comment by grouma** [comment]
On it.
