### ISSUE TITLE
package|file.dart sometimes means package:package/file.dart?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#238]
There seems to be some inconsistency about asset resolution.

```dart
// Is this package:build_test/build_test.dart
new AssetId('build_test', 'build_test.dart')

// Or is this?
new AssetId('build_test', 'lib/build_test.dart');
```

In particular I'm using `PackageResolver` in an upcoming PR, and needed to write:

```dart
  File _resolve(AssetId id) {
    // Gets around inconsistencies with asset URIs.
    //
    // Sometimes build_test|build_test.dart = package:build_test/build_test.dart
    // and sometimes you need |lib/build_test.dart. The package resolver is the
    // former, so a prefix of 'lib/' results in 'lib/lib/'.
    if (id.path.startsWith('lib/')) {
      id = new AssetId(id.package, id.path.substring('lib/'.length));
    }
    return new File.fromUri(_packageResolver.urlFor(id.package, id.path));
  }
```

**Comment by natebosch** [comment]
I'm pretty sure we intend for only `new AssetId('build_test', 'lib/build_test.dart');` to work, so if the other version works we have a bug somewhere.

Will take a look at `PackageResolver`.

**Comment by matanlurey** [comment]
To clarify, `PackageResolver` is a different package which might have it's own rules. 

I figured this out, they don't expect `lib/` in the second parameter.
