### ISSUE TITLE
--log-performance crashes on Windows

### ISSUE THREAD

**Issue by Fox32** [dart-lang/build#2393]
I'm using build_runner on Windows and just found the `--log-performance` command line option and wanted to try it. However the application crashes when I specify it:

```
>pub run build_runner build --output out --log-performance out
[INFO] Generating build script completed, took 651ms
[INFO] Reading cached asset graph completed, took 246ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Running build completed, took 58ms
[INFO] Caching finalized dependency graph completed, took 159ms
[SEVERE] Unhandled build failure!
FileSystemException: Cannot create file, path = '...\out/2019-08-07T11:29:25.601099' (OS Error: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
, errno = 123)
[SEVERE] Failed after 253ms
```

The exception is in German, but more or less means that the file path contains invalid characters. In this case it's the colon `:` in the date format which isn't allowed on Windows. For better Windows compatibility you could use a different separator in the date format.

However as a workaround, you can use `--track-performance` together with `serve` to view the performance at the `/$perf` endpoint. That you UI is really nice!

*Additional info:*
* Dart SDK Version: Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"
* build_runner version: 1.6.5

**Comment by jakemac53** [comment]
This should be fixed now (the invalid characters part at least, the path still seems a bit wonky so feel free to file a new issue or comment here if you still have problems).

Also note that while this adds logging it is in a somewhat incomplete state - we don't provide any way of viewing those performance logs etc. If you wanted to contribute here that would likely be welcome.

If you want to dig into and parse these logs they are produced by the `timing` package, so you can deserialize them using those classes to create your own UI or whatever you like. If you come up with anything cool let us know!

**Comment by jakemac53** [comment]
Actually sorry I was slightly wrong, to deserialize the logs you would want to use our `BuildPeformance` class here https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/performance_tracker.dart#L21. I forgot we wrap up the timings objects in a few more layers.

**Comment by Fox32** [comment]
Thanks for fixing this that fast.
I currently have no further plans to use that output, as the UI on the serve mode is sufficient for me. The UI isn't fast and gets a bit tiny when the build duration takes a minute, but gives a lot of insights in what happens with my builders. Maybe a standalone version of the UI that allows to load the log files would be nice.

**Comment by jakemac53** [comment]
Ya - I think a standalone version would be good for sure. This logging feature was originally written just for that so that people could send us logs but we have never actually used it thus we haven't implemented the viewing feature even though it should be trivial haha.
