### ISSUE TITLE
Ddc: Consider using summaries as input 

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/build#240]
We could feed the `build` with summaries too for the DDC use case in order to provide an analysis context that takes into account prebuilt libraries too.

**Comment by jakemac53** [comment]
Fwiw this should be coming soonish, once the globbing apis are stabilized we should be able to deliver a DDC builder and that can also output summaries.

**Comment by jakemac53** [comment]
Although to be clear it wouldn't be feeding the build with summaries as much as actually producing summaries as a part of the build, but that is a minor distinction ;).

**Comment by dam0vm3nt** [comment]
cool!

**Comment by matanlurey** [comment]
I believe this is the case as-of HEAD right now:

https://github.com/dart-lang/build/blob/master/build_compilers/lib/src/dev_compiler_builder.dart#L60.

Please re-open if I'm mistaken!
