### ISSUE TITLE
InMemoryAssetReader#findAssets should support non-lib assets

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#241]
i.e.

```dart
reader.findAssets(new Glob('test/*.dart'))
```

If not, `InMemoryAssetReader` has a bug. Willing to fix, just checking in.

**Comment by natebosch** [comment]
findAssets() should not be limited to lib/ in the 'root' package.

**Comment by matanlurey** [comment]
Ack. Changing this to a bug, I can help fix this.

**Comment by matanlurey** [comment]
Ugh this is just my confusion around lib/ again. I'll add a test anyway though.
