### ISSUE TITLE
findAssets can't find files outside of lib/ folder for aggregate builders

### ISSUE THREAD

**Issue by comigor** [dart-lang/build#2426]
Hey there!

I'm trying to create an aggregate builder, but it appears that I can't find any asset but `pubspec.*` outside `lib/` folder, regardless of what [this test](https://github.com/dart-lang/build/blob/db7af3d9868e84c554ed93314df5469ad5e9c142/build_test/test/test_builder_test.dart#L53-L74) says.

I've created a minimal reproduction repository with the exact same code as the test pointed above, but the output is empty! https://github.com/comigor/repro_aggregate_builder

Is there any other configuration that need to be done to work with `$lib$` synthetic input?

* Dart SDK Version: 2.4.0 @ macOS
* `build: ^1.1.4`
* Builder: https://github.com/comigor/repro_aggregate_builder

**Comment by comigor** [comment]
Okay, answering my own question (after taking a look at the code): you need to whitelist the folders you want to be processed on `build.yaml` file:
```
targets:
  $default:
    sources:
      - lib/**
      - data/**
```

If you don't do this, by default it will consider only [some inputs](https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/options.dart#L21-L31).

**Comment by jakemac53** [comment]
Correct, this is to avoid accidentally including build output directories and hidden directories etc. Fwiw we derived the default include list from the [package layout conventions](https://dart.dev/tools/pub/package-layout) page (to be clear it is fine if you use other directories, it will just require explicit config as you discovered).

**Comment by comigor** [comment]
That's good to know! Thanks for pointing this to me!
