### ISSUE TITLE
Parsing and resolving a Dart source from string

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#2431]
## Scenario
I'm writing a builder that generates Dart classes from `CREATE TABLE` sql statements. I'd like to provide a convenience feature that let's users store complex Dart objects in columns if they provide a mapping function to and from something that can be stored in SQL (e.g. strings). For those scenarios, I need to resolve the type of Dart expressions. For instance, given two files ("input.moor" and "mapper.dart") defined like this:
```sql
-- input.moor
import 'mapper.dart';
CREATE TABLE test (
  blob TEXT MAPPED BY `const MyMapper()`
);
```
and 
```dart
// mapper.dart
import 'package:moor/moor.dart';

class MyMapper extends TypeConverter<MyFancyObject, String> {
  // contains methods to map an instance of MyFancyObject from and to String
}
```

I would like to generate a class that has a `final MyFancyObject blob;` field. To know the appropriate type of that field, I need to obtain the `DartType` of the `const MyMapper()` expression declared in the imported file.

## Problem
I couldn't find a way to parse expressions or infer their type via the analysis apis exposed by a build step or the resolver. I considered creating a fake Dart file that contains the relevant import statements and declares a variable like `var expr = $expressionToParse;`. I could then get the static type of that variable using a resolved library parsed by the analyzer.

I'm aware of functions like `parseString` from the analyzer, but those can't resolve imported files in a string source. Ideally, I'd also like to use the same analysis driver that the build step already uses. Can the build package expose an API to enable this?

**Comment by jakemac53** [comment]
I don't think there is any api available to parse an arbitrary expression and resolve it.

**Comment by simolus3** [comment]
Yeah my plan was to create a "fake file" that looks like
```dart
import 'mapper.dart';
// Other import statements

var expr = {expression string to resolve};
```
Resolve that, and then read the type from the `expr` variable. The test package is doing [something similar](https://github.com/dart-lang/test/blob/efe2d60f127a4ba6788e606fbe4d7953773b1a6d/pkgs/test/test/util/string_literal_iterator_test.dart#L243), but that api doesn't work for fake code with import statements. I assumed that the build package could help here as it seems similar to what `resolveSources` in the `build_test` package is doing.

**Comment by natebosch** [comment]
You might get the best leverage by writing an intermediate file (with `build_to: cache`) and then using it as the primary input for the next step - from there the Resolver should work.

I think we are unlikely to try to add more facilities around resolving from a String.

**Comment by simolus3** [comment]
Thank you for the suggestions, I will try that!

**Comment by simolus3** [comment]
> using it as the primary input for the next step

Is there a reason this doesn't work when performed in a single build step (apart from #493)? The following snippet throws (as expected)
```dart
await buildStep.writeAsString(tempAssetId, 'void main() {}');
await buildStep.resolver.libraryFor(tempAssetId);
```

But do you see any problems (apart from the referenced issue) that could cause this to fail? Making my generator work across an arbitrary number of build steps requires significant work which I would like to avoid, if possible.

**Comment by natebosch** [comment]
> But do you see any problems (apart from the referenced issue) that could cause this to fail?

We disallow reading any Asset which is an output of the current phase. I think you'd also be unable to do `buildStep.readAsString` immediately following a `buildStep.writeAsString` for any given asset. We could consider loosening that restriction for the outputs of the _specific_ build step that emitted them (we'd still restrict reading the outputs of any other steps in the same phase). I'm not sure how that might impact our attempts at preserving hermetic builds, there are already holes that can introduce non-hermetic builds through misuse of the Resolver, but I can't quite decide if this would make that worse.

**Comment by simolus3** [comment]
Thanks for the explanation!

> We disallow reading any Asset which is an output of the current phase

Are there any docs on build phases I can read? I only found the `build_runner_core/lib/src/generate/phase.dart` file which indicates that each regular builder gets its own phase, and then there's another phase for the whole post-processing step. Is that correct?

> I'm not sure how that might impact our attempts at preserving hermetic builds

In my use case the flow would be like this

1. builder creates `.temp.dart` asset
2. same builder resolves that asset
3. a post processing builder deletes `.temp.dart` assets

I can't see how that would have an impact on hermetic builds, or how that api could be misused. Are directives like `import`, `part` or `export` reflected in the build graph when resolved?

> there are already holes that can introduce non-hermetic builds through misuse of the Resolver

Forgive my ignorance, but there will always be some holes, right? I mean builders could just read inputs via `File.readAsString`, roll their own caching graph, pass asset files to external tools etc. There's always some level of "hey build authors, please stick to the rules or the build will break" that the build system can't enforce programmatically.

I can understand if there's a concern with loosening that restriction, but should I open another issue as a feature request where this could be discussed? I'm afraid this closed issue might get lost.

**Comment by jakemac53** [comment]
> Are there any docs on build phases I can read? I only found the `build_runner_core/lib/src/generate/phase.dart` file which indicates that each regular builder gets its own phase, and then there's another phase for the whole post-processing step. Is that correct?

There is actually a phase for each builder + target combination (by default a target is a whole package). Builders are applied to packages "bottom up" - so with the exception of package cycles they always run on your dependencies before you.

> and then there's another phase for the whole post-processing step

Yes there is a single post processing phase. Post processing builders are extremely limited - they are basically only meant to support extracting archive files that were output from previous phases which couldn't declare all their outputs ahead of time.

**Comment by jakemac53** [comment]
> I can't see how that would have an impact on hermetic builds, or how that api could be misused. Are directives like `import`, `part` or `export` reflected in the build graph when resolved?

I can't think of anything specific here that would cause a problem. We could likely allow this. The implementation might get a bit wonky - we would need to make sure and not track that output as an  input (otherwise it would be an input to itself). Also the resolver would have to be re-initialized, we would need some special logic here.

It might also limit our ability to change the resolver implementation in the future.

**Comment by jakemac53** [comment]
> I can understand if there's a concern with loosening that restriction, but should I open another issue as a feature request where this could be discussed? I'm afraid this closed issue might get lost.

I think it would be fair to open an issue about specifically allowing reading of an asset that you output previously in the current phase.

Just to be transparent we are very focused supporting flutter_web specifically right now, and would not likely have time to spend on this ourselves for a while. However, we do accept pull requests if you would like to work on this to get something sooner.

**Comment by simolus3** [comment]
Thank you so much for all the insights! I can fully understand that you have other priorities - I've opened an issue and I'll try to work on that.
