### ISSUE TITLE
Promote log record matchers to pkg:test or pkg:matcher?

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2443]
I just discovered the `recordLogs()` util as well as the LogRecord matchers in pkg:build_test, which are awesome! Has there been any thought to exporting those somewhere else like pkg:test or pkg:matcher or maybe even a new package specifically for testing `Logger`? The stream matchers that exist make it _pretty_ easy to test loggers, but having the specific log record matchers makes the tests more readable IMO, and they provide better error descriptions.

```dart
      expect(
          Logger.root.onRecord,
          emitsThrough(predicate<LogRecord>((record) =>
              record.message.contains('test/template.html') &&
              record.level == Level.SEVERE)));
      await testBuilder(...);
```

```dart
      final logs = recordLogs(() => testBuilder(...);
      expect(
          logs,
          emits(severeLogOf(allOf(
            contains('template must contain a `{test}`'),
            contains('test/template.html'),
          ))));
```

**Comment by jakemac53** [comment]
The `test` and `matcher` packages are probably not the right place, those packages don't currently have a dependency on `logging` and they generally shouldn't contain matchers that are specific to certain packages.

It is also definitely weird to have these live in `build_test`.

I suppose the "correct" thing to do would be to create a `logging_test` package or something but that feels like overkill?

**Comment by evanweible-wf** [comment]
Yeah, I agree that it feels overkill to have its own test package, _but_ it's probably one of the most commonly used packages which seems like a decent justification.

**Comment by jakemac53** [comment]
This is definitely a case where "package features" would be perfect if we had actually landed that...

**Comment by jakemac53** [comment]
@natebosch wdyt? logging_test package?

**Comment by natebosch** [comment]
The matchers could reasonably be moved to a `package:logging_test`, the `recordLogs` function is specific to `package:build` and can't be moved.

**Comment by jakemac53** [comment]
I don't think we plan on doing this at this. I think the value isn't worth the maintenance cost for us. I would recommend copying them into your own project and using them.
