### ISSUE TITLE
 NoSuchMethodError: The getter 'references' was called on null.

### ISSUE THREAD

**Issue by Darshan0** [dart-lang/build#2474]
* Dart SDK Version :Dart 2.5.0 
* Plugin Issue : build_runner 1.7.1
* OS : Linux (Ubantu) 

Trying to generate a .g.dart file using the dev dependencies json_serializable 
on i run the command   "flutter packages pub run build_runner watch"
i got this error on my terminal .

NoSuchMethodError: The getter 'references' was called on null.
Receiver: null
Tried calling: references
dart:core                                                         Object.noSuchMethod
package:analyzer/src/summary2/linked_bundle_context.dart 22:47    new LinkedBundleContext
package:analyzer/src/dart/analysis/library_context.dart 407:11    LibraryContext._createElementFactory
package:analyzer/src/dart/analysis/library_context.dart 94:7      new LibraryContext
package:analyzer/src/dart/analysis/driver.dart 1439:29            AnalysisDriver._createLibraryContext
package:analyzer/src/dart/analysis/driver.dart 1380:28            AnalysisDriver._computeUnitElement.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1378:20            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 997:34             AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 1931:24            AnalysisDriverScheduler._run
package:analyzer/src/dart/analysis/driver.dart 1865:5             AnalysisDriverScheduler.start
package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 193:19        BuildOptions.create
package:build_runner/src/generate/watch_impl.dart 71:36           watch
package:build_runner/src/generate/build.dart 159:5                watch
package:build_runner/src/entrypoint/watch.dart 31:25              WatchCommand.run
package:args/command_runner.dart 197:27                           CommandRunner.runCommand
package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
dart:async                                                        new Future.sync
package:args/command_runner.dart 112:14                           CommandRunner.run
package:build_runner/src/entrypoint/run.dart 24:31                run
.dart_tool/build/entrypoint/build.dart 22:22                      main

pub finished with exit code 1

after this i ran this command "flutter packages pub run build_runner watch --delete-conflicting-outputs"

and ended up getting this error :

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

FileSystemException: Failed to watch path, path = '/home/darshan/Work/taglink-flutter-app/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/taglink/0/lib/screens/List' (OS Error: No space left on device, errno = 28)
dart:isolate  _RawReceivePortImpl._handleMessage

**Comment by jakemac53** [comment]
These look like two separate issues, the first would probably be resolved by updating your `build_resolvers` dependency (using `pub upgrade`). We got broken recently by a change in analyzer but a fix has been published.

For the 2nd issue how large is your `.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache` directory? How much available space is on your machine?

**Comment by Darshan0** [comment]
pub upgrade did fix my first issue , 
for the 2nd issue  i ran this command
echo 1048576 > /proc/sys/fs/inotify/max_user_watches 


Thank you
