### ISSUE TITLE
build_web_compilers is still using analyzer-ddc version of dart_sdk.js

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/build#2483]
repro:
```sh
git clone git@github.com:davidmarne/built_redux.git
cd built_redux
pub get
pub run build_runner build --release --delete-conflicting-outputs test
```

This test started failing with ce6f40b, went away with the revert, but reappeared with the second attempt to land the change in a6cc7b9

In terms of dev releases, 2.6.0-dev.2.0 is the first dev release that has this breaking change

**Comment by natebosch** [comment]
@nshahan pointed this out to me yesterday. I fixed in https://github.com/dart-lang/build/pull/2481 and @jakemac53 published this morning. This should be fixed with a `pub upgrade`.

>  Do we need a fix for flutter as well?

I think the flutter SDK only had the kernel version of the files. We should double check.

**Comment by nshahan** [comment]
@natebosch There was some investigation done by @vsmenon and it sounded like Flutter should be fine since they are bundling their own version of the SDK that they rebuilt (using DDK).

**Comment by vsmenon** [comment]
Thanks!  I verified the repro from @greglittlefield-wf works after a `pub upgrade`.

I looked at my flutter build.  I only see kernel versions under the built `flutter_web_sdk`.

**Comment by davidmarne-wf** [comment]
So it doesn't appear that updating to build_web_compilers 2.6.1+ fixed the issue with built_redux running `pub run build_runner test --release --delete-conflicting-outputs -- -p chrome`.

@sigmundch you said,

> Note that this is without --release. If you use --release there are different runtime errors. I checked and those errors are not new (old versions of the sdk also show the same errors).

Did the issue of running tests on dart2js get conflated with an issue running tests with DDC (the latter of which nate's pr to build_web_compilers addressed)?

Should we open another issue for the issue presented when running tests with the release flag?

**Comment by sigmundch** [comment]
@davidmarne-wf yes, indeed, they got conflated in an earlier bug and I accidentally pasted `--release` here on the first comment.

Nate's PR should have addressed the DDC tests.

We may need your help to let us know if the `--release` test failures are due to an issue on our side or if the test themselves need to be updated. Because I saw the same errors on the older SDKs (like 2.4.1, which I believe is what your team is currently using), I thought it is most likely the latter? If you believe the issue is on our side, please do open a bug for us under the sdk repo.

Cheers!

**Comment by davidmarne-wf** [comment]
cool, i create https://github.com/dart-lang/sdk/issues/38927

> We may need your help to let us know if the --release test failures are due to an issue on our side or if the test themselves need to be updated. Because I saw the same errors on the older SDKs (like 2.4.1, which I believe is what your team is currently using.

I can only assume its something on your side that needs to be fixed. Even if the bug was introduced prior to 2.4.1, it still seems like it is an issue that dart2js should address since the code is clearly syntactically correct and it passes in ddc and the dart vm.
