### ISSUE TITLE
Builder ordering appears to be different on windows

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2487]
When adding windows bots for all our unit tests I had to skip the `_test/test-generated_script_integration_test.dart`, it looks like it is ordering build_web_compilers before build_vm_compilers when the opposite is expected.

**Comment by natebosch** [comment]
These packages are not dependencies of eachother and so they can be ordered in either way. It's likely that we never handled making those cases explicit. Since an arbitrary ordering should be fine I will look at whether we should go in alpha order.

**Comment by jakemac53** [comment]
Ya that makes sense that the ordering isn't defined, but we should try and make it consistent. Otherwise we could get hit some really weird edge cases that are difficult to reproduce.

For these particular builders it shouldn't matter I am more concerned about the general case.
