### ISSUE TITLE
Clarification on cache vs source

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2497]
We maintain a [builder for the `over_react` package](https://github.com/Workiva/over_react/blob/master/build.yaml#L1-L7) and it is currently configured to build to cache. Its primary use is to generate code for components in `lib/` that are then published to a pub server.

We had a discussion about cache vs source for this builder back in February, and opted to continue building to cache. We're now having the discussion again due to some pain points that we're hitting. Before we go any further, I wanted to get some clarification. The documentation for deciding between cache and source is currently this:

> ## When should a Builder build to `cache` vs `source`?
>
>Outputs to `source` will generally be published with the package on pub. **This
can be risky.** If the generated code depends on _any_ details from the current
pub solve - that is it reads information from dependencies - then a consumer of
the package which has different versions of dependencies in their pub solve
**may be broken**. If the generated code imports any libraries, including from
the package providing the builder, it must only use the API surface area which
is guaranteed to not break without a major version bump.
>
>Outputs to `cache` will never be published with the package, and if they are
required to compile or run, then the build system must be used by every consumer
of the code. **This is always safe**, but may place limitations on the end user.
Any outputs which are used _during_ a build to produce other outputs, but don't
need to be compiled or seen by the user, should also be built to `cache`.

Looking at just that guidance, the build-to-cache option looks like the better option. Build-to-source is framed as risky and requiring careful implementation by the builder authors, whereas build-to-cache is framed as safe, but with the caveat that it passes the build system dependency onto all consumers (if the outputs are required in order to compile/run).

That caveat is currently the source of our pain points, although it's mainly exacerbated by the fact that our builder generates some of the public API members which means that a build is required for the code to be statically analyzable/complete (not just for it to compile/run). If we were to fix that by only having the builder generate implementation code and using `// ignore:` comments to the references to generated symbols, is it accurate to say that build-to-cache is a valid and potentially better approach even for code published to pub?

**Comment by natebosch** [comment]
> is it accurate to say that build-to-cache is a valid and potentially better approach even for code published to pub?

What do you mean by "code" in this sentence?

If you mean "the generated code" this should always build to source. I'm not sure what the publish process would be otherwise? Even if a process was established all the risks come from the fact that the code is published, so building to cache then publishing it anyway won't mitigate any risk.

If you mean "other code in a package that references the generated code" then it could go either way. There is code in `package:angular` that refers to `.template.dart` files that don't exist until build time, and doesn't require any `// ignore:` for a good UX for end users. If end users need to refer to symbols from generated code, then they'll see the errors until their first build.

**Comment by evanweible-wf** [comment]
Yeah, in re-reading that sentence I see that it was confusing, since in the case of build to cache we obviously aren't publishing it.

We currently have our over_react builder configured to build to cache and auto-apply to all dependents. Then we publish our packages that leverage the over_react builder with the assumption that in order to consume them, a build must be run. That part seems to align with this part of the cache vs source guidance:

> Outputs to cache will never be published with the package, and if they are
required to compile or run, then the build system must be used by every consumer
of the code. This is always safe, but **may place limitations on the end user.**

..where the limitation on the end user is the requirement to run a build.

That angular example sounds like what we would end up with assuming we can fix our issue of having public API members generated by the builder. End users would be able to reference component APIs from dependencies, they just wouldn't have their implementations filled out until a build is run.

**Comment by natebosch** [comment]
You might end up with trouble around using `dartanalyzer` CLI vs the analysis server. The analysis server should understand the generated cache directory, but I think the CLI doesn't. So depending on where you are looking for errors you might see some even after a build.

To give more clarity on the risks, a lot of it comes down to how breaking changes are surfaced. We've seen that some builder authors use patterns where they rely on the _generated_ code only being built against the _builder package_ at the same version used to generate.

For a really simple example, imagine the generated code is a library that has its own imports, and it imports from `lib/src` on the builder package.

Private library in the package that has the builder:

```dart
// my_builder/lib/src/helpers.dart
String toStringHelper(Foo foo) => '${foo.name}';
```

Generated files look like:

```dart
// some_users.generated.dart
import 'package:my_builder/src/helpers.dart';

class SomeClass implements Foo {
  String get name => 'Some generated name';

  @override
  String toString() => toStringHelper(this);
}
```

We might want to rename `toStringHelper` or add another argument or something... We _can_ do that if we were `build_to: cache` - the version of the code generated always matches the version of the package we build with (and we didn't consider that API as public). If we were `build_to: source` and there are generated files published on pub, we _can't_ do a breaking change in `toStringHelper` even though it's not public to any code other than our generated code.

**Comment by evanweible-wf** [comment]
Thanks for the info @natebosch, that helps! I'm going to close this for now.
