### ISSUE TITLE
build_web_compilers fails without lib/ in sources

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/build#2531]
**pubspec.yaml**
```yaml
dev_dependencies:
    build_runner: '^1.7.2'
    build_web_compilers: '^2.7.1'
```

**build.yaml**
```yaml
targets:
  $default:
    sources:
      - "web/**"
```

```
> dart --version
Dart VM version: 2.6.0-dev.8.2 (Thu Oct 24 09:35:58 2019 +0200) on "windows_x64"

> pub run build_runner build
[INFO] Generating build script completed, took 290ms
[INFO] Creating build script snapshot... completed, took 11.3s
[INFO] Building new asset graph completed, took 1.0s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] build_web_compilers:ddc_modules on web/main.dart:

NoSuchMethodError: The getter 'modules' was called on null.
Receiver: null
Tried calling: modules
[SEVERE] build_web_compilers:entrypoint on web/main.dart:

AssetNotFoundException: demo|web/main.ddc.module
[INFO] Running build completed, took 572ms
[INFO] Caching finalized dependency graph completed, took 122ms
[SEVERE] Failed after 705ms
```

Adding `"lib/**"` to `sources` in `build.yaml` fixes the build, although the folder does not exist.

**Comment by jakemac53** [comment]
This is because of the synthetic `lib/$lib$` source file. The module builders require this to be available.

**Comment by lexaknyazev** [comment]
Could `build_config` auto-insert it at runtime?

**Comment by jakemac53** [comment]
We could hack it so those synthetic nodes always exists but it would mean users wouldn't be able to exclude those sources and it would cause worse problems. For instance you would essentially never be able to create more than one target without having duplicate sources between them which will cause overlapping output errors.

**Comment by lexaknyazev** [comment]
Thanks for the clarification. I guess the best short-term solution here is to improve the error message then.

**Comment by kuhnroyal** [comment]
@jakemac53 After updating to build_runner 1.9.0 I get the warning that the `$package$` source is missing. How do I fix this? I added `$package$` to the sources which silences the warning but I doubt this is the correct way.

**Comment by jakemac53** [comment]
That is actually the correct way - its just a bit weird. This makes it be treated as an input for your package which allows builders to run using it. That is just a special file, what we call a "placeholder", which builders that run on an entire package can use as their primary input.

**Comment by kuhnroyal** [comment]
Thanks for the explanation. It would be great if there was a way to add sources in `build.yaml` instead of overwriting it. Would make this a bit easier.

Do I have to add `lib/$lib$` when I have `lib/**` in the sources?

**Comment by jakemac53** [comment]
> Do I have to add `lib/$lib$` when I have `lib/**` in the sources?

No - because that glob matches that "file" :)
