### ISSUE TITLE
support passing VM flags to subprocesses

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/build#2543]
Users would like to be able to plumb VM flags to subprocesses. The main motivating example at this time is to specify a different `--old-gen-heap-size` to the VM when invoking dart2js to prevent OOM errors. See https://github.com/dart-lang/sdk/issues/27883 for an example

@jakemac53 - not sure if this is the right repo to track this?

**Comment by jakemac53** [comment]
It should be done with an environment variable, so only `build` will have to know about it.

**Comment by jakemac53** [comment]
How do we want to support passing multiple arguments here? separate by commas or...?

**Comment by jakemac53** [comment]
Actually I will just go with space separated args

**Comment by jakemac53** [comment]
planned name for the environment variable is `BUILD_DART2JS_VM_ARGS`

**Comment by jakemac53** [comment]
This has been publish in build_modules 2.7.0. Multiple arguments can be provided by separating them with spaces.

**Comment by robbecker-wf** [comment]
Thanks! Can confirm this does in fact get `--old-gen-heap-size` through to dart2js when running webdev.
