### ISSUE TITLE
using both built value and json serializable and hit this issue

### ISSUE THREAD

**Issue by shriharip** [dart-lang/build#2557]
* Dart SDK Version (`dart --version`) 
Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "macos_x64"

Flutter 1.12.6 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 6eb0a0e371 (17 hours ago) • 2019-11-20 20:18:51 -0500
Engine • revision 6bf311f1d6
Tools • Dart 2.7.0

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
build_runner: ^1.7.2

  * _If you are not sure, try checking your `pubspec.lock` file._
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
json_serializable: ^3.2.3
built_value

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOS Mojave v 10.14.6

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* Any other packages or constraints we should know about
Flutter channel dev. since build runner is having problem with version and sdk .

Missing some or all of the above might make the issue take longer or be impossible to act on.

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
package:analyzer/src/summary/link.dart 5568:5                     TypeProviderForLink._buildInterfaceType
package:analyzer/src/summary/link.dart 5533:23                    TypeProviderForLink.objectType
package:analyzer/src/summary/link.dart 926:67                     ClassElementForLink_Class._computeInterfaceTyp
e
package:analyzer/src/summary/link.dart 824:27                     ClassElementForLink_Class.supertype
package:analyzer/src/task/strong_mode.dart 303:33                 InstanceMemberInferrer._inferClass
package:analyzer/src/task/strong_mode.dart 335:9                  InstanceMemberInferrer._inferClasses
package:analyzer/src/task/strong_mode.dart 56:5                   InstanceMemberInferrer.inferCompilationUnit
package:analyzer/src/summary/link.dart 1640:7                     CompilationUnitElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3870:12                    LibraryElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3570:15                    LibraryCycleNode.link
package:analyzer/src/summary/link.dart 3510:7                     LibraryCycleDependencyWalker.evaluate
package:analyzer/src/summary/link.dart 2226:13                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2192:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2245:18                    DependencyWalker.walk
package:analyzer/src/summary/link.dart 3543:42                    LibraryCycleForLink.ensureLinked
package:analyzer/src/summary/link.dart 4075:35                    Linker.link
package:analyzer/src/summary/link.dart 312:74                     _relink
package:analyzer/src/summary/link.dart 126:3                      link
package:analyzer/src/dart/analysis/library_context.dart 220:25    LibraryContext.load.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/library_context.dart 219:12    LibraryContext.load
package:analyzer/src/dart/analysis/library_context.dart 98:7      new LibraryContext
package:analyzer/src/dart/analysis/driver.dart 1429:29            AnalysisDriver._createLibraryContext
package:analyzer/src/dart/analysis/driver.dart 1377:26            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 997:34             AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 1921:24            AnalysisDriverScheduler._run
package:analyzer/src/dart/analysis/driver.dart 1855:5             AnalysisDriverScheduler.start
package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 192:19        BuildOptions.create
package:build_runner/src/generate/build.dart 85:36                build
package:build_runner/src/entrypoint/build.dart 28:24              BuildCommand.run
package:args/command_runner.dart 197:27                           CommandRunner.runCommand
package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
dart:async                                                        new Future.sync
package:args/command_runner.dart 112:14                           CommandRunner.run
package:build_runner/src/entrypoint/run.dart 24:31                run
.dart_tool/build/entrypoint/build.dart 26:22                      main

**Comment by jakemac53** [comment]
You need to `pub upgrade` (or `flutter pub upgrade`) to get the latest build_resolvers package (this is a transitive dep so it does not need to appear in your pubspec)
