### ISSUE TITLE
Unused Imports Cause Unnecessary DDC Module Dependencies

### ISSUE THREAD

**Issue by todbachman-wf** [dart-lang/build#2558]
When compiling code with DDC it appears unused imports will affect the structure of the modules that are generated. I would not have expected that to be possible. On some of our larger code bases we've found that can negatively impact the incremental rebuild times. Obviously we could make the analyzer shout at us any time we introduce an unused import, but it might be nice if the build system just didn't create these unnecessary dependency in the first place.

Here's an example repo demonstrating the problem: https://github.com/todbachman-wf/modules_with_unused_imports

### My Environment:
* Dart SDK Version: 2.6.1
* Build packages used:
  * build: 1.2.2
  * build_config: 0.4.1+1
  * build_daemon: 2.1.0
  * build_modules: 2.7.0
  * build_resolvers: 1.2.1
  * build_runner: 1.7.2
  * build_runner: 4.2.0
  * build_test: 0.10.10
  * build_web: 2.7.1
* MacOSX

**Comment by natebosch** [comment]
When we build up the module structure we do so without doing a full resolve of the Dart code. Adding a full resolve would make things considerably slower - especially if no other builders were involved that did a resolve.

The most straightforward behavior, in my opinion, is to base modules off of imports as written. Silently ignoring certain imports feels strange to me.

**Comment by natebosch** [comment]
> Obviously we could make the analyzer shout at us any time we introduce an unused import

I'd highly recommend following this approach. The analyzer should give you a hint by default, and you can upgrade it to a warning or error. Internally we disallow unused imports from getting checked in.


Closing for now since I don't think there is anything we can do about the module structure without tanking performance.
