### ISSUE TITLE
Rename hasInput

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#256]
The distinction between 'input' and 'primaryInput' is not drastic enough - some authors seem to get confused about what they are allowed to read etc.

We should name it `hasAsset` or `canRead` or similar.

Will want to deprecate the current version and leave it in for a while.

**Comment by jakemac53** [comment]
I like `exists`, as it maps to regular `File` apis.

**Comment by natebosch** [comment]
I would agree if it was something like AssetId.exists... but `buildStep.exists(someAssetId)` looks strange to me.

**Comment by natebosch** [comment]
We still have a hasInput for now on BuildStep, marked as deprecated. Will remove in next breaking release.
