### ISSUE TITLE
pub run build_runner test returning exit code 0 with failed tests

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/build#2562]
Example CI run: https://cirrus-ci.com/task/6172341138096128

Test script is: https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L554

Dart Version: Dart 2.7.0 (build 2.7.0-dev.2.1 413867d678)

Versions:
  - test: 1.9.4
  - build_runner: 1.7.2
  - build_vm_compilers: 1.0.4
  - build_test: 0.10.10

**Comment by jonahwilliams** [comment]
This can be seen in the PR https://github.com/flutter/flutter/pull/46140 if https://github.com/flutter/flutter/pull/46140/files#diff-a9d73960c607f511d218217af489e4d5L39 is changed back to true.

**Comment by jonahwilliams** [comment]
FYI @jakemac53

**Comment by jakemac53** [comment]
Do you know if this is only happening on windows?

Or is it possibly related to https://github.com/flutter/flutter/pull/46210?

**Comment by jakemac53** [comment]
@jonahwilliams

**Comment by jakemac53** [comment]
My current assumption is this is related to that issue and the process was exiting manually with a zero exit code - going to assign to you to close if you agree or re-assign to me if you think this needs further investigation.

**Comment by jonahwilliams** [comment]
Yes, it was the same issue. Sorry for the trouble!

**Comment by jakemac53** [comment]
No worries - glad we got it resolved :).
