### ISSUE TITLE
request to add Flutters assets folder to root whitelists

### ISSUE THREAD

**Issue by maks** [dart-lang/build#2571]
It would be useful if Flutters `assets` folder could be added to the [existing root package sources whitelist](https://github.com/dart-lang/build/blob/935dba607fe3634d5fc66264a9e24ee578debf3e/build_runner_core/lib/src/generate/options.dart#L23-L34) as other domain sepecific ones wuch as `web` are already included.

**Comment by jakemac53** [comment]
This seems quite uncontroversial I can go ahead and start work on it
