### ISSUE TITLE
build-filter does not work with multiple file extensions

### ISSUE THREAD

**Issue by maxlapides** [dart-lang/build#2580]
I have a very large project and I am trying to reduce the build time. I thought I would try to rename all of the files that have a `.g.dart` generated part something like `myfile.built.dart` and then use the `build-filter` argument to build only files named `*.built.dart`. Unfortunately, this doesn't work. It always produces no output:

```
❯ pub run build_runner build --delete-conflicting-outputs --verbose --build-filter="**.built.dart"
[INFO] Generating build script completed, took 333ms
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 61ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 565ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 11ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 36ms

[INFO] Build:Succeeded after 58ms with 0 outputs (0 actions)
```

That result is from a fresh project with just a few files. Note that `--build-filter="**.dart"` does work as expected:

```
❯ pub run build_runner build --delete-conflicting-outputs --verbose --build-filter="**.dart"
[INFO] Generating build script completed, took 325ms
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 62ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 570ms

[INFO] Build:Running build...
[INFO] Heartbeat:1.1s elapsed, 0/5 actions completed.
[FINE] built_value_generator:built_value on lib/models/demo_struct1.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/models/models.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/internals.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/main.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/models/demo_struct2.built.dart:Running BuiltValueGenerator
[INFO] Build:Running build completed, took 1.7s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 36ms
```

Environment:

```
❯ dart --version
Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "macos_x64"
```

pubspec.yaml:

```
name: build_demo
description: Build Demo

dependencies:
  built_value: ^7.0.0

dev_dependencies:
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
```

**Comment by jakemac53** [comment]
@maxlapides Is your builder listed as `optional` in the `build.yaml` builders section?

Build filters don't force optional builders to run. You could try making your builder not be optional, but what I would actually suggest is simply passing the application that you want to build as a build filter. This will still build all of its optional inputs (anything required to build the application will be built).

**Comment by maxlapides** [comment]
@jakemac53 I do not have a `build.yaml` file. I created a minimum reproduction case to demonstrate the issue: https://github.com/maxlapides/dart_build_issue_2580. You can test out the issue:

1. Run `pub run build_runner watch --verbose --build-filter="**.dart"` and then save a change to `demo_struct.build.dart`. This works as expected:

```
[INFO] Watch:------------------------------------------------------------------------

[INFO] Watch:Starting Build

[INFO] Build:Updating asset graph...
[INFO] Build:Updating asset graph completed, took 7ms

[INFO] Build:Running build...
[FINE] built_value_generator:built_value on lib/main.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/demo_struct.build.dart:Running BuiltValueGenerator
[INFO] Build:Running build completed, took 98ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 16ms

[INFO] Build:Succeeded after 124ms with 2 outputs (3 actions)
```

1. Run `pub run build_runner watch --verbose --build-filter="**.build.dart"` and then save a change to `demo_struct.build.dart`. This does NOT work as expected:

```
[INFO] Watch:------------------------------------------------------------------------

[INFO] Watch:Starting Build

[INFO] Build:Updating asset graph...
[INFO] Build:Updating asset graph completed, took 4ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 0ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 13ms

[INFO] Build:Succeeded after 21ms with 0 outputs (0 actions)
```

As you can see above, that build produced no output. The intention of filing this bug is to point out that **this glob pattern is not recognized, when I believe it should be**.

Regardless of whether this is the best solution to my problem, I believe this is a bug that should be fixed. However, I am interested to discuss the best solution to my problem. You said:

> what I would actually suggest is simply passing the application that you want to build as a build filter. This will still build all of its optional inputs (anything required to build the application will be built).

The issue that I am having is I have a very large project with lots of built_value files scattered around the project. I have been trying to clean up the dependency tree of the project, but it is still very large and very complex. As a result, saving some files can result in very expensive incremental builds. I believe a simple solution, at least as a stop-gap, would be to apply a build filter to ONLY build the files that actually require code generation.

**Comment by jakemac53** [comment]
The `--build-filter` argument specifies the _outputs_ that you want to build - not the _inputs_ like what you are trying to do.

For your case the actual generated output is a `.build.g.dart` file so you could try that filter `--build-filter=**.build.g.dart`.

**Comment by maxlapides** [comment]
Oh okay that makes a lot of sense! Thanks so much for the explanation. I think that resolves this issue :)
