### ISSUE TITLE
Builder use too much memory when compiling web entrypoints 

### ISSUE THREAD

**Issue by svarl** [dart-lang/build#2583]
```
Dart sdk 2.4.0

webdev 2.5.1
build_runner 1.6.4
build_web_compilers 2.4.1
```

We have a project with a few dart entrypoints. So during the build process, the builder start dart2js compilation in parallel. Dart2js processes use a lot of memory and cause oom exception. 

How to limit the max number of parallel dart2js processes? Can you add ability to do this?
_NB:_ build_runner `--low-resources-mode` flag doesn't work for us.

**Comment by natebosch** [comment]
You can set the `BUILD_MAX_WORKERS_PER_TASK` environment variable.

I'll leave this issue open to track adding something to our FAQ about this.

**Comment by svarl** [comment]
Thanks for the help
