### ISSUE TITLE
How to specify source generation order?

### ISSUE THREAD

**Issue by elnurvl** [dart-lang/build#2584]
Hi. I have a file which should include `.g.dart` and `.jorm.dart` generated files. However the `.jorm.dart` file also depends on the `.g.dart file`.

How can I configure the `build_runner` to generate the source of the`.g.dart` file firstly? Otherwise, the parser of the `.jorm.dart` files cannot recognize classes of the `.g.dart` files.

**Comment by natebosch** [comment]
See https://pub.dev/packages/build_config#adjusting-builder-ordering

You can either put `required_inputs: [".g.dart"]` on the builder definition for the builder which outputs `.jorn.dart` files, or you can put a `runs_before` on the builder which outputs `.g.dart` files. Most likely you'll want to go with `required_inputs: [".g.dart"]`.

**Comment by elnurvl** [comment]
@natebosch , thanks for the quick response. I tried it, but no success. The builder still fails to find the dependent classes on the generated `.g.dart` files. It works fine when I do not refer to them. Below you can check the build.yaml file for the jaguar_orm generator package:
`
builders:
  jaguar_orm_gen:
    import: "package:jaguar_orm_gen/builder.dart"
    builder_factories: ["jaguarOrm"]
    build_extensions: {".dart": [".jorm.dart"]}
    auto_apply: root_package
    build_to: source
    required_inputs: [".g.dart"]
`

**Comment by natebosch** [comment]
You should be able to verify the order by inspecting the file `.dart_tool/build/entrypoint/build.dart`. There will be a series of calls like `_i1.apply('jaguar_orm_gen:jaguarm_orm_gen', ...`.

Can you look in there and see if the order is correct between these two builders?

**Comment by elnurvl** [comment]
@natebosch , it is in this form:
`
[
  _i1.apply('built_value_generator:built_value', [_i2.builtValue],
      _i1.toDependentsOf('built_value_generator'),
      hideOutput: true, appliesBuilders: ['source_gen:combining_builder']),
  _i1.apply('source_gen:combining_builder', [_i3.combiningBuilder],
      _i1.toNoneByDefault(),
      hideOutput: false, appliesBuilders: ['source_gen:part_cleanup']),

    // This one requires the above one
  _i1.apply('jaguar_orm_gen:jaguar_orm_gen', [_i4.jaguarOrm], _i1.toRoot(),
      hideOutput: false),
  _i1.applyPostProcess('source_gen:part_cleanup', _i3.partCleanup,
      defaultGenerateFor: const _i5.InputSet())
]
`
I cannot figure out what is the problem. The thing is that, it was working few months ago. Now I cannot use `built_value` generated classes for the `.jorm.dart` generator for whatever reason. For instance, when I copy the `.g.dart` file and rename it in order to prevent "regeneration" the `.jorm.dart` generator makes no problem.

**Comment by natebosch** [comment]
Double check that you are using the latest package versions, especially `build_resolvers`. This is something I would expect to work. There were some changes fairly recently that made even more code able to be resolved (it used to be that you could only resolve code that was a transitive import of the primary input for a build step, now you should be able to resolve code that isn't imported).

If you are trying to resolve the code that's in a `part of` file, make sure to target the library, not the part file, when you use the resolver.

**Comment by elnurvl** [comment]
It seems I have found the root cause of the problem. It is due to the dart analyzer package upgrade. When I switch the `analyzer` version back to `0.34.3`, `build_runner` builds everything correctly! I could not find out which exact change causes this issue, but right now, I do not want to keep myself upgrading to the latest versions just because of this unknown issue. @natebosch , should it be considered as a bug of `build` package or `analyzer` package?

**Comment by natebosch** [comment]
Most likely the fix would need to be here. If you can provide a minimal reproduction we can dig in. I'm not aware of anything in either `build_resolvers` or `analyzer` that would have caused a regression like this.

**Comment by elnurvl** [comment]
@natebosch , here you can see a simple example project. Strangely, I could not use `analyzer 0.34.3` package for whatever reason, but you can at least reproduce the issue.
https://github.com/elnurvl/example-dart-project/issues/1#issue-545235420

**Comment by natebosch** [comment]
This looks similar to some other issues around resolving part files. It is possible this was resolved by https://github.com/dart-lang/build/pull/2618

Can you upgrade to to `build_resolvers` version `1.3.3` and see if that helps? @jakemac53 - were there still analyzer bugs that need to be solved here?

**Comment by elnurvl** [comment]
That's it! The new version of the `build_resolvers` resolved the issue. Thank you for your support!
