### ISSUE TITLE
Intermittent error: RangeError (byteOffset): Invalid value: Valid value range is empty: 0#0

### ISSUE THREAD

**Issue by shyndman** [dart-lang/build#2589]
We're encountering intermittent errors in our CI environment while running the test suite for [`mobx_codegen`](https://pub.dev/packages/mobx_codegen).

Here is the exception:
```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0#0     
_ByteDataView.getUint32 (dart:typed_data-patch/typed_data_patch.dart:4411:7)

#1      BufferContext._getUint32 (package:analyzer/src/summary/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:analyzer/src/summary/flat_buffers.dart:54:21)
#3      TableReader.read (package:analyzer/src/summary/flat_buffers.dart:731:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:16966:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:1825:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:196:42)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:140:43)
#8      List.forEach (dart:core-patch/growable_array.dart:285:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:140:18)
#10     new SummaryBasedDartSdk (package:analyzer/src/summary/summary_sdk.dart:32:18)
#11     analysisDriver (package:build_resolvers/src/analysis_driver.dart:26:13)
#12     AnalyzerResolvers._ensureInitialized.<anonymous closure> (package:build_resolvers/src/resolver.dart:189:20)
<asynchronous suspension>
#13     AnalyzerResolvers._ensureInitialized (package:build_resolvers/src/resolver.dart:192:6)
#14     AnalyzerResolvers.get (package:build_resolvers/src/resolver.dart:197:11)
#15     BuildStepImpl.resolver (package:build/src/builder/build_step_impl.dart:73:54)
#16     _Builder.build (package:source_gen/src/builder.dart:64:32)
#17     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#18     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#19     Future.wait (dart:async/future.dart:393:26)
#20     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
```

Any thoughts?

* Dart SDK Version (`dart --version`)

  Dart VM version: 2.7.0 (Unknown timestamp) on "linux_x64"

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

  analyzer 0.39.2+1
  build 1.2.2
  build_config 0.4.1+1
  build_daemon 2.1.2
  build_resolvers 1.3.0
  build_runner 1.7.2
  build_runner_core 4.3.0
  build_test 0.10.11

**Comment by jakemac53** [comment]
cc @scheglov any ideas?

**Comment by scheglov** [comment]
It looks that an empty / truncated summary file was given to analyzer.

**Comment by jakemac53** [comment]
@shyndman one thing that could be happening is build_runner could be running before the full flutter sdk has been downloaded. We need the dart sources of the flutter engine to be available so we can summarize it, and maybe if they aren't we are ending up with an empty summary file?

I think you can do `flutter precache` to ensure all those sources are available (any other normal flutter commands should also end up doing this).

**Comment by shyndman** [comment]
I'll give it a shot and report back. Thank you.

**Comment by shyndman** [comment]
Our project switched over from CircleCI to using Github Actions for CI (unrelated to this issue), and we are no longer seeing the problem.

I'm going to close this off until we see it again. Thanks.
