### ISSUE TITLE
Trouble with incremental builds

### ISSUE THREAD

**Issue by maxlapides** [dart-lang/build#2602]
Hey there! I'm having some trouble with a big project I'm working on, where the incremental builds often don't work and instead a full rebuild of the entire project is run. I'm just asking here if anyone has any advice or experience on how to improve the situation.

I think this may be an issue with the way we've structured our project. We have a big file called `internals.dart` that exports all of our reusable stuff, this includes reusable components and well as `built_value` models. The problem is that we have a bunch of circular dependencies within `internals.dart`, so every time a file that is exported by `internals.dart` is modified, the entire project is rebuilt.

I think we may be able to get rid of the circular dependencies by breaking up `internals.dart` into smaller files. The problem, I think, is that some files in `exports1.dart` would import `exports2.dart` and then some files in `exports2.dart` would import `exports1.dart`, creating a circular dependency that would result in a full rebuild of `exports1.dart`, `exports2.dart` and any other files that import those files.

Unfortunately due to the size of the project, it is very expensive for me to try to reorganize the project to try to avoid these issues. I have already spent many days trying to reconfigure the imports. I have managed to isolate the circular dependencies to within `internals.dart`, but I have been having trouble getting past this.

Do you have any recommendations for best practices on how to structure projects? Or do you have any recommendations on how I can identify circular dependencies? Does any such tooling exist?

Thanks so much for your help!

**Comment by jakemac53** [comment]
> a full rebuild of the entire project is run

Is this the entire project or just your application package?

**Comment by jakemac53** [comment]
Also - is this for compiler builds (build_web_compilers, build_vm_compilers) or just general Dart 
codegen?

**Comment by maxlapides** [comment]
I think it's just my application. This is for my Flutter project. We're using a lot of `built_value` :)

**Comment by jakemac53** [comment]
Ah - are you sure this is related to build_runner specifically? If you have some logs (in -v mode) that might help.

**Comment by maxlapides** [comment]
@jakemac53 is there somewhere I can privately send you logs? The verbose logs basically output our entire application structure, which I'm a little wary of posting here since it's a closed-source project.

**Comment by jakemac53** [comment]
You can find me on gitter in this channel https://gitter.im/dart-lang/build (actually might be a better place to discuss anyways)

**Comment by jakemac53** [comment]
I am going to close this for now - the recommendation was to use `generate_for` to run built value on only the model classes.

Keeping a clean separation of model code from other code will also help a lot here.
