### ISSUE TITLE
pub upgrade + AssetGraph version change interact poorly

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#261]
1. Pub upgrade, get new version of build and build_runner
2. dart tool/build.dart
    Error message about overwriting inputs. We thought the build script changed so we do a different set of checks that fails to check whether old outputs need to be deleted
3. dart tool/build.dart
    Asks if stale outputs should be deleted

Ideally we should skip step 2 and go straight to step 3

**Comment by jakemac53** [comment]
I believe this has been fixed for a while, please re-open if I am wrong :)
