### ISSUE TITLE
Influencing builder ordering through the target

### ISSUE THREAD

**Issue by shyndman** [dart-lang/build#2611]
Hello,

[Several of our users](https://github.com/mobxjs/mobx.dart/issues/405) are seeing our code generator emit `dynamic` types when attempting to reference types created by other builders.

Correct me if I'm wrong, but it's my understanding that ordering of the builders may be to blame — our builder can't see what doesn't yet exist.

Is there a way to influence the ordering of builders through a target? Or otherwise hint our builder to run again after an initial generation pass has completed?

Both builders in this case make use of the `source_gen` package, and its `combining_builder`.

**Comment by jakemac53** [comment]
`SharedPartBuilder`s that use the `combining_builder` can never see the outputs of other `SharedPartBuilder`s. The way that builder works is it doesn't actually generate the dart file at all until all the combining builder runs. That builder collects up the outputs of all the other builders and writes a dart file that merges all the outputs together.

See https://github.com/dart-lang/build/blob/07c39cdd05e52c69538b8a7d9c24023caf5686ce/build_config/README.md#adjusting-builder-ordering for the ordering primitives that are available, but these are only provided at the builder definition level and not exposed via the `target`.

**Comment by elbeshenrique** [comment]
Looking foward for a possible solution to that

**Comment by jakemac53** [comment]
I don't think we have anything planned to fix this at this time.

In general, it is best if builders don't expose any new apis and only fill in the implementation of existing (explicitly typed) apis (through referencing some generated symbol etc).

That isn't always possible though.

**Comment by shyndman** [comment]
Alright. Thank you.

**Comment by rrousselGit** [comment]
@jakemac53 
So if I have a code-generator that generates code for another generator, does that mean the first generator must not be a "SharedPartBuilder"?

I'm currently trying to make a generator that outputs something that `json_serializable` can use, but I have no success with that

**Comment by jakemac53** [comment]
Yes - shared part builders cannot see the outputs of other shared part builders.

You would need to generate a library builder or regular part builder, and use `runs_before: json_serializable`.

**Comment by rrousselGit** [comment]
I've tried this, still without success

I opened an issue about it: https://github.com/dart-lang/source_gen/issues/446

**Comment by natebosch** [comment]
`runs_before: json_serializable`, and writing the `.dart` file from your builder (not using `SharedPartBuilder`, can be a `LibraryBuilder` or something writing to `.dart`) should be the solution. It could be that #2389 was also causing trouble.

Closing for now, please comment if this is still a problem.
