### ISSUE TITLE
toJson 方法有点问题

### ISSUE THREAD

**Issue by Darren-chenchen** [dart-lang/build#2627]
```
import 'package:json_annotation/json_annotation.dart';
import './Location.dart';

part 'Address.g.dart';

@JsonSerializable()
class Address {
	//详细地址
	String detailAddress;
	//邮编
	String postcode;
	//位置信息
	Location location;

	Address();

	factory Address.fromJson(Map<String, dynamic> json) => _$AddressFromJson(json);

	static Map<String, dynamic> toJson(Address instance) => _$AddressToJson(instance);

}
```
```
part of 'Address.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Address _$AddressFromJson(Map<String, dynamic> json) {
  return Address()
    ..streetName = json['streetName'] as String
    ..detailAddress = json['detailAddress'] as String
    ..postcode = json['postcode'] as String
    ..location = json['location'] == null
        ? null
        : Location.fromJson(json['location'] as Map<String, dynamic>);
}

Map<String, dynamic> _$AddressToJson(Address instance) => <String, dynamic>{
      'streetName': instance.streetName,
      'detailAddress': instance.detailAddress,
      'postcode': instance.postcode,
      'location': instance.location,
    };
```

此时执行   String str = json.encode(Address.toJson(shop)); 会报错。Unhandled Exception: Converting object to an encodable object failed: Instance of 'Location'

我觉得AddressToJson这个方法需要修改成：
```
Map<String, dynamic> _$AddressToJson(Address instance) => <String, dynamic>{
      'streetName': instance.streetName,
      'detailAddress': instance.detailAddress,
      'postcode': instance.postcode,
      'location': Location.toJson(instance.location), /// Location.toJson
    };
```

**Comment by jakemac53** [comment]
It sounds like the `Location` class does not have a `toJson` instance method, which is required for this to work.

**Comment by Darren-chenchen** [comment]
> It sounds like the `Location` class does not have a `toJson` instance method, which is required for this to work.
> 
> Note that this can't be an extension method - it has to be an instance method.

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Location.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Location _$LocationFromJson(Map<String, dynamic> json) {
  return Location()
    ..longitude = json['longitude'] as String
    ..latitude = json['latitude'] as String
    ..distance = (json['distance'] as num)?.toDouble();
}

Map<String, dynamic> _$LocationToJson(Location instance) => <String, dynamic>{
      'longitude': instance.longitude,
      'latitude': instance.latitude,
      'distance': instance.distance,
    };

**Comment by jakemac53** [comment]
What does your the look like? You have to hook it into these methods as well:

```
class Location {
  ...
  Map<String, dynamic> toJson() => _$LocationToJson(this);
}
```

**Comment by jakemac53** [comment]
Oh I just noticed in your `Address` class you made this a static method. That will not work, it has to be an instance method like in my example above.

Probably you used the same pattern in the Location class and that is the problem. Going to go ahead and close this as I am pretty confident that is your issue.
