### ISSUE TITLE
build_runner terminates after change to pubspec.yaml

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/build#2638]
Is there a way to automatically restart the script after a change to pubspec.yaml. Because after I changed the pubspec.yaml file alle the watch tasks of build_runner are terminated with this message:

> [SEVERE] Terminating builds due to package graph update, please restart the build.
> [INFO] Terminating. No further builds will be scheduled

I work on a project with multiple packages each of them containing a lot of code generation. When I need to restart the tasks for multiple projects each time pubspec.yaml changes is a lot of work. Also after a branch change, git pull, etc. I need to restart to.

Is there a way to prevent this from happening?

Something similar was discussed here: https://github.com/dart-lang/build/issues/777

**Comment by jakemac53** [comment]
We have to recreate the build script and make sure it hasn't changed, so we can't really do much here.

You can create a wrapper script which re-runs it automatically (I think we exit with a special exit code as well).

I think we do that already for the actual `build_runner` commands, but things like webdev do not.

**Comment by HerrNiklasRaab** [comment]
Hey @jakemac53, thanks for you response. Currently we are using this command to start the watcher task for all our packages: "packages pub run build_runner watch --delete-conflicting-outputs". 

Could you explain more in detail, how I could implement a wrapper script you mentioned here:  "You can create a wrapper script which re-runs it automatically (I think we exit with a special exit code as well).". Do you have an example?

**Comment by jakemac53** [comment]
I mean some sort of basic wrapper script which runs `pub run build_runner watch --delete-conflicting-outputs` in a loop, untested example below:

```dart
import 'dart:io';

void main(_) async {
  while (true) {
    await Process.run('pub', ['run', 'build_runner', 'watch', '--delete-conflicting-outputs']);
  }
}
```

You might want to check the exit code or stdout to make sure you only do it for expected things, etc.

You may also want to run it with `ProcessStartMode.inheritStdio`.

**Comment by jakemac53** [comment]
I am going to close this though as I don't think there is anything we can really do here - our own script can't do this because we don't know if our own dependencies changed as a result of the package update.

**Comment by HerrNiklasRaab** [comment]
@jakemac53  Thanks for the tip. I just wonder myself, that nobody else, seems to have this problem. This is how I solved it, maybe I can help someone else:

``` dart
import 'dart:convert';
import 'dart:io';

var packageFolders = Directory.current.parent
    .listSync(recursive: false)
    .whereType<Directory>()
    .where((directory) => directory.name != ".git");

void main(_) async {
  packageFolders.forEach((directory) async {
    print("Start infinite process for: " + directory.path);
    var workingDirectory = "../" + directory.name;
    await InfiniteProcess(() async {
      var process = await Process.start(
          'flutter',
          [
            'packages',
            'pub',
            'run',
            'build_runner',
            'watch',
            '--delete-conflicting-outputs'
          ],
          workingDirectory: workingDirectory);
      ProcessOutputWriter(process, directory.name);
      return process;
    }, shouldExitDecisionMakers: [PubReRunDecisionMaker(workingDirectory)])
        .start();
  });
}

class ProcessOutputWriter {
  String outputPrefix;
  ProcessOutputWriter(Process process, this.outputPrefix) {
    process.stdout.listen((event) {
      if (outputPrefix != null) {
        stderr.write(outputPrefix + ": ");
      }
      stdout.add(event);
    });
    process.stderr.listen((event) {
      if (outputPrefix != null) {
        stderr.write(outputPrefix + " (Error): ");
      }
      stderr.add(event);
    });
  }
}

class InfiniteProcess {
  Future<Process> Function() runProcess;
  bool Function(int) onExit;
  List<ShouldExitDecisionMaker> shouldExitDecisionMakers;
  InfiniteProcess(this.runProcess, {this.shouldExitDecisionMakers});

  Future<int> start() async {
    var exitCode = 0;
    bool reRun = false;
    while (exitCode == 0 || reRun) {
      reRun = false;
      var process = await runProcess();
      exitCode = await process.exitCode;
      reRun = shouldExitDecisionMakers?.any((shouldExitDecisionMaker) =>
              !shouldExitDecisionMaker.shouldExit(exitCode)) ??
          false;
    }
    return exitCode;
  }
}

abstract class ShouldExitDecisionMaker {
  bool shouldExit(int exitCode);
}

class PubReRunDecisionMaker extends ShouldExitDecisionMaker {
  String workingDirectory;

  PubReRunDecisionMaker(this.workingDirectory);

  @override
  bool shouldExit(int exitCode) {
    if (exitCode == 65 || exitCode == 255) {
      print("Should we run pub get? (y/n)");
      if (stdin.readLineSync(encoding: Encoding.getByName('utf-8')) == "y") {
        var result = Process.runSync("flutter", ['pub', 'get'],
            workingDirectory: workingDirectory);
        print(result.stderr);
        print(result.stdout);
        return true;
      }
    }
    return false;
  }
}

extension FileExtention on FileSystemEntity {
  String get name {
    return path?.split("/")?.last;
  }
}

```

**Comment by icodeyou** [comment]
To run this in a loop, you can simply run this bash command in your terminal :

```shell
"command": "while true; do dart run build_runner watch --delete-conflicting-outputs; sleep 1; done"
```

To abort, Ctrl+C will do.
