### ISSUE TITLE
Fail to start when using a newer `build.yaml` feature than is supported by old snapshot

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2652]
If we have an old snapshot and try to run it, but packages are using newer `build_config` features than was supported by that snapshot, we fail and exit before we get a chance to clean out the old build script.

**Comment by jakemac53** [comment]
Ah that makes sense... I don't think we can do the build script update check until after we parse the build.yaml files though (it requires an asset graph etc).

We will have to think on the best way to resolve this.

**Comment by natebosch** [comment]
I think it could make sense to treat an exception from `build_config` like we would an out of date snapshot. The only case this makes worse is that we'd be slower to run for cases where there is continually an error in a `build.yaml`.

**Comment by jakemac53** [comment]
One problem with this is ensuring that we actually exit with an error on the next run. 🤔 

We don't want to blow away the entire cache, and so it would require some other explicit command line config option or something like that which seems gross.

**Comment by jakemac53** [comment]
Given the complexity of actually doing the right thing here versus the value, I am going to instead add some additional context to the error log indicating that a `pub run build_runner clean` may fix the issue if you are using a new feature.
