### ISSUE TITLE
Support language versioning for builders

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2658]
- [x] pass the correct `Packages` to for the analysis driver
- [x] expose language version on LibraryElement
- [ ] write docs for builder authors with guidance

**Comment by jakemac53** [comment]
cc @scheglov do you know when the next analyzer version will be released with the `packages` argument to AnalysisDriver? I see it in the sdk but it hasn't been published yet.

**Comment by scheglov** [comment]
We plan publishing a new version of analyzer soon.
https://github.com/dart-lang/sdk/issues/41222

https://dart-review.googlesource.com/c/sdk/+/141464 will include expose language version from `LibraryElement`.

**Comment by jakemac53** [comment]
PR pending here https://github.com/dart-lang/build/pull/2669. This contains everything but the docs.
