### ISSUE TITLE
`build_runner build --help` does not print help

### ISSUE THREAD

**Issue by srawlins** [dart-lang/build#2679]
[The docs](https://pub.dev/packages/build_runner#built-in-commands) for build_runner say:

> The available commands are build, watch, serve, and test.
>
> ...
>
> All the above commands support the following arguments:
> * --help: Print usage information for the command.

However, this does not work for me:

```none
$ pub run build_runner build --help
Unable to spawn isolate: lib/src/specs/type_reference.g.dart:9:7: Error: The non-abstract class '_$TypeReference' is missing implementations for these members:
```

None of these worked either: `pub run build_runner --help`, `pub run build_runner help run`.

According to `pubspec.lock`, I'm using build_runner 1.8.1.

**Comment by jakemac53** [comment]
Did you try a `pub upgrade`? It looks like the isolate failed to spawn at all.

**Comment by srawlins** [comment]
This was me running it from _within_ the code_builder package, and I think that led to exactly what you said. I guess no way to even print help if the code in the isolate has compile-time errors?

**Comment by jakemac53** [comment]
Right - we never get to the point where we can even parse the args...
