### ISSUE TITLE
Tests run under build_runner don't allow user-defined platform

### ISSUE THREAD

**Issue by alanknight-wk** [dart-lang/build#2684]
* Dart SDK Version 
2.7.2
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
build_test - 0.10.12+1
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Mac
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome
* Any other packages or constraints we should know about

I have a test suite where I define a new platform. It runs fine under pub test, but pub run build_runner test fails with the error 

Undefined variable ...  @TestOn('chromeWithExtension')

It feels like this should be relatively simple. If build didn't complain, test would run this successfully. It seems like it just needs build to invoke test in a way that it sees dart_test.yaml and can answer about those platforms. 

The motivation is that I have a Chrome Extension and want to be able to test both with the extension loaded and not loaded.

**Comment by natebosch** [comment]
Can you run with `--verbose` to get a stack trace?

**Comment by natebosch** [comment]
It looks like we hardcode known platforms.

https://github.com/dart-lang/build/blob/65e54a4aa5ebb1a7d17040f3a592cfb2f215f357/build_test/lib/src/test_bootstrap_builder.dart#L52-L54

@jakemac53 - do you know if user defined platforms have enough information to know if we should consider it a browser test?

**Comment by alanknight-wk** [comment]
/me waves

User-defined platforms can only inherit from existing platforms, so any check (other than a hard-coded list) that tells you if a regular platform is a browser test should also work on user-defined tests. For example, my motivating use case is to define a sub-platform of Chrome with additional command-line options.

**Comment by alanknight-wk** [comment]
```

Error on line 2, column 10 of test/clipboard_extension_test.dart: Undefined variable.
  ╷
2 │ @TestOn('chromeWithExtension')
  │          ^^^^^^^^^^^^^^^^^^^
  ╵
package:test_core/src/runner/parse_metadata.dart 516:7                  _Parser._contextualize
package:test_core/src/runner/parse_metadata.dart 123:12                 _Parser._parsePlatformSelector
package:test_core/src/runner/parse_metadata.dart 117:7                  _Parser._parseTestOn
package:test_core/src/runner/parse_metadata.dart 83:18                  _Parser.parse
package:test_core/src/runner/parse_metadata.dart 27:48                  parseMetadata
package:build_test/src/test_bootstrap_builder.dart 35:20                TestBootstrapBuilder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 486:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 484:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 441:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 437:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 375:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 374:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 372:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 320:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] Build:
```

**Comment by jakemac53** [comment]
@alanknight-wk I pushed this branch, https://github.com/dart-lang/build/tree/custom-runtimes. Can you try that out and tell me if it does what you need?

It requires some private imports from test_core, so landing it will be a bit more work, but I wanted to make sure I encapsulated your requirements/goals sufficiently.

Note that you will have to add `dart_test.yaml` to your sources for this to work, something like:

```yaml
targets:
  $default:
    sources:
      - dart_test.yaml
      - $package$
      - lib/**
      - test/**
      - web/**
```

**Comment by alanknight-wk** [comment]
That needs to be r.identifier, not r.name in the call to parseMetadata. With that it seems like it's working.
