### ISSUE TITLE
Generating code in different directories (e.g. test_driver)

### ISSUE THREAD

**Issue by chris-rutkowski** [dart-lang/build#2698]
Can the tool generating code outside of lib folder?
I have some models that are manually serialised in `test` and `test_driver` directories (Flutter app).

The ` flutter pub run build_runner build` and ` flutter pub run build_runner watch` doesn't seam to generate anything outside of `lib`.

```
dart: 2.8.1
build_runner 1.10.0
```

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build
