### ISSUE TITLE
build_runner failing to compile after analyzer upgrade to 0.39.9

### ISSUE THREAD

**Issue by shyndman** [dart-lang/build#2712]
Hey there,

I'm running into failures compiling `build_runner` against `analyzer` 0.39.9, which was released this morning by the looks of it. Here is the error:

```
Failed to precompile build_runner:build_runner:
../../../../../../../../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.9/lib/src/resolver.dart:340:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context).build(
         ^^^^^^^^^^^^^^
pub finished with exit code 1
```

Thanks!

Version info:
build_runner: 5.20
build_resolvers: 1.3.9
dart --version: Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "macos_x64"

**Comment by srdrymn** [comment]
same problem here
```
Failed to precompile build_runner:build_runner:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.9/lib/src/resolver.dart:340:10: Error: Method not found: 'SummaryBuilder'.  
  return SummaryBuilder(sdkSources, sdk.context).build(
         ^^^^^^^^^^^^^^
pub finished with exit code 1`
```

**Comment by aarontwf** [comment]
Seems to be resolved https://github.com/dart-lang/sdk/issues/42163

**Comment by jakemac53** [comment]
Yes we got a patch release of analyzer (`0.39.10`) which fixes the problem

**Comment by shyndman** [comment]
Nice! Thanks

**Comment by henriSedjame** [comment]
I got same error with the new version 0.39.13

**Comment by nicemanis** [comment]
I am also getting this issue with 0.39.15 version:

```
Failed to precompile build_runner:graph_inspector:
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:343:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context)
         ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:332:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.15/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^
Failed to precompile build_runner:build_runner:
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:343:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context)
         ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:332:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.15/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^
pub finished with exit code 1
```

**Comment by jakemac53** [comment]
I followed up in the new issue that was filed https://github.com/dart-lang/build/issues/2764 - sorry I missed the previous followup comment here about the 0.39.13 version.

Note that the easiest fix here is to update your `build_resolvers` version to at least `1.3.10`.

**Comment by ebbyferguson** [comment]
> I followed up in the new issue that was filed #2764 - sorry I missed the previous followup comment here about the 0.39.13 version.
> 
> Note that the easiest fix here is to update your `build_resolvers` version to at least `1.3.10`.

i have the same issue, however this fix isn't working for me

**Comment by re-kent** [comment]
> > I followed up in the new issue that was filed #2764 - sorry I missed the previous followup comment here about the 0.39.13 version.
> > Note that the easiest fix here is to update your `build_resolvers` version to at least `1.3.10`.
> 
> i have the same issue, however this fix isn't working for me

Did you run `flutter packages pub upgrade`?

**Comment by ebbyferguson** [comment]
Yes i did.

**Comment by kdmatrosov** [comment]
Try like this
```
dev_dependencies:
  ...
  build_resolvers: ^1.3.11
  ...
```

**Comment by ebbyferguson** [comment]
I had to move on quickly. i moved the files to a new flutter project and it worked

**Comment by 136759790** [comment]
just run `flutter packages upgrade`

**Comment by lzhuor** [comment]
You actually only need to upgrade the `build_runner`. Overrides `build_resolvers` seems a hackish approach to me.
