### ISSUE TITLE
Document how to use a Matcher with testBuilder

### ISSUE THREAD

**Issue by srawlins** [dart-lang/build#2717]
testBuilder's `outputs` parameter is allowed to be a `Map<String, Matcher<String>>` or a `Map<String, List<int>>`. But I don't see how to use it.

`test_bootstrap_builder_test.dart` has examples like:

```dart
outputs: {
      'a|test/hello_test.dart.vm_test.dart': decodedMatches(allOf(
          contains('import "hello_test.dart" as test;'),
          contains('import "package:test/bootstrap/vm.dart";'))),
    });
```

Perhaps this is primary way to use a Matcher here. I think that could be added to the dartdoc for `testBuilder`, or maybe just a link to `decodedMatches`.

**Comment by jakemac53** [comment]
Which part of it are you finding confusing? That should help inform what we should put in the docs.

The `decodedMatches` matcher fwiw basically is just a helper for comparing the string representation (it decodes the bytes as a utf8 string and runs the nested matchers against that)

**Comment by srawlins** [comment]
Right, I think its all just the decoding part. When I saw the API accepted a Matcher, I immediately tried this:

```dart
    outputs: {
        'foo|test/foo_test.mocks.dart': contains('''
        class MockFoo extends _i1.Mock implements _i2.Foo {
          _i2.Bar m1() => super.noSuchMethod(Invocation.method(#m1, []), _i2.Bar.one);
        }
        '''),
```

and the test fails with:

```none
  Expected: contains 'class MockFoo extends _i1.Mock implements _i2.Foo {\n'                     
              '  _i2.Bar m1() => super.noSuchMethod(Invocation.method(#m1, []), _i2.Bar.one);\n'
              '}\n'
              ''  
    Actual: [     
              105,
              109,
              112,
              111,
              114,
              116,
              32, 
              39, 
              112,
              97,
              99,
              107,
              97,
              103,
              101,
              58,
              109,
              111,
              99,
              107,
              105,
              116,
              111,
              47,
              ...
            ]
  Unexpected content for foo|test/foo_test.mocks.dart in result.outputs.
```

which seemed like just a dead end. Since I don't control the two values sent to `expect` (like if I were able to write `expect(a, contains(b));`), I didn't know how to proceed. I was unaware of the `decodedMatches` helper, and I got lucky grepping the mono-repo for `testBuilder` and `contains`.

**Comment by srawlins** [comment]
Oh, also it seemed weird that I could pass a string directly, but not a Matcher using almost the same string. Because `checkOutputs` secretly does this:

```dart
if (contentsMatcher is String) {
        expected = utf8.decode(actual);
```

I think just one sentence like "When using a Matcher, be sure to encode Strings or use [decodedMatches]."
