### ISSUE TITLE
Support building/running in strong or weak null safety mode.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2723]
- [ ] Each library has to be compiled separately for each of these modes
  - Need separate builders, with different file extensions but we can likely re-use the module files
  - When creating libraries we need to pass the correct sdk dill outline file
- [ ] The entrypoint builders will determine the mode (strong/weak) based on the language version, and will require the correct corresponding JS files (which in turn require the correct dill files)
- [ ] We want to compile the sdk on our own to avoid shipping duplicate JS files with the SDK
  - `dartdevc` should expose a command that takes an sdk dill + module type and compiles it (for the sdk)
    - we need to create these on demand (using a builder) based on which mode apps are running in, and cache the file

**Comment by franklinyow** [comment]
Is this something we need for track for tech preview 2?

**Comment by jakemac53** [comment]
This should not affect flutter, so no I don't believe so.

**Comment by nshahan** [comment]
AFAIK once https://github.com/dart-lang/sdk/commit/9460ac3c8daaac958147b1b7d98afb381cb74cd5 is included in a dev release all the parts of this issue should be unblocked.

**Comment by jakemac53** [comment]
Sounds good, I would like to wait to support this until the feature lands in a dev release (no experiment flag is required).

Otherwise the detection of whether a library is "null safe" or not will have to be continually updated etc.

**Comment by natebosch** [comment]
> Otherwise the detection of whether a library is "null safe" or not will have to be continually updated etc.

I don't understand this - do you mean that you hope to avoid adopting the extra complexity that comes from this idea of there being 2 meanings of the `2.9` language version?

**Comment by natebosch** [comment]
@nshahan - I talked with Jake offline about this. I'm fine taking this on once we have a published 2.10 dev SDK to try with.

**Comment by jakemac53** [comment]
I am going to work on this in a separate branch and send multiple PRs to that, merging all at once when it is done https://github.com/dart-lang/build/tree/sound-null-safety-ddc
