### ISSUE TITLE
build_runner  ||   FileSystemException:  ||  errno = 3 

### ISSUE THREAD

**Issue by p-r-t** [dart-lang/build#2740]
### On running command  "flutter packages pub run build_runner watch --delete-conflicting-outputs", I get error 

[INFO] Generating build script...
[INFO] Generating build script completed, took 414ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 15.4s

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 11ms

[INFO] Waiting for all file watchers to be ready...
### [SEVERE] Error from directory watcher for package:xxxxxx

If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.  

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

### FileSystemException: Directory listing failed, path = 'c:\users\xxxx\git-dev\flutter\xxx\xxxx\xxxx\*' (OS Error: The system cannot find the path specified., errno = 3)

Flutter doctor -v output is following:
[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.19.0-4.2.pre at C:\Users\xxxxxx\flutter
    • Framework revision 9b9b543d92 (6 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

Other relevant information:
* build_runner: ^1.10.0
* Windows
* Chrome
* moor_generator: ^3.2.0
  freezed: ^0.10.8

**Comment by jakemac53** [comment]
See the recommendation `If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.`. This is something coming from the directory watcher, so not much we can do here. You can disable that though and use the polling watcher which shouldn't have this problem, but uses more cpu.

**Comment by p-r-t** [comment]
Hi @jakemac53, Thanks for taking out time to respond to my query. Per your recommendation, I used  "flutter pub run build_runner watch --use-polling-watcher" command. However, I got another kind of error:

### AssetNotFoundException: xxxx_xxxxx|.packages
package:build_runner_core/src/asset/file_based.dart 134:18     _fileForOrThrow.<fn>
dart:async                                                     _completeOnAsyncReturn
package:pool/pool.dart                                         Pool.withResource
package:build_runner_core/src/asset/file_based.dart 133:26     _fileForOrThrow
package:build_runner_core/src/asset/file_based.dart 33:48      FileBasedAssetReader.readAsBytes
package:build_runner/src/generate/watch_impl.dart 326:52       WatchImpl._run.<fn>
package:build_runner/src/generate/watch_impl.dart              WatchImpl._run.<fn>
package:build_runner/src/generate/watch_impl.dart 355:6        WatchImpl._run
package:build_runner/src/generate/watch_impl.dart 196:20       new WatchImpl
package:build_runner/src/generate/watch_impl.dart 127:5        _runWatch
package:build_runner/src/generate/watch_impl.dart 85:15        watch
dart:async                                                     _completeOnAsyncReturn
package:build_runner_core/src/generate/options.dart            BuildOptions.create
dart:async                                                     _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart  TargetGraph.forPackageGraph
dart:async                                                     _completeOnAsyncReturn
package:build_runner_core/src/package_graph/target_graph.dart  _packageBuildConfig
dart:async                                                     _completeOnAsyncReturn
package:build_config/src/build_config.dart                     BuildConfig.fromBuildConfigDir



I suspect that this is a windows issue. Because when I used the command "flutter packages pub run build_runner watch --delete-conflicting-outputs", the path generated in the error message was all in lower case. In fact, when I tried command "cd <path in error message>, I got invalid path error on command prompt.
