### ISSUE TITLE
--build-filter fails on Windows for larger number of targets

### ISSUE THREAD

**Issue by nturgut** [dart-lang/build#2765]
For Flutter Web engine we use `--build-filter` flag for building all the unit tests: https://github.com/flutter/engine/blob/master/lib/web_ui/dev/test_runner.dart#L468

It works fine in Linux. However in Windows the following [error](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8873742113308400432/+/steps/felt_test_chrome/0/stdout) encountered:

``` 
Building 77 targets for HTML
The command line is too long.
Failed to compile tests. Compiler exited with exit code 1
```

This tracker is for issues related to: dart2js

Dart SDK Version: 2.10 This issues is observed on the previous version as well.

Operating system: Windows

**Comment by natebosch** [comment]
We could implement a `--build-filter-file` option where you could write the paths to a file first, or a general `--args-file` to put all args in a file. I'd prefer _not_ to do that, and I don't really know how well the `--build-filter` stuff will scale as you grow the number of arguments there.

I agree that the best course is to see if we can reduce the need for so many filters at once.

**Comment by nturgut** [comment]
> How is that a dart problem? Isn't this just about passing a too long command line on windows?
> 
> https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation#:~:text=On%20computers%20running%20Microsoft%20Windows,command%20prompt%20is%202047%20characters.
> 
> Tentatively relabelling as web because the description mentions dart2js.

It works fine on Linux and MacOS. We observed this issue only on Windows.

**Comment by nturgut** [comment]
> We could implement a `--build-filter-file` option where you could write the paths to a file first, or a general `--args-file` to put all args in a file. I'd prefer _not_ to do that, and I don't really know how well the `--build-filter` stuff will scale as you grow the number of arguments there.
> 
> I agree that the best course is to see if we can reduce the need for so many filters at once.

The problem we have is we would like to use one config for all the canvas kit tests: https://github.com/flutter/engine/tree/master/lib/web_ui/test/canvaskit

And another one for the rest of the web engine unit test:
https://github.com/flutter/engine/tree/master/lib/web_ui/test

Is there any other filter (for folders maybe?), we can use to achieve this. I agree adding so many arguments is not idea.

Thanks a lot for the reply.

**Comment by jakemac53** [comment]
See my original response - I have a temporary workaround that could work listed there, and the long term solution would be to special case the situation where you want to run _all_ tests, such that it would pass a single glob.

**Comment by jakemac53** [comment]
I am going to close this as I don't believe there is anything actionable on our side that we plan to do, we can always revisit if that is not the case.
