### ISSUE TITLE
Support more specific filenames for build configurations

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#2770]
We recently ran into issues with third-party tools that misinterpret unrelated files as build configuration (https://github.com/SchemaStore/schemastore/issues/1163). The problem is that these tools identify files by their name, and `build.yaml` is rather generic.

Other Dart tools use more specific configuration files (like `dart_test.yaml`). Would it be possible for the build system to optionally support configuration files named `dart_build.yaml`? It could check if there's a `build.yaml` present and fall back to `dart_build.yaml` for full backwards compatibility.
I'm happy to contribute if this is deemed to be a feature worth having. Otherwise, feel free to just close this.

**Comment by jakemac53** [comment]
Fwiw we do support custom yaml files with the `--config=<config>` option, which will load a config file like this `build.<config>.yaml`. This isn't really its intended use case but it would possibly work.
