### ISSUE TITLE
Consider changing AssetReader.readAsBytes to return Uint8List

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2778]
In `dart:io` the `File.readAsBytes` methods return a `Uint8List`. We currently return `List<int>`. In some cases it is inconvenient to have a `List<int>` because it takes some conversion to get a `Uint8List`.

Changing this should be non-breaking for users. It would be breaking for overrides though so we should make sure we're OK with that.

**Comment by simolus3** [comment]
> we should make sure we're OK with that.

Are there any thoughts on this? It looks like a major version bump of `package:build` is happening soon, should we do this now?

I welcome this change as a builder author, are there any concerns from an implementation perspective?

**Comment by jakemac53** [comment]
I think the main concern here would be that not necessarily all implementations actually will natively get a `Uint8List`? So in that case some implementations may need to do a conversion?

Presumably today a consumer who needs a `Unit8List` could do a type check before converting, which might ultimately be more efficient than forcing a copy for the implementations that don't already have one?

**Comment by jakemac53** [comment]
We should I think make a decision now though as to whether we think this should be done, and either do it or close it :)

**Comment by natebosch** [comment]
I can't remember the reasoning here, and I can't find any particular use case that needs a `Uint8List`. I think most likely I filed this for consistency, but looking back now I'm not sure it's worth the churn.

I'll close for now.
