### ISSUE TITLE
AssetNotFoundException: my-app|.dart_tool/package_config.json

### ISSUE THREAD

**Issue by JanMate** [dart-lang/build#2790]
I got this stacktrace, so it can be useful for future debugging.

I launched:
flutter pub run build_runner watch --delete-conflicting-outputs

and after a few time it ends with. Maybe it terminated during flutter pub get or during anything else.

AssetNotFoundException: my-app|.dart_tool/package_config.json
package:build_runner_core/src/asset/file_based.dart 134:18  _fileForOrThrow.<fn>
dart:async                                                  _completeOnAsyncReturn
package:pool/pool.dart                                      Pool.withResource
package:build_runner_core/src/asset/file_based.dart 133:26  _fileForOrThrow
package:build_runner_core/src/asset/file_based.dart 33:48   FileBasedAssetReader.readAsBytes
package:build_runner/src/generate/watch_impl.dart 272:46    WatchImpl._run.<fn>

pub finished with exit code 1

**Comment by jakemac53** [comment]
This looks like it definitely could have been a result of running a `flutter pub get` while using the `watch` command - it tried to re-run before the package config was re-written.

Do you see this happen often or just once? I am a bit surprised I haven't seen a report of this before...

**Comment by JanMate** [comment]
Sometimes I catch this problem. It is nothing severe. Re-run "flutter pub run build_runner watch --delete-conflicting-outputs" always helps and works like a charm. :)

**Comment by jakemac53** [comment]
I went ahead and sent out a pr with a simple fix here to keep trying to read the file for at least 1 second. That should generally work although it isn't perfect obviously :).
