### ISSUE TITLE
build_runner: ^1.10.2 in quickstart is too high for Dart SDK 2.9.1 (flutter satble)

### ISSUE THREAD

**Issue by KipCrossing** [dart-lang/build#2795]
The quickstart docs [here](https://pub.dev/packages/hive) say to use `build_runner: ^1.10.2` but, on the stable channel of flutter we get:

```
The current Dart SDK version is 2.9.1.

Because moveitnq depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.
pub upgrade failed (1; Because moveitnq depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.)
```

Consider changing to `build_runner: ^1.10.2` until flutter stable is updated.

**Comment by jakemac53** [comment]
The latest build_runner does require the latest dev sdk - the reasoning is a bit convoluted but it is basically a workaround for an analyzer issue.

It might be worth filing an issue on the hive documentation to not suggest a constraint like that, something like `^1.0.0` should be sufficient.
