### ISSUE TITLE
Support for transient assets in build_runner

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#281]
Transformers can 'consume' assets, and bazel let's us write arbitrary files that effectively disappear if we don't declare them as outputs.

We should support something like this in build_runner. Potentially this could be something like assets which live only in memory during a build. Invalidation might get a little tricky, and the configuration will be tough to get right.

**Comment by jakemac53** [comment]
duplicate of https://github.com/dart-lang/build/issues/189 :)
