### ISSUE TITLE
analyzer: ^0.39.14 using dart_style 1.3.6

### ISSUE THREAD

**Issue by ybin0823** [dart-lang/build#2813]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "macos_x64"
* 
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "^4.1.1"
  test: "^1.6.3"
  build_runner: "^1.7.2"
  json_serializable: "^3.2.2"
dependency_overrides:
  analyzer: '0.39.14'
```
* MacOS

reference with
https://github.com/dart-lang/build/issues/2763#issuecomment-683201195

hello, I recently updated the flutter version and found something weird while running.

---------------------

*Step 1. without dependency_overrides*
```
dependency_overrides:
  analyzer: '0.39.14'
```
I found `analyzer` using `dart_style 1.3.6` in `.dart_tool/package_config.json`

*Step 2. with dependency_overrides*
`analyzer` using `dart_style 1.3.7` in `.dart_tool/package_config.json`

*Step 3. with dependency_overrides after flutter clean, flutter pub upgrade
```
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.7/lib/src/source_visitor.dart:1428:21: Error: The getter 'externalKeyword' isn't defined for the class 'FieldDeclaration'.
 - 'FieldDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'externalKeyword'.
      modifier(node.externalKeyword);
                    ^^^^^^^^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.7/lib/src/source_visitor.dart:1430:21: Error: The getter 'abstractKeyword' isn't defined for the class 'FieldDeclaration'.
 - 'FieldDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'abstractKeyword'.
      modifier(node.abstractKeyword);
                    ^^^^^^^^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.7/lib/src/source_visitor.dart:2618:21: Error: The getter 'externalKeyword' isn't defined for the class 'TopLevelVariableDeclaration'.
 - 'TopLevelVariableDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'externalKeyword'.
      modifier(node.externalKeyword);
```

In my opinion, dart-style 1.3.7 should be used when analyzer: ^0.39.14. 
Would you find out the cause of this part? 🙏 

Thank you!

**Comment by jakemac53** [comment]
I don't think there is anything actionable on this issue - the latest dart_style does require a newer analyzer, and overriding the analyzer version can break it. That is just the risk of dependency overrides...

If there were no overrides you should get compatible versions, and hopefully you should no longer need to pin analyzer at all (the previous issue should be resolved).

If not you can try also pinning dart_style.
