### ISSUE TITLE
[Feature request] Allow arguments pointing / restricting  build_runner to a certain directory or file

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/build#2815]
build_runner: ^1.10.0

In my large-sized project, running build_runner on the entire package, takes a considerable about of time, maybe 2 minutes to complete when I only want to change a single file. Even running it on watch takes a while to redo when a change is made. I know there are configurations values we can set in the build config file, but it was so confusing to me that I gave up 3 times trying to figure out how to restrict the directories that are being processed. Can we have a parameter we can add to the call to tell build_runner where to start crawling from?

**Comment by jakemac53** [comment]
Are you using build_runner for codegen only or for web? I am not sure exactly what feature you are asking for here - it is definitely true that the current configuration format is confusing and easy to get wrong. We could potentially help you with that or with identifying problematic builders, but need more information.

See https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md which may help for identifying problematic builders.

**Comment by ThinkDigitalSoftware** [comment]
For code generation. I want to be able to say something like `build_runner build path/to/file` and it'll only process the file or directory I choose

**Comment by jakemac53** [comment]
You can do `--build-filter=path/to/file`, does that work for you?

Note that it may generate more than just that file, if it depends on other generated files.

**Comment by ThinkDigitalSoftware** [comment]
> You can do `--build-filter=path/to/file`, does that work for you? Glob syntax is supported for paths, as well as `package:` uris.
> 
> Note that it may generate more than just that file, if it depends on other generated files.

This appeared to go through the entire project when I pointed it to one subdirectory. The files I have are for generating dio clients using retrofit. I don't see why it would have external dependencies. The only references outside the file are for model classes for the return types. no links to other files that need to be generated.

**Comment by jakemac53** [comment]
It will definitely still crawl all the files in your project - we need to know ahead of time all the files we possibly _could_ generate which requires knowing what files exist in the project.

But we should only generate the files you requested (or the files requested during the building of those files). Are you seeing some other behavior?

**Comment by ThinkDigitalSoftware** [comment]
Yes, after looking through the changed files in git, there were loads of files that had been modified or regenerated. I expected 1 or 2

**Comment by jakemac53** [comment]
Note that when resolving a dart file (which most code generators do), all transitive imports of that file must be generated. That is likely what is causing what you describe but I can't confirm that without a full repro.

**Comment by jakemac53** [comment]
I am going to close this for now, the --build-filter feature works as advertised as far as I can tell.

If you believe it is not and can create a simple repro to demonstrate that we can re-open the issue.
