### ISSUE TITLE
Could not find an option named "sound-null-safety"

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2832]
* Dart 2.9.3
* Build deps:
  * `build_runner 1.10.1`
  * `build_web_compilers 2.11.0`
* No other builders
* MacOSX
* n/a

Pubspec:

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  js: any
```

---

I was trying to write a minimal repro for a different issue, and when I switched to 2.9.3 I hit this issue and am unable to build at all. I get this error:

```
Precompiling executable... (12.2s)
Precompiled build_runner:build_runner.
[INFO] Generating build script completed, took 398ms
[INFO] Creating build script snapshot... completed, took 12.4s
[INFO] Building new asset graph completed, took 937ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
[SEVERE] build_web_compilers:ddc on package:js/js.ddc.module:
Error creating js|lib/js.ddc.dill
Error creating kernel summary for module:js|lib/js.ddc.dill

Response:--dart-sdk-summary=file:///usr/local/Cellar/dart/2.9.3/libexec/lib/_internal/ddc_sdk.dill --output=/private/var/folders/vb/k8ccjw095q16jrwktw31ctmm0000gn/T/scratch_spaceQtaMmf/packages/js/js.ddc.dill --packages-file=org-dartlang-app:///.dart_tool/package_config.json --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///usr/local/Cellar/dart/2.9.3/libexec/lib/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/vb/k8ccjw095q16jrwktw31ctmm0000gn/T/kernel_builder_wz4TSj/used_inputs.txt --no-sound-null-safety --source=package:js/js.dart
FormatException: Could not find an option named "sound-null-safety".
#0      Parser.validate (package:args/src/parser.dart:290:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:268:9)
#2      Parser.parse (package:args/src/parser.dart:88:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:326:42)
#4      computeKernel (file:///b/s/w/ir/cache/builder/sdk/utils/bazel/kernel_worker.dart:172:38)
#5      KernelWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/utils/bazel/kernel_worker.dart:69:26)
#6      AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:35:41)
#7      _rootRun (dart:async/zone.dart:1190:13)
#8      _CustomZone.run (dart:async/zone.dart:1093:19)
#9      _runZoned (dart:async/zone.dart:1630:10)
#10     runZoned (dart:async/zone.dart:1550:10)
#11     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:35:26)
<asynchronous suspension>
#12     main (file:///b/s/w/ir/cache/builder/sdk/utils/bazel/kernel_worker.dart:38:48)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by jakemac53** [comment]
This was a bad version of build_modules - it should have had a min sdk constraint.

I have published a revert release in version `2.11.1` - please try that

**Comment by evanweible-wf** [comment]
That fixed it, thanks!

**Comment by jakemac53** [comment]
Thanks for letting us know!

**Comment by ArpitPatel21** [comment]
The very same problem "could not find an option named "no-sound-null-safety" is happening with me... I tried the above solutions but could not fix it. 🥲

**Comment by jakemac53** [comment]
@ArpitPatel21 did you run a `dart pub upgrade`? what are your versions of `build_modules`, `build_web_compilers`, and the Dart SDK?

**Comment by Markfgui675** [comment]
Hi! I've having the same problem. I tried the above solutions, but doesn't worked.

My pubspec.yaml doesn't have `build_modules` and `build_web_compilers`

My Dart SDK version:

`
Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"
`

**Comment by stefan-sherwood** [comment]
_Could not find an option named "no-sound-null-safety"._

Same here.

`Dart SDK version: 3.0.1 (stable) (Tue May 16 11:57:19 2023 +0000) on "windows_x64"`

**Comment by stefan-sherwood** [comment]
> But I also recommend reading: [link](https://dart.dev/resources/dart-3-migration#100-sound-null-safety)

That's helpful in retrospect. But since that option was added automatically, wasn't visible, no solution in Google searches, project or source files, or searching the settings, it wasn't at all obvious how to resolve the problem.

**Comment by cehanshul** [comment]
For me flutter Additional args is already empty, but i still can't run flutter project

**Comment by gopikarp** [comment]
> _Could not find an option named "no-sound-null-safety"._
> 
> Same here.
> 
> `Dart SDK version: 3.0.1 (stable) (Tue May 16 11:57:19 2023 +0000) on "windows_x64"`
> 
> Edit: I was able to resolve it by going into the VS Code settings and search for _Dart: Flutter Run Additional Args_, which looked like this:
> 
> ![image](https://user-images.githubusercontent.com/2094779/240100735-65ca5884-c788-4b19-8b0d-8c00059180ed.png)
> 
> Clicking the X on the right side removed that option and resolved the problem.
This worked for me. Thank you very much

**Comment by yawebs** [comment]
> For me flutter Additional args is already empty, but i still can't run flutter project <img alt="Screenshot 2023-06-02 at 6 18 54 AM" width="765" src="https://user-images.githubusercontent.com/68245513/242757035-f0e8d6b9-2524-40e5-adb6-9acbac37fbaa.png">

Hi, where you able to resolve yours cause have been facing same issues
