### ISSUE TITLE
build_runner expose generate_for from as command-line paramater

### ISSUE THREAD

**Issue by KlausJokinen** [dart-lang/build#2859]
Would it be possible to expose `generate_for` as a command-line parameter when running build_runner?
This would allow developers to create custom scripts on what files build_runner should check for code generation.

Currently, I'm using `--build-filter` which speeds up the code generation a bit. but if I understand correctly `generate_for`  would be better.

The main reason for using these is not the performance but the analyzer won't "freak out" that much when there aren't so many changed files.

Related: https://github.com/dart-lang/sdk/issues/43166

**Comment by jakemac53** [comment]
You probably don't want to use `generate_for` for this purpose - changing that value requires re-generation of the asset graph in its entirely and we have to start the build over from scratch. We don't generally expose options on the command line which would have this effect.

Note that it would also end up _deleting_ any other generated outputs that are no longer generated, likely causing analyzer errors and churn.

The suggestion to use `generate_for` is more around permanent config to optimize all your builds and avoid running builders on files that you know they don't need to be ran on - but that won't really help the analyzer situation you describe.

**Comment by KlausJokinen** [comment]
Thanks, for clarification @jakemac53. I'll close this issue.
