### ISSUE TITLE
AssetNotFoundException: web_worker_channel|web/main.ddc.module for building multi-targets in one project

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/build#2874]
Dart version: 2.8.3~2.10.2

I try to build this project [web_worker_channel](https://github.com/matanlurey/web_worker_channel) with the [build.yaml](https://github.com/matanlurey/web_worker_channel/blob/master/build.yaml)

It causes the following error:
```
[SEVERE] build_web_compilers:ddc_modules on web/main.dart:

Bad state: No element
[SEVERE] build_web_compilers:entrypoint on web/main.dart:

AssetNotFoundException: web_worker_channel|web/main.ddc.module
[SEVERE] build_web_compilers:dart2js_modules on web/worker.dart:

Bad state: No element
[SEVERE] build_web_compilers:entrypoint on web/worker.dart:

AssetNotFoundException: web_worker_channel|web/worker.dart2js.module
``` 

Can any of your team help to solve this to build multi-targets with different compiler?
Because WebWorkers API cannot work with DDC mode, so we need the solution to work with WebWorkers API in Dev. env. within a same project just like @matanlurey's [web_worker_channel](https://github.com/matanlurey/web_worker_channel) project.

**Comment by jakemac53** [comment]
See this example https://github.com/dart-lang/build/blob/master/_test_null_safety/build.yaml - this is the easiest way to set up multiple apps with different ddc/dart2js config (you can ignore the build_vm_compilers|entrypoint configs in your case).

The important part is keeping all Dart files under the `$default` target - the build_modules package doesn't function poperly if you don't do that unfortunately.

On that target  you disable the `build_web_compilers:entrypoint` builder on that target, and explicitly enable it on the other targets while disabling everything else using the `auto_apply_builders: false` option.

**Comment by jumperchen** [comment]
@jakemac53 
Thanks for the helping information, now the project can work as expected. 👍
