### ISSUE TITLE
Should build_runner create files as readonly?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#289]
Most generated files should be updated only by rerunning the builder - we could help prevent accidentally editing these files by setting the files as readonly.

Some potential complications:

1. It's possible some folks write a Builder to 'bootstrap' a files, but not to maintain it. We don't really target this use case though.
2. If a file is readonly for some other reason we probably wouldn't want to overwrite it. The existing warning about deleting current files could be extended to handle this case, and if it's in the stored asset graph we should be safe in deleting it.

**Comment by jakemac53** [comment]
As far as I know we can't do this using dart:io anyways - technically we could run chmod or something but it doesn't seem worth the effort.

**Comment by natebosch** [comment]
😢 
https://github.com/dart-lang/sdk/issues/15078

Since that issue has been open for a while I don't anticipate it getting traction anytime soon. Not much use keeping this issue open.

oh well
