### ISSUE TITLE
Stack trace chaining is breaking some tests

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2894]
See the job here https://travis-ci.org/github/dart-lang/build/jobs/742878372

Something has changed in the stack trace package and/or vm such that we are seeing `package:stack_trace/src/stack_zone_specification.dart` when we do `Frame.caller().uri`, instead of the uri of the actual caller.

**Comment by jakemac53** [comment]
@natebosch did this get resolved?

**Comment by natebosch** [comment]
Not yet, I couldn't figure out what was happening in `stack_trace` and this fell off my radar

**Comment by jakemac53** [comment]
no worries, I was just wondering if we can close it :D

**Comment by natebosch** [comment]
Details of the `stack_trace` bug in https://github.com/dart-lang/stack_trace/issues/111

This stemmed from a change in the VM's stack traces inside the `Chain.capture` zone: https://github.com/dart-lang/sdk/issues/46326

**Comment by jakemac53** [comment]
Any idea what the state of this is? We don't have failing tests any more and it doesn't look like they are skipped to me.

I think maybe we can close the issue?

**Comment by natebosch** [comment]
The `Trace.current` is still broken which is what was impacting these tests. If we don't have tests impacted by that bug anymore we can close this issue. The `stack_trace` and SDK issues remain open.

**Comment by jakemac53** [comment]
It looks like we worked around the issue, going to close this one.
