### ISSUE TITLE
Consider using `ninja` as a build-system implementation

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#291]
Source: https://ninja-build.org/

Rationale:
* Ninja is cross-platform (C++), and a tiny dependency that could be bundled with the SDK.

* Ninja is extremely fast - probably fast enough that workers/iBazel isn't necessary.

* Ninja itself is based on tools emitting a ninja configuration from their own configuration.

> _This would work out well since we are exploring having a `build.yaml` or enhanced `pubspec.yaml`, so generating `.ninja` files in the background sort of works transparently here._

* Ninja is already used heavily by Chromium/Chrome, Dart, Flutter, and Fuchsia

This could eliminate the need for a "pure" Dart build system implementation, we'd only be responsible for generating a ninja file for a given package.

_Based on a discussion with @cbracken, @yjbanov, and @filiph._

**Comment by natebosch** [comment]
Definitely worth exploring. We've got thing abstracted in such a way that it might not be too difficult to make this an option.

We'd have to consider how it might stretch our focus.

**Comment by matanlurey** [comment]
I think we could experiment a bit - but this might be an alternative to writing a full build system using build_runner for example

**Comment by matanlurey** [comment]
I think it's unlikely we will focus on this anytime soon :D
