### ISSUE TITLE
Resolver PackageNotFoundException after releases from 18th Nov 

### ISSUE THREAD

**Issue by vaind** [dart-lang/build#2916]
The library I maintain ([objectbox](https://github.com/objectbox/objectbox-dart) uses code-generator (objectbox_generator package) employing build_runner: https://github.com/objectbox/objectbox-dart/blob/main/generator/build.yaml

This `objectbox_generator` is used by any `objectbox` users to generate binding code and it's also used in the `objectbox` package itself to generate the code for tests. That's where I've noticed the CI suddenly started to fail, with the only relevant change being the release of the latest build_* packages yesterday. Looks like `pub run build_runner` now tries to go into all the subdirectories (namely: examples). Maybe something to do with a different handling of the config? 

* `Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "linux_x64"`

### Before, when it worked fine:
```
+ build 1.5.0
+ build_config 0.4.2
+ build_daemon 2.1.4
+ build_resolvers 1.4.3
+ build_runner 1.10.4
+ build_runner_core 6.0.3
```
```pub run build_runner build
Precompiling executable... (8.5s)
Precompiled build_runner:build_runner.
[INFO] Generating build script completed, took 244ms
[INFO] Creating build script snapshot... completed, took 8.6s
[INFO] Building new asset graph completed, took 496ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Generating SDK summary completed, took 2.4s
[INFO] Running build completed, took 9.0s
[INFO] Caching finalized dependency graph completed, took 29ms
[INFO] Succeeded after 9.0s with 6 outputs (50 actions)

```

## Now, with the build broken:
```
+ build 1.5.1
+ build_config 0.4.3
+ build_daemon 2.1.4
+ build_resolvers 1.4.3
+ build_runner 1.10.6
+ build_runner_core 6.1.0
```
```
[INFO] Generating build script completed, took 256ms
[INFO] Creating build script snapshot... completed, took 11.4s
[INFO] Building new asset graph completed, took 630ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
[INFO] Generating SDK summary completed, took 2.9s
[SEVERE] objectbox_generator:resolver on example/flutter/objectbox_demo/lib/main.dart:

PackageNotFoundException: path_provider
[SEVERE] objectbox_generator:resolver on example/flutter/objectbox_demo/test_driver/app_test.dart:

PackageNotFoundException: flutter_driver
[SEVERE] objectbox_generator:resolver on example/flutter/objectbox_demo/test_driver/app.dart:

PackageNotFoundException: objectbox_demo
[SEVERE] objectbox_generator:resolver on example/flutter/objectbox_demo_desktop/lib/main.dart:

PackageNotFoundException: flutter
[SEVERE] objectbox_generator:resolver on example/flutter/objectbox_demo_sync/lib/main.dart:

PackageNotFoundException: path_provider
[INFO] Running build completed, took 9.6s
[INFO] Caching finalized dependency graph completed, took 30ms
[SEVERE] Failed after 9.7s
```

I can reproduce the same locally after upgrading to the latest versions of the packages. Not exactly sure which one it is though...

**Comment by jakemac53** [comment]
I am taking a look - fwiw the `example` directory has been included by default for the root package for a long time.

However, if I recall we try to automatically ignore any directory which is itself a package (by checking for a pubspec.yaml file I believe). My guess is that part got broken somehow, so I am checking into that.

**Comment by jakemac53** [comment]
It looks like this is actually a long standing issue that wasn't ever fixed if the packages in question aren't depended on (https://github.com/dart-lang/build/issues/560), but I can confirm that a previous version does build successfully.

The workaround for now is to use `build_runner_core` version `6.0.3`:

```yaml
dependency_overrides:
  build_runner_core: 6.0.3
```

**Comment by jakemac53** [comment]
Oh I see what is happening here, somehow the `example` dir from a _dependency_ is being picked up! (this is `objectbox-generator` specifically here).

**Comment by jakemac53** [comment]
Ok, so I have confirmed that in both cases (old version and new) all the `example` dir files are available as input sources, so that isn't the root of the problem.

**Comment by vaind** [comment]
> The workaround for now is to use build_runner_core version 6.0.3:

Thanks for taking a look (and the updates on WIP :+1: ). I'm aware of the workaround though obviously would prefer to get this fixed somehow - If you have a suggestion I'm ready to change the declarations in our `build.yaml`. Maybe we were exposing some undocumented behaviour that has changed :shrug: .

**Comment by jakemac53** [comment]
Ahah! so I figured out the behavior change - the difference is that we now accidentally throw in `canRead` calls if the asset id passed is an unknown package (cc @simolus3 ).

This is surfacing some likely undesirable behavior in the `objectbox` build - it is trying to run on all your examples, but without all their deps present. This is a result of the issue I linked earlier https://github.com/dart-lang/build/issues/560 which we don't really have a generalizable resolution for.

We did not intend to make this throw though (`canRead` is never supposed to throw, just return false), so I can work on a bug fix for that.

One thing you can do to work around this (and fix the build generally), is to add a `build.yaml` to your root directory, that excludes the `example` dir:

```yaml
targets:
  $default:
    sources:
      exclude:
        - example/**
```
