### ISSUE TITLE
Have an option in `PackageAssetReader` to return an empty Stream instead of throwing

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#2923]
https://github.com/dart-lang/build/blob/8fbdb405f17ff20a8391cb454d40e8cc32fe2883/build_test/lib/src/package_reader.dart#L112-L115

This makes it possible to use this in `testBuilder` where some packages are in-memory.

It's super nice to be able to just pass in trivial `sourceAssets` to `testBuilder`. But in my case, I need those files to import packages, which fails without also providing a `MultiPackageAssetReader` to the `reader` param.

`testBuilder` already combines the provided reader with other readers here.

https://github.com/dart-lang/build/blob/8fbdb405f17ff20a8391cb454d40e8cc32fe2883/build_test/lib/src/test_builder.dart#L180-L184

I just need it to not throw so the `inMemoryReader` result can be used!

...the alternative – using `test_descirptor` greatly increases the code complexity.

**Comment by jakemac53** [comment]
Can you clarify a bit more what you expect here and the use case? This reader is really only meant to be able to resolve things based on the package config you give it, and I think we probably would want to keep it that way.

It might be better to use `test_descriptor` to create a real package, add that to your existing package config, and then pass that package config?

Or you could create a hybrid reader that takes both an in memory reader and package reader and delegates to whichever as needed?

**Comment by kevmoo** [comment]
Added more details @jakemac53

**Comment by natebosch** [comment]
I don't follow this. Can you link a code example of what you were trying to accomplish when you hit this/

**Comment by natebosch** [comment]
Took a brief look at the usage. I don't think there was any real thought put into throwing vs returning empty stream when I wrote that API. I think it would be reasonable to switch it without any option, and I very strongly doubt anyone will be impacted. We don't expect anyone to catch errors, so changing from an error to any other behavior shouldn't be considered breaking. I have a PR out to see if any of our existing tests depend on this.
