### ISSUE TITLE
Code generation skips lib/main.dart

### ISSUE THREAD

**Issue by eernstg** [dart-lang/build#2924]
## Context

* Dart SDK Version: 2.12.0-79.0.dev
* What package(s) from this repo you are using, and the version:
  * build 1.5.1
  * build_config 0.4.3
  * build_daemon 2.1.4
  * build_resolvers 1.4.3
  * build_runner 1.10.6
  * build_runner_core 6.1.1
  * build_test 1.3.0
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  * reflectable, only.
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  * Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
  * N/A

## Issue

The reflectable package uses build_runner to generate code to support reflection. It has a 'build.yaml' that includes the following:

```
builders:
  reflectable:
    ...
    defaults:
      generate_for:
        exclude:
        - lib/**.dart
        include:
        - lib/main.dart
        ...
```

This has been used since August 2018 to enable code generation for flutter applications (where the entry point is expected to be 'lib/main.dart'). But code generation for 'lib/main.dart' suddenly stopped working recently (cf. https://github.com/google/reflectable.dart/issues/227).

I can see that the reflectable builder's `ReflectableBuilder.build` is not invoked in order to generate code for 'lib/main.dart', but other entry points are provided in such an invocation of as expected. So it is as if 'lib/main.dart' is suddenly auto-excluded. Has 'build_runner' been changed recently in a manner that makes it ignore 'lib/main.dart'?

Note that there is no need to use flutter in order to see that 'lib/main.dart' is excluded, it happens in a non-flutter package as well.

[reflectable227b.tar.gz](https://github.com/dart-lang/build/files/5617656/reflectable227b.tar.gz)

**Comment by jakemac53** [comment]
I will take a look here

**Comment by jakemac53** [comment]
Actually... looking at this @eernstg I don't believe this was ever intended to work.

The `exclude`s take priority over the `include`s - this matches the behavior of `bazel` rules which is where we inherited this from (and we try to maintain compatibility with).

Are you totally certain that this ever worked? The code in question has not been updated in some time.

**Comment by jakemac53** [comment]
Fwiw, you should be able to remove the `exclude` entirely, and your `include` config would just work and do what you are trying to do with that.

**Comment by eernstg** [comment]
The `build.yaml` which has `exclude` before `include` and includes 'lib/main.dart' has been in effect since commit 0b86e09a288d64e305de53d46d11d26afafc662c, Thu Aug 16 15:54:31 2018 +0200, and it has been working until recently.

It is in fact still working with [flutter_reflectable](https://github.com/eernstg/reflectable-flutter), which is using `build_runner` 1.10.2 and `build_runner_core` 6.0.1. `flutter create .` emits the warning 'Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2', but it seems unlikely that this should cause build_runner to treat 'lib/main.dart' differently.

Anyway, deleting the `exclude:` list works, and 'lib/main.reflectable.dart' is again generated. Thanks!

**Comment by jakemac53** [comment]
That is very weird, I don't know what could have been allowing that to work before.... 😕

**Comment by eernstg** [comment]
I saw `build_runner` 1.10.2 / `build_runner_core` 6.0.1 generate 'lib/main.reflectable.dart' yesterday, so it can be explored why it happens. But I guess it is not particularly important.
