### ISSUE TITLE
NoSuchMethodError: The getter 'uri' was called on null.

### ISSUE THREAD

**Issue by laitooo** [dart-lang/build#2931]
I was working with build_runner perfectly when suddenly it stopped working and kept giving me errors .

```
Dart SDK version: 2.10.1 (stable) (Tue Oct 6 10:54:20 2020 +0200) on "windows_x64"
my packages : 
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.22.0
  build_runner: ^1.10.0
  json_serializable: ^3.5.0
  analyzer: ^0.41.1
  json_annotation: ^3.1.0

```

I am using windows 10 
I am using flutter 1.22

error log:

> [INFO] Generating build script...
[INFO] Generating build script completed, took 741ms
[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 27.5s
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 2.0s
[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[SEVERE] json_serializable:json_serializable on lib/common_widgets/alert_screens.dart:
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
[INFO] 4.6s elapsed, 1/17 actions completed.
[INFO] 5.7s elapsed, 1/17 actions completed.
[INFO] 6.7s elapsed, 1/17 actions completed.
[INFO] 7.7s elapsed, 1/17 actions completed.
[INFO] 8.8s elapsed, 1/17 actions completed.
[INFO] 9.8s elapsed, 1/17 actions completed.
[INFO] 10.9s elapsed, 1/17 actions completed.
[INFO] 12.0s elapsed, 1/17 actions completed.
[INFO] 13.1s elapsed, 1/17 actions completed.
[INFO] 14.2s elapsed, 1/17 actions completed.
[INFO] 15.2s elapsed, 1/17 actions completed.
[INFO] 16.3s elapsed, 1/17 actions completed.
[INFO] 17.4s elapsed, 1/17 actions completed.
>[WARNING] No actions completed for 15.1s, waiting on:
>  - json_serializable:json_serializable on lib/common_widgets/app_logo.dart
>  - json_serializable:json_serializable on lib/common_widgets/app_tab_bar.dart
>  - json_serializable:json_serializable on lib/common_widgets/buttons_widgets.dart
>  - json_serializable:json_serializable on lib/common_widgets/cards.dart
> - json_serializable:json_serializable on lib/common_widgets/choice_group.dart
>  .. and 11 more
>[INFO] 18.8s elapsed, 1/17 actions completed.
>[INFO] 19.8s elapsed, 1/17 actions completed.
>[INFO] 20.9s elapsed, 1/17 actions completed.

The error just keeps going on like that and doesn't stop.
I thought this is an error form my code but tried new project and still same error.

Here's a code example of the model I am trying to generate : 

```import 'package:flutter/foundation.dart';
import 'package:json_annotation/json_annotation.dart';

part 'clinic.g.dart';

@JsonSerializable()
class Clinic {
  final int establishmentYear;
  final String workingHours;
  final String phoneNumber;
  final String location;

  Clinic({
    @required this.establishmentYear,
    @required this.workingHours,
    @required this.phoneNumber,
    @required this.location,
  });

  factory Clinic.fromJson(Map<String, dynamic> json) => _$ClinicFromJson(json);
  Map<String, dynamic> toJson() => _$ClinicToJson(this);
}
```

**Comment by jakemac53** [comment]
@laitooo can you run in verbose mode (with `-v`), that should show a stack trace so we can direct this issue to the right place (it could be a `json_serializable` issue, or a `build` issue).

I believe that json_serializable recently had a new release so my initial hunch is this is related to that, cc @kevmoo

**Comment by laitooo** [comment]
@jakemac53 hey, sorry but I can't right now , I upgraded flutter from 1.22.1 to 1.22.4 and that fixed it .
