### ISSUE TITLE
Consider adding warning for any builder which has an input extension of `.dart`.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2934]
While convenient, this leads to poor build times and bloated asset graphs. Relying instead on a file name convention for your builder (`.<package-name>.dart` is a great option) can significantly improve build times without requiring manual configuration for users - instead relying on file name conventions.

Related to https://github.com/dart-lang/build/issues/2933.

There are some legit use cases (build_modules for instance), so we would want some way of silencing the warning.

**Comment by jakemac53** [comment]
cc @natebosch wdyt?

**Comment by natebosch** [comment]
As long as it is only the builder author that sees this I think it could be OK. It feels a little vague and I do wonder if we can be more precise. Something like identifying when a builder only creates an output for some small percentage of it's inputs or similar.

**Comment by jakemac53** [comment]
> It feels a little vague

I am not sure I agree actually - I think this is a pretty common concrete issue that many builders have.

> Something like identifying when a builder only creates an output for some small percentage of it's inputs or similar.

This would be hard to warn about only for the builder author I think. It would also still have a lot of false positives in build_modules and the source gen combining builder for instance.

**Comment by natebosch** [comment]
> I think this is a pretty common concrete issue that many builders have.

We can concretely emit the warning, I don't think we can cleanly and concrete describe when it's OK or not OK.

If we give a warning, we should expect users will ask us "What does this warning mean, is it OK to ignore it?" and I don't think we can give a good answer there.

**Comment by jakemac53** [comment]
Yes I agree there will be false positives here. Probably the best advice we could give is "don't do this if you also use a resolver".

Unfortunately we don't know if they use a resolver or not before emitting the warning, and trying to check that would be difficult.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/issues/2934 might just resolve this well enough to not need to try and do anything here.

**Comment by jakemac53** [comment]
Closing this, lots of false positives and the source gen fix should resolve a lot of this.
