### ISSUE TITLE
Resolver: Cannot access a library via libraryFor when it exists in libraries

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#2936]
Will have a pointer to source here briefly.

`build_resolvers 1.4.4`

```dart
  final shelfLib = await resolver.libraries.singleWhere(
    (element) => element.source.uri == Uri.parse('package:shelf/shelf.dart'),
  );
```

**Comment by kevmoo** [comment]
https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/12f1af51c6953fadf3cf11ce3ac0411c2a4c2364/functions_framework_builder/lib/builder.dart#L91-L95

This code will likely be gone once the PR lands. Will update to checked-in code

**Comment by jakemac53** [comment]
turns out this was user error
