### ISSUE TITLE
How to breakpoint and debug build_runner ?

### ISSUE THREAD

**Issue by xiaocode337317439** [dart-lang/build#2945]
How to breakpoint and debug build_runner ? (Use idea or VSCode)
How do I break to debug code generated by extends GeneratorForAnnotation class？

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md#how-can-i-debug-my-builder

As far as debugging the generated code that should work just like debugging normal code, as long as you build to source and not cache. 

If you are building to cache then probably it would be easiest to build to an output directory and then run/debug from there (`pub run build_runner build -o <output-dir>`)

**Comment by jakemac53** [comment]
Closing this but you can continue to ask clarifying questions
