### ISSUE TITLE
Can't generate code with null safety

### ISSUE THREAD

**Issue by definev** [dart-lang/build#2966]
Thank you for taking the time to file an issue!

I have trouble with build_runner when i try to use null safety.

`
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] .dart_tool/build/entrypoint/build.dart:26:3: Warning: Operand of null-aware operation '?.' has type 'SendPort' which excludes null. - 'SendPort' is from 'dart:isolate'.  sendPort?.send(result);  ^Error: Cannot run with sound null safety, because the following dependenciesdon't support null safety: - package:build_runner_core - package:freezed - package:json_serializable - package:source_gen - package:build_config - package:build_runner - package:build - package:json_annotation - package:glob - package:pool - package:crypto - package:logging - package:watcher - package:build_resolvers - package:timing - package:graphs - package:package_config - package:yaml - package:analyzer - package:freezed_annotation - package:dart_style - package:pedantic - package:checked_yaml - package:pubspec_parse - package:build_daemon - package:args - package:io - package:convert - package:pub_semver - package:_fe_analyzer_shared - package:http_multi_server - package:shelf - package:built_value - package:built_collection - package:stream_transform - package:http_parser - package:mime - package:shelf_web_socket - package:web_socket_channel - package:quiver - package:cli_util - package:fixnumFor solutions, see https://dart.dev/go/unsound-null-safety.dart_tool/build/entrypoint/build.dart:24:44: Error: The parameter 'sendPort' can't have a value of 'null' because of its type 'SendPort', but the implicit default value is 'null'. - 'SendPort' is from 'dart:isolate'.Try adding either an explicit non-'null' default value or the 'required' modifier.void main(List<String> args, [_i6.SendPort sendPort]) async {                                           ^^^^^^^^
pub finished with exit code 78
`

* Dart SDK Version (`dart 2.12.0-141.0.dev`)
* build_runner version (`1.10.2`)

**Comment by jakemac53** [comment]
This was fixed in version `1.10.4` - please update to that version.

**Comment by definev** [comment]
`
[htlib_admin] flutter pub get
Running "flutter pub get" in htlib_admin...                     
Because no versions of freezed match >0.11.6 <0.12.0-∞ or >0.12.6 and freezed <0.1.1 depends on analyzer ^0.39.0, freezed <0.1.1-∞ or >0.11.6 <0.12.0-∞ or >0.12.6 requires analyzer ^0.39.0.
And because freezed >=0.1.1 <0.1.2 depends on analyzer ^0.39.2 and freezed >=0.1.2 <0.11.6 depends on analyzer ^0.39.4, freezed <0.11.6-∞ or >0.11.6 <0.12.0-∞ or >0.12.6 requires analyzer ^0.39.0.



And because no versions of freezed match 0.12.6 and freezed >=0.12.0 <0.12.6 depends on freezed_annotation >=0.12.0 <2.0.0, freezed <0.11.6-∞ or >0.11.6 requires analyzer ^0.39.0 or freezed_annotation >=0.12.0 <2.0.0.
Because no versions of freezed_annotation match >0.12.0 <2.0.0 and no versions of freezed_annotation match 0.12.0, freezed_annotation >=0.12.0 <2.0.0 is forbidden.

Thus, freezed <0.11.6-∞ or >0.11.6 requires analyzer ^0.39.0.

And because freezed 0.11.6 depends on analyzer ^0.39.5, every version of freezed requires analyzer ^0.39.0.


Because build_resolvers >=1.4.4 depends on analyzer >=0.40.1 <0.42.0 and build_resolvers >=1.4.0 <1.4.4 depends on analyzer ^0.40.1, build_resolvers >=1.4.0 requires analyzer >=0.40.1 <0.42.0.

Thus, freezed is incompatible with build_resolvers >=1.4.0.
And because build_runner >=1.10.3 depends on build_resolvers ^1.4.0, freezed is incompatible with build_runner >=1.10.3.

So, because htlib_admin depends on both build_runner ^1.10.11 and freezed any, version solving failed.
pub get failed (1; So, because htlib_admin depends on both build_runner ^1.10.11 and freezed any, version solving failed.)
exit code 1
`
I upgrade to latest version but it seem conflict ?

**Comment by jakemac53** [comment]
It looks like `freezed` needs to update to a newer analyzer - or possibly you need to update to a newer version of freezed that supports a newer analyzer.
