### ISSUE TITLE
Add resolveAsset(AssetId inputId, { ... })

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#297]
This makes it possible to analyze real files on the file system, with a similar API:

```dart
var testAsset = new AssetId('foo', 'test|test_files/test_lib.dart');
var resolver = await resolveSourceOf(testAsset);
```

**Comment by natebosch** [comment]
How does this differ from [`Resolver.getLibrary(assetId)`](https://www.dartdocs.org/documentation/build/0.9.3/build/Resolver/getLibrary.html)?

Is there a situation where some asset can't be resolved through an existing Resolver that this would be able to resolve?

**Comment by natebosch** [comment]
Ah nvm - this is when we don't already have a Resolver in a test :)

IMO we should call this `resolveAsset` - but otherwise I think it makes sense as a complement to `resolveSource`
