### ISSUE TITLE
Make multi-package builds easier

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#2981]
Basically, this is a follow-up to #2819 to evaluate whether we can allow _writing_ assets outside of the root package.

## Motivation

Let's say that I had a multi-package build layout in a mono repository. For instance, this could be a web app with a backend and a client split across 4 packages:

- a `client` package being built as a static website
- a `server` package with some rest apis. For additional complexity, let's say that the compiled client should be added to a `static/` folder in the server
- some shared `common` package with `json_serializable` classes or whatnot
- finally, a build-root package to tie everything together

For easy development and deployments, I want to build all components by running `build_runner build` in the root package. This should have similar effects as running the build in each of the project's packages.

This is not currently possible. For instance, `json_serializable` wouldn't be able to generate outputs in the `common` package because it's not the build root. I think that this is an unfortunate limitation that effectively makes multi-project builds impossible with `build_runner`.

## Suggestion

Currently, a builder (with `build_to: source`) is allowed to write assets in the root package. In addition, I'm proposing that a builder should be able to write assets if:

- the asset being written is in the same package as the primary input of the build step, and
- the enclosing package is a (potentially transitive?) `path`-dependency of the root package

## Considerations

To archive package-transparency to builders, we'd have to include every asset of `path` dependencies in the asset graph, potentially slowing down builds.
To make this an opt-in, there could also be an option in `build.yaml` listing which packages are meant to be a local part of the build. It would be an error to list a non-path dependency there.

I've also seen #2681 and its resolution, but I'm _not_ asking for `build_runner` to treat every package as root, so maybe this slightly more restrictive version stands a chance :D

**Comment by jakemac53** [comment]
In general principle I do agree it might be possible to come up with a scheme which allows for generating code to source in `path` dependencies. There are however a lot of difficult questions that would arise from that.

One such question is whether we still allow local builds within the path dependency. That local build would want to generate the same files that the larger builds would be generating, but it would not share an asset graph. Do you force all builds to go through a single package in the repo, so effectively the entire build is always driven from one place regardless of which package you are actually working in? How do you do that?

There is a related question for `apply_to: root` builders... you mention here they would not be treated as "root" but that means building the package locally versus as a part of a larger build would apply different builders, and this may or may not be what you want, and that is likely dependent on the builder.

One possible different answer here, is to allow overriding the "build_to: source" for the builders in these path dependencies - so they build to cache when building the package that depends on them. That keeps the builds separate so they aren't actually overwriting the same files, while keeping their generated code up to date as a part of the same build. But it also means they duplicate work, and you need to manually rebuild from the child package as the root to actually update its sources. It puts you in a weird spot where I think you can accidentally do the wrong thing easily (forget to update true generated sources).

I could also potentially imagine some sort of "dependent build" setup where you could make it so builds in one package automatically first ran builds in another package... but that seems like it would get complicated quickly, and it wouldn't make things faster just more automatic. It also presents other issues like race conditions around file watching and change notifications.

Overall, while I agree the current workflows here are not great, I haven't really come up with myself or had proposed a full solution to this that I am happy with so far.

> To archive package-transparency to builders, we'd have to include every asset of `path` dependencies in the asset graph, potentially slowing down builds.

Note that we do actually do this already, we load in and watch for changes on all sources from all path dependencies.

**Comment by simolus3** [comment]
Thank you for your quick and detailed answer!

> One such question is whether we still allow local builds within the path dependency. That local build would want to generate the same files that the larger builds would be generating, but it would not share an asset graph

Maybe we can have a bazel-style file to identify the root of the workspace? Maybe something like `buildroot.yaml` containing the packages that are part of a build. The build runner could then look for such file in parent directories, and, if it exists, run the parent build. It might be possible to only build the targets of the local package in the context of the build root too.

 But I wouldn't necessarily expect the path dependencies to have a dependency on `build_runner` at all.

> There is a related question for `apply_to: root` builders

This is indeed a much harder question to answer. But if we allow generating assets outside of the root package, is there really a compelling use for `apply_to: root`? Couldn't the sub-packages, knowing that they won't be root, just manually apply those builders to their targets? Those builders could still emit source assets, they wouldn't have to build to cache.

**Comment by jakemac53** [comment]
> Maybe we can have a bazel-style file to identify the root of the workspace? Maybe something like `buildroot.yaml` containing the packages that are part of a build. The build runner could then look for such file in parent directories, and, if it exists, run the parent build. It might be possible to only build the targets of the local package in the context of the build root too.

Ya I think that is at least heading in the general direction of the type of solution we would need here. We do really need a "root" package - and ideally that package would depend on all other packages. Maybe we create a synthetic "root" package or something in this scenario that depends on the listed packages. In that scenario I think we also need to enforce that the `buildroot.yaml` doesn't live inside of any existing package as well.

> But I wouldn't necessarily expect the path dependencies to have a dependency on `build_runner` at all.

Ya I don't know if you end up wanting some other globally activated package to manage running builds at that point.

> This is indeed a much harder question to answer. But if we allow generating assets outside of the root package, is there really a compelling use for `apply_to: root`? Couldn't the sub-packages, knowing that they won't be root, just manually apply those builders to their targets? Those builders could still emit source assets, they wouldn't have to build to cache.

One of the main usages is the compiler builders. The ones that actually drive compilation of apps (build_web_compilers:entrypoint as an example), apply to root. We typically only want to compile apps in the current package during builds. I am not sure how or if other types of builders are using this strategy.

**Comment by simolus3** [comment]
I've thought about this some more, and I think it's hard to provide something that can reasonably compete with just running `build_runner build` in every subdirectory. We can't even share an asset graph because it references build phases local to each entrypoint.

I still feel like we could safely allow writes to a path dependency, but users would have to manually apply compilers (or other `auto_apply: root` builders). They would pick some root package depending on all other packages, and only run the build in there. Running a build in other packages would cause all kinds of unwanted behavior, but maybe the solution is to just not make those packages depend on `build_runner` in the first place.

**Comment by jakemac53** [comment]
Ya, I could envision a strategy like that where you have a single root package that manages generating code for multiple packages. I am not sure whether it really has a lot of payoff for the potential complexity though... if those packages want to run tests through `pub run build_runner test` then they also need to support running build_runner themselves, but _not_ the codegen parts? I am not totally sure what the correct approach is there.

**Comment by simolus3** [comment]
I've thought about this some more, and it seems like there are just too many drawbacks to do this realistically. I have found a workaround for my build setup and that doesn't require me to build to source, so that should work.
