### ISSUE TITLE
Expand the constraints on shelf dependency

### ISSUE THREAD

**Issue by nickmeinhold** [dart-lang/build#2983]
I believe recent migration of [http](https://pub.dev/packages/http/versions/0.13.0-nullsafety.0) and [shelf](https://pub.dev/packages/shelf/versions/1.0.0-nullsafety.0) puts us in the situation described in [this comment](https://github.com/dart-lang/build/issues/2920#issuecomment-754896524) where we can't migrate a package that depends on both build_runner and http/shelf. 

@jakemac53 you mentioned that it might be possible to expand build_runner's dependency constraints - is it possible to do so for shelf?  

Thanks heaps!

**Comment by kevmoo** [comment]
@jakemac53 and @natebosch – when you get a chance!
