### ISSUE TITLE
Web compilers fail on libraries importing themselves

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#2984]
The build system can't compile Dart files importing themselves via an empty import.

### How to reproduce

Run `stagehand web-simple`. Then, replace `web/main.dart` with 

```dart
import 'dart:html';

import '' as self;

void main() {
  querySelector('#output').text = 'Your Dart app is running.';
  self.foo();
}

void foo() {}
```

Both `dart2js` and `dartdevc` happily compile that file, and there are no analysis errors, but a build fails with

```
[SEVERE] build_web_compilers:entrypoint on web/main.dart:
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import '' as self;` from build_repro|web/main.dart at 3:1
```

This example is obviously nonsense, but self-imports are useful to call a top-level function in a class which has a method with the same name. It's valid Dart too, so the builders shouldn't fail.

### Package versions

I'm using the following packages that might be relevant:

- `build_web_compilers`: 2.16.1
- `build_modules`: 3.0.3

**Comment by jakemac53** [comment]
Huh, I had no idea this was a thing lol.

It looks like we would need to special case the `AssetId.resolve` logic for the empty string to support this. I am actually surprised at how the relative uri resolution works for the empty string (I would have expected to to be equivalent to `./` or something), but that is beside the point :).

Also we would need to add some tests in to build_modules to make sure that this doesn't break any assumptions in there... I wouldn't be terribly surprised if it did.
