### ISSUE TITLE
I migrated to null safety and i cant run “flutter pub run build_runner build” without an error being thrown

### ISSUE THREAD

**Issue by namdiemefo** [dart-lang/build#2992]
i have added //@dart=2.9 to the top of all my .dart files but the build_runner wont do its thing without throwing this error

Warning: Operand of null-aware operation '?.' has type 'SendPort' which excludes null. - 'SendPort' is from 'dart:isolate'. sendPort?.send(result); ^Error: Cannot run with sound null safety, because the following dependenciesdon't support null safety: - package:build_runner_core - package:json_serializable - package:moor_generator - package:objectbox_generator - package:retrofit_generator - package:source_gen - package:build_config - package:build_runner - package:build - package:json_annotation - package:glob - package:pool - package:crypto - package:logging - package:watcher - package:build_resolvers - package:timing - package:graphs - package:package_config - package:yaml - package:analyzer - package:sqlparser - package:objectbox - package:dart_style - package:built_collection - package:code_builder - package:dio - package:tuple - package:retrofit - package:pedantic - package:checked_yaml - package:pubspec_parse - package:build_daemon - package:args - package:io - package:convert - package:pub_semver - package:ffi - package:quiver - package:moor - package:recase - package:_fe_analyzer_shared - package:built_value - package:http_parser - package:http_multi_server - package:shelf - package:stream_transform - package:mime - package:shelf_web_socket - package:web_socket_channel - package:cli_util - package:fixnum - package:synchronizedFor solutions, see https://dart.dev/go/unsound-null-safety.dart_tool/build/entrypoint/build.dart:44:44: Error: The parameter 'sendPort' can't have a value of 'null' because of its type 'SendPort', but the implicit default value is 'null'. - 'SendPort' is from 'dart:isolate'.Try adding either an explicit non-'null' default value or the 'required' modifier.void main(List args, [_i8.SendPort sendPort]) async {

**Comment by simolus3** [comment]
You're probably using an outdated version of `build_runner`. You need version `1.10.4` at minimum, the current version is `1.11.1`.

**Comment by jakemac53** [comment]
Feel free to follow up with additional questions if you have them - but upgrading should be the fix
