### ISSUE TITLE
build_runner hangs on "Creating build script snapshot......"

### ISSUE THREAD

**Issue by JostSchenck** [dart-lang/build#2998]
Dart SDK version: 2.12.0-259.8.beta (beta) (Tue Feb 2 15:59:29 2021 +0100) on "windows_x64"
using build_runner: ^1.11.1

Since some time, in a project of mine build_runner hangs on "Creating build script snapshot......" forever (hours). The only builder I'm using is from objectbox_generator package; it worked before (version 0.10.0), but even if I revert from version 0.11.0 back to it, build_runner hangs. I'm not experienced with build_runner (not that experienced with flutter either, I admit). I tried getting any output with -verbose but I do not get any more information on what it is hanging with.
Following advices I found for people having a hanging build_runner I did many a `flutter clean`, `flutter upgrade`, `flutter pub get`. I used the flutter install that used to work till somewhen last week, I used a fresh flutter from current dev branch (I'm developing for desktop, so stable is not an option for me).

I created a new flutter example application with flutter create, added the objectbox libraries and build_runner and ran it. Build_runner hangs at the same step.

I'm clueless and would be grateful for any ideas.

```flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 253ms

[INFO] Creating build script snapshot......
```

**Comment by jakemac53** [comment]
Can you try manually snapshotting the build script? You can do this with the following command:

`dart --snapshot=test.dart.snapshot $(pub run build_runner generate-build-script)`

**Comment by JostSchenck** [comment]
Thank you! I tried (`dart --snapshot=test.dart.snapshot $(flutter pub run build_runner generate-build-script)`). I have no idea why, because I didn't change anything knowingly, but my app as well as the test app I created now complain because of missing null safety. I tried adding a `--no-sound-null-safety`, but this didn't help.

```
Failed to precompile build_runner:build_runner:
/C:/Users/Jost%20Schenck/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/build_runner-1.11.1/bin/build_runner.dart:89:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:io
 - package:build_runner
 - package:build
 - package:glob
 - package:pool
 - package:crypto
 - package:watcher
 - package:build_config
 - package:build_resolvers
 - package:timing
 - package:graphs
 - package:package_config
 - package:yaml
 - package:code_builder
 - package:dart_style
 - package:build_daemon
 - package:http_multi_server
 - package:shelf
 - package:pub_semver
 - package:pubspec_parse
 - package:analyzer
 - package:convert
 - package:http_parser
 - package:shelf_web_socket
 - package:web_socket_channel
 - package:_fe_analyzer_shared
 - package:checked_yaml
 - package:json_annotation
 - package:cli_util

For solutions, see https://dart.dev/go/unsound-null-safety
pub finished with exit code 1
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

<-- snip -->
```

**Comment by jakemac53** [comment]
That is very weird.... build_runner should be on language version `2.10` and not be opted in to null safety.

**Comment by JostSchenck** [comment]
I have no idea what happened, but after deleting `AppData/Pub/Cache`, at least creating the snapshot manually `dart --snapshot=test.dart.snapshot $(flutter pub run build_runner generate-build-script)` worked (without explicit `--no-null-safety`). 

However, `flutter pub run build_runner build` will still just hang on "Creating build script snapshot".

**Comment by jakemac53** [comment]
Can you link a full repro via a gist or github repo or something that we can use to try and use to diagnose this?

**Comment by JostSchenck** [comment]
I uploaded my test app to https://github.com/JostSchenck/myapp2.git .
I did a fresh checkout from there and the problem persists. Thank you very much for your help.

**Comment by jakemac53** [comment]
I wasn't able to repro the issue on my linux box - so I tried opening up my windows box and I am able to reproduce this it looks like there.

So probably something to do with windows and how the snapshot process is exiting or something will investigate.

**Comment by jakemac53** [comment]
Ok, it looks like this is logging some warnings on stdout, which we are not listening to. If I just drain those messages then the process does exit as expected.

@natebosch do you think we should log these? Here is an example output https://gist.github.com/jakemac53/520c313ea143a2bc2598fe5a5d532e52.

**Comment by natebosch** [comment]
> @natebosch do you think we should log these?

I would expect that some of the time it's actionable and some of the time it isn't. How about if we log a message at info level like "There was output on stdout while compiling the build script snapshot. Run with --verbose to see the output".

If the process fails we should probably log both stdout and stderr.

I don't think it needs to be a warning level. Builder authors can hopefully use that as a signal to look deeper if something strange is happening.


WDYT?

**Comment by jakemac53** [comment]
That sounds good to me, logging at the `fine` level effectively then for anything on `stdout`, and then an `info` message with an extra newline to make sure it doesn't get overwritten by other info logs.

I don't want to double-log everything so I think in the failure case I might just log an error telling you to rerun with `--verbose` flag?

**Comment by JostSchenck** [comment]
@jakemac53 Great, thanks a lot for your fixing this so quickly :)
