### ISSUE TITLE
Add a way to regenerate only 1 file or 1 folder

### ISSUE THREAD

**Issue by subzero911** [dart-lang/build#3004]
I use MobX. If I changed 1 Store, I don't want to regenerate the whole project and wait for 3-4 minutes. I want just to change an appropriate .g file

It would be nice to have a command line parameter
`flutter pub run build_runner build --target=./profile.dart`
or
`flutter pub run build_runner build -t models`

**Comment by simolus3** [comment]
`build_runner build` is incremental by default, it only runs build steps for changed inputs.

If you have a project where the input file to MobX has many dependencies (e.g. many transitive imports), changing any imported file triggers a rebuild. Maybe you could check if that is the case?
To speed up builds, you can also limit what a specific builder is allowed to see with a [build.yaml](https://pub.dev/packages/build_config) file. For expensive builders, using `generate_for` can help sometimes.

**Comment by jakemac53** [comment]
There is also the `--build-filter` command that you can use to filter some outputs, but it doesn't always do what you want (all inputs to that output will still be built, and if I recall build-to-source builders always run?)

**Comment by jakemac53** [comment]
I am going to close this as the `--build-filter` argument is designed for this use case. There were some specific decisions made with regards to that which might not always be intuitive, and end up building more than you might expect, but I don't think we want to introduce further options here.

In general the best thing to do to speed up builds is specifying the `generate_for` option as @simolus3 suggested.
