### ISSUE TITLE
build_runner and build target must agree on dependencies

### ISSUE THREAD

**Issue by alanknight-wk** [dart-lang/build#3012]
I'm not sure if this is known, working as intended, or if there's anything that could be done about it, but I certainly didn't realize it.

build_runner, or at least the generated build script, runs in the context of the containing package. So it uses the dependencies from the local pubspec. Probably it has to so that it's picking up the correct version of the compiler, if nothing else. But it means that if build_runner (maybe just build_runner_core?) upgrades a dependency that has a breaking change, then this is also a breaking change for build_runner if the target shares that dependency.

I noticed this in testing out a build_runner_core issue. The bleeding edge build_runner_core version uses glob 2.0.0. My package, and some of its dependencies also use glob. So if I run build_runner it crashes telling me that it can't find an import file that's new in glob 2.0. To run build_runner properly I would have to upgrade my package and all its dependencies to use glob 2.0.0. 

Fortunately, in this case I didn't actually have to do that, a little creative fiddling with the pub cache was enough, but it could have been a significant obstacle if the changes to glob were larger.

**Comment by jakemac53** [comment]
I think this was probably just a result of using `dependency_overrides` on one or both of build_runner_core or build_runner? Both today require `glob` version `2.0.0`, but that wouldn't be enforced if you have overrides.

**Comment by natebosch** [comment]
I don't know if this is actionable.

It's true that we use a single pub solve for `build_runner` and your package so you can't have conflicts between `build_runner` constraints and your own. In the old days `pub` had special constraints that were more limited in their impact but were tied to the SDK. `build_runner` chose instead to rely entirely on the pub solve, but that means it also imposes a larger surface area of dependency constraints if you hope to get any specific version.

Changing this would be difficult and is probably out of scope. We'd need to be able to handle our own separate pub solve for the build constraints which are different from the normal constraints.  We'd also have all the pain points of manually testing and maintaining compatibility between the higher level wrapper that can set up that second pub solve with the inner build system that does the real work. We've had pain with this type of thing in `webdev`.

**Comment by alanknight-wk** [comment]
@jakemac53 I think the way that it exhibited, as a compile-time build error, is because it's a dependency error. But if it was a regular dependency it would just mean tell me that at pub-time (which sounds more fun than it is)

@natebosch Yeah, I don't know how you'd avoid that in general. The only actionable thing is likely to be aware that upgrading build dependencies to require a breaking change release is also a breaking change to build_runner.

**Comment by jakemac53** [comment]
I am still not quite understanding myself how this became a compile time error though? Or was it that some other dependency wasn't setting an upper bound on `glob`?

I don't think we can really do anything about the general pub solve issues, we import user code into the build script and so must be a part of the users pub solve. But we would expect this to result in failed pub get and not a compile time error.

**Comment by jakemac53** [comment]
Going to close this but we can re-open if we think there is something actionable to do here.
