### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by felixwortmann** [dart-lang/build#3026]
Please migrate this package to Null-Safety.
https://dart.dev/null-safety/migration-guide

**Comment by MarlonJD** [comment]
We cannot using build runner on flutter 2.0.0 or 2.0.1, we need update

**Comment by simolus3** [comment]
Duplicate of #2920. The `build`, `build_resolvers` and `build_test` packages have been migrated and will be released in the next weeks (afaik).

> We cannot using build runner on flutter 2.0.0 or 2.0.1, we need update

You can use the current `build_runner` with Flutter 2.
