### ISSUE TITLE
Infinite loop on Build-runner build after flutter upgrade 2.0

### ISSUE THREAD

**Issue by AbhijeetRajputMB** [dart-lang/build#3032]
my pubspec.yaml

name: flutter_2021_quickstart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  analyzer: null
  auto_route: ^0.6.9
  badges: ^1.1.6
  basic_utils: null
  built_collection: ^4.3.2
  built_value: null
  cached_network_image: null
  carousel_slider: ^3.0.0
  chopper: ^3.0.6
  configurable_expansion_tile: ^1.0.0
  connectivity: ^2.0.2
  convert: null
  country_code_picker: ^1.7.0
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  dotted_border: ^1.0.7
  equatable: ^1.2.5
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_cache_manager: null
  flutter_hooks: ^0.15.0
  flutter_html: ^1.2.0
  flutter_open_whatsapp: ^0.1.2
  flutter_rating_bar: ^3.2.0+1
  flutter_rounded_date_picker: ^1.0.5+1
  flutter_share: ^1.0.5
  flutter_svg: null
  flutter_swiper: ^1.1.6
  flutter_twitter_login: ^1.1.0
  flutter_typeahead: ^2.0.0
  flutter_webview_plugin: ^0.3.11
  get_it: ^6.0.0
  google_fonts: ^1.1.2
  google_maps_flutter: ^1.1.1
  google_sign_in: ^4.5.9
  hive: ^1.4.4+1
  http: ^0.12.2
  image_picker: ^0.6.7+22
  injectable: ^1.2.0
  logger: ^0.9.4
  modal_bottom_sheet: ^1.0.0+1
  observable_ish: ^2.1.5
  path_provider: ^1.6.18
  pin_code_fields: ^6.1.0
  shared_preferences: null
  shimmer: ^1.1.2
  stacked: ^1.7.7
  stacked_hooks: ^0.1.3+2
  stacked_services: ^0.6.6
  tabbar: null
  timeline_tile: null
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: null
  build_runner: null
  build_runner_core: null
  built_value_generator: null
  chopper_generator: null
  flutter_launcher_icons: null
  hive_generator: null
  injectable_generator: null
  lint: null

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/ar.json
    - fonts/
  
  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/proximanova.ttf
        
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by jakemac53** [comment]
@AbhijeetRajputMB can you describe the issue in detail please? How would I reproduce the problem?

**Comment by AbhijeetRajputMB** [comment]
Please Copy my pubspec config and 
run flutter pub run build_runner build --delete-conflicting-outputs in terminal

Terminal get same output in loop

**Comment by jakemac53** [comment]
This looks like a bug in the `auto_route_generator` package as that is the builder that is not completing. I would file an issue on that package and see if they can debug this.

**Comment by AbhijeetRajputMB** [comment]
> This looks like a bug in the `auto_route_generator` package as that is the builder that is not completing. I would file an issue on that package and see if they can debug this.

Ya sure thank you
