### ISSUE TITLE
Support for node.js

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/build#3034]
I am a user of [build_node_compilers](https://pub.dev/packages/build_node_compilers) that currently does not work on dart 2.12 (or at least not in a simple way and with no ability to use any null safe code).

It is not clear whether build_node_compilers will be maintained in the future (no response from maintainer) and I'd like to know what are the dart team plan on node support in the future.

It is actually a nice solution that allow using dart on servers that only support node.js. I have been using it on firebase functions and alibaba with great success but my fear is that my solution in place (for more than 2 years now) cannot be maintained in the future.

Maybe that is not the right repository to ask this (well I'd love to see build_node_compilers next to build_web_compilers)...Thanks anyway!

**Comment by jakemac53** [comment]
We do not have any plans for official node support in the `build` family of packages at this time. We can leave this issue open but there isn't much demand for it and we have no expertise in the matter nor use cases of our own. This is best served imo as a community supported package, it can closely follow the example set out by build_web_compilers though.

**Comment by alextekartik** [comment]
Thanks for the info @jakemac53 . I completely understand the choice, I guess I'll learn about compilers!
