### ISSUE TITLE
Dependency issue with latest build_runner and shelf_web_socket

### ISSUE THREAD

**Issue by erf** [dart-lang/build#3039]
Missing some or all of the above might make the issue take longer or be impossible to act on.

I'm having a dependency issue with   `build_runner: ^1.11.5` and `shelf_web_socket: ^1.0.0`.

Dart SDK version: 2.13.0-77.0.dev (dev) (Thu Feb 25 00:41:11 2021 -0800) on "macos_x64"

Output:

```
dart pub get
Resolving dependencies...
Because build_runner 1.11.5 depends on shelf_web_socket ^0.2.2+4 and no versions of build_runner match >1.11.5 <2.0.0, build_runner ^1.11.5 requires shelf_web_socket ^0.2.2+4.
So, because fakkt depends on both shelf_web_socket ^1.0.0 and build_runner ^1.11.5, version solving failed.
exit code 1
```

**Comment by jakemac53** [comment]
I am working on publishing the versions that allow the latest shelf_web_socket now - see https://github.com/dart-lang/build/pull/3040.
