### ISSUE TITLE
Failed to precompile build_runner:build_runner with analyzer 1.2.0

### ISSUE THREAD

**Issue by nileshbhakre** [dart-lang/build#3058]
Failed to precompile build_runner:build_runner:
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/dart/constant/evaluation.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/dart/error/ffi_code.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/manifest/manifest_warning_code.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/pubspec/pubspec_warning_code.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/string_source.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/dart/element/type.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/dart/element/scope.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/services/lint.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/summary/api_signature.dart: Error: The control character U+0000 can only be used in strings and comments.
/F:/flutter_sdk/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/dart/error/syntactic_errors.dart: Error: The control character U+0000 can only be used in strings and comments.
________________________________________________________________________________________________________________________________________
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.18362.592], locale en-US)
    • Flutter version 2.0.3 at F:\flutter_sdk\flutter_windows_2.0.3-stable\flutter
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\nilesh\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\nilesh\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\nilesh\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\nilesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

**Comment by jakemac53** [comment]
cc @scheglov any ideas?

**Comment by scheglov** [comment]
The error comes from CFE, I think.
But maybe something is wrong with the downloaded code for `package:analyzer`.
I checked that `src/summary/api_signature.dart` does not have `0x00` in my local copy, and on pub.dev (version `1.2.0`).
So, it might be a bug on the local file system.

**Comment by jakemac53** [comment]
@nileshbhakre try a `flutter pub cache repair`?

**Comment by nileshbhakre** [comment]
I have fixed the issue with flutter upgrade..I am closing this issue
