### ISSUE TITLE
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart

### ISSUE THREAD

**Issue by oligazar** [dart-lang/build#3060]
* Dart SDK Version (`2.13.0-134.0.dev (dev)`)
* `build_runner: ^1.12.2`
* Using MacOSX

After running `flutter packages pub run build_runner build --delete-conflicting-outputs` I'm getting:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 481ms

[INFO] Creating build script snapshot......
[WARNING] stderr: ../../../../../.pub-cache/hosted/pub.dartlang.org/source_gen-0.9.10+4/lib/src/library.dart:41:17: Error: The getter 'typeAliases' isn't defined for the class 'CompilationUnitElement'.
[WARNING] stderr:  - 'CompilationUnitElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/dart/element/element.dart').
[WARNING] stderr: Try correcting the name to the name of an existing getter, or defining a getter or field named 'typeAliases'.
[WARNING] stderr:       yield* cu.typeAliases;
[WARNING] stderr:                 ^^^^^^^^^^^
[INFO] Creating build script snapshot... completed, took 7.9s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0
  google_maps_flutter: ^2.0.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  dio: ^3.0.10
  uuid: ^3.0.2
  package_info: ^2.0.0
  intl: ^0.17.0
  intl_translation: ^0.17.10+1
  sqflite: ^2.0.0+3
  geolocator: ^7.0.1
  built_value: ^7.1.0
  path_provider: ^2.0.1
  maps_toolkit: ^1.1.0+2
  url_launcher: ^6.0.2
  firebase_core: ^1.0.2
  firebase_crashlytics: ^1.0.0
  action_cable_stream: ^0.0.3
  background_locator: ^1.5.0+1
  cupertino_icons: ^1.0.2

dependency_overrides:
  analyzer: ^0.41.0
  intl: ^0.17.0-nullsafety.2
  google_maps_flutter: ^2.0.1
  built_value: ^8.0.0
  package_config: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  built_value_generator: ^8.0.4
```

What the error means and how it should be addressed?

**Comment by jakemac53** [comment]
This is almost certainly because of your `dependency_overrides`. Any time you use these you are overriding the dependency constraints in packages, causing issues like this.

Try removing the overrides, or specifically the `analyzer` override.

**Comment by oligazar** [comment]
@jakemac53 Thanks for the reply. Any time I change smth in `dependency_overrides` I no longer can run `dart pub get` and compile my build. This configuration is what I ended up after lots of attempts. 

Would be much helpful if the error message point exactly on the problematic dependency so I can start the process again from there

**Comment by jakemac53** [comment]
> Would be much helpful if the error message point exactly on the problematic dependency so I can start the process again from there

The dependency solves are very complex, so the error messages can be verbose, but they do contain all the necessary information to understand the problem. If you can post yours we can help decipher it.
