### ISSUE TITLE
Cannot resolve flutter i18n classes inside gen_I10n using build_runner

### ISSUE THREAD

**Issue by SandroMaglione** [dart-lang/build#3064]
Hi,

I am working on [`repo_case`](https://pub.dev/packages/repo_case), which uses code generation.

When generating code, I use the following:
```dart
/// parameter: [ParameterElement]
/// type: [DartType]
final parameterReturnType = parameter.type.getDisplayString(withNullability: true);
```
When the `ParameterElement` is of type `AppLocalizations?` from [flutter internationalization](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages), which is imported from `import 'package:flutter_gen/gen_l10n/app_localizations.dart';` inside `.dart_tool`, the value of `parameterReturnType` in the code above is `dynamic`, not `AppLocalizations?`.

Is it a problem in the build generation or should I use another function to extract the type `AppLocalizations?`?
***
`Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "windows_x64"` - `dart --version`
```yaml
  build_runner: ^1.11.1
  build: ^2.0.0 
  source_gen: ^1.0.0
  analyzer: ^1.1.0
```

**Comment by SandroMaglione** [comment]
The idea is that the package should take a method:
```dart
String getLocal(AppLocalizations? appLocalizations);
```
And extract the type of the parameter (`appLocalizations`), which should be `AppLocalizations?`.

I use `parameter.type.getDisplayString(withNullability: true)` to extract the type of the parameter.

The problem is when I call `getDisplayString` and the type of the parameter is `AppLocalizations?`, the returned `String` is `"dynamic"` instead of `"AppLocalizations?"`.

[Here you can find an example](https://github.com/SandroMaglione/repo_case.dart/blob/ca56f7fc56136251b99ff1b42de231921a2fb342/example/lib/domain/repository/user_repository.rc.dart#L128). As you can see, all the other types are correct, while where it should be `AppLocalizations?` is instead `dynamic` 🤔

**Comment by jakemac53** [comment]
I think this means it wasn't able to resolve the `AppLocalizations` type. Is that a generated class by chance?

**Comment by natebosch** [comment]
> Is that a generated class by chance?

Yes. But not generated by a `Builder`.

https://flutter.dev/docs/development/accessibility-and-localization/internationalization


@SandroMaglione - does that class get generated in a file on disk, or does it only exist transiently within the flutter tools? If the latter, you might need to drop a stub for it or something on disk. If the former, have you run that code generation step?

**Comment by SandroMaglione** [comment]
@natebosch the class is generated automatically by flutter on the first launch of the app on a device/emulator. It is created inside `.dart_tool/flutter_gen`:

![Screenshot 2021-03-31 204005](https://user-images.githubusercontent.com/10065056/113194492-7f4a7080-9261-11eb-8cbd-ad067f2af4ac.png)

I think the file is updated on each launch. However, once generated the class is available and recognized by all the files in the `lib` folder. 

I run the code generation and the class is available. Nonetheless, the type is still resolved as `dynamic`.

**Comment by jakemac53** [comment]
My guess here would be that the build system can't actually see this file. Is this package depended on in your pubspec?

**Comment by SandroMaglione** [comment]
@jakemac53 What do you mean by 'depended on'?

My package only takes the type from the source/annotated class and builds a new file (class) with the same type. It is intended to work for any type with no specific dependency. This is the first time it fails to resolve a type.

**Comment by jakemac53** [comment]
> @jakemac53 What do you mean by 'depended on'?

I mean in the `dependencies` (or `dev_dependencies`) of the root package (transitive deps are also allowed).

Do you have an explicit dependency on this package under `.dart_tool/flutter_gen/gen_i10n` in your pubspec?

This sounds like it is probably more of an issue with how flutter sets up that package. We have had a lot of issues with it in the past because its a very non-standard approach and something only flutter itself understands afaik.

**Comment by SandroMaglione** [comment]
Yes, in the application's `pubspec.yaml` I import `flutter_localizations` from the flutter sdk:
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```
Furthermore, the `.dart_tool/flutter_gen` itself contains a auto-generated `pubspec.yaml`:
```yaml
# Generated by the flutter tool
name: synthetic_package
description: The Flutter application's synthetic package.
```
![Screenshot 2021-04-02 063401](https://user-images.githubusercontent.com/10065056/113380795-73ec6780-937d-11eb-8114-8752d5d895e4.png)

Do you think the issue can be solved? Should I open an issue on the flutter repository?

**Comment by natebosch** [comment]
You would need something in your pubspec like

```yaml
dependencies:
  synthetic_package:
    path: ./.dart_tool/flutter_gen
```

I'm not sure if that is likely to cause other problem.

It looks like `flutter_localizations` chose a generation strategy incompatible with `build_runner` in general. You might want to ask them for a compatible strategy. We can't resolve any code that isn't in your package and dependencies _as they are understood by pub_. If the flutter build tool is generating synthetic sources and only surfacing them internally within its own build, then it won't work with `build_runner`.

**Comment by SandroMaglione** [comment]
I see. I tried your solution but there is another problem with how the code gets generated:
```
The current Dart SDK version is 2.12.1.



Because my_app depends on synthetic_package from path which requires SDK version <2.0.0, version solving failed.
pub get failed
```
Flutter generates a `pubspec.yaml` with the following content:
```yaml
# Generated by the flutter tool
name: synthetic_package
description: The Flutter application's synthetic package.
```
I [opened an issue](https://github.com/flutter/flutter/issues/79776) on the flutter repository about this.

**Comment by jakemac53** [comment]
Closing this issue as it seems stale now - the path dependency should hopefully resolve things once there is a valid pubspec in that generated directory.
