### ISSUE TITLE
build_runner_core: StackOverflow on AssetGraph._addGeneratedOutputs with specific build_extensions

### ISSUE THREAD

**Issue by KalilDev** [dart-lang/build#3068]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* /home/pedro/projects/template_generator/build.yaml
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * build_runner_core 6.1.12
  * build_runner 1.12.2
* I wanted to create an builder which consumes .template.dart files and produces an .dart file with the source being used to generate some boilerplate
* Whether you are using Windows, MacOSX, or Linux: Linux
* Whether you are using Chrome, Safari, Firefox, Edge: Not applicable
* Any other packages or constraints we should know about: no

When i started working on my code generator, i generated .t.dart files from the .dart files, but i wanted to generate an .dart from a .template.dart file, so i changed the `build_extensions` on `build.yaml` to `build_extensions: { '.template.dart': ['.dart'] }`, and the error ocurred. I tried with other extensions in the form of `.[a-z|A-Z].dart` and the same error occurs.

stdout and stderr of `pub run build_runner build -v`: [error.log](https://github.com/dart-lang/build/files/6252843/error.log)

**Comment by jakemac53** [comment]
@KalilDev just to confirm do you have identical build extensions in your builder code? You can also try running `pub run build_runner doctor` to do some basic diagnostic checks.

**Comment by KalilDev** [comment]
> @KalilDev just to confirm do you have identical build extensions in your builder code?

I would expect not, my build.yaml contains the following `build_extensions` mapping: `build_extensions: { '.t.dart': ['.dart'] }`. But, after running `pub run build_runner doctor`, as you suggested, the result was the following:

```pub run build_runner doctor
[INFO] Generating build script completed, took 513ms
[WARNING] Builder bug_generator:builder_bug uses input extension .dart which is not specified in the `build.yaml`
```

Are extensions that end with `.dart` but are not exactly `.dart` not supported?

I created an minimum reproducible case [at this repository](https://github.com/KalilDev/builder_issue_repro) and the error from `pub run build_runner -v` was [the following](https://github.com/dart-lang/build/files/6259187/log.txt)

**Comment by jakemac53** [comment]
@KalilDev any extensions are supported, but the problem you are likely into here is that the input extension and output extension are identical, which is causing our code to get in an infinite loop (that should probably be fixed on our end also though).

It looks like you need to request support from the `source_gen` package to allow you to configure the input extension, so that you can set it at `.template.dart`. It hard codes `.dart` as the input extension it looks like without a way to override that.

**Comment by KalilDev** [comment]
Oh, alright then. Thanks a ton! Should i close this issue, or should it still be open until the infinite loop is fixed?

**Comment by jakemac53** [comment]
Lets keep it open until we fix that issue

**Comment by jakemac53** [comment]
Ah so it looks like we do validate the `build.yaml` config for this, but we don't do the same for the actual build extensions configured by the builder.
