### ISSUE TITLE
Cannot generate files on Windows

### ISSUE THREAD

**Issue by kil0ba** [dart-lang/build#3074]
When i try to generate files on Windows is fails then tries to move them to the correct folder:

`FileSystemException: Cannot create file, path = 'c:\work\mobileapp\.dart_tool/build/generated/dol/lib/app/ui/screens/main_tabs_screen/tabs/services_tab/abonent_services/service_categories_screen/services_screen/subscription_details_screen/subscription_details_screen_store.store_generator.g.part' (OS 
Error: The system cannot find the path specified. `

In the error you can see how the code generator switches to slashes for unix (/ instead of \\)

I tried flutter clean to reinstall all deps, but it doesn't help

Has anyone met this problem?

Dart 2.10.5
Deps:
  rxdart: ^0.23.1
  provider: ^4.0.1
  get_it: ^4.0.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  http: ^0.12.0+4
  http_interceptor: ^0.2.0
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  path_provider: ^1.6.10
  flare_flutter: ^2.0.1
  flutter_slidable: ^0.5.4
  intl: ^0.16.0
  flutter_markdown: ^0.3.5
  conditional_builder: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  dio: ^3.0.9
  flutter_signature_pad: ^2.0.2
  barcode_scan: 3.0.1
  flutter_web_browser: ^0.11.0
  package_info: ^0.4.0+13
  image_picker: ^0.6.7+21
  multi_image_picker: ^4.7.12
  file_picker: ^1.13.3
  mime: ^0.9.6+3
  uuid: ^2.0.4
  open_file: ^3.0.1
  image: ^2.1.13
  pdf: ^1.9.0
  printing: ^3.4.0
  url_launcher: ^5.5.2
  auto_size_text: ^2.1.0
  back_button_interceptor: ^4.3.1
  basic_utils: ^2.6.3
  html: ^0.14.0+4
  store_redirect: ^1.0.2

  build_runner: ^1.10.11
  mobx_codegen: ^1.1.2

Using Mobx_codegen

**Comment by jakemac53** [comment]
Did this start breaking in a recent release or was this your first time trying it?

**Comment by kil0ba** [comment]
@jakemac53 first time trying, before that I worked on a mac

**Comment by jakemac53** [comment]
> @jakemac53 first time trying, before that I worked on a mac

ok, I know that in general things do work on windows, so I wonder if there is something specific about your windows machine that is somehow causing this...? What program are you using to run build_runner, maybe that also has something to do with it?

**Comment by kil0ba** [comment]
I tried through powershell, comand prompt and git bash terminal with comand "flutter packages pub run build_runner build / watch".

I don't know how specific the amd ryzen processor is, but what I have is what I have

**Comment by kil0ba** [comment]
> ok, I know that in general things do work on windows, so I wonder if there is something specific about your windows machine that is somehow causing this...? What program are you using to run build_runner, maybe that also has something to do with it?

I tried through powershell, comand prompt and git bash terminal with comand "flutter packages pub run build_runner build / watch".

I don't know how specific the amd ryzen processor is, but what I have is what I have

**Comment by jakemac53** [comment]
> I don't know how specific the amd ryzen processor is, but what I have is what I have

Just trying to narrow down a repro case :). We do want to support generally whatever hardware/shell combination is causing this.

**Comment by kil0ba** [comment]
Upgrade project to Flutter 2 solved that issue, build_runner is still 1.10.11

**Comment by jakemac53** [comment]
> Upgrade project to Flutter 2 solved that issue, build_runner is still 1.10.11

Interesting, do you know what version you had before?

**Comment by natebosch** [comment]
At first glance I thought this was a case of long file paths like https://github.com/dart-lang/sdk/issues/27825

However it looks like the path in question here is already a bit shorter than 260 characters, so maybe it's a different issue.

**Comment by kil0ba** [comment]
@jakemac53 1.22.6

**Comment by natebosch** [comment]
Even though we weren't able to find a root cause here I'm going to close if this no longer repros on recent version of flutter.
