### ISSUE TITLE
Fail fast in Bazel when you omit the Dart SDK in data

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#308]
Which is fine, but we should be able to throw a bit early, right now it hits an NPE on `codePoints`, and it even took me a few minutes to figure out what that means. We should be able to throw something like a `StateError` describing that the SDK was not loadable.

**Comment by natebosch** [comment]
This is specifically for tests? We'll probably need to write a utility method and add it manually to tests - we don't have a hook otherwise.

**Comment by natebosch** [comment]
I think I've been able to remove this sharp edge - turns out I should have been including the SDK in the data for the `build_resolvers` target which eliminates the need to manually include it in every test.
