### ISSUE TITLE
Avoid generating empty files

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#309]
_From @a14n on December 15, 2015 15:48_

Original issue a14n/zengen#24

(tested with _0.4.7+1_)

A simple file `test.dart`:

``` dart
library a;
```

will generate `test.g.dart`

``` dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of a;

// **************************************************************************
// Generator: ZengenGenerator
// Target: library a
// **************************************************************************
```

With `build.dart`:

``` dart
import 'package:zengen/generator.dart';
import 'package:source_gen/source_gen.dart' show build;

main(List<String> args) async {
  print(await build(args, [new ZengenGenerator()],
      librarySearchPaths: ['example/'], omitGenerateTimestamp: true));
}
```

IIRC empty part files were ignored some times ago.

_Copied from original issue: dart-lang/source_gen#74_

**Comment by matanlurey** [comment]
_From @kevmoo on December 16, 2015 5:23_

Not 100% sure on this. If one doesn't want empty parts, remove the generator for that file, right?

**Comment by matanlurey** [comment]
_From @a14n on December 16, 2015 7:59_

Yes but in a large project it's easier to give a folder instead of hundreds of path.

**Comment by matanlurey** [comment]
_From @stevenroose on January 8, 2016 13:43_

I'm with @a14n here. Ideally, the generation script should just search the `web/`, `bin/` and `lib/` folders for files that require generation and just process those.

**Comment by matanlurey** [comment]
_From @jakemac53 on January 8, 2016 14:59_

I think this needs to be an option that you can toggle on/off. Many build systems require that you declare all your outputs up front (before reading the contents of the files) so source_gen needs the ability to output empty files in this case.

**Comment by matanlurey** [comment]
@jakemac53 Any thoughts on closing? I don't imagine we are going to invest lots of resources in alternative build systems anytime soon.

**Comment by matanlurey** [comment]
_From @jakemac53 on June 21, 2017 14:17_

We do have an alternative solution to output files with default content in bazel now - so source_gen doesn't have to output empty files (I am not sure if it actually does this today any more?).

**Comment by matanlurey** [comment]
OK @a14n @stevenroose Do either of you feel strongly about this? Want to send a PR?

**Comment by matanlurey** [comment]
_From @stevenroose on June 27, 2017 9:32_

> We do have an alternative solution to output files with default content in bazel now - so source_gen doesn't have to output empty files (I am not sure if it actually does this today any more?).

@matanlurey if it still outputs empty files, I'd leave this as an enhancement. I don't have strong feelings and I'm barely using source_gen anymore, but it stays a point of improvement.

**Comment by jakemac53** [comment]
Closed as you `Builder`s are not required to output files they declare for some time now. I think source_gen specifically has already been fixed for this as well.
