### ISSUE TITLE
`build_runner watch` crashed during `flutter clean`

### ISSUE THREAD

**Issue by araruna** [dart-lang/build#3124]
* Dart SDK Version (`dart --version`): `Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "linux_x64"`
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`): `build_runner ^2.0.4`
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.: `injectable_generator ^1.4.1` and `moor_generator ^4.3.1`
* Whether you are using Windows, MacOSX, or Linux (if applicable): Linux (Manjaro Gnome)

I ran the command `flutter packages pub run build_runner watch --delete-conflicting-outputs` and, while the command was idle, I ran the command `flutter clean`. After this, the first command exited after printing the following error:
```
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


AssetNotFoundException: precos|.dart_tool/package_config.json
package:build_runner/src/generate/watch_impl.dart 400:3  _readOnceExists

pub finished with exit code 1
```

What other information would be useful to add? Unfortunately, at this moment, I don't have the time to craft an MWE.

**Comment by jakemac53** [comment]
Thanks for the report!

I think this is probably a race condition where a file was deleted after we checked if it existed, but before we actually read it. A subsequent build should work fine, and there isn't a whole lot we can reasonably do in this situation. You should just restart the build process.
