### ISSUE TITLE
Limitation on generated files (path and extension)

### ISSUE THREAD

**Issue by jaumard** [dart-lang/build#3126]
Hello, 

I have developed a package builder [intl_flavors](https://pub.dev/packages/intl_flavors) that basically take you localisation class and transform it into ARB, then once all ARB are present it generate all the localization files. 

It does the same as intl_translation but run with build_runner instead of custom CLI commands. 

When developing this builder I found myself limited with the way builder works, for example on the build.yml I have to put ahead or time the generated extension I want to support. But on my case I don't know how many locales I will have to generate. And also I will have to generate multiple files (one per locales, and one global) so it's not just changing the extension. 

Let's take an example, I have my `translations.dart`, and I have 2 locales, `en` and `fr`. The builder will generate:
- `translations.arb`
- `translations_messages_en.dart`
- `translations_messages_fr.dart`
- `translations_messages_all.dart`

Builder also let you specify a directory for ARB and a directory for generated code, again that look like it's not supported by the builder. 

So for now my workaround is to not use the buildStep to generate the files but directly the dart File API. It works but would be really nice if it can be done "by the book"

`Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "macos_x64"`
`build_runner 2.0.3`

**Comment by jakemac53** [comment]
This is a pretty hard constraint based on the design of the build apis, and the cross-build-system compatibility that we provide. Generally, all inputs and outputs must be known ahead of time, before we run the build. This is specifically a limitation of the `bazel` build system (or at least the dart build rule implementation we use internally with it).

We have explored some other options to make build extensions more flexible in the past, for instance https://github.com/dart-lang/build/issues/1689.

Sometimes you can also output a single archive file, and then extract that with a post-processing builder (these don't have to declare outputs), but that doesn't allow for any other builder to process the files that you output. This would mean for instance your builder wouldn't work with the `build_web_compilers` builder, which is what non-flutter users generally use to compile dart code to JS.

In your case does the user know all the languages they want to output? It might be possible to devise a feature that allows the users to provide a list of languages to the builder as an option, which would then be translated to a custom list of output extensions for that target that was configured.

**Comment by jakemac53** [comment]
> So for now my workaround is to not use the buildStep to generate the files but directly the dart File API. It works but would be really nice if it can be done "by the book"

This probably causes an extra build to happen each time though? The build system will just see these as "new" files and then probably rerun the build if they change, but that might be generally OK. Just know that this isn't a supported path right now so any issues around invalidation and things we won't be able to help with.

**Comment by jakemac53** [comment]
@jaumard we did just release a "capture groups" feature which would enable you to place all the generated files in a separate directory at least. See some docs at https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md#capture-groups (you probably need multiple capture groups for your use case).

I am going to close this issue though as I don't think we will be further expanding the functionality here.
