### ISSUE TITLE
[build_runner] Do not sent the file contents with the response to a HEAD request.

### ISSUE THREAD

**Issue by annagrin** [dart-lang/build#3129]
See https://github.com/dart-lang/webdev/issues/1345.

Some change in SDK uncovered a problem where build_runner sends the whole file contents to the client, but the 
client does not read it, causing broken pipe errors in some configurations but not the others.

The HEAD request spec mentions:
> The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by jakemac53** [comment]
Is this specifically for build_daemon?

**Comment by annagrin** [comment]
> Is this specifically for build_daemon?
yes

**Comment by annagrin** [comment]
Thanks Jake, this helps us improve expression evaluation startup time!
