### ISSUE TITLE
Error trying to use mockito on Flutter (No such file or directory)

### ISSUE THREAD

**Issue by VCortes** [dart-lang/build#3133]
* Dart SDK Version (`dart --version`)

Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "windows_x64"

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

build_runner: ^2.0.4

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.

I'm using mockito to generate mocks.

* Whether you are using Windows, MacOSX, or Linux (if applicable)

Windows 10

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

VSCode and Android Studio

* Any other packages or constraints we should know about

 mockito: ^5.0.10

I'm trying to use mockito on flutter without success. It works in a Dart console project, but not when I use it in a Flutter project. After the command "dart run build_runner build" the error appears:

FileSystemException: Cannot open file, path = 'C:\Users{name}\Documents\flutter\version' (OS Error: OS Error: No such file or directory, errno = 2)

What's going on here?

**Comment by jakemac53** [comment]
When in a flutter project you should run `flutter pub run build_runner build`, can you try that? I haven't seen that specific error before though...

**Comment by VCortes** [comment]
Worked perfectly!
It wasn't clear in the documentation, but it seems obvious to non-beginners.
Thanks!
