### ISSUE TITLE
Add `expectedOutputs` getter to `BuildStep`

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#3154]
Having an `expectedOutputs` getter (returning an `Iterable<AssetId>`) on `BuildStep` would help builder authors to determine which assets to emit.

A lot of builders know that they will emit one asset per primary input, so doing `buildStep.writeAsString(buildStep.expectedOutputs.single,)` may be easier than manually changing the extension. This will especially true for builders using capture groups, which typically requires two replace operations on the input path. The build system already has this information, so we could expose it to make these scenarios easier.

Do we consider new methods on `BuildStep` to be breaking?

**Comment by jakemac53** [comment]
This LGTM, no I don't think new methods on BuildStep should be breaking (I believe we have only one impl).

However, we could implement this as an extension to avoid that?

**Comment by jakemac53** [comment]
Fwiw I had the same thought, especially with capture groups, it gets a bit more complicated :).

**Comment by simolus3** [comment]
I've actually considered making it an extension, but I didn't find a good way to do so because the originating builder is not part of the `BuildStep`. We could make it an extension function on `Builder` that takes an asset or a `BuildStep` as parameter, but IMO that's not quite as convenient.
