### ISSUE TITLE
Add predefined copy builder to `package:build`?

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#3156]
This is more of a discussion than a feature request, I'm wondering what your thoughts on this are.

It looks like we're about to support directory moves for builders. But today, all builders emit outputs in the same directory as their primary input. Given the popularity of that feature, I can imagine that there will be pressure for each builder to support emitting files in a designated directory after the build system allows it. I think we should provide some standardized way of letting builders emit code in different directories. 
For instance, consider a proto builder that might take a `.proto` as input today and emit a bunch of `.pb.dart` files, relative to its primary input. We could change this builder to look for definitions in `assets/proto` and write them to `lib/src/generated`, but what if

- Some users prefer another folder over `lib/src/generated`? Or what if they want to store definitions in a different folder?
- There's another builder writing to `lib/src/my_builder` instead? It will start to get messy if every builder just picks its favorite output directory.

I think an easy approach to standardize this is to keep existing builders unchanged. So most of them would take a primary input and emit files with a changed extension only.
To allow directory moves, we could add a copying builder to `package:build` that users would configure themselves:

```yaml
targets:
  prepare:
    auto_apply_builders: false
    builders:
      build|copy:
        options:
          inputs: {'^proto/{{}}.proto': ['lib/src/generated/{{}}.proto']}
  $default:
    dependencies: [':prepare']
```

So an actual build would look like this:

1. A copying builder in `package:build` copies `proto/my/custom/file.proto` to (a hidden) `lib/src/generated/my/custom/file.proto`
2. The regular proto builder runs on `lib/src/generated/my/custom/file.proto` and writes the desired outputs to source.

It looks like this is what most users want today, and it doesn't require any additional effort for existing builders.

There are some downsides of course:

- Most users probably don't know about build configs at all
- Setting up the right target sources can be tricky.
- The copying builder can't declare outputs in a `build.yaml` since they depend on an option. So one needs to use targets to get the ordering right.

But I'm wondering if this could be worth it since it looks like a relatively minor effort in the build system and it would enable directory moves with zero additional effort for existing builders.

**Comment by jakemac53** [comment]
Configuring output extensions via an option in general I think doesn't work as expected, consider for instance what happens if you were to change that configuration. We would have already generated the asset graph with the previous config, and it would now be incorrect. But I am quite sure we wouldn't be able to adjust for it today.

Because of this, build extensions are not allowed to change today, and should not be configured either.

You can somewhat allow users to determine where under `lib` their files end up by using extensions like `{'proto/{{}}.proto': ['lib/{{}}.pb.dart']}`. Then whatever structure is used under the `proto` dir is copied over to the `lib` dir. So if you want files in `lib/src/generated/` you would put your protos under `protos/src/generated`. Not a perfect solution, but it works.

**Comment by simolus3** [comment]
That's a good point! I thought I remembered reading about build configurations being nodes in the asset graph that could be updated, but maybe I misunderstood something. Either way, if changes to a builder applications also change build phases it will be hard to do incremental rebuilds at all.

I think the solution with `protos/src/generated` should work well enough.

**Comment by jakemac53** [comment]
> That's a good point! I thought I remembered reading about build configurations being nodes in the asset graph that could be updated, but maybe I misunderstood something.

The builder options can be udpated (we create a synthetic node for the options object, and add a dependency on that).

But the configuration of the builder itself cannot be updated right now.
