### ISSUE TITLE
Windows Path problem using build_runner 

### ISSUE THREAD

**Issue by ZeroOneTV** [dart-lang/build#3158]
Hi, could you help me with this problem? 

# Problem information 
* Windows 10 Pro • Version 20H2 (Compilation 19042.1110)
* Flutter 2.5.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
* Framework • revision 184e5871be (4 days ago) • 2021-07-26 04:38:02 -0400
* Engine • revision a877f6fed6
* Tools • Dart SDK version: 2.14.0-350.0.dev (dev) (Fri Jul 23 20:45:53 2021 -0700) on "windows_x64"
* build_runner version: "2.0.6"
* json_serializable: ^4.1.0 || mockito: ^5.0.11 || moor_generator: ^4.4.1 || using theses builds

The most similar problem I'm having would be this: https://github.com/dart-lang/pub/issues/3012

Making use of these packages mentioned, i'm currently trying to run build_runner to generate the .g models and mocks for testing. 
But, when I run `flutter pub run build_runner build --delete-conflicting-outputs` or `dart run build_runner build --delete-conflicting-outputs `

I get the following error: 
``` PS C:\Users\Zero\Documents\OneApp> flutter pub run build_runner build --delete-conflicting-outputs
Could not find a file named "pubspec.yaml" in "C:\Users\Zero\AppData\Local\Pub\Cache\git\flutter_plugins-fe50c5bb70cde2cbec931f082aabad229e8003d7\packages%5Cequalizer".
pub finished with exit code 66 
```

``` PS C:\Users\Zero\Documents\OneApp> dart run build_runner build --delete-conflicting-outputs
Could not find a file named "pubspec.yaml" in "C:\Users\Zero\AppData\Local\Pub\Cache\git\flutter_plugins-fe50c5bb70cde2cbec931f082aabad229e8003d7\packages%5Cequalizer".
```

I tried to remove the backslash from pubspec.lock file but I get the error:
```
The pubspec.lock file has changed since the .packages file was generated, please run "pub get" again.
pub finished with exit code 65
```

This error occurs on flutter channel:
 - Dev
 - Beta
 - Master

The only one in which the build is possible without major problems is the Stable channel.

**Comment by natebosch** [comment]
https://github.com/dart-lang/pub/issues/3012 appears to be the correct place to track this issue. I don't see anything here that requires changes in the `build` repo.
