### ISSUE TITLE
when i run flutter pub get

### ISSUE THREAD

**Issue by TomWang1** [dart-lang/build#3168]
pub `get`
Because every version of flutter_test from sdk depends on meta 1.3.0 and json_annotation >=4.1.0 depends on meta ^1.4.0, flutter_test from sdk is incompatible with json_annotation >=4.1.0.
So, because bili_app depends on both json_annotation ^4.1.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because bili_app depends on both json_annotation ^4.1.0 and flutter_test any from sdk, version solving failed.)

**Comment by jakemac53** [comment]
You will  need to downgrade your dependency constraint on `json_annotation` to something which is compatible with your SDK.

You can try changing it to `any` instead of `^4.1.0`, see what version you get, and then put that version in as the constraint.
