### ISSUE TITLE
Change to conditional imports broke web platform

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/build#3173]
@jakemac53 's changes in #3170 as a response to @mraleph 's issue of https://github.com/dart-lang/sdk/issues/46918 has had some side effects.

Namely, I cannot build any of my projects that depend on conditional imports to differentiate between VM and web platforms. 
A good example would be [package:universal_html](https://pub.dev/packages/universal_html) that is publicly available. 

- Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"
- Affected builder package: `build_modules v4.0.2` (v4.0.1 works fine)

**Repro code**

```dart
import 'package:universal_html/html.dart';

void main() {
  print(document.body != null);
}
```

## Observed errors

**With DDC:**

```sh
# dart run build_runner serve web:8080
[SEVERE] build_modules:module_library on package:universal_html/js.dart: Invalid argument(s): Unsupported conditional import of `dart:js` found in universal_html|lib/js.dart:

export 'dart:js';

This environment does not support direct conditional imports of `dart:` libraries. Instead you must create a separate library which unconditionally imports (or exports) the `dart:` library that you want to use, and conditionally import (or export) that library.
```

**With dart2js**
```sh
# dart run build_runner serve -r --define 'build_web_compilers|entrypoint=compiler=dart2js' --define 'build_web_compilers|entrypoint=dart2js_args=["-O1"]' web:8080

[SEVERE] build_modules:module_library on package:universal_html/js.dart (cached):

Invalid argument(s): Unsupported conditional import of `dart:js` found in universal_html|lib/js.dart:

export 'dart:js';
```

**Comment by jakemac53** [comment]
The example you have shown was never intended to work. I think there was a bug where we allowed conditional imports/exports of `dart:` libraries if the _default_ import was a `dart:` library.

I would forward fix the package to export a library that exports `dart:js`.

**Comment by jakemac53** [comment]
Note that if you attempted to compile for the vm (with build_vm_compilers) I am quite sure it would not have worked.
