### ISSUE TITLE
dart2js still using unsound null safety on a NNBD library

### ISSUE THREAD

**Issue by agreaves** [dart-lang/build#3191]
Dart SDK Version: 2.14.0
Packages: **build_modules-4.0.2**, **build_runner-2.1.2**, **build-2.1.0***

We're generating JS code from a directory that has been completely migrated to sound null safety, running the following lines:
```
var dart2js = await buildStep.fetchResource(dart2JsWorkerResource);
var result = await dart2js.compile(args);
```

The problem is, despite not specifying unsound null safety (and even passing in arguments for **sound_null_safety** explicitly), we're still getting errors of the nature:

```
packages/package_config/src/package_config_json.dart:287:33:
Error: Null safety features are disabled for this library.
  if (data is Map<String, Object?>) {

...
```

I'm not sure what might be causing dart2js to try to compile without null safety when the entire library has been successfully migrated with no issues.

**Comment by jakemac53** [comment]
@agreaves what is your `build_web_compilers` version?

**Comment by jakemac53** [comment]
Closing as stale
