### ISSUE TITLE
Latest build runner publish causing issues when imported from a non-null-safe package

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/build#3200]
```
../../../../../.pub-cache/hosted/pub.dartlang.org/build_runner_core-7.2.1/lib/src/generate/build_impl.dart:788:28: Error: The argument type 'Future<void>?' can't be assigned to the parameter type 'Future<void>' because 'Future<void>?' is nullable and 'Future<void>' isn't.
 - 'Future' is from 'dart:async'.
      unawaited(_lazyGlobs.remove(globNode.id));
```

This is from the DevTools build. See https://github.com/flutter/devtools/pull/3420/checks?check_run_id=3771809219

**Comment by icfilho** [comment]
same error here

**Comment by rmargolinross** [comment]
Also seeing this issue. Is there a way to work around it somehow?

**Comment by kenzieschmoll** [comment]
Looks like a fix was landed and published: https://github.com/dart-lang/build/pull/3201. This is resolved for me now after upgrading

**Comment by rmargolinross** [comment]
I have found that including a reference to `build_runner_core: 7.2.2` will fix the issue, though it should not be needed

**Comment by natebosch** [comment]
A `dart pub upgrade` or `flutter pub upgrade` should resolve this. @jakemac53 published a corrected version.
