### ISSUE TITLE
Dart import prefixes are not used in generated code

### ISSUE THREAD

**Issue by CaseyHillers** [dart-lang/build#3212]
I created a class:

```
// my_class.dart
import 'package:my_package/my_package.dart' as mine;

@JsonSerializable()
class MyClass {
  final mine.Type field;
}
```

Which then creates something like

```
// my_class.g.dart
Type field; // BAD. Expectation is mine.Type
```

It needs to carry over the prefix, otherwise the generated code does not run.

* Dart SDK Version (`dart --version`)

`Dart SDK version: 2.15.0-116.0.dev (dev) (Thu Sep 16 09:47:01 2021 -0700) on "linux_x64"`

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

`2.1.2`

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.

json_serializable

* Whether you are using Windows, MacOSX, or Linux (if applicable)

`Linux`

**Comment by jakemac53** [comment]
This looks like an issue with `json_serializable`, I would file the issue over there https://github.com/google/json_serializable.dart/issues/new. I would transfer it but we can only transfer issues between dart-lang repos.

**Comment by CaseyHillers** [comment]
This is a duplicate of https://github.com/google/json_serializable.dart/issues/678
