### ISSUE TITLE
 build_runner build  error

### ISSUE THREAD

**Issue by xiaocode337317439** [dart-lang/build#3221]
[✓] Flutter (Channel master, 2.6.0-12.0.pre.984, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.6.0-12.0.pre.984 at /Users/osulcode.xiao/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6b51924de3 (10 hours ago), 2021-12-09 16:49:10 -0500
    • Engine revision 2516ea636d
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/osulcode.xiao/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • ANDROID_HOME = /Users/osulcode.xiao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

---------------------------------------------------------------------------------
flutter packages pub run build_runner build

[INFO] Generating build script...
[INFO] Generating build script completed, took 993ms

[INFO] Precompiling build script......
[WARNING] Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:json_ast
 - package:grapheme_splitter

For solutions, see https://dart.dev/go/unsound-null-safety
[INFO] Precompiling build script... completed, took 8.1s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78

---------------------------------------------------------------------------------
build_runner: ^2.1.5

**Comment by jakemac53** [comment]
A few questions to help diagnose this:

- Which version of `analyzer` do you have (you can use `pub deps` to check that)?
- What is your sdk constraint in your pubspec?

**Comment by jakemac53** [comment]
Actually, if you can provide the entire output of `flutter pub deps` that would help.

It looks like a builder of yours probably migrated out of order, or one of its deps did, which is causing this issue. The `json_ast` and `grapheme_splitter` packages are not migrated, but are transitively imported by a builder which is opted in to null safety. We only check if the builder imports themselves are opted in to null safety when determining the mode to run in.

The easiest solution is to opt out the specific `builderImport` files, with a dart language comment `// @dart=2.10` or some such at the top of those files.
