### ISSUE TITLE
“flutter packages pub run build_runner build --delete-conflicting-outputs” question

### ISSUE THREAD

**Issue by pleasecallmelm** [dart-lang/build#3225]
Hello, the flutter version of our project is 2.5.3，build_runner version is 2.1.5,We project have no support nullsafe, It‘s error when we execute “flutter packages pub run build_runner build --delete-conflicting-outputs”,error message is "Generator cannot target libraries that have not been migrated to null-safety",How can I handle this situation

**Comment by jakemac53** [comment]
@pleasecallmelm You likely need to downgrade the package that is giving you that message, to its pre-null-safety version.
