### ISSUE TITLE
Builders can write to the same file multiple times

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#3227]
Consider a builder like this:

```dart
Future<void> build(BuildStep step) async {
  final output = step.allowedOutputs.single;

  await step.writeAsString(output, 'foo');
  await step.writeAsString(output, 'bar');
}
```

This does not throw an exception, and ends with a single output with the content `bar`. Should this really be allowed? I was having a hard time figuring out why my builder writes unexpected content until I found this bug in my code. If there's no real scenario where this would be useful, can we make the second write throw an exception for visibility?

**Comment by jakemac53** [comment]
Just an oversight/bug, should not be allowed 👍

**Comment by jakemac53** [comment]
@simolus3 did you want to work on this fix for this? I just don't want to duplicate any work :).

**Comment by simolus3** [comment]
Yup! PR coming soon :)

**Comment by jakemac53** [comment]
This is published as well now
