### ISSUE TITLE
please add some flowchart how build runner works

### ISSUE THREAD

**Issue by erlangparasu** [dart-lang/build#3232]
please add some flowchart how build runner works, which code executed first, second, ...
i have no idea how it works currently. I hope documentation added in Getting Started page

**Comment by jakemac53** [comment]
Are you specifically looking for documentation on the order in which builders are ran?

**Comment by erlangparasu** [comment]
yes. I think it would be better if there was documentation on how build_runner works in graphical form. I myself just understood how to implement this lib after reading and trying according to the sample code
https://github.com/dart-lang/build/tree/master/example
