### ISSUE TITLE
Consider running client tests

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#3236]
It isn't common for this package to accidentally break other packages, but it is possible for us to, and it could potentially cause widespread breakage. We could try to prevent this by running the tests of some of our more popular builders alongside our own tests.

It is a bit complicated to actually do this, it isn't as simple as cloning the repo and running their tests - we also need to override all package:build dependencies so they depend on the current versions in this repo.

We could possibly just clone the repos and then inject some `dependency_overrides` into the desired pubspecs. The process for adding a client test would then be to add to some configuration file in this package the git uri for the client repo, a list of directories which are packages that we want to run tests in, and then a (possibly optional) list of commands to run (could default to just `dart test`). We would automatically update the pubspecs in the listed directories and run the listed commands.

I think we probably would mark these jobs as allowed to fail, it would just be a signal for us on pull requests. There are times where we will be making known breakages and know we will be breaking client tests.

**Comment by AlexV525** [comment]
Replying to https://github.com/dart-lang/build/pull/3222#issuecomment-1012385326: The breakage is caused by the chain reaction. If the constraint can be loosened by a single minor version upgrade, other packages/projects can upgrade to the breakable major version easily by running pub upgrade.

Speaking of customer tests, Flutter does have the mechanism in https://github.com/flutter/tests, which provides tests commit hash and steps that needs to be tested in every single commit.

**Comment by AlexV525** [comment]
Consider that the last breakage is from `analyzer`, we might apply this to it too.

**Comment by jakemac53** [comment]
> Speaking of customer tests, Flutter does have the mechanism in https://github.com/flutter/tests, which provides tests commit hash and steps that needs to be tested in every single commit.

That approach seems pretty general which is nice, and the config format seems pretty simple.

**Comment by jakemac53** [comment]
Note that I am on a sprint right now for the next ~1 month prototyping macros but I am open to contributions in this area.

cc @simolus3 or @rrousselGit may be interested in doing this in order to facilitate their own tests?

**Comment by AlexV525** [comment]
Actually the current scenario is pretty awkward, non of my packages depend on analyzer but only the serializable did, which pull to latest but a major version upgraded analyzer, then break the usage. So yes it's actually broken by the analyzer, but it's chained to the constraint update.
The point here is when we're applying any upgrades to major versions, we might take extras tests and thoughts to keep the functionality.
Packages like build or analyzer can improve how to affect their ecosystem though, by applying customers tests.

**Comment by jakemac53** [comment]
I do think client tests in general are the best way to prevent this type of breakage. This was caused by a change in analyzer that was not thought to be breaking which ended up being breaking. So they would have needed to be running client tests to discover that.

I have no idea if there would be an appetite for adding client tests to the Dart SDK though (where the analyzer is developed). The analyzer does intentionally do breaking changes quite often (much more than this repo), so it would probably be somewhat annoying/noisy for them. The SDK tests do have mechanisms to approve failing tests and stuff which might make it fairly manageable though.

**Comment by simolus3** [comment]
I don't remember being broken by `build` packages before, but I'll gladly add some tests for my packages as a precaution. 

> That approach seems pretty general which is nice, and the config format seems pretty simple.

I'm happy to work on tooling for third-party tests in this repository, but I don't know if we need something as fancy as Flutter. Would it be enough if we had some script in this repo to add the necessary dependency overrides and then contribute community test cases as a GitHub action? That approach sounds easier to me than the custom testing logic Flutter is doing, but it'll probably be enough here?

**Comment by AlexV525** [comment]
Should we move this issue to the [dart-lang/sdk](https://github.com/dart-lang/sdk) repo?

**Comment by jakemac53** [comment]
> Would it be enough if we had some script in this repo to add the necessary dependency overrides and then contribute community test cases as a GitHub action?

Actually ya that does make a lot of sense, I like that approach 👍 . That way its also a separate workflow as well.

**Comment by jakemac53** [comment]
> Should we move this issue to the [dart-lang/sdk](https://github.com/dart-lang/sdk) repo?

I would file a separate one there, they use different CI infrastructure and we would ideally do this in both places.

**Comment by rrousselGit** [comment]
> > Would it be enough if we had some script in this repo to add the necessary dependency overrides and then contribute community test cases as a GitHub action?
> 
> Actually ya that does make a lot of sense, I like that approach 👍 . That way its also a separate workflow as well.

Then I'd recommend having a single "community" workflow instead of one workflow per package

I could see having one workflow per package causing scaling issues. We'd have problems in FlutterFire due to a limit on the number of workflows that can be running concurrently

**Comment by jakemac53** [comment]
We have something up and running here now, see this example job https://github.com/dart-lang/build/blob/master/.github/workflows/community.yml#L8. PRs welcome to add more jobs.
