### ISSUE TITLE
Asset server should accept HTTP Range requests

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/build#3242]
HTTP range requests are needed, since the asset server is accessed by `webbed serve` proxy (`shelf_proxy`).

When any browser accesses the `webdev` port, it's actually accessing the Asset Server (`AssetHandler.handle`):

https://github.com/dart-lang/build/blob/372dce1d7d04deb254d1db5ad433bbcaf3a7c471/build_runner/lib/src/server/server.dart#L364

Here's a HTTP Range implementation as reference:
https://github.com/dart-lang/shelf_static/blob/master/lib/src/static_handler.dart#L216

If you are developing, some browser requests need to be made using a range requests, like a video. For example Safari will only accept to load a video using a HTTP Range requests. And yes, you can be developing and testing it on Chrome and Safari at the same time.

**Comment by jakemac53** [comment]
Note that we don't actually have APIs available to read only a portion of a file (we go through the `AssetReader` interface), so we would have to read all the bytes and then serve just a portion of them today.

In general I would not expect this server to perform well for serving video or other large assets. It keeps assets fully in memory and caches them. The memory usage will likely balloon far out of control doing it that way.

Can you serve these assets from some other server on the side?

**Comment by gmpassos** [comment]
In production no one should use this as a server.

But in development environments this is the way. The current implementation won't allow to test some assets in the browser, like a video in Safari, since it demands the range request.

**Comment by jakemac53** [comment]
> But in development environments this is the way.

Even for development though I would very strongly discourage using this server to serve large files. It is going to end up caching the _entire_ video in memory.

I would suggest running a separate server on the side, and loading videos from that.
