### ISSUE TITLE
Error: Type 'TypeName' not found. void visitTypeName(TypeName node)

### ISSUE THREAD

**Issue by henriqueArrazao** [dart-lang/build#3251]
```
> flutter pub run build_runner --delete-conflicting-outputs
Failed to build build_runner:build_runner:
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dart_style-2.1.1/lib/src/source_visitor.dart:2695:22: Error: Type 'TypeName' not found.
  void visitTypeName(TypeName node) {
                     ^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dart_style-2.1.1/lib/src/source_visitor.dart:2695:22: Error: 'TypeName' isn't a type.
  void visitTypeName(TypeName node) {
                     ^^^^^^^^
pub finished with exit code 1
```

My pubspec:
https://github.com/henriqueArrazao/ferry_app/blob/main/pubspec.yaml

I simply don't know what is going on, I put some `dependency_overrides` because before there was too much more errors. Please some help.

**Comment by jakemac53** [comment]
This is almost certainly a mismatch between the `dart_style` and `analyzer` versions, as a result of the `dependency_overrides`.

You really don't want to leave overrides like that in if you can avoid it because it circumvents version solving and compatibility guarantees.

**Comment by jakemac53** [comment]
Fwiw, `dart_style` version `2.1.1` (which it looks like you are using) requires analyzer `'>=1.3.0 <3.0.0'`.

You probably have a newer version of analyzer, so you can try upgrading `dart_style` to `2.2.1` which supports newer analyzer versions.

**Comment by jakemac53** [comment]
Closing this issue as there isn't any bug here, but you can respond to try and get some assistance in further debugging if you like

**Comment by henriqueArrazao** [comment]
Nothing worked hehe, just changed the package, thank you.
