### ISSUE TITLE
Ability to opt-out of or opt-in to a specific Builder

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/build#3262]
* Dart SDK Version
  * Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"`
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * `build_runner 2.1.7`
  * `build 2.2.1`
* What builder(s) you are using (or writing yourself)
  * We're writing a custom builder with synthetic input on the `lib` directory that scans dart files for `ClassDeclaration`s annotated with a custom annotation, and produces a single markdown file with those `ClassDeclaration`s documentation and a few other tidbits of information. The idea is sort of like an opt-in `dartdoc` model rather than _everything_ being documented.
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  * MacOSX

---

Hi there! As described above, we're working on a builder that acts like an opt-in `dartdoc` in that only very few things in the codebase get added to a markdown file within a package, so we can point new hires to the most important building blocks of our codebase, while still allowing for the ability to document all of the public api in our codebase. AFAIK `dartdoc` does not support this model -- it _does_ support `@nodoc` but we wouldn't want to put that on every single thing we _don't_ want documented, just to have only some things documented.

This all works as expected, but it isn't the best in terms of efficiency, for the following reasons:
1. During CI executions, we _don't_ want to run this builder because it's not a critical output. The markdown file can be produced after CI validations, upon merging the pull request. In this case, it would be nice to be able to specify a builder to opt-OUT of, e.g `flutter pub run build_runner build +x directory_builder` where `-x` indicates a builder to ignore.
2. If the above was possible and we set up a workflow on CI to build the directory upon a successful merge to `main`, we'd want to _only_ run our builder and generate the directory, but would not want to run ALL builders as that would result in needless execution time. In this case we'd want something like `flutter pub run build_runner build -b directory_builder` where `-b` is the only builder to run.

Has this type of input ever been considered? Am I maybe missing the fact that this is already possible? Thank you!

**Comment by btrautmann** [comment]
@jakemac53 yeah, I don't think that would work for us because we use builders like `freezed` which [also require all dart files] for their outputs. 

Are there reasons why this type of opt-out or opt-in functionality shouldn't or can't be supported?

**Comment by jakemac53** [comment]
Actually, now that I think about it there is another way for you to do this.

We support custom named "configurations", which each get their own `build.<config>.yaml` file. You pass the name of the configuration to use with the `--config` flag so for instance `--config=nodocs`. And then a `build.nodocs.yaml` file could look like this:

```yaml
targets:
  $default:
    builders:
      my_docs_builder:
        enabled: false
```

You would need to also duplicate any other definitions in the original `build.yaml` so it is a bit of a pain to keep them in sync.

You can al
```

You would need to also duplicate any other definitions in the original `build.yaml` so it is a bit of a pain to keep them in sync.

You can also enable just the docs builder with something like this:

```yaml
targets:
  $default:
    auto_apply_builders: false # Disables all builders by default
    builders:
      my_docs_builder:
        enabled: true
```

**Comment by btrautmann** [comment]
Ah, that might work for us. Assuming `build` is OK with me having a `build.yaml` and a `build.docs.yaml`, we could keep everything the same as it is now but then pass `--config=docs` when generating the documentation for our annotated classes. I'll give that a shot and if it works, provide what our final configuration looked like for anyone that stumbles across this need and close this. Thanks @jakemac53!

**Comment by jakemac53** [comment]
> Running `flutter pub run build_runner build --config=nodocs` correctly runs my builder and nothing else, _but_ it deletes all generated files by other builders (the ones configured in the default `build.yaml`). Is this expected?

Yes - this is a totally different build configuration, it bashes away all artifacts from previous builds and does a new build with the new configuration.

> Additionally, running our default config, which is normally done via `flutter pub run build_runner build --delete-conflicting-outputs` unfortunately _deletes_ the markdown file built by `nodocs` from `lib/generated` but doesn't recreate it because that builder is not run.

Ya, same problem.

> I'm generally wondering if this behavior between build configs is expected or if I'm missing something 😄

It is expected, and that does make sense it might not be the best option for you.

There is yet another option though... you can create a totally custom build script which is a _separate_ build from the original. You would check this script into the `tool` dir or something in your repo. The easiest way to make that script is to configure it via `build.yaml`, run a build (or use the `generate-build-script` command), and then copy that generated script (possibly clean it up though so its more human readable).

In order to make this build truly separate from your normal builds, you would want to add one extra line at the top of `main`, to call [overrideGeneratedOutputDirectory](https://pub.dev/documentation/build_runner_core/latest/build_runner_core/overrideGeneratedOutputDirectory.html) with a custom name. This will make it build to a different output directory (for stuff built to cache at least).

Then you can run this custom script, instead of running `dart run build_runner`, when doing the "no docs" version of the build. Both builds will be able to co-exist and not conflict with each other (as long as they don't write to the same source outputs).

**Comment by btrautmann** [comment]
Ah, thanks for the pro tip!

This seems to work perfectly:

```dart
import 'package:build_runner_core/build_runner_core.dart' as build_runner_core;
import 'package:nodocs/nodocs.dart' as nodocs;
import 'dart:isolate' as isolate;
import 'package:build_runner/build_runner.dart' as build_runner;
import 'dart:io' as io;

final _builders = <build_runner_core.BuilderApplication>[
  build_runner_core.apply(
    // ignore: unnecessary_raw_strings
    r'nodocs:nodocs',
    [nodocs.nodocs],
    build_runner_core.toRoot(),
    hideOutput: false,
  ),
];
Future<void> main(List<String> args, [isolate.SendPort? sendPort]) async {
  final result = await build_runner.run(args, _builders);
  sendPort?.send(result);
  io.exitCode = result;
}
```

In an effort to make this more consumer friendly, I made the following change:

```diff
  build_runner_core.apply(
    // ignore: unnecessary_raw_strings
    r'nodocs:nodocs',
    [nodocs.nodocs],
-  build_runner_core.toRoot(),
+  build_runner_core.toDependentsOf('copyist'),
    hideOutput: false,
  ),
```

and placed the script in `bin/copyist.dart` so it can be invoked by packages that depend on `copyist` via `dart run copyist:copyist build`. Does anything about that feel wrong? Anything I might be missing?

If not I think we can consider this a success 👍

**Comment by jakemac53** [comment]
> and placed the script in `bin/nodocs.dart` within the actual nodocs package so it can be invoked by packages that depend on `nodocs` via `dart run nodocs:nodocs build`. Does anything about that feel wrong? Anything I might be missing?

That should be fine with one caveat - you should add a _real_ dependency on all packages used in imports of that script, which is a bit less than ideal (usually they would just be dev dependencies). Mostly that just might add a bit of maintenance burden on you to update version constraints of these occasionally. But `build_runner` and `build_runner_core` are anyways pretty stable at this point.

**Comment by jakemac53** [comment]
Also fwiw you can remove all the isolate stuff from this script if you want :).

**Comment by jakemac53** [comment]
I am going to go ahead and close this as I think it is mostly resolved? Or at least an alternate solution reached :)

**Comment by jakemac53** [comment]
> Just to make sure, you mean doing this for the `nodocs` package, correct?

Right, any scripts in `bin` are a public dependency and so their imports should be real dependencies and not dev dependencies.
