### ISSUE TITLE
FileSystemException: Cannot create file, path = './.dart_tool' (OS Error: Access is denied. , errno = 5)

### ISSUE THREAD

**Issue by Kareem21227gg** [dart-lang/build#3276]
* Dart SDK Version (Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64")

> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   flutter_lints: ^1.0.0
>   test: ^1.17.12
>   build_runner: ^2.1.8
>   auto_route_generator: ^3.2.3
>   chopper_generator: ^4.0.1
>   json_serializable: ^6.1.4
>   swagger_dart_code_generator: ^2.4.6
> targets:
>   $default:
>     builders:
>       swagger_dart_code_generator:
>         options:
>           input_folder: 'lib/some-folder'
>           output_folder: 'lib/some-folder/'

* on windows 
* I'm trying to generate swagger files 

> 

> [INFO] Generating build script...
> [INFO] Generating build script completed, took 1.4s
> 
> [WARNING] Invalidated precompiled build script due to missing asset graph.
> [INFO] Precompiling build script......
> [INFO] Precompiling build script... completed, took 2.7s
> 
> 
> 
> You have hit a bug in build_runner
> Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
> 
> 
> FileSystemException: Cannot create file, path = './.dart_tool' (OS Error: Access is denied.
> , errno = 5)
> dart:io                                                                     _File.createSync
> package:swagger_dart_code_generator/swagger_dart_code_generator.dart 61:30  _generateExtensions
> package:swagger_dart_code_generator/swagger_dart_code_generator.dart 99:32  SwaggerDartCodeGenerator.buildExtensions
> package:build_runner_core/src/package_graph/apply_builders.dart 403:33      _validateBuilder
> package:build_runner_core/src/package_graph/apply_builders.dart 183:9       new BuilderApplication.forBuilder.<fn>.<fn>
> package:build_runner_core/src/package_graph/apply_builders.dart 346:27      _createBuildPhasesForBuilderInCycle.<fn>.<fn>
> dart:core                                                                   Iterable.toList
> package:build_runner_core/src/package_graph/apply_builders.dart 293:8       createBuildPhases
> package:build_runner_core/src/generate/build_impl.dart 109:29               BuildImpl.create
> package:build_runner/src/generate/build.dart 109:35                         build
> package:build_runner/src/entrypoint/build.dart 35:18                        BuildCommand._run
> package:args/command_runner.dart 209:13                                     CommandRunner.runCommand      
> package:build_runner/src/entrypoint/run.dart 26:18                          run
> .dart_tool\build\entrypoint\build.dart 35:16                                main
> 
> pub finished with exit code 1 
>

**Comment by jakemac53** [comment]
It sounds like maybe your working directory is write protected? I don't believe we have any way of working around this, we need to be able to write to your package directory.

**Comment by Kareem21227gg** [comment]
thanks im gonna try thaa

**Comment by jakemac53** [comment]
Closing as I don't think there is anything actionable for us here.

**Comment by jaustin42** [comment]
This does not appear to be a permissions issue.  Maybe the file is being accessed by two processes, or it is trying to create a directory that exists?

```
>rmdir /s .dart_tool
.dart_tool, Are you sure (Y/N)? y

>dir .dart_tool

File Not Found

>flutter pub get
Running "flutter pub get" in posh_poc...                         1,233ms

>dir .dart_tool

12/24/2022  02:52 PM    <DIR>          .
12/24/2022  02:52 PM    <DIR>          ..
12/24/2022  02:52 PM    <DIR>          dartpad
12/24/2022  02:52 PM            15,776 package_config.json
12/24/2022  02:52 PM            14,838 package_config_subset
12/24/2022  02:52 PM                 6 version
               3 File(s)         30,620 bytes
               3 Dir(s)  26,852,614,144 bytes free

>flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 370ms

[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 5.9s



You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


FileSystemException: Cannot create file, path = './.dart_tool' (OS Error: Access is denied.
, errno = 5)
dart:io                                                                      _File.createSync
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 76:30   _generateExtensions
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 132:32  SwaggerDartCodeGenerator.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33       _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9        new BuilderApplication.forBuilder.<fn>.<fn>package:build_runner_core/src/package_graph/apply_builders.dart 346:27       _createBuildPhase\
sForBuilderInCycle.<fn>.<fn>
dart:core                                                                    Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8        createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29                BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42               BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                          build
package:build_runner/src/entrypoint/build.dart 35:18                         BuildCommand._run
package:args/command_runner.dart 209:13                                      CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                           run
.dart_tool\build\entrypoint\build.dart 49:16                                 main
```

**Comment by ganeshnikale** [comment]
FileSystemException: Cannot create file, path = './macos' (OS Error: Is a directory, errno = 21)
dart:io                                                                      _File.createSync
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 76:30   _generateExtensions
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 132:32  SwaggerDartCodeGenerator.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33       _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9        new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27       _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                                    Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8        createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29                BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42               BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                          build
package:build_runner/src/entrypoint/build.dart 35:18                         BuildCommand._run
package:args/command_runner.dart 212:13                                      CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                           run
.dart_tool/build/entrypoint/build.dart 49:16                                 main

pub finished with exit code 1

**Comment by jakemac53** [comment]
@ganeshnikale that looks related to the swagger_dart_code_generator package https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/3228c9b8e2173bf98a9eba24bb698f06e62473c6/lib/swagger_dart_code_generator.dart#LL76C8-L76C28 I would file an issue on them
