### ISSUE TITLE
Support for backend proxy

### ISSUE THREAD

**Issue by wytrych** [dart-lang/build#3277]
Feature request:

Same as https://github.com/flutter/flutter/issues/51530 but maybe this repository is a better place for such a request? In short - run a configurable proxy server for development to allow requests against different backends. It's standard practice with modern frameworks and is built into webpack for example.

**Comment by jakemac53** [comment]
We have had requests this before, but don't have any plans to implement it at this time.

It is my opinion at least that the server provided by build_runner should be one of the services that is delegated to by some other higher level proxy server. It is not within the scope of this package to provide such a proxy server though, this package is solely focused on building and then serving up exactly the files it has built, at the locations it built them.
