### ISSUE TITLE
Selective build with filter presets

### ISSUE THREAD

**Issue by subzero911** [dart-lang/build#3289]
I want to have building presets, to rebuild not the whole project, but, say, MobX stores only, or Hive type adapters, or JsonSerialzable models only:
```
$ flutter pub run build stores
$ flutter pub run build type_adapters
$ flutter pub run build models
```
It's partially implemented already with a `--build-filter` parameter, but it's very cumbersome, requiring you to write the full path every time:
```
$ flutter pub run build_runner build --build-filter="lib/foundation/data_persistence/hive/type_adapters"
```
So it's probably should be some kind of build filter aliases / presets, allowing you to define the path in your `build.yaml` with a custom name and reuse it.

The idea is taken from this package https://pub.dev/packages/fast_i18n , where you can run
```
$ flutter pub run fast_i18n
```
and it will generate localization files only.

**Comment by jakemac53** [comment]
I would suggest making scripts under the `tool` directory of you package which run the various workflows that make sense for your project.

Individual packages also already have a way to release something like this to you today - they could ship a script under `bin` which runs build_runner with certain flags.

Given the existing options, I am not sure something like this makes a lot of sense to implement as a feature. It would be difficult to generalize I think, and probably isn't worth cost of implementation/maintenance.

**Comment by subzero911** [comment]
> I would suggest making scripts under the tool directory of you package which run the various workflows that make sense for your project.

Thanks, I tried your approach with creation of tools folder with 1-line .sh scripts, and found it working very well.
By the way, where can I read more about `bin` scripts?

> they could ship a script under bin which runs build_runner with certain flags.

**Comment by jakemac53** [comment]
> By the way, where can I read more about `bin` scripts?

https://dart.dev/tools/dart-run#running-a-program-thats-in-a-package has some info (and related links). Basically anything under `bin` can be ran via `dart run <package-name>[:script_name]`.

> (I have checked this out https://github.com/Tienisto/flutter-fast-i18n/blob/master/bin/fast_i18n.dart and hasn't understand how does it ever work).

This is not using build_runner, so it isn't a good example of what I mean.

I was really suggesting just a script that runs build_runner directly, something like:

```dart
import 'dart:io';

void main(List<String> args) async {
  args.addAll(['--build-filter', '<some-filter>']); // Any custom args here.
  var process = await Process.start(Platform.resolvedExecutable, args);
  process.stdout.pipe(stdout);
  process.stderr.pipe(stderr);
  stdin.pipe(process.stdin);
  exitCode = await process.exitCode;
}
```

Basically just the equivalent of the shell script, but in dart, and a bit more complicated because you have to manually pipe stdin/stdout/stderr.

**Comment by jakemac53** [comment]
Closing this issue based on the available workarounds
