### ISSUE TITLE
Inconsistent docs about builder key in builder configuration (build.yaml)

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/build#3293]
I'm learning about code generation and I am reading all there is about it and noticed the following: here https://github.com/dart-lang/build/blob/0f5cb1c5d12a082b0e0ab2a8c18ff9ecdaaa9510/build_config/README.md?plain=1#L41 it says the builder key syntax is `packageName:builderName`, but here https://github.com/dart-lang/build/blob/0f5cb1c5d12a082b0e0ab2a8c18ff9ecdaaa9510/docs/build_yaml_format.md?plain=1#L129 it says it is `packageName|builderName`. Judging by examples, e.g. https://github.com/rrousselGit/freezed/blob/master/packages/freezed/build.yaml#L13 and https://github.com/google/json_serializable.dart/blob/master/json_serializable/build.yaml#L22 the former is wrong.

**Comment by jakemac53** [comment]
So actually, both work. cc @natebosch can you remember which one is the "recommended" approach?

**Comment by natebosch** [comment]
`:` is recommended. `|` is the legacy character that we moved away from because it's inconvenient to use in windows terminal IIRC.

**Comment by natebosch** [comment]
Although, it looks like we have a bug - I bet some output isn't as nice as it should be:

https://github.com/dart-lang/build/blob/0f5cb1c5d12a082b0e0ab2a8c18ff9ecdaaa9510/build_runner_core/lib/src/generate/phase.dart#L200-L206

**Comment by wujek-srujek** [comment]
Found the normalization code: https://github.com/dart-lang/build/blob/master/build_config/lib/src/key_normalization.dart. In this case I guess it would be better to change `build_yaml_format.md` file to recommend the recommended delimiter?

**Comment by jakemac53** [comment]
Yes I think we should just change all docs to suggest using `:`, and update the code that @natebosch found to support simplifying `:` as well :).

**Comment by wujek-srujek** [comment]
Hi, the docs now mention the recommended `:` character but I noticed that the schema located here: https://json.schemastore.org/dart-build.json would need to be updated as well, otherwise the regular pattern for builder key doesn't work for the recommendation as it requires `|`.

**Comment by natebosch** [comment]
@jakemac53 - do you think the schema should have an option between `|` and `:` or should it accept `:` only? I'm leaning towards `:` only...

**Comment by natebosch** [comment]
I can't quite tell from the readme how breaking changes are handled. There is a reference to putting a version number into the file name, but we don't have a version number we can refer to, unless we use the package version.

I guess if we make the regex allow either then we could consider it non-breaking?

@simolus3 - I think you had originally contributed the schema - do you know the patterns for making changes like this?

**Comment by jakemac53** [comment]
> @jakemac53 - do you think the schema should have an option between `|` and `:` or should it accept `:` only? I'm leaning towards `:` only...

I think `:` only

**Comment by wujek-srujek** [comment]
Please note that only supporting `:` in the schema will kind of break it for many existing packages as `|` , e.g. https://github.com/google/json_serializable.dart/blob/master/json_serializable/build.yaml#L22 will not validate against it without them changing anything in the project.

**Comment by simolus3** [comment]
Huh, I've always thought it was `:` for targets and `|` for builders (no idea were that came from lol).

Do `^(?:\w+\|)?\w+|\$default$` and `^(?:\w*\|)?\w+$` seem like reasonable regexps for target respectively builder keys to you? I can open a PR to change the schema then.

**Comment by natebosch** [comment]
> Huh, I've always thought it was `:` for targets and `|` for builders (no idea were that came from lol).

It used to be.

> Do `^(?:\w*:)?\w+|\$default$` and `^(?:\w*:)?\w+$` seem like reasonable regexps for target respectively builder keys to you? I can open a PR to change the schema then.

Yes, I think that looks good assuming we decide on `:` only instead of allowing either in the schema.
