### ISSUE TITLE
Undocumented inputs delivered to Builder.build()

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/build#3296]
According to the documentation here https://pub.dev/documentation/build/latest/build/Builder/buildExtensions.html and some more here https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md?plain=1#L37-L42 the input can be an empty string and then each input is considered matching.

I did so and I notice my builder gets curious inputs: `test/$test$`, `web/$web$`, `$package$` and `lib/$lib$`. This is in a Flutter project that's probably why `$web` is here. Why am I getting these, what do they mean, and could they please be documented?

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md talks about these a bit. They are what we call _synthetic inputs_.

Basically, they allow a builder which just wants to run on an entire package to pin to a synthetic input, that will (almost) always exist for all packages (unless they have custom sources/modules and don't include them in any).

One way to detect them would be to do a `buildStep.canRead` check on the input id, if you can't read your input, you know its a synthetic input or something similar.

**Comment by wujek-srujek** [comment]
Perfect, thank you for your answer and for updating the docs.
