### ISSUE TITLE
Inconsistent $package$ and $lib$ behavior with and without custom targets

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/build#3304]
I have an aggregate builder in a package which is depended upon by another package. All the builder does is
```dart
  @override
  Future<void> build(BuildStep buildStep) async {
    await for (final assetId in buildStep.findAssets(Glob('**'))) {
      log.info(assetId);
    }
```

Depending on whether the input is `$package$` or `$lib$` and depending on whether sources is configured in a custom target the behavior (what assets the `BuildStep` finds) is different/inconsistent:

Input: `$package$`, no `build.yaml` in dependent package, output:
```shell
[INFO] Running build...
[INFO] my_builder:my_builder on $package$:my_app|lib/main.dart
[INFO] my_builder:my_builder on $package$:my_app|pubspec.yaml
[INFO] my_builder:my_builder on $package$:my_app|pubspec.lock
[INFO] my_builder:my_builder on $package$:my_app|README.md
[INFO] Running build completed, took 10ms
```

Input: `$lib$`, no `build.yaml` in dependent package, output:
```shell
[INFO] Running build...
[INFO] my_builder:my_builder on lib/$lib$:my_app|lib/main.dart
[INFO] my_builder:my_builder on lib/$lib$:my_app|README.md
[INFO] my_builder:my_builder on lib/$lib$:my_app|pubspec.yaml
[INFO] my_builder:my_builder on lib/$lib$:my_app|pubspec.lock
[INFO] Running build completed, took 11ms
```

I.e. here the same assets are found, whether I use `$package$` or `$lib$` as input, the only difference seems to be the ordering.

Input: `$package$`, `build.yaml`:
```yaml
targets:
  flutter_experiments:my_target:
    sources:
      - $package$ 
  $default:
    auto_apply_builders: false
```
Output:
```shell
[INFO] Running build...
[INFO] my_builder:my_builder on $package$:my_app|lib/main.dart
[INFO] my_builder:my_builder on $package$:my_app|pubspec.lock
[INFO] my_builder:my_builder on $package$:my_app|pubspec.yaml
[INFO] my_builder:my_builder on $package$:my_app|README.md
[INFO] Running build completed, took 13ms
```

Input: `$lib$`, `build.yaml`:
```yaml
targets:
  flutter_experiments:my_target:
    sources:
      - $lib$ 
  $default:
    auto_apply_builders: false
```
Output:
```shell
[INFO] Running build...
[INFO] Running build completed, took 2ms
```

I.e. no matter whether I use `$package$` or `$lib$` the builder sees the same assets, EXCEPT when the input is `$lib$` and target.source is also `$lib$`, then it doesn't see any assets at all.

1. I'm actually surprised the first 2 cases (`$package$` or `$lib$`) result in the same assets - is there no difference between them?
2. Why doesn't the combination of `$lib$` as input and target sources `$lib$` find anything at all, contrary to input `$package$` and target sources `$package$`, which finds the same assets as when there is no custom target?

**Comment by jakemac53** [comment]
Note that the special `$lib$` asset is actually located at `lib/$lib$`. So this is actually what explains the behavior.

An _input extension_ matches the _suffix_ of files, so `$lib$` matches `lib/$lib$`. That is why the first example works.

In the later example, you are using a sources config to add `$lib$`, but that doesn't match any file. It is just a target with no sources, which fails. 

> 1. I'm actually surprised the first 2 cases (`$package$` or `$lib$`) result in the same assets - is there no difference between them?

Generally, yes there is no difference in terms of the visible inputs. What is different is how the outputs would be created (outputs are declared by replacing the matching _suffix_ with the output extension).

Fwiw `lib/$lib$` is actually completely unnecessary, we added `$package$` later on and ideally it would be the _only_ special marker like this, all the others are redundant and provide no real value, but we have builders that rely  on them that we don't consider it to be worth breaking, at least for now. In the next breaking release we may change this.

**Comment by wujek-srujek** [comment]
But in the latest example where I use `$lib$` - why isn't even `lib/main.dart` matching? And in another issue you mentioned that sources just extend the sources for all targets - so why does defining `$lib$` only not see all the other sources that are already defined?

**Comment by jakemac53** [comment]
> But in the latest example where I use `$lib$` - why isn't even `lib/main.dart` matching?

The issue is that your builder is never running _at all_. If it did run, it would see those sources. But the glob never even runs, because there are no sources in the target it is running on, so the input extension (`$lib$`) doesn't match anything, and the builder never runs.

The difference is primary inputs versus secondary inputs. This target:

```
flutter_experiments:my_target:
    sources:
      - $lib$ 
```

Actually has no sources, so no builder can ever run. If you update that to `lib/$lib$`, that will match the placeholder source, so a builder with input extension `$lib$` will run (it can suffix match that source).

**Comment by wujek-srujek** [comment]
I thought `lib/$lib$` and `$lib$` were aliases as they seemed to result in the same.
Anyway, thank you for your explanations, much appreciated.
