### ISSUE TITLE
Generate Required Source Generation from git dependency

### ISSUE THREAD

**Issue by Dargoz** [dart-lang/build#3319]
Compiler & Dependencies
--------
Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "windows_x64"

```
build_runner: "2.1.11"
json_annotation: "4.5.0"
json_serializable: "6.2.0"
```
Host : Microsoft Windows [Version 10.0.19044.1645]

Description
---------
Hi there, I want to ask if I could build code generation inside external dependencies? for example I included dependency :
```
git_issues_form:
    git:
      url: https://github.com/dargoz/git_issues_form
      ref: main
```
which use ``build_runner`` to generate some code related to ``json_annotation``, ``get_it``, etc.
and my current project use that dependency also do the same stuff, but apparently when I run ``flutter pub run build_runner build --delete-conflicting-outputs`` only my current project successfully generated and I got build error when I try to run the project.., something like this :
```
 Error: Method not found: '$initGetIt'.
void configureDependencies() => $initGetIt(getIt);
                                ^^^^^^^^^^

Error: Method not found: '_$IssueFromJson'.
  factory Issue.fromJson(Map<String, dynamic> json) => _$IssueFromJson(json);
```
those missing generated code come from git_issues_form dependency

Is it possible to make it also generate the required part .g.dart inside that dependencies ? or should commit the .g.dart part instead ?

**Comment by jakemac53** [comment]
I am going to close this issue but feel free to respond with additional questions.

**Comment by Dargoz** [comment]
> > Hi there, I want to ask if I could build code generation inside external dependencies? for example I included dependency :
> 
> You can only generate code inside dependencies if your builder is set as `build_to: cache` instead of `build_to: source`.
> 
> The pub cache is a shared immutable cache of packages, so it isn't safe for us to generate code inside there, but using `build_to: cache` places all generated files in a local cache to the package (`.dart_build/build/generated`).
> 
> This comes with its own downsides though (all people using your package must also use build_runner, and generate all files for all their dependencies). So the more common approach is to use `build_to: source` and then check in the generated files and publish them.

so that means the common approach is : I need to included the generated files and commit it to my git repo ?

**Comment by Dargoz** [comment]
got it, thank you 😁
