### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "flutter/.pub-cache/hosted/pub.dartlang.org/bloc-8.0.3"

### ISSUE THREAD

**Issue by Faamica** [dart-lang/build#3322]
Dart: 2.16.1
Flutter : 2.10.3
build_runner: ^2.1.8
Mac, M1

Hi, I've been using build_runner for using Hive.
However, after executing the command after a long time, the following error message appeared.
```Could not find a file named "pubspec.yaml" in "flutter/.pub-cache/hosted/pub.dartlang.org/bloc-8.0.3"```
```pub finished with exit code 66```

When I first installed hive and build_runner, it ran without problems.
Anyway I checked the path, but there is no bloc-8.0.3 folder
<img width="477" alt="image" src="https://user-images.githubusercontent.com/87428594/173210942-d30788d8-49ce-4097-bb3d-3c8cb95eb09d.png">

What Can I do to solve this?

**Comment by jakemac53** [comment]
It looks like you probably need to run a `dart pub get` or `flutter pub get`? Probably you had purged your pub cache at some point?
