### ISSUE TITLE
How to use build_runner in my app?

### ISSUE THREAD

**Issue by 20jun2022** [dart-lang/build#3324]
How to call the build_runner in my app to parse and generate code at runtime?
I am trying to build an app that parses dart code and make some useful stuff wih it.
I know that this isn't gonna support flutter but I'm ok with it.
So is there any 'api' to use the build_runner in my app?
Thanks!

**Comment by jakemac53** [comment]
I don't really understand what you are wanting to do here, but some options:

- There is a programmatic API exposed by [build_runner_core](https://pub.dev/documentation/build_runner_core/latest/build_runner_core/build_runner_core-library.html) but it requires a lot of setup. You may also be able to use the [build_test](https://pub.dev/documentation/build_test/latest/build_test/testBuilder.html) package for inspiration.
- If you have sources on disk that you want to generate code for, I would just do normal builds via `dart run build_runner build`, although you could also look into using the [build_daemon](https://pub.dev/documentation/build_daemon/latest/) package if you want more control over when builds happen.
