### ISSUE TITLE
output "pub finished with exit code 1" with "'super' can't be used as an identifier because it's a keyword."

### ISSUE THREAD

**Issue by takapiroid88** [dart-lang/build#3325]
i updated flutter version to 3.0.1 and dart 2.17.1.

i have below code in project.

```
class A extends B {
  A({
    required super.text,
  });

class B {
  B({
    required this.text,
  });
  final String text;
}
```

i tried to generate *.g.dart from other class.
(run " flutter packages pub run build_runner build --delete-conflicting-outputs")
its generated but console output "pub finished with exit code 1".

with

```
outputs...
................
This builder requires Dart inputs without syntax errors.
However, xxx.dart (or an existing part) contains the following errors.
xxx.dart:394:14: 'super' can't be used as an identifier because it's a keyword.

Try fixing the errors and re-running the build.
```

"xxx.dart:394:14:" is above "class A" code at "required super.text".

how to solve this error?
help me.

### environment
```
dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^4.1.3
```

```
 % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale ja-JP)                                                                                                                                                      Checking Android licenses is taking an unexpectedly long time...
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by jakemac53** [comment]
It looks like you need to either update  your analyzer package to a version that supports super parameters (`flutter pub upgrade` should do it unless you are not able to get the latest due to some other package limiting it), or possibly you need to update your min sdk version of your package so that you are on the latest language version (at least 2.17).

**Comment by takapiroid88** [comment]
my pubspec.yaml, target sdk is below.

```
environment:
  sdk: ">=2.17.0 <3.0.0"
```

which package depend on this problem do you know?

i'm using that relate package to generate code, json_serializable, json_annotation.

there are not able to get the latest due to other package limiting now.

**Comment by takapiroid88** [comment]
resolved it.

```
dependencies:
  json_annotation: 4.1.0

dev_dependencies:
  json_serializable: 4.1.4

```

above package and version occured error.

i created new project.
and install these package newer version.
it solved.
