### ISSUE TITLE
Enable consumers to configure builder ordering

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#3328]
See https://github.com/google/reflectable.dart/issues/278 for context.

Sometimes two builders which don't actually know about each other, must be ran in a particular order. Ideally those builders would not have to know about each other directly (unless some explicit coupling already exists), but today the only way to resolve this situation is for one of the builders to configure itself to run after or before the other builder.

It would instead be better if the user who has enabled both of these builders, could configure them to run in the correct order, removing the unnecessary coupling between the unrelated builders.

## Possible solution

One solution could be to allow the user to express dependencies from builders to other builders. This would basically just add extra edges to the existing dependency graph we set up between builders when determining ordering. This would make the builder author ordering and user ordering compose well together, and warn appropriately on cycles etc.

The configuration could just be a map of builder keys to a list of builder keys that must run before (or after) that builder, something like:

```yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        runs_before:
          - reflectable
```

We could also potentially allow this under the "global" configuration, but we could start with only target level.

**Comment by natebosch** [comment]
> We could also potentially allow this under the "global" configuration, but we could start with only target level.

Today we order builders once, while generating the build script. We do not have target level information at that time. Implementing a global config would be easy, but implementing per-target ordering would be a much bigger change.

I'm in favor of a global option for this. We need to decide if this config appends or replaces the original config - I think it should append.

**Comment by jakemac53** [comment]
Ah interesting, yeah I forgot that we did the builder ordering more globally.

> I'm in favor of a global option for this. We need to decide if this config appends or replaces the original config - I think it should append.

This generally SGTM, although it won't work for packages on pub, but we don't have many packages that publish on pub but require you to do codegen separately afaik (other than angular).

You could always require your users to write their own global config I suppose as well.

**Comment by shtse8** [comment]
Hi,

I have a question about implementing run_after. How can I ensure that my builder runs after freezed|freezed?

Thank you for your help!

**Comment by natebosch** [comment]
> How can I ensure that my builder runs after `freezed|freezed`?

You can also use `required_inputs: [".freezed.dart"]` - since the freezed builder outputs that extension it will run before your builder.
