### ISSUE TITLE
You have hit a bug in build_runner

### ISSUE THREAD

**Issue by bshlomo** [dart-lang/build#3330]
Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "windows_x64"

While trying to build a web app

Using Intelij
IntelliJ IDEA 2022.1.2 (Community Edition)
Build #IC-221.5787.30, built on May 31, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 7 6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 986M
Cores: 4
Non-Bundled Plugins:
    Dart (221.5787.37)

"C:\Program Files\Dart\dart-sdk\bin\dart.exe" pub global run webdev daemon web:53322 --launch-app=web/index.html

[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 1.3s
[INFO]
[INFO] Invalidated precompiled build script due to core package update
[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 29.8s
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs

[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[WARNING] Throwing away cached asset graph because the language version of some package(s) changed. This would most commonly happen when updating dependencies or changing your min sdk constraint.
[INFO] Cleaning up outputs from previous builds....
[SEVERE]
[SEVERE]
[SEVERE] You have hit a bug in build_runner

[SEVERE] Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

[SEVERE]
[SEVERE]

[SEVERE] FileSystemException: Deletion failed, path = '.dart_tool/build/generated' (OS Error: The directory is not empty.
[SEVERE] , errno = 145)
[SEVERE] dart:async                                                           _CustomZone.runUnary

[SEVERE] package:build_runner_core/src/generate/build_definition.dart 333:7   _Loader._deleteGeneratedDir
[SEVERE] package:build_runner_core/src/generate/build_definition.dart 444:7   _Loader._cleanupOldOutputs.<fn>
[SEVERE] package:build_runner_core/src/logging/logging.dart 25:18             logTimedAsync

[SEVERE] package:build_runner_core/src/generate/build_definition.dart 424:5   _Loader._cleanupOldOutputs
[SEVERE] dart:async                                                           Future.wait.<fn>
[SEVERE] package:build_runner_core/src/generate/build_definition.dart 383:11  _Loader._tryReadCachedAssetGraph.<fn>
[SEVERE] package:build_runner_core/src/logging/logging.dart 25:18             logTimedAsync
[SEVERE] package:build_runner_core/src/generate/build_definition.dart 213:22  _Loader.prepareWorkspace

[SEVERE] package:build_runner_core/src/generate/build_impl.dart 114:27        BuildImpl.create
[SEVERE] package:build_runner/src/daemon/daemon_builder.dart 230:19           BuildRunnerDaemonBuilder.create

[SEVERE] package:build_runner/src/entrypoint/daemon.dart 93:17                DaemonCommand._run
[SEVERE] package:args/command_runner.dart 209:13                              CommandRunner.runCommand
[SEVERE] package:build_runner/src/entrypoint/run.dart 26:18                   run
[SEVERE] .dart_tool\build\entrypoint\build.dart 101:16                        main

[SEVERE]

Process finished with exit code 1

-----

**Comment by jakemac53** [comment]
@bshlomo did you possibly have multiple builds going at the same time? For instance if you are running webdev and then also do a build on the side (or maybe `dart run build_runner test`, which also does a build?).

**Comment by bshlomo** [comment]
@jakemac53 Yes. I am using this practice sometimes
In this case, after I run all the builds for all projects, one after another, the build was finished without errors
