### ISSUE TITLE
Is it safe to share `Resource` between different builders? 

### ISSUE THREAD

**Issue by wurikiji** [dart-lang/build#3350]
I have several builders `first_builder`, `second_builder`, `third_builder`, etc.

The order is strictly defined in the `build.yaml` using `runs_before` option.

The generated in-memory data should be passed to the next builder during the build. So I am using `Resource` and `buildStep.fetchResource()` right now. 

It seems to work properly, but I want to ensure that this is safe to run. 

Is this a safe approach to sharing the intermediate in-memory data between builders?

**Comment by jakemac53** [comment]
It is, but Resources are easy to use incorrectly. Make sure you fully read the docs https://pub.dev/documentation/build/latest/build/Resource-class.html. In particular, this part:

```
Most resources should accept a BuildStep, or an AssetReader argument and ensure that any assets which contribute to the result have an interaction for each builder which uses that result. For example if a resource is caching the result of an expensive computation on some asset, it might read the asset and perform some work the first time it is used, and call only AssetReader.canRead to verify the caller is allowed to access the information before returning the cached result on subsequent calls.
```
