### ISSUE TITLE
"ENTRYPOINT_EXTENSION_MARKER" is misspelled to "ENTRYPOINT_EXTENTION_MARKER"

### ISSUE THREAD

**Issue by eggfly** [dart-lang/build#3360]
I think it's misspelled in:

https://github.com/dart-lang/build/blob/09c1d25b77d3181c8d3d93340b329e84696cdc5f/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L502
https://github.com/dart-lang/build/blob/f70760a8d783585ba300364a09b131721ee4a6e8/build_runner/lib/src/server/server.dart#L31

But there's already some usage in flutter web project:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/bootstrap.dart#L134

**Comment by jakemac53** [comment]
Yes I think we should not fix this - it is something webdev also relies on afaik. Not worth potential breakage.

**Comment by gspencergoog** [comment]
@jakemac53 Could you support both spellings instead of only the misspelled one?
