### ISSUE TITLE
how to detect finished successful build_runner ?

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [dart-lang/build#3362]
We need to be notified of the successful completion (or failure to re-run) of build_runner. I need to call its command in a bash file, but the program It does not close after the operation completes (successfully or unsuccessfully). I want to use it in build automation steps (ci/cd). Please help on this particular issue thanks.

**Comment by jakemac53** [comment]
Are you using the `build` command? That does set the exit code based on build status https://github.com/dart-lang/build/blob/master/build_runner/lib/src/entrypoint/build.dart#L54.

**Comment by esmaeil-ahmadipour** [comment]
Thank.. finally  i use build command and close this issue.
