### ISSUE TITLE
Case that needs a `clean` before `build`

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/build#3371]
There's a specific case (legit) that before a `build` a `clean` is needed.

The case can be seen using the package
[reflection_factory](https://pub.dev/packages/reflection_factory)

In the example below you can build a proxy to the class `Foo` without import it:

(`proxies.dart`):
```dart
import 'package:reflection_factory/reflection_factory.dart';

part 'reflection/proxies.g.dart';

@ClassProxy('FooClass', libraryPath: 'package:foo/foo_lib.dart')
class FooClassProxy implements ClassProxyListener {
  
  @override
  Object? onCall(instance, String methodName, Map<String, dynamic> parameters, TypeReflection? returnType) {
    print('CALL>> $call');
    return 'ok' ;
  }

}
```

(The `FooClass` at `foo_lib.dart`):
```dart
class FooClass {

  String call1(String arg1) {
    return 'arg1: $arg1';
  }

  String call2(int n) {
    return 'n: $n';
  }

}
```

Then you can use the generated proxy in many different ways. Here's a simple example (without enter in a real use case of a proxy):

```dart
import 'proxies.dart';

void main() {

  var fooProxy = FooClassProxy();

  fooProxy.call1('x');

  fooProxy.call2(123);

}
```

The issue is when you change the `FooClass` it won't trigger a new build of the `reflection/proxies.g.dart` file, because this is only triggered by changes in `proxies.dart`.

The `build` framework doesn't have a way to tell that the generated file is dependent on a 3rd/extra file (`package:reflection_factory/reflection_factory.dart`).

If there was a feature that allows to inform that the asset being generated is dependent on an extra asset will be great, and resolve issues like that. My suggestion is to add a parameter to `BuildStep.writeAsString` that can indicate the extra assets:

```dart
  //...

  buildStep.writeAsString(genId, genCode, extraDependencies: [otherFileId]);

```

**Comment by jakemac53** [comment]
It sounds like this builder is using `dart:io` directly to read files. If you do that, then yes we won't set up dependencies properly.

You can indicate files are used manually by either calling `buildStep.canRead(<asset>)` or `buildStep.readAsString(<asset>)` etc though, to work around this.

But I would use the build step to read the files directly, instead of dart:io, if at all possible.

**Comment by gmpassos** [comment]
I'm the author of the package [reflection_factory](https://pub.dev/packages/reflection_factory).

The building process is not using `dart:io` to read or resolve any class from `.dart` files.

The `dart:io` package is being used by a separated tool, not related with the building process.

If you want to see how it uses `BuildStep` to find a class without import it, all is done through this method in `ReflectionBuilder._findClassElement`:

https://github.com/gmpassos/reflection_factory/blob/master/lib/src/reflection_factory_builder.dart#L343

**Comment by gmpassos** [comment]
I think that this shouldn't be closed.
