### ISSUE TITLE
Facing issue in build runner

### ISSUE THREAD

**Issue by siddhantpatil6** [dart-lang/build#3375]
AssetNotFoundException: mf|.packages
package:build_runner_core/src/asset/file_based.dart 135:18  _fileForOrThrow.<fn>
dart:async                                                  _CustomZone.runUnary
package:build_runner/src/generate/watch_impl.dart 341:20    WatchImpl._run.<fn>
what to do in such situation?

**Comment by jakemac53** [comment]
You need to update `build_runner`, the `.packages` file is no longer created by the SDK, and new versions don't require it.

**Comment by jakemac53** [comment]
Note that specifically [2.1.11](https://pub.dev/packages/build_runner/changelog#2111) is the version you need
