### ISSUE TITLE
Resolving `dart:` SDK libraries

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#3387]
This is mostly a question, but if it turns out to be impossible, then please view this as a feature request. I'm happy to implement support for it in that case.

Basically, I'm looking for a way to reliably resolve a `dart:` library through the build resolver (so that I can get the `LibraryElement` for it). I know that ASTs for `dart:` will probably not work in all implementations, but getting the element model should be fine?

I know that I can lookup libraries by name (so doing that with `dart.core` would work), but I'm also looking for ways to resolve libraries not imported by any of the entrypoints used by the resolver. Is there a decent way to get hold of a `LibraryElement` for an SDK library at the moment?

**Comment by jakemac53** [comment]
It seems to me like this works today? I tried adding the following test to build_resolvers which passes:

```dart
test('Can resolve sdk libraries that are not imported', () async {
    await resolveSources({
      'a|lib/a.dart': '',
    }, (resolver) async {
      var convert = await resolver.findLibraryByName('dart.convert');
      expect(convert, isNotNull);
      expect(convert!.getClass('Codec'), isNotNull);
    }, resolvers: AnalyzerResolvers());
  });
```

**Comment by simolus3** [comment]
Huh, I didn't expect this to work. The docs mention that imported libraries are available, so I'd expect that only `dart:core` would be reachable. Is this because `dart:core` imports the other SDK libraries?

**Comment by jakemac53** [comment]
I don't see any specific logic in there adding the SDK libraries, so I think that is probably the case. That would also explain why we don't see `dart:mirrors`, `dart:cli`, `dart:io`, etc, which I now realize are all missing :).

So yeah, I think there is a feature request here, maybe an api like `Resolver#libraryForUri`? I don't believe we have a way of creating an asset id for an sdk library, so you can't use `Resolver#libraryFor`. The naming becomes a bit unfortunate, but 🤷 .

**Comment by jakemac53** [comment]
Actually though this would end up requiring a breaking change for `package:build`, since that interface is meant to be implemented :(.

**Comment by jakemac53** [comment]
Given that, I think we should either make some way of talking about an SDK library with an `AssetId`, or allow `findLibraryByName` to search all available SDK libraries. If we do the latter we need to decide if they should all be added to `libraries` as well. 

Note that the API docs on `libraries` today actually says it does include all SDK libraries. It just lies :). But maybe just implementing that properly is the easiest fix.

**Comment by simolus3** [comment]
> Note that the API docs on `libraries` today actually says it does include all SDK libraries. It just lies :). But maybe just implementing that properly is the easiest fix.

I think that would be a decent solution, that also fixes `findLibraryByName` for free. I'll open a PR for that.
