### ISSUE TITLE
Make the apis in Resolver async

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#339]
Migrating to the AnalysisDriver will require some of the apis that are currently synchronous to instead return a Future.

In anticipation of that change we should start returning Futures wherever we'll need them.

**Comment by natebosch** [comment]
If the individual apis need to be async, should we make the BuildStep give you the Resolver instance synchronously? It feels a little weird to have to wait for the resolver and then also wait for it to do anything.

We could add a wrapper in package:build that can turn a `Future<Resolver>` into a `Resolver` which could make it easier to implement.

Are there any apis on Resolver which *won't* need to be async?

**Comment by matanlurey** [comment]
I'm +1 for whatever takes less "await" statements.

**Comment by natebosch** [comment]
The `release()` method could throw a wrench in that plan since it is (and should remain) synchronous but it's not visible to clients so we might be able to work around it. We might also be able to stop using it if we can get off of `package:code_transformers`

**Comment by matanlurey** [comment]
+1 for that too. +100 for deleting that package for all eternity.

**Comment by jakemac53** [comment]
As far as I can tell all methods on the abstract `Resolver` class will have to be async now. `computeLibraryElement` has become `getLibraryByUri`, and `computeKindOf` has become `getSourceKind`. Both of the new methods are async.
