### ISSUE TITLE
build_runner failer

### ISSUE THREAD

**Issue by Oldwarrior62** [dart-lang/build#3396]
Hello all;

I'm trying to save my data on the phone I used preferred preferences it works but data is lost when the phone is powered off.

I looked a few methods but have no idea what will work.

was going to use json but lost the video.

**any suggestions of something that works?**

found Hive interesting because of boxes trying to get it to work but stuck at trying to generate (part 'userInformation.g.dart';)

**getting this error** 

PS C:\Users\oldwa\E-SLB\e_slb> flutter packages pub run build_runner watch

[INFO] Generating build script...
[INFO] Generating build script completed, took 554ms

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 18ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 129ms

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

AssetNotFoundException: flutter_complete_guide|.packages
package:build_runner_core/src/asset/file_based.dart 135:18  _fileForOrThrow.<fn>
dart:async                                                  _CustomZone.runUnary
package:build_runner/src/generate/watch_impl.dart 329:20    WatchImpl._run.<fn>

pub finished with exit code 1

**tried theses commands**

dart run build_runner builder
flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
flutter pub upgrade
flutter pub add analyzer
flutter pub run build_runner clean
flutter pub cache repair
flutter clean
flutter pub get
dart pub add build_runner --dev

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  datetime_picker_formfield: ^2.0.1
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  analyzer: ^2.8.0
 # geolocator: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_tabler_icons: ^1.1.1
   # hive database generators
  build_runner: ^1.12.2
  hive_generator: ^1.0.1

PS C:\Users\oldwa\E-SLB\e_slb> flutter --version
Flutter 3.3.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18a827f393 (4 weeks ago) • 2022-09-28 10:03:14 -0700
Engine • revision 5c984c26eb
Tools • Dart 2.18.2 • DevTools 2.15.0

**Comment by jakemac53** [comment]
You need to update to a newer version of `build_runner`, at least `2.1.11`. The `.packages` file is no longer generated by the sdk tools (its now a `.dart_tool/package_config.json` file) so you need a version of build_runner that is compatible with that change.

**Comment by Oldwarrior62** [comment]
tried that gave ne none compatible error

after googling some I found these suggestions
 flutter pub upgrade --major-versions
flutter pub run build_runner build --delete-conflicting-outputs

Target of URI hasn't been generated: ''userInformation.g.dart''.
Try running the generator that will generate the file referenced by the URI.dart[uri_has_not_been_generated](https://dart.dev/diagnostics/uri_has_not_been_generated)

Could not find a file named "pubspec.yaml" in "C:\Users\oldwa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\json_serializable-6.5.4".


version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  datetime_picker_formfield: ^2.0.1
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  analyzer: ^5.2.0
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  
 # geolocator: ^8.0.5

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
