### ISSUE TITLE
NoSuchMethodError: The getter 'futureDynamicType' was called on null.

### ISSUE THREAD

**Issue by sunbao** [dart-lang/build#3399]
NoSuchMethodError: The getter 'futureDynamicType' was called on null.
Receiver: null
Tried calling: futureDynamicType
dart:core                                                       Object.noSuchMethod
package:analyzer/src/dart/element/element.dart 5660:40          LibraryElementImpl.createLoadLibraryFunctionForLibrary
package:analyzer/src/dart/element/element.dart 5510:9           LibraryElementImpl.createLoadLibraryFunction
package:analyzer/src/summary/resynthesize.dart 337:24           SummaryResynthesizer.getLibraryElement.<fn>
dart:collection                                                 _LinkedHashMapMixin.putIfAbsent
package:analyzer/src/summary/resynthesize.dart 325:36           SummaryResynthesizer.getLibraryElement
package:analyzer/src/summary/resynthesize.dart 387:20           SummaryResynthesizer._buildTypeProvider
package:analyzer/src/summary/resynthesize.dart 176:5            new SummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 339:9   new StoreBasedSummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 319:26  ResynthesizerResultProvider.createResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 78:5    new InputPackagesResultProvider
package:analyzer/src/dart/sdk/sdk.dart 96:19                    AbstractDartSdk.context
package:analyzer/src/context/context.dart 1971:46               PartitionManager.forSdk
package:analyzer/src/context/context.dart 740:50                AnalysisContextImpl.createCacheFromSourceFactory.createCache
package:analyzer/src/context/context.dart 745:38                AnalysisContextImpl.createCacheFromSourceFactory
package:analyzer/src/context/context.dart 472:14                AnalysisContextImpl.sourceFactory=
package:build_resolvers/src/resolver.dart 95:14                 new AnalyzerResolver
package:build_resolvers/src/resolver.dart 449:32                new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 132:19      BuildOptions.create
package:build_runner/src/generate/build.dart 90:36              build
package:build_runner/src/entrypoint/build.dart 28:24            BuildCommand.run
package:args/command_runner.dart 197:27                         CommandRunner.runCommand
package:args/command_runner.dart 112:25                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 112:14                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 23:31              run
.dart_tool\build\entrypoint\build.dart 19:22                    main

pub finished with exit code 1

**Comment by jakemac53** [comment]
Apologies for never responding here, I assume this is fixed now though as it looks like it was an analyzer issue, and others aren't complaining.

Please comment if you are still having the problem.
