### ISSUE TITLE
Add method of recognizing generated files

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#34]
After a build, the next build needs to know which files were generated previously, so that they aren't treated as inputs.

Proposed solution:

Output a `build_outputs.json` file under a new hidden folder `.build`, eventually this will be replaced by the dependency graph file, but for now it will just be a list of all output file ids. Just using JSON for now as its the easiest, eventually more formats need to be evaluated.

On startup, check if the file exists and:

- If it does exists, read the file and ignore all listed files as inputs. Probably also delete those files from disk (otherwise we can easily end up with stranded files, we can be smarter about this later on).
- If it doesn't exist, call `declareOutputs` on all builders in all phases, recording all declared outputs which would conflict with an existing file on disk. If there are conflicts then summarize the results to the user to confirm deletion of these files, and then start over.

**Comment by jakemac53** [comment]
cc @kegluneq @nex3 @munificent please review proposed solution. This should mean we don't need to require any specific file extensions in order to discover which files are generated files.

**Comment by jakemac53** [comment]
cc @kevmoo as well

**Comment by kegluneq** [comment]
I like this idea better than the other solutions we've discussed.

**Comment by nex3** [comment]
:+1:

I like that this dovetails well with on-disk caching of derived information.

**Comment by jakemac53** [comment]
Done
