### ISSUE TITLE
build_runner build with --enable-experiments fails 

### ISSUE THREAD

**Issue by annagrin** [dart-lang/build#3403]
It seems that the analyzer does not get the --enable-experiment arguments passed to it and throws here: https://github.com/dart-lang/build/blob/master/build_resolvers/lib/src/resolver.dart#L225

Repro: 
- replace man.dart in `webdev/example` with

```dart
void main() {
   print('TEST: ${(true, 3).runtimeType}');
}
```

- run the following command:
`dart run build_runner build --enable-experiment records`

- observe the compilation failure that indicates that records experiment is not enabled:

➜  example git:(master) ✗ dart run build_runner build --enable-experiment records
[INFO] Generating build script completed, took 165ms
[INFO] Reading cached asset graph completed, took 142ms
[INFO] Checking for updates since last build completed, took 374ms
[INFO] Running build completed, took 59ms
[INFO] Caching finalized dependency graph completed, took 146ms
[SEVERE] build_web_compilers:entrypoint on web/main.dart (cached):

This builder requires Dart inputs without syntax errors.
However, asset:webdev_example_app/web/main.dart (or an existing part) contains the following errors.
main.dart:13:19: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.

[SEVERE] Failed after 213ms
```

**Comment by jakemac53** [comment]
@annagrin did you try increasing the sdk constraint in the example to `>=2.19.0-dev`? I think you would have to be on 2.19 for it to work as well (that is likely the experimental language version).

I tried that and it works for me 👍
