### ISSUE TITLE
Trying to get g.dart from abi.json but i'm getting this issues

### ISSUE THREAD

**Issue by Sangza** [dart-lang/build#3410]
rying to generate .g.dart file from abi json then getting these error

`

[INFO] Generating build script...
[INFO] Generating build script completed, took 139ms

[INFO] Precompiling build script......
[WARNING] .dart_tool/build/entrypoint/build.dart:9:8: Error: Error when reading '../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/web3dart-2.4.1/lib/src/builder/builders.dart': No such file or directory
import 'package:web3dart/src/builder/builders.dart' as _i2;
       ^
.dart_tool/build/entrypoint/build.dart:18:10: Error: Undefined name 'abiGenerator'.
    [_i2.abiGenerator],
         ^^^^^^^^^^^^
.dart_tool/build/entrypoint/build.dart:32:9: Error: Undefined name 'deleteSource'.
    _i2.deleteSource,
        ^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 400ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
please i need help on this
-----

**Comment by jakemac53** [comment]
The file that is being imported there does not exist (`package:web3dart/src/builder/builders.dart`). If that is a generated file that isn't allowed - it would have to be a file that is built to source separately and shipped with the package.

**Comment by Sangza** [comment]
what can be done to get the g.dart correctly, cause i followed the docs rules and i'm still getting issues

**Comment by Sangza** [comment]
please can you give me a working command for making this work with abi.json or a tutorials

**Comment by jakemac53** [comment]
This issue isn't related to this package, but the `web3dart` package. I would file an issue there.

**Comment by jakemac53** [comment]
going to close this issue because I don't see anything for us to do, but you can respond and we can re-open it if the `web3dart` maintainers have additional questions.
