### ISSUE TITLE
Failed to build build_runner:build_runner, because The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>

### ISSUE THREAD

**Issue by Mae623** [dart-lang/build#3419]
* Dart SDK Version (`dart --version`)
2.18.5

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Mac mini, Ventura 13.0.1, Apple M1

Hello, when I run "flutter pub run build_runner build", I came across the error as below

```
Failed to build build_runner:build_runner:
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart:8153:48: Error: The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>'.
 - 'NodeListImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
 - 'TypeAnnotationImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
Try correcting the name to the name of an existing method, or defining a method named 'elementAtOrNull'.
    var elementType = typeArguments?.arguments.elementAtOrNull(0)?.typeOrThrow;
                                               ^^^^^^^^^^^^^^^

```

But I never do something to this file. I hope there is a way to solve it, thank you so much!

**Comment by jakemac53** [comment]
Do you have `dependency_overrides`?

**Comment by jakemac53** [comment]
Oh actually, it looks like you picked up `analyzer` version `5.3.0` which was a bad version and has since been redacted.

If you do a `flutter pub upgrade` you should get version `5.3.1` which fixes this issue.

**Comment by Mae623** [comment]
> dependency_overrides

I have no of memory it, and I can't find it in pubspec.yaml

**Comment by Mae623** [comment]
> Do you have `dependency_overrides`?

I have no of memory it, and I can't find it in pubspec.yaml

**Comment by Mae623** [comment]
> Oh actually, it looks like you picked up `analyzer` version `5.3.0` which was a bad version and has since been redacted.
> 
> If you do a `flutter pub upgrade` you should get version `5.3.1` which fixes this issue.

What confused me is that I didn't add analyzer package, should I add it in pubspec.yaml?
By the way, I do the "flutter pub upgrade" already before I open this issus.

**Comment by Mae623** [comment]
I found where is the question!
I can't upgrade the 'collection' package from 1.16.0 to 1.17.0 for flutter_test from sdk and flutter_localizations from sdk and flutter from sdk all depends on collection 1.16.0, so I can't upgrade analyzer to 5.3.1
Thank you so much, I will find if there is any way to solve it.

**Comment by jakemac53** [comment]
`analyzer` is what we call a "transitive dependency" - it's a dependency of a dependency, if that makes sense :).

It sounds like you may need to use some dependency overrides to fix your situation, although I see that flutter at HEAD does allow collection version 1.17.0, so upgrading flutter (possibly switching to the dev channel), should also solve the issue.

If you want to solve it with overrides, I would suggest overriding package:collection, like this:

```yaml
dependency_overrides:
  collection: 1.17.0
```

You will want to remove this once it is no longer necessary.

**Comment by Mae623** [comment]
> `analyzer` is what we call a "transitive dependency" - it's a dependency of a dependency, if that makes sense :).
> 
> It sounds like you may need to use some dependency overrides to fix your situation, although I see that flutter at HEAD does allow collection version 1.17.0, so upgrading flutter (possibly switching to the dev channel), should also solve the issue.
> 
> If you want to solve it with overrides, I would suggest overriding package:collection, like this:
> 
> ```yaml
> dependency_overrides:
>   collection: 1.17.0
> ```
> 
> You will want to remove this once it is no longer necessary.

You are very right!
I switch to master channel and solve this question.
very appreciate for your answer and suggestion~

**Comment by sdjwj1118** [comment]
最后怎么解决的 也遇到了

**Comment by Mae623** [comment]
> 最后怎么解决的 也遇到了

把channel 由stable 换成master 就行了，命令语句是 flutter channel master

更多的可以看这个issue
[https://github.com/flutter/flutter/issues/116755#event-8003835142](url)

**Comment by jakemac53** [comment]
fyi @scheglov - I think this only affects a subset of users that had ran a `pub get` prior to the bad version being pulled, but for those users, who are also on stable flutter, they are left in a bad spot currently.
