### ISSUE TITLE
Let the AssetReader in build_runner delay `canRead` and `readAs*` methods until the build catches up to an output

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#342]
Today we depend on synchronizing across phases so that all readable files are present on disk by the time a builder runs. Instead we should let each GeneratedAssetNode in the AssetGraph provide a `Future<bool>` which will wait until the `Builder` which would generate that asset runs and then fire to notify listeners whether it was actually output.

This might make sense on the `GeneratedAssetNode` class itself - or in some sort of parallel structure that tracks build progress. We might want to shift AssetGraph more towards the static structure of the build, and have another class which tracks the dynamic progress through the build.

**Comment by natebosch** [comment]
Blocked by https://github.com/dart-lang/build/issues/348 or we'll deadlock

**Comment by jakemac53** [comment]
This is somewhat resolved by the addition of the `isOptional` field on `BuildAction` which adds lazy/optional build steps... although not entirely.

**Comment by natebosch** [comment]
We might not want to do this for now. Since we're still using a Resolver implementation which locks we don't really want to start later phases unless we know the earlier ones don't need the Resolver.

We have something of a hole around this with `isOptional` today - we don't want to make that hole bigger...

**Comment by matanlurey** [comment]
@natebosch Want to punt to M1+?

**Comment by natebosch** [comment]
yeah, I don't think we're realistically going to do work on this very soon.

**Comment by jakemac53** [comment]
Agreed

**Comment by matanlurey** [comment]
Yay!

**Comment by natebosch** [comment]
I think this is basically done. The `isOptional` handling extends to any phase that might not need to run (for instance if it's in `test/` and we're only building `web/`). We still do have a concept of some phases being eager but it's working well and if we revisit that decision it will probably be in a much bigger overhaul than this issue signals.
