### ISSUE TITLE
build with --build-filter option fails if conflicting outputs error encountered

### ISSUE THREAD

**Issue by subzero911** [dart-lang/build#3420]
I tried to use --build-filter to avoid "conflicting outputs" error, and to build selectively only the one file I needed.
Unfortunately it did not help. The build runner still claims to rebuild the whole project.

![image](https://user-images.githubusercontent.com/12999702/206665107-aa7fa1e9-6e46-47fe-a4ba-507ae2a291fa.png)

Consider removing the conflicting outputs check if I use build-filters parameter, or to add some --ignore-conflicting-outputs flag.

**Comment by jakemac53** [comment]
The check needs to exist regardless of the `--build-filter` flag - when you ask to build something with build filter it may also build any other arbitrary files which are inputs to the file you asked to build (and their transitive inputs as well).

There is a `--delete-conflicting-outputs` flag which will just automatically go ahead and delete the conflicting outputs though, but  you have to make an explicit choice (either via the prompt or that flag).
