### ISSUE TITLE
Add a SummaryBuilder

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#343]
In the future we might want to run the anlayzer in-process or as a worker. As a first pass maybe write inputs to a temp directory and run the analyzer from there.

**Comment by matanlurey** [comment]
Do you imagine this (and #344) being part of `build_runner` or some other thing?

**Comment by matanlurey** [comment]
On a related note, maybe we need `IpcBuilder` and/or `AsyncWorkerBuilder`. Up to you though :)

**Comment by natebosch** [comment]
Both this and the DDCBuilder will probably start in the `build_runner` package but we could move them elsewhere if we find they have utility in general.

I don't expect we'll ever want to use them with bazel.
