### ISSUE TITLE
Ignoring builders configuration when running with --config

### ISSUE THREAD

**Issue by tilteddev** [dart-lang/build#3433]
Hi, I am facing this warning / issue which is not able to execute my builders configuration when running with `--config=development`.

* Dart SDK Version: 2.18.2
* Build Runner: 2.3.3
* OS: MacOS

**Command**
`flutter pub run build_runner build --delete-conflicting-outputs --config=development`

**Warnings** 
_[WARNING] Ignoring `builders` configuration in `build.development.yaml` - overriding builder configuration is not supported._

**build.development.yaml**

`
builders:
  ssoWidgetUrlBuilder:
    import: "package:example_app/application/utils/sso/sso_widget_url_builder.dart"
    builder_factories: ["ssoWidgetUrlBuilderDevelopment"]
    build_extensions: {"web/index.html.template": ["web/index.html"]}
    auto_apply: all_packages
    build_to: source
`

**Comment by jakemac53** [comment]
We do not support the `builders:` section in config overrides. IIRC you can just remove it from your `build.development.yaml`. If you are trying to change the configuration intentionally, that isn't allowed today.
