### ISSUE TITLE
Special caracters in project title causing memory leak when using build_runner

### ISSUE THREAD

**Issue by MathiasD4B** [dart-lang/build#3436]
Hello,

I've encoutered a bug that has blocked me for a while. I resolved it and wanted to let you know.

I am using auto_router in a flutter project. When running the command `flutter packages pub run build_runner build` , I ended up with "exhausted heap space, trying to allocate ..." messages, which was due to a memory leak caused by the build_runner. What's weird is that this command works perfectly on my co-worker's computer. After searching for a while, I found out that in some cases, some caracters in the project title will cause this memory leak when trying to use build_runner. In my case it was a "%", but it seems that a white space will have the same effect (see [this issue](https://github.com/flutter/flutter/issues/56435)).

[this issue](https://github.com/dart-lang/build/issues/2559) is also related but wasn't resolved

After removing the special caracters from the project title, everything works great.

The main difference between my set up and my co-worker's set up is that I'm on windows and he is on mac, so it may be related to the os.

**Comment by jakemac53** [comment]
The actual error being linked seems to be coming from the compiler which is also interesting.
