### ISSUE TITLE
build_runner No option to NOT clean (do not delete) previously generated files

### ISSUE THREAD

**Issue by jmandawg** [dart-lang/build#3443]
There appears to be no option to leave previously generated files:

[INFO] Cleaning up outputs from previous builds....

We have a workflow where we want to generate injectables/jsonserialize in the first step of pipeline, and the test mocks in a later step in the build pipeline than the other generated files to save on processing time.  

Currently it seems when we run the build runner for just the test moks, it deletes all previously generated output.

Is there a flag to disable this functionality?  I searched the code but did not see it.

**Comment by jmandawg** [comment]
We do change the buld.yaml file between stages to enable the mockBuilder and disable the injectible/jsonserializer builders.  Would that trigger an invalidation?

**Comment by jmandawg** [comment]
Our problem is the build runners are very slow, and they can't be run in parallel.

so to save time we have this (steps 2 and 3 run in parallel in gitlab):
```
  1. pre-build (build_runner) step (generate injectible/jsonserializer) 
  2. test step (use generated output from #1 and also generate mockito Mocks)
  3. build ios (using generated output from #1)
```
if we also generate mocks in step one it increases the entire pipeline time by around 5 minutes.

**Comment by jakemac53** [comment]
> We do change the buld.yaml file between stages to enable the mockitoBuilder and disable the injectible/jsonserializer builders. Would that trigger an invalidation?

Yes, changing build.yaml fully invalidates the build (and build script too). You should try to avoid doing this if you can.

**Comment by jakemac53** [comment]
You might be able to instead use the [build filters](https://github.com/dart-lang/build/blob/47dcd92f6eba6b0c457edb888b973464848d494c/docs/partial_builds.md?plain=1#L14) feature but it's somewhat likely that it won't actually end up working very well for you - depending on what other builders you have applied and whether your builders generate code "to source" which I think will make them always be generated.

You may also just want to use [generate_for](https://github.com/dart-lang/build/blob/47dcd92f6eba6b0c457edb888b973464848d494c/docs/faq.md#how-do-i-avoid-running-builders-on-unnecessary-inputs) configuration if you aren't already for your mocks - I think by default mockito will run on _all_ files when it really only needs to run on tests.

**Comment by jmandawg** [comment]
Thanks for the suggestions, yeah we are already using generate_for for all the builders.  
Were just trying to optimize things a little more, as once the projects get big things really start to slow down.

**Comment by jakemac53** [comment]
Another thing regarding mocks that you could experiment with is creating a single library (or small number of libraries) that you generate all your mocks in, and then import those from the tests, instead of regenerating the same mocks over and over for all tests. Mockito makes it really easy to do the latter but it is quite inefficient.

**Comment by jakemac53** [comment]
Also in general reducing the number of transitive imports in your test files would help the analysis go faster - I don't know the structure of your app but if it is a single large package, and you have just one or a small number of public imports under `lib` which your tests are all importing, breaking that up into smaller libraries and importing those from the tests can help. This may or may not be feasible though, depending on your situation (and whether you use a lot of unit tests, or more full integration tests that require essentially everything).

**Comment by jmandawg** [comment]
Thanks for the tips, i will look into them.  We have many packages under lib.  We have also thought of doing the library for other code as well, which may be a good idea, but we have so much parallel develment/branching/merging i'm not sure our team is ready for another repo to branch/merge/sync.  

Do you know if there any plan for build_runners to run in parallel?  I would think you'd just have to be able to define a dependency tree in the build.yaml.

**Comment by jakemac53** [comment]
> We have many packages under lib

My comment isn't really about the number of separate libraries, but how they are imported. Do you import exactly the libraries you need or do you have a convenience library which exports many other libraries, and then import that? If the latter, you pay the cost of all the _exported_ libraries when you import that public import, and it also hurts invalidation (all codegen will tend to get invalidated on any file change). This also generally applies to flutter hot reload last I checked fwiw, (although I think there has been work to be smarter but it's challenging/expensive to do finer grained dependency tracking).

> but we have so much parallel develment/branching/merging i'm not sure our team is ready for another repo to branch/merge/sync.

You may want to explore a mono_repo approach. There are downsides as well, but it does eliminate the need to sync multiple repos. Or you can use a private pub server (there are multiple solutions out there) so you would do internal development similar to how regular external development works. When teams are ready to release a package they actually just publish it to the private pub server and you get it by just doing a `dart pub upgrade`. Pretty cool stuff.

> Do you know if there any plan for build_runners to run in parallel? I would think you'd just have to be able to define a dependency tree in the build.yaml.

There is no plan for this, for code generators which build to cache you can actually generate code inside your dependencies which sort of does this, but all through one build_runner instance. Note that build_runner is quite heavy weight once you take analysis into account and you probably don't want to run multiple instances anyways (it can use up multiple GB of ram just to do the analysis for large projects).

**Comment by jmandawg** [comment]
Thanks for the feedback and info.  Very informative.  I will look into some of these options

**Comment by jakemac53** [comment]
See https://dart.dev/tools/pub/custom-package-repositories for info on private pub repositories.

I am going to close this for now as I don't believe there is anything we can do, but you can continue to ask questions if you like.
