### ISSUE TITLE
web project not being recognized as web in 2.19

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/build#3444]
We are upgrading Angular to use analyzer 5.4.0 but getting this exception when serving. Error happens in DDC and dart2js.

```
dart run build_runner serve --verbose
Building package executable... (8.3s)
Built build_runner:build_runner.
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 588ms

[INFO] Bootstrap:Precompiling build script......
[WARNING] Bootstrap:
../../../public/ngdart.dart/ngdart/lib/src/testability/testability.dart:5:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' show Element;
```

**Comment by sigmundch** [comment]
Seems likely related to package:build_runner, so I'm tentatively transferring the issue there.

**Comment by natebosch** [comment]
It looks like you changed some imports around, and are now importing more from the library that defines a `Builder` than you used to.

This error is telling you that while trying to compile the build script - which imports the library defining the `Builder` - there was an unsupported import.

@jakemac53 might still have a script that can help you track down the import causing the problem, but I would take a look at anything you changed in the transitive import set from the `Builder`

**Comment by jakemac53** [comment]
What @natebosch said, the utility I have to help find the import path is [package:import_path](https://pub.dev/packages/import_path). It is probably behind on analyzer versions so if you hit issues feel free to file one on the repo and I can update it.

**Comment by jodinathan** [comment]
found the issue. There is a reason why angular use `TypeChecker.fromUrl` instead of `fromRuntime`

thanks
