### ISSUE TITLE
Flutter build_runner error after upgrading to flutter 3.7.0

### ISSUE THREAD

**Issue by halilbulentorhon** [dart-lang/build#3447]
We are executing "flutter packages pub run build_runner watch --delete-conflicting-outputs" but it throws a "Invalid argument(s): name shouldn't end with a '.'" error. It was working fine until we upgrade flutter version from 3.3.10 to 3.7.0. The file which throws that exception is "logger.dart"

**Comment by lucas404x** [comment]
Yep, this is happening to me as well. I was trying to add a new field for a specific class using the [json_serializable](https://pub.dev/packages/json_serializable/changelog). This was the error using --verbose:

```
[FINE] json_serializable on lib/src/shared/widgets/save_module_operation_result/save_module_operation_result.page.dart:Running JsonLiteralGenerator - 2 of 2 
[FINE] json_serializable on lib/src/shared/widgets/widgets.dart:Running JsonSerializableGenerator - 1 of 2
[FINE] json_serializable on lib/src/shared/widgets/widgets.dart:Running JsonLiteralGenerator - 2 of 2
[SEVERE] Build:
Unhandled build failure!
Invalid argument(s): name shouldn't end with a '.'
package:logging/src/logger.dart 82:7   new Logger._named
package:logging/src/logger.dart 64:47  new Logger.<fn>
dart:collection                        _LinkedHashMapMixin.putIfAbsent
package:logging/src/logger.dart 64:16  new Logger
package:logging/src/logger.dart 93:16  new Logger._named
package:logging/src/logger.dart 64:47  new Logger.<fn>
dart:collection                        _LinkedHashMapMixin.putIfAbsent
package:logging/src/logger.dart 64:16  new Logger
package:build_runner_core              _SingleBuild._runForInput.<fn>.<fn>
package:pool/pool.dart 127:14          Pool.withResource
```

**Comment by halilbulentorhon** [comment]
> 

change your loggin version to "1.1.0" from your pubspec.lock file. then run flutter pub get command

logging:
    dependency: transitive
    description:
      name: logging
      sha256: c0bbfe94d46aedf9b8b3e695cf3bd48c8e14b35e3b2c639e0aa7755d589ba946
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"

**Comment by lucas404x** [comment]
wow, thank you so much @halilbulentorhon ! 
It worked like a charm here

**Comment by jakemac53** [comment]
It looks like we create the name here https://github.com/dart-lang/build/tree/5b4222bafff7f28b03f4f674e18b54b33052ad47#L943, so if a file name ends with a `.` we would create a name like that. I wish the error here told us the name of the asset... :/

**Comment by jakemac53** [comment]
I am going to close this though if the latest logging package resolves the issue, not sure why it would but 🤷

**Comment by Passer-by** [comment]
I use logging 1.1.1 have the same error
