### ISSUE TITLE
Using a dependency as an input

### ISSUE THREAD

**Issue by VerTiGoEtrex** [dart-lang/build#3449]
* Dart SDK Version (`dart --version`): **`Dart SDK version: 2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "macos_arm64"`**
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * `build 2.3.1`
  * `build_config 1.1.1`
  * `build_daemon 3.1.0`
  * `build_resolvers 2.1.0`
  * `build_runner 2.3.3`
  * `build_runner_core 7.2.7`
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  * **`dart-protoc-builder` found [here](https://github.com/pikaju/dart-protoc-builder)**
  * **My own builder (which I need help with)**
* Whether you are using Windows, MacOSX, or Linux (if applicable): **MacOSX**
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): **NA**
* Any other packages or constraints we should know about: **NA**

In the end, I'm aiming to generate a "client" class to help me access a pubsub service which uses protobuf for messages.

I've set things up to have three packages
- apis (the package which contains the compiled protos)
- client (the package which autogenerates a client using the compiled protos from `apis`)
- app (uses both of the above to do interesting things)

# Generating the compiled protos (`apis`)

I successfully setup `apis`. It uses [dart-protoc-builder](https://github.com/pikaju/dart-protoc-builder) to spit out a tree of compiled protobufs.

It looks something (slightly minimized) like this
```
apis/
├── protos/
│   ├── symlink_to_some_protos_1/
│   └── symlink_to_some_protos_2/
├── lib/
│   └── compiled_protos_end_up_here/
│       ├── proto1.pb.dart
│       ├── proto1.pbenum.dart
│       └── proto1.pbjson.dart
└── build.yaml
```

# Generating a client from the protos (`client`)

Next, I want to generate a client from the protos. I previously had this working in a janky way by building as part of `apis`, so I know my code works. Now I'm struggling to move it into its own package depending on `apis` rather than building within the same package.

Since this builder itself depends on one or two of the compiled protos (I mean it literally imports them, not just uses them as sources for the code gen) it cannot stay in the `apis` package.

`build_runner` constructs all builders at the start. This means it wants to run like this: 

`dart-protoc-builder ctor -> client_builder ctor -> run dart-protoc-builder -> run client_builder`. 

But, since my client generator depends on (literally imports inline) the output from the protoc generator I'd need it to run like this, which it does not: 

`dart-protoc-builder ctor -> run dart-protoc-builder -> client_builder ctor -> run client_builder`

Splitting into a new package was my idea to enforce this execution timeline and solve this problem.

It looks something like this
```
client/
├── lib/
│   └── _nongenerated/
│       └── client_builder.dart
└── build.yaml
```

client_builder needs to access the `*.pb*.dart` files from `apis` to generate a client which uses those generated messages. Unfortunately, it seems that they're not accessible from the `client` build context. Any advice on how to work around this?

To better illustrate the problem, here's what the two modules look like together:

```
.
├── client/
│   ├── lib/
│   │   ├── _nongenerated/
│   │   │   └── client_builder.dart   <--< wants to use <--|
│   │   └── client.g.dart <^^^^ to generate this client    |
│   └── build.yaml                                         |
└── apis/                                                  |
    ├── protos/                                            |
    │   ├── symlink_to_some_protos_1/                      |
    │   └── symlink_to_some_protos_2/                      |
    ├── lib/                                               |
    │   └── compiled_protos_end_up_here/                   |
    │       ├── proto1.pb.dart                ]            |
    │       ├── proto1.pbenum.dart            ] --->---->--|
    │       └── proto1.pbjson.dart            ]
    └── build.yaml
```

For a greater sense of what I'm doing, here's the builder I had working before (with some distracting impl details removed). Note that I'm following the advice [here](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md) to process multiple inputs into a single output.

```
import 'dart:async';
import 'dart:convert';

import 'package:apis/somePBneededbythebuilder.pb.dart';
import 'package:apis/google/protobuf/descriptor.pb.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;
import 'package:protobuf/protobuf.dart';

Builder clientBuilder(BuilderOptions options) => ClientBuilder(options);

class ClientBuilder extends Builder {
  ClientBuilder(BuilderOptions options) {  }

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    // Accumulate all descriptor lines into a single file
    List<String> out = [];

    // Get all pbjson files. These will contain all possible message descriptors.
    await for (final input in buildStep.findAssets(Glob('lib/generated_protos_end_up_here/**/*.pbjson.dart'))) {
      // Find all descriptors
      // Using buildStep.* adds the dependency to the build asset graph which
      // ensures dependent resources are rebuilt if their dependencies change.
      final contents = await buildStep.readAsString(input);
      final descriptorLines = contents.split("\n").where((element) => element.contains(RegExp(r"final \$typed_data\.Uint8List .*Descriptor ="))).toList(growable: false);
      for (final line in descriptorLines) {
          out.add(line);
        }
      }
    }

    final outputAsset = buildStep.allowedOutputs.first;
    print("Writing client to: ${outputAsset.path}");
    // I know, this isn't a client. That code was way too long. Suffice to say that I need to read from `.pbjson.dart` in `apis` to generate this output.
    buildStep.writeAsString(outputAsset, out.join("\n"));
  }

  @override
  Map<String, List<String>> get buildExtensions => {
    r"$lib$": ["client.g.dart"]
  };
}
```

and the `build.yaml` for `client`:

```
targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/_nongenerated/client_generator.dart
    builders:
      client:ClientBuilder:
        options:

builders:
  clientBuilder:
    import: 'package:client/_nongenerated/client_generator.dart'
    builder_factories:
      - clientBuilder
    build_extensions:
      $lib$:
        - client.g.dart
    build_to: source
```

**Comment by jakemac53** [comment]
> Why wouldn't you allow a dependent to access files from its dependencies as part of its build?

Efficiency (fewer inputs) and invalidation (summary files change less often). We create a single summary file for a group of input dart files - often only one per entire package. Packages that depend on that package only require the summary and not the sources to build. These summaries don't contain method bodies, comments, or whitespace, and thus we don't have to rebuild package "b" if package "a" changes in one of those ways.

These summary files are sort of like c++ header files, but they are generated, and we only create one for any number of Dart files, instead of one per Dart file. Technically, it doesn't have to work this way, but you get a ton of benefits from it. We do allow access to type information from all transitive dependencies (all transitive summaries are available). We also have some extra smarts around reporting "unused inputs" after the fact to mitigate the effects of this on invalidation though.

> All of this makes me miss Bazel. Any sense for how likely Google will open-source the Bazel stuff for Dart (and maybe Flutter)?

We did try to do this a while back, but the efforts were scrapped. We have a lot of special internal stuff and it turned out we really couldn't share much. Ultimately we just ended up prioritizing other things. This would be a large project to maintain for us as a standalone thing.

> In other words: have apis run a second custom builder that globs for the .pb*.dart generated outputs and output them to another file within apis, let's say all_proto_file_paths.txt.

Yes, exactly. This file would always be emitted at a known location within the package so you don't have to glob for it later on. It would effectively cash the result of the glob as well, and the glob would essentially never have to re-run, because dependency packages are unlikely to change.

> Then how would client access that file to run its builder to generate the client, then? Since it's still in a dependency, I don't see how I could access it. Do you have a short snippet of code which would demonstrate child lib reading a file from parent lib? I thought child lib cannot access anything from parent lib.

If you know the name of the package containing the protos, something like this would work fine:

```dart
var protoFile = await buildStep.readAsString(AssetId('apis', 'lib/all_proto_files.txt'));
```

Otherwise finding the name of the package is the challenging part - we don't expose the package graph to you. You might need to require the user to configure your builder with a list of package names to search for protos?
