### ISSUE TITLE
Implement a way to determine which .dart files produce a .summary and .js file

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#345]
As a first pass for getting DDC working we'll only chunk strongly connect components into modules and let all other dart libraries stand as a library on their own.

Add some code that can take a `Resolver` for a dart library and figure out whether we'll be outputting a module for it - or if not which .dart file will get the module.

**Comment by matanlurey** [comment]
Maybe it makes sense to create a `ModuleBuilder`? i.e. writes a JSON file based on the module heuristic?

**Comment by natebosch** [comment]
We've definitely talked about a `ModuleBuilder`. Depending on how we get the analyzer wired up it may end up being faster to pull this out into a separate Builder so we can avoid repeating the work - but it could also end up being just as fast to recompute and then we don't have to worry about the transient file thing for a deployable output directory.
