### ISSUE TITLE
Can't use enable-experiment with web projects

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/build#3466]
We are testing `records` and `patterns` in our web app (AngularDart) using `dart run build_runner serve --enable-experiment="records,patterns"` and it works when you use the new features in the project but claims that `records` isn't enabled for files outside the project that use those features.

Digging the source code it only worked when we added `enabledExperiments: ['records', 'patterns']` to [FrontendServerClient.start](https://github.com/dart-lang/build/blob/1faecee3b71e54c8ec3b11dc46a2d0ec374aa1ff/build_runner/lib/src/build_script_generate/bootstrap.dart#L156)

I guess this is a bug?

Dart SDK version: 3.0.0-263.0.dev (dev) (Tue Feb 21 17:59:38 2023 -0800) on "macos_x64"

**Comment by jakemac53** [comment]
Ah so this is for the actual build script it looks like? What if you do `dart run --enable-experiment=records,patterns build_runner build`?

**Comment by jodinathan** [comment]
nope

```log
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 790ms

[INFO] Bootstrap:Precompiling build script......
[WARNING] Bootstrap:
../../../oni-group/server/oni_server/lib/src/storage/storage.dart:15:46: Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
      Uint8List bytes) contentTypeFinder) => (
```

**Comment by jakemac53** [comment]
You can try https://github.com/dart-lang/build/pull/3467, but I am pretty confident it works so you could also just wait
