### ISSUE TITLE
build_runner AssetNotFoundException when using the watch option

### ISSUE THREAD

**Issue by christianbookout** [dart-lang/build#3479]
* Dart SDK version: 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_x64"
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * ```
      build_runner:
      dependency: "direct dev"
      description:
        name: build_runner
        sha256: cd95f4d4a6a13b0dc1408b0a4b086bffdac08dcb61e45a0e1f2f58905d4c97a5
        url: "https://pub.dev"
      source: hosted
      version: "1.12.2"
    build_runner_core:
      dependency: transitive
      description:
        name: build_runner_core
        sha256: "653b9dfd0472476ca837ef62786717434b8fa4f5e5521c85d7376dd3234aefeb"
        url: "https://pub.dev"
      source: hosted
      version: "6.1.12"
    ```
*  Build command: `flutter pub run build_runner watch`
* Whether you are using Windows, MacOSX, or Linux (if applicable)
   * I am using MacOSX
* Any other packages or constraints we should know about
   * This does not occur when I run `flutter pub run build_runner build --delete-conflicting-outputs`, only when I use the `watch` option. 

Output:
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 467ms

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 18ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 199ms

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

AssetNotFoundException: my_project_name|.packages
package:build_runner_core/src/asset/file_based.dart 135:18  _fileForOrThrow.<fn>
dart:async                                                  _CustomZone.runUnary
package:build_runner/src/generate/watch_impl.dart 329:20    WatchImpl._run.<fn>

pub finished with exit code 1
```

**Comment by jakemac53** [comment]
This was fixed in `build_runner` version `2.1.11`, updating your build_runner version should fix it.
