### ISSUE TITLE
Implement a new Resolver and drop dependency on build_barback

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#348]

**Comment by matanlurey** [comment]
I imagine we want this based on `AnalysisDriver`, right?

`build/build_resolver`, and maybe share this with `_bazel_codegen` too?

**Comment by natebosch** [comment]
Most likely yes. Some slight differences since the build runner one won't use summaries but we should be able to abstract that away and share most of the implementation

**Comment by matanlurey** [comment]
Is this still planned?

There are at least two packages (refactoring tool and semver verifier) that need to resolve Dart libraries, and it would be worthwhile not to duplicate this very difficult to do/mostly unsupported API surface.

**Comment by natebosch** [comment]
Yes this is our highest priority item on our performance list and we hope to get to it soon. My current plan is to wait until we've published something with a working end to end and then decide whether I or @jakemac53 should start on this.

Jake started on a similar transition for bazel here: https://github.com/dart-lang/bazel/pull/184
I think we ran in to some issues with hooking in to the analyzer code to get it to read our assets instead of trying to read from disk and we're going to need to implement more support classes, like maybe a `ResourceProvider` to get it to work so it's not going to be a straightforward implementation.

**Comment by jakemac53** [comment]
I was talking with @stereotype441 yesterday about this as well, and he had some good feedback re the new frontend as well. We set up a more formal meeting for next week, which I will invite you to @matanlurey.

**Comment by matanlurey** [comment]
I think we decided that w'll push this for a time being. Moving to M1.

**Comment by jakemac53** [comment]
Closing as we no longer have a dependency on build_barback outside of a few tests, going to open a separate issue to clean that up.

When we are ready to migrate to a kernel based resolver we can create a new issue.
