### ISSUE TITLE
FeatureRequest: Validate if build_runner build would change anything

### ISSUE THREAD

**Issue by bw-flagship** [dart-lang/build#3486]
We sometimes have the problem that a change is made, but the dev forgets to run build_runner build.
It would be great to have a command that checks if a build WOULD change anything.
Then, in CI, we could do something like this:

```
hasChange = fvm flutter pub run build_runner checkIfChangeNeeded;
if (hasChange) throw Error();
```

**Comment by jakemac53** [comment]
There is this package you can use https://pub.dev/packages/build_verify. I generally prefer keeping this logic in a separate package like this where possible.
