### ISSUE TITLE
build_runner dose not work as expected with Dart 2.19 and reflectable

### ISSUE THREAD

**Issue by Vildnex** [dart-lang/build#3490]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version: 2.19.6 (stable) (Unknown timestamp) on "linux_x64"
* What package(s) from this repo you are using, and the version:
    - **reflectable:** 4.0.5
    - **build_runner:** 2.3.3
    - **built_value_generator:** 8.4.4
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
     I am running the one from **reflectable** lib
* Whether you are using Windows, MacOSX, or Linux:
     Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable):
     None

I make a git [repository](https://github.com/Vildnex/reflectable_bug) for this small bug.

# reflectable_bug
This repository is just for showing a bug regarding the reflectable package of dart/flutter 

## Steps to reproduce

1. Clone this repository
2. Run `dart pub get`

## Success case

1. Run `dart run build_runner build`
2. Everything works fine and will output this:

```
[INFO] Generating build script completed, took 452ms
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds. completed, took 3ms
[INFO] Generating build script completed, took 105ms
[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script... completed, took 1.1s
[INFO] Building new asset graph completed, took 1.1s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 2.1s
[INFO] Caching finalized dependency graph completed, took 30ms
[INFO] Succeeded after 2.2s with 1 outputs (6 actions)
```

## Failure case

1. Change the name of the `lib` folder to whatever else, in this case will be `main_dir`
2. Change in build.yaml the `lib` folder to the new name, in this case will be `main_dir`
3. Run `dart run build_runner build`
4. Nothing is going to happen and the build_runner will output this:

```
Built build_runner:build_runner.
[INFO] Generating build script completed, took 311ms
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds. completed, took 4ms
[INFO] Generating build script completed, took 56ms
[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script... completed, took 1.1s
[INFO] Building new asset graph completed, took 870ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 4ms
[INFO] Caching finalized dependency graph completed, took 30ms
[INFO] Succeeded after 49ms with 0 outputs (0 actions)
```

Doesn't matter if you change the name of the folder to something else, the build_runner will always output the same thing.

**Comment by eernstg** [comment]
The repository is called `reflectable_bug`, but this issue is in `dart-lang/build`. I think it's correct to classify it as being a build_runner issue and not a reflectable issue. So it doesn't have much to do with reflectable or me. ;-)

However, I would not expect that you can work with non-standard directories like `main_dir` in the root of a package. Dart tools expect to find certain directories (including `lib`, `bin`, `example`, `test`), as described in [Package layout conventions](https://dart.dev/tools/pub/package-layout), and many commands will ignore non-standard directories.

So you probably just need to put your `main.dart` into `bin` or keep it in `lib`.

**Comment by Vildnex** [comment]
I see... ok so is it standard... I was expecting this behavior to not work on flutter but not in dart. Thanks for the clarification :)
