### ISSUE TITLE
Generating files with build_runner taking more than 10 minutes 

### ISSUE THREAD

**Issue by prolificcoder** [dart-lang/build#3491]
Our flutter app is becoming huge about ~40 developers and 3000 tests and one aspect that is particularly annoying is the time required to create generated files in CI or locally. 

* Dart SDK Version (`dart --version`)
**Dart SDK version: 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_arm64"**
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
 **build_runner: 2.3.2**
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
* Mockito for tests -> *.mock.dart
* Freezed for data classes -> *.freezed.dart
* JSON Serializer for API classes -> *.g.dart
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Tried mac and linux
**-> linux 4g boxes: fails with pub finished with exit code -9
-> linux 14g boxes: 16 mins (CI box)
-> m1 mac: 8 mins
-> mac-ec2: 13 mins (mac CI box)**
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* Any other packages or constraints we should know about
**Flutter version 3.7.9**

I see there is an option to run build_runner as a web server with `serve`, can that used in a CI environment? Each PR will have different generated files, so not sure how that would work.

**Comment by jakemac53** [comment]
The first (and easiest) step towards trying to optimize builds is to use [generate_for](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-do-i-avoid-running-builders-on-unnecessary-inputs) to configure exactly which builders run on which files.

The next (harder) step would be to try and re-structure your imports, to reduce the number of unnecessary transitive imports that are imported by files that you run code generation on. You pay a cost for all the transitive deps, so importing exactly the libraries you need (or possibly even extracting out minimal pieces into new libraries and importing those) can help.

You can also follow [these instructions](https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md) to try and get an idea of where build time is going. We can try to help further if you can use that to identify areas of slowness.

Long term, we are working on integrating most codegen into the compiler via macros which will dramatically improve the situation (and scalability) here.

> I see there is an option to run build_runner as a web server with `serve`, can that used in a CI environment? Each PR will have different generated files, so not sure how that would work.

For CI builds, you can likely cache previous builds by caching and re-using the `.dart_tool` (or `.dart_tool/build`) directories. That should give you incremental builds whenever possible (which should be often, especially if you don't have custom builders and check in your `pubspec.lock` files).

**Comment by jakemac53** [comment]
@prolificcoder you can try this PR https://github.com/dart-lang/build/pull/3556 and see if it helps as well
