### ISSUE TITLE
Out-of-date dependency: build_runner

### ISSUE THREAD

**Issue by fennelhans** [dart-lang/build#3498]
I just submitted a pull request against the `dynamic_config_generator` package to update the dependencies in preparation for Dart 3. https://github.com/shkcodes/dynamic_config_generator/pull/5

I had to use an older version of the `build` dependency due to the dependency mismatch with `build_runner`. See the comment in that PR for additional details.

**Comment by jakemac53** [comment]
Thanks for the report, this should be fixed now in build_runner 2.4.2
