### ISSUE TITLE
Running code gen/generators for a different dependent Package(s)

### ISSUE THREAD

**Issue by donpaul120** [dart-lang/build#3513]
I have a usecase and i'm not sure if it's even possible.

I have a main app that depends on **packageA** and **packageB**

**PackageA** and **PackageB** uses freezed

within the **MainApp** i'm depending on **PackageA** and **PackageB** using `git:ref`

**PackageA** and **PackageB** ignores the generated code of` .freezed.dart` or `.g.dart`

is it possible such that the **MainApp** can trigger the `builder_runner` to generate those files within those packages??

What do i have to do or read on to achieve this.

**Comment by jakemac53** [comment]
In order for this to work, a builder must be marked as `build_to: cache` (this would be in the builder config in the build.yaml file for the builder). Then you would need it to be marked `apply_to: dependents` or something similar to make them apply to any package that depends on them and not just the root package.

These builders aren't intended to be used in the way you describe, so they mark themselves as `build_to: source` - you are generally expected to check in the outputs of builders like this to git and ship the sources with the packages.

You could possibly fork the packages and change their `build.yaml` configuration such that they work how you describe?
