### ISSUE TITLE
BuildForInputLogger needs to be updated for latest `pkg:logger`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#3514]
...specifically

error: Missing concrete implementation of 'getter Logger.onLevelChanged'. (non_abstract_class_inherits_abstract_member at [build_runner_core] lib/src/logging/build_for_input_logger.dart:13)

**Comment by kevmoo** [comment]
See https://github.com/flutter/website/actions/runs/5062554416/jobs/9088203605#step:3:1328

**Comment by dieferomanoski** [comment]
did you find any workaround solution for this? i need to use build_runner urgently

**Comment by knyghtryda** [comment]
add
```
dependency_overrides:
  logging: 1.1.1
```
That will hold the logging package back until the fix is rolled out.

**Comment by ditman** [comment]
Also reported here: https://github.com/dart-lang/logging/issues/143
