### ISSUE TITLE
How to generate codes for specific file

### ISSUE THREAD

**Issue by manhtran-itr** [dart-lang/build#3517]
I found a way to generate a specific file by adding generate_for into build.yaml file but
I always get the error
Found 460 declared outputs which already exist on disk. This is likely because the.dart_tool/buildfolder was deleted, or you are submitting generated files to your source repository. [SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with--delete-conflicting-outputs.

Because of the error, I must add the option '--delete-conflicting-outputs' it deletes all my files generated before I don't expect that. I want to generate a specific file and ignore all the previous files generated.

**Comment by jakemac53** [comment]
Whenever you are starting a fresh build, we require that all the outputs of the current build be deleted first.

Changing the `generate_for` config does I believe cause a new build always because it changes the shape of what we are building.

See https://github.com/dart-lang/build/blob/master/docs/partial_builds.md for how to build a specific output without changing the structure of the build (and thus requiring us to delete all the other outputs).

**Comment by jakemac53** [comment]
The document is general purpose it just uses web as an example. You can use the `--build-filter` flag to specify any _output_ file you want to build. Any inputs to that will also be built.

**Comment by manhtran-itr** [comment]
@jakemac53  We cannot generate the g.dart file. the output is Succeeded after 26ms with 0 outputs
Please help me to review the codes:

`name: test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

`import 'package:json_annotation/json_annotation.dart';

part 'test.g.dart';

@JsonSerializable()
class Test {
  final String a;

  Test({
    required this.a,
  });
}
`
cmd: flutter pub run build_runner build --build-filter 'lib/model/test.dart'

**Comment by jakemac53** [comment]
> flutter pub run build_runner build --build-filter 'lib/model/test.dart'

You need to specify the _output_ (the file you want to build), not the _input_ (the file you wrote). So it should be:

flutter pub run build_runner build --build-filter 'lib/model/test.g.dart'

**Comment by manhtran-itr** [comment]
@jakemac53  Thank you so much for your support. I did it.
