### ISSUE TITLE
Aggregate Builder not rebuilding once when input files update.

### ISSUE THREAD

**Issue by samyakkkk** [dart-lang/build#3534]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "macos_arm64"
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
```
 build: 2.4.1
 build_config: 1.1.1
 build_runner: 2.4.4
 build_runner_core: 7.2.10
```
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
I'm trying to use the simple aggregate builder as explained in the [documentation](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md).
* Whether you are using Windows, MacOSX, or Linux
MacOS
----

I'm using a basic aggregate Builder as defined in the docs with a custom script. It works the first time. Then if I make any changes to files in `lib` folder, the builder is supposed to rerun but it doesn't? It keeps showing 0 outputs and no builder prints in the logs are seen.

aggregate_builder.yaml:
```
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;

class ListAllFilesBuilder implements Builder {
  static final _allFilesInLib = new Glob('lib/**');

  static AssetId _allFileOutput(BuildStep buildStep) {
    return AssetId(
      buildStep.inputId.package,
      p.join('lib', 'all_files.txt'),
    );
  }

  @override
  Map<String, List<String>> get buildExtensions {
    return const {
      r'$lib$': ['all_files.txt'],
    };
  }

  @override
  Future<void> build(BuildStep buildStep) async {
    print('ListAllFilesBuilder');
    final files = <String>[];
    await for (final input in buildStep.findAssets(_allFilesInLib)) {
      files.add(input.path);
    }
    final output = _allFileOutput(buildStep);
    return buildStep.writeAsString(output, files.join('\n'));
  }
}
```

bin/files.yaml:
```
import 'package:build_runner_core/build_runner_core.dart' as build_runner_core;
import 'package:welltested/builder.dart' as welltested;
import 'package:build_runner/build_runner.dart' as build_runner;
import 'dart:io' as io;

final _builders = <build_runner_core.BuilderApplication>[
  build_runner_core.apply(r'welltested:allFiles', [welltested.listAllFiles],
      build_runner_core.toDependentsOf(r'welltested'),
      hideOutput: false)
];
Future<void> main(List<String> args) async {
  build_runner_core.overrideGeneratedOutputDirectory('welltested_save_cache');
  final result = await build_runner.run(args, _builders);
  io.exitCode = result;
}
```

builder.dart:
```
Builder listAllFiles(BuilderOptions options) => ListAllFilesBuilder();
```

**Comment by jakemac53** [comment]
Your builder doesn't actually depend on the contents of any files (it doesn't read them) - it only is dependent on the result of the Glob. So this builder would only get invalidated if a file matching that glob is created/deleted.

**Comment by samyakkkk** [comment]
I understand this technically. But when using builders, in most cases, we want to rerun them when the files content change. 

Doesn't aggregate builder not supporting it not usable most times?

**Comment by jakemac53** [comment]
Aggregate builders _do_ support re-running when files change. They are just optimized to not do that unless you actually read the file contents.

If you are reading the contents through some other process so the build system can't see that you actually depend on the contents, I would consider using a package such as `scratch_space` to set up a virtual directory in which to run those processes. That will go through the build system apis in order to actually read the files and set up the correct dependencies, and it will also help ensure that the process doesn't read anything additional that you didn't expect it to.
