### ISSUE TITLE
Support passing arguments to ddc

### ISSUE THREAD

**Issue by annagrin** [dart-lang/build#3535]
Apologies if I missed it, but is there a way to pass arguments to ddc in build_web_compilers, for example, `--canary` flag? 

Related: https://github.com/dart-lang/webdev/issues/1949

**Comment by natebosch** [comment]
We do not currently support passing arbitrary arguments to DDC.
Is this something that we expect end users to be able to do, or is this limited to Dart team use for testing purposes?

**Comment by annagrin** [comment]
> Is this something that we expect end users to be able to do, or is this limited to Dart team use for testing purposes?

This is only for testing features under development in DDC (the testing would be done in webdev)

**Comment by natebosch** [comment]
In the very short term I would override to a local copy of `build_web_compilers` and hardcode the argument in the list.
https://github.com/dart-lang/build/blob/ac65c072611ea105fe8ad9367c7938d743c82d22/build_web_compilers/lib/src/dev_compiler_builder.dart#L185

If you'd like to open a PR we could make `--canary` an explicitly supported flag similar to how we have one for `--emit-debug-symbols`. https://github.com/search?q=repo%3Adart-lang%2Fbuild+emitDebugSymbols&type=code

**Comment by annagrin** [comment]
Need a longer term, will open a PR for canary flag
