### ISSUE TITLE
 Error: The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>'

### ISSUE THREAD

**Issue by zhangli4659507** [dart-lang/build#3542]
Flutter 3.3.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4f9d92fbbd (10 months ago) • 2022-09-06 17:54:53 -0700
Engine • revision 3efdf03e73
Tools • Dart 2.18.0 • DevTools 2.15.0
----
question：
 flutter pub run build_runner clean
Failed to build build_runner:build_runner:
../../../develop/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-5.3.0/lib/src/dart/ast/ast.dart:8153:48: Error: The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>'.
 - 'NodeListImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../develop/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
 - 'TypeAnnotationImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../develop/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
Try correcting the name to the name of an existing method, or defining a method named 'elementAtOrNull'.
    var elementType = typeArguments?.arguments.elementAtOrNull(0)?.typeOrThrow;
                                               ^^^^^^^^^^^^^^^
pub finished with exit code 1

-----

**Comment by jakemac53** [comment]
@zhangli4659507 It looks like this is a bug in version 5.3.0 of analyzer, which was fixed in [5.3.1](https://pub.dev/packages/analyzer/changelog#531). Please upgrade your dependencies with `flutter pub upgrade`.
