### ISSUE TITLE
We might want different usage for `resolveSource`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#355]
The `tearDown` future feels a little clunky to me now that all the methods on `Resolver` are async. I had to add a bunch of completers in https://github.com/dart-lang/source_gen/pull/270 because you used to be able to do some synchronous work with the Resolver and now you can't.

It's possible that if we get off of `code_transformers` this issue might go away... if it doesn't we should consider a signature like:

```dart
Future resolveSource(String source, Future Function(Resolver) action)
```

Usage like:
```dart
setUp(() async {
  await resolveSource(source, (resolver) async {
    libraryElement = await resolver.findLibraryByName('foo');
  });
}
```

**Comment by jakemac53** [comment]
This would also get rid of the nested awaits in that pr which aren't ideal.

**Comment by natebosch** [comment]
@matanlurey - I'll probably make this change soon and update source_gen and angular to use it. Let me know if you have any concerns.
