### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by karthik14344** [dart-lang/build#3551]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw  GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    namespace "com.mycompany.login_firebase"
    compileSdkVersion 30
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.mycompany.login_firebase"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics'
    implementation platform('com.google.firebase:firebase-bom:32.2.2')
}

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\FLUTTER_COURSE\Flutter_Projects\login_firebase\android\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'android'.
> Supplied String module notation 'com.google.gms.google-services' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

unable to run my code because of this exception

**Comment by jakemac53** [comment]
This looks like an issue with the flutter `build` command, not the `build` package which is this repo (this is just for codegen).

Please re-open this at https://github.com/flutter/flutter/issues/new/choose

**Comment by karthik14344** [comment]
I already posted in that website.
https://stackoverflow.com/questions/76845037/build-gradel-exception-in-vscode-gradeleceptionn?noredirect=1#comment135472425_76845037

**Comment by MountahaBoukallel** [comment]
first you need to add this to your android\build.gradle 
classpath 'com.google.gms:google-services:4.4.1'

then apply your Google services plugin correctly without a version at the bottom of your app\build.gradle like this 

apply plugin: 'com.google.gms.google-services'

this should cover it

**Comment by karthik14344** [comment]
Error got resolved Long Back..Thank uu
