### ISSUE TITLE
Don't delete generated files from packages that are not enabled

### ISSUE THREAD

**Issue by ikbendewilliam** [dart-lang/build#3553]
Our build_runner build time is currently quite long and I've been looking on how to improve this. Currently when changing only one single dependency, 621 actions are executed taking 2 minutes. Most builds take 6-10 minutes. (note: we don't use convenience imports).

The best way I see is using different configurations, using the `-c` option. This way we could disable all packages and only enable one specific generator. For example we use drift for database and injectable for DI. When we change a DI we don't need to run the drift generator and the other way round. 

`flutter pub run build_runner build -c injectable`

The only issue I have with the config approach is that this deletes the output from the other generators. Meaning that if I run the injectable config, our database is deleted. Is there a way or can this be added to not delete generated files from packages that are not enabled? 

```
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (8 weeks ago) • 2023-06-13 15:51:02 -0700
Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "macos_x64"
```

Dependencies:
* build 2.4.1
* build_config 1.1.1
* build_daemon 4.0.0
* build_resolvers 2.2.1
* build_runner 2.4.6
* build_runner_core 7.2.10

Builders:
* drift_dev: ^2.8.3 (database)
* get_x_navigation_generator: ^0.0.12 (navigation)
* injectable_generator: ^2.1.6 (dependency injection)
* mockito: ^5.4.1 (test -> mocks)
* json_serializable: ^6.7.0 (json serialization)
* retrofit_generator: ^7.0.1 (http requests/services)

**Comment by vanlooverenkoen** [comment]
I have the same issue

We created a package called `model_generator`. This package generates dart code based on a yaml file. After we ran the model_generator we want to run `json_serializable` again to generate the `toJson` & `fromJson` methods in the `.g.dart` files. 

But right now all other builders are executed as well. Using the `-c` option indeed removed all the other files as well so currently it is not possible for us to make the build time smaller.

**Comment by jakemac53** [comment]
Question: Are you using `generate_for` to only run builders on the libraries they definitely need to run on?

That might be a simpler way to resolve this.

Another question: Have you tried using the `--build-filter` flag? You would specify the outputs you want to build, so you could do something like `--build-filter **/*.drift.dart` (guessing at file extensions here but you get the idea).

Note that if the drift files import the injectable files, the drift ones would get rebuilt still if the injectable files change.

**Comment by natebosch** [comment]
> So it would have its own asset graph, generated files dir, etc, based on the config name.

My gut reaction was to be worried about confusion that could come up with having all to-source outputs surface as inputs to the other build runs. We already have an order dependency when running builds with differing configs though, so I don't know how much new confusion it could cause.

Treating different configurations as entirely independent builds could end up allowing a simpler mental model and lead to less confusion overall.

It would be a breaking change - it's possible there is someone relying on the current behavior in their workflow, and _not_ deleting some files on disk could cause problems.

Overall I'm in favor with a major version bump.

**Comment by ikbendewilliam** [comment]
I haven't tried the build-filter yet, but it feels more like a band-aid imo, also since DI and json serialization are generators, eventually almost everything depends on each other in regards to builders. My preference is allowing for separate configs to run independent of each other. Or as you put it 
> Treating different configurations as entirely independent builds

Greatly appreciated if this is possible!

**Comment by ikbendewilliam** [comment]
Thanks, I'll try that out
