### ISSUE TITLE
Error: Method not found: 'FallThroughError'...

### ISSUE THREAD

**Issue by giapmn-1380** [dart-lang/build#3554]
### Versison:
- Flutter version 3.10.6
- Dart version 3.0.6

### Command:
`flutter pub run build_runner build --delete-conflicting-outputs`

### Error details:
Failed to build build_runner:build_runner:
../../../../../.pub-cache/hosted/pub.dev/pub_semver-2.1.1/lib/src/version_constraint.dart:96:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
make: *** [freezed] Error 1

![Screen Shot 2023-08-08 at 16 08 31](https://github.com/dart-lang/build/assets/30829812/1095d0df-f56a-4cb0-a551-c3c698ae501f)

`dart run build_runner doctor`
![Screen Shot 2023-08-08 at 16 09 12](https://github.com/dart-lang/build/assets/30829812/24a47144-608c-494f-bf88-189460ee361e)

`flutter doctor -v`
![Screen Shot 2023-08-08 at 16 11 13](https://github.com/dart-lang/build/assets/30829812/d03ab36e-df39-4204-a194-b294516d19c4)

**Comment by jakemac53** [comment]
The `FallThroughError` class was removed in Dart 3.0. You will need to upgrade your dependencies, the newer version of pub_semver does not use this error.
