### ISSUE TITLE
_TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>' in type cast)

### ISSUE THREAD

**Issue by karthik14344** [dart-lang/build#3558]
// Import necessary libraries
// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fpdart/fpdart.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:reddit_tutorial/core/constants/firebase_constants.dart';
import 'package:reddit_tutorial/core/failure.dart';
import 'package:reddit_tutorial/core/providers/firebase_provider.dart';
import 'package:reddit_tutorial/models/user_model.dart';

import '../../../core/constants/constraints.dart';
import '../../../core/type_def.dart';

final authRepositoryProvider = Provider(
  (ref) => AuthRepository(
    firestore: ref.read(firestoreProvider),
    auth: ref.read(authProvider),
    googleSignIn: ref.read(googleSignInProvider),
  ),
);

// A class that handles authentication related operations
class AuthRepository {
  // Instance of Firestore for database operations
  final FirebaseFirestore _firestore;

  final FirebaseAuth _auth; // Instance of FirebaseAuth for authentication
  final GoogleSignIn
      _googleSignIn; // Instance of GoogleSignIn for Google authentication

  // Constructor to initialize the AuthRepository with required instances
  AuthRepository({
    required FirebaseFirestore firestore,
    required FirebaseAuth auth,
    required GoogleSignIn googleSignIn,
  })  : _auth = auth,
        _firestore = firestore,
        _googleSignIn = googleSignIn;

  CollectionReference get _users =>
      _firestore.collection(FirebaseConstants.usersCollection);

  Stream<User?> get authStateChange => _auth.authStateChanges();

  // Method to sign in using Google authentication
  FutureEither<UserModel> signInWithGoogle() async {
    try {
      final GoogleSignInAccount? googleUser =
          await _googleSignIn.signIn(); // Start Google sign-in process

      // Create a GoogleAuthProvider credential using the obtained authentication data
      //It provides our app with an Access token and an id token to allow user to access the app features and to verify the user's identity..
      final credential = GoogleAuthProvider.credential(
        accessToken: (await googleUser?.authentication)?.accessToken,
        idToken: (await googleUser?.authentication)?.idToken,
      );
      UserCredential userCredential = await _auth.signInWithCredential(
          credential); //This will allow us to store the credentials in the firebase

      UserModel userModel;

      if (userCredential.additionalUserInfo!.isNewUser) {
        userModel = UserModel(
          name: userCredential.user!.displayName ?? "No Name",
          profilePic: userCredential.user!.photoURL ?? Constants.avatarDefault,
          banner: Constants.bannerDefault,
          uid: userCredential.user!.uid,
          isAuthenticated: true,
          karma: 0,
          awards: [],
        );
        await _users.doc(userCredential.user!.uid).set(userModel.toMap());
      } else {
        userModel = await getUserData(userCredential.user!.uid).first;
      }
      return right(userModel);
    } on FirebaseException catch (e) {
      throw e.message!;
    } catch (e) {
      return Left(Failure(e.toString()));
    }
  }

// stream is used for Real-time Data Synchronization

  Stream<UserModel> getUserData(String uid) {
    return _users.doc(uid).snapshots().map(
        (event) => UserModel.fromMap(event.data() as Map<String, dynamic>));
  }

//In the context of databases and data management, a snapshot is a representation of data at a specific point in time. It captures the state of the data at that moment and is often used for creating backups, restoring data to a previous state, or maintaining historical records.
}

Exception has occurred.
_TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>' in type cast)

**Comment by eernstg** [comment]
Submitted by accident?

@karthik14344, I'm not working on the 'build' packages, but this advice would be applicable in general: It's easier to respond to your issue if you can demonstrate the core of the issue in a small stand-alone program (in particular, with no imports unless the point is that some imported library behaves incorrectly), and the source code is backed up by useful explanatory text.

I'll close this issue because it isn't actionable. Please submit a new one if needed.
