### ISSUE TITLE
Upgrade watcher dependency to 1.1.0

### ISSUE THREAD

**Issue by Zigotote** [dart-lang/build#3560]
Hello,

When trying to upgrade my projet to Flutter 3.13, I had this warning : 
```
Failed to build build_runner:build_runner:
../../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
```

It seems that build_runner depends on watcher 1.0.2.
The latest version of watcher is 1.1.0 doesn't longer implements `FileSystemEvent`, which should solve this issue. Would it be possible to upgrade this dependency ? 

* Dart SDK Version: 3.1.0 (stable)
* What package(s) from this repo you are using, and the version: `build_runner 2.4.6`

**Comment by khaled-0** [comment]
Bump

**Comment by baconcheese113** [comment]
Fixed this by upgrading the `watcher` dependency in my pubspec.lock with `flutter pub upgrade`

Alternatively you can directly modify the pubspec.lock to contain this version

```
  watcher:
    dependency: transitive
    description:
      name: watcher
      sha256: "3d2ad6751b3c16cf07c7fca317a1413b3f26530319181b37e3b9039b84fc01d8"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"
```

It would still be helpful for build_runner to fix this

**Comment by harikrushn1412** [comment]
Please add this dependency watcher: ^1.1.0 in your pubspec.yaml file. it's working for me.

**Comment by Zigotote** [comment]
Upgrading with `flutter pub upgrade` did work, thanks.

**Comment by jakemac53** [comment]
There is no need to update the dependency on watcher in this package, it won't actually help anybody in practice (and it just causes unnecessary churn). The correct fix is to run `flutter pub upgrade`, which would be required regardless of what we do.
