### ISSUE TITLE
AssetNotFoundException on latest release

### ISSUE THREAD

**Issue by n0ks** [dart-lang/build#3565]
After updating my dependencies, I observed that the build_resolvers were upgraded to version 2.3.0, which subsequently led to the occurrence of the following error. However, when I go back to 2.2.0 it works as expected

![image](https://github.com/dart-lang/build/assets/22434056/e070fd86-0d60-4626-872b-594df4d9ef74)

```
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (5 months ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

**Comment by rkl550** [comment]
same issue as n0ks

**Comment by jjoelson** [comment]
For others encountering this, the temporary workaround is to add a dependency_override in your pubspec.yaml to override `build_resolvers` back to the prior version, as @n0ks mentioned:
```
dependency_overrides:
  # Workaround for https://github.com/dart-lang/build/issues/3565
  build_resolvers: 2.2.1
```

**Comment by jakemac53** [comment]
I can do a revert for now - does anybody have a stack trace? (run with `--verbose`)

That would help to diagnose exactly which call is failing

**Comment by jakemac53** [comment]
If somebody wants to try the fix you can add this to your pubspec:

```dart
dependency_overrides:
  build_resolvers:
    git: https://github.com/dart-lang/build.git
    ref: build_resolvers_fix
    path: build_resolvers
```

It might be good to get confirmation from at least one person that this does fix the issue

**Comment by jakemac53** [comment]
I am also generally curious exactly which situation people are in which is triggering this. You are expected to start seeing warnings when you hit this scenario (but not crash).

Do you have custom targets specified? If so you may want to look at https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps.

If you have cycles between packages, that could also cause this, but hopefully that isn't the case :).

We might end up needing to add an option to silence the warning or something, so let me know if its super spammy/annoying.

**Comment by jakemac53** [comment]
I am going to go ahead and release the fix even without confirmation, pretty confident it will resolve the issue.

**Comment by jakemac53** [comment]
Please chime in if you update to build_resolvers 2.3.1 and still have the issue though, and I will re-open this.

**Comment by jakemac53** [comment]
> mono repo where we have multiple packages using `build_runner` that also depend on each other.

In general this should be ok, unless there are dependency cycles. In particular cycles within regular dependencies (and not dev_dependencies).

If there are cycles then that is what is causing this issue, you won't be able to reliably get this optimization. We could be quieter about it though. Or, you could just disable the builder entirely on some of your packages that are in a cycle.

> We also exclude the generated files from the repo, which is perhaps something we should reconsider.

This could also be part of the issue - although presumably you do have to locally do builds of everything or else you couldn't develop? But the _order_ in which you do those builds might matter now, where it didn't before.

**Comment by jakemac53** [comment]
Fwiw, in general checking in files is recommended. But I would also have a check on CI that does a build and verifies that nothing changed (basically ensure your checked in generated files are actually up to date). There is a package for that, [build_verify](https://pub.dev/packages/build_verify).

**Comment by jjoelson** [comment]
Thanks for the info!

> But the order in which you do those builds might matter now, where it didn't before.

I considered this when we started encountering this `AssetNotFoundException` issue and re-ordered my build script to execute `build_runner build` in order according to the dependencies, but I was still encountering the same error. It's possible I got the order wrong though. 😅

**Comment by n0ks** [comment]
> Hey @jakemac53! I haven't had a chance to dig too deeply into what the change was here, but our situation is a mono repo where we have multiple packages using `build_runner` that also depend on each other.
> 
> We also exclude the generated files from the repo, which is perhaps something we should reconsider.

Yeah i'm on the same situation here.

After the update to 2.3.1 it generates without any problem with just the warnings

![image](https://github.com/dart-lang/build/assets/22434056/54c95422-3e6f-4fd8-a468-397cc4cd0550)

**Comment by AbiMulLyA** [comment]
Halo, please fix these warnings, its very annoying to see all these warnings every time i do build runner

<img width="515" alt="image" src="https://github.com/dart-lang/build/assets/42445812/438c6002-4aa0-4cae-b821-ab230a62d844">

**Comment by jakemac53** [comment]
> Halo, please fix these warnings, its very annoying to see all these warnings every time i do build runner

Some questions:

- Have you tried reading the linked docs to solve the issue?
  - If so, did you find it too hard or not possible to resolve?
- Or would you prefer just a quick option to remove the warnings and are not too concerned about the loss of any optimizations?
