### ISSUE TITLE
"astNodeFor" is 5x slower on secondary runs of `build_runner watch`

### ISSUE THREAD

**Issue by Adam-Langley** [dart-lang/build#3575]
* Dart SDK Version (`dart --version`)
**Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_x64"**
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * _If you are not sure, try checking your `pubspec.lock` file._
**build: ^2.4.1**

I am using the database abstraction library `drift`.
Drift has a generator which will find classes which extend the drift 'Table' class, and iterate over the properties within, to generate DAO classes.

I have found that using 'build_runner watch' the first run is fast, but subsequent runs are painfully slow (to the order of 5x).

I tracked it down to a call to `_DelayedResolver.astNodeFor` - which, when stopwatched, takes 100ms on the first launch of 'build_runner watch' - but subsequent runs (after touching an input file to trigger a re-gen) take 500ms+.

I've also filed a bug in the drift project, which may get closed if it's found that build is indeed the cause
https://github.com/simolus3/drift/issues/2608

**Comment by jakemac53** [comment]
Dart is a highly async language, and this package in particular schedules an abundance of async tasks. So stopwatching that call is unfortunately not going to provide any meaningful result.

What is almost certainly happening here is the order in which things happen is different, and there is more async work happening at the time the builder runs.

You can run with `--track-performance` in `serve` mode, and load the `/$perf` page to get a more realistic breakdown (it can track only the actual work spent doing what _you asked for_. But the page can also be quite overwhelming.

**Comment by jakemac53** [comment]
There is fwiw a known issue that analysis in general struggles on rebuilds - it can hog the CPU a lot, which could be what you are seeing.
