### ISSUE TITLE
[build_runner] throws InvalidType is not a class element for a non-generated class

### ISSUE THREAD

**Issue by agustka** [dart-lang/build#3588]
Somewhat out of the blue and for unexplained reasons, I am suddenly getting the following error when generating code:

```
[SEVERE] injectable_generator:injectable_builder on lib/infrastructure/core/service/base_service_module.dart:

InvalidType is not a class element
package:injectable_generator/utils.dart 38:5                             throwIf
package:injectable_generator/resolvers/dependency_resolver.dart 66:5     DependencyResolver.resolveModuleMember
package:injectable_generator/generators/injectable_generator.dart 51:15  InjectableGenerator.generate
package:source_gen/src/builder.dart 355:23                               _generate
```

The module in question is not providing any generated class like some others have had a problem with, it's just supposed to provide IOClient from the http package. I'm completely at a loss how this can happen. Here's a small section of the module file (the rest is just about the IOClient to be returned):

```
import 'package:http/io_client.dart';

@module
abstract class BaseServiceModule {
  IOClient get ioClient {
    ...
  }
}
```

I've investigated other problems like this before but they all suggest changing the order of builders so that the input to one builder is generated before some other builder is run - all of which I can't really understand to be applicable here as this module is providing a non-built class IOClient.

-----------------------------------------------------

* Dart SDK Version: **3.1.2 (stable)** 
* build_runner version **2.4.6**
* What builder(s) you are using: **injectable_generator:injectable_builder**
* OS: **MacOS**
* Any other packages or constraints we should know about: I've disabled all other builders, but it does not matter the error persists no matter what other builders are included.

**Comment by jakemac53** [comment]
You could also try version `2.2.1` if that doesn't work.
