### ISSUE TITLE
[build_runner] Cyclic transitive dependencies

### ISSUE THREAD

**Issue by Pante** [dart-lang/build#3592]
* Dart SDK Version 3.1.2
* `build_runner: "2.4.6"`

How do we handle cyclic transitive dependencies? The [example](https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps) in the FAQ mentions splitting the targets and having one depend on another but I don't think it works with cyclic dependencies (at least I have no idea how to set that up)?

In `auto_route`, we generate a `router.gr.dart` file that contains all routes in a project. Said generated routes are used by widgets through a project. However, to generate  `router.gr.dart` the generator needs to first scan through all widgets in the project, some of which have a transitive dependency on the non-existent `router.gr.dart`.

**Comment by jakemac53** [comment]
I am a bit confused about the setup here, is this `router.gr.dart` file generated in the root package, and then depended on by files in the root packages dependencies? Or is it only imported by files in the current package?

Also, do you have multiple targets in your `build.yaml` currently?

**Comment by Pante** [comment]
> I am a bit confused about the setup here, is this `router.gr.dart` file generated in the root package, and then depended on by files in the root packages dependencies? Or is it only imported by files in the root package?
> 
> Also, do you have multiple targets in your `build.yaml` currently?

The generated `router.gr.dart` is imported by other files in the root package. 

The `build.yaml` currently looks like this:
```yaml
targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/router.dart
          - lib/views/**_page.dart
```

**Comment by Pante** [comment]
My apologies, it seems like it was a bug in `auto_route` causing the issue rather than what I mentioned above.
