### ISSUE TITLE
build-Runner fails on old watcher pacakge

### ISSUE THREAD

**Issue by AFASbart** [dart-lang/build#3604]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
3.1.0 (stable)
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
build_runner 1.4.6
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
Not required, but it is using the flutter_gherkin builder.
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

When using the builder_runner package I get an error that the package watcher implements a sealed class (abstract class _ConstructableFileSystemEvent implements FileSystemEvent).
This is fixed in watcher 1.1.0.

**Comment by jakemac53** [comment]
Yes this is a known issue, the solution is just to run `dart pub upgrade` to upgrade your watcher dependency.
