### ISSUE TITLE
Why `build_config` only support `.yaml` extension not both `.yaml` and `.yml`?

### ISSUE THREAD

**Issue by schaipipat** [dart-lang/build#3615]
Not sure if this is the right place to ask or not, but my background from using many of YAML file, it suppose to recognize that both `.yaml` and `.yml` is the extension for the same file type.

**Comment by schaipipat** [comment]
May be a good thing to have for people who just come from another languages/tools like me. I'm happy to contribute if you're busy. Thanks a lot. 🙇‍♂️

**Comment by jakemac53** [comment]
I do know of one other person who also made this mistake so you definitely aren't alone :)

**Comment by jakemac53** [comment]
I do feel quite comfortable adding a check in for that file and emitting a warning. We can still keep a consistent convention that way and it doesn't promise any kind of long term support or maintenance burden, it would be a nice isolated piece of code.
