### ISSUE TITLE
[build_runner] + [dart_frog] unable to run builder on `routes` input

### ISSUE THREAD

**Issue by PiotrFLEURY** [dart-lang/build#3617]
# Context

I'm trying to create annotation builders for my [nenuphar_cli](https://pub.dev/packages/nenuphar_cli) package. 

The main goal is to generate `openapi` documentation using annotations on [dart_frog](https://pub.dev/packages/dart_frog) routes

Dart Frog routes are into the `routes/` folder and not into the `lib/` one.

# Issue

build_runner command seems to ignore the `routes` folder.

[The build runner documentation](https://pub.dev/documentation/build_runner/latest/#inputs) confirm it

```
You can read any files under the top level lib folder any package dependency
```

I also found a mehod explicitely skipping every source outside of the `lib/` folder here => [https://github.com/dart-lang/build/blob/7f5b10393de5e129f1bc08f2ffbd76ae388c97f4/build_runner_core/lib/src/generate/finalized_assets_view.dart#L58](https://github.com/dart-lang/build/blob/7f5b10393de5e129f1bc08f2ffbd76ae388c97f4/build_runner_core/lib/src/generate/finalized_assets_view.dart#L58)

This is preventing me to parse sources under the `routes/` folder containing my annotation.

Can we add an option to take into account a custom source folder ?

# Steps to reproduce

Checkout [nenuphar_cli:/feat/annotations](https://github.com/PiotrFLEURY/nenuphar_cli/tree/feat/annotations) branch

Open a terminal in the `example` folder and run `dart run build_runner build`

The `allowMethodBuilder` configured in [build.yaml](https://github.com/PiotrFLEURY/nenuphar_cli/blob/feat/annotations/nenuphar_generator/build.yaml) is not executed.

# Expected behavior

The `allowMethodBuilder` should be executed with classes annotated with `@Allow` in the `routes/` folder. See [index.dart](https://github.com/PiotrFLEURY/nenuphar_cli/blob/feat/annotations/example/routes/todos/index.dart) for example

# Versions

* Dart SDK version: 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "linux_x64"
* Dart Frog 1.1.1
* build_runner: ^2.4.6
* build: ^2.4.1
* code_builder: ^4.7.0
* dart_style: ^2.3.3
* source_gen: ^1.4.0
* Custom builder used for custom `@Allow` annotation. See [allow_generator.dart](https://github.com/PiotrFLEURY/nenuphar_cli/blob/feat/annotations/nenuphar_generator/lib/src/allow_generator.dart) 
* Linux Ubuntu 22.04
* Custom CLI package [nenuphar_cli](https://pub.dev/packages/nenuphar_cli)

**Comment by jakemac53** [comment]
If you only need to read these files in the _current_ package, then you can just add them, see https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build

**Comment by PiotrFLEURY** [comment]
Thank you for the link @jakemac53 

I'll try it.

So I guess this issue is more related to documentation improvement.
It is easy to be lost in `build_runner` `build_config` `build` `code_builder` etc...

The [https://pub.dev/packages/build_runner](https://pub.dev/packages/build_runner) documentation only reference the `getting started` and I didn't saw it first.

Can we add also the FAQ documentation link to the `build_runner` README on pub.dev ?

**Comment by jakemac53** [comment]
> Can we add also the FAQ documentation link to the `build_runner` README on pub.dev ?

Yeah we should probably link a few more of the docs there.

**Comment by PiotrFLEURY** [comment]
Thank you @jakemac53
