### ISSUE TITLE
Mockito Build runner not generating  *.mocks.dart file

### ISSUE THREAD

**Issue by MichaelOdumosu57** [dart-lang/build#3619]
* Dart SDK Version (`dart --version`)
    Tools • Dart 3.2.1 • DevTools 2.28.3
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  build_runner: ^2.4.6

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  I am using GenerateNiceMocks from the flutter mockito library in this manner
```dart
import 'package:flutter/material.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

@GenerateNiceMocks([MockSpec<Article>()])
import 'article.mocks.dart';


class Article {
  String returnString() {
    return "String";
  }
}
```
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  Windows powershell to run unit test cases

* Any other packages or constraints we should know about

# Mockito Build runner not generating  *.mocks.dart file

## Links to issue
*[Github](https://github.com/dart-lang/build/issues/3619)
* [Video](https://www.youtube.com/watch?v=g46ZLLn6uB4)

## Expected Behavior
generate the .mocks file

## Current Behavior
does not generate

## Steps to Reproduce

1. make new flutter app
2. create file lib/article.dart w/ the following code
```dart
import 'package:flutter/material.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

@GenerateNiceMocks([MockSpec<Article>()])
import 'article.mocks.dart';


class Article {
  String returnString() {
    return "String";
  }
}

```
3. try in the command line
```dart
dart run build_runner build
```
4.
try in the command line
```dart
flutter clean;flutter pub get;dart run build_runner clean;dart run build_runner build
```

**Comment by jakemac53** [comment]
This is because mockito only runs on files under the `test` directory by default, https://github.com/dart-lang/mockito/blob/fb8a2b5731553f5ed22107e1a0f7af8918d28442/build.yaml#L29.

You can override that with something like this:

```yaml
targets:
  $default:
    builders:
      mockito|mockBuilder:
        generate_for:
          - lib/**.dart
          - test/**.dart
```

I would file something on mockito to add documentation about this though.
