### ISSUE TITLE
Add wasm support to build_web_compilers

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#3621]
Wasm now works in stable chrome, so we should add some more official support for users trying to use it.

**Comment by simolus3** [comment]
I've started working on this by fixing the `--multi-root` option when passed to `dart compile wasm` in https://dart-review.googlesource.com/c/sdk/+/377662. With that being fixed, supporting `dart2wasm` in `build_web_compilers` pretty much boils down to copying the `dart2js` logic and emitting a suitable entrypoint. If no one else is currently working on this I'm happy to do that as well.

**Comment by jakemac53** [comment]
@simolus3 sure if you would like to take this on that would be much appreciated
