### ISSUE TITLE
build_modules not compatible with Dart SDK >=3.4

### ISSUE THREAD

**Issue by srujzs** [dart-lang/build#3637]
Here's a sample CI run: https://github.com/srujzs/web/actions/runs/7451155930/job/20271633779

Dart SDK version: `3.4.0-edge.3c42222b7e59dff9e47a2a848f7a547f4123826d`
Package: `build_web_compilers: ^4.0.7`
Platform: Linux

`build_web_compilers` published `4.0.8` to add support for Dart `3.4`. But `build_modules`, which `build_web_compilers` depends on, does not have a new version compatible with `3.4`, so this fails to resolve.

This is likely on your radar, but figured I might as well file an issue. :)

**Comment by jakemac53** [comment]
Thanks, it wasn't yet on my radar but is now :)

**Comment by jakemac53** [comment]
@annagrin this should be working now, let me know if you see additional issues please
