### ISSUE TITLE
Issue including files from different directories in a Dart code generator with "build" (aggregate builder)

### ISSUE THREAD

**Issue by erick-ciudaz** [dart-lang/build#3639]
First of all, I would like to emphasize that I am just learning about Aggregate Builder.I am working on a Dart code generator using **build_runner**, and I've encountered an issue when trying to include files from different directories in the code generation process. My goal is to examine all .dart files in the project, but it seems that **buildStep.findAssets(Glob("**/\*.dart"))\*\* only includes files within the conventional lib or test directories from flutter.

I have a code generator project, and a dartfrog backend that implements it

## Code generator project

- dependencies:
  - `Dart SDK version: 3.0.3 (stable) (Wed May 31 15:35:05 2023 +0000) on "linux_x64"`
  - `build : 2.4.1`
  - `glob : 2.1.2`
  - `source_gen : 1.5.0`
  - `build_runner : 2.4.7`

- custom_builder.dart

```dart
// custom_builder.dart

import 'dart:async';
import 'package:build/build.dart';
import 'package:glob/glob.dart';

class CustomBuilder extends Builder {
  static final _scope = Glob('**/*.dart');

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    await _findFilesAndBuild(buildStep);
    log.info("1.- ASSETS FOUND");
    await writeInFile(buildStep);
    log.info("2.- FILE WRITE SUCCESSFULL");
  }

  @override
  Map<String, List<String>> get buildExtensions => {
        r'$package$': [".custom.gen.temp"]
      };

  _findFilesAndBuild(BuildStep buildStep) async {
    await for (var fileAsset in buildStep.findAssets(_scope)) {
      log.info("CUSTOM BUILDER: file path ${fileAsset.path}");
      await _buildForFile(fileAsset, buildStep);
    }
  }

  _buildForFile(AssetId fileAsset, BuildStep buildStep) async {
    // logic for fileAsset
  }

  writeInFile(BuildStep buildStep) {}
}
```

- build.yaml:

```yaml
## build.yaml

builders:
  custom_generator:
    import: "package:custom_generator/custom_generator.dart"
    builder_factories: ["customBuilder"]
    build_extensions: { r'$package$': [ ".custom.gen.temp" ] }
    auto_apply: dependents
    build_to: source
```

## Dart_frog backend

- dependencies:
  - `Dart SDK version: 3.0.3 (stable) (Wed May 31 15:35:05 2023 +0000) on "linux_x64"`
  - `dart_frog : ^1.0.0`
  - `build_runner : 2.4.7`

I have the following directory tree:

```
|- config/
|    - config_class.dart
|- lib/
|    - lib_class1.dart
|- routes/
|    - index.dart
|    - route_class.dart
|- test/
|    - routes/
|    - test_class1.dart
|
```

after running the command `dart run build_runner build --delete-conflicting-outputs -v` on my dart frog project I get the following impressions:

```bash
[INFO] Build:Running build...
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path lib/lib_class1.dart
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path test/routes/index_test.dart
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path test/test_class1.dart
[INFO] custom_generator on $package$:1.- ASSETS FOUND
[INFO] custom_generator on $package$:2.- FILE WRITE SUCCESSFULL testo
[INFO] Build:Running build completed, took 22ms

```

You can see that only printouts of files that belong to the lib or test directories appear, apparently buildStep.findAssets(\_scope) does not include the other directories.

- what am I doing wrong?
- What configuration should I make to achieve my goal?

I attach the repository of the projects in question https://github.com/erick-ciudaz/code_generation_project

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build

**Comment by erick-ciudaz** [comment]
> Consulte https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build


Thanks for the response, I just added my /config and /routes directories as an additional source
```yaml
targets:
  $default:
    sources:
      - config/**
      - routes/**
      - lib/**
      - $package$
      - pubspec.*

builders:
  custom_generator:
    import: "package:custom_generator/custom_generator.dart"
    builder_factories: ["customBuilder"]
    build_extensions: { r'$package$': [ ".custom.gen.temp" ] }
    auto_apply: dependents
    build_to: source

```
clear cache: 
```bash
art run build_runner clean
```
then I run the build command :
```bash
dart run build_runner build --delete-conflicting-outputs -v
```
However, everything remains the same, the files from the included directories do not appear.

```bash
[INFO] Build:Running build...
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path lib/lib_class1.dart
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path test/routes/index_test.dart
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path test/test_class1.dart
[INFO] custom_generator on $package$:1.- ASSETS FOUND
[INFO] custom_generator on $package$:2.- FILE WRITE SUCCESSFULLy
[INFO] Build:Running build completed, took 25ms

```

On the other hand, when I execute: dart run build_runner doctor in the code generator project and I get this Warning:
```bash
[WARNING] Builder custom_generator:custom_generator uses input extension $package$ which is not specified in the `build.yaml`.
```

I'm not sure if this message has to do with my main problem.

I tried to make some configurations about it, but I was unsuccessful.

**Comment by jakemac53** [comment]
Note that the sources have to be defined in a `build.yaml` in the package that you are trying to run your builder on - it wasn't clear to me if that is what you are doing or not?

In other words, are you running build_runner in the `custom_generator` package, or a package which depends on `custom_generator`? The `build.yaml` that you need to update is the one in which you are using the `custom_generator`, not `custom_generator` itself, if that makes sense.

My guess, is that you are in a different package, which has a build.yaml with custom sources, but doesn't include the `$package$` source.

**Comment by erick-ciudaz** [comment]
> Tenga en cuenta que las fuentes deben definirse en `build.yaml`el paquete en el que está intentando ejecutar su generador; no me quedó claro si eso es lo que está haciendo o no.
> 
> En otras palabras, ¿está ejecutando build_runner en el `custom_generator`paquete o en un paquete que depende de `custom_generator`? El `build.yaml`que necesitas actualizar es aquel en el que estás usando `custom_generator`, no `custom_generator`el mismo, si eso tiene sentido.
> 
> Supongo que estás en un paquete diferente, que tiene un build.yaml con fuentes personalizadas, pero no incluye la `$package$`fuente.

Thanks, you are right, I just made the configuration in the "my_backend" project that depends on "custom_generator":

```yaml
targets:
  $default:
    sources:
      - config/**
      - routes/**
      - lib/**
      - $package$
      - pubspec.*
```

The impressions are what I was waiting for:
```bash
[INFO] Build:Running build...
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path config/config_class.dart
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path routes/index.dart
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path routes/route_class.dart
[INFO] custom_generator on $package$:CUSTOM BUILDER: file path lib/lib_class1.dart
[INFO] custom_generator on $package$:1.- ASSETS FOUND
[INFO] custom_generator on $package$:2.- FILE WRITE SUCCESSFULL
[INFO] Build:Running build completed, took 26ms
```
With this experience I understand that:
- when I use `$package$`  as synthetic input,
  the code `buildStep.findAssets(Glob('**/*.dart'))`  will search by default in conventional folders such as /test and /lib, and to search in other root directories I must include them in the build.yaml of the project that depends on my "custom generator".

- when I use `$lib$` as synthetic input the code `buildStep.findAssets(Glob('lib/**'))`  will find assets only in the lib folder and it will not be necessary to add - lib/** in the build.yaml

I would like to know how correct my assessment is. thanks for your attention.

**Comment by erick-ciudaz** [comment]
sorry, I reopened the problem by accident

**Comment by erick-ciudaz** [comment]
> > Tenga en cuenta que las fuentes deben definirse en `build.yaml`el paquete en el que está intentando ejecutar su generador; no me quedó claro si eso es lo que está haciendo o no.
> > En otras palabras, ¿está ejecutando build_runner en el `custom_generator`paquete o en un paquete que depende de `custom_generator`? El `build.yaml`que necesitas actualizar es aquel en el que estás usando `custom_generator`, no `custom_generator`el mismo, si eso tiene sentido.
> > Supongo que estás en un paquete diferente, que tiene un build.yaml con fuentes personalizadas, pero no incluye la `$package$`fuente.
> 
> Gracias, tienes razón, acabo de realizar la configuración en el proyecto "my_backend" que depende de "custom_generator":
> 
> ```yaml
> targets:
>   $default:
>     sources:
>       - config/**
>       - routes/**
>       - lib/**
>       - $package$
>       - pubspec.*
> ```
> 
> Las impresiones son las que estaba esperando:
> 
> ```shell
> [INFO] Build:Running build...
> [INFO] custom_generator on $package$:CUSTOM BUILDER: file path config/config_class.dart
> [INFO] custom_generator on $package$:CUSTOM BUILDER: file path routes/index.dart
> [INFO] custom_generator on $package$:CUSTOM BUILDER: file path routes/route_class.dart
> [INFO] custom_generator on $package$:CUSTOM BUILDER: file path lib/lib_class1.dart
> [INFO] custom_generator on $package$:1.- ASSETS FOUND
> [INFO] custom_generator on $package$:2.- FILE WRITE SUCCESSFULL
> [INFO] Build:Running build completed, took 26ms
> ```
> 
> Con esta experiencia entiendo que:
> 
> * cuando lo uso `$package$`  como entrada sintética, 
>   el código `buildStep.findAssets(Glob('**/*.dart'))`  buscará por defecto en carpetas convencionales como /test y /lib, y para buscar en otros directorios raíz debo incluirlos en el build.yaml del proyecto que depende de mi "generador personalizado". ".
> * cuando lo uso `$lib$`como entrada sintética, el código `buildStep.findAssets(Glob('lib/**'))`  encontrará activos solo en la carpeta lib y no será necesario agregar - lib/** en build.yaml
> 
> Me gustaría saber qué tan correcta es mi valoración. gracias por tu atención.

sorry, I reopened this by accident

**Comment by jakemac53** [comment]
Your understanding is generally correct, with one note:

> * when I use `$lib$` as synthetic input the code `buildStep.findAssets(Glob('lib/**'))`  will find assets only in the lib folder and it will not be necessary to add - lib/** in the build.yaml

There isn't anything special about `$lib$` here, this only works because `lib` is one of the default directories. You can always glob for it, regardless of your build extensions, unless the package you are running on has explicit sources which exclude it.
