### ISSUE TITLE
add integration_test/** to default included source files

### ISSUE THREAD

**Issue by StephenWithPH** [dart-lang/build#3643]
`build_runner`'s documentation (as of 2.4.8) states: https://github.com/dart-lang/build/blob/8e1cbf8f7b573dfe73790fbb8cf53062b3e5d452/docs/faq.md#L169-L173

The linked docs show an `integration_test/` within the example `enchilada` package's directory structure. ([source](https://github.com/dart-lang/site-www/blob/5ac42d804c6f2dbce40fb1b3bcb906d4ddbab0bf/src/tools/pub/package-layout.md))

Further down the page, it states:

> Flutter app packages may also have special integration tests, which use the integration_test package. These tests live in their own integration_test directory.
>
> Other packages may choose to follow a similar pattern, to separate their slower integration tests from their unit tests, but note that by default dart test will not run these tests. You will have to explicitly run them with dart test integration_test.

Given the above, it seems reasonable to include `integration_test/**` as part of `build_runner`'s default sources for root packages:

https://github.com/dart-lang/build/blob/8e1cbf8f7b573dfe73790fbb8cf53062b3e5d452/build_runner_core/lib/src/generate/options.dart#L33-L53

Doing so would allow authors of builders which do _something_ with sources from `integration_test/` to see things "just work" rather than having to figure out how to include that path along with all of the current default includes.

**Comment by jakemac53** [comment]
That makes sense, I remember when we added `integration_test/` as a specifically supported dir I had meant to add it here as well, but forgot. Thanks for the reminder!

**Comment by StephenWithPH** [comment]
@jakemac53 ... thank you for the quick response on this!
