### ISSUE TITLE
 dart run build_runner build cn't running properly

### ISSUE THREAD

**Issue by anandsathya80** [dart-lang/build#3672]
when running `dart run build_runner build --delete-conflicting-outputs` get message  :

[INFO] Generating build script completed, took 258ms
[WARNING] Throwing away cached asset graph due to version mismatch or corrupted asset graph.

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

PathNotFoundException: Deletion failed, path = '.dart_tool/build/generated' (OS Error: The system cannot find the path specified.
, errno = 3)
dart:async                                                           _CustomZone.runUnary
package:build_runner_core/src/generate/build_definition.dart 333:7   _Loader._deleteGeneratedDir
dart:async                                                           Future.wait.<fn>
package:build_runner_core/src/generate/build_definition.dart 411:9   _Loader._tryReadCachedAssetGraph.<fn>
package:build_runner_core/src/logging/logging.dart 25:18             logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 213:22  _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 114:27        BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:26       BuildRunner.create
package:build_runner/src/generate/build.dart 109:17                  build
package:build_runner/src/entrypoint/build.dart 35:18                 BuildCommand._run
package:args/command_runner.dart 212:13                              CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                   run
.dart_tool\build\entrypoint\build.dart 82:16                         main

**Comment by jakemac53** [comment]
Interesting, was this a one-off error or is it continuing to happen?
