### ISSUE TITLE
docs/examples: build_to missing from cssBuilder

### ISSUE THREAD

**Issue by ewann** [dart-lang/build#3674]
Off the back of https://www.youtube.com/watch?v=ngUiuIdcGjk I was reviewing the examples. After longer than I would have liked, I noticed this omission.

Happy to raise a pr, but didn't easily find contrib rules so decided to file here in the first instance - hopefully if nothing else happens it will at least be on a next persons search results.

```
diff --git a/example/build.yaml b/example/build.yaml
index 6d18b367..0b9831fe 100644
--- a/example/build.yaml
+++ b/example/build.yaml
@@ -24,6 +24,7 @@ builders:
     import: "package:example/builder.dart"
     builder_factories: ["cssBuilder"]
     build_extensions: {"$package$": ["web/generated.css"]}
+    build_to: source
     auto_apply: root_package
 
   textBuilder:
```

**Comment by ewann** [comment]
perhaps my real question is: what is this example supposed to demonstrate?

All of the other builder examples in https://github.com/dart-lang/build/blob/master/example/build.yaml `build_to: source` but https://github.com/dart-lang/build/blob/master/example/build.yaml#L23 does not.

So I think I'd be agreeing by stating that having `// build_to: source` would be helpful to a new reader, since it hopefully calls out louder: A setting is available here, but is deliberately not configured. That would possibly have brought the difference to my attention faster, thus improving the learning / onboarding process.

**Comment by jakemac53** [comment]
I agree I think the fix here is just to call out the choice with a comment.
