### ISSUE TITLE
Invalidate outputs based on better than timestamp

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#371]
Today a changed file can cascade to any output which may end up rebuilding way more than is optimal. If we track some type of content hash we can get away with pruning the build graph more eagerly.

**Comment by jakemac53** [comment]
This will also help for correctness, so I am going to go ahead and tackle it.

See https://github.com/dart-lang/build/issues/536 for an example.

**Comment by jakemac53** [comment]
Actually I am only going to tackle invalidating _inputs_, not also invaliding outputs based on whether files actually changed (at least right now).
