### ISSUE TITLE
Too much memory and crashing with out of memory exception

### ISSUE THREAD

**Issue by tsherdiwala** [dart-lang/build#3710]
## configurations

* Dart SDK Version (`dart --version`) : 
`Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "macos_arm64"`

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
`build_runner 2.4.9`

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
The build of concern is `dart_mappable_builder` with version `4.2.3`

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOS

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)  - Not applicable

## issue details:
when running the `build` command the builder consumes large amount of memory. The `build` function basically does the operations using the `analyser` package to infer the code for the code generation and created `*.mapper.dart` files.  

Is seems that there are the `Element` classes which are not be garbage collected.

<img width="1417" alt="Screenshot 2024-05-26 at 16 43 41" src="https://github.com/dart-lang/build/assets/11754414/79864651-7c7b-406b-81c5-0867efff07dd">

**Comment by Colton127** [comment]
I intended to post the same issue. I've had issues with a memory leak where build_runner watch consumes 20GB+ RAM:
![Screenshot 2024-06-11 at 11 24 16 PM](https://github.com/dart-lang/build/assets/20976940/6e8aa9b6-a9a7-4c65-9408-8aa480d73dfb)

A fresh instance of build_runner consumes roughly 3.5GB on my machine, making it the current most memory-intensive application open. Output logs indicate everything is working as intended; no errors.

**Comment by jakemac53** [comment]
Please file this on the `dart_mappable_builder` package, I did a bit of digging and it caches resolvers in a global variable:

cache [here](https://github.com/schultek/dart_mappable/blob/4777e79cdc99e15730d18990e1d774edc0064b0a/packages/dart_mappable_builder/lib/src/utils.dart#L22), assigned [here](https://github.com/schultek/dart_mappable/blob/4777e79cdc99e15730d18990e1d774edc0064b0a/packages/dart_mappable_builder/lib/src/builders/mappable_builder.dart#L33) 

This is almost certainly the culprit.
