### ISSUE TITLE
not generating files on windows

### ISSUE THREAD

**Issue by SaurabhS120** [dart-lang/build#3712]
On a Windows machine, I am trying to run the build_runner command to generate files for the mockito mock class and retrofit RestApi class.
I have tried to solve this issue using the following solutions but none of them are working :
- removing '.dart_tool' folder
- running command `flutter pub cache repair`
- running command `flutter pub cache clean`

I have recently upgraded flutter SDK with `flutter upgrade` command.

Extra info:
Trying to run build_runner inside a local data layer package present in the root directory (projectDir/data)

* Dart SDK Version 3.4.1 
flutter 2.4.10
build_runner version 2.4.10

**Comment by jakemac53** [comment]
There isn't really enough information to go off of here, we would need a full reproduction case (we run tests on windows etc and they are not failing, so things are generally working).

The only hypothesis I have is that you moved your mock files out of the `test` dir to thie `data` dir? Mockito by default only runs on files in the test dir, afaik. You can customize that using `generate_for` in the build.yaml.

**Comment by SaurabhS120** [comment]
The test file is present in the test directory. 
![Screenshot 2024-06-03 204434](https://github.com/dart-lang/build/assets/70626113/36877251-5045-4af3-82bd-17a4cf1ec148)
I am also attaching my pubspec.yaml and pubspec.lock.
[pubspec.lock.txt](https://github.com/user-attachments/files/15536170/pubspec.lock.txt)
[pubspec.yaml.txt](https://github.com/user-attachments/files/15536172/pubspec.yaml.txt)

**Comment by jakemac53** [comment]
I believe the annotation needs to be on an _import_, not the `main` function (this import is the file that will be generated), something like this:

```dart
@GenerateNiceMocks([MockSpec<ProductsRepoImpl>()])
import 'product_repo_impl_test.mocks.dart';
```

**Comment by jakemac53** [comment]
This is all mockito specific though, I would address further questions at that repo, or by reading their documentation. I don't own that package or use it, I have just provided this recommendation based on reading their docs.

**Comment by SaurabhS120** [comment]
![Screenshot 2024-06-03 215713](https://github.com/dart-lang/build/assets/70626113/e0b734a6-9cd4-4d1f-a8b3-0f01f0306bef)
![Screenshot 2024-06-03 215730](https://github.com/dart-lang/build/assets/70626113/2d953781-78d8-41f1-a273-f0ec94e1170f)
This solution is also not working for me,
I was also facing issue with retrofit, It took 3 hours to generate RestApi file, That is why I thought this issue must be with the common build_runner package.

**Comment by SaurabhS120** [comment]
For mockito, it was not present in the dev_dependencies of pubspec.yaml file.
In this case, there should be a warning or error message which can guide developers.

**Comment by SaurabhS120** [comment]
For my PC if mokito is removed from pubspec.yaml import will take from pub-cache. 

<img src='https://github.com/dart-lang/build/assets/70626113/a7a5cdd0-f7c1-4128-a806-50c36d146771' width=600/>

So, imports will work for instance but build_runner will not generate '.g.dart' files for package (Mockito for me).
