### ISSUE TITLE
dart run build_runner build   error

### ISSUE THREAD

**Issue by Ganeshkumarbojja** [dart-lang/build#3718]
[WARNING] json_serializable on lib/swagger_generated_code/kapil_crm_swagger.swagger.dart:
Could not read the "pubspec.yaml` file associated with this package. Usage of package:json_annotation could not be verified.

getting this warning while generating dart files from swagger json using dart run build_runner build command.
Kindly help me regarding this.

**Comment by jakemac53** [comment]
Please re-file this issue on the json_serializable package https://github.com/google/json_serializable.dart
