### ISSUE TITLE
build-runner was released targeting a dev version of the SDK

### ISSUE THREAD

**Issue by zillemarco** [dart-lang/build#3731]
* Dart SDK Version: `3.4.3 (stable)`
* What package(s) from this repo you are using, and the version: `build_runner 2.4.12`
* What builder(s) you are using: Flutter?
* On Windows
* No browser
* Any other packages or constraints we should know about: none really

I have a Flutter project using Dart 3.4.3 with Flutter SDK 3.22.2 and `build_runner` is one of the dependencies, set to have `^2.4.7` as the version.

Running `flutter pub upgrade` it tries to update the `build_runner` package to `2.4.12` but it fails because that version of the package was released targeting a yet unreleased version of the Dart SDK.

Not a big deal because I can just avoid upgrading to `2.4.12`, but I wanted to let you know.

**Comment by jakemac53** [comment]
Yes, this is intentional. It is fine to just stay on the older version until 3.5 stable is released.
