### ISSUE TITLE
Implement `checkOutputs` as a Matcher

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#376]
We don't currently have unit tests of `checkOutputs` but it is public. Adding tests against code which has it's own `expect` isn't straightforward - it would be a lot easier to test this independently if it was implemented as a Matcher.

The downside is that implementing the Matcher api isn't as easy as the code we have now.

**Comment by natebosch** [comment]
The tests actually aren't terrible: https://github.com/dart-lang/build/pull/377

I think this still makes the most sense as a Matcher though so I'll keep this open for consideration.

**Comment by matanlurey** [comment]
Now that you have a `BuildResult` this should be much easier, yeah?

**Comment by natebosch** [comment]
This isn't really feasible without degrading the UX. I don't think it's worth doing.
https://github.com/dart-lang/test/blob/c0470b542b4081f220d8d2f5f29544f1c74c479e/pkgs/test_api/lib/src/frontend/expect.dart#L159
