### ISSUE TITLE
Output directory option

### ISSUE THREAD

**Issue by dhikshithrm** [dart-lang/build#3769]
## Description

currently, the generated file is saved in the same directory as the source file.

A command-line argument for setting the output directory would be great, such as `dart run build_runner build—-out=./dist` or something similar.

## Additional Info
Dart SDK version: 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "macos_arm64"
- `build` - v2.4.1
- `build_runner` - v2.4.9
- `build_runner_core` - v7.3.0

**Comment by jakemac53** [comment]
Two things:

- Builder authors can configure whether or not their files are generated into your source tree, via the `build_to` configuration option. They can choose `source` or `cache`. It sounds like you are using some builders which output to `source`, but wish they were `cache`. However, it is likely this isn't a feasible option for them. See https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md#when-should-a-builder-build-to-cache-vs-source for more info.
- There is already an output directory option (`-o`), but this creates a "merged view" - basically its a full copy of your project for deployment, with all generated artifacts (although possibly some "deleted" ones, if builders choose to do some cleanup). It will not affect the "build to source" builders - they will still output files in your source tree.

**Comment by ZhiyongPan** [comment]
> Two things:
> 
> * Builder authors can configure whether or not their files are generated into your source tree, via the `build_to` configuration option. They can choose `source` or `cache`. It sounds like you are using some builders which output to `source`, but wish they were `cache`. However, it is likely this isn't a feasible option for them. See https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md#when-should-a-builder-build-to-cache-vs-source for more info.
> * There is already an output directory option (`-o`), but this creates a "merged view" - basically its a full copy of your project for deployment, with all generated artifacts (although possibly some "deleted" ones, if builders choose to do some cleanup). It will not affect the "build to source" builders - they will still output files in your source tree (in addition to the output dir).

hi, i can choose `source` or `cache` via build_to option in normal builder, but how can do that in PostProcessBuilder? There is no `build_to` option in PostProcessBuilderDefinition.
