### ISSUE TITLE
`build_runner test` does not exit after test process exits

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#3770]
* Dart SDK Version: 3.5.4
* What package(s) from this repo you are using:
```
+ build 2.4.1
+ build_config 1.1.1
+ build_daemon 4.0.2
+ build_modules 5.0.9
+ build_resolvers 2.4.2
+ build_runner 2.4.13
+ build_runner_core 7.3.2
+ build_test 2.2.2
+ build_web_compilers 4.0.11
```
* What builder(s) you are using (or writing yourself): https://github.com/Workiva/test_html_builder/
* Whether you are using Windows, MacOSX, or Linux (if applicable): MacOSX
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): Chrome

---

We recently noticed that part of our CI is failing on Dart stable due to a `dart run build_runner test` process not exiting even though the child `test` process has (seemingly) exited successfully.

Fwiw, I filed a similar issue a long time ago (https://github.com/dart-lang/build/issues/2327), so maybe something regressed here? I haven't worked in the `test_html_builder` repo in a while, which is where we're seeing this issue, so I'm not sure when it would have actually been introduced.

Here's an example CI run where the process hangs and eventually times out:
https://github.com/Workiva/test_html_builder/actions/runs/11802042443/job/32876800406?pr=52

**Comment by jakemac53** [comment]
There was  I believe another report of this recently as well, but we couldn't figure out the issue. Our own e2e tests do not reproduce it.

**Comment by jakemac53** [comment]
Ah, yeah https://github.com/dart-lang/test/issues/2294 is the previous one.

**Comment by jakemac53** [comment]
closing as a duplicate
