### ISSUE TITLE
Add a mode to build to an output directory

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#387]
Should include result of DDC. Might also need the input Dart files laid out in a `packages/` directory or similar for source maps

**Comment by matanlurey** [comment]
How is this different than `writeToCache`?

**Comment by natebosch** [comment]
The output directory would include copying source files. Today the cache is only generated files

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/pull/667 add the `pub run build_runner:create_merged_dir --script=my/dart/script.dart --output-dir=my-output-dir` command but that is currently experimental and not what we want long term most likely.

Anybody who is following along and wants a stopgap solution can use it today though.

**Comment by matanlurey** [comment]
Just to clarify, do we expect more work here for the MVP? Should we boot?

**Comment by jakemac53** [comment]
I think it would be good to keep as a stretch goal? It would improve the testing story if we could get it done.

**Comment by natebosch** [comment]
The solution we'll go with is an `--output-dir` flag for the `build`, `watch`, and `serve` commands.

Closing in favor of #810
