### ISSUE TITLE
Figure out how to handle Builder lifecycles

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#396]
Our analyzer and ddc steps will likely need to run as workers and use a temp directory.

We need to figure out how to signal the lifecycle for builds - when to start and stop these processes, when to clean up scratch space, etc.

**Comment by matanlurey** [comment]
Ah, so are you imaging some sort of integration with `WorkerLoop`, or?

**Comment by natebosch** [comment]
Yeah I think we'll want to use the `bazel_worker/driver.dart` library for this, like what we do from pub today.

We had hoped to be able to get DDC and analyzer summaries running in-process and sharing an AnalysisDriver as a long term goal - but DDC isn't going to be using AnalysisDriver in the long term (or, it seems, ever).

Eventually DDC will be consuming kernel files, and we'll switch from using the analyzer to create summaries to using the frontend to create kernel. It's not clear that we'll get to a place where we can do that in process and share any in-memory view of the kernel. Not to mention the versioning difficulties that would arise trying to depend on Dart apis within DDC.

I think we're going to be stuck running DDC as a separate process because it's going to have a more stable surface area. Even this won't be stable during the summary -> kernel transition so we probably can't launch anything stable until that flip happens in DDC.

**Comment by natebosch** [comment]
Straw man proposal:

```dart
class MyBuilder implements Builder {
  @override
  Future build(BuildStep buildStep) {
    var expensiveResource = await buildStep.oncePerBuild('ResourceName', createExpensive);
  }
}

Future<Expensive> createExpensive() {...}
```

By default the 'per build' means 'per call to `runBuilder`' but this can be overridden by the build system to be more optimal like:

```dart
runBuilder(..., closeBuild: false);
...

closeBuild();
```

```dart
// in BuildStep:

/// Runs [callback] only once per build, returns a cached copy of the result if it's already been run.
T oncePerBuild(String key, T Function() callback) {
  return resourceCache.putIfAbsent(key, callback) as T;
}

// top level:
Map<String, Object> resourceCache;
/// Resets the [resourceCache] if it was kept open after `runBuilder`
void closeBuild() => resourceCache.clear(); 
```

**Comment by natebosch** [comment]
I just realized my proposal doesn't allow for cleanup....

```dart
class MyBuilder implements Builder {
  @override
  Future build(BuildStep buildStep) {
    var expensiveResource = await buildStep.oncePerBuild('ResourceName', createExpensive, disposeExpensive);
  }
}

Future<Expensive> createExpensive() {...}

Future dispose(Expensive e) {...}
```

```dart
/// Runs [callback] only once per build, returns a cached copy of the result if it's already been run.
T oncePerBuild(String key, T Function() callback, [void Function(T) dispose]) {
  disposeCache.putIfAbsent(key, dispose);
  return resourceCache.putIfAbsent(key, callback) as T;
}

// top level:
Map<String, Object> resourceCache;
Map<String, void Function(Null)> disposeCache;
/// Resets the [resourceCache] if it was kept open after `runBuilder`
void closeBuild() {
  for(var key in disposeCache.keys) {
    disposeCache[key](resourceCache[key]);
  }
  resourceCache.clear(); 
}
```

Some of the generics might get tricky...

**Comment by natebosch** [comment]
Another option that might get around some of the generic issues with the map:

```dart
// in package:build
class Resource<T> {
  /// Create or return already created instance.
  T _fetch() {...}
  /// Remove cached instance and run the dispose callback.
  Future _dispose() {...}

  Resource(T Function() create, FutureOr Function(T) dispose);
}

// in BuildStep
/// Marks that [resource] needs to be cleaned up at the end of the build and initializes its value.
T fetch(Resource<T> resource) {
  activeResources.add(resource);
  resource._fetch();
}

// top level:
void closeBuild() {
  for(var resource in activeResource) {
    activeResource._dispose();
  }
  activeResources.clear();
}
```

This way sharing is done by referring to the same `Resource` instances instead of by String key.

**Comment by jakemac53** [comment]
I think I like the `Resource` proposal more, although I think it needs to be more clear when `create` and `dispose` are being called.

Specifically, that a new `Resource` is created at least for each build (and possibly once per BuildStep for other environments where that can't be supported).

**Comment by jakemac53** [comment]
Another possibly simpler idea, would be to add a `buildId` field to `BuildStep`?

**Comment by natebosch** [comment]
`buildId` would handle resource that can be reused during a single build, but we'd still need a way to register a callback for cleanup right?

**Comment by jakemac53** [comment]
Ah true, we would still need some additional hook for cleanup.

**Comment by jakemac53** [comment]
Ok I am going to start working on this, going to go with the `Resource` class, as well as a `ResourceStore` class and `runBuilder` will take an optional `ResourceStore` arg so that it can be optimized for build_runner/bazel_codegen implementations.
