### ISSUE TITLE
Add hook to run dispose callbacks after builders finish

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#398]
We saw a nice usability improvement when we took `Resolver.release()` out of the hands of `Builder` authors since it was 1 fewer trap to fall into. As we add new resources that can be used during a build, but should not be shared for the sake of hermetic builds (like a scratch space, #397), it would be nice to let those resources hook into the zone that is running the builders and register to get cleaned up afterwards.

I'm imagining:

```dart
Future<SomeResource> createSomeResource() async {
  var handle = await _createResource();
  // Throws if this isn't running in a runBuilder zone
  buildZone.registerCleanup(_destroyResource(handle));
  return handle;
}
```

**Comment by jakemac53** [comment]
@natebosch I think we effectively covered this with the `Resource` api?

**Comment by natebosch** [comment]
Yes I think we've got this covered with `Resource` and related APIs
