### ISSUE TITLE
stale generated assets can stick around in the AssetGraph

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#409]
When we change the build actions or dependencies such that some asset will never get created some generated assets won't get deleted from the graph, we still serialize them to json and load them back in.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/pull/523 should partially fix this problem at least, or maybe entirely. At least it should help with cleaning up the cache dir which previously could end up with a lot of extra turds hanging around.

**Comment by jakemac53** [comment]
@natebosch do you know if this is still an issue?

**Comment by natebosch** [comment]
I can't repro this anymore.
