### ISSUE TITLE
Default serve handler should have a default document of `index.html`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#413]
You should be able to go to a directory and have it load the `index.html` by default.

**Comment by natebosch** [comment]
Today with `pub serve` I think it automatically picks up `web/index.html`? Should we try to mimic that?

**Comment by jakemac53** [comment]
I don't think we should do anything special around `web` necessarily. Pub serve automatically spins up a server for `web` and `test`, under different ports.

I don't think we have to mimic that behavior exactly, especially since we are just returning a more generic handler.

**Comment by natebosch** [comment]
It's also possible that `web/` will be the only prefix before `packages/` so handling it specially *could* let use make the handler a little less hacky?

**Comment by jakemac53** [comment]
There will also be `test/packages` for sure. Also now that I think about it `test` will likely have to be treated specially to work with package:test (serve directly from the `test` dir)....
