### ISSUE TITLE
Consider downgrading some WARNINGs to INFOs

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#426]
When developing a generator, it's really common to... change the generator.

These warnings come up over and over though:

1. `[WARNING] BuildDefinition: Invalidating asset graph due to build script update`
2. `[WARNING] Build: Found 2 declared outputs which already exist on disk.`

For `1`, maybe it makes sense to make this an `INFO`?
For `2`, I guess it's silenceable by using `deleteFilesByDefault` anyway?

**Comment by natebosch** [comment]
Yes, 2 can be silenced with `deleteFilesByDefault`. It's also silenced by `writeToCache`

I'd be fine with `[INFO]` instead of `[WARNING]`
