### ISSUE TITLE
Watch build does not restart when tool/** changes

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#429]
For example, I have a simple builder in `tool/codegen/builder.dart`, and `tool/build.dart` imports it.

There might be some option to allow this, but I don't see it :)

**Comment by zoechi** [comment]
Might be related to #314

**Comment by natebosch** [comment]
This was intentionally change (broken?) in https://github.com/dart-lang/build/pull/422 - we no longer kill the watch process immediately when the build script or a dependency changes. Do you think we should restore that behavior? We never would have rebuilt files, only killed the process which might cause you to restart it manually.

**Comment by matanlurey** [comment]
Oh, right. I don't know what I was thinking... I guess we could hot-reload? ;)

**Comment by matanlurey** [comment]
Thought about this a bit, a couple of options:

1. Warn when the script/dependency changes, so the user knows the generator is stale.
2. Support some sort of "hot reload" solution:

```dart
// Uses Isolate.spawn internally.
hot(() => watch(...));
```

Not a priority, just fun thoughts :)

**Comment by natebosch** [comment]
Once we start autogenerating and running the script we might not even need anything tricky beyond being able to recognize the situation and rerun the watch using the mechanism we need to build anyway.

**Comment by matanlurey** [comment]
I'm closing as a duplicate of #353 then @natebosch.
