### ISSUE TITLE
Proposal: add `bool get optional` field to Builder interface (defaults to false)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#432]
Some builders want to run lazily and only if their output is needed by some other builder or requested directly from a server. This should be able to extend to full builds as well so the outputs will never be generated if not needed by any other part of the build.

One of the primary use cases initially will be for analyzer summaries and ddc, we only want to summarize and/or compile any modules that are actually required by an actual web application. Today we compile for the entire world and it does a lot of extra work.

Note that this is different from `lazy` transformers, which always run if you do `pub build`, which is why I called the field `optional` instead. They are lazy, but they also won't ever be built in any context unless required by some other build action.

I think these actions would still live in a specific phase, so their inputs would be limited to what was available in that phase, they would just delay their execution until later.

cc @natebosch @matanlurey

**Comment by jakemac53** [comment]
@matanlurey I think it might make sense for angular to do run in this mode as well? You could potentially only compile templates for the components that are actually used in the app for instance.

**Comment by natebosch** [comment]
Should this be done with build.yaml and in the BuidAction rather than the builder? This wouldn't have meaning in bazel would it?

**Comment by jakemac53** [comment]
True that it wouldn't be optimizable in bazel, but that should be fine? We don't have to make guarantees around it, just a best effort based on implementation.

I think it would be a lot simpler to have the config be based on a field in your builder implementation than requiring a build.yaml.

**Comment by matanlurey** [comment]
Maybe it would help explaining when this optimization could be used.

From an AngularDart perspective, I don't understand it.

@jakemac53:

> @matanlurey I think it might make sense for angular to do run in this mode as well? You could potentially only compile templates for the components that are actually used in the app for instance.

We only know what components are "used" by one of four signals:

* An import to the file containing them (not always true)
* Use of the component in a `directives: const [ ... ]` list (still not always true)
* Use of the component's `Type` somewhere in the application (still not always true)
* Use of the component's `{Type}NgFactory` (still not always true)

I'm not sure how I'd optimize given these constraints.

**Comment by jakemac53** [comment]
@matanlurey I was thinking essentially you could have a bootstrap builder which runs in the last phase and basically just crawls the import graph asking for a corresponding `.template.dart` file for every import it sees? Maybe I am missing something but I would think that could work. Even just resolving the entrypoint library should actually cause this to happen automatically (assuming it has an import to the .template.dart for your root component).

**Comment by natebosch** [comment]
Assuming we request the generated .js file for each entrypoint we should be guaranteed that all reachable .template.dart sources are requested and built.

Maybe we should think of a name that reflects when we would use this. Something like `srcs` vs `data` in bazel, where the optional builders produce sources a compiler would consume, while the non-optional builders are presumably producing data that is used at runtime but not otherwise requested during the build.

**Comment by jakemac53** [comment]
> Assuming we request the generated .js file for each entrypoint we should be guaranteed that all reachable .template.dart sources are requested and built.

Yes, that's exactly how summaries/ddc work in pub and its actually really nice imo.

> Maybe we should think of a name that reflects when we would use this. Something like srcs vs data in bazel, where the optional builders produce sources a compiler would consume, while the non-optional builders are presumably producing data that is used at runtime but not otherwise requested during the build.

I don't think it directly maps to anything like that really, for instance analyzer is only producing summaries for other build steps but ddc is producing actual js modules that are used at runtime. I think `optional` describes it pretty well - they are only built if requested by something else.
