### ISSUE TITLE
build_runner should have a general way of ignoring certain directories

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#440]
We currently have a hardcoded list of `toolDirs` in `build_runner/lib/src/util/constants.dart`, but users should have the ability to customize this. We should also consider just ignoring all hidden directories?

**Comment by matanlurey** [comment]
#451 might help a bit, right?

**Comment by natebosch** [comment]
Ignoring all hidden directories sounds fine.

We could also explore going the other direction, configure a whitelist for directories to pay attention to. For dependencies it's always only `lib/` and for the root package it defaults to `lib/`, `web/`, `bin/` but can be expanded with config.

**Comment by matanlurey** [comment]
👍 Opt-in versus opt-out.

**Comment by natebosch** [comment]
We have a whitelist as of https://github.com/dart-lang/build/pull/682
