### ISSUE TITLE
Code generation error on nested generic bounded type arguments

### ISSUE THREAD

**Issue by KholmatovS** [dart-lang/build#4454]
Code generation throws an error when a nested generic bounded type argument is used. The following code reproduces the issue:

example:
```dart
abstract class Worker<T extends Worker<T>> {}
mixin Workers {
  void someWork<T extends Worker<T>>() {
    print('Work on: $T');
  }
}
abstract class Bar<T> with Workers {}
class BackgroundWorker extends Worker<BackgroundWorker> {}
class Foo extends Bar<Foo> {
  void doWork() {
    someWork<BackgroundWorker>();
  }
}
```
> **Bad state: T extends Worker\<T\> not found, scopes: [{}, {T extends Worker\<T\>: T}]**

or simpler example:

```dart
class Foo<T> {}
abstract class Bar<T> {
  Iterable<X> m1<X extends Foo<X>>(X Function(T) f);
}
abstract class FooBar<X> extends Bar<X> {}
```
> **Bad state: X extends Foo\<X\> not found, scopes: [{X: X}, {X extends Foo\<X\>: X1}]**

**Comment by scheglov** [comment]
My understanding is that type equality is not defined by the language specification. @eernstg 

I can only see `20.5 Function Types` that says
<img width="586" alt="image" src="https://github.com/dart-lang/build/assets/384794/609d8b5e-9cc6-4d1c-9e35-c276f39d6bc9">

I would say that two `TypeParameterType`s are equal only when the are based on the same `TypeParameterElement`, not just have the same name. We might have be somewhat lax in the analyzer, and return `true` even in other cases, but this breaks in other cases.

I don't know what to advise here without getting into details how you use these types.
