### ISSUE TITLE
Globbing apis don't properly track dependencies

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#455]
Specifically for new files, if you do a glob for "**.dart" for instance you should get reran if any new dart files are added. Today that is not the case because we only track the files that the glob originally matched against.

We may actually not want to track the actual input files at all in this case and just track the globs separately? That should help trim the dependency graph and still gives us all the info we need.

**Comment by matanlurey** [comment]
Interesting enough this is also a bug/lack of feature in `iblaze`/`bazel_watcher`:

```build
dart_library(
  srcs = glob(["lib/**.dart"]),
)
```

... If you**add** `lib/x.dart`, it will not trigger a re-build, as it apparently was expensive to do so at bazel-like level; that being said, pub packages tend to be easier to reason with and maybe we could watch for _all_ changes, and then check if the change matches any glob.

**Comment by jakemac53** [comment]
Ya, luckily we only allow you to glob within the same package so that narrows down the number of actions we have to check against when a new file is added, but it still has the potential to be somewhat expensive.

This is only for new files though, and only matters when you have an existing asset graph so it won't slow down the initial build, and it should be pretty rare that you see a ton of new files otherwise. Potentially changing to a new branch or something where you added a thousand files might suck a bit, but there isn't really any way around that anyways.
