### ISSUE TITLE
Use a PackageWatcher abstraction over Watcher?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#456]
I noticed when in the process of working on #424 that the usage of `Watcher` is quite complex; it needs to map arbitrary file events back to a potential asset changed. This makes tests such as those in `watch_test.dart` already a little opaque:

```dart
FakeWatcher.notifyWatchers(
  new WatchEvent(
    ChangeType.MODIFY, 
    path.absolute('a', 'packages', 'a', 'a.txt')
  )
);
```

What I'm proposing is a `build_runner` abstraction over `Watcher`:

```dart
abstract class PackageWatcher {
  factory PackageWatcher(String path) = _PackageWatcher;

  Stream<AssetId> watchDirectory(String directory);
}
```

This would be much easier to mock out, but also easier (potentially) in the future to support custom file systems, in-memory implementations, or whatever requirement others might have. WDUT?

/cc @jakemac53 @natebosch

**Comment by jakemac53** [comment]
Sounds good to me

**Comment by natebosch** [comment]
Sounds good
