### ISSUE TITLE
Add PackageNode.synthetic (name?)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#459]
```dart
class PackageNode {
  PackageNode.synthetic(String name, Uri location)
    : this(name, null, null, location);
}
```

This allows removing lots of testing code that relies on passing `null`. We can optionally annotate this with `@visibleForTesting` if you're afraid users might think about using it in production code.

**Comment by jakemac53** [comment]
I am ok w/this, or optionally we could create a helper method under test/common/
