### ISSUE TITLE
`findAssets` needs to become async to support lazy builders

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#461]
We don't know what assets will actually be generated or not until we try to build them which is an async process, so we will have to change this to be async.

This is going to require coordination across all the packages most likely :(.

**Comment by jakemac53** [comment]
cc @natebosch

**Comment by natebosch** [comment]
😞
It was a risk when we made it synchronous in the first place. Shouldn't be too hard to update since it isn't widely used.
