### ISSUE TITLE
Infer root for `BuildAction`?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#467]
A typical user bug is copy-pasting a `build.dart` from another package, only to hit an error:

> I am finding source_gen for the first time when attempting to use json_serializable.
> I figured out that I need to create a "build script" and started by copying the one from here
 (https://github.com/dart-lang/json_serializable/blob/master/json_serializable/tool/build_actions.dart). However, when I run dart tool/build.dart I get a the error: `A build action is attempting to operate on a package which is not the root`

I also never really understood `BuildAction` needing a package - I imagine if we want Bazel compatibility ultimately then building _another_ package is not exactly allowed anyway. I realize this might be obsolete (or uninteresting) once we have https://github.com/dart-lang/build/issues/353, but worth filing I think.

At the very least, maybe we should have the error help you out a bit:

```
A build action is attempting to operate on package "foo", but the build script is located in package "bar". It's not valid to attempt to generate files for another package, did you mean to write:

  new BuildAction(..., 'bar')

... instead?
```

**Comment by jakemac53** [comment]
Now with `writeToCache` we do support running builders on other packages. We could consider packing `package` an optional argument though and defaulting it to the root package?

**Comment by matanlurey** [comment]
I'm going to just improve the error message for now!
