### ISSUE TITLE
Rebuilds shouldn't hit the file system to get the list of inputs

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#48]
Today each rebuild will list the file system for all files. We should instead just keep an updated set of valid inputs, based on updates that are seen.

**Comment by natebosch** [comment]
This is fixed now. The only place we call `AssetReader.findAssets` is in `build_definition.dart`, and that only happens on the [first load](https://github.com/dart-lang/build/blob/ca4743640af3e8d109e19013137507176448e1ff/build_runner/lib/src/generate/build_definition.dart#L70). Subsequent builds based on the file changes [update the asset graph](https://github.com/dart-lang/build/blob/ca4743640af3e8d109e19013137507176448e1ff/build_runner/lib/src/generate/build_impl.dart#L91) without listing from disk.
