### ISSUE TITLE
Should writeToCache implicitly copy inputs?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#484]
... similar to Bazel's runfiles?

Otherwise you'll have to write a more complex serving handler/overlay file system.

It would potentially also make the analysis story easier for IDEs?

**Comment by jakemac53** [comment]
I think we want to handle this with https://github.com/dart-lang/build/issues/387

**Comment by jakemac53** [comment]
Fwiw though the serving mechanism is not difficult if you have an AssetGraph, and we expose that through a normal shelf handler now so you can plug it into any shelf server.

**Comment by matanlurey** [comment]
Closing, this looks simple enough already.
