### ISSUE TITLE
Allow limited re-writing of assets?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#485]
Was hacking a bit with `watch` and `build_compilers`.

It would be really nice to rewrite `web/index.html`:

```html
<html>
  <script src="main.dart" type="application/dart"></script>
</html>
```

... to ...

```html
<html>
  <!-- Change these depending on the DDC module format. -->
  <script src="require.js"></script>
  <script src="dart_sdk.js"></script>
  <!-- ... -->

  <script src="main.js"></script>
</html>
```

We do something like this internally, but use `index.ddc.html`. It would be nice to offer a better user experience here _if_ we can do it safely.

**Comment by jakemac53** [comment]
With dartium going away I think we just want to start encouraging users to directly include the `main.dart.js` script as a normal js script, or they can do what they have been doing and include the `packages/browser/dart.js` script if they want dartium support as well.

For DDC this can just be a bootstrapping script which injects these other scripts.

If we allow overwriting of files in any way it severely limits a lot of optimizations that we can do (and breaks existing assumptions) so I really don't want to go down that path.

**Comment by natebosch** [comment]
I would like to push as far as we can without allowing rewrites. When we get to the point that we have an unsolvable problem we can evaluate solutions around very limited rewriting where it happens only as the last step and rewritten files can't be read by any other Builders.

**Comment by matanlurey** [comment]
I think @jakemac53's original points is fine for me, assuming we generate a bootstrap :)
