### ISSUE TITLE
Consider a way of providing outputs which are only produced if the file doesn't already exist

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#508]
The primary use case for this today is during test bootstrapping. We want to automatically create an `_test.html` file for each `_test.dart` file, but only if it doesn't already exist.

The only options today are:

- force users to always create the html file
- never allow users to create the html file
- add configuration for whether or not to create the html file

**Comment by natebosch** [comment]
We'll have to be careful how we do this - it won't work nicely without `buildToCache`. I think with that flag though we can probably detect the situation and avoid running a `Builder` that claims it will overwrite an existing source.

**Comment by jakemac53** [comment]
Ya, this is tricky potentially to handle in bazel as well although it could be done.

**Comment by jakemac53** [comment]
Ok - we talked offline and are going to run with roughly the following:

- Add an optional arg to `apply` that enables you to declare overlapping outputs, and delays any errors until you actually try to output a pre-existing source.
  - Only allowed if you are also outputting to cache
  - When building the asset graph if we see an output that conflicts with a source file (and you are using this option), we leave the `SourceAssetNode` node in place and do not create a `GeneratedAssetNode`
  - If you ever try and actually write an output which has an existing `SourceAssetNode` then we fail at that point
- Add a corresponding config option to build_config, and use that in the autogen script

This would be opt-in only, as it effectively delays errors to build time instead of asset graph creation time. In general we would prefer to keep errors early.

**Comment by jakemac53** [comment]
@natebosch 

So I have this working but I realized a weird edge case in the process... lets say you have a builder which outputs a file `foo.txt`, and then another builder with `allowDeclaredOutputConflicts` set to `true` that outputs that same file (and comes afterwords). If the first builder doesn't actually output `foo.txt` then the second builder will do the "right thing" and check `canRead`, which will return `false`, and go ahead and try to output that file.

This should theoretically work but in reality we will (or at least should) throw an exception because the `phaseNumber` for the `GeneratedAssetNode` won't match the 2nd builders phase - it will match the first builders phase.

Some potential solutions:

- Do not allow this situation at all - essentially only allow you to declare overlapping outputs for source files but not other generated files.
- Add support somehow to `GeneratedAssetNode` - possibly turn `phaseNumber` into an Iterable.
- Add a new node type for these nodes, where the generating `phaseNumber` is allowed to change and possibly also has a list of potential generating phase numbers.

For now I think I will just drop support for conflicting outputs with other generated sources, lmk what you think though please.

**Comment by jakemac53** [comment]
We also wouldn't be able to allow conflicting outputs with other generated sources in bazel - or it would be much more difficult.

**Comment by natebosch** [comment]
> For now I think I will just drop support for conflicting outputs with other generated sources, lmk what you think though please.

I'm on board. I think it's much simpler to express that a Builder may either output a file or the user may write one manually. Getting in to more complex interactions between builders is both harder for us, and more confusing for the users and Builder authors.

**Comment by matanlurey** [comment]
+1 to dropping support. I think it would be reasonable for a user to have to opt-out of certain HTML files being generated if they want custom ones and not rely on the ones created for use by pkg/test.

In a brave new world, the webdev CLI could try and help here, too. It's unfortunate that the format for both pubspec and build is YAML, which is really hard to automatically update with tooling today.

Does `generate_for` work for this purpose? Do we need to add the concept of excludes, i.e.:

```yaml
  generate_for:
    include: [...]
    exclude:
        # Do not emit a custom_test.dart.html, because one is hand-written.
        - test/custom_test.dart
```

**Comment by natebosch** [comment]
`generate_for` already supports `exclude`, but I don't think it helps much with this case unless we also split the builder out into a separate one. Splitting the builder would be a little weird since they'd both wrap the same Transformer, do the same work, and they'd each just throw away different parts of it.

Jake is working on another (hacky) solution to unblock the testing use case: https://github.com/dart-lang/build/pull/775

**Comment by matanlurey** [comment]
Cool!

**Comment by jakemac53** [comment]
Moved this out of the MVP milestone as it was primarily for testing and we have a different solution there now.

**Comment by natebosch** [comment]
PostProcessBuilder gets us close enough. We can reopen if we think we need this for builders earlier on.
