### ISSUE TITLE
File watching doesn't start until after the first build is complete

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#524]
Because of this any edits during the first build will not be captured.

We should really set up all the file watchers before even starting the first build, otherwise we can get in a bad state.

**Comment by natebosch** [comment]
yeah I think I broke this behavior in https://github.com/dart-lang/build/pull/404

**Comment by natebosch** [comment]
I think what we want is to undo https://github.com/dart-lang/build/pull/331 so that we can `await` and be sure the watchers are running before moving on to do more work.
