### ISSUE TITLE
Invalidate the asset graph if the build script changes

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#53]
This needs to see if any dependencies change as well.

**Comment by Allan-Nava** [comment]
How can I fix this problem?

**Comment by jakemac53** [comment]
This should be fixed, what problem are you seeing?

**Comment by Allan-Nava** [comment]
> This should be fixed, what problem are you seeing?

> 
> Error compiling dartdevc module:dart_noipy|web/main.ddc.js
> 
> [error] The getter 'AppComponentFactory' isn't defined for the class 'ng'. (/web/main.dart, line 38, col 13)
>

**Comment by jakemac53** [comment]
This looks like a static error in the code - to me it looks like `ng` is an import prefix for a generated template file, and that file doesn't contain something you expect it to?

**Comment by Allan-Nava** [comment]
> This looks like a static error in the code - to me it looks like `ng` is an import prefix for a generated template file, and that file doesn't contain something you expect it to?

This project: https://github.com/NoipyDevOPS/Dart-Noipy/blob/master/web/web/main.dart#L38

**Comment by Allan-Nava** [comment]
> > This looks like a static error in the code - to me it looks like `ng` is an import prefix for a generated template file, and that file doesn't contain something you expect it to?
> 
> This project: https://github.com/NoipyDevOPS/Dart-Noipy/blob/master/web/web/main.dart#L38

I fix! thanks for support
