### ISSUE TITLE
Editing library dependency under same non-lib dir causes build failure

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#533]
It looks like summaries for non-lib modules have absolute uris to the files, which point at a tmp dir that only exists for a single build.

We will need to change the uris in the summaries inside of `_analyzerSourceArgsForModule` in summary_builder.dart, and then also change dev_compiler_builder.dart to know about the new uris for those files (probably using --url-mapping).

**Comment by jakemac53** [comment]
cc @vsmenon @jmesserly I think I am taking the right approach to this but I haven't actually been able to get it to work.

For example, we have a file structure like:

test/
  hello_world_test.dart
  common/
    message.dart

When compiling I get this error:

```
[error] Target of URI doesn't exist: 'common/message.dart'. (/tmp/build_compilersJtITsk/test/hello_world_test.dart, line 12, col 8)
[error] Undefined name 'message'. (/tmp/build_compilersJtITsk/test/hello_world_test.dart, line 24, col 41)

Please fix all errors before compiling (warnings are okay).
```

I am currently passing this argument:

--url-mapping=file:///tmp/build_compilersJtITsk/test/common/message.dart,/test/common/message.dart

The summary for `test/common/message.dart` looks like this:

```
{
  version: 1.0,
  linkedLibraryUris: ["file:///test/common/message.dart"],
  unlinkedUnitUris: ["file:///test/common/message.dart"],
  library "file:///test/common/message.dart": {
    dependencies[0]: {uri: "file:///test/common/message.dart"},
    dependencies[1]: {
      parts[0]: "dart:core/annotations.dart",
      parts[1]: "dart:core/bool.dart",
      parts[2]: "dart:core/comparable.dart",
      parts[3]: "dart:core/date_time.dart",
      parts[4]: "dart:core/double.dart",
      parts[5]: "dart:core/duration.dart",
      parts[6]: "dart:core/errors.dart",
      parts[7]: "dart:core/exceptions.dart",
      parts[8]: "dart:core/expando.dart",
      parts[9]: "dart:core/function.dart",
      parts[10]: "dart:core/identical.dart",
      parts[11]: "dart:core/int.dart",
      parts[12]: "dart:core/invocation.dart",
      parts[13]: "dart:core/iterable.dart",
      parts[14]: "dart:core/iterator.dart",
      parts[15]: "dart:core/list.dart",
      parts[16]: "dart:core/map.dart",
      parts[17]: "dart:core/null.dart",
      parts[18]: "dart:core/num.dart",
      parts[19]: "dart:core/object.dart",
      parts[20]: "dart:core/pattern.dart",
      parts[21]: "dart:core/print.dart",
      parts[22]: "dart:core/regexp.dart",
      parts[23]: "dart:core/set.dart",
      parts[24]: "dart:core/sink.dart",
      parts[25]: "dart:core/stacktrace.dart",
      parts[26]: "dart:core/stopwatch.dart",
      parts[27]: "dart:core/string.dart",
      parts[28]: "dart:core/string_buffer.dart",
      parts[29]: "dart:core/string_sink.dart",
      parts[30]: "dart:core/symbol.dart",
      parts[31]: "dart:core/type.dart",
      parts[32]: "dart:core/uri.dart",
      uri: "dart:core"
    },
    importDependencies: [1],
    numPrelinkedDependencies: 2,
    defining compilation unit: {
      references: [{kind: unresolved}, {name: "String", dependency: 1 (dart:core), unit: 28}],
      apiSignature: [180, 3, 204, 93, 122, 92, 146, 229, 96, 24, 3, 168, 39, 108, 33, 116],
      codeRange: {length: 255},
      executables[0]: {
        name: "message",
        codeRange: {length: 37, offset: 217},
        kind: getter,
        nameOffset: 228,
        returnType: {reference: 1 (String)}
      },
      imports: [{isImplicit: true}],
      lineStarts: [0, 78, 156, 216, 217, 255],
      publicNamespace: {names: [{name: "message", kind: topLevelPropertyAccessor}]}
    }
  },
  apiSignature: "8b969dcab8a7c2884d23f1bc3c52a51a",
  unlinkedUnitHashes: ["d3157fa3eaff7ff567a69027874e6891"]
}
```

**Comment by vsmenon** [comment]
Do you know if this is working bazel?

**Comment by jakemac53** [comment]
It looks like it does, but I don't see anything obviously different, it is using the same general strategy except the uris are relative to the bazel root instead of package root which shouldn't affect things.

**Comment by jakemac53** [comment]
Ok, the difference is the additional usage of --bazel-mapping. I now have things working, the new args passed look like this for the example above:

--url-mapping=file:///tmp/build_compilersJHsXpi/test/common/message.dart,test/common/message.dart
--bazel-mapping=test/common/message.dart,common/message.dart

**Comment by jakemac53** [comment]
Actually, nvm again :). The --bazel-mapping is not required. The change that got it working is making the mapped path for --url-mapping be relative not abosolute (changing /test/common/message.dart => tool/common/message.dart), even though its absolute in the summary.

**Comment by jakemac53** [comment]
hmm even then it looks like the dependency is getting compiled into to root module though :/
