### ISSUE TITLE
Support running ddc tests with --precompiled

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#534]
See https://github.com/dart-lang/test/issues/709, today our ddc bootstrapping code relies on absolute paths to point a packages directories and also modules (its a lot simpler that way, and we only allow you to serve top level dirs anyways).

This works fine for running tests with --pub-serve, but it would probably be better to run tests with --precompiled instead. For instance we should be able to run generated test files, which we can't do with --pub-serve (it still hits the file system to glob for tests in that scenario).

**Comment by nex3** [comment]
Please note that `--precompiled` is not an officially-supported part of the (external) API surface. If you use it, you run the risk of being broken by future `test` versions or being unable to use certain features like plugin loading in the future.

**Comment by jakemac53** [comment]
closing as not planned for now
