### ISSUE TITLE
Change Builder.build to FutureOr<void>

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#535]
Prepares for `FutureOr<void>`, and doesn't require adding `async` to your method body.

... though maybe all of this is not too important if post-Barback we can make methods sync?

**Comment by jakemac53** [comment]
Not sure what you meant re: post-barback, but in general I think this SGTM.

We already made a similar change in source_gen because somebody requested it https://github.com/dart-lang/source_gen/issues/250.

**Comment by matanlurey** [comment]
Seems like this isn't really worth it since `Future<void>` is rolling out.

We can wait until then.

**Comment by jakemac53** [comment]
Ping on this, @natebosch @matanlurey @grouma  should we implement this for 1.0.0 or should we close the issue?

**Comment by natebosch** [comment]
Yes, I'd like to get this in for 1.0.0

**Comment by matanlurey** [comment]
Not: should be void now not Null :)
