### ISSUE TITLE
Add skippable build actions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#539]
When serving/editing your main app, you probably don't want to constantly be rebuilding your tests as well, but today you would. If you have a lot of tests that could potentially slow down your edit/refresh significantly.

In order to support something like `dbuild serve web` and `dbuild serve test`, I propose that we add a notion of skippable build actions. This means our AssetGraph can retain the structure of the build, but simply skip certain portions of it.

One possible option could be combining this with the `optional` build actions concept, so that skipped actions would still be ran if something non-optional requested them. More concretely, I suggest adding a named arg such as `List<Glob> forceBuildIfMatches` to `BuildAction`, which is only allowed if `isOptional` is also `true`. Instead of skipping all actions that have `isOptional == true`, we would actually run builds for anything matching any of the provided globs. It would be safe to change those globs for different build invocations, based on command line args or whatever.

This would enable you to build specific apps based on their entry point file etc (`dbuild web/main.dart` etc).

cc @natebosch wdyt?

**Comment by natebosch** [comment]
I think this makes sense. I'd maybe call the parameter `alwaysBuild`

**Comment by jakemac53** [comment]
@natebosch @grouma @kevmoo I am going to start working on this, but we should clarify what the api should look like.

I actually no longer think we need to add any special flag that says an option is skippable, we can just treat all actions as skippable instead. We can accept a glob of paths that should be built - and only build the non-optional things that match those globs (and any other outputs from those same actions).

Then there is a question of what the command line interface should look like, especially because we already support trailing arguments for the `serve` and `test` commands.

Some options:

- Add a flag `--if-matches` or `--only` or something like that. This seems verbose though.
- Extend the `serve` trailing args to support globs patterns like `web/main.dart.js:8080`. I think we would always serve the top level folder in that case - but then only build `web/main.dart.js`.
  - This allows us to support it via normal trailing args in the `build` command as well.
  - It is unclear exactly how to handle the `test` command here - we could change it so we forward these args on to `pub run test`, so to run a single test would look like `pub run build_runner test --build-args test/foo_test.dart -- --test-args`. This would probably get a bit nasty in the arg parser logic, but should be doable.

Any other ideas?

**Comment by jakemac53** [comment]
Oh one other option is to support building `targets` by name, which might be nice in some ways but would require some configuration as well, and it still doesn't solve building individual tests unless you make a target for each one.

**Comment by natebosch** [comment]
One thing to consider if we want to use globs is that some shells want to handle the globbing themselves, so getting the glob through to the process requires some extra escaping. Bazels approach of using `path/to/package:all` or `path/to/...` avoids this problem.

**Comment by jakemac53** [comment]
Another option here after talking to @kevmoo is we could have users specify the "entrypoints" they want to build. Essentially these would be the dart files, and we would build all the primary outputs of those nodes. So you could do `pub run build_runner build test/foo_test.dart`. This most closely corresponds to your understanding of the package layout most likely, and means you don't have to know the output file names? For instance, knowing to reference `*_test.dart.browser_test.dart.js` would be not ideal.

**Comment by natebosch** [comment]
specifying based on existing sources also has the nice benefit of working by default with file-based tab complete.

Maybe it can be either/or? Specify a source file and build all non-optional outputs stemming from that file, specify a generated file and build it (and all outputs from the same step)

**Comment by jakemac53** [comment]
> specifying based on existing sources also has the nice benefit of working by default with file-based tab complete.

Good point, definitely another point in favor of this approach.

> Maybe it can be either/or? Specify a source file and build all non-optional outputs stemming from that file, specify a generated file and build it (and all outputs from the same step)

I do like the idea of both, but I am not sure how we would differentiate between the two modes. I don't think we can base it solely off whether the file is generated or not - you should be able to reference generated entrypoints and build the outputs of those as well imo.

**Comment by jakemac53** [comment]
> One thing to consider if we want to use globs is that some shells want to handle the globbing themselves, so getting the glob through to the process requires some extra escaping. Bazels approach of using path/to/package:all or path/to/... avoids this problem.

Yep true, we could support directories and explicit paths only for now? I think that covers the major use cases.

**Comment by jakemac53** [comment]
Ok, going to work on an initial implementation for now which only supports filtering by top level directories.

After that we can consider layering on special magic for the `test` command itself, or exposing more explicit options.

**Comment by natebosch** [comment]
We don't have immediate plans to add deep understanding of test targets so I think we've done everything we need to on this issue.
