### ISSUE TITLE
LibraryBuilder: generate `y.dart` from input `x.dart`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#553]
I'm trying to create `test/src/foo_nullable.dart` given `test/src/foo.dart`

But I seem to only be able to generate `test/src/foo.nullable.dart`

Intentional? I'd love to have a bit more flexibility here...

`#ThingsIShouldKnow`
 Related to https://github.com/dart-lang/build/issues/552

**Comment by matanlurey** [comment]
Isn't this pkg/source_gen?

**Comment by kevmoo** [comment]
I hit this just using Builders – so I don't *think* so...

**Comment by natebosch** [comment]
No, this is not possible today. We intentionally limited the files you can output to only changing extensions on the primary input.
We want to use only configuration driven output possibilities so that we can find outputs in Skylark without writing custom code for each builder.

What is the use case for being able to output to a different file basename?

**Comment by kevmoo** [comment]
> What is the use case for being able to output to a different file basename?

I have some file `x.dart` and I'd like to treat it like a template to generate 3 other flavors.

`x_nullable.dart`, `x_nullable_custom_classes.dart`, `x_custom_classes.dart`

I can do all of this with extensions, obviously – just starts feeling a bit weird.

...more curious than anything

**Comment by natebosch** [comment]
This would be possible today. We say "extension" but the way it's implemented is "postfix" so you could configure a builder to have `buildExtensions' as `{ '.dart': [ '_nullable.dart', '_custom_classes.dart']}`

Similarly if you had a use case you could go from `_test.dart` to `_harness.dart` or similar.

**Comment by natebosch** [comment]
This would be possible today. We say "extension" but the way it's implemented is "postfix" so you could configure a builder to have `buildExtensions' as `{ '.dart': [ '_nullable.dart', '_custom_classes.dart']}`

Similarly if you had a use case you could go from `_test.dart` to `_harness.dart` or similar.

**Comment by jakemac53** [comment]
We have also had requests to generate files in a separate directory. This matters less when you are setting `writeToCache: true`, which will become more common soon, but I think it is still a valid use case we will want to eventually support, and we should be able to do it in a generic fashion that works across build systems without custom code per builder.

**Comment by natebosch** [comment]
Interesting, the `example/` use case is pretty compelling, I'm having a hard time coming up with a configuration we could use that would work for that without being overly specific to that use case.

The types of directory moves I can imagine are:

1. Move from one top-level directory to another (`lib/something/foo.dart` to `example/something/foo.example.dart`)
2. Move to a sibling directory (`lib/something/foo.dart` to `lib/different/foo.dart`)
3. Move to a sub directory (`lib/something/foo.dart` to `lib/something/sub/foo.dart`)

Describing each of these without only configuration metadata could be tough.

**Comment by natebosch** [comment]
I think we would most likely want the `example/` use case to be solved with `example/$example$` like our other [magic placeholder](https://github.com/dart-lang/build/pull/746) files. I don't think we want to go down a path of allowing an arbitrary number of assets to be mirrored in a separate directory tree.

We can reopen if we find a compelling use case, but for now I'm going to close this as not planned and we can file a separate issue for `$example$` if and when we need it.
