### ISSUE TITLE
Incremental builds don't work with build script in `.dart_tool`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#587]
We exclude `.dart_tool/` from the AssetGraph and since the build script is there it can't be used to detect build script changes so incremental builds are not attempted.

We could potentially always include the script entrypoint in the asset graph (override the exclude for just that file) but it would mean relative imports don't work to other files in `.dart_tool/` - this is probably an acceptable tradeoff since we control the script contents.

**Comment by jakemac53** [comment]
We could also just whitelist a whole subdirectory under that, `.dart_tool/build/entrypoint` or something
