### ISSUE TITLE
Behavior difference against _bazel_codegen - pipeline of Builders

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#589]
In `_bazel_codegen` when you use multiple builderFactories in a single list they are applied in order and only fed as an input the previous builder's output.

Today in `build_runner` if you have multiple builderFactories in a single list they are applied in order, but *any* previous asset may be treated as a primary input - not limited to only the outputs of the previous builder.

I don't think any Builder is truly relying on this today. Angular has multiple builderFactories in series, but their input extensions are unique enough that we don't necessarily rely on only getting the subset of previous inputs.

We should either change this behavior in `_bazel_codegen` or find a way to support it in `build_runner`.

**Comment by jakemac53** [comment]
I think we should change `bazel_codegen` semantics to match that of `build_runner`.

**Comment by natebosch** [comment]
at the moment I can't think of any reason that we can't accomplish this behavior in `_bazel_codegen` so I filed an issue there. If for some reason that turns out to be difficult we can revisit.
