### ISSUE TITLE
Decide how by-dependency builders interact with manual configuration

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#596]
Open questions:

1 - Should all builders become automatic or should we add a flag `apply_by_dependency` to the build config to opt in to that?
2 - If a package has a `build.yaml` with a `target` explicitly opting in to some Builder, should it *also* get automatically applied builders from dependencies or should a manual config opt you out of the magic?
3 - We currently use package-level dependency information to apply automatic builders.`package:angular` does not have a package-level dependency on itself but does need the builders run.
   - Require a manual `target` definition including the builder applied?
   - Change to target-level dependency information to apply automatic builders and Angular's 'default' target can have a dependency on the target which defines the builder? (might break the auto dependency for other packages)

**Comment by matanlurey** [comment]
FWIW Angular feels a little exceptional - building code generation that it-itself uses.

I'd be fine with us needing manual hookup if it simplifies things.

Though I imagine most packages will need codegen run on their tests/some of them anyway?

**Comment by jakemac53** [comment]
> 1 - Should all builders become automatic or should we add a flag apply_by_dependency to the build config to opt in to that?

I think they should probably remain automatic, unless you explicitly disable that. It should be based on the dependencies of the module though, not the whole package.

> 2 - If a package has a build.yaml with a target explicitly opting in to some Builder, should it also get automatically applied builders from dependencies or should a manual config opt you out of the magic?

I think you should still get auto applied builders in this case. It would override the settings for any identical auto-configured builder, or add the builder if it wasn't already auto-added.

> 3 - We currently use package-level dependency information to apply automatic builders.package:angular does not have a package-level dependency on itself but does need the builders run.
> 
> Require a manual target definition including the builder applied?

I think this is reasonable for this case, or we expose it as an explicit option.

> Change to target-level dependency information to apply automatic builders and Angular's 'default' target can have a dependency on the target which defines the builder? (might break the auto dependency for other packages)

We should change to target-level dependencies for applying automatic builders anyways, but I don't know if we want to expose the builders at the the target level or not.... it could be interesting though.

**Comment by natebosch** [comment]
Closed by https://github.com/dart-lang/build/pull/756

1 - We have an `auto_apply` configuration key to specify which builders should be applied in this way
2 - We will merge auto builders and manual builders for a given target, unless the target manually specifies `enabled: False` for a builder that would have otherwise been applied>
3 - Packages like angular will manually opt in to their own builders since they don't have a dependency on themselves. We aren't going to try to work in some per-target dependency option - the auto application is at a package dependency level

We can revisit the idea of using target-level dependency information to apply builders in the future.
