### ISSUE TITLE
Decide how users will pick up DDC

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#600]
Two aspects to this question:

1. How will we know to add it to a project? Will users opt in? Will we do it by default with an opt out? Will we just always add the DDC actions and since they are lazy they'll never run unless the user tries to request one of the outputs from the server?
2. How will users pick up a dependency on the `build_compilers` package. Today this is intentionally a separate package from `build_runner` and to use DDC it must be a separate dev dependency. This has a nice purity to it, but might not have the best UX. We could add a dep from `build_runner` so users always pick it up.

**Comment by matanlurey** [comment]
Depends on our UX story I think, ultimately.

* If we have our own entry-point, i.e. `dweb`, then it could opt-in the project automatically.
* If we have the concept of "platforms", a web platform could be mean opt-in.
* If we don't, we could use other signals, such as `web: true` (?) in `pubspec.yaml`.
* If we can't do that, then always including it as a lazy builder seems the right bet for now.

For `build_compilers`:

* We could export from `build_runner`.
* We could just let it be a transitive dependency (pub will whine though?)
* Ultimately if we are generating 99% of the time, does it matter?

For the generated case - are we going to touch the user's `dev_dependencies` @natebosch?

**Comment by natebosch** [comment]
I like the idea of opting in the project based on the entrypoint - we'll need a short term solution before we have that entrypoint. Maybe a `--ddc` argument?

I don't think pub will see the generated file, so we can just depend on it from `build_runner` and pick it up transitively. The minor downsides are:
1. Even packages that don't care about DDC will end up picking it up as a transitive dep
2. When we work on `build_runner` pub might whine that we have a dependency we aren't using.

> For the generated case - are we going to touch the user's `dev_dependencies`

My plan was not to touch `dev_dependencies` automatically. The UX I had in mind is:

```
$ webdev serve
WARNING: You do not have a dev_dependency on build_runner. Please add one at version 0.6.0
```

// edits pubspec.yaml, pub get

```
$ webdev serve
//magic happens
```

I'm very open to alternatives - editing `yaml` programatically is (unfortunately) an unsolved problem in dart.

**Comment by matanlurey** [comment]
> I like the idea of opting in the project based on the entrypoint - we'll need a short term solution before we have that entrypoint. Maybe a `--ddc` argument?

That seems like a fine short-term option.

> I don't think pub will see the generated file, so we can just depend on it from `build_runner` and pick it up transitively. The minor downsides are:
> 1. Even packages that don't care about DDC will end up picking it up as a transitive dep
> 2. When we work on `build_runner` pub might whine that we have a dependency we aren't using.

That seems reasonable then.

>> For the generated case - are we going to touch the user's `dev_dependencies`

> My plan was not to touch `dev_dependencies` automatically. The UX I had in mind is:

> ```
> $ webdev serve
> WARNING: You do not have a dev_dependency on build_runner. Please add one at version 0.6.0
> ```

> I'm very open to alternatives - editing `yaml` programatically is (unfortunately) an unsolved problem in dart.

This seems messy. Now we potentially can conflict with `build_runner`'s dependencies, for example the `analyzer` package, so on and so forth. At least `pub's` current setup is based on the SDK and is shielded a bit.

**Comment by natebosch** [comment]
> This seems messy. Now we potentially can conflict with `build_runner`'s dependencies, for example the `analyzer` package, so on and so forth. At least `pub`'s current setup is based on the SDK and is shielded a bit.

Yes, this scares me a lot.

I think we're in a pretty risky situation today. @jakemac53 might be able to tell me what mistakes I'm making - but I think today we end up being unsafe when it comes to the `analyzer` package. `angular` has a dependency on `analyzer` at a certain version, but when it runs as a `Transformer` it ends up getting the SDK version. We're lucky that `angular` hasn't needed to rely on anything breaking against the version that folks have with their stable SDK.

The advantage of the new model is that we can run with versions that are known to be compatible because they are version solved. The disadvantage is we *have* to version solve with those packages so we can get into really tough upgrade positions.

**Comment by matanlurey** [comment]
At least for the fast-moving analyzer/kernel/and-beyond, I don't know if we can rely on this.

**Comment by natebosch** [comment]
We discussed today having an explicit dev_dependency on `build_compilers` to pick up DDC. We might also rename it to `build_web_compilers` for clarity.
