### ISSUE TITLE
Decide what order BuildActions should run in - builder preference or package preference

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#601]
With our manual build script we have been preferring to apply builders across packages, then move on to the next builder.
For example: https://github.com/dart-lang/angular/blob/6fc43bb170683432f4532877d54abb3ccbc676c6/_tests/tool/build.dart#L76-L80

If we have the builders `[b1, b2]` then `b1` will run everywhere before `b2` runs and can never read any file that *any* `b2` produces - including from dependencies.

This is different from pub and different from bazel. In both of these places builders run in order within a target, but assume they can read any asset produced by later builders in dependencies.

Which behavior should we prefer?

In order to have DDC operate while allowing package cycles we need to use this behavior.

**Comment by natebosch** [comment]
Discussed offline and what we won't do is match behavior of our manual build scripts today. We *don't* want to run a builder on every package, then run the next builder on every package.

We came up with 3 potential strategies:

1. Run every builder on a package, then run every builder on the next package - so package-precedence (sort of like bazel but fails with package cycles).
   This strategy is almost certain to fail for DDC because it can't handle *any* package cycles. This is worse then the pub + angular state today which only restricts cycle on packages using the angular transformer - not transitively.

2. When there is no cycle: run every builder on a package, then run every builder on the next package. When there is a package cycle: switch to the builder-precedence strategy within the cycle.
   In practice this is like ordering by `List<List<Package>>` where the inner list is a strongly connected cycle. This does not match our bazel strategy but can be done automagically and should work for the vast majority of builders

3. Force package cycles to be broken by module config in `build.yaml`, disallow module cycles, and come up with an absolute ordering for modules. Apply builders by module instead of by package.
   This is basically the bazel model, but it requires more static config up front in the case of cycles in the transitive package dependency graph. It is the most likely model to allow us a smooth transition to `dazel` for power users.

I think we're going to work towards 3.

**Comment by jakemac53** [comment]
+1 for 3, its more work now but gives greater power later for users to properly resolve situations.

It is worth noting though that this effectively adds a restriction to packages where they can't have import cycles between packages _at all_. @kevmoo do you think that would be an issue?

**Comment by alorenzen** [comment]
As long as we can detect the cycles and print a useful message, a la blaze, then I don't think this would be an issue.

**Comment by matanlurey** [comment]
+1 for 3 - it's _already_ our requirement internally, and doesn't seem to be a huge blocker.

**Comment by natebosch** [comment]
We smoothly handle these cycles for DDC in pub today. Our pub no-cycle requirement only applies to packages opting in to the Angular Transformer - transitive deps are still allowed to have cycles and work with DDC.

We expect that these cycles in transitive deps are likely to exist, so if we go with option 3 we'd be blocking adoption for some projects until the cycle is resolved.

We expect that these cycles are in packages which don't care about angular or the web. Platform agnostic packages far removed from the end user could be the ones that contain cycles. Giving end the users the ability to solve it manually would inevitably mean introducing config that relies on implementation details from packages you don't own.

We also know that it is not 100% possible to avoid these package level cycles, even as an author of one of the packages in the cycle. Since multiple versions of packages are allowed to have different deps, a cycle could exist for some instances of the version solve but not others. So as a package author I could make no mistakes and still cause a cycle.

We do expect that these cases are rare - but the cases where they pop up are likely *very* painful.

In the short term I think our focus will be:
- Use some magic (option 2 above)
- Detect and possibly warn the users when magic is happening
- See if we can analyze the package ecosystem to determine how often this happens

**Comment by matanlurey** [comment]
Sounds good!
