### ISSUE TITLE
How to handle manual edits to generated files?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#61]
Today we only handle deletes (by regenerating the file), but if you modify them we ignore it. This is because we don't have a way of detecting edits currently, the same modified timestamp logic as regular inputs doesn't work since it is always newer than the asset graph.

It is also unclear what should even be done in this case?

**Comment by matanlurey** [comment]
For AngularDart, this is really interesting, because it could (potentially, with other changes to make `build_runner` or similar a more full-featured system) let us experiment with making small changes to a generated file, but then re-running tests or benchmarks.

**Comment by jakemac53** [comment]
So you actually would prefer it to be left alone then potentially?

**Comment by matanlurey** [comment]
Maybe a flag? i.e. `--retain-user-edits`

**Comment by jakemac53** [comment]
I guess today you could actually get what you want by just making the edit and then not changing any file which would cause that file to be regenerated.

I definitely do not want to get in a situation where we are trying to re-apply user edits to generated files, and not re-generating them based on changes also seems like a bad idea.

**Comment by matanlurey** [comment]
Should we close this @jakemac53? I imagine editing the file as is works fine for now.

**Comment by jakemac53** [comment]
Ya I think we can close this, edits will be bashed over by the next build
but that is fine imo. It is still nice for being able to quickly test out
changes to the generated files.
