### ISSUE TITLE
Dart2js support

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#617]

**Comment by matanlurey** [comment]
I need this for something I'm hacking on, and I'm willing to contribute here!

... but if you're planning on waiting for CFE/Kernel first, then it's alright.

WDUT @jakemac53?

**Comment by jakemac53** [comment]
We don't need to wait on CFE/Kernel I don't think but this is going to be a bit complicated because we want users to be able to switch back and forth between ddc/dart2js with the same build script. We could chat offline or I can add details here for some of our ideas.

**Comment by matanlurey** [comment]
Ah I see.

I was planning on just writing the `Dart2JSBuilder` (similar to the `DartDevCBuilder`), without plumbing it through the rest of the system (and just using this builder directly for my own needs). If that gets you more towards your goal of #617, then I'm happy to contribute it.

If you think you'll need something more clever, I can hold off.

**Comment by matanlurey** [comment]
Though, I could see value in just getting rid of the differentiation in the future:

```dart
abstract class DartJSBuilder implements Builder {
  // DDC
  factory DartJSBuilder() => ...

  // Dart2JS
  factory DartJSBuilder.release() => ...
}
```

... though you might have something more complicated in mind here too :)

**Comment by jakemac53** [comment]
So my current thinking on this is essentially that we should have a single builder which knows how to build both DDC apps (the current DevCompilerBootstrapBuilder) and Dart2js apps.

You would switch between the two modes based on configuration - and could override the current setting with a flag. This would use the standard configuration strategy based on `BuilderOption`s that @natebosch is are starting to add support for now.

Whenever the configuration for a builder changes (we would need to serialize the previous configuration as a part of the asset graph), we would invalidate all the outputs of that builder.

This has some nice properties:

- All the ddc modules are always a part of the build graph, since they are built with a separate builder. 
  - No penalty for switching back and forth between compilers, ddc modules are compiled lazily (so not at all in dart2js mode) and previous cached versions will still exist when you switch back.
- It is only the bootstrap files at the top (*.dart.js and related) that get invalidated when you switch compilers.
- Users can configure their default compilers and easily override with a flag for one-off situations.

**Comment by matanlurey** [comment]
I like all of this!

Only one question:

> Users can configure their default compilers and easily override with a flag for one-off situations.

How do we intend to deal with a package like so:

```
web/
  main.dart     // <-- Compile me with Dart2JS
test/
  app_test.dart // <-- Compile and run me with DDC
```

**Comment by jakemac53** [comment]
So the tldr; is essentially that if you wanted to make some progress towards this in the meantime I would recommend changing the `DevCompilerBootstrapBuilder` to a `DartToJsBuilder` with two modes (ddc and dart2js). For now you would have to manually configure your build script with a certain mode (maybe via a different constructor as you suggested, but both need to end up giving you an instance of the same exact type today or you will have issues).

**Comment by jakemac53** [comment]
> How do we intend to deal with a package like so:
> 
> web/
>   main.dart     // <-- Compile me with Dart2JS
> test/
>   app_test.dart // <-- Compile and run me with DDC

Good question, I think you would probably have two separate builder applications in your build.yaml - one with a glob like `web/**.dart` and one with a glob like `test/**.dart`.

**Comment by matanlurey** [comment]
@jakemac53:

> So the tldr; is essentially that if you wanted to make some progress towards this in the meantime I would recommend changing the `DevCompilerBootstrapBuilder` to a `DartToJsBuilder` with two modes (ddc and dart2js).

Sg. I may work a bit on this today.

> For now you would have to manually configure your build script with a certain mode (maybe via a different constructor as you suggested, but both need to end up giving you an instance of the same exact type today or you will have issues).

Yeah, I see you use `.runtimeType` as a canonical ID (though I'm not sure it's safe to?)

In either case, I can either `@override` it (surprisingly legal) or figure out another method.

>> How do we intend to deal with a package like so:
>>
>> ```
>> web/
>>   main.dart     // <-- Compile me with Dart2JS
>> test/
>>   app_test.dart // <-- Compile and run me with DDC
>> ```

> Good question, I think you would probably have two separate builder applications in your build.yaml - one with a glob like `web/**.dart` and one with a glob like `test/**.dart`, and they would each set different options for the builder.

Wait, so the _user_ will need to write this part, right? Similar to `transformers: `?

I imagine this is going to be the common case for AngularDart packages that want to write tests, so post-M0 it would be nice for this to be as easy/little configuration as possible. But not too important for M0.

**Comment by jakemac53** [comment]
> Yeah, I see you use .runtimeType as a canonical ID (though I'm not sure it's safe to?)
> 
> In either case, I can either @override it (surprisingly legal) or figure out another method.

This is really just a best effort sort of thing - its not designed to be perfect. Also wtf you can override runtimeType????

> Wait, so the user will need to write this part, right? Similar to transformers:?

If they want to override whatever the default is, yes.

> I imagine this is going to be the common case for AngularDart packages that want to write tests, so post-M0 it would be nice for this to be as easy/little configuration as possible. But not too important for M0.

I think for development most people would want ddc for all directories, and that makes sense to be the default. Then if you want to deploy or test the dart2js mode you would add that command line flag, or maybe we default that flag when you go through `webdev deploy` or whatever top level deployment command we end up with.

**Comment by matanlurey** [comment]
> Then if you want to deploy or test the dart2js mode you would add that command line flag, or maybe we default that flag when you go through `webdev deploy` or whatever top level deployment command we end up with.

Ah that makes sense, good point.

**Comment by matanlurey** [comment]
I'm going to take this task to get started, but feel free to bump me if you need it sooner.

**Comment by matanlurey** [comment]
I probably won't complete this week, so unassigning for now.
