### ISSUE TITLE
Consider changing `needsUpdate` to a `state` field which is an enum of possible states

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#622]
This should allow us to avoid issues like the one discovered [here](https://github.com/dart-lang/build/pull/621)

**Comment by jakemac53** [comment]
We would also want to guard against updating any of the fields unless the node is in a certain state, etc.

**Comment by natebosch** [comment]
So would the states `wasOutput` and `wasNotOutput` imply it no longer needs an update?

**Comment by jakemac53** [comment]
I would leave the `wasOutput` field as is - other than we could potentially throw if you try and read it when the node is not in a fully updated state.

**Comment by jakemac53** [comment]
We might not really need an enum - I am not sure if we need more than 2 states. The real win would be enforcing that you can't modify any of the fields unless `needsUpdate == false`.

**Comment by jakemac53** [comment]
For clarity though it might make sense to have 3 states:

- Up to date
- Needs update
- Currently building

**Comment by natebosch** [comment]
Yeah I'm not sure if we'd be able to do anything with currentlyBuilding.

Disallowing updates would be interesting...

**Comment by jakemac53** [comment]
I think its worth doing this just for the glob case, we can have a state enum as follows:

```
enum NodeState {
  upToDate,
  mayNeedUpdate,
  definitelyNeedsUpdate,
}
```

**Comment by jakemac53** [comment]
cc @natebosch how do you feel about those names?

**Comment by natebosch** [comment]
synced offline. The other option we could at some point investigate is a synthetic asset node representing the result of a glob - we could then invalidate it's digest and have better cohesiveness with how we handle other changes. That has other costs that the enum don't have so I think we should go with the enum you've proposed.
