### ISSUE TITLE
Better asset invalidation with globs

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#624]
Today if a node has any glob dependencies, we need to skip the inputs hash check and just assume it needs an update. We could instead have a flag like `globsWereUpdated` or a special state to indicate the globs were updated as proposed in https://github.com/dart-lang/build/issues/622.

**Comment by natebosch** [comment]
We've fixed this, we have an extra understanding of how things are invalidated based on globs vs input hashes.

**Comment by natebosch** [comment]
Fixed by https://github.com/dart-lang/build/pull/1037
