### ISSUE TITLE
Decide how to order the 'auto' builders from multiple packages

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#626]
As a for instance, Sass should always run before angular. If both of these were applied automatically, how would we know to run sass first?

If a package exposes multiple builders (not builderFactories), we need to pick an order for those as well. In most cases this likely shouldn't matter since ordering dependencies should be indicated by ordering the builderFactories within a logical builder.

**Comment by natebosch** [comment]
https://github.com/dart-lang/build/pull/661 started on this.

**Comment by jakemac53** [comment]
Should we just close this and re-open if we need additional config? I don't think we have plans to do anything extra right now.
