### ISSUE TITLE
Add some testing for the `createBuildActions` method

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#627]
Especially once we start handling modules and manual config this method is going to get a lot more complex.

We should test the PackageFilters and the method itself.

**Comment by jakemac53** [comment]
@natebosch I don't think we even expose that any more, but we probably do need some other tests related to PackageFilters etc still?

**Comment by natebosch** [comment]
We've got some tests: https://github.com/dart-lang/build/blob/c0846dc32fb636c5d8b6fe4dcdb438a865ca9b39/build_runner_core/test/package_graph/apply_builders_test.dart
