### ISSUE TITLE
Something like Bazel's "extra actions"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#650]
Source: https://docs.bazel.build/versions/master/be/extra-actions.html

I've been thinking of different ways to re-implement something like the `linter` package (i.e. closer to error prone for Java) without re-implementing lots of the already neat parts of `build_runner` and the `build` infrastructure.

i.e. do something like:

```dart
abstract class Linter extends Builder {
  List<SourceSpan> lint(LibraryElement library);
}
```

... where `.dart` files output a `.lint` file in a "map"-like process, and another tool in a "reduce"-like process can determine what the outcome of the lints mean (fail a build, use a web-hook with github to display a message).

Does this sound crazy? Is `build_runner` already setup enough to handle this without needing anything special (i.e. use `writeToCache: true` and a custom build script)? Already emitting summaries through `build_compilers` and using that for incremental analysis is likely much faster than use `dartanalyzer` or `flutter analyze` due to caching, so I'm wondering if we can consolidate infrastructures a bit.

We _would_ need access to function bodies (of at least primary sources), however.

/cc @mk13 @MichaelRFairhurst for FYI.

**Comment by natebosch** [comment]
I think we probably have most of what we need in `build_runner`. We can output the `.lint` files and then use a [PackageBuilder](https://github.com/dart-lang/build/blob/c5d3517e412e61ac31570666688d9e47ff1f0131/build_runner/lib/src/package_builder/package_builder.dart#L9) which finds `**/*.lint` assets and does processing to output some other file. If it wants to take an external action too I don't see any reason that wouldn't work.

Would you want it to always run, or only run when the `.lint` files have changed?

**Comment by matanlurey** [comment]
Not sure yet, just thinking out loud :)

**Comment by jakemac53** [comment]
Ya I don't think much if anything would need to be added to `build_runner` to support this, if you are willing to manage it as a separate `build.dart` script.

We could eventually make this a part of the main build when we implement something like  https://github.com/dart-lang/build/issues/539 which would allow you to make these be optional build artifacts which would be built only if specifically requested.

**Comment by matanlurey** [comment]
Ok great. We might need this sooner rather than later.

One big difference between this method and what is needed for linting/refactoring is that you need reliable access to the AST node - I'm not sure `computeNode` is enough (or consistent enough), though maybe @MichaelRFairhurst can help explain that to me.

How reasonable would it be to add AST nodes/parsing to `BuildStep`?

**Comment by matanlurey** [comment]
I think we have this resolved for now, I'll re-open if we need additional help.
