### ISSUE TITLE
e2e-example doesn't work on Windows machine

### ISSUE THREAD

**Issue by yury-yufimov** [dart-lang/build#651]
build_runner has some bugs for running on Windows machine. When I try to execute e2e-example's build.dart, I receive following error:
```
[WARNING] BuildScriptUpdates: e2e_example|../../../../../C:/projects/tmp/build/e2e_example/tool/build.dart was not found in the asset graph, incremental builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
```
Some investigation shows, that
https://github.com/dart-lang/build/blob/52801f53655bcb0b6c66f8c6af8c881b6b4d1078/build_runner/lib/src/changes/build_script_updates.dart#L70
receives uri with path like "/C:/projects/tmp/build/e2e_example/tool/build.dart" (starting with slash!), which can't be handled correctly. Removing of this slash locally fixes the problem, but I think it needs more complex investigation for correct fix.

**Comment by matanlurey** [comment]
We realistically need some sort of windows-based testing for this repository (sorry, most testing and developing has been on unix - OSX, Linux - machines). Let's keep this issue open for tracking this specific fixes.

**Comment by jakemac53** [comment]
We also need to fix up the tests so they will run on windows but we can track that separately. I know today a lot of them fail because the tests expect some linux specific behavior.
