### ISSUE TITLE
Stripping section from `lib/` modules in addition to others

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#664]
Looks like we intended to only match the modules outside of `lib/` but since we're ignore the result of the `where` that isn't what is happening.

We should probably add a test for this.
https://github.com/dart-lang/build/compare/build-dir#diff-bd617c616175fce78564a34518a068ceR68

**Comment by jakemac53** [comment]
This is fixed in master now, but there aren't tests around it specifically so I am leaving it open for now
