### ISSUE TITLE
Throw if `AssetId` contains invalid characters.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#673]
Such as, you know, not a `/`.

See https://github.com/dart-lang/angular/issues/723#issuecomment-348359855 for background.

Breaking change-ish... but I don't know if it was ever usable without anyway?

**Comment by natebosch** [comment]
Hmm. This might not be straightforward.

I don't think there is a consistent set of characters to look for between Windows and Linux.

**Comment by matanlurey** [comment]
Could `\` be enough to trigger a failure here?

**Comment by natebosch** [comment]
`\` is a legal character in a filename on linux, and a legal import in Dart (on linux?).

```dart
// Legal import to a file in the same directory with the name `foo\bar.dart`
import 'foo\\bar.dart';
```

**Comment by matanlurey** [comment]
Alright, happy to close for now. Maybe just better windows coverage is what we really need.
