### ISSUE TITLE
BuilderOptions can't change buildExtensions

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#683]
Example use case: angular_components want SASS to output `.scss.css` while other packages want it to output `.css`. We have not solution for this with config driven generation.

In bazel this is handled by using custom skylark code, but as we look to revisit dazel we don't have a solution for package authors providing us custom skylark.

We have a few options:
1. Disallow varying the build extensions by config. angular_components can either switch to `.css`, or the SASS package can vend two builders - one which uses `.css` and one which uses `.scss.css` and angular_components can choose to apply the latter and disable the former.
1. Write a configuration language that allows us to understand this statically and be able to use it in both bazel and build_runner. IMO the complexity of this makes it a non-option.
1. Allow this in build_runner and make it clear that builders which use the flexibility won't work in bazel. This let's us punt on the problem and we can eventually allow this in bazel by solving the custom skylark problem. The downside is that any package which takes advantage of this will be blocked from using bazel until we solve that problem - and anything that depends on them will be blocked too.

**Comment by natebosch** [comment]
@nshahan - would it be possible to switch `angular_components` to use the standard extension?

**Comment by jakemac53** [comment]
I am in favor of simply disallowing it for now if possible

**Comment by natebosch** [comment]
Chatted with @nshahan about this.
There is some annoying stuff about switching this in angular_components:
- It's (another) divergence between the internal and external versions of the source. Switching the extension internally is unlikely
- It's a breaking change since some packages that depend on angular_components might refer to these files directly

That said, It's hard to justify adding the hole in compatibility or the complexity of configuration. If we can find 1 or 2 other use cases for Builders which want to have similar flexibility (or existing Transformers which already do) we can revisit one of the other options.

**Comment by nshahan** [comment]
It sounds like some form of the first option will be the way forward for the foreseeable future. If sass_builder were to vend two builders and angular_components opted into the non-default `.scss.css` builder would that impact any packages that depend on angular_components and use the same builder.

In other words, would a custom builder choice in one package have any ramifications on dependencies that use the same builder themselves?

**Comment by jakemac53** [comment]
It won't have an affect on other packages - but the sass_builder package would need to make some choices about how it configures its builders (specifically, whether or not one would be automatically applied or not). If one is auto-applied then it would have to be disabled for users who opt into the other one.

**Comment by nshahan** [comment]
I have another use case for configurable output extensions. I would like to write simple builder that generates files from mustache templates. It would be nice to create a single mustache builder that has a configurable output extension rather than a separate builder for each file type that you would want to output.

**Comment by natebosch** [comment]
We can share a `Builder` class implementation, what we'd need to vary is the `builder:` section of `build.yaml` and the builder factory we use to create it.

Do you think this can be implemented where it is 100% driven by BuilderOptions?

**Comment by nshahan** [comment]
After more offline conversations with @natebosch I do think there is a path forward to work with the given restrictions. 

The sass_builder package can vend the standard builder via a factory that always constructs the builder with the `.css` output extension. The angular_components package can opt out of that standard builder (in whatever form that takes) and have it's own builder factory that uses the custom `.scss.css` extension.

This same pattern can be applied to other hypothetical builders like the mustache use case. Users would just need to write a builder factories for the desired output extensions in their package.

**Comment by natebosch** [comment]
I'm going to close this for now as not planned.

I can think of a few mechanisms by which we could allow consuming package configuration to allow this, but the big drawbacks are:
- Complexity of the solution to satisfy a use case which we only see a single example of, and which has a relatively low barrier workaround
- A general solution has a high risk of making Builder consumption very tightly coupled with the Builder implementation. For instance if we allow overriding extensions in general it could make it hard to change extensions of intermediate files that the user doesn't care about, or it could make it hard to rely on knowing what Assets can be read by a Builder in a later step.

**Comment by natebosch** [comment]
We're still open to hearing new concrete use cases though - if we find more specific examples we can revisit the idea of allowing this based on config.

**Comment by natebosch** [comment]
package:intl offers us a new concrete use case to discuss

The outputs there depend on the locales you have enabled.

**Comment by kevmoo** [comment]
Another example from `build_version`. Folks would like to be able to specify where `version.dart` goes. At the moment it's hard-wired for `lib/src/version.dart`. Folks would like that changed.

**Comment by simolus3** [comment]
Now that we support directory moves with build extensions, I think there's another reason to revisit this. A lot of users were interested in generating files into a fixed directory (e.g. `lib/src/generated`). On the other hand, some users may prefer relative files or may want to use a different directory for generated files.

One solution that I had in mind would be to make builder outputs configurable in a `TargetBuilderConfig`. By default, builders would use the extensions declared in their definition. When extensions are overridden for a target, those are used instead. The resolved extensions would be made available in `BuilderConfig`, and builders would be encouraged to use those extensions in their `buildExtensions` getter. As we now have an [`allowedOutputs`](https://pub.dev/documentation/build/latest/build/BuildStep/allowedOutputs.html) getter on `BuildSteps`, most builders could refer to that when computing output ids.

For example, a build config could look like this:

```yaml
targets:
  $default:
    # Make all shared builders generate code into lib/src/generated
    source_gen|combiningBuilder:
      build_extensions:
        'lib/{{dir}}/{{file}}.dart': ['lib/src/generated/{{dir}}/{{file}}.g.dart']
    # Use a custom output location for build_version
    build_version:
      build_extensions:
        '^pubspec.yaml': ['lib/my/custom/path/for/the/generated/version.dart']
    # As a builder could iterate over expected outputs, we can also use this to declare enabled languages for
    # an i18n builder
    i18n:
      build_extensions:
        '^assets/messages.yaml':
          - 'lib/src/translations/en.dart'
          - 'lib/src/translations/de.dart'
          - 'lib/src/translations/es.dart'
``` 

As build phases are computed based on the target graph, we should have enough information here.

**Comment by jakemac53** [comment]
This has me wondering a bit whether we should actually just allow configuring it however builders choose through their own builder config (as opposed to an explicit setting for it).

We already track builder options as a node, and will invalidate the builders configured with that. We could track the build extensions configuration we got from the builder on that node as well. So I don't think we need an explicit configuration here.

Allowing the builder authors to choose how you configure the extensions probably makes it easier for them to determine their outputs, and also makes things less error prone in general. Asking users to copy the entire build extensions config (and tweak output dirs) seems error prone to me. For instance as a builder you now wouldn't be able to tweak your build extensions at all (even add new hidden files), without doing a breaking change.

When the build extensions do change, in either case, we probably should rebuild from scratch that entire portion of the asset graph. Delete completely all the primary outputs for the previous build extensions, (and all their outputs too), and then re-build the list of outputs with the new extensions. So we will need to track the previous config to be able to compare it.

**Comment by natebosch** [comment]
My biggest concern is that we don't have a plan for supporting this in bazel and if any third party builders decide to take advantage of this we'd be unable to use them with bazel.

**Comment by simolus3** [comment]
Would it be possible to implement statically-defined extensions (individual to a builder and a target) in bazel? I see how they are more error prone than allowing this as regular build options, but if that's what can be supported across all implementations it might be worth it?

> For instance as a builder you now wouldn't be able to tweak your build extensions at all (even add new hidden files), without doing a breaking change.

All outputs of a builder are either hidden or generated to source, right? So adding hidden files would typically happen through another builder that end users probably don't care about. Not being able to change build extensions without doing a breaking change is a strong point, but I assume most public builders rarely change outputs at all.

A builder would effectively be able to opt-out of this by checking the desired build extensions reported in the `BuildConfig` and throwing an exception if they don't match what's expected.

**Comment by natebosch** [comment]
> Would it be possible to implement statically-defined extensions (individual to a builder and a target) in bazel?

Yeah, I think if we design it so that you can only override the entire extensions map it could work.

**Comment by jakemac53** [comment]
I am pretty opposed to overriding the whole map here. It will be quite difficult as a builder author to understand what the heck to do with the build extensions I think? In the extremely trivial case (one input, one output) it might be ok, but it gets very weird very fast for anything non-trivial.

As far as bazel goes we could require the static configuration _in addition to_ the builder configuration, if we really had to.

**Comment by jakemac53** [comment]
Doing a full clean build after extensions change would probably be fine, yes.

Do things just work in watch mode today as well as between manual builds?

**Comment by simolus3** [comment]
From a quick manual test with https://github.com/kevmoo/build_version/pull/21 it looks like it handles that gracefully.

**Comment by jakemac53** [comment]
Interesting, so do we actually need to change anything at all here? Does this "just work" today even though it wasn't really intended to?

**Comment by simolus3** [comment]
I was trying to store previous build extensions in the asset graph, and then halfway through I realized that we already support invalidating the build here lol. From https://github.com/dart-lang/build/issues/3156#issuecomment-889247604, I assumed it wouldn't work but from my limited manual testing it looks like all situations are handled as I'd expect them to.

I can open a PR to add integration tests for this, but if they work I think we can just declare this as working as intended.

**Comment by jakemac53** [comment]
I am not sure what the ramifications of having the build extensions not match those in the `build.yaml` are either... this sort of implies we could completely drop them from the build.yaml potentially. I can't remember what actually reads those any more.

**Comment by natebosch** [comment]
> this sort of implies we could completely drop them from the build.yaml potentially. I can't remember what actually reads those any more.

At this point just the `doctor` output I think?

At this point they only exist in `build.yaml` to reinforce that they need to be static. If we're dropping that push for compatibility with bazel we could consider removing them entirely.

**Comment by jakemac53** [comment]
It looks like we also use this for `required_input` ordering. So that could be problematic.
