### ISSUE TITLE
Add resolveSources (plural) to pkg/build_test

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#709]
https://github.com/dart-lang/build/blob/ad197837da3f45e49b9c1079447392f575b2a734/build_test/lib/src/resolve_source.dart#L56-L58

This is needed to write tests that will assume multiple on-disk files, instead of just a single one.

A simple `Map<String, String>` probably suffices.

/cc @natebosch PTAL. If agreed I'd like to add this asap for Angular.

**Comment by natebosch** [comment]
SGTM. We should use the same format for the keys as we do in other places: `package_name|path`.

Do we want to deprecate and remove `resolveSource` or keep it as a special case of `resolveSources({inputId: inputSource}, ...)`?

**Comment by matanlurey** [comment]
I honestly like it for the simplified case, and it would be a good candidate to just be short-hand for `{inputId: inputSource}`. Does that make sense?

**Comment by natebosch** [comment]
works for me.

**Comment by matanlurey** [comment]
One snag, currently you can "just use the real asset" by not providing `inputSource`.

That makes `Map<String, String>` a little weird, because it's not clear how to express "provide this asset, but use the real on-disk source". I use this feature quite a bit for things like Angular.

Alternatives:

1. Provide a more typed `Map<AssetId, AssetContents>`, where you can do:

```dart
resolveSources({
  new AssetId('angular', 'lib/angular.dart'): AssetContents.useAssetReader,
  new AssetId('test_lib', 'lib/test_lib.dart'): new AssetContents(r'''
    import 'package:angular/angular.dart';

    ...
  '''),
})
``` 

2. Add some sort of enum-like string to indicate "use real source":

```dart
resolveSources({
  'angular|lib/angular.dart': useAssetReader /* top-level const String */ ,
  'test_lib|lib/test_lib.dart': r''' ... ''',
})
```

3. Start pivoting to some `test_descriptor`-based extension/API instead.

**Comment by natebosch** [comment]
I like option 2. Since this is test code I generally favor terseness over closing type holes.

**Comment by matanlurey** [comment]
Sounds good. Easy enough to pivot if this becomes some super-used package/pattern.
