### ISSUE TITLE
Proposal: Move the `digest` method to the `AssetReader` abstract class

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#710]
cc @natebosch wdyt?

Today in `build_runner` we have a `DigestAssetReader` class which is used internally for computing digests. It adds the `Future<Digest> digest(AssetId id)` method, which today is used primarily for tracking changes to files.

I would like to move that to the abstract `AssetReader` class - including a default implementation of roughly `md5.convert(await readAsBytes(id))`.

## Why?

Builders could make use of this - specifically any Builder using the bazel worker protocol to talk to a subprocess can use it to efficiently provide a list of inputs and their digests. The analyzer cli today will use that if available to optimize loading of only the changed summaries, and ddc should likely be updated to do the same.

`Resource`s could also use this to do other forms of smart caching/invalidation. For instance the `ScratchSpace` package could use it to do less copying, today it starts over at the start of each build since it doesn't have efficient access to this information.

## Risks

The main risk here is we are opening the door a bit to non-hermetic builds. You have to trust anybody using these Digests to do the right thing. Bazel already does allow this though - and I think it is a reasonable tradeoff.

## When?

I would like to roll this into the other breaking changes in v0.7.0.

**Comment by natebosch** [comment]
Do we anticipate other implementations than `md5.convert(await readAsBytes(id))`?

> I would like to roll this into the other breaking changes in v0.7.0.

This would be breaking in `package:build` v0.12.0, not breaking in `build_runner`

**Comment by matanlurey** [comment]
This sounds reasonable :).

Ultimately we might want tooling to help users find if builds are non-hemertic (imagine a "checked" mode for build_runner), similar to the tooling @davidmorgan build around Bazel internally, but this sounds good to me!

**Comment by jakemac53** [comment]
> Do we anticipate other implementations than md5.convert(await readAsBytes(id))?

Yes - in bazel_codegen we should use the input hashes provided by blaze when in worker mode.

**Comment by jakemac53** [comment]
> This would be breaking in package:build v0.12.0, not breaking in build_runner

Oh yes this would additionally be a breaking change in build_runner though because we expose `DigestAssetReader` today.

**Comment by natebosch** [comment]
It would be good to have a better idea of what benefit we'll see. I think this should be fine for us, my only concern as we discussed offline is that this increases the surface area of `BuildStep` with an 'experts only' method which is easy to misuse and will require a lot of cautionary documentation.

**Comment by jakemac53** [comment]
> It would be good to have a better idea of what benefit we'll see.

Agreed, when I get a chance I will see if I can evaluate the performance. This is quite difficult to do with the lazy nature of many builds but I think its worth validating before we proceed.

**Comment by natebosch** [comment]
We had the wrong issue link. This has not been implemented.

**Comment by jakemac53** [comment]
Fyi, I have implemented this and confirmed a >10% speedup for angular_components_example, when combined with a few other changes to optimize large number of requests for digests.

As a result I think this is definitely worth moving forward with, we should see an additional speedup if we make dartdevc take advantage of these input hashes as well.
