### ISSUE TITLE
Provide test helpers to ensure build-users commit files w/ build already run

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#716]
See https://github.com/dart-lang/json_serializable/blob/example/json_serializable/test/ensure_build_test.dart

Maybe a no-opt build mode that (instead of writing files) makes sure that the target file exists and has the content that would be written?

Or just an easy way to run build and see changed files?

**Comment by natebosch** [comment]
Along with #718 what about parsing an arg `--assert-up-to-date` or similar and `exit(1)` if the outputs are stale?

**Comment by kevmoo** [comment]
I really don't like calling `exit(...)` except for the top-most script.

Or we just set `exitCode` and we're super clear about that...

**Comment by natebosch** [comment]
we could have `run` return a `Future` that completes with an error code?

**Comment by kevmoo** [comment]
...sure?

`exitCode = await run(...)`

Not too bad...

**Comment by jakemac53** [comment]
in the case of watch mode it isn't clear what the exit code should be though.... it could be based on the final build I guess?

**Comment by kevmoo** [comment]
> in the case of watch mode it isn't clear what the exit code should be though.... it could be based on the final build I guess?

watch ends on ctrl-c or crash, right?

Don't you send negative exit codes for signals?

I'd guess watch would never end in 0

**Comment by jakemac53** [comment]
> I'd guess watch would never end in 0

I think today it we exit with a 0 or 2 if you ctrl-c - 0 if you let it properly shut down and a 2 if you hit ctrl-c more than once and we shut down in the middle of a build.

Maybe neither of those are really correct though.

**Comment by matanlurey** [comment]
Is this really important right now @kevmoo?

**Comment by jakemac53** [comment]
This is important for users that are committing their generated files, and it should be relatively trivial to expose.

**Comment by kevmoo** [comment]
> Is this really important right now @kevmoo? json-serializable is not on our OKRs.

Not at all. Just filing issues as I find problems.

We've now copied it a third time, though - https://github.com/dart-lang/pub-dartlang-dart/commit/7966dc3fd08e847e7470444db5f0685d5754003c

**Comment by nex3** [comment]
I would also love to see an API that just indicates whether the current output is up-to-date.

**Comment by kevmoo** [comment]
Return an exit code of 78 if things aren't up-to-date.

Bonus points for logging the files that changed...

```dart
/// Something was found in an unconfigured or misconfigured state.
static const config = const ExitCode._(78, 'config');
```

**Comment by kevmoo** [comment]
FYI: running on my own package for this - https://github.com/kevmoo/build_verify

**Comment by jakemac53** [comment]
Closing in favor of the build_verify package
