### ISSUE TITLE
Proposal: create magic placeholder files to replace PackageBuilder functionality

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#741]
The idea is to materialize synthetic assets that can be used as placeholder files by any builder. They will exist under the valid top level directories of all packages, and can be used as primary inputs, but most likely would throw if you try to read them (or possibly are just empty).

You can use `buildExtensions` normally, with the full path to the placeholder as the input extension, and the full path to the output as the output extension. This allows you to write files anywhere under the same top level directory as the placeholder.

For the initial implementation we will probably just support a single placeholder in the top level `lib` folder but may expand support if requested.

Current ideas for the placeholder file name/path are:

- `lib/$$`
  - You could use `$$` or `lib/$$` as your input extension this way.
- `$lib/$`
  - If we did this we would probably require the full path with the leading `$` as an indication that this is a placeholder file.

cc @nshahan

**Comment by natebosch** [comment]
> Current ideas for the placeholder file name/path are:

I like `$lib$` as the input extension, and we create a synthetic asset at `lib/$lib$`.

**Comment by jakemac53** [comment]
> I like $lib$ as the input extension, and we create a synthetic asset at lib/$lib$.

Would we allow matching on just `$` as the input extension?

**Comment by natebosch** [comment]
Once we want to support matching in any top level dir I think we'd add a new placeholder. `$$` and automatically create `lib/$$`, `web/$$`, `bin/$$`, `test/$$`, ...

If we have use cases for targeting specifically other (common) top-level dirs we could also add `$web$` and others.

**Comment by jakemac53** [comment]
What does `lib/$lib$` buy us in the short term over just `lib/$$` then?

**Comment by natebosch** [comment]
It gives use the ability to target that specific directory without having to worry about what it means to include a directory in the `inputExtension`.

For instance, what if they set a buildExtensions of `{r'lib/$$': [r'web/some-not-lib.dart']}` - if we don't already disallow this we probably want to disallow ever writing a file to a different directory than the primary input. And if we don't allow that it's safer to never allow a directory to be part of the input extension.

**Comment by jakemac53** [comment]
I think all that really matters is that we don't allow writing to an invalid output directory - which I am pretty sure we do today? If not we could easily add that. Either way it doesn't prevent somebody from using `{r'lib/$lib$': [r'web/com-not-lib.dart']}`...

I don't think there would be anything inherently _wrong_ with `{r'lib/$$': [r'web/some-not-lib.dart']}` in any case - as long as `web` is a valid output directory.

**Comment by natebosch** [comment]
Launching with `lib/$$` would also mean it's potentially breaking to start putting `$$` assets anywhere other than `lib` because Builders would start running on inputs they don't want. If we don't plan on launching with the semantics of "There will be a `$$` in every top level directory" (and I don't think it's worth doing that work yet) then I don't think we should use the same placeholder we'd use if we had those semantics.

**Comment by jakemac53** [comment]
I will start with `lib/$lib$`, we can keep that working indefinitely without significant technical debt and add `$$` later if desired.

**Comment by nshahan** [comment]
In the gallery generator use case where I would use this, I need to generate files in the web/ directory. At this time I create multiple placeholder files there so I can rely on them in my builders.

**Comment by natebosch** [comment]
Chatted with @nshahan about this. We can start with both `lib/$lib$` and `web/$web$`. We don't (yet) need something that runs in each top-level directory, and in this case the Builder targeting each one will be different so it first the use case better to have a special placeholder for each than to implement the `$$` general solution.

**Comment by jakemac53** [comment]
Adding in `test/$test$` as well

**Comment by natebosch** [comment]
Fixed by https://github.com/dart-lang/build/pull/746 but we had the wrong issue there.
