### ISSUE TITLE
Make it easy to build for AppEngine / Firebase Hosting / etc.

### ISSUE THREAD

**Issue by filiph** [dart-lang/build#753]
Common scenario: I have my Dart frontend app and some — let's say — AppEngine backend. Imagine a web app that accesses URLs like `/data.json?q=foo` on its own server. Those JSONs aren't static so you need to have the AppEngine dev server running.

Currently, I need to do the following for every dev cycle:

* Build the Dart app to `build/`
* Sync the generated files to something like `server/static/`.
* Check changes on AppEngine's dev server.

@matanlurey, @yjbanov and I just talked about this. Maybe it's possible to create a simple copying build step that does the first two things for you. Even better if we can have an "app engine step" and "firebase hosting step" that Just Work™.

**Comment by yjbanov** [comment]
> Currently, I need to do the following for every dev cycle:

Or worse, run `pub serve` and `dev_appserver.py` simultaneously and put a proxy in-between, that magically routes between pub and appengine, like we do in the [Flutter devicelab](https://github.com/flutter/cocoon/blob/master/app/bin/dev_server.dart).

**Comment by matanlurey** [comment]
I talked to @filiph and @yjbanov offline, and this would be an awesome demo of how replacing pub serve with this tool makes even non-codegen related tasks much easier and hackable. Would love some input from @jakemac53 @natebosch @kevmoo - I can work with interested folks on a demo if we agree this is good to have/do.

**Comment by natebosch** [comment]
> - Build the Dart app to `build/`

We have experimental support for this: https://github.com/dart-lang/build/pull/667 Expect it to get hardened and leave experimental status after we can get some other people trying it out and polish it some.

> - Sync the generated files to something like `server/static/`

I'm not sure I understand. Is this something under `build/`? That's where generated files will go with the above.

> - Check changes on AppEngine's dev server

I don't understand what this means.

**Comment by matanlurey** [comment]
>> - Build the Dart app to `build/`

We have experimental support for this: https://github.com/dart-lang/build/pull/667 Expect it to get hardened and leave experimental status after we can get some other people trying it out and polish it some.

Nice. Yes, we could piggy-back here, but it would be nice to make this part of the watch process eventually - for example for every successful build to "mock deploy" to another directory on disk.

>> - Sync the generated files to something like `server/static/`

> I'm not sure I understand. Is this something under `build/`? That's where generated files will go with the above.

No, in fact it might be in another directory entirely:

```
my_app/
  my_app_server/
   static/
  my_app_dart_web/
    lib/
```

>> - Check changes on AppEngine's dev server

> I don't understand what this means.

@filiph means use Firebase/AppEngine as the HTTP server, where the `static` folder (see example above) has a copy of the generated outputs.

**Comment by jakemac53** [comment]
I think for a good workflow here you don't really want the solution in https://github.com/dart-lang/build/pull/667 long term because it isn't incremental. We can work on something more incremental though going forward.

**Comment by matanlurey** [comment]
I think #667 is still much better than having to hand-write a MAKEFILE or dig files out yourself, so I think @filiph and @yjbanov could start there, and we could talk about what the best strategy is for a more automated tool after the initial MVP?

**Comment by jakemac53** [comment]
sure - we could also add a mode which uses symlinks only instead of copying files which might work for this use case and be faster

**Comment by natebosch** [comment]
Sounds like we maybe want to just generalize #667 
- make it work for `watch`
- make it more incremental
- Support some other 'format' for where to stick files

All of these seem pretty doable once we find the time to polish this use case.

**Comment by filiph** [comment]
Thanks! 

By #667, do you mean the `output-dir` flag? It looks like that flag [deletes the output directory](https://github.com/dart-lang/build/pull/667/files#diff-dea9a5019990f156b31f40c2c9b01ea9R51) before writing to it, which might be a problem. (For example, you might want to have assets checked in at `my_app/my_app_server/static/` instead of always copying them over from `my_app/my_app_dart_web/lib/`.)

As Nate says, I think this would need to work with `watch` for this to significantly improve the dev cycle.

The other stuff, like making it more incremental, is nice-to-have in context of a small-ish external web app.

**Comment by natebosch** [comment]
> It looks like that flag deletes the output directory before writing to it, which might be a problem.

Not deleting the output directory is what we mean when we say "more incremental". We'd only delete files that are no longer generated.

**Comment by jakemac53** [comment]
Ya, the main issue is making sure we can clean up the dir appropriately - even if you manually delete your `.dart_tool` dir or we have to throw away the asset graph due to a breaking change in the format etc.

The current script bashes away the whole directory to sidestep those issues (it is primarily meant for running tests on Travis with --precompiled)

**Comment by jakemac53** [comment]
I was thinking about this a bit and I have the following simple-ish proposal to allow incremental writing of files to a directory which may contain other pre-existing sources:

1. Create an extra manifest file at the top level of the merged output directory, (`build_outputs.manifest` or similar). This would be a very simple format with the asset ids or possibly file paths for all files that have previously been written to that directory as well as their serialized hashes.
2. After each build we would update the output folder by:
    - reading the old manifest into memory
    - creating a new manifest in memory
    - update any files whose hashes changed
    - deleting any files that no longer exist
    - copying in any new files
    - replacing the old manifest on disk with the new one

**Comment by matanlurey** [comment]
@jakemac53 @filiph With the newest features and `-o`, is this closable?

**Comment by jakemac53** [comment]
Yes, we have actually implemented the manifest file as well. It does not do an incremental update today but it will only remove files that previously existed instead of deleting the entire directory, so you could technically output into some sort of pre-existing directory as long as you are careful.
