### ISSUE TITLE
pub run build_runner fails with unhandled exception

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#776]
```
Unhandled exception:
Could not find an option named "assume-tty".
```

Here is the relevant parts of my `pubspec.yaml`:

```yaml
dev_dependencies:
  build_runner: ^0.7.1
```

**Comment by matanlurey** [comment]
If I specify a command, it seems to work fine.

**Comment by jakemac53** [comment]
Ah ok ya we auto-add that flag but shouldn't if the args are empty

**Comment by jakemac53** [comment]
Went ahead and published, but i noticed this still crashes if you explicitly pass `--help` so reopening this.

**Comment by jakemac53** [comment]
This got fixed in https://github.com/dart-lang/build/pull/794
