### ISSUE TITLE
build_runner doesn't pick up new dependencies

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#777]
For example I added `browser: any`, ran `pub get`.

I had to re-run the `serve` command so that `packages/browser/dart.js` could be found.

**Comment by jakemac53** [comment]
Oh hmm that makes sense actually because the package location actually changed as a result. I guess the best we can do is watch the .packages file and update the package graph or something but that might be difficult.

**Comment by natebosch** [comment]
We could be pessimistic and treat a change to `.packages` like a change to the build script and throw everything away and start from scratch.

It should be possible to update the PackageGraph and end up treating these as add/change events, but I'm not sure it's worth the complexity.

**Comment by jakemac53** [comment]
> We could be pessimistic and treat a change to .packages like a change to the build script and throw everything away and start from scratch.

We can do a more incremental build if you just restart the script though - maybe we just kill the script with a message asking you to restart it?

When running through wrapper scripts we could auto-restart it for you.

**Comment by matanlurey** [comment]
@natebosch:
> We could be pessimistic and treat a change to .packages like a change to the build script and throw everything away and start from scratch.

But you wouldn't do that if you manually restarted the script, right?

@natebosch:
> It should be possible to update the PackageGraph and end up treating these as add/change events ... but I'm not sure it's worth the complexity.

This is one of the things users complained the most about with the current pub/transformers workflow, having to manually restart the serve/watch script. Is it possible to somehow treat the `.packages` as a "required" input that invalidates dependencies?

The way I look at it, we _should_ tackle this, though if the solution is "have a wrapper script do it" I'm OK with that too. But maybe just notifying the user that a restart is required is good enough for the MVP.

**Comment by jakemac53** [comment]
>This is one of the things users complained the most about with the current pub/transformers workflow, having to manually restart the serve/watch script. Is it possible to somehow treat the .packages as a "required" input that invalidates dependencies?

We will be a bit better in many cases because at least we should start up faster, but I agree it isn't ideal.

Handling this in a wrapper script also has the advantage that it can restart the build when the script itself is changed. A restart will always be required in that case unless we attempted to hot reload or something but that seems sketchy and the benefit would be minimal.

**Comment by matanlurey** [comment]
Will this invalidate the entire build? For example if I add the `browser` package, but no other versions change, hypothetically you should be able to keep the cache for everything, right?

@jakemac53:

> A restart will always be required in that case unless we attempted to hot reload or something but that seems sketchy and the benefit would be minimal.

This would be a cool gimmick for developers _of_ builders, but yeah, not necessary today.

**Comment by jakemac53** [comment]
> Will this invalidate the entire build? For example if I add the browser package, but no other versions change, hypothetically you should be able to keep the cache for everything, right?

Now that we are using content hashes it will do an incremental rebuild when you return - assuming the build script was not affected.

**Comment by matanlurey** [comment]
Exciting!

**Comment by jakemac53** [comment]
Actually - the shape of the build need to stay the same as well, so if you are running ddc and add a package dependency it would actually cause the whole thing to be invalidated because of the additional build actions.

**Comment by jakemac53** [comment]
We could do something better here though.

**Comment by natebosch** [comment]
yeah when I say "start from scratch" I mean in the "kill the script and restart it" way.

If no dependencies imported by the build script change we definitely could do something better. I'm just not sure it's worth it... how often do users run `pub get` that it's worth optimizing for that to be seamless?

**Comment by matanlurey** [comment]
When you are starting a new project? Unless you are starting with a template you probably realize you need another dependency at some point :)

**Comment by natebosch** [comment]
True the new project use case will see this happen more often. And it also is likely to be the first time new users see the tools so there could be value in polishing that workflow.

**Comment by matanlurey** [comment]
I think for M0 I'd like to just see "please restart your build script."

For M1+ we can figure out what strategy we want for restarting/reconfiguring the build.
