### ISSUE TITLE
Add pub run build_runner update command?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#778]
Something to just ensure that the build script is up to date, but does nothing else.

This will be useful for CLIs that wrap/delegate and perform a "doctor"-like command.

(Happy to add this, just want a 👍 first)

**Comment by matanlurey** [comment]
Also if this is added, I'd like to make `pub run build_runner` just show commands, and not ensure that the build script is updated. It's a little confusing today because you pass no commands, but some work happens.

**Comment by natebosch** [comment]
I'm not sure we want to to use `update` for this. I think the usage should be rare, so I'm inclined to use a longer command name. How about `pub run build_runner generate-entrypoint`?

I'm in favor of not generating the entrypoint when no command is given, but I'm not sure how we'd implement that. We might need to duplicate knowledge of the `run` commands in the wrapping binary.

**Comment by matanlurey** [comment]
I mean we can even make it a hidden command if you want, meant for other tools, not users:

```bash
$ pub run build_runner ensure-build-script
```

... ?

@natebosch:

> but I'm not sure how we'd implement that

Unless I'm mistaken, can't we just not run `ensureBuild()` unless you choose `test/serve/watch`?

**Comment by natebosch** [comment]
> Unless I'm mistaken, can't we just not run `ensureBuild()` unless you choose `test/serve/watch`?

Skipping the generation is easy :) I'm only worried about printing the help string.

The code that runs `ensureBuild()` doesn't use the same arg parsing logic as the code that actually does the build. I suppose though that we can just refer to the arg parser that the generated script would use.

**Comment by jakemac53** [comment]
@matanlurey I am curious what is the primary motivation behind this request? I am not sure what the value is of just creating the build script itself since we would do that again at the start of any meaningful action anyways.
