### ISSUE TITLE
Add generalized `rootPackageAssetFor` method or equivalent.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#78]
You can't output files in other packages, but it is common to want to output a file which corresponds to a file in another package (maybe its the compiled js file, or a metadata file). Sometimes these files can just be published with that package, but there are a lot of situations where that might not be the ideal case, and it makes sense for the application package to do all the code generation.

My proposed solution is to add the following as methods on `BuildStep` (which has a package graph representation):

``` dart
/// Gives a path corresponding to [original] in the local package.
AssetId rootPackageAssetFor(AssetId original);

// Should this return a Uri or a String?
String assetIdToUri(AssetId id);

// Should this take a Uri or a String for the first arg?
// Relative paths will be relative to [from]. Should this be an optional arg?
AssetId uriToAssetId(String uri, AssetId from); 
```

The `rootPackageAssetFor` method would return a path like `lib/$someSpecialFolder/${original.package}/${original.path}` where `someSpecialFolder` is a special folder name that we decide to reserve for this purpose.

**Comment by jakemac53** [comment]
cc @kegluneq @kevmoo @nex3 @munificent

**Comment by kevmoo** [comment]
Love the general idea. We should discuss...

**Comment by nex3** [comment]
So `rootPackageAssetFor()` actually causes a new asset to be copied over?

**Comment by jakemac53** [comment]
It just gives you an `AssetId`. It should probably be renamed to `rootPackageAssetIdFor`? Or maybe we can come up with something shorter/better.

**Comment by nex3** [comment]
But if it doesn't copy anything over, doesn't that mean the `AssetId` refers to a file that isn't there?

**Comment by jakemac53** [comment]
The asset may or may not exist, this method could be used by the `Builder` which is creating the file to get the `AssetId` for the `Asset` is going to create, or by some later stage to read in that `Asset`.

**Comment by nex3** [comment]
It seems confusing to me that the system would provide a function that canonicalizes a particular location for external packages without providing corresponding infrastructure to actual create those assets.

**Comment by jakemac53** [comment]
It does provide the infrastructure, through `BuildStep#writeAsString`, which takes an `Asset`.

**Comment by jakemac53** [comment]
Maybe a more full example would help, lets say you want to produce a metadata file for all dart files, but you don't want to publish that metadata with each package. You might have a `Builder` with a `build` function that looks something like this:

```dart
Future build(BuildStep buildStep) {
  var metaId = rootPackageAssetFor(buildStep.input.id).addExtension('.meta');
  var metaContents = getMetaFor(buildStep.input.stringContents);
  var metaAsset = new Asset(metaId, metaContents);
  buildStep.writeAsString(metaAsset);
}
```

**Comment by nex3** [comment]
Okay, that makes sense. I think it's fine as long as you're careful to explain that it's just a convention, and provide an example like the one above.

**Comment by jakemac53** [comment]
closing as I don't think we actually need this any more.
