### ISSUE TITLE
Consider representing durations more user-friendly

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#784]
For example instead of `Build: Succeeded after 19644ms with 980 outputs`

➡️ `Build: Succeeded after 19.6s with 980 outputs`

**Comment by jakemac53** [comment]
The heartbeat class uses package:millisecond which is ok but does some bad rounding so we might just want to roll our own thing... (It reports 2 minutes for 90-150 seconds...). We could contribute changes to that package as well though.

**Comment by matanlurey** [comment]
Yeah we could definitely reach out, or roll something very simple if we can't.
