### ISSUE TITLE
publish a 'not here anymore' bump to build_compilers

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#790]
Deprecated, etc.

**Comment by natebosch** [comment]
Will be fixed by https://github.com/dart-lang/build/commit/fe7a3b591e6f4fd372b82e1ee40f2f0bb5b6b1e5

@kevmoo - can I get an LGTM of that commit before I `pub publish`?

**Comment by kevmoo** [comment]
LGTM – one note. Not a biggy, though...

**Comment by natebosch** [comment]
Published, tagged, deleted the branch

https://github.com/dart-lang/build/tree/build_compilers-v0.2.0
