### ISSUE TITLE
Allow configurable root package source whitelist

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#797]
In #666 we hardcoded this. As it turns out `angular` is using a non-whitelisted directory - `test_files`.

We think this is sensible and we want to allow this use case. Question is how:

1. Read the `generate_for` globs (or maybe `sources` globs?) in the `build.yaml` targets section for the root package and automatically whitelist all of them
2. Add a new top level key in `build.yaml` like `source_whitelist` which is a list of Strings (as globs)
   - If we do this should they append to the defaults or override them?
3. Add a command line argument? Something else?

I'm leaning towards option 1. Any thoughts @jakemac53 @matanlurey

**Comment by jakemac53** [comment]
responded in the pr, but I think we should use the full sources for the targets not generate_for - all sources should be readable not just primary inputs for build actions
