### ISSUE TITLE
Add a way of overriding the config for a builder globally 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#817]
Right now you can only do it per target, but you can imagine plenty of scenarios where a global override would be what you want. For instance switching the dev compiler builder from analyzer mode to kernel mode.

We also want this for the command line flags so we will need the general plumbing regardless I think.

**Comment by natebosch** [comment]
What should the config approach be other than command line args? Something in build.yaml?

**Comment by jakemac53** [comment]
I think it should be something in build.yaml, because people will want to have it be something they can save as a permanent setting as well as overriding on the command line. To that end I would also expect the command line args to take precedence.

**Comment by jakemac53** [comment]
We should also probably make the target level config override the global config? I am actually not 100%  sure on that though.

**Comment by natebosch** [comment]
As discussed offline:

We also need to explore how this might interact with the `--config` flag, and whether we should be honoring that flag for `build.<config>.yaml` files from dependencies. For instance if we want to put together a `release` and `debug` mode set of options for `build_web_compilers` - how can we expose that?

**Comment by natebosch** [comment]
This is coming up again for the module granularity.

We want to push to see if we can avoid it but we're still considering it.

**Comment by jakemac53** [comment]
@natebosch this is done now right?

**Comment by natebosch** [comment]
Yes, fixed by https://github.com/dart-lang/build/pull/1561
