### ISSUE TITLE
Remove .packages file hack from the Kernel mode of the DevCompilerBuilder and KernelSummaryBuilder

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#818]
Today we use dart:io directly and create one-off .packages files for each module for each of these builders, which is separate from the shared scratch space. Ideally we would come up with some other solution that didn't require dart:io directly.

One option could be a PackagesFileBuilder which creates a single custom `.packages` file per package. This would need to be output under the lib directory so that it is available for all builds, likely using the placeholder file as the primary input.

**Comment by natebosch** [comment]
Is there a reason we can't create a single `.packages` based on the transitive deps and use that for every action?

**Comment by jakemac53** [comment]
> Is there a reason we can't create a single `.packages` based on the transitive deps and use that for every action?

We don't have access to the package graph in the builder

**Comment by jakemac53** [comment]
Closing, we now create a single package_config.json
