### ISSUE TITLE
`test` command doesn't seem to use the compact reporter

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#821]
See https://github.com/dart-lang/test/issues/749 which looks like the underlying issue.

**Comment by kevmoo** [comment]
ProcessStartMode.INHERIT_STDIO landed in 2.0.0-dev.20 - https://github.com/dart-lang/sdk/commit/6523896c6fb27a7ead2ced038da4d15164d894d4

**Comment by jakemac53** [comment]
wooohooooooo!!!
