### ISSUE TITLE
Add a user exposed way of tracking performance

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#823]
With lazy builds especially it is extremely difficult to track performance in a general way. I think we need to expose to the `Builder` implementors a way of explicitly tracking the things they care about.

I see at least three potential ways this could be exposed:

- Add a method to `BuildStep`.
- Add a top level method similar to `log` which uses an instance of a tracker hanging off the current zone.
- Create a new package which exposes a performance tracker as a `Resource`. It could log performance information in its `dispose` callback. This would have the benefit of separating the details out of the `build` package itself.

**Comment by natebosch** [comment]
> This would have the benefit of separating the details out of the build package itself.

I definitely like the idea of being able to opt in to this separately from the rest of Build and not even be exposed to it otherwise.

**Comment by jakemac53** [comment]
This is done now
