### ISSUE TITLE
resolveSources: Assets not resolvable until next event loop

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#843]
I'm in the process of writing tests in `source_gen`, and hit the following:

```dart
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Increase timeouts on this test which resolves source code and can be slow.
@Timeout.factor(2.0)
import 'dart:async';

import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:build_test/build_test.dart';
import 'package:source_gen/source_gen.dart';
import 'package:test/test.dart';

void main() {
  // Holds the analyzer open until all of the tests complete.
  final doneWithResolver = new Completer<Null>();

  LibraryReader b;

  setUpAll(() async {
    final resolver = await resolveSources(
      {
        'test_lib|lib/a.dart': sourceA,
        'test_lib|lib/b.dart': sourceB,
      },
      (r) => r,
      tearDown: doneWithResolver.future,
    );
    // Some bug in build_test causes the 'libraryFor' statement below to throw
    // saying it is not a dart library source unless we wait for the next event
    // loop. 
    await new Future.delayed(Duration.ZERO);
    b = new LibraryReader(
      await resolver.libraryFor(new AssetId('test_lib', 'lib/b.dart')),
    );
    expect(b.element, isNotNull);
  });

  tearDownAll(doneWithResolver.complete);

  group('top level fields', () {
    List<Element> topLevelFields;

    setUpAll(() {
      topLevelFields = b.element.definingCompilationUnit.topLevelVariables;
    });

    test('should read the prefix of a type', () {
      expect(b.prefixFor(topLevelFields[0]), 'a_prefixed');
    });

    test('should read null when the type is not prefixed', () {
      expect(b.prefixFor(topLevelFields[1]), isNull);
    });
  });
}

const sourceA = r'''
  class A {}
  class B {}
''';

const sourceB = r'''
  import 'a.dart' show B;
  import 'a.dart' as a_prefixed;

  a_prefixed.A topLevelFieldWithPrefix;   // [0]
  B topLevelFieldWithoutPrefix;           // [1]
''';
```

... where a `await new Future.delayed(...)` is required to go forwards. This is probably a bug.

**Comment by matanlurey** [comment]
Ok, figured it out, it's not a timing issue, it's a bug in the implementation:

https://github.com/dart-lang/build/blob/71b79a63e49d98d4aa89c45c389cd6aa56d6e682/build_test/lib/src/resolve_source.dart#L200-L208

Basically, we return the `Resolver` (via `complete`) too early, before all libraries are "built" (added and resolved). My intuition here is to give a `Set<AssetId>` to the builder, and have the builder remove assets it "builds", and once the set is empty, consider the resolver "primed". Thoughts?

@jakemac53 @natebosch

**Comment by matanlurey** [comment]
OK, not that simple. You actually need a different `Resolver` for each input.

That makes the existing:
`typedef FutureOr<T> _ResolverAction<T>(Resolver resolver);`

... less useful. A couple ideas:

1. We restrict the code to get the `Resolver` for only a single library (you specify, defaults to first)
2. We change the code to return some sort of meta-resolver that has all the resolvers you need:

```dart
typedef GetResolver = Resolver Function(AssetId);
```

That would make the API more like this (only for `resolveSources`):

```dart
test() async {
  final getResolver = await resolveSources(...);
  final resolverForLibA = getResolver(assetLibA);
}
```

**Comment by natebosch** [comment]
> 1. We restrict the code to get the `Resolver` for only a single library (you specify, defaults to first)

This SGTM. I'd imagine this is the typical use case anyway.

**Comment by matanlurey** [comment]
I agree. It is easy enough to change to the latter if we really need it later.
