### ISSUE TITLE
Add user-facing documentation

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#848]
We can start scenario based instead of being too technical/deep-dive:

1. How do you start using `build_runner`?
2. How do you compile using DDC?
3. How do you compile using Dart2JS?
4. How do you convert from using `build_runner` on-demand to auto generation (`build.yaml`)?
5. How do you write a builder?
6. How do you convert from using a transformer to a `builder`?
7. How do you use `pub run test` with `build_runner`?
8. How do you use a `build_runner`-based web app with a backend server (for dev)?

Some other ideas that aren't as high priority:

* How to run builders in a CI environment (low resources, etc)
* How to have a `debug` and `release` mode for your builders
* How do you interop with existing build tools (like SASS, external executables on NPM, etc)
* How to debug and profile your builders (with observatory, etc)

**Comment by matanlurey** [comment]
It might make sense to start as markdown files, and then go on webdev.dartlang once solid.

**Comment by natebosch** [comment]
I think we're doing pretty well on this now. There are docs and FAQs and we are expanding them as questions come up.
