### ISSUE TITLE
Too many open files errors on mac

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#857]
We should dial back our max number of open files and see if that resolves the issue, otherwise the issue may be in the analyzer or dartdevc workers.

cc @kwalrath

**Comment by jakemac53** [comment]
Additional ideas here involve checking the `ulimit` on mac before doing builds, and catching these specific errors and dealing with them in a more friendly way.

**Comment by kwalrath** [comment]
The workaround is to increase the limit. Here's what I used on my Mac:

```
ulimit -n 1024
pub run build_runner serve
```

**Comment by natebosch** [comment]
I think the `ulimit -n 1024` fix is temporary - that only applies to the terminal you're running in. I think if you start a new terminal or log out and back in you'll hit this issue again.

https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard
