### ISSUE TITLE
Silent failures from build_runner serve

### ISSUE THREAD

**Issue by nshahan** [dart-lang/build#858]
In the latest version at 71b79a63e49d98d4aa89c45c389cd6aa56d6e682 `build_runner serve` will fail silently. To repro make sure you are using that version and launch a simple web server on localhost:8080. Then try to run `build_runner serve` on a package. It should fail because the port is in use by another process but the failure doesn't log anything to the console.

**Comment by jakemac53** [comment]
You must have an old server hanging around listening on that port, try this: `fuser -k 8080/tcp`.

**Comment by jakemac53** [comment]
Sorry didn't real the comment fully :). Looks like it is an issue with the isolate approach.

**Comment by jakemac53** [comment]
cc @natebosch

**Comment by nshahan** [comment]
Yeah, reverting back to 76216ea2856b0886c44d7288d456a55a547222a7 (right before the isolate change) gets back to the state where a crash stack trace is printed in the console.

**Comment by natebosch** [comment]
does it work as expected when you use `dart .dart_tool/build/entrypoint/build.dart serve` instead of `pub run`?

**Comment by nshahan** [comment]
@natebosch Yes.

**Comment by jakemac53** [comment]
See https://api.dartlang.org/stable/1.24.3/dart-isolate/Isolate/errors.html?

**Comment by natebosch** [comment]
Fixed by #860
