### ISSUE TITLE
Allow specifying a different build.yaml

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#881]
Related to https://github.com/dart-lang/build/issues/801.

`$ pub run build_runner:build --config build.prod.yaml`

> @matanlurey: Would be really nice to have a dev (DDC mode) with certain flags, and a prod (Dart2JS) with others.

/cc @jakemac53

**Comment by natebosch** [comment]
This would be pretty straightforward to plumb through. I don't see any reason not to support it.

**Comment by natebosch** [comment]
What do you think of `--config <name>` implying `build.<name>.yaml`?

**Comment by natebosch** [comment]
hmm, this pattern would conflict if there was a package named `prod`.

We already support having files like `build.angular.yaml` which overrides whatever `build.yaml` file was published with angular...

**Comment by matanlurey** [comment]
> What do you think of `--config <name>` implying `build.<name>.yaml`?

LGTM.

> hmm, this pattern would conflict if there was a package named `prod`.

Can we maybe changed that then? I imagine overrides are rarer. For example:

`--config-override=angular:build.angular.yaml`

(Or better)

**Comment by natebosch** [comment]
Ah I was wrong, we support `angular.build.yaml` as it is, so these can both be allowed.

Though I think our overrides support is broken today...
