### ISSUE TITLE
Issue with build/watch on Windows

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/build#887]
Please see issue filed against built_value here:

https://github.com/google/built_value.dart/issues/331 

The build runner is failing to find a file, so it always does a full rebuild.

Any ideas, please?

**Comment by jakemac53** [comment]
I think this is because of an old version of build_runner, see https://github.com/dart-lang/build/issues/651.

**Comment by jakemac53** [comment]
@davidmorgan if you are going to be at dart conf we meet at some point and upgrade built_value to the latest and greatest? There have been a lot of recent features, namely you can set it up such that your users don't have to write a build.dart file any more, or actually do any config whatsoever (similar to the uber generator approach).

**Comment by davidmorgan** [comment]
Sadly not, but I will have a go at switching anyway. Actually I already have an issue open :)

https://github.com/google/built_value.dart/issues/311

Thanks!

**Comment by jakemac53** [comment]
Ok sounds good, the docs on this part are still quite lacking so you can ask questions directly if you hit roadblocks. You can look at [json_serializable](https://github.com/dart-lang/json_serializable/blob/master/json_serializable/build.yaml) as an example.

**Comment by davidmorgan** [comment]
Will do, thanks!

**Comment by matanlurey** [comment]
@davidmorgan please re-open if you need any more assistance after upgrading.

**Comment by davidmorgan** [comment]
@jakemac53 

Me again :) ... so I've been looking into build.yaml. It looks like I probably want "auto_apply: dependents", like the json_serializable example:

https://github.com/dart-lang/json_serializable/blob/master/json_serializable/build.yaml 

But, what I need is for `package:built_value` to trigger the generator under `package:built_value_generator`. Is this possible, please?

If I understand correctly I would add a `built.yaml` file to `package:built_value`, and in that, the `target` needs to be `package:built_value_generator` ... but it's not clear how to do that?

The intended effect is that when you add a dep on `built_value`, the builder from `built_value_generator` will run.

Thanks!

**Comment by jakemac53** [comment]
You should be able to add a `builders` section to your built_value package and provide an import to the other package, at least today that would be the easiest way.

**Comment by jakemac53** [comment]
You should be able to reference `built_value_generator` as the target as well, that is only required for bazel anyways.

**Comment by davidmorgan** [comment]
I'll give it a try. Unfortunately it looks like I need to make code_builder work with built_value v5 first. This is rather tricky as it turns out ...

https://github.com/dart-lang/code_builder/issues/191

**Comment by davidmorgan** [comment]
I'll close this (again) for now, will re-open if I get stuck again. Thanks :)

**Comment by davidmorgan** [comment]
I have built_value working locally with build_runner now ... one (hopefully) last question, please.

I'm wiring things up via ` build.yaml` file in `built_value`:

https://github.com/google/built_value.dart/pull/342/files#diff-c38a034ddd5c70d971bdb8cf447353dd

This depends on the generator in `built_value_generator`. If I try to use `built_value` from another package without also adding a `dev_dependencies` on `built_value_generator`, then `build_runner` fails with:

```
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
Could not import "package:built_value_generator/builder.dart" from "file:///usr/local/google/home/davidmorgan/git/built-value-dart/built_value_test/.dart_tool/build/entrypoint/build.dart": Failure getting http://localhost:34381/packages/built_value_generator/builder.dart:
```

which makes sense--it can't find the builder because there is no dev dependency on it--but I wonder if there is a better way to do this?

It would be ideal if the `built_value_generator` dev dependency could somehow be picked up via the `built_value` dependency. (But I don't think it works like that...)

Failing that, would it be possible for `build_runner` to give a more helpful error message if this happens?

Thanks!

**Comment by jakemac53** [comment]
> It would be ideal if the built_value_generator dev dependency could somehow be picked up via the built_value dependency. (But I don't think it works like that...)

Yes the only way to do that would be to add it to the normal deps of built_value.

With these `build_to: source` builders you would ideally avoid adding a real dependency on the actual builder package, so that consumers of packages that use `built_value` wouldn't pick up those dependencies (they may not even need to run any codegen). The only way to make that happen today would be if they have an explicit dev_dependency on built_value_generator in each the packages that intend to do codegen - which also effectively means you might as well move the build.yaml to that package.

**Comment by natebosch** [comment]
> Failing that, would it be possible for `build_runner` to give a more helpful error message if this happens?

Not easily, but this is an interesting use case that we might be able to improve in the future. #961

**Comment by matanlurey** [comment]
Closing in favor of the more general https://github.com/dart-lang/build/issues/961.
