### ISSUE TITLE
Split out `BuilderApplications` list from the rest of build.dart

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#888]
This could make it possible to automatically generate the actions from config, but then let the user write a manual file with the parts that are less config driven.

Would we need a way to dump this to `tool/` instead of `.dart_tool/`?

What would the user workflow look like? Just one command to generate this then they don't `pub run build_runner` again?

How would we warn about the downsides of having separate build.dart and serve.dart files?

**Comment by jakemac53** [comment]
> Would we need a way to dump this to tool/ instead of .dart_tool/?

I don't think we would need/want to do that, we would want to keep it up to date when your dependencies or targets change.

> What would the user workflow look like? Just one command to generate this then they don't pub run build_runner again?

Going with my logic above we would still want users to go through build_runner to keep their app up to date.

**Comment by natebosch** [comment]
So perhaps a workflow like:

`pub run build_runner run-custom tool/build.dart`

Would we need to ask them to write a strange-looking import?

`import '../.dart_tool/build/entrypoint/builders.dart';`

**Comment by jakemac53** [comment]
> Would we need to ask them to write a strange-looking import?

We could make a special package `$generated` or something that is an alias for that. If we are forcing people to go through a special command anyways we can also create a custom .packages file that knows where to look for that.

**Comment by jakemac53** [comment]
@natebosch I think we should consider closing this as it hasn't come back up and its been >6 months, wdyt?

**Comment by jakemac53** [comment]
Also we do have better support for custom builders with package-relative import paths now

**Comment by natebosch** [comment]
yeah I think this will be easy enough to do if we find a new motivation for it, but no use keeping an issue open since we don't have immediate plans.
