### ISSUE TITLE
A better "-v" verbosity for build_runner

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#889]
I'm trying to debug build performance on a smaller package, `angular_test`.

Cold build performance hovers around ~30s on my Macbook Pro, so I ran with `-v`:

```
INFO] ensureBuildScript: Generating build script completed, took 345ms
[INFO] BuildDefinition: Initializing inputs
[INFO] BuildDefinition: Reading cached asset graph...
[INFO] BuildDefinition: Reading cached asset graph completed, took 339ms

[INFO] BuildDefinition: Checking for updates since last build...
[INFO] BuildDefinition: Checking for updates since last build completed, took 476ms

[WARNING] BuildDefinition: Invalidating asset graph due to build script update
[INFO] BuildDefinition: Building new asset graph...
[INFO] BuildDefinition: Building new asset graph completed, took 494ms

[INFO] BuildDefinition: Checking for unexpected pre-existing outputs....
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 1ms
```

```
[INFO] Build: Running build...
[FINE] Instance of 'LibraryBuilder' on angular|lib/angular.dart: Running [TemplateGenerator] for angular|lib/angular.dart
[FINER] Instance of 'LibraryBuilder' on angular|lib/angular.dart: Running TemplateGenerator for angular|lib/angular.dart
[FINE] Instance of 'LibraryBuilder' on angular|lib/angular.dart: [findComponents] took 1 ms on angular|lib/angular.dart
```

... lines above out 1000 more times ...

```
[INFO] Heartbeat: ... still running (16.0s so far)
[INFO] Heartbeat: ... still running (21.0s so far)
[INFO] Heartbeat: ... still running (28.7s so far)
[INFO] Heartbeat: ... still running (33.7s so far)
[INFO] Build: Running build completed, took 34.5s

[INFO] Build: Caching finalized dependency graph...
[INFO] Build: Caching finalized dependency graph completed, took 158ms

[INFO] Build: Succeeded after 34.8s with 2258 outputs
```

A couple issues (can file separate if needed):

* [ ] My build took 34.5s, but I don't see any action that even took 1s above
* [ ] Majority of the log is non-useful information (`Instance of ... took 1ms on ...`)

From the perspective of a builder _provider_ (i.e. AngularDart) I want to know...

* How long _my_ builder is impacting the build (versus analyzer, ddc, etc)
* If I'm on the critical path, or not

From the perspective of a user, I want to know ...

* Why is my build so slow
* Will my build get 10x slower if my project gets 10x bigger
* Is there ways I could organize my package(s) to get faster builds/better incremental builds

**Comment by jakemac53** [comment]
It seems like this was a mostly performance related ask - we do now have the `--track-performance` flag and in serve mode a UI to view that. As well as specific performance tracking apis for builders.
