### ISSUE TITLE
Silly: Consider a default favicon.ico if missing/404

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#892]
Most consoles will 404 without this, and we could use the opportunity to show a logo.

**Comment by natebosch** [comment]
@matanlurey - do you know if there are other development servers have this kind of behavior?

@jakemac53 is concerned that by masking a problem in development it could cause some users to overlook until it hits production...

**Comment by matanlurey** [comment]
Sure, lots of Java frameworks (Play Framework, etc) have this approach.

**Comment by jakemac53** [comment]
how about we just serve a favicon that looks exactly like what you would get if you have no favicon :P
