### ISSUE TITLE
Watch is watching the .build_tool folder?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#893]
For example, I see this when running `-v`:

```
Watch: Got modify event for "asset:web_hello_world/.dart_tool/build/d9d0eaec453f092c5191075c5eae4ab9/asset_graph.json
```

False alarm?

**Comment by matanlurey** [comment]
On a semi-related note, it looks like `asset_graph.json` is written more often than it changes?

**Comment by natebosch** [comment]
It's watching the root of the directory, then we filter out changes to files we don't care about. That we we only need one watcher, not one for each top-level file/directory.

> On a semi-related note, it looks like `asset_graph.json` is written more often than it changes?

Yes, we write it once per build, even if the build was a no-op

**Comment by matanlurey** [comment]
Anything actionable here then? Should I just close?

**Comment by natebosch** [comment]
We could potentially eliminate writes to `asset_graph.json` when it's identical, but I think those are cheap enough that it doesn't matter for now. If and when we get to the point where we've eliminated other overhead that happens in all cases we can revisit the overhead in these edge cases.
