### ISSUE TITLE
Getting Workiva/OverReact on Build Runner

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#897]
We spoke to @greglittlefield-wf at DartConf, and we wanted to start this working issue.

Things to cover:

1. Examples of how `OverReact` uses transformers today.
2. Examples of how `OverReact` relies on same-file transformations
3. Potential workarounds to use `package:build` and `build_runner`, instead.

/cc @natebosch @jakemac53.

**Comment by jakemac53** [comment]
Some basic docs from @greglittlefield-wf https://github.com/Workiva/over_react/blob/master/lib/src/transformer/README.md#overreact-transformer

**Comment by matanlurey** [comment]
Started some working documents here:
https://github.com/dart-lang/build/blob/master/docs/transforming_code.md

**Comment by matanlurey** [comment]
Hey @greglittlefield-wf, have you had any time to consider options here?

**Comment by greglittlefield-wf** [comment]
Hey @matanlurey, I've been thinking about it in the back of my mind, but haven't had a chance to dig in to the code yet, sorry! I'll try to do that this week and get back to you

**Comment by matanlurey** [comment]
Hey @greglittlefield-wf thanks for the writeup!

One idea, if you used redirecting factory constructors it could work:

```dart
@Props()
abstract class FooProps extends UiProps { 
  factory PooProps() = _$FooProps;

  String foo;
}

// .g.dart
class _$FooProps implements FooProps {
  // ...
}
```

/cc @natebosch

**Comment by jakemac53** [comment]
Another thing that you can do, which is a bit of an anti-pattern according to some but might help the mixin case, is actually generate the public `FooProps` class, and make implementors write the `_$FooProps` abstract class:

```dart
@Props()
abstract class _$FooProps implements UiProps { 
  String foo;
}

// .g.dart
class FooProps extends UiProps implements _$FooProps {
  // ...
}
```

That requires less boilerplate for the user (no mention of generated classes, no redirecting factory constructor), but they do have to follow a specific naming convention. For consumers I believe it means they can just mixin/extend the `FooProps` class, but if they navigate to it they will be in a generated file. I know some people don't like that aspect of it, but I don't personally see it as being a huge issue.

**Comment by greglittlefield-wf** [comment]
@matanlurey Yeah, those are definitely on the table!

With out current setup, though, we probably wouldn't need to add redirecting factory constructors, since we only allow instantiation of those classes under the hood.

```dart
UiFactory<FooProps> Foo = $Foo;
@Props()
abstract class FooProps extends UiProps { 
  String foo;
}

// .g.dart
FooProps $Foo() => new $FooPropsImpl();

// usage
render() {
  FooProps builder = Foo();
  new FooProps(); // this was never allowed, and threw a runtime exception
}
```

**Comment by greglittlefield-wf** [comment]
@jakemac53 Ooh, interesting, I hadn't thought about doing it "backwards" like that... I'll definitely explore that idea, thanks!

That `implements` may result in this dart2js issue https://github.com/dart-lang/sdk/issues/14729, but maybe not. Either way, hopefully it gets fixed at some point 😄.

**Comment by matanlurey** [comment]
Ah I like that too.

re: https://github.com/dart-lang/sdk/issues/14729, I believe it is an error in Dart2 now.

**Comment by corwinsheahan-wf** [comment]
@matanlurey OverReact 2.0.0 has been released which converts the previous transformer functionality to a builder and is Dart 2 compatible. This issue can now be closed. Many thanks from all of us at Workiva for the help!

**Comment by natebosch** [comment]
Happy to hear its working!
