### ISSUE TITLE
Push a release for the stable Dart SDK that ...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#908]
... notifies that using `pub run build_runner` requires Dart 2.0+A newer version.

We could link to a `.md` file on this repo.

The rationale here is folks from the conference not yet on a `dev` SDK will try to reproduce the commands and get frustrated when pub says there is no executable not understanding they need a new version of the SDK and the package.

Thoughts? @natebosch @jakemac53 @kevmoo

**Comment by kevmoo** [comment]
Could work in theory. We'd have to do something weird...like release `0.6.9+fyi` or something...

**Comment by matanlurey** [comment]
Yeah, that's reasonable, I think.

**Comment by jakemac53** [comment]
closed by https://github.com/dart-lang/build/pull/954
