### ISSUE TITLE
build_runner test "compiles" for 12 min and then times out

### ISSUE THREAD

**Issue by chalin** [dart-lang/build#912]
As shown by [this Travis log](https://travis-ci.org/dart-lang/site-webdev/jobs/333770755), an attempt at running `pub run build_runner test --delete-conflicting-outputs --output=build -- -p chrome` results in 12 minutes of an attempt at compiling the `test/app_test.dart` and then a timeout.

The code being run is this version of the [toh-0 example](https://github.com/dart-lang/site-webdev/tree/chalin-upgrade-build-runner-0126/examples/ng/doc/toh-0).

cc @kwalrath

**Comment by jakemac53** [comment]
Fwiw it isn't actually compiling (the compile is already done before that point), something else is going on.

**Comment by jakemac53** [comment]
Btw we do create those *.debug.html files now if you want to try running it manually and see if there is a loading exception or something like that - or I can try next week

**Comment by chalin** [comment]
> Fwiw it isn't actually compiling (the compile is already done before that point), something else is going on.

Yeah, that is why I put "compiles" in quotes :).

> Btw we do create those *.debug.html files now ...

Taking a look now.

**Comment by chalin** [comment]
FYI, the tests run fine when I compile using `dart2js`.

**Comment by chalin** [comment]
Tests run fine manually (regardless of the web compiler I use), ... so does that mean that `angular_test` is the source of the problem? If so, should I reopen this issue over `angular_test`?

**Comment by matanlurey** [comment]
Tests run fine with `.debug.html`? We haven't changed `angular_test` in a while.

It is more likely a `pkg/test` (runner) issue than anything to do with `angular_test`.

**Comment by natebosch** [comment]
I think there are cases where even if we pass `--precompiled` the test package will try to compile anyway. I think they have to do with missing some files. @jakemac53 - do you remember the details?

**Comment by chalin** [comment]
FYI, the problem appeared with I did the following update to the example pubspec.yaml files:

<img width="376" alt="screen shot 2018-01-26 at 14 40 59" src="https://user-images.githubusercontent.com/4140793/35457449-fcc3ccbc-02a6-11e8-9210-eccf00e63fca.png">

I don't know if that can give a clue.

**Comment by matanlurey** [comment]
I'm marking as a bug of `build_web_compilers`, but it might be something else.

**Comment by matanlurey** [comment]
Is this still an issue?

**Comment by jakemac53** [comment]
Got things working here https://github.com/dart-lang/site-webdev/pull/1306. Note that I also did the manual bootstrapping, because I updated to the latest angular... not sure if that was the problem.

**Comment by jakemac53** [comment]
Closing this for now - you should be able to load up the `*.debug.html` file to test it out and see the real errors (that is how I diagnosed the issues).

**Comment by chalin** [comment]
Thanks @jakemac53. I'll check out #1306 now.
