### ISSUE TITLE
Request: Synchronous logging interface

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#914]
Forked from https://github.com/dart-lang/build/issues/759.

I'd like to see a simplified logging interface that better matches user intention, *and* is synchronous (unlike `package:logging`), which will make many things more trivial and understandable, especially around testing and failing on severe.

```dart
abstract class BuildLogger {
  void info(String message, [...]);
  void warn(String message, [Object exception, StackTrace trace]);
  void error(String message, [...]);
}
```

Other ideas:
* Do we need something like `.debug` or `.fine`?
* Should we add performance tracing here too (`.trace` and `.traceAsync`?)

**Comment by natebosch** [comment]
`.trace` could tie in with #823 

Is there value in designing something that can be used outside of the build ecosystem as well?

**Comment by matanlurey** [comment]
Probably, but personally I'd rather slow our roll of trying to fix everything.

(There isn't much importance for CLI-based logging outside of the Dart team itself)

**Comment by jakemac53** [comment]
@matanlurey I did update it so that we synchronously capture severe logs (just wrapping the logger). Do you think that is enough or is there still value in this from your perspective?

**Comment by matanlurey** [comment]
Value? Yes. Priority? No.
