### ISSUE TITLE
Generate source maps with build_web_compilers

### ISSUE THREAD

**Issue by eredo** [dart-lang/build#916]
The `build_web_compilers` should also generate source map files. The `.ddc.js` output files contain the reference to a `.ddc.js.map` file but the files are not generated.

The verbose logging shows that `.js.map` files are generated. However it looks like they are not persisted to disk and chrome doesn't recognise them in regular stack logging.

**Comment by jakemac53** [comment]
I see the sourcemaps for e2e_example, and they are working in chrome. Can you confirm you have js sourcemaps enabled in devtools (enable javascript sourcemaps under dev tools settings)?

**Comment by matanlurey** [comment]
I've seen a few people murmur about this on Gitter. We need more information.

@eredo Could you provide:

1. What version of `build_runner` and `build_web_compilers` is being used?
2. What operating system and version?
3. What version of the Dart SDK? (`dart --version`)
4. An example terminal output that shows `.js.map` files being generated
5. An example of on-disk missing files
6. An example of Chrome failing to fetch the files

That will help greatly in debugging this.

**Comment by eredo** [comment]
After doing some further digging, I realised that Intellij simply hides the source map. So the files do exist, sorry! But the chrome console output doesn't contain the proper source location in the exception. Is there maybe some extra work necessary? Source maps are activated in the chrome developer tools settings.
Setting up a break point in the `.dart` file actually works, so I assume loading of the source maps works as expected.

Example project: https://github.com/eredo/poc_angulardart_subapps
Example component:

```dart
import 'package:angular/angular.dart';

@Component(
  selector: 'stack-trace',
  template: '<button (click)="throwIt()">Throw exception</button>',
)
class StackTraceComponent {
  void throwIt() => throw new Exception('this is a test exception.');
}
```

I'm adding the details @matanlurey asked for, in case anybody else is having the originally assumed issue.
Dependencies:

```
build 0.12.0
build_barback 0.5.0+2
build_config 0.2.2+1
build_runner 0.7.8
build_test 0.10.0
build_web_compilers 0.2.1
```

OS: `MacOS 10.13.2`
Dart SDK: `Dart VM version: 2.0.0-dev.19.0 (Fri Jan 19 08:01:12 2018 +0100) on "macos_x64"`
Output directory in `.dart_tool/generated/...`:

```
-rw-r--r--   1 user  group   1794 Jan 29 19:30 stack_trace_component.ddc.js
-rw-r--r--   1 user  group    154 Jan 29 19:30 stack_trace_component.ddc.js.map
-rw-r--r--   1 user  group   6500 Jan 29 19:30 stack_trace_component.linked.sum
-rw-r--r--   1 user  group    244 Jan 29 19:30 stack_trace_component.module
-rw-r--r--   1 user  group      0 Jan 29 19:30 stack_trace_component.ng_placeholder
-rw-r--r--   1 user  group   4168 Jan 29 19:30 stack_trace_component.template.dart
-rw-r--r--   1 user  group  14129 Jan 29 19:30 stack_trace_component.template.ddc.js
-rw-r--r--   1 user  group   1256 Jan 29 19:30 stack_trace_component.template.ddc.js.map
-rw-r--r--   1 user  group  11948 Jan 29 19:30 stack_trace_component.template.linked.sum
-rw-r--r--   1 user  group    700 Jan 29 19:30 stack_trace_component.template.module
-rw-r--r--   1 user  group   4368 Jan 29 19:30 stack_trace_component.template.unlinked.sum
-rw-r--r--   1 user  group    832 Jan 29 19:30 stack_trace_component.unlinked.sum
```

**Exception in chrome:**

```
dart_sdk.js:63799 EXCEPTION: Exception: this is a test exception.
STACKTRACE: 
package:$sdk/dev_compiler/amd/dart:_runtime/operations.dart 626:20                                       throw
package:poc_angulardart_subapps/src/components/stack_trace_component/stack_trace_component.ddc.js 10:24  throwIt
package:$sdk/dev_compiler/amd/dart:async/zone.dart 1131:12                                               _rootRun
package:$sdk/dev_compiler/amd/dart:async/zone.dart 713:12                                                run
package:angular/src/core/zone/ng_zone.ddc.js 101:23                                                      [_run]
package:$sdk/dev_compiler/amd/dart:async/zone.dart 1023:12                                               run
package:$sdk/dev_compiler/amd/dart:async/zone.dart 925:7                                                 runGuarded
package:angular/src/core/zone/ng_zone.ddc.js 203:31                                                      runGuarded
package:angular/src/core/linker/app_view.ddc.js 950:81                                                   event

ORIGINAL EXCEPTION: Exception: this is a test exception.
```

**Expected output:**

```
...
package:poc_angulardart_subapps/src/components/stack_trace_component/stack_trace_component.dart 8:21  throwIt
...
```

**Comment by matanlurey** [comment]
Thanks. This indeed looks like a bug, though I'll let @jakemac53 @natebosch figure out where.

**Comment by jakemac53** [comment]
I am going to start trying to dive into this and see how far I can get

**Comment by jakemac53** [comment]
Ok, with the next sdk dev release this should be fixed fully.

With my latest fix it is almost fully fixed, except that `dart:` things will look like `package:$sdk/some/internal/path/dart:blah.dart` which isn't exactly ideal :).
