### ISSUE TITLE
Bug when moving from manual build.dart --> build.yaml

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#920]
In `code_builder`, I currently have checked-in `.g.dart` files from before.

I got everything working (sort of) with #919, but `pub run build_runner build` results in...

> [INFO] Build: Succeeded after 51ms with 0 outputs

Sort of suspicious. There isn't a good way for me to "clear" the previous builds.

I tried to manually delete one file, `lib/src/specs/class.g.dart`, and then re-build, and hit:

```
Unable to spawn isolate: Unhandled exception:
Could not import "package:code_builder/src/specs/class.g.dart" from "package:code_builder/src/specs/class.dart": Failure getting http://localhost:52858/packages/code_builder/src/specs/class.g.dart:
  404 Not Found
null
```

Pretty scary. Here is my generated `build.dart` file:

```dart
import 'package:build_runner/build_runner.dart' as _i1;
import '../../../tool/src/builder.dart' as _i2;

final _builders = [
  _i1.apply('code_builder|_built_value', [_i2.builtValueBuilder],
      _i1.toNoneByDefault(),
      hideOutput: false)
];
main(List<String> args) => _i1.run(args, _builders);
```

Where `builder.dart` is:

```dart
import 'package:build/build.dart';
import 'package:built_value_generator/built_value_generator.dart';
import 'package:source_gen/source_gen.dart';

/// Returns a [Builder] to generate `.g.dart` files for `built_value`.
Builder builtValueBuilder(BuilderOptions _) {
  return new PartBuilder([
    const BuiltValueGenerator(),
  ]);
}
```

**Comment by natebosch** [comment]
Hmm, I think this points to the new build graph not thinking it would need to output these files.

Can you try something like

```sh
$ pub run build_runner:graph_inspector .dart_tool/build/entrypoint/build.dart
> inspect lib/src/specs/class.g.dart
```

We want to see it tell us that it's a generated asset, not a source asset

**Comment by jakemac53** [comment]
I noticed in the build.yaml this:

```yaml
targets:
  $default:
    builders:
      _built_value:
```

The builder key there actually gets normalized to `_built_value|_built_value`. If you start with a leading `|` that would refer to the one in your package.

It seems like a bug that we are erroring in some form on this non-existent builder.

**Comment by matanlurey** [comment]
@natebosch:

```
Asset: lib/src/specs/class.g.dart
  type: SourceAssetNode
```

@jakemac53:

I see. I tried:

```yaml
targets:
  $default:
    builders:
      |_built_value:
``` 

... and it works 🎆  but then I tried manually deleting `.g.dart` files again and get

```
pub run build_runner build
Unable to spawn isolate: Unhandled exception:
Could not import "package:code_builder/src/specs/class.g.dart" from "package:code_builder/src/specs/class.dart": Failure getting http://localhost:53687/packages/code_builder/src/specs/class.g.dart:
  404 Not Found
null
```

... so something bad still happens.

**Comment by matanlurey** [comment]
And even if I delete `.dart_tool`, I still get the above error ^

**Comment by natebosch** [comment]
@matanlurey  - does the `|_built_value` change also turn the node into a generated node?

**Comment by matanlurey** [comment]
Yup!

```
Asset: lib/src/specs/class.g.dart
  type: GeneratedAssetNode
  needsUpdate: false
  wasOutput: true
```

**Comment by natebosch** [comment]
Ah, so I think what is happening here is that you are generating in a package that also exposes a builder, and we always generate the code in `build.dart` to import the builder even if it won't get used.

This could be tricky...

Maybe we could add some checks during `buildScriptGenerate` to avoid generating code (imports really) for unused builders?

**Comment by natebosch** [comment]
Hmm, looking at your generated entrypoint that isn't the case - it isn't importing anything in `package:code_builder`... Is there a package cycle? Does one of those other imports transitively import this part file?

**Comment by natebosch** [comment]
Ahh, we import `code_builder` from `build_runner`, and if you're running with a local version of build_runner you're getting https://github.com/dart-lang/build/pull/891 which means that the normal import transitively imports stuff from code_builder.

If you're running from a hosted version I wouldn't think we'd have an import reachable from `build_runner.dart` but we might.

I think anything in the transitive imports of `build_runner.dart` is going to have similar difficulties.

**Comment by matanlurey** [comment]
@natebosch Should I try again? A little confused how to move forward (I could create a PR)

**Comment by natebosch** [comment]
yeah, try with build_runner 0.7.9 and see if you still run in to this problem.

You will probably need to *not* delete any files before running `pub run build_runner build`, and if you get into a situation where you do need to delete files you'll need to use `dart .dart_tool/build/entrypoing/build.dart build` instead of `pub run`

**Comment by matanlurey** [comment]
Great, looks like it works fine now!
