### ISSUE TITLE
"pub run build_runner watch --output build" error on file change

### ISSUE THREAD

**Issue by Meai** [dart-lang/build#927]
Code uses the repo: https://github.com/dart-lang/sample-pop_pop_win
I just run `pub run build_runner watch --output build` and then change some string in a `print("hi")` that I inserted in pop_pop_win.dart and it errors out immediately, both Linux and Windows. 
build_runner version 0.8.7

```
[pc@localhost sample-pop_pop_win]$ pub run build_runner watch --output build
[INFO] Entrypoint: Generating build script completed, took 424ms
[INFO] Watch: Setting up file watchers completed, took 29ms
[INFO] Watch: Waiting for all file watchers to be ready completed, took 87ms
[INFO] BuildDefinition: Reading cached asset graph completed, took 285ms
[INFO] BuildDefinition: Checking for updates since last build completed, took 671ms
[WARNING] BuildDefinition: Invalidating asset graph due to build script update
[INFO] BuildDefinition: Cleaning up outputs from previous builds. completed, took 96ms
[INFO] BuildDefinition: Building new asset graph completed, took 707ms
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Build: Running build completed, took 33.8s
[INFO] Build: Caching finalized dependency graph completed, took 117ms
[INFO] CreateOutputDir: Creating merged output dir `build` completed, took 2.0s
[INFO] Build: Succeeded after 36.0s with 1202 outputs

[INFO] Watch: Starting Build
[INFO] Build: Updating asset graph completed, took 3ms
[INFO] Build: Running build completed, took 275ms
[INFO] Build: Caching finalized dependency graph completed, took 65ms
[INFO] CreateOutputDir: Deleting existing output dir `build` completed, took 140ms
[INFO] CreateOutputDir: Creating merged output dir `build`...AssetNotFoundException: pop_pop_win|lib/.goutputstream-35KRDZ
#0      _fileForOrThrow.<anonymous closure> (package:build_runner/src/asset/file_based.dart:133:18)
#1      _RootZone.runUnary (dart:async/zone.dart:1381)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:662)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:112)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

**Comment by jakemac53** [comment]
Looks like there was a transient file which got deleted between the build happening and it trying to write to the output directory.

Here are a couple potential fixes, none of them are very pretty though:

- Ignore all hidden files/folders by default
- Gracefully handle these errors when creating the output directory. This is inherently unsafe but we could warn when we do it.

I would probably lean towards ignoring hidden files entirely... but there may be some that we do in fact care about.

**Comment by matanlurey** [comment]
@jakemac53:

> Ignore all hidden files/folders by default

> Gracefully handle these errors when creating the output directory

... what about a combination of both, that is, gracefully handle hidden files?

**Comment by jakemac53** [comment]
> ... what about a combination of both, that is, gracefully handle hidden files?

Ya that might be a reasonable approach, I think its pretty safe to assume a hidden file which no longer exists was just a swap file or some other transient thing that doesn't actually matter.

My main concern would be we still end up copying extra hidden files to the build dir in a lot of cases (when they do still exist), and it wouldn't be reproducible which ones were getting copied.

**Comment by Meai** [comment]
On windows I get an additional error btw:

![windows error](https://user-images.githubusercontent.com/649922/35582105-0dca8c54-05ee-11e8-953b-7c2bbe1099e0.png)

**Comment by matanlurey** [comment]
@Meai This is with `--output`, right?

**Comment by Meai** [comment]
yeah, same exact command

**Comment by jakemac53** [comment]
> On windows I get an additional error btw:

Ah ya I think this is because there is a process running in that directory (are you running a server in there?). If so then I don't think windows will let you delete the directory.

We probably need to just delete the contents of the directory instead... although I think that will end up being much slower. Will need to look into what the correct thing to do here is for windows.

**Comment by Meai** [comment]
would be better for linux too, it just killed my `python3 -m http.server` off right under my nose on a watch edit cycle

**Comment by matanlurey** [comment]
I think one of the main uses of `-o` will end up being to run a server, FWIW.

**Comment by natebosch** [comment]
As an FYI a server which only reads from the filesystem without adding new capabilities (like `python -m http.server`) adds no value over the server that comes with `pub run build_runner serve` and will give a worse UX. The built-in serve blocks requests while builds are happening which makes it harder to get an inconsistent load (where assets come from different instances of the build and don't work together) and won't require you to reload multiple times after a change.

If you need extra capabilities beyond what the dev server provides we recommend a proxy rather than serving form the output directory with a `watch`.

That said, it is a use case we'd like to work, just not one we recommend.
