### ISSUE TITLE
Move bazel_codegen to this repository

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#931]
Just thinking out loud, might not make any sense, but maybe it does make sense :)

Sub-issues:
* [x] Move the package as-is (no changes), include in travis (w/ tests).
* [x] Add a README.md, upgrade the pubspec dependencies.
* [ ] Optional: Add some e2e-ish test coverage (if needed).
* [ ] Optional: Rename to `build_bazel`?

**Comment by jakemac53** [comment]
Probably? Not a super high priority but I don't see why not.

**Comment by matanlurey** [comment]
Sure, just to be clear, this is to help with future breaking changes, not to be annoying :)

**Comment by matanlurey** [comment]
@natebosch WDUT re: tests/rename? I can dump if its just not useful.

(At minimum we are getting analyzer coverage - still a good thing)

**Comment by natebosch** [comment]
I think the rename is not important. We don't expect any user to see this package directly.

We did have e2e_tests in the other repo... Part of what makes this tough is that this code is tightly coupled to dart-lang/rules_dart

**Comment by matanlurey** [comment]
Not for bazel_codegen, those tests are internal only AFAIK.

Closing this for now as "complete". We can always revisit.
