### ISSUE TITLE
`--dump-info` doesn't seem to work w/ dart2js

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#951]
Here's the content of the log...

`Instance of 'WebEntrypointBuilder' on data_silly|web/main.dart: Running dart2js with --trust-type-annotations --trust-primitives --dump-info --no-frequency-based-minification --minify -ppackages -oweb/main.dart.js web/main.dart`

**Comment by jakemac53** [comment]
Ah, ya I guess we have to special case this one so we know to copy back the extra output.

Do you know if there are any other flags which create extra outputs?

**Comment by jakemac53** [comment]
Or possibly we just handle this the same way we do deferred loading - output an archive file. We would still need to know the pattern to look for to include in the archive though.

**Comment by natebosch** [comment]
Could also consider this another case for #938

**Comment by jakemac53** [comment]
Oh true, I guess you could use that as a way to support deferred loading as well although it would be a bit painful

**Comment by natebosch** [comment]
Yeah for the deferred loading case if we use that approach we'd have to configure each entrypoint to say how many outputs to expect since it still needs to be known statically

**Comment by jakemac53** [comment]
> Yeah for the deferred loading case if we use that approach we'd have to configure each entrypoint to say how many outputs to expect since it still needs to be known statically

Technically, we could just support up to some default number of outputs and allow you to override that, since we can declare outputs we don't emit.

**Comment by matanlurey** [comment]
@jakemac53:

> Technically, we could just support up to some default number of outputs

Sounds scary. I'd prefer to go the archive route unless we just can't pull it off.

(We probably also need an API for outputting an archive)

**Comment by jakemac53** [comment]
closes, https://github.com/dart-lang/build/pull/1107
