### ISSUE TITLE
When logging an error (severe or otherwise) include error and stack w/ call

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#96]
Noticed in `build_impl.dart` you do string formatting on an exception.
1. These calls in `Logger` have positional error, stackTrace args that can be used
2. This call doesn't format things nicely with `stack_trace` – which makes it hard to debug issues.

**Comment by jakemac53** [comment]
pretty sure this was recently fixed by https://github.com/dart-lang/build/pull/133
