### ISSUE TITLE
README.md regarding how to use dart2js with build_web_compilers

### ISSUE THREAD

**Issue by furrary** [dart-lang/build#960]
In the [README.md](https://github.com/dart-lang/build/blob/master/build_web_compilers/README.md#configuration), it demonstrates how to configure the package to use `dart2js`, but not how to actually use it. Few people in https://gitter.im/dart-lang/angular, including me, recently asked about how to compile with `dart2js`.

The doc should add something like
"Save this configuration as `build.prod.yaml` and use it like this `pub run build_runner build --config=prod --output=build`. The output will be in the `build` folder."

**Comment by jakemac53** [comment]
Fwiw, you can also add the flag `--define=build_web_compilers|entrypoint=compiler=dart2js` but that is a little bit wordy :D. Some docs here would definitely be good.
