### ISSUE TITLE
dart2js builds use different defaults than `pub build`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#964]
Adding a `build.yaml` which only sets the compiler to `dart2js` and changes nothing else won't produce the same output as `pub build` does. The flags we're passing to `dart2js` by default must be different. In a small repro the output from build_web_compilers is much bigger.

We should either change our default flags to match pub, or document how they are different and give an example `build.yaml` to make them the same.

**Comment by matanlurey** [comment]
From what I can tell the only obvious missing default is `--minify`.

That should be easy enough to start with?
