### ISSUE TITLE
Figure out what new APIs we'd need to add to support `source_gen` dynamically generating builders to wrap multiple generators

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#975]
It would be nice if packages like `source_gen` could have some hooks to dynamically create Builders which wrap multiple generators so that they can share a single output.

We don't support this internally - instead we hardcode all the generators that are used. Externally this could be supported in bazel because it could happen in the 'init' step. In build_runner it could happen at the step where we generate the build step.

This might not be feasible in practice, since it likely requires two phases of generating and executing scripts in order to run the package provided code.

**Comment by matanlurey** [comment]
Ostensibly builders could write to: `.g.dart.temp-builder1` `.g.dart.temp-build2`, and we could have a concat builder specifically for `source_gen` that knows how to concatenate the results of those builds into the `.g.dart` with the appropriate header. Is it worth the effort is a good follow-up Q.

**Comment by kevmoo** [comment]
I'm hoping the goal here is to generalize this special-case logic within source_gen to a general concept in pkg/build – right?

**Comment by jakemac53** [comment]
> I'm hoping the goal here is to generalize this special-case logic within source_gen to a general concept in pkg/build – right?

Yep, to quote Nate "packages like `source_gen`"

**Comment by matanlurey** [comment]
> ... so that they can share a single output

To be clear, I imagine this will only work (easily) using `part` files. Otherwise it will be _really_ easy to emit invalid code in a standalone file (i.e. imports or symbols that collide). 

So `part` files only, right (or files like that, maybe JSON etc)?

**Comment by jakemac53** [comment]
We talked a bit about this with @davidmorgan last week, and decided the best path forward is probably the separate files approach with a combining builder later on.

This would be essentially a convention based approach, so each source_gen `Generator` would create a `.<unique_extension>.g.part` file (exact extension up to debate), and then `source_gen` would provide a builder which globs for `my_file.*.g.part` files and creates a merged `my_file.g.dart` file, which is the actual part you would import.

The combining builder may actually make sense to exist in some other package, but keeping it in source_gen for now is probably fine.

This has a few nice properties:

- Allows you to see the output of each individual builder if you want
- Works with the existing model for Builders
  - Except for the combining builder which we may want to add an additional feature for, a notion of `requiredBuilders`, which are builders that must run after this builder. This has already been requested for the angular component gallery builder though.
- It is conceptually simple
- Builders of different types can easily coordinate (they don't all have to use the source_gen package even, they just follow the convention for `.g.part` files).

There are a few downsides as well:

- it would be a bit less efficient
  - each build step will be ran on its own, and have its own dependencies and outputs.
  - more nodes in the graph.
- requires an extra builder and/or dependency unless we make the `requiredBuilders` change or similar

**Comment by natebosch** [comment]
We'll need #1010 and #1055 for a decent UX on this.

**Comment by natebosch** [comment]
`source_gen` is now using a combining builder.
