### ISSUE TITLE
Add a newline between log messages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#980]

**Comment by jakemac53** [comment]
@matanlurey while the description sounds very obvious I am nonetheless a little bit confused by exactly what you would like here :rofl:. Could  you give an example of todays logging and what you would like it to look like?

**Comment by matanlurey** [comment]
Sure, it looks something like this:

```
[SEVERE] BAD
[SEVERE] BAD
```

It might make sense to have it print like this:

```
[SEVERE] BAD

[SEVERE] BAD
```

**Comment by jakemac53** [comment]
I think I personally like the existing logging more... @natebosch @kevmoo what do you think?

This also makes overwriting previous info logs a bit more difficult.

**Comment by kevmoo** [comment]
I'm happy w/ what I'm seeing in the output now...

**Comment by matanlurey** [comment]
Maybe I generate many more errors than you folks ;)

**Comment by jakemac53** [comment]
Maybe we should do it just for errors/warnings?

**Comment by natebosch** [comment]
I'd be fine with extra newlines around WARNING or higher

**Comment by matanlurey** [comment]
Eh, not a huge issue. I'll re-open if I have good examples of where this would really help.
