### ISSUE TITLE
Forward build_runner test <args> -> pub run test <args>

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#983]
I.e. this should work:

```bash
$ pub run build_runner test -p firefox
```

**Comment by matanlurey** [comment]
Ah I see you need to do `pub run build_runner test --`

**Comment by jakemac53** [comment]
ya in an ideal world that wouldn't be required but its the easiest way to make a clean separation between build args and test args.

**Comment by natebosch** [comment]
Is there some way for us to improve the error message in this case?
