### ISSUE TITLE
I wish test running was modular/cacheable

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#985]
For example, I have a PR where I removed some unused code in `_test.dart` files (8 to be precise), but the test runner will execute all of the tests again (locally, and on travis). I wish there was a way we could store the test graph and avoid re-running tests that couldn't have changed.

(I realize this is hard, related to https://github.com/dart-lang/build/issues/967, but even worse - we'd have to for example include the `chrome` binary as an external dependency and track if it changes)

**Comment by jakemac53** [comment]
There is also another issue of people depending on external things we can't track in their tests. The simple example is a goldens test.

**Comment by matanlurey** [comment]
I realize we become Bazel at some point, but I guess we could have input globs?

**Comment by jakemac53** [comment]
I think if we could just override what dart:io does that would be ideal, I know there was some talk of that but I don't know if it actually became a thing or not.

That would still require more tight integration with package:test as well though.
