### ISSUE TITLE
Still get prompted even if --delete-conflicting-outputs is used

### ISSUE THREAD

**Issue by chalin** [dart-lang/build#998]
Maybe I'm misunderstanding the intended effect of the option, but isn't `--delete-conflicting-outputs` supposed to suppress the "found existing output directory" prompt? That isn't what I'm seeing anymore:

```nocode
pub run build_runner build --fail-on-severe --delete-conflicting-outputs --output=build
[INFO] Entrypoint: Generating build script completed, took 216ms
[WARNING] BuildDefinition: Throwing away cached asset graph due to version mismatch.
[INFO] BuildDefinition: Reading cached asset graph completed, took 67ms
[INFO] BuildDefinition: Building new asset graph completed, took 580ms
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Build: Running build completed, took 19.4s
[INFO] Build: Caching finalized dependency graph completed, took 103ms

Found existing output directory `build` but no manifest file. Please choose one of the following options:
1 - Skip creating the output directory
2 - Delete the existing directory entirely
3 - Leave the directory in place and write over any existing files
```

Environment: Dart 2-dev.23 on macOS
```
  build 0.12.0+1
  build_runner 0.7.10+1 (was 0.7.9+2)
  build_web_compilers 0.2.1+1 (0.3.0 available)
```

cc @jakemac53 @kwalrath

**Comment by chalin** [comment]
Also, if I choose "2 - Delete the existing directory entirely", the following message says that it is merging output:

```nocode
...
Found existing output directory `build` but no manifest file. Please choose one of the following options:
1 - Skip creating the output directory
2 - Delete the existing directory entirely
3 - Leave the directory in place and write over any existing files
2
[INFO] CreateOutputDir: Creating merged output dir `build` completed, took 2.1s
...
```

If it is deleted entirely, then it shouldn't be merging.

**Comment by jakemac53** [comment]
`--delete-conflicting-outputs` is actually an older flag that existed before you could create outputs at all - it is related to builders that write to your source tree instead of the cache. It will assume any "source" files it sees are previously generated files if you pass that flag.



> Also, if I choose "2 - Delete the existing directory entirely", the following message says that it is merging output:

It did delete the directory, this is just a bad interaction of different messages. By "merged output dir" it means merging your source assets and generated assets together into one dir.

**Comment by chalin** [comment]
> --delete-conflicting-outputs is actually an older flag

Is it still useful to include this flag then?

So what is the recommended way to avoid getting this prompt? (Other than deleting the directory before hand?)

> By "merged output dir" it means merging your source assets and generated assets together into one dir.

Ah, ok.

**Comment by jakemac53** [comment]
> So what is the recommended way to avoid getting this prompt? (Other than deleting the directory before hand?)

In general you shouldn't be getting this prompt except for the first build after you pub upgrade, we added the manifest recently to get around some other issues but have no way of detecting if a previous output directory was in fact created by us.

If you are consistently getting this prompt that is a bug.

**Comment by jakemac53** [comment]
> Is it still useful to include this flag then?

It is still useful yes, for instance its required on travis if you check in your generated to source files (the standard procedure) because otherwise you would get a prompt.

**Comment by jakemac53** [comment]
Closing for now, please re-open if you think there is something to do here
